// @ts-nocheck
export const dynamic="force-dynamic";
import {auth} from "@/lib/auth";
import {redirect} from "next/navigation";
import {db,clients,mediaMetrics,creativeTasks,financeRecords,contacts,salesActivities,salesLeads} from "@/lib/db";
import {eq,and,gte,desc,sum,inArray} from "drizzle-orm";
import {Role} from "@/lib/types";
import {formatCurrency} from "@/lib/utils";
import Link from "next/link";

async function logActivity(clientId:string,fd:FormData){"use server";const session=await auth();if(!session?.user||![Role.SUPER_ADMIN,Role.ACCOUNT_MANAGER].includes((session.user as any).role))throw new Error("Unauthorized");const role=(session.user as any).role,userId=String((session.user as any).id);if(role===Role.ACCOUNT_MANAGER){const [owned]=await db.select({id:clients.id}).from(clients).where(and(eq(clients.id,clientId),eq(clients.accountManagerId,userId),eq(clients.isActive,true))).limit(1);if(!owned)throw new Error("Client access denied");}const [lead]=await db.select({id:salesLeads.id}).from(salesLeads).where(eq(salesLeads.clientId,clientId)).limit(1);await db.insert(salesActivities).values({leadId:lead?.id||clientId,userId,type:String(fd.get("type")||"note"),notes:String(fd.get("notes")||"")||null,outcome:String(fd.get("outcome")||"")||null,nextActionDate:fd.get("nextDate")?new Date(String(fd.get("nextDate"))):null});const {revalidatePath}=await import("next/cache");revalidatePath(`/dashboard/clients/${clientId}`)}

const TYPE_ICON:Record<string,string>={REEL:"🎬",GRAPHIC:"🎨",CAROUSEL:"📊",MOTION_GRAPHIC:"✨",VIDEO_EDIT:"🎥",PHOTO_SESSION:"📸",STORY:"📱",UGC:"👤"};
const STATUS_COLOR:Record<string,string>={PENDING:"#64748b",IN_PROGRESS:"#2563eb",REVIEW:"#f59e0b",APPROVED:"#10b981",REVISION:"#ef4444",COMPLETED:"#059669"};
const isVideo=(url:string,type:string)=>["REEL","VIDEO_EDIT","MOTION_GRAPHIC"].includes(type)||/\.(mp4|mov|webm)(\?|$)/i.test(url||"");

export default async function ClientDetailPage({params}:{params:Promise<{id:string}>}){const session=await auth();if(!session?.user)redirect("/login");const role=(session.user as any).role as Role,userId=String((session.user as any).id);if(![Role.SUPER_ADMIN,Role.ACCOUNT_MANAGER,Role.MEDIA_BUYER,Role.ACCOUNTANT].includes(role))redirect("/dashboard");const {id}=await params,now=new Date(),monthStart=new Date(now.getFullYear(),now.getMonth(),1);const [client,tasks,invoices,metrics,contactList,linkedLead]=await Promise.all([db.select().from(clients).where(eq(clients.id,id)).then(r=>r[0]),role===Role.ACCOUNTANT?Promise.resolve([]):db.select().from(creativeTasks).where(eq(creativeTasks.clientId,id)).orderBy(desc(creativeTasks.updatedAt)).limit(30),db.select().from(financeRecords).where(and(eq(financeRecords.clientId,id),eq(financeRecords.year,now.getFullYear()))).orderBy(desc(financeRecords.month)).limit(12),role===Role.ACCOUNTANT?Promise.resolve([]):db.select({adSpend:sum(mediaMetrics.adSpend),leads:sum(mediaMetrics.leads),revenue:sum(mediaMetrics.revenue),purchases:sum(mediaMetrics.purchases)}).from(mediaMetrics).where(and(eq(mediaMetrics.clientId,id),gte(mediaMetrics.date,monthStart))),db.select().from(contacts).where(eq(contacts.clientId,id)),role===Role.ACCOUNTANT?Promise.resolve(null):db.select({id:salesLeads.id}).from(salesLeads).where(eq(salesLeads.clientId,id)).limit(1).then(r=>r[0]||null)]);if(!client)redirect("/dashboard/clients");if(role===Role.ACCOUNT_MANAGER&&client.accountManagerId!==userId)redirect("/dashboard/clients");if(role===Role.MEDIA_BUYER&&client.mediaBuyerId!==userId)redirect("/dashboard/clients");const activityKeys=linkedLead?.id?[id,linkedLead.id]:[id];const activities=role===Role.ACCOUNTANT?[]:await db.select().from(salesActivities).where(inArray(salesActivities.leadId,activityKeys)).orderBy(desc(salesActivities.createdAt)).limit(12);const spend=Number(metrics[0]?.adSpend||0),leads=Number(metrics[0]?.leads||0),revenue=Number(metrics[0]?.revenue||0),purchases=Number(metrics[0]?.purchases||0),roas=spend?revenue/spend:0,pending=tasks.filter(t=>!["COMPLETED","APPROVED"].includes(t.status)).length,review=tasks.filter(t=>t.status==="REVIEW").length,done=tasks.filter(t=>["COMPLETED","APPROVED"].includes(t.status)).length,primary=contactList.find((x:any)=>x.isPrimary)||contactList[0],canManage=[Role.SUPER_ADMIN,Role.ACCOUNT_MANAGER].includes(role),showFullFinance=[Role.SUPER_ADMIN,Role.ACCOUNTANT].includes(role);return <div style={{display:"flex",flexDirection:"column",gap:18,minWidth:0}}>
<div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:14,flexWrap:"wrap"}}><div style={{display:"flex",alignItems:"center",gap:13}}><Link href="/dashboard/clients" className="btn btn-ghost btn-sm" style={{textDecoration:"none"}}>← Clients</Link><div style={{width:54,height:54,borderRadius:16,display:"grid",placeItems:"center",fontSize:20,fontWeight:900,color:"white",background:"linear-gradient(135deg,#6b274f,#d12b38)"}}>{client.companyName.slice(0,2).toUpperCase()}</div><div><h1 className="page-title" style={{margin:0}}>{client.companyName}</h1><p className="page-subtitle" style={{marginTop:3}}>{client.industry||"Client workspace"} · {primary?.name||"No primary contact"}</p></div></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{primary?.whatsapp&&<a className="btn btn-secondary btn-sm" href={`https://wa.me/${String(primary.whatsapp).replace(/\D/g,"")}`} target="_blank" style={{textDecoration:"none"}}>💬 WhatsApp</a>}{primary?.email&&<a className="btn btn-secondary btn-sm" href={`mailto:${primary.email}`} style={{textDecoration:"none"}}>✉️ Email</a>}{canManage&&<Link href={`/dashboard/clients/${id}/edit`} className="btn btn-secondary btn-sm" style={{textDecoration:"none"}}>Edit client</Link>}{canManage&&<Link href={`/dashboard/creative/new?clientId=${id}`} className="btn btn-primary btn-sm" style={{textDecoration:"none"}}>+ New Task</Link>}</div></div>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:10}}>{[{l:"Active tasks",v:pending,c:"#2563eb"},{l:"In review",v:review,c:"#f59e0b"},{l:"Approved / done",v:done,c:"#10b981"},{l:"Media spend MTD",v:formatCurrency(spend),c:"#7c3aed"},{l:"Results / leads",v:leads||purchases,c:"#0f766e"},{l:"ROAS",v:`${roas.toFixed(2)}x`,c:roas>=2?"#10b981":"#ef4444"}].map(k=><div className="card" key={k.l} style={{padding:15,borderTop:`3px solid ${k.c}`}}><div style={{fontSize:11,color:"var(--text-muted)",fontWeight:800,textTransform:"uppercase"}}>{k.l}</div><div style={{fontSize:23,fontWeight:900,color:k.c,marginTop:5}}>{k.v}</div></div>)}</div>
<div style={{display:"grid",gridTemplateColumns:"minmax(0,2fr) minmax(280px,1fr)",gap:16,alignItems:"start"}}>
<div style={{display:"flex",flexDirection:"column",gap:16}}><div className="card" style={{padding:0,overflow:"hidden"}}><div className="card-header" style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div className="card-title">🎨 Creative Tasks</div><div style={{fontSize:12,color:"var(--text-muted)",marginTop:2}}>Visual task cards — open any task to review files, comments and workflow.</div></div>{canManage&&<Link href={`/dashboard/creative/new?clientId=${id}`} className="btn btn-primary btn-sm" style={{textDecoration:"none"}}>+ Add task</Link>}</div><div style={{padding:12,display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(220px,1fr))",gap:12}}>{tasks.map((t:any)=><Link key={t.id} href={`/dashboard/creative/${t.id}`} style={{textDecoration:"none",color:"inherit",border:"1px solid var(--card-border)",borderRadius:14,overflow:"hidden",background:"var(--card-bg)",boxShadow:"0 7px 18px rgba(15,23,42,.05)"}}>{t.fileUrl?<div style={{aspectRatio:"4/3",background:"#0b1020",overflow:"hidden"}}>{isVideo(t.fileUrl,t.type)?<video src={t.fileUrl} muted playsInline preload="metadata" style={{width:"100%",height:"100%",objectFit:"cover"}}/>:<img src={t.fileUrl} alt={t.title} style={{width:"100%",height:"100%",objectFit:"cover"}}/>}</div>:<div style={{aspectRatio:"4/3",display:"grid",placeItems:"center",fontSize:38,background:"linear-gradient(135deg,rgba(107,39,79,.09),rgba(209,43,56,.08))"}}>{TYPE_ICON[t.type]||"📁"}</div>}<div style={{padding:12}}><div style={{display:"flex",justifyContent:"space-between",gap:8,alignItems:"start"}}><div style={{fontSize:13,fontWeight:900,lineHeight:1.35}}>{t.title}</div><span style={{fontSize:9,fontWeight:900,color:STATUS_COLOR[t.status]||"#64748b",whiteSpace:"nowrap"}}>{t.status.replace(/_/g," ")}</span></div><div style={{fontSize:11,color:"var(--text-muted)",marginTop:7}}>Due {new Date(t.deadline).toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"})}</div></div></Link>)}{!tasks.length&&<div style={{padding:30,textAlign:"center",color:"var(--text-muted)"}}>No tasks yet.</div>}</div></div>
{showFullFinance&&<div className="card" style={{padding:0,overflow:"hidden"}}><div className="card-header"><div className="card-title">💰 Finance & invoices</div></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Invoice</th><th>Revenue</th><th>Paid</th><th>Outstanding</th><th>Status</th></tr></thead><tbody>{invoices.map((r:any)=><tr key={r.id}><td>{r.invoiceNumber||`${r.month}/${r.year}`}</td><td>{formatCurrency(r.totalRevenue)}</td><td>{formatCurrency(r.paid)}</td><td>{formatCurrency(r.outstanding)}</td><td><span className={`badge ${r.outstanding===0?"badge-green":r.paid>0?"badge-amber":"badge-red"}`}>{r.outstanding===0?"Paid":r.paid>0?"Partial":"Unpaid"}</span></td></tr>)}</tbody></table></div></div>}
</div>
<div style={{display:"flex",flexDirection:"column",gap:14}}><div className="card"><div className="card-title" style={{marginBottom:12}}>👤 Client profile</div><div style={{display:"grid",gap:10,fontSize:13}}>{[{l:"Contact",v:primary?.name||"—"},{l:"Phone",v:primary?.phone||primary?.whatsapp||"—"},{l:"Email",v:primary?.email||"—"},{l:"Website",v:client.website||"—"},{l:"Currency",v:client.currency||"EGP"},{l:"Media budget",v:formatCurrency(client.mediaBudget||0)}].map(x=><div key={x.l} style={{display:"flex",justifyContent:"space-between",gap:12}}><span style={{color:"var(--text-muted)"}}>{x.l}</span><b style={{textAlign:"right",wordBreak:"break-word"}}>{x.v}</b></div>)}{showFullFinance&&<div style={{display:"flex",justifyContent:"space-between",gap:12}}><span style={{color:"var(--text-muted)"}}>Retainer</span><b>{formatCurrency(client.monthlyRetainer||0)}</b></div>}</div>{client.internalNotes&&<div style={{marginTop:14,padding:12,borderRadius:12,background:"var(--bg-tertiary)"}}><div style={{fontSize:10,fontWeight:900,color:"var(--text-muted)",textTransform:"uppercase"}}>Internal notes</div><div style={{fontSize:13,marginTop:5,whiteSpace:"pre-wrap"}}>{client.internalNotes}</div></div>}</div>
<div className="card"><div className="card-title" style={{marginBottom:12}}>💬 Communication Log</div>{canManage&&<details style={{marginBottom:12}}><summary style={{cursor:"pointer",fontWeight:800,fontSize:13}}>+ Log activity</summary><form action={logActivity.bind(null,id)} style={{display:"grid",gap:8,marginTop:10}}><select name="type" className="input"><option value="call">Call</option><option value="whatsapp">WhatsApp</option><option value="email">Email</option><option value="meeting">Meeting</option><option value="note">Note</option></select><textarea name="notes" className="input" placeholder="Notes…" rows={3}/><input name="outcome" className="input" placeholder="Outcome"/><input name="nextDate" type="date" className="input"/><button className="btn btn-primary btn-sm">Save activity</button></form></details>}<div style={{display:"grid",gap:8}}>{activities.map((a:any)=><div key={a.id} style={{padding:10,border:"1px solid var(--card-border)",borderRadius:10}}><div style={{display:"flex",justifyContent:"space-between",gap:8}}><b style={{fontSize:12,textTransform:"capitalize"}}>{a.type}</b><span style={{fontSize:10,color:"var(--text-muted)"}}>{new Date(a.createdAt).toLocaleDateString("en-GB")}</span></div><div style={{fontSize:12,marginTop:4}}>{a.notes||a.outcome||"Activity logged"}</div></div>)}{!activities.length&&<div style={{fontSize:12,color:"var(--text-muted)"}}>No activity logged yet.</div>}</div></div>
</div></div></div>}
