create table if not exists tech.recurring_service_invoices (
 id uuid primary key default gen_random_uuid(), recurring_service_id uuid not null references tech.recurring_services(id) on delete cascade, client_id uuid not null references tech.clients(id), project_id uuid references tech.projects(id), currency text not null default 'EGP', amount numeric(14,2) not null check(amount>=0), period_start date not null, period_end date not null, due_date date not null, status text not null default 'pending' check(status in ('pending','sent','paid','overdue','void')), idempotency_key text not null unique, paid_at timestamptz, created_at timestamptz not null default now(), check(period_end>=period_start)
);
alter table tech.recurring_service_invoices enable row level security;
create policy server_only on tech.recurring_service_invoices for all to public using(false) with check(false);
create table if not exists tech.subscription_usage_events (
 id uuid primary key default gen_random_uuid(), subscription_id uuid not null references tech.subscriptions(id) on delete cascade, addon_id uuid references tech.saas_addons(id), metric_code text not null, quantity numeric(14,4) not null check(quantity>=0), unit_price numeric(14,4) not null default 0 check(unit_price>=0), occurred_at timestamptz not null default now(), idempotency_key text not null unique, metadata jsonb not null default '{}'::jsonb
);
alter table tech.subscription_usage_events enable row level security;
create policy server_only on tech.subscription_usage_events for all to public using(false) with check(false);

create or replace view tech.dependency_impact as
select d.id dependency_id,d.project_id,d.depends_on_project_id,d.depends_on_milestone_id,d.dependency_type,d.lag_days,p.planned_start dependent_start,p.planned_end dependent_end,coalesce(dp.planned_end,m.due_date) prerequisite_due,greatest(0,coalesce((coalesce(dp.planned_end,m.due_date)+d.lag_days)-p.planned_start,0)) impact_days,case when coalesce(dp.planned_end,m.due_date)+d.lag_days>p.planned_start then 'at_risk' else 'clear' end impact_state
from tech.project_dependencies d join tech.projects p on p.id=d.project_id left join tech.projects dp on dp.id=d.depends_on_project_id left join tech.milestones m on m.id=d.depends_on_milestone_id;

create or replace function tech.cr_required_approval_role(p_change_request uuid) returns text language plpgsql set search_path=pg_catalog,tech,vgroup as $$
declare amount numeric; bu uuid; result text;
begin select coalesce(cr.proposed_price,0),p.business_unit_id into amount,bu from tech.change_requests cr join tech.projects p on p.id=cr.project_id where cr.id=p_change_request; select required_role into result from tech.change_request_approval_rules where business_unit_id=bu and active and amount>=min_amount and (max_amount is null or amount<=max_amount) order by min_amount desc limit 1; return coalesce(result,'PROJECT_MANAGER'); end$$;
create or replace function tech.client_credit_available(p_client uuid) returns numeric language sql stable set search_path=pg_catalog,tech as $$ select case when cp.on_hold or cp.risk_rating='blocked' then 0 else greatest(0,cp.credit_limit-coalesce((select sum(c.amount_due) from tech.collection_cases c where c.client_id=p_client and c.status not in ('resolved','written_off')),0)) end from tech.client_credit_profiles cp where cp.client_id=p_client $$;
create or replace function tech.set_quotation_status(p_quote uuid,p_status text,p_actor uuid) returns tech.quotations language plpgsql set search_path=pg_catalog,tech,vgroup as $$
declare q tech.quotations; pending_count int; rejected_count int; floor_margin numeric; available_credit numeric;
begin select * into q from tech.quotations where id=p_quote for update; if q.id is null then raise exception 'QUOTE_NOT_FOUND'; end if; if p_status in ('approved','sent','accepted','converted') then select count(*) filter(where decision='pending'),count(*) filter(where decision='rejected') into pending_count,rejected_count from tech.proposal_approvals where quotation_id=p_quote; if pending_count>0 or rejected_count>0 or not exists(select 1 from tech.proposal_approvals where quotation_id=p_quote and decision='approved') then raise exception 'PROPOSAL_APPROVAL_REQUIRED'; end if; select default_margin_floor into floor_margin from tech.service_catalog where id=q.service_id; if floor_margin is not null and q.margin_percent<floor_margin then raise exception 'MARGIN_BELOW_FLOOR'; end if; end if; if p_status in ('accepted','converted') then select tech.client_credit_available(q.client_id) into available_credit; if available_credit is not null and q.total>available_credit then raise exception 'CLIENT_CREDIT_LIMIT_EXCEEDED'; end if; end if; update tech.quotations set status=p_status,updated_at=now() where id=p_quote returning * into q; return q; end$$;
create or replace function tech.convert_quotation_to_project(p_quote uuid,p_actor uuid,p_manager uuid default null) returns uuid language plpgsql set search_path=pg_catalog,tech,vgroup as $$
declare q tech.quotations; project_id uuid; template tech.project_templates; phase jsonb; inst jsonb; seq int:=0; n int:=0; due date;
begin select * into q from tech.quotations where id=p_quote for update; if q.id is null then raise exception 'QUOTE_NOT_FOUND'; end if; if q.status<>'accepted' then raise exception 'QUOTE_MUST_BE_ACCEPTED'; end if; perform tech.set_quotation_status(p_quote,'converted',p_actor); insert into tech.projects(business_unit_id,client_id,project_manager_id,name,project_type,currency,base_price,current_price,planned_start,planned_end,target_end,status) values(q.business_unit_id,q.client_id,p_manager,q.title,'custom',q.currency,q.total,q.total,current_date,current_date+q.duration_days,current_date+q.duration_days,'planning') returning id into project_id; select * into template from tech.project_templates where service_id=q.service_id and active order by created_at limit 1; if template.id is not null then for phase in select value from jsonb_array_elements(template.phases) loop seq:=seq+1; insert into tech.project_phases(project_id,name,sequence,weight_percent,status) values(project_id,coalesce(phase->>'name','Phase '||seq),seq,coalesce((phase->>'weight_percent')::numeric,0),'planned'); end loop; for inst in select value from jsonb_array_elements(template.installment_template) loop n:=n+1; due:=current_date+coalesce((inst->>'due_days')::int,0); insert into tech.payment_installments(project_id,installment_number,label,currency,amount,due_date,status) values(project_id,n,inst->>'label',q.currency,round(q.total*coalesce((inst->>'percent')::numeric,0)/100,2),due,'pending'); end loop; end if; return project_id; end$$;
create or replace function tech.advance_collection_case(p_case uuid,p_actor uuid,p_status text default null) returns tech.collection_cases language plpgsql set search_path=pg_catalog,tech,vgroup as $$
declare c tech.collection_cases; next_status text;
begin select * into c from tech.collection_cases where id=p_case for update; if c.id is null then raise exception 'COLLECTION_CASE_NOT_FOUND'; end if; next_status:=coalesce(p_status,case c.stage when 1 then 'promise_to_pay' when 2 then 'finance_hold' when 3 then 'service_suspended' else c.status end); update tech.collection_cases set stage=least(5,stage+1),status=next_status,next_action_at=case when next_status in ('resolved','written_off') then null else now()+interval '3 days' end,owner_id=coalesce(owner_id,p_actor),updated_at=now() where id=p_case returning * into c; if next_status='finance_hold' then update tech.client_credit_profiles set on_hold=true,updated_at=now() where client_id=c.client_id; end if; return c; end$$;
create or replace function tech.approve_credit_note(p_note uuid,p_actor uuid) returns tech.credit_notes language plpgsql set search_path=pg_catalog,tech,vgroup as $$ declare n tech.credit_notes; begin select * into n from tech.credit_notes where id=p_note for update; if n.id is null then raise exception 'CREDIT_NOTE_NOT_FOUND'; end if; if n.requested_by=p_actor then raise exception 'MAKER_CHECKER_VIOLATION'; end if; if n.status<>'draft' then raise exception 'CREDIT_NOTE_NOT_DRAFT'; end if; update tech.credit_notes set approved_by=p_actor,status='approved' where id=p_note returning * into n; return n; end$$;
create or replace function tech.recognize_revenue(p_id uuid,p_actor uuid) returns tech.revenue_recognition language plpgsql set search_path=pg_catalog,tech,vgroup as $$ declare r tech.revenue_recognition; begin select * into r from tech.revenue_recognition where id=p_id for update; if r.id is null then raise exception 'RECOGNITION_NOT_FOUND'; end if; if r.status<>'draft' then raise exception 'RECOGNITION_NOT_DRAFT'; end if; update tech.revenue_recognition set status='recognized',recognized_at=now() where id=p_id returning * into r; return r; end$$;
create or replace function tech.pause_subscription(p_subscription uuid,p_reason text,p_resume_at timestamptz default null) returns tech.subscriptions language plpgsql set search_path=pg_catalog,tech as $$ declare s tech.subscriptions; begin update tech.subscriptions set paused_at=now(),resume_at=p_resume_at,pause_reason=p_reason,access_state='suspended',updated_at=now() where id=p_subscription and status<>'cancelled' returning * into s; if s.id is null then raise exception 'SUBSCRIPTION_NOT_PAUSABLE'; end if; return s; end$$;
create or replace function tech.resume_subscription(p_subscription uuid) returns tech.subscriptions language plpgsql set search_path=pg_catalog,tech as $$ declare s tech.subscriptions; begin update tech.subscriptions set paused_at=null,resume_at=null,pause_reason=null,access_state='enabled',updated_at=now() where id=p_subscription and paused_at is not null returning * into s; if s.id is null then raise exception 'SUBSCRIPTION_NOT_PAUSED'; end if; return s; end$$;
create or replace function tech.record_subscription_usage(p_subscription uuid,p_addon uuid,p_metric text,p_quantity numeric,p_idempotency text,p_metadata jsonb default '{}'::jsonb) returns uuid language plpgsql set search_path=pg_catalog,tech as $$
declare price numeric; event_id uuid; amount numeric;
begin if p_quantity<0 then raise exception 'INVALID_USAGE'; end if; select unit_price into price from tech.saas_addons where id=p_addon and active; if price is null then raise exception 'ADDON_NOT_FOUND'; end if; insert into tech.subscription_usage_events(subscription_id,addon_id,metric_code,quantity,unit_price,idempotency_key,metadata) values(p_subscription,p_addon,p_metric,p_quantity,price,p_idempotency,p_metadata) on conflict(idempotency_key) do update set idempotency_key=excluded.idempotency_key returning id into event_id; amount:=round(p_quantity*price,2); if amount<>0 and not exists(select 1 from tech.subscription_adjustments where subscription_id=p_subscription and metadata->>'usage_event_id'=event_id::text) then insert into tech.subscription_adjustments(subscription_id,adjustment_type,amount,metadata) values(p_subscription,'overage',amount,jsonb_build_object('usage_event_id',event_id,'metric',p_metric)); end if; return event_id; end$$;
create or replace function tech.generate_recurring_service_invoices(p_as_of date default current_date) returns int language plpgsql set search_path=pg_catalog,tech as $$
declare s tech.recurring_services; created int:=0; pstart date; pend date; due date; key text;
begin for s in select * from tech.recurring_services where status='active' and next_bill_date<=p_as_of for update loop pstart:=s.next_bill_date; pend:=case s.billing_period when 'monthly' then (pstart+interval '1 month')::date-1 when 'quarterly' then (pstart+interval '3 months')::date-1 else (pstart+interval '1 year')::date-1 end; due:=pstart+7; key:='recurring:'||s.id||':'||pstart; insert into tech.recurring_service_invoices(recurring_service_id,client_id,project_id,currency,amount,period_start,period_end,due_date,idempotency_key) values(s.id,s.client_id,s.project_id,s.currency,s.amount,pstart,pend,due,key) on conflict(idempotency_key) do nothing; if found then created:=created+1; end if; update tech.recurring_services set next_bill_date=case s.billing_period when 'monthly' then (s.next_bill_date+interval '1 month')::date when 'quarterly' then (s.next_bill_date+interval '3 months')::date else (s.next_bill_date+interval '1 year')::date end where id=s.id; end loop; return created; end$$;
create or replace function tech.generate_renewal_opportunities(p_horizon_days int default 60) returns int language plpgsql set search_path=pg_catalog,tech as $$
declare n int:=0; m int:=0;
begin insert into tech.renewal_pipeline(client_id,subscription_id,renewal_date,expected_value,currency,probability,stage) select s.client_id,s.id,s.current_period_end::date,sp.price,sp.currency,70,'upcoming' from tech.subscriptions s join tech.subscription_plans sp on sp.id=s.plan_id where s.status in ('active','trialing') and s.current_period_end is not null and s.current_period_end::date<=current_date+p_horizon_days and not exists(select 1 from tech.renewal_pipeline r where r.subscription_id=s.id and r.renewal_date=s.current_period_end::date); get diagnostics n=row_count; insert into tech.renewal_pipeline(client_id,support_contract_id,renewal_date,expected_value,currency,probability,stage) select c.client_id,c.id,c.end_date,c.monthly_fee*12,c.currency,70,'upcoming' from tech.support_contracts c where c.status='active' and c.end_date is not null and c.end_date<=current_date+p_horizon_days and not exists(select 1 from tech.renewal_pipeline r where r.support_contract_id=c.id and r.renewal_date=c.end_date); get diagnostics m=row_count; return n+m; end$$;
create or replace function tech.refresh_customer_success_health(p_client uuid,p_usage numeric,p_billing numeric,p_support numeric,p_engagement numeric) returns numeric language plpgsql set search_path=pg_catalog,tech as $$
declare score numeric; risk text;
begin score:=round((greatest(0,least(100,p_usage))+greatest(0,least(100,p_billing))+greatest(0,least(100,p_support))+greatest(0,least(100,p_engagement)))/4,2); risk:=case when score<35 then 'high' when score<55 then 'elevated' when score<75 then 'standard' else 'low' end; insert into tech.customer_success_health(client_id,usage_score,billing_score,support_score,engagement_score,churn_risk,updated_at) values(p_client,p_usage,p_billing,p_support,p_engagement,risk,now()) on conflict(client_id) do update set usage_score=excluded.usage_score,billing_score=excluded.billing_score,support_score=excluded.support_score,engagement_score=excluded.engagement_score,churn_risk=excluded.churn_risk,updated_at=now(); update tech.subscriptions set churn_risk=risk,updated_at=now() where client_id=p_client and status in ('active','trialing','past_due'); return score; end$$;
create or replace function tech.process_trial_funnel(p_now timestamptz default now()) returns int language plpgsql set search_path=pg_catalog,tech as $$
declare n int:=0;
begin insert into tech.trial_events(subscription_id,event_type,occurred_at,metadata) select s.id,'trial_ending',p_now,jsonb_build_object('trial_ends_at',s.trial_ends_at) from tech.subscriptions s where s.status='trialing' and s.trial_ends_at between p_now and p_now+interval '3 days' and not exists(select 1 from tech.trial_events e where e.subscription_id=s.id and e.event_type='trial_ending' and e.occurred_at>p_now-interval '7 days'); get diagnostics n=row_count; insert into tech.trial_events(subscription_id,event_type,occurred_at) select s.id,'expired',p_now from tech.subscriptions s where s.status='trialing' and s.trial_ends_at<p_now and not exists(select 1 from tech.trial_events e where e.subscription_id=s.id and e.event_type='expired'); update tech.subscriptions set access_state='suspended',updated_at=p_now where status='trialing' and trial_ends_at<p_now; return n; end$$;

-- Cover all foreign-key columns introduced by the Tech operating-system migrations.
do $$
declare r record; idx text;
begin for r in select c.relname table_name,con.conname,array_agg(a.attname order by u.ord) cols from pg_constraint con join pg_class c on c.oid=con.conrelid join pg_namespace n on n.oid=c.relnamespace cross join lateral unnest(con.conkey) with ordinality u(attnum,ord) join pg_attribute a on a.attrelid=c.oid and a.attnum=u.attnum where con.contype='f' and n.nspname='tech' and c.relname in ('resource_capacity','timesheets','support_contracts','recurring_services','deliverables','uat_cycles','issues','environments','release_records','project_asset_registry','change_request_approval_rules','revenue_recognition','credit_notes','collection_cases','client_credit_profiles','saas_addons','subscription_addons','subscription_adjustments','trial_events','customer_success_health','renewal_pipeline','external_resources','external_resource_assignments','service_catalog','project_templates','quotations','quotation_items','proposal_approvals','client_feedback','project_postmortems','recurring_service_invoices','subscription_usage_events') group by c.relname,con.conname loop idx:='idx_'||substr(md5(r.conname),1,16); execute format('create index if not exists %I on tech.%I (%s)',idx,r.table_name,(select string_agg(format('%I',x),',') from unnest(r.cols) x)); end loop; end$$;
