-- VIVITO enterprise governance: gates 13-32. Server-side only; fail-closed RLS.
begin;
create table if not exists public.vivito_governance_controls(id text primary key,workspace_id text not null default 'default',scope_type text not null check(scope_type in('WORKSPACE','CLIENT','ACTION')),scope_id text,autonomy_enabled boolean not null default true,kill_switch boolean not null default false,max_daily_actions integer not null default 100,max_daily_ai_calls integer not null default 500,policy_version text not null default 'v1',updated_by text,updated_at timestamptz not null default now(),unique(workspace_id,scope_type,scope_id));
create table if not exists public.vivito_decision_journal(id text primary key,workspace_id text not null default 'default',client_id text,event_id text,decision_version text not null,model_provider text,evidence_quality numeric not null default 0 check(evidence_quality between 0 and 1),confidence numeric not null default 0 check(confidence between 0 and 1),evidence jsonb not null default '{}'::jsonb,decision jsonb not null default '{}'::jsonb,simulation jsonb,outcome jsonb,created_at timestamptz not null default now());
create table if not exists public.vivito_knowledge_provenance(id text primary key,workspace_id text not null default 'default',scope_type text not null,scope_id text,source_type text not null,source_id text,source_version text,content_hash text not null,valid_from timestamptz not null default now(),expires_at timestamptz,superseded_by text,confidence numeric not null default 1 check(confidence between 0 and 1),metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.vivito_runtime_checkpoints(id text primary key,workspace_id text not null default 'default',run_key text not null unique,state jsonb not null default '{}'::jsonb,status text not null,attempt integer not null default 1,lease_until timestamptz,last_error text,updated_at timestamptz not null default now());
create table if not exists public.vivito_eval_metrics(id text primary key,workspace_id text not null default 'default',metric_date date not null default current_date,metric_name text not null,value numeric not null,baseline numeric,drift_detected boolean not null default false,evidence jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),unique(workspace_id,metric_date,metric_name));
create table if not exists public.vivito_value_ledger(id text primary key,workspace_id text not null default 'default',event_id text,cost_amount numeric not null default 0,value_amount numeric not null default 0,currency text not null default 'EGP',method text not null default 'OBSERVED',evidence jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.vivito_backup_manifests(id text primary key,workspace_id text not null default 'default',snapshot_key text not null unique,status text not null,checksum text,record_counts jsonb not null default '{}'::jsonb,restore_verified_at timestamptz,created_at timestamptz not null default now());
create index if not exists idx_vivito_decision_client_created on public.vivito_decision_journal(workspace_id,client_id,created_at desc);create index if not exists idx_vivito_provenance_scope on public.vivito_knowledge_provenance(workspace_id,scope_type,scope_id,created_at desc);create index if not exists idx_vivito_eval_drift on public.vivito_eval_metrics(workspace_id,drift_detected,metric_date desc);create index if not exists idx_vivito_value_event on public.vivito_value_ledger(workspace_id,event_id);
alter table public.vivito_governance_controls enable row level security;alter table public.vivito_decision_journal enable row level security;alter table public.vivito_knowledge_provenance enable row level security;alter table public.vivito_runtime_checkpoints enable row level security;alter table public.vivito_eval_metrics enable row level security;alter table public.vivito_value_ledger enable row level security;alter table public.vivito_backup_manifests enable row level security;
commit;
