-- Shared / Group controls
create table if not exists vgroup.finance_periods (
  id uuid primary key default gen_random_uuid(), business_unit_id uuid not null references vgroup.business_units(id), period_start date not null, period_end date not null,
  status text not null default 'open' check (status in ('open','closed','reopened')), closed_by uuid references vgroup.users(id), closed_at timestamptz,
  reopened_by uuid references vgroup.users(id), reopened_at timestamptz, reason text, created_at timestamptz not null default now(), check (period_end >= period_start), unique(business_unit_id,period_start,period_end)
); alter table vgroup.finance_periods enable row level security;
create table if not exists vgroup.approval_requests (
  id uuid primary key default gen_random_uuid(), business_unit_id uuid references vgroup.business_units(id), entity_type text not null, entity_id uuid not null, action text not null,
  requested_by uuid references vgroup.users(id), requested_at timestamptz not null default now(), decided_by uuid references vgroup.users(id), decided_at timestamptz,
  status text not null default 'pending' check (status in ('pending','approved','rejected','cancelled')), decision_note text, metadata jsonb not null default '{}'::jsonb,
  check (decided_by is null or requested_by is null or decided_by <> requested_by)
); create index if not exists approval_requests_pending_idx on vgroup.approval_requests(status,business_unit_id,requested_at) where status='pending'; alter table vgroup.approval_requests enable row level security;
create table if not exists vgroup.permission_delegations (
  id uuid primary key default gen_random_uuid(), business_unit_id uuid references vgroup.business_units(id), delegator_user_id uuid not null references vgroup.users(id), delegate_user_id uuid not null references vgroup.users(id),
  permission_code text not null, starts_at timestamptz not null, ends_at timestamptz not null, revoked_at timestamptz, approved_by uuid references vgroup.users(id), reason text, created_at timestamptz not null default now(),
  check (delegate_user_id <> delegator_user_id), check (ends_at > starts_at)
); create index if not exists permission_delegations_active_idx on vgroup.permission_delegations(delegate_user_id,starts_at,ends_at) where revoked_at is null; alter table vgroup.permission_delegations enable row level security;
create table if not exists vgroup.operational_exceptions (
  id uuid primary key default gen_random_uuid(), business_unit_id uuid references vgroup.business_units(id), source_system text not null, entity_type text, entity_id uuid,
  severity text not null default 'medium' check (severity in ('low','medium','high','critical')), code text not null, title text not null, detail text,
  status text not null default 'open' check (status in ('open','acknowledged','resolved','ignored')), assigned_to uuid references vgroup.users(id), resolved_by uuid references vgroup.users(id), resolved_at timestamptz,
  dedupe_key text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
); create unique index if not exists operational_exceptions_open_dedupe_uq on vgroup.operational_exceptions(dedupe_key) where dedupe_key is not null and status in ('open','acknowledged'); create index if not exists operational_exceptions_queue_idx on vgroup.operational_exceptions(status,severity,created_at); alter table vgroup.operational_exceptions enable row level security;
create table if not exists vgroup.notification_escalation_rules (id uuid primary key default gen_random_uuid(),business_unit_id uuid references vgroup.business_units(id),event_type text not null,after_minutes integer not null check(after_minutes>=0),target_role_code text,channel text not null default 'in_app',priority text not null default 'normal' check(priority in ('normal','high','critical')),active boolean not null default true,created_at timestamptz not null default now()); alter table vgroup.notification_escalation_rules enable row level security;
create table if not exists vgroup.kpi_targets (id uuid primary key default gen_random_uuid(),business_unit_id uuid references vgroup.business_units(id),entity_type text,entity_id uuid,metric_code text not null,period_start date not null,period_end date not null,target_value numeric(18,4) not null,unit text not null default 'number',created_by uuid references vgroup.users(id),created_at timestamptz not null default now(),check(period_end>=period_start)); create index if not exists kpi_targets_lookup_idx on vgroup.kpi_targets(business_unit_id,metric_code,period_start,period_end); alter table vgroup.kpi_targets enable row level security;
create table if not exists vgroup.data_retention_policies (id uuid primary key default gen_random_uuid(),business_unit_id uuid references vgroup.business_units(id),entity_type text not null,retention_days integer not null check(retention_days>=1),archive_before_delete boolean not null default true,permanent_delete_requires_super_admin boolean not null default true,active boolean not null default true,created_at timestamptz not null default now(),unique(business_unit_id,entity_type)); alter table vgroup.data_retention_policies enable row level security;
create table if not exists vgroup.intercompany_settlements (id uuid primary key default gen_random_uuid(),intercompany_transaction_id uuid not null references vgroup.intercompany_transactions(id),requested_by uuid references vgroup.users(id),approved_by uuid references vgroup.users(id),status text not null default 'pending' check(status in ('pending','approved','posted','rejected','cancelled')),settlement_reference text,approved_at timestamptz,posted_at timestamptz,created_at timestamptz not null default now(),check(approved_by is null or requested_by is null or approved_by<>requested_by)); create index if not exists intercompany_settlements_tx_idx on vgroup.intercompany_settlements(intercompany_transaction_id,status); alter table vgroup.intercompany_settlements enable row level security;
create or replace function vgroup.guard_finance_period() returns trigger language plpgsql security definer set search_path=vgroup,public as $$begin if exists(select 1 from vgroup.finance_periods p where p.business_unit_id=new.business_unit_id and p.status='closed' and new.occurred_at::date between p.period_start and p.period_end) then raise exception 'finance_period_closed'; end if; return new; end$$;
drop trigger if exists ledger_finance_period_guard on vgroup.ledger_transactions; create trigger ledger_finance_period_guard before insert on vgroup.ledger_transactions for each row execute function vgroup.guard_finance_period();
create or replace function vgroup.guard_ledger_immutable() returns trigger language plpgsql security definer set search_path=vgroup,public as $$begin raise exception 'ledger_is_immutable_use_reversal'; end$$; drop trigger if exists ledger_immutable_guard on vgroup.ledger_transactions; create trigger ledger_immutable_guard before update or delete on vgroup.ledger_transactions for each row execute function vgroup.guard_ledger_immutable();
create or replace function vgroup.reverse_ledger_transaction(p_original uuid,p_created_by uuid,p_reason text,p_replacement_amount numeric default null) returns table(reversal_id uuid,replacement_id uuid) language plpgsql security definer set search_path=vgroup,public as $$declare o vgroup.ledger_transactions%rowtype;r uuid;n uuid;begin select * into o from vgroup.ledger_transactions where id=p_original;if o.id is null then raise exception 'ledger_transaction_not_found';end if;insert into vgroup.ledger_transactions(business_unit_id,source_system,source_type,source_id,transaction_type,direction,account_code,counterparty_type,counterparty_id,currency,amount,occurred_at,description,idempotency_key,metadata,created_by) values(o.business_unit_id,o.source_system,'reversal',o.id,'reversal',case when o.direction='credit' then 'debit' else 'credit' end,o.account_code,o.counterparty_type,o.counterparty_id,o.currency,o.amount,now(),coalesce(p_reason,'Correction reversal'),'reversal:'||o.id::text,jsonb_build_object('reverses',o.id),p_created_by) returning id into r;if p_replacement_amount is not null then insert into vgroup.ledger_transactions(business_unit_id,source_system,source_type,source_id,transaction_type,direction,account_code,counterparty_type,counterparty_id,currency,amount,occurred_at,description,idempotency_key,metadata,created_by) values(o.business_unit_id,o.source_system,'replacement',o.id,o.transaction_type,o.direction,o.account_code,o.counterparty_type,o.counterparty_id,o.currency,p_replacement_amount,now(),coalesce(p_reason,'Correction replacement'),'replacement:'||o.id::text,jsonb_build_object('replaces',o.id),p_created_by) returning id into n;end if;return query select r,n;end$$; revoke all on function vgroup.reverse_ledger_transaction(uuid,uuid,text,numeric) from public;

alter table hospitality.security_deposits add column if not exists forfeited_amount numeric(18,2) not null default 0; alter table hospitality.security_deposits add constraint security_deposit_amounts_ck check(amount>=0 and held_amount>=0 and released_amount>=0 and forfeited_amount>=0 and released_amount+forfeited_amount<=amount) not valid; alter table hospitality.security_deposits validate constraint security_deposit_amounts_ck;
create table if not exists hospitality.cancellation_events(id uuid primary key default gen_random_uuid(),reservation_id uuid not null references hospitality.reservations(id),policy_id uuid references hospitality.cancellation_policies(id),event_type text not null check(event_type in ('cancelled','no_show')),gross_amount numeric(18,2) not null,penalty_amount numeric(18,2) not null,refund_amount numeric(18,2) not null,calculated_at timestamptz not null default now(),processed_by uuid references vgroup.users(id),metadata jsonb not null default '{}'::jsonb); alter table hospitality.cancellation_events enable row level security;
create or replace function hospitality.quote_cancellation(p_reservation_id uuid,p_event_type text,p_at timestamptz default now()) returns table(policy_id uuid,penalty_amount numeric,refund_amount numeric) language sql stable security definer set search_path=hospitality,public as $$with r as(select * from hospitality.reservations where id=p_reservation_id and archived_at is null),p as(select cp.* from hospitality.cancellation_policies cp join r on r.property_id=cp.property_id where cp.active order by cp.created_at desc limit 1) select p.id,round(case when p_event_type='no_show' then r.gross_amount*p.no_show_percent/100 when extract(epoch from(r.check_in::timestamp-p_at))/3600>=p.free_cancel_hours then 0 else r.gross_amount*p.penalty_percent/100 end,2),round(r.gross_amount-case when p_event_type='no_show' then r.gross_amount*p.no_show_percent/100 when extract(epoch from(r.check_in::timestamp-p_at))/3600>=p.free_cancel_hours then 0 else r.gross_amount*p.penalty_percent/100 end,2) from r join p on true$$; revoke all on function hospitality.quote_cancellation(uuid,text,timestamptz) from public;
alter table hospitality.owner_payouts add column if not exists requested_by uuid references vgroup.users(id); alter table hospitality.owner_payouts add column if not exists approved_by uuid references vgroup.users(id); alter table hospitality.owner_payouts add column if not exists approved_at timestamptz;
create or replace function hospitality.guard_owner_payout() returns trigger language plpgsql security definer set search_path=hospitality,public as $$declare cap numeric;used numeric;begin if new.requested_by is not null and new.approved_by is not null and new.requested_by=new.approved_by then raise exception 'maker_checker_violation';end if;select net_payable into cap from hospitality.owner_statements where id=new.statement_id;if cap is null then raise exception 'owner_statement_not_found';end if;select coalesce(sum(amount),0) into used from hospitality.owner_payouts where statement_id=new.statement_id and id<>new.id and status not in('failed','cancelled');if used+new.amount>cap then raise exception 'owner_payout_exceeds_statement_net';end if;return new;end$$; drop trigger if exists owner_payout_guard on hospitality.owner_payouts; create trigger owner_payout_guard before insert or update on hospitality.owner_payouts for each row execute function hospitality.guard_owner_payout();
create or replace function hospitality.guard_refund_maker_checker() returns trigger language plpgsql security definer set search_path=hospitality,public as $$begin if new.requested_by is not null and new.approved_by is not null and new.requested_by=new.approved_by then raise exception 'maker_checker_violation';end if;return new;end$$; drop trigger if exists refund_maker_checker_guard on hospitality.refunds; create trigger refund_maker_checker_guard before insert or update on hospitality.refunds for each row execute function hospitality.guard_refund_maker_checker();
create table if not exists hospitality.expense_approval_rules(id uuid primary key default gen_random_uuid(),business_unit_id uuid not null references vgroup.business_units(id),min_amount numeric(18,2) not null default 0,max_amount numeric(18,2),required_role_code text not null,second_approval_required boolean not null default false,active boolean not null default true,created_at timestamptz not null default now(),check(max_amount is null or max_amount>=min_amount)); alter table hospitality.expense_approval_rules enable row level security;
create table if not exists hospitality.inventory_reorder_alerts(id uuid primary key default gen_random_uuid(),inventory_item_id uuid not null references hospitality.inventory_items(id) on delete cascade,quantity numeric not null,reorder_level numeric not null,status text not null default 'open' check(status in('open','ordered','resolved','ignored')),opened_at timestamptz not null default now(),resolved_at timestamptz,unique(inventory_item_id,status)); alter table hospitality.inventory_reorder_alerts enable row level security;
create or replace function hospitality.refresh_inventory_reorder_alerts() returns integer language plpgsql security definer set search_path=hospitality,public as $$declare n integer;begin insert into hospitality.inventory_reorder_alerts(inventory_item_id,quantity,reorder_level,status) select i.id,i.quantity,i.reorder_level,'open' from hospitality.inventory_items i where i.archived_at is null and i.quantity<=i.reorder_level on conflict(inventory_item_id,status) do update set quantity=excluded.quantity,reorder_level=excluded.reorder_level;get diagnostics n=row_count;update hospitality.inventory_reorder_alerts a set status='resolved',resolved_at=now() where a.status='open' and exists(select 1 from hospitality.inventory_items i where i.id=a.inventory_item_id and i.quantity>i.reorder_level);return n;end$$;
alter table hospitality.owner_statements add column if not exists locked_at timestamptz; alter table hospitality.owner_statements add column if not exists locked_by uuid references vgroup.users(id);
create table if not exists hospitality.owner_statement_adjustments(id uuid primary key default gen_random_uuid(),statement_id uuid not null references hospitality.owner_statements(id),amount numeric(18,2) not null check(amount<>0),reason text not null,created_by uuid not null references vgroup.users(id),created_at timestamptz not null default now()); alter table hospitality.owner_statement_adjustments enable row level security;
create or replace function hospitality.guard_locked_owner_statement() returns trigger language plpgsql security definer set search_path=hospitality,public as $$begin if old.locked_at is not null then raise exception 'owner_statement_locked_use_adjustment';end if;return new;end$$; drop trigger if exists owner_statement_lock_guard on hospitality.owner_statements; create trigger owner_statement_lock_guard before update or delete on hospitality.owner_statements for each row execute function hospitality.guard_locked_owner_statement();
create table if not exists hospitality.maintenance_sla_rules(id uuid primary key default gen_random_uuid(),business_unit_id uuid not null references vgroup.business_units(id),priority text not null,acknowledge_minutes integer not null check(acknowledge_minutes>0),resolve_minutes integer not null check(resolve_minutes>0),active boolean not null default true,unique(business_unit_id,priority)); alter table hospitality.maintenance_sla_rules enable row level security;
create table if not exists hospitality.work_order_escalations(id uuid primary key default gen_random_uuid(),work_order_id uuid not null references hospitality.work_orders(id) on delete cascade,breach_type text not null check(breach_type in('acknowledgement','resolution')),due_at timestamptz not null,escalated_at timestamptz not null default now(),resolved_at timestamptz,unique(work_order_id,breach_type)); alter table hospitality.work_order_escalations enable row level security;
create or replace view hospitality.property_profitability as select p.id property_id,p.name,coalesce(r.revenue,0)::numeric(18,2) revenue,coalesce(i.costs,0)::numeric(18,2) operating_costs,(coalesce(r.revenue,0)-coalesce(i.costs,0))::numeric(18,2) operating_profit from hospitality.properties p left join(select property_id,sum(net_owner_amount) revenue from hospitality.reservations where archived_at is null and status not in('cancelled','no_show') group by property_id)r on r.property_id=p.id left join(select property_id,sum(total) costs from hospitality.invoices where archived_at is null and status not in('cancelled','void') and invoice_type in('expense','vendor','cost') group by property_id)i on i.property_id=p.id where p.archived_at is null;
create or replace view hospitality.property_kpis_30d as with x as(select p.id property_id,p.name,coalesce(sum(greatest(0,least(r.check_out,current_date)-greatest(r.check_in,current_date-30))),0)::numeric booked_nights,coalesce(sum(case when r.check_out>current_date-30 and r.check_in<current_date then r.gross_amount else 0 end),0)::numeric revenue from hospitality.properties p left join hospitality.reservations r on r.property_id=p.id and r.archived_at is null and r.status not in('cancelled','no_show') where p.archived_at is null group by p.id,p.name) select property_id,name,round(booked_nights/30*100,2) occupancy_percent,round(case when booked_nights>0 then revenue/booked_nights else 0 end,2) adr,round(revenue/30,2) revpar from x;

create or replace function tech.guard_project_dependency_cycle() returns trigger language plpgsql security definer set search_path=tech,public as $$begin if new.depends_on_project_id is null then return new;end if;if new.project_id=new.depends_on_project_id then raise exception 'project_dependency_cycle';end if;if exists(with recursive chain(project_id) as(select new.depends_on_project_id union select d.depends_on_project_id from tech.project_dependencies d join chain c on d.project_id=c.project_id where d.depends_on_project_id is not null and d.id<>coalesce(new.id,gen_random_uuid())) select 1 from chain where project_id=new.project_id) then raise exception 'project_dependency_cycle';end if;return new;end$$; drop trigger if exists project_dependency_cycle_guard on tech.project_dependencies; create trigger project_dependency_cycle_guard before insert or update on tech.project_dependencies for each row execute function tech.guard_project_dependency_cycle();
alter table tech.milestones add column if not exists requires_client_acceptance boolean not null default false; alter table tech.milestones add column if not exists acceptance_status text not null default 'not_required' check(acceptance_status in('not_required','pending','accepted','rejected')); alter table tech.milestones add column if not exists accepted_by uuid references vgroup.users(id); alter table tech.milestones add column if not exists accepted_at timestamptz;
create or replace function tech.guard_milestone_completion() returns trigger language plpgsql security definer set search_path=tech,public as $$begin if new.status='completed' and new.requires_client_acceptance and new.acceptance_status<>'accepted' then raise exception 'client_acceptance_required';end if;return new;end$$; drop trigger if exists milestone_acceptance_guard on tech.milestones; create trigger milestone_acceptance_guard before insert or update on tech.milestones for each row execute function tech.guard_milestone_completion();
create table if not exists tech.project_cost_entries(id uuid primary key default gen_random_uuid(),project_id uuid not null references tech.projects(id) on delete cascade,cost_type text not null,description text,currency text not null default 'EGP',amount numeric(18,2) not null check(amount>=0),occurred_at date not null default current_date,created_by uuid references vgroup.users(id),created_at timestamptz not null default now()); create index if not exists project_cost_entries_project_idx on tech.project_cost_entries(project_id,occurred_at); alter table tech.project_cost_entries enable row level security;
create or replace view tech.project_margin as select p.id project_id,p.name,p.current_price revenue,coalesce(sum(c.amount),0)::numeric(18,2) cost,(p.current_price-coalesce(sum(c.amount),0))::numeric(18,2) margin,round(case when p.current_price>0 then(p.current_price-coalesce(sum(c.amount),0))/p.current_price*100 else 0 end,2) margin_percent from tech.projects p left join tech.project_cost_entries c on c.project_id=p.id where p.archived_at is null group by p.id,p.name,p.current_price;
create table if not exists tech.installment_escalations(id uuid primary key default gen_random_uuid(),installment_id uuid not null references tech.payment_installments(id) on delete cascade,level integer not null default 1 check(level between 1 and 5),due_at date not null,status text not null default 'open' check(status in('open','resolved','waived')),escalated_at timestamptz not null default now(),resolved_at timestamptz,unique(installment_id,level)); alter table tech.installment_escalations enable row level security;
create or replace function tech.refresh_overdue_installment_escalations() returns integer language plpgsql security definer set search_path=tech,public as $$declare n integer;begin insert into tech.installment_escalations(installment_id,level,due_at) select i.id,least(5,greatest(1,1+((current_date-i.due_date)/7))),i.due_date from tech.payment_installments i where i.status not in('paid','cancelled') and i.paid_amount<i.amount and i.due_date<current_date on conflict(installment_id,level) do nothing;get diagnostics n=row_count;update tech.installment_escalations e set status='resolved',resolved_at=now() where e.status='open' and exists(select 1 from tech.payment_installments i where i.id=e.installment_id and(i.status='paid' or i.paid_amount>=i.amount));return n;end$$;
create or replace view tech.change_request_cumulative_impact as select p.id project_id,p.name,p.base_price,p.current_price,p.target_end,coalesce(sum(cr.proposed_price)filter(where cr.status in('approved','implemented')),0)::numeric(18,2) approved_change_value,coalesce(sum(cr.extra_days)filter(where cr.status in('approved','implemented')),0)::int approved_extra_days,(p.current_price+coalesce(sum(cr.proposed_price)filter(where cr.status='priced'),0))::numeric(18,2) projected_price,(p.target_end+coalesce(sum(cr.extra_days)filter(where cr.status='priced'),0)::int)::date projected_end from tech.projects p left join tech.change_requests cr on cr.project_id=p.id where p.archived_at is null group by p.id,p.name,p.base_price,p.current_price,p.target_end;
alter table tech.sla_incidents add column if not exists escalated_at timestamptz; alter table tech.sla_incidents add column if not exists escalation_level integer not null default 0;
create or replace function tech.refresh_sla_escalations() returns integer language plpgsql security definer set search_path=tech,vgroup,public as $$declare n integer;begin with breached as(select i.id,i.project_id,i.subscription_id,i.opened_at,r.response_minutes,r.resolution_minutes,case when i.first_response_at is null and now()>i.opened_at+make_interval(mins=>r.response_minutes) then 'response' when i.resolved_at is null and now()>i.opened_at+make_interval(mins=>r.resolution_minutes) then 'resolution' end breach from tech.sla_incidents i join tech.sla_rules r on r.id=i.sla_rule_id where i.status<>'resolved') update tech.sla_incidents i set escalated_at=coalesce(i.escalated_at,now()),escalation_level=greatest(i.escalation_level,1) from breached b where b.id=i.id and b.breach is not null;get diagnostics n=row_count;insert into vgroup.operational_exceptions(source_system,entity_type,entity_id,severity,code,title,dedupe_key) select 'tech','sla_incident',i.id,'high','SLA_BREACH','SLA breach requires attention','sla:'||i.id::text from tech.sla_incidents i where i.escalation_level>0 and i.status<>'resolved' on conflict(dedupe_key) where dedupe_key is not null and status in('open','acknowledged') do nothing;return n;end$$;
alter table tech.subscriptions add column if not exists access_state text not null default 'enabled' check(access_state in('enabled','grace','suspended')); alter table tech.subscriptions add column if not exists grace_ends_at timestamptz; alter table tech.subscriptions add column if not exists suspended_at timestamptz; alter table tech.subscriptions add column if not exists dunning_stage integer not null default 0 check(dunning_stage between 0 and 5);
create or replace function tech.refresh_subscription_dunning(p_grace_days integer default 7) returns integer language plpgsql security definer set search_path=tech,public as $$declare n integer;begin update tech.subscriptions s set access_state=case when x.days_overdue>p_grace_days then 'suspended' else 'grace' end,grace_ends_at=case when x.days_overdue<=p_grace_days then x.first_due+make_interval(days=>p_grace_days) else s.grace_ends_at end,suspended_at=case when x.days_overdue>p_grace_days then coalesce(s.suspended_at,now()) else null end,dunning_stage=least(5,greatest(1,1+(x.days_overdue/3))) from(select subscription_id,min(due_at) first_due,extract(day from now()-min(due_at))::int days_overdue from tech.subscription_invoices where status not in('paid','void','cancelled') and due_at<now() group by subscription_id)x where s.id=x.subscription_id and s.status not in('cancelled');get diagnostics n=row_count;update tech.subscriptions s set access_state='enabled',grace_ends_at=null,suspended_at=null,dunning_stage=0 where not exists(select 1 from tech.subscription_invoices i where i.subscription_id=s.id and i.status not in('paid','void','cancelled') and i.due_at<now()) and s.status<>'cancelled';return n;end$$;
create table if not exists tech.subscription_entitlements(id uuid primary key default gen_random_uuid(),subscription_id uuid not null references tech.subscriptions(id) on delete cascade,entitlement_code text not null,limit_value numeric,unit text not null default 'count',active boolean not null default true,created_at timestamptz not null default now(),unique(subscription_id,entitlement_code)); alter table tech.subscription_entitlements enable row level security;
create table if not exists tech.subscription_usage(id uuid primary key default gen_random_uuid(),subscription_id uuid not null references tech.subscriptions(id) on delete cascade,entitlement_code text not null,usage_value numeric not null default 0 check(usage_value>=0),period_start timestamptz not null,period_end timestamptz not null,updated_at timestamptz not null default now(),check(period_end>period_start),unique(subscription_id,entitlement_code,period_start,period_end)); alter table tech.subscription_usage enable row level security;
create table if not exists tech.project_acceptances(id uuid primary key default gen_random_uuid(),project_id uuid not null references tech.projects(id) on delete cascade,acceptance_type text not null default 'final' check(acceptance_type in('milestone','final')),milestone_id uuid references tech.milestones(id),status text not null default 'pending' check(status in('pending','accepted','rejected')),requested_at timestamptz not null default now(),accepted_by uuid references vgroup.users(id),accepted_at timestamptz,warranty_days integer not null default 30 check(warranty_days>=0),warranty_ends_at timestamptz,notes text,created_at timestamptz not null default now()); create index if not exists project_acceptances_project_idx on tech.project_acceptances(project_id,status); alter table tech.project_acceptances enable row level security;
create or replace view tech.project_health as select p.id project_id,p.name,p.progress_percent,p.status,coalesce(r.avg_risk,0)::numeric(6,2) average_risk_score,coalesce(o.overdue_installments,0)::int overdue_installments,case when p.status in('cancelled','archived') then 0 else greatest(0,least(100,100-coalesce(r.avg_risk,0)*6-coalesce(o.overdue_installments,0)*10-case when p.target_end<current_date and p.progress_percent<100 then 25 else 0 end)) end::numeric(6,2) health_score from tech.projects p left join(select project_id,avg(score)::numeric avg_risk from tech.project_risks where status not in('closed','resolved') group by project_id)r on r.project_id=p.id left join(select project_id,count(*) overdue_installments from tech.payment_installments where status not in('paid','cancelled') and paid_amount<amount and due_date<current_date group by project_id)o on o.project_id=p.id where p.archived_at is null;
insert into vgroup.data_retention_policies(business_unit_id,entity_type,retention_days) select null,x.entity_type,x.days from(values('audit_log',2555),('financial_transaction',3650),('property_media',1095),('project_file',1095),('notification',365))x(entity_type,days) on conflict(business_unit_id,entity_type) do nothing;
insert into hospitality.maintenance_sla_rules(business_unit_id,priority,acknowledge_minutes,resolve_minutes) select bu.id,x.priority,x.ack,x.res from vgroup.business_units bu cross join(values('low',240,4320),('medium',120,1440),('high',30,480),('critical',10,120))x(priority,ack,res) where bu.code='hospitality' on conflict(business_unit_id,priority) do nothing;
