export const dynamic="force-dynamic";
import {NextRequest,NextResponse} from "next/server";
import {auth} from "@/lib/auth";
import {db,emailLogs,clients,contacts,creativeTasks,users,financeRecords} from "@/lib/db";
import {eq,and} from "drizzle-orm";

const RESEND_URL="https://api.resend.com/emails";
const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!)).slice(0,2000);
const email=(v:unknown)=>String(v??"").trim().toLowerCase().slice(0,254);
const validEmail=(v:string)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);
const _rate=new Map<string,{count:number;resetAt:number}>();
function rateOk(key:string){const now=Date.now(),x=_rate.get(key);if(!x||now>x.resetAt){_rate.set(key,{count:1,resetAt:now+3600000});return true}if(x.count>=20)return false;x.count++;return true}
async function sendEmail(to:string,subject:string,html:string,type:string){const apiKey=process.env.RESEND_API_KEY;if(!apiKey)return {success:false,error:"Email provider is not configured"};const res=await fetch(RESEND_URL,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${apiKey}`},body:JSON.stringify({from:process.env.EMAIL_FROM??"VIVIT ERP <noreply@viviterp.com>",to:[to],subject,html}),signal:AbortSignal.timeout(8000)});const data=await res.json().catch(()=>({}));await db.insert(emailLogs).values({to,subject,type,status:res.ok?"sent":"failed",resendId:data.id||null});return res.ok?{success:true,id:data.id||null}:{success:false,error:"Email provider rejected the request"}}
async function activeClient(clientId:string,workspaceId:string){return db.select({id:clients.id,companyName:clients.companyName,userId:clients.userId,accountManagerId:clients.accountManagerId}).from(clients).where(and(eq(clients.id,clientId),eq(clients.workspaceId,workspaceId),eq(clients.isActive,true))).limit(1).then(r=>r[0]||null)}
async function clientRecipients(clientId:string,workspaceId:string){const c=await activeClient(clientId,workspaceId);if(!c)return {client:null,emails:[] as string[]};const [primary,portal]=await Promise.all([db.select({email:contacts.email}).from(contacts).innerJoin(clients,eq(contacts.clientId,clients.id)).where(and(eq(contacts.clientId,clientId),eq(contacts.isPrimary,true),eq(clients.workspaceId,workspaceId),eq(clients.isActive,true))).limit(1).then(r=>r[0]),c.userId?db.select({email:users.email}).from(users).where(and(eq(users.id,c.userId),eq(users.workspaceId,workspaceId),eq(users.isActive,true))).limit(1).then(r=>r[0]):Promise.resolve(null)]);return {client:c,emails:[email(primary?.email),email(portal?.email)].filter(validEmail)}}
export async function POST(req:NextRequest){
 const session=await auth();if(!session?.user)return NextResponse.json({error:"Unauthorized"},{status:401});
 const role=String(session.user.role||""),userId=String(session.user.id||""),workspaceId=String(session.user.workspaceId||"").trim();if(!workspaceId)return NextResponse.json({error:"Workspace context is required"},{status:403});if(!rateOk(`email:${workspaceId}:${userId}`))return NextResponse.json({error:"Email rate limit exceeded"},{status:429});
 const body=await req.json().catch(()=>null);if(!body)return NextResponse.json({error:"Invalid JSON body"},{status:400});const type=String(body.type||""),to=email(body.to),data=body.data&&typeof body.data==="object"?body.data:{};if(!validEmail(to))return NextResponse.json({error:"Valid recipient required"},{status:400});
 const allowed:Record<string,string[]>={task_assigned:["SUPER_ADMIN","ACCOUNT_MANAGER"],creative_review:["SUPER_ADMIN","ACCOUNT_MANAGER"],invoice_reminder:["SUPER_ADMIN","ACCOUNTANT"],monthly_report:["SUPER_ADMIN","ACCOUNT_MANAGER","ACCOUNTANT"],welcome:["SUPER_ADMIN"]};if(!allowed[type]?.includes(role))return NextResponse.json({error:"Forbidden"},{status:403});
 let subject="",html="";const footer=`<p style="color:#777;font-size:12px;margin-top:28px;border-top:1px solid #ddd;padding-top:12px">VIVIT GROUP · Automated ERP message</p>`;
 if(type==="task_assigned"){
  const taskId=String(data.taskId||"");const [task]=await db.select({id:creativeTasks.id,title:creativeTasks.title,clientId:creativeTasks.clientId,assignedToId:creativeTasks.assignedToId,deadline:creativeTasks.deadline,brief:creativeTasks.brief}).from(creativeTasks).where(and(eq(creativeTasks.id,taskId),eq(creativeTasks.workspaceId,workspaceId))).limit(1);if(!task)return NextResponse.json({error:"Task not found"},{status:404});const c=await activeClient(task.clientId,workspaceId);if(!c||role==="ACCOUNT_MANAGER"&&c.accountManagerId!==userId)return NextResponse.json({error:"Forbidden"},{status:403});const [assignee]=task.assignedToId?await db.select({email:users.email,name:users.name}).from(users).where(and(eq(users.id,task.assignedToId),eq(users.workspaceId,workspaceId),eq(users.isActive,true))).limit(1):[];if(!assignee||email(assignee.email)!==to)return NextResponse.json({error:"Recipient is not the assigned creator"},{status:403});subject=`New task assigned: ${String(task.title).slice(0,120)}`;html=`<h2>New Creative Task</h2><p><b>${esc(task.title)}</b></p><p>Client: ${esc(c.companyName)}</p><p>Deadline: ${esc(task.deadline)}</p><p>${esc(task.brief).slice(0,500)}</p><p><a href="${esc(process.env.NEXTAUTH_URL)}/dashboard/creative/${encodeURIComponent(task.id)}">Open task</a></p>${footer}`;
 }else if(type==="creative_review"){
  const taskId=String(data.taskId||"");const [task]=await db.select({id:creativeTasks.id,title:creativeTasks.title,clientId:creativeTasks.clientId}).from(creativeTasks).where(and(eq(creativeTasks.id,taskId),eq(creativeTasks.workspaceId,workspaceId))).limit(1);if(!task)return NextResponse.json({error:"Task not found"},{status:404});const {client:c,emails}=await clientRecipients(task.clientId,workspaceId);if(!c||role==="ACCOUNT_MANAGER"&&c.accountManagerId!==userId||!emails.includes(to))return NextResponse.json({error:"Recipient is not an authorized client contact"},{status:403});subject=`Creative ready for review: ${String(task.title).slice(0,120)}`;html=`<h2>Creative ready for review</h2><p>${esc(task.title)}</p><p>Please open your VIVIT portal to approve or request changes.</p><p><a href="${esc(process.env.NEXTAUTH_URL)}/dashboard/portal">Open portal</a></p>${footer}`;
 }else if(type==="invoice_reminder"){
  const invoiceId=String(data.invoiceId||"");const [inv]=await db.select({id:financeRecords.id,clientId:financeRecords.clientId,invoiceNumber:financeRecords.invoiceNumber,outstanding:financeRecords.outstanding,dueDate:financeRecords.dueDate}).from(financeRecords).where(and(eq(financeRecords.id,invoiceId),eq(financeRecords.workspaceId,workspaceId))).limit(1);if(!inv)return NextResponse.json({error:"Invoice not found"},{status:404});const {client:c,emails}=await clientRecipients(inv.clientId,workspaceId);if(!c||!emails.includes(to))return NextResponse.json({error:"Recipient is not an authorized client contact"},{status:403});subject=`Invoice reminder: ${inv.invoiceNumber||"VIVIT invoice"}`;html=`<h2>Invoice Reminder</h2><p>Client: ${esc(c.companyName)}</p><p>Invoice: ${esc(inv.invoiceNumber)}</p><p>Outstanding: ${esc(inv.outstanding)} EGP</p><p>Due: ${esc(inv.dueDate)}</p>${footer}`;
 }else if(type==="monthly_report"){
  const clientId=String(data.clientId||"");const {client:c,emails}=await clientRecipients(clientId,workspaceId);if(!c||role==="ACCOUNT_MANAGER"&&c.accountManagerId!==userId||!emails.includes(to))return NextResponse.json({error:"Recipient is not an authorized client contact"},{status:403});subject=`Monthly report: ${String(c.companyName).slice(0,120)}`;html=`<h2>Monthly Performance Report</h2><p>${esc(c.companyName)} · ${esc(data.period)}</p><p>Spend: ${esc(data.spend)} · Leads: ${esc(data.leads)} · ROAS: ${esc(data.roas)}</p><p><a href="${esc(process.env.NEXTAUTH_URL)}/dashboard/portal">Open portal</a></p>${footer}`;
 }else if(type==="welcome"){
  const targetId=String(data.userId||"");const [target]=await db.select({id:users.id,email:users.email,name:users.name,role:users.role,isActive:users.isActive}).from(users).where(and(eq(users.id,targetId),eq(users.workspaceId,workspaceId))).limit(1);if(!target||!target.isActive||email(target.email)!==to)return NextResponse.json({error:"Recipient is not an active ERP user in this workspace"},{status:403});subject="Welcome to VIVIT ERP";html=`<h2>Welcome ${esc(target.name)}</h2><p>Your VIVIT ERP account is ready.</p><p>Email: ${esc(target.email)}</p><p>Role: ${esc(target.role)}</p><p>For security, passwords are never sent by email.</p><p><a href="${esc(process.env.NEXTAUTH_URL)}/login">Sign in</a></p>${footer}`;
 }
 const result=await sendEmail(to,subject,html,type);return NextResponse.json(result,{status:result.success?200:502,headers:{"Cache-Control":"private, no-store","X-Content-Type-Options":"nosniff"}});
}
