export const dynamic="force-dynamic";
import {NextRequest,NextResponse} from "next/server";
import {auth} from "@/lib/auth";
import {db,sql} from "@/lib/db";
import {buildDailyCompetitiveReport,platformFromUrl} from "@/lib/vivito/competitive-intelligence";
const W="default";const rows=(v:any)=>Array.from(v as any) as any[];
async function allowedClientIds(role:string,userId:string){if(["SUPER_ADMIN","ACCOUNTANT"].includes(role))return rows(await db.execute(sql`select id from clients where workspace_id=${W} and is_active=true`)).map(x=>String(x.id));if(role==="ACCOUNT_MANAGER")return rows(await db.execute(sql`select id from clients where workspace_id=${W} and is_active=true and account_manager_id=${userId}`)).map(x=>String(x.id));if(role==="MEDIA_BUYER")return rows(await db.execute(sql`select c.id from clients c join client_media_buyers cmb on cmb.client_id=c.id where c.workspace_id=${W} and c.is_active=true and cmb.media_buyer_id=${userId}`)).map(x=>String(x.id));return[]}
export async function GET(req:NextRequest){const s=await auth();if(!s?.user)return NextResponse.json({error:"Unauthorized"},{status:401});const role=String((s.user as any).role||""),uid=String((s.user as any).id||""),ids=await allowedClientIds(role,uid),clientId=req.nextUrl.searchParams.get("clientId");if(clientId&&!ids.includes(clientId))return NextResponse.json({error:"Forbidden"},{status:403});const target=clientId?[clientId]:ids;if(!target.length)return NextResponse.json({watchlists:[],reports:[]});const list=rows(await db.execute(sql`select w.id,w.client_id,w.competitor_name,w.notes,w.is_active,p.id profile_id,p.platform,p.profile_url,p.handle,p.last_checked_at,p.last_success_at,p.last_error from competitor_watchlists w left join competitor_social_profiles p on p.watchlist_id=w.id where w.workspace_id=${W} and w.client_id in (${sql.join(target.map(id=>sql`${id}`),sql`,`)}) order by w.client_id,w.competitor_name,p.platform`));const reports=rows(await db.execute(sql`select id,client_id,report_date,summary,created_at from competitor_daily_reports where workspace_id=${W} and client_id in (${sql.join(target.map(id=>sql`${id}`),sql`,`)}) order by report_date desc limit 30`));return NextResponse.json({watchlists:list,reports},{headers:{"Cache-Control":"private, no-store"}})}
export async function POST(req:NextRequest){const s=await auth();if(!s?.user)return NextResponse.json({error:"Unauthorized"},{status:401});const role=String((s.user as any).role||""),uid=String((s.user as any).id||""),body=await req.json().catch(()=>({})),op=String(body.op||""),ids=await allowedClientIds(role,uid),clientId=String(body.clientId||"");if(!["SUPER_ADMIN","ACCOUNT_MANAGER","MEDIA_BUYER"].includes(role))return NextResponse.json({error:"Forbidden"},{status:403});if(!clientId||!ids.includes(clientId))return NextResponse.json({error:"Client is outside your authorized scope."},{status:403});try{
 if(op==="add_competitor"){const name=String(body.name||"").trim().slice(0,180);if(!name)return NextResponse.json({error:"Competitor name is required."},{status:400});const w=rows(await db.execute(sql`insert into competitor_watchlists(workspace_id,client_id,competitor_name,notes,created_by) values(${W},${clientId},${name},${String(body.notes||"").slice(0,1000)||null},${uid}) returning id,competitor_name`))[0];const urls=Array.isArray(body.urls)?body.urls.slice(0,12):[];for(const raw of urls){const url=String(raw||"").trim();if(!url)continue;const platform=platformFromUrl(url);await db.execute(sql`insert into competitor_social_profiles(watchlist_id,platform,profile_url) values(${String(w.id)},${platform},${url}) on conflict do nothing`)}return NextResponse.json({ok:true,watch:w},{status:201})}
 if(op==="add_profile"){const watchId=String(body.watchId||""),url=String(body.url||"").trim();const own=rows(await db.execute(sql`select id from competitor_watchlists where id=${watchId} and workspace_id=${W} and client_id=${clientId} limit 1`))[0];if(!own)return NextResponse.json({error:"Watchlist not found in this client."},{status:404});const platform=platformFromUrl(url);const p=rows(await db.execute(sql`insert into competitor_social_profiles(watchlist_id,platform,profile_url) values(${watchId},${platform},${url}) on conflict(watchlist_id,platform,profile_url) do update set is_active=true returning id,platform,profile_url`))[0];return NextResponse.json({ok:true,profile:p},{status:201})}
 if(op==="run_now"){const report=await buildDailyCompetitiveReport(clientId);return NextResponse.json({ok:true,report},{headers:{"Cache-Control":"private, no-store"}})}
 if(op==="remove_competitor"){const watchId=String(body.watchId||"");await db.execute(sql`update competitor_watchlists set is_active=false,updated_at=now() where id=${watchId} and workspace_id=${W} and client_id=${clientId}`);return NextResponse.json({ok:true})}
 return NextResponse.json({error:"Unknown competitive-intelligence operation."},{status:400})
 }catch(e:any){return NextResponse.json({error:String(e?.message||"Competitive intelligence operation failed safely.")},{status:422})}}
