export const dynamic="force-dynamic";
export const maxDuration=300;
import {NextRequest,NextResponse} from "next/server";
import {auth} from "@/lib/auth";
import {db,adPlatformConnections,adCampaigns,clients,auditLogs,sql} from "@/lib/db";
import {and,eq} from "drizzle-orm";
import {connectionAccessToken} from "@/lib/ad-oauth";

const ROLES=["SUPER_ADMIN","MEDIA_BUYER","ACCOUNT_MANAGER"],MEDIA_CUTOFF="2026-07-25";
const n=(v:unknown)=>Number(v||0),iso=(d:Date)=>d.toISOString().slice(0,10);
async function metaJson(url:string){const r=await fetch(url,{cache:"no-store"}),d=await r.json().catch(()=>({}));if(!r.ok||d?.error)throw new Error(d?.error?.message||`Meta API error ${r.status}`);return d}
async function metaPages(url:string,maxPages=100){let next=url,rows:any[]=[];for(let i=0;next&&i<maxPages;i++){const d=await metaJson(next);rows.push(...(d.data||[]));next=String(d?.paging?.next||"")}if(next)throw new Error("Meta response exceeded safe pagination limit");return rows}
async function listMetaCampaigns(accountId:string,token:string){const id=String(accountId).replace(/^act_/i,"");return metaPages(`https://graph.facebook.com/${process.env.META_GRAPH_VERSION||"v23.0"}/act_${id}/campaigns?fields=id,name,status,objective,adsets.limit(100){optimization_goal,promoted_object,destination_type}&limit=250&access_token=${encodeURIComponent(token)}`,50)}
async function listAccountInsights(accountId:string,token:string,from:string,to:string){const id=String(accountId).replace(/^act_/i,""),fields="campaign_id,date_start,spend,impressions,reach,clicks,frequency,ctr,cpc,cpm,actions,action_values,cost_per_action_type",q=new URLSearchParams({level:"campaign",fields,time_range:JSON.stringify({since:from,until:to}),time_increment:"1",action_report_time:"conversion",use_account_attribution_setting:"true",limit:"500",access_token:token});return metaPages(`https://graph.facebook.com/${process.env.META_GRAPH_VERSION||"v23.0"}/act_${id}/insights?${q}`,100)}
function action(row:any,type:string){return n(row?.actions?.find((a:any)=>a.action_type===type)?.value)}
function value(row:any,type:string){return n(row?.action_values?.find((a:any)=>a.action_type===type)?.value)}
function firstAction(row:unknown,types:string[]){for(const type of types){const v=action(row,type);if(v)return{type,value:v}}return{type:types[0]||"result",value:0}}
const MSG=["onsite_conversion.messaging_conversation_started_7d","messaging_conversation_started_7d","onsite_conversion.messaging_first_reply","messaging_first_reply"],ATC=["omni_add_to_cart","add_to_cart","offsite_conversion.fb_pixel_add_to_cart","onsite_web_add_to_cart"],BUY=["omni_purchase","purchase","offsite_conversion.fb_pixel_purchase"],LEAD=["lead","onsite_conversion.lead_grouped","offsite_conversion.fb_pixel_lead"],LPV=["landing_page_view","link_click"],ENG=["post_engagement","video_view"];
type Semantic={kind:"MESSAGES"|"ATC"|"SALES"|"LEADS"|"TRAFFIC"|"REACH"|"ENGAGEMENT";type:string;label:string};
function campaignSemantic(remote:any):Semantic{const o=String(remote?.objective||"").toUpperCase(),nm=String(remote?.name||"").toUpperCase(),sets=remote?.adsets?.data||[],goals=sets.map((x:any)=>String(x.optimization_goal||"").toUpperCase()),events=sets.map((x:any)=>String(x.promoted_object?.custom_event_type||"").toUpperCase()),destinations=sets.map((x:any)=>String(x.destination_type||"").toUpperCase());
 if(events.includes("ADD_TO_CART")||nm.includes("ATC")||nm.includes("ADD TO CART"))return{kind:"ATC",type:"add_to_cart",label:"Add to carts"};
 if(events.includes("PURCHASE"))return{kind:"SALES",type:"purchase",label:"Purchases / Orders"};
 if(o.includes("SALE")||o.includes("CONVERSION"))return{kind:"SALES",type:"purchase",label:"Purchases / Orders"};
 if(destinations.some((x:string)=>/MESSENGER|WHATSAPP|INSTAGRAM_DIRECT|DIRECT/.test(x))||goals.some((x:string)=>/CONVERSATION|MESSAGING/.test(x)))return{kind:"MESSAGES",type:"messaging_conversation_started",label:"Messaging conversations"};
 if(goals.some((x:string)=>/LEAD/.test(x))||o.includes("LEAD"))return{kind:"LEADS",type:"lead",label:"Leads"};
 if(o.includes("TRAFFIC")||goals.includes("LANDING_PAGE_VIEWS")||goals.includes("LINK_CLICKS"))return{kind:"TRAFFIC",type:"landing_page_view",label:"Landing page views"};
 if(o.includes("AWARENESS")||goals.includes("REACH"))return{kind:"REACH",type:"reach",label:"Reach"};
 return{kind:"ENGAGEMENT",type:"post_engagement",label:"Engagements"}}
function primary(row:any,s:Semantic){if(s.kind==="MESSAGES")return firstAction(row,MSG).value;if(s.kind==="ATC")return firstAction(row,ATC).value;if(s.kind==="SALES")return firstAction(row,BUY).value;if(s.kind==="LEADS")return firstAction(row,LEAD).value;if(s.kind==="TRAFFIC")return firstAction(row,LPV).value;if(s.kind==="REACH")return n(row.reach);return firstAction(row,ENG).value}
function commerce(row:unknown){return{addToCart:firstAction(row,ATC).value,purchases:firstAction(row,BUY).value,revenue:value(row,"omni_purchase")||value(row,"purchase")||value(row,"offsite_conversion.fb_pixel_purchase")}}
function dayFromRow(row:any,s:Semantic){const c=commerce(row),spend=n(row.spend),impressions=n(row.impressions),clicks=n(row.clicks),results=primary(row,s);return{date:String(row.date_start||""),spend,impressions,reach:n(row.reach),clicks,frequency:n(row.frequency),ctr:n(row.ctr)||(impressions?clicks/impressions*100:0),cpc:n(row.cpc)||(clicks?spend/clicks:0),cpm:n(row.cpm)||(impressions?spend/impressions*1000:0),results,costPerResult:results?spend/results:0,addToCart:c.addToCart,purchases:c.purchases,revenue:c.revenue,resultType:s.type,resultLabel:s.label,resultKind:s.kind}}
function summaryFromDays(days:any[],s:Semantic){const t=days.reduce((a,d)=>({spend:a.spend+n(d.spend),impressions:a.impressions+n(d.impressions),reach:a.reach+n(d.reach),clicks:a.clicks+n(d.clicks),results:a.results+n(d.results),addToCart:a.addToCart+n(d.addToCart),purchases:a.purchases+n(d.purchases),revenue:a.revenue+n(d.revenue)}),{spend:0,impressions:0,reach:0,clicks:0,results:0,addToCart:0,purchases:0,revenue:0});return{...t,frequency:t.reach?t.impressions/t.reach:0,ctr:t.impressions?t.clicks/t.impressions*100:0,cpc:t.clicks?t.spend/t.clicks:0,cpm:t.impressions?t.spend/t.impressions*1000:0,costPerResult:t.results?t.spend/t.results:0,resultType:s.type,resultLabel:s.label,resultKind:s.kind,source:"META_ACCOUNT_REPORTED"}}
async function persist(c:any,days:any[]){for(const d of days){const date=String(d.date||"").slice(0,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(date))continue;await db.execute(sql`delete from ad_performance_daily where campaign_id=${c.id} and date=${date}::date and breakdown_type='TOTAL' and ad_set_id is null and ad_id is null`);await db.execute(sql`insert into ad_performance_daily(id,campaign_id,date,breakdown_type,breakdown_value,spend,impressions,reach,clicks,results,qualified_leads,purchases,add_to_cart,revenue,frequency,ctr,cpc,cpm,cpl,cost_per_result,cpa,roas) values(gen_random_uuid()::text,${c.id},${date}::date,'TOTAL','ALL',${n(d.spend)},${Math.round(n(d.impressions))},${Math.round(n(d.reach))},${Math.round(n(d.clicks))},${n(d.results)},0,${n(d.purchases)},${n(d.addToCart)},${n(d.revenue)},${n(d.frequency)},${n(d.ctr)},${n(d.cpc)},${n(d.cpm)},${n(d.costPerResult)},${n(d.costPerResult)},${n(d.purchases)?n(d.spend)/n(d.purchases):0},${n(d.spend)?n(d.revenue)/n(d.spend):0})`)}}

export async function POST(req:NextRequest){const s=await auth();if(!s?.user)return NextResponse.json({error:"Unauthorized"},{status:401});const role=String((s.user as any).role),userId=String((s.user as any).id);if(!ROLES.includes(role))return NextResponse.json({error:"Forbidden"},{status:403});const b=await req.json().catch(()=>null),connectionId=String(b?.connectionId||"");if(!connectionId)return NextResponse.json({error:"Connection is required"},{status:400});const [connection]=await db.select().from(adPlatformConnections).where(eq(adPlatformConnections.id,connectionId)).limit(1);if(!connection||connection.platform!=="META")return NextResponse.json({error:"Meta connection not found"},{status:404});const [client]=await db.select().from(clients).where(and(eq(clients.id,connection.clientId),eq(clients.isActive,true))).limit(1);if(!client)return NextResponse.json({error:"Client is archived or missing"},{status:404});if(role==="MEDIA_BUYER"&&client.mediaBuyerId!==userId||role==="ACCOUNT_MANAGER"&&client.accountManagerId!==userId)return NextResponse.json({error:"Client access denied"},{status:403});let token="";try{token=await connectionAccessToken(connection)}catch(e){return NextResponse.json({error:e.message||"Meta authorization is invalid"},{status:409})}if(!token)return NextResponse.json({error:"Connect Meta first"},{status:409});
 try{const from=MEDIA_CUTOFF,to=iso(new Date()),remote=await listMetaCampaigns(connection.adAccountId,token),accountRows=await listAccountInsights(connection.adAccountId,token,from,to),by=new Map<string,unknown[]>();for(const row of accountRows){const id=String(row.campaign_id||"");if(id)by.set(id,[...(by.get(id)||[]),row])}const eligible=remote.filter(r=>by.has(String(r.id))),ids=new Set(eligible.map(r=>String(r.id))),old=await db.select({id:adCampaigns.id,externalId:adCampaigns.externalId}).from(adCampaigns).where(and(eq(adCampaigns.connectionId,connection.id),eq(adCampaigns.platform,"META")));
  // Auto-discovery may archive campaigns that no longer have delivery after the cutoff,
  // but it must never restore a campaign manually archived by a user.
  for(const x of old)if(!ids.has(String(x.externalId)))await db.execute(sql`update ad_campaigns set archived_at=coalesce(archived_at,now()),updated_at=now() where id=${x.id}`);
  let synced=0,failed=0;const failures=[];
  for(const r of eligible){try{const externalId=String(r.id),name=String(r.name||externalId).slice(0,160),objective=String(r.objective||"UNKNOWN"),rows=by.get(externalId)||[],semantic=campaignSemantic(r),existing=(await db.select({id:adCampaigns.id,archivedAt:sql<Date|null>`archived_at`}).from(adCampaigns).where(and(eq(adCampaigns.platform,"META"),eq(adCampaigns.externalId,externalId))).limit(1))[0],[c]=await db.insert(adCampaigns).values({clientId:connection.clientId,connectionId:connection.id,platform:"META",externalId,name,objective,status:String(r.status||"UNKNOWN"),campaignUrl:`https://adsmanager.facebook.com/adsmanager/manage/campaigns?act=${connection.adAccountId}&selected_campaign_ids=${externalId}`,createdBy:userId}).onConflictDoUpdate({target:[adCampaigns.platform,adCampaigns.externalId],set:{connectionId:connection.id,name,objective,status:String(r.status||"UNKNOWN"),updatedAt:new Date()}}).returning();
    if(!existing?.archivedAt)await db.execute(sql`update ad_campaigns set archived_at=null,archived_by=null where id=${c.id}`);
    const days=rows.map(x=>dayFromRow(x,semantic)),summary=summaryFromDays(days,semantic);await persist(c,days);await db.execute(sql`update ad_campaigns set last_sync_at=now(),updated_at=now(),reported_metrics=${JSON.stringify(summary)}::jsonb,reported_period_start=${from}::date,reported_period_end=${to}::date,reported_result_type=${summary.resultType},reported_result_label=${summary.resultLabel} where id=${c.id}`);synced++}catch(e){failed++;failures.push({name:String(r.name||r.id),error:String(e.message||e).slice(0,250)})}}
  await db.update(adPlatformConnections).set({status:failed&&synced===0?"ERROR":"CONNECTED",lastSyncAt:synced?new Date():connection.lastSyncAt,syncError:failed?`${failed} campaign(s) failed · ${failures.slice(0,2).map((x:any)=>`${x.name}: ${x.error}`).join(" | ")}`:null,updatedAt:new Date()}).where(eq(adPlatformConnections.id,connection.id));await db.insert(auditLogs).values({userId,action:"meta_account_synced_semantic_v2",entity:"ad_platform_connections",entityId:connection.id,newValues:JSON.stringify({from,to,synced,failed})});return NextResponse.json({success:true,discovered:eligible.length,synced,failed,from,to,failures})
 }catch(e){const message=String(e.message||"Meta account sync failed").slice(0,700);await db.update(adPlatformConnections).set({status:"ERROR",syncError:message,updatedAt:new Date()}).where(eq(adPlatformConnections.id,connection.id));return NextResponse.json({error:message},{status:400})}}
