// @ts-nocheck
export const dynamic="force-dynamic";
export const maxDuration=300;
import {NextRequest,NextResponse} from "next/server";
import {auth} from "@/lib/auth";
import {db,adPlatformConnections,adCampaigns,adPerformanceDaily,clients,auditLogs,sql} from "@/lib/db";
import {and,eq,isNull} from "drizzle-orm";
import {connectionAccessToken} from "@/lib/ad-oauth";
import {syncCampaign} from "@/lib/ad-platforms";

const ROLES=["SUPER_ADMIN","MEDIA_BUYER","ACCOUNT_MANAGER"];
const MEDIA_CUTOFF="2026-07-25";
const n=(v:any)=>Number(v||0),iso=(d:Date)=>d.toISOString().slice(0,10),sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function metaJson(url:string){const r=await fetch(url,{cache:"no-store"}),d=await r.json().catch(()=>({}));if(!r.ok||d?.error)throw new Error(d?.error?.message||`Meta API error ${r.status}`);return d}
async function metaPages(url:string,maxPages=100){let next=url,rows:any[]=[];for(let i=0;next&&i<maxPages;i++){const d=await metaJson(next);rows.push(...(d.data||[]));next=String(d?.paging?.next||"")}if(next)throw new Error("Meta response exceeded safe pagination limit");return rows}
async function listMetaCampaigns(accountId:string,token:string){const id=String(accountId).replace(/^act_/i,"");return metaPages(`https://graph.facebook.com/${process.env.META_GRAPH_VERSION||"v23.0"}/act_${id}/campaigns?fields=id,name,status,objective&limit=500&access_token=${encodeURIComponent(token)}`,50)}
async function listAccountInsights(accountId:string,token:string,from:string,to:string){const id=String(accountId).replace(/^act_/i,""),fields="campaign_id,date_start,spend,impressions,reach,clicks,frequency,ctr,cpc,cpm,actions,action_values,cost_per_action_type",q=new URLSearchParams({level:"campaign",fields,time_range:JSON.stringify({since:from,until:to}),time_increment:"1",action_report_time:"conversion",use_account_attribution_setting:"true",limit:"500",access_token:token});return metaPages(`https://graph.facebook.com/${process.env.META_GRAPH_VERSION||"v23.0"}/act_${id}/insights?${q}`,100)}
function action(row:any,type:string){return n(row?.actions?.find((a:any)=>a.action_type===type)?.value)}
function value(row:any,type:string){return n(row?.action_values?.find((a:any)=>a.action_type===type)?.value)}
function actionCost(row:any,type:string){return n(row?.cost_per_action_type?.find((a:any)=>a.action_type===type)?.value)}
function firstAction(row:any,types:string[]){for(const type of types){const v=action(row,type);if(v)return {type,value:v,cost:actionCost(row,type)}}return {type:types[0]||"result",value:0,cost:0}}
function resultFor(row:any,objective:string){const o=String(objective||"").toUpperCase();if(o.includes("AWARENESS")||o==="REACH")return {type:"reach",label:"Reach",value:n(row.reach),cost:n(row.reach)?n(row.spend)/n(row.reach):0};if(o.includes("TRAFFIC"))return {...firstAction(row,["landing_page_view","link_click"]),label:"Landing page views"};if(o.includes("LEAD"))return {...firstAction(row,["lead","onsite_conversion.lead_grouped"]),label:"Leads"};if(o.includes("SALES")||o.includes("CONVERSION"))return {...firstAction(row,["omni_purchase","purchase","offsite_conversion.fb_pixel_purchase"]),label:"Purchases"};if(o.includes("ENGAGEMENT"))return {...firstAction(row,["post_engagement","onsite_conversion.messaging_conversation_started_7d","messaging_conversation_started_7d","video_view"]),label:"Engagements"};return {...firstAction(row,["lead","omni_purchase","purchase","onsite_conversion.messaging_conversation_started_7d","landing_page_view","link_click","post_engagement"]),label:"Results"}}
function commerce(row:any){return{addToCart:action(row,"omni_add_to_cart")||action(row,"add_to_cart")||action(row,"offsite_conversion.fb_pixel_add_to_cart"),purchases:action(row,"omni_purchase")||action(row,"purchase")||action(row,"offsite_conversion.fb_pixel_purchase"),revenue:value(row,"omni_purchase")||value(row,"purchase")||value(row,"offsite_conversion.fb_pixel_purchase")}}
function dayFromRow(row:any,objective:string){const r=resultFor(row,objective),c=commerce(row),spend=n(row.spend),impressions=n(row.impressions),clicks=n(row.clicks);return{date:String(row.date_start||""),spend,impressions,reach:n(row.reach),clicks,frequency:n(row.frequency),ctr:n(row.ctr)||(impressions?clicks/impressions*100:0),cpc:n(row.cpc)||(clicks?spend/clicks:0),cpm:n(row.cpm)||(impressions?spend/impressions*1000:0),results:n(r.value),costPerResult:n(r.cost)||(n(r.value)?spend/n(r.value):0),addToCart:c.addToCart,purchases:c.purchases,revenue:c.revenue,resultType:r.type,resultLabel:r.label}}
function summaryFromDays(days:any[],objective:string){const totals=days.reduce((a,d)=>({spend:a.spend+n(d.spend),impressions:a.impressions+n(d.impressions),reach:a.reach+n(d.reach),clicks:a.clicks+n(d.clicks),results:a.results+n(d.results),addToCart:a.addToCart+n(d.addToCart),purchases:a.purchases+n(d.purchases),revenue:a.revenue+n(d.revenue)}),{spend:0,impressions:0,reach:0,clicks:0,results:0,addToCart:0,purchases:0,revenue:0}),probe=resultFor({},objective);return{...totals,frequency:totals.reach?totals.impressions/totals.reach:0,ctr:totals.impressions?totals.clicks/totals.impressions*100:0,cpc:totals.clicks?totals.spend/totals.clicks:0,cpm:totals.impressions?totals.spend/totals.impressions*1000:0,costPerResult:totals.results?totals.spend/totals.results:0,resultType:days[0]?.resultType||probe.type,resultLabel:days[0]?.resultLabel||probe.label,source:"META_ACCOUNT_REPORTED"}}
function permanentMetaError(message:string){const m=message.toLowerCase();return m.includes("does not have permission")||m.includes("permissions error")||m.includes("invalid oauth")||m.includes("access token")||m.includes("unsupported get request")||m.includes("belongs to ad account")||m.includes("cannot be loaded due to missing permissions")}
async function syncWithRetry(input:any){let last:any;for(let attempt=1;attempt<=3;attempt++){try{return await syncCampaign(input)}catch(e:any){last=e;const message=String(e?.message||e||"Sync failed");if(attempt===3||permanentMetaError(message))throw e;await sleep(attempt*1200)}}throw last}
async function persist(c:any,days:any[]){for(const day of days||[]){const date=String(day?.date||"").slice(0,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(date))continue;const spend=n(day.spend),results=n(day.results),purchases=n(day.purchases),impressions=Math.max(0,Math.round(n(day.impressions))),clicks=Math.max(0,Math.round(n(day.clicks))),revenue=n(day.revenue),reach=Math.max(0,Math.round(n(day.reach))),frequency=n(day.frequency),addToCart=n(day.addToCart),ctr=n(day.ctr)||(impressions?clicks/impressions*100:0),cpc=n(day.cpc)||(clicks?spend/clicks:0),cpm=n(day.cpm)||(impressions?spend/impressions*1000:0),cost=n(day.costPerResult)||(results?spend/results:0);await db.execute(sql`delete from ad_performance_daily where campaign_id=${c.id} and date=${date}::date and breakdown_type='TOTAL' and ad_id is null`);await db.execute(sql`insert into ad_performance_daily(id,campaign_id,date,breakdown_type,breakdown_value,spend,impressions,reach,clicks,results,qualified_leads,purchases,add_to_cart,revenue,frequency,ctr,cpc,cpm,cpl,cost_per_result,cpa,roas) values(gen_random_uuid()::text,${c.id},${date}::date,'TOTAL','ALL',${spend},${impressions},${reach},${clicks},${results},0,${purchases},${addToCart},${revenue},${frequency},${ctr},${cpc},${cpm},${cost},${cost},${purchases?spend/purchases:0},${spend?revenue/spend:0})`)}}

export async function POST(req:NextRequest){
 const s=await auth();if(!s?.user)return NextResponse.json({error:"Unauthorized"},{status:401});
 const role=String((s.user as any).role),userId=String((s.user as any).id);if(!ROLES.includes(role))return NextResponse.json({error:"Forbidden"},{status:403});
 const b=await req.json().catch(()=>null),connectionId=String(b?.connectionId||"");if(!connectionId)return NextResponse.json({error:"Connection is required"},{status:400});
 const [connection]=await db.select().from(adPlatformConnections).where(eq(adPlatformConnections.id,connectionId)).limit(1);if(!connection||connection.platform!=="META")return NextResponse.json({error:"Meta connection not found"},{status:404});
 const [client]=await db.select().from(clients).where(and(eq(clients.id,connection.clientId),eq(clients.isActive,true))).limit(1);if(!client)return NextResponse.json({error:"Client is archived or missing"},{status:404});
 if(role==="MEDIA_BUYER"&&client.mediaBuyerId!==userId||role==="ACCOUNT_MANAGER"&&client.accountManagerId!==userId)return NextResponse.json({error:"Client access denied"},{status:403});
 let token="";try{token=await connectionAccessToken(connection)}catch(e:any){return NextResponse.json({error:e.message||"Meta authorization is invalid"},{status:409})}if(!token)return NextResponse.json({error:"Connect Meta first to authorize this ad account."},{status:409});
 try{
  const from=MEDIA_CUTOFF,to=iso(new Date()),remote=await listMetaCampaigns(connection.adAccountId,token);let accountRows:any[]=[],accountError="";
  try{accountRows=await listAccountInsights(connection.adAccountId,token,from,to)}catch(e:any){accountError=String(e.message||"Account insights unavailable").slice(0,300)}
  const rowsByCampaign=new Map<string,any[]>();for(const row of accountRows){const id=String(row.campaign_id||"");if(!id)continue;const list=rowsByCampaign.get(id)||[];list.push(row);rowsByCampaign.set(id,list)}
  const eligibleRemote=accountError?remote:remote.filter(r=>rowsByCampaign.has(String(r.id)));
  if(!accountError){const eligibleIds=new Set(eligibleRemote.map(r=>String(r.id))),existingRows=await db.select({id:adCampaigns.id,externalId:adCampaigns.externalId}).from(adCampaigns).where(and(eq(adCampaigns.connectionId,connection.id),eq(adCampaigns.platform,"META")));for(const old of existingRows){if(!eligibleIds.has(String(old.externalId)))await db.execute(sql`update ad_campaigns set archived_at=coalesce(archived_at,now()), archived_by=${userId}, updated_at=now() where id=${old.id}`)}}
  let synced=0,failed=0;const failures:any[]=[];
  for(const r of eligibleRemote){
   const externalId=String(r.id),[existing]=await db.select().from(adCampaigns).where(and(eq(adCampaigns.platform,"META"),eq(adCampaigns.externalId,externalId))).limit(1);
   if(existing&&existing.clientId!==connection.clientId){failed++;failures.push({id:externalId,name:String(r.name||externalId),error:"Campaign belongs to another VIVIT client"});continue}
   const [campaign]=await db.insert(adCampaigns).values({clientId:connection.clientId,connectionId:connection.id,platform:"META",externalId,name:String(r.name||`Meta Campaign ${externalId}`).slice(0,160),status:String(r.status||"UNKNOWN"),campaignUrl:`https://adsmanager.facebook.com/adsmanager/manage/campaigns?act=${connection.adAccountId}&selected_campaign_ids=${externalId}`,createdBy:userId}).onConflictDoUpdate({target:[adCampaigns.platform,adCampaigns.externalId],set:{connectionId:connection.id,name:String(r.name||`Meta Campaign ${externalId}`).slice(0,160),status:String(r.status||"UNKNOWN"),updatedAt:new Date()}}).returning();
   await db.execute(sql`update ad_campaigns set archived_at=null,archived_by=null where id=${campaign.id}`);
   try{
    let days:any[]=[],summary:any;
    if(!accountError){days=(rowsByCampaign.get(externalId)||[]).map(row=>dayFromRow(row,String(r.objective||"")));summary=summaryFromDays(days,String(r.objective||""))}
    else{const result=await syncWithRetry({platform:"META",campaignId:externalId,adAccountId:connection.adAccountId,accessToken:token,start:from,end:to});days=result.days||[];summary=result.summary;if(!days.length){await db.execute(sql`update ad_campaigns set archived_at=coalesce(archived_at,now()),archived_by=${userId},updated_at=now() where id=${campaign.id}`);continue}}
    await persist(campaign,days);
    await db.update(adCampaigns).set({name:String(r.name||campaign.name),status:String(r.status||campaign.status),lastSyncAt:new Date(),updatedAt:new Date()}).where(eq(adCampaigns.id,campaign.id));
    if(summary)await db.execute(sql`update ad_campaigns set reported_metrics=${JSON.stringify(summary)}::jsonb,reported_period_start=${from}::date,reported_period_end=${to}::date,reported_result_type=${summary.resultType||null},reported_result_label=${summary.resultLabel||null} where id=${campaign.id}`);
    synced++;
   }catch(e:any){failed++;failures.push({id:externalId,name:String(r.name||externalId),error:String(e.message||"Sync failed").slice(0,300)})}
  }
  const hiddenBeforeCutoff=Math.max(0,remote.length-eligibleRemote.length),failureSummary=failures.length?failures.slice(0,2).map(x=>`${x.name}: ${x.error}`).join(" | ").slice(0,650):null;
  await db.update(adPlatformConnections).set({status:failed&&synced===0?"ERROR":"CONNECTED",lastSyncAt:synced?new Date():connection.lastSyncAt,syncError:failed?`${failed} campaign(s) failed${failureSummary?` · ${failureSummary}`:""}`:accountError?`Account-level insights fallback used · ${accountError}`:null,updatedAt:new Date()}).where(eq(adPlatformConnections.id,connection.id));
  await db.insert(auditLogs).values({userId,action:"meta_account_discovered_and_synced",entity:"ad_platform_connections",entityId:connection.id,newValues:JSON.stringify({campaigns:eligibleRemote.length,totalRemote:remote.length,hiddenBeforeCutoff,synced,failed,mode:accountError?"PER_CAMPAIGN_FALLBACK":"ACCOUNT_INSIGHTS",from,to,accountError:accountError||null,failures:failures.slice(0,5)})});
  return NextResponse.json({success:true,discovered:eligibleRemote.length,totalRemote:remote.length,hiddenBeforeCutoff,synced,failed,mode:accountError?"PER_CAMPAIGN_FALLBACK":"ACCOUNT_INSIGHTS",from,to,accountError:accountError||null,failures:failures.slice(0,10)});
 }catch(e:any){const message=String(e.message||"Meta account sync failed").slice(0,700);await db.update(adPlatformConnections).set({status:"ERROR",syncError:message,updatedAt:new Date()}).where(eq(adPlatformConnections.id,connection.id));return NextResponse.json({error:message},{status:400})}
}
