export const dynamic="force-dynamic";
import {NextRequest,NextResponse} from "next/server";
import {auth} from "@/lib/auth";
import {db,auditLogs,sql} from "@/lib/db";
import {executeVivitoAction,VivitoActionError} from "@/lib/vivito/executor";
import {executeVivitoExtendedAction,isVivitoExtendedAction} from "@/lib/vivito/executor-extended";
import {executeVivitoOperatorAction,isVivitoOperatorAction} from "@/lib/vivito/executor-operator";
import {VIVITO_ACTION_CATALOG,type VivitoActionOp} from "@/lib/vivito/action-engine";
import {buildVivitoDryRun,decideVivitoApproval} from "@/lib/vivito/approval-policy";

const W="default";
const clean=(v:any,n=120)=>String(v||"").trim().slice(0,n);
const noStore={"Cache-Control":"private, no-store"};
type VivitoExecutionResult={success:boolean;action?:string;entityId?:string|null;message?:string;[key:string]:unknown};
async function execute(op:VivitoActionOp,args:any,role:string,userId:string):Promise<VivitoExecutionResult>{if(isVivitoOperatorAction(op))return executeVivitoOperatorAction(op,args||{},role,userId) as Promise<VivitoExecutionResult>;return isVivitoExtendedAction(op)?executeVivitoExtendedAction(op,args||{},role,userId) as Promise<VivitoExecutionResult>:executeVivitoAction(op,args||{},role,userId) as Promise<VivitoExecutionResult>}

export async function POST(req:NextRequest){
 const session=await auth();if(!session?.user)return NextResponse.json({error:"Unauthorized"},{status:401});
 const body=await req.json().catch(()=>null);if(!body)return NextResponse.json({error:"Invalid request."},{status:400});
 const role=String((session.user as any).role||""),userId=String((session.user as any).id||"");
 if(body.retryOf){const retryId=clean(body.retryOf,120);const owner=role==="SUPER_ADMIN"?sql``:sql`and user_id=${userId}`;const prior=Array.from(await db.execute(sql`select new_values from audit_logs where workspace_id=${W} and id=${retryId} and action='vivito_action_failed' ${owner} limit 1`)) as any[];if(!prior[0])return NextResponse.json({error:"Retry source was not found or is not accessible."},{status:404,headers:noStore});let saved:any={};try{saved=JSON.parse(String(prior[0].new_values||"{}"))}catch{}body.op=saved.op;body.args=saved.args||{};body.requestId=`retry:${retryId}`;}
 const requestId=clean(body.requestId,100),plan=Array.isArray(body.plan)?body.plan.slice(0,8):null;
 if(plan?.length){
  if(plan.length<2)return NextResponse.json({error:"Multi-step execution requires at least two steps."},{status:400,headers:noStore});
  const normalized=plan.map((s:any)=>({op:clean(s?.op,60) as VivitoActionOp,args:s?.args&&typeof s.args==="object"&&!Array.isArray(s.args)?s.args:{},summary:clean(s?.summary,500)}));
  if(normalized.some(s=>!VIVITO_ACTION_CATALOG[s.op]))return NextResponse.json({error:"One or more VIVITO plan steps are unsupported."},{status:400,headers:noStore});
  const decisions=normalized.map(s=>({op:s.op,...buildVivitoDryRun(s.op,s.args,role)}));
  if(body.dryRun===true)return NextResponse.json({success:true,dryRun:true,plan:true,steps:decisions,ready:decisions.every(d=>d.ready),willWrite:false},{headers:noStore});
  if(decisions.some(d=>d.approval.mode==="BLOCK"))return NextResponse.json({error:"One or more VIVITO plan steps are not authorized for your role.",steps:decisions},{status:403,headers:noStore});
  if(decisions.some(d=>d.missingFields.length))return NextResponse.json({error:"One or more VIVITO plan steps are missing required fields.",steps:decisions},{status:400,headers:noStore});
  const requiresConfirmation=decisions.some(d=>d.approval.requiresConfirmation);if(requiresConfirmation&&body.confirm!==true)return NextResponse.json({error:"Explicit confirmation is required before VIVITO executes this plan.",steps:decisions},{status:409,headers:noStore});
  const rootId=requestId||crypto.randomUUID(),results:VivitoExecutionResult[]=[];
  for(let i=0;i<normalized.length;i++){const step=normalized[i],stepKey=`${rootId}:${i}`;const previous=Array.from(await db.execute(sql`select new_values from audit_logs where workspace_id=${W} and user_id=${userId} and action='vivito_plan_step_executed' and new_values::jsonb->>'stepKey'=${stepKey} order by created_at desc limit 1`)) as any[];if(previous[0]){let saved:any={};try{saved=JSON.parse(String(previous[0].new_values||"{}"))}catch{}results.push(saved.result||{success:true,duplicate:true});continue}try{const result=await execute(step.op,step.args,role,userId);results.push(result);await db.insert(auditLogs).values({workspaceId:W,userId,action:"vivito_plan_step_executed",entity:"vivito_plan",entityId:rootId,newValues:JSON.stringify({requestId:rootId,stepKey,stepIndex:i,op:step.op,summary:step.summary,result,approval:decisions[i].approval})} as any)}catch(error){const status=error instanceof VivitoActionError?error.status:500,message=error instanceof Error?error.message:"VIVITO stopped the plan safely.";await db.insert(auditLogs).values({workspaceId:W,userId,action:"vivito_plan_stopped",entity:"vivito_plan",entityId:rootId,newValues:JSON.stringify({requestId:rootId,stepIndex:i,op:step.op,args:step.args,message,completedSteps:results.length})} as any);return NextResponse.json({success:false,partial:results.length>0,requestId:rootId,completedSteps:results,stoppedAt:i,error:message,details:error instanceof VivitoActionError?error.details||null:null},{status,headers:noStore})}}
  await db.insert(auditLogs).values({workspaceId:W,userId,action:"vivito_plan_executed",entity:"vivito_plan",entityId:rootId,newValues:JSON.stringify({requestId:rootId,stepCount:results.length,results})} as any);return NextResponse.json({success:true,requestId:rootId,plan:true,results},{headers:noStore})
 }
 const op=clean(body.op,60) as VivitoActionOp;if(!VIVITO_ACTION_CATALOG[op])return NextResponse.json({error:"Unsupported VIVITO action."},{status:400,headers:noStore});
 const args=body.args&&typeof body.args==="object"&&!Array.isArray(body.args)?body.args:{};const dry=buildVivitoDryRun(op,args,role);if(body.dryRun===true)return NextResponse.json({success:true,...dry},{headers:noStore});
 if(dry.approval.mode==="BLOCK")return NextResponse.json({error:dry.approval.reason,approval:dry.approval},{status:403,headers:noStore});if(dry.missingFields.length)return NextResponse.json({error:"Required action fields are missing.",missingFields:dry.missingFields,approval:dry.approval},{status:400,headers:noStore});if(dry.approval.requiresConfirmation&&body.confirm!==true)return NextResponse.json({error:"Explicit confirmation is required before VIVITO writes to the ERP.",approval:dry.approval},{status:409,headers:noStore});
 if(requestId){const done=Array.from(await db.execute(sql`select id,new_values from audit_logs where workspace_id=${W} and user_id=${userId} and action='vivito_action_executed' and new_values::jsonb->>'requestId'=${requestId} order by created_at desc limit 1`)) as any[];if(done[0]){let previous:any={};try{previous=JSON.parse(String(done[0].new_values||"{}"))}catch{}return NextResponse.json({success:true,duplicate:true,action:op,result:previous.result||null},{headers:noStore})}}
 try{const result=await execute(op,args,role,userId);await db.insert(auditLogs).values({workspaceId:W,userId,action:"vivito_action_executed",entity:"vivito",entityId:String(result.entityId||requestId||crypto.randomUUID()),newValues:JSON.stringify({requestId:requestId||null,op,result,approval:decideVivitoApproval(op,role)})} as any);return NextResponse.json({success:true,action:op,result},{headers:noStore})}catch(error){const status=error instanceof VivitoActionError?error.status:500,message=error instanceof Error?error.message:"VIVITO could not execute the action safely.";const failureId=crypto.randomUUID();await db.insert(auditLogs).values({id:failureId,workspaceId:W,userId,action:"vivito_action_failed",entity:"vivito",entityId:requestId||failureId,newValues:JSON.stringify({requestId:requestId||null,op,args,message,status})} as any).catch(()=>{});if(error instanceof VivitoActionError)return NextResponse.json({error:error.message,details:error.details||null,failureId},{status:error.status,headers:noStore});console.error("VIVITO action execution failed",error);return NextResponse.json({error:"VIVITO could not execute the action safely.",failureId},{status:500,headers:noStore})}
}
