"use client";
import { useState } from "react";

type Entity = "clients" | "tasks" | "sales" | "finance" | "media" | "expenses";
type ReportPayload={headers:string[];rows:unknown[][];count:number;error?:string};
const errorMessage=(error:unknown,fallback:string)=>error instanceof Error&&error.message?error.message:fallback;

const ENTITIES:{value:Entity;label:string;icon:string;fields:string[]}[]=[
 {value:"clients",label:"Clients",icon:"🏢",fields:["Company","Industry","Health Score","Churn Risk","Monthly Retainer","Media Budget","Contract Value","Performance Score"]},
 {value:"tasks",label:"Tasks",icon:"🎨",fields:["Title","Type","Status","Priority","Client ID","Assigned To","Deadline","Revisions","Posted"]},
 {value:"sales",label:"Sales",icon:"🎯",fields:["Company","Contact","Stage","Source","Value","Probability","Industry","Expected Close"]},
 {value:"finance",label:"Finance",icon:"💰",fields:["Client ID","Month","Year","Retainer","Media Fee","Extra","Total","Paid","Outstanding","Status"]},
 {value:"media",label:"Media",icon:"📣",fields:["Client ID","Platform","Date","Ad Spend","Leads","Purchases","Revenue","ROAS","CPL","Agency Fee"]},
 {value:"expenses",label:"Expenses",icon:"🧾",fields:["Category","Description","Amount","Date"]},
];
const ROLE_ENTITIES:Record<string,Entity[]>={SUPER_ADMIN:["clients","tasks","sales","finance","media","expenses"],ACCOUNT_MANAGER:["clients","tasks","media"],ACCOUNTANT:["clients","finance","expenses"],MEDIA_BUYER:["clients","media"],SALES:["sales"]};

function compareCells(a:unknown,b:unknown){
 const an=typeof a==="number"?a:Number(String(a??"").replace(/[^0-9.-]/g,""));
 const bn=typeof b==="number"?b:Number(String(b??"").replace(/[^0-9.-]/g,""));
 if(Number.isFinite(an)&&Number.isFinite(bn)) return an-bn;
 const ad=Date.parse(String(a??"")),bd=Date.parse(String(b??""));
 if(Number.isFinite(ad)&&Number.isFinite(bd)) return ad-bd;
 return String(a??"").localeCompare(String(b??""),undefined,{numeric:true,sensitivity:"base"});
}

export function ReportsClient({role}:{role:string}){
 const visibleEntities=ENTITIES.filter(e=>(ROLE_ENTITIES[role]||[]).includes(e.value));
 const [entity,setEntity]=useState<Entity>(visibleEntities[0]?.value||"clients");
 const [selFields,setFields]=useState<string[]>([]);
 const [data,setData]=useState<ReportPayload|null>(null);
 const [loading,setLoading]=useState(false);
 const [format,setFormat]=useState<"table"|"json">("table");
 const [sortCol,setSortCol]=useState<number|null>(null);
 const [sortDir,setSortDir]=useState<"asc"|"desc">("asc");
 const [visibleRows,setRows]=useState(50);
 const [error,setError]=useState("");
 const selectedEntity=visibleEntities.find(e=>e.value===entity)||visibleEntities[0];
 const activeFields=data?(selFields.length?data.headers.filter(h=>selFields.includes(h)):data.headers):[];
 const activeIndexes=data?activeFields.map(h=>data.headers.indexOf(h)):[];
 const projectedRows=data?data.rows.map(row=>activeIndexes.map(i=>row[i])):[];
 const sortedRows=data?[...projectedRows].sort((a,b)=>{if(sortCol===null)return 0;const result=compareCells(a[sortCol],b[sortCol]);return sortDir==="asc"?result:-result}):[];
 const handleSort=(col:number)=>{if(sortCol===col)setSortDir(d=>d==="asc"?"desc":"asc");else{setSortCol(col);setSortDir("asc")}};
 const toggleField=(f:string)=>setFields(prev=>prev.includes(f)?prev.filter(x=>x!==f):[...prev,f]);
 const selectAll=()=>setFields([...(selectedEntity?.fields||[])]);
 const clearAll=()=>setFields([]);
 const runReport=async()=>{setLoading(true);setError("");setRows(50);try{const r=await fetch(`/api/export?entity=${entity}`);const d:ReportPayload=await r.json();if(!r.ok)throw new Error(d.error||"The report could not be generated.");setData(d)}catch(e:unknown){setData(null);setError(errorMessage(e,"The report could not be generated."))}finally{setLoading(false)}};
 const download=(kind:"csv"|"json")=>{if(!data)return;let blob:Blob;if(kind==="csv"){const rows=[activeFields,...projectedRows];const csv=rows.map(r=>r.map(c=>`"${String(c).replace(/"/g,'""')}"`).join(",")).join("\n");blob=new Blob([csv],{type:"text/csv"})}else{const records=projectedRows.map(row=>Object.fromEntries(activeFields.map((h,i)=>[h,row[i]])));blob=new Blob([JSON.stringify(records,null,2)],{type:"application/json"})}const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`vivit-${entity}-${new Date().toISOString().slice(0,10)}.${kind}`;a.click();URL.revokeObjectURL(url)};
 const quickExport=async(target:Entity)=>{setError("");try{const response=await fetch(`/api/export?entity=${target}`);const payload:ReportPayload=await response.json();if(!response.ok)throw new Error(payload.error||"The export could not be generated.");const records=payload.rows.map(row=>Object.fromEntries(payload.headers.map((header,index)=>[header,row[index]])));const blob=new Blob([JSON.stringify(records,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`vivit-${target}-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)}catch(e:unknown){setError(errorMessage(e,"The export could not be generated."))}};
 if(!selectedEntity)return <div className="card"><div className="card-body">No reports available for this role.</div></div>;
 return <div className="reports-ui"><style>{`
  .reports-ui{display:flex;flex-direction:column;gap:12px;min-width:0}.report-card{background:var(--card-bg);border:1px solid var(--card-border);border-radius:8px;padding:14px;box-shadow:none}.report-title{font-size:12.5px;font-weight:750;color:var(--text-primary);margin-bottom:10px}.entity-grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:6px}.entity-btn{min-height:52px;border:1px solid var(--card-border);background:var(--card-bg);border-radius:6px;color:var(--text-secondary);cursor:pointer;font:inherit;transition:border-color .14s ease,background-color .14s ease,color .14s ease}.entity-btn:hover{border-color:#c8c8cf;background:#fafafa}.entity-btn.active{border-color:var(--erp-accent);background:var(--erp-accent-soft);color:var(--erp-accent-strong);box-shadow:inset 2px 0 0 var(--erp-accent)}.field-head{display:flex;justify-content:space-between;align-items:center;gap:10px;margin:13px 0 8px}.field-head p{font-size:10px;font-weight:800;color:var(--text-muted);text-transform:uppercase;letter-spacing:.06em}.field-actions{display:flex;gap:7px}.link-btn{border:0;background:transparent;color:var(--erp-accent-strong);font:inherit;font-size:11px;font-weight:700;cursor:pointer}.field-list{display:flex;flex-wrap:wrap;gap:5px}.field-chip{border:1px solid var(--card-border);background:var(--card-bg);color:var(--text-secondary);border-radius:6px;padding:5px 7px;font:inherit;font-size:10.5px;cursor:pointer}.field-chip.active{border-color:var(--erp-accent);background:var(--erp-accent-soft);color:var(--erp-accent-strong);font-weight:700}.report-controls{display:flex;align-items:center;gap:6px;flex-wrap:wrap;margin-top:13px}.format-toggle{display:flex;border:1px solid var(--card-border);border-radius:6px;overflow:hidden}.format-toggle button{border:0;background:var(--card-bg);color:var(--text-muted);padding:7px 9px;font:inherit;font-size:10.5px;font-weight:700;cursor:pointer}.format-toggle button.active{background:var(--erp-accent-soft);color:var(--erp-accent-strong)}.result-card{background:var(--card-bg);border:1px solid var(--card-border);border-radius:8px;overflow:hidden}.result-head{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:10px 13px;border-bottom:1px solid var(--card-border);background:#fbfbfc}.result-table{overflow:auto;-webkit-overflow-scrolling:touch}.result-table table{min-width:760px}.report-json{padding:14px;font-size:11px;color:var(--text-secondary);overflow:auto;max-height:420px;background:var(--bg-tertiary)}.quick-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:6px}.quick-btn{display:flex;align-items:center;gap:8px;padding:9px 10px;border:1px solid var(--card-border);background:var(--card-bg);border-radius:6px;color:var(--text-primary);font:inherit;text-align:left;cursor:pointer;transition:border-color .14s ease,background-color .14s ease}.quick-btn:hover{border-color:#c8c8cf;background:#fafafa}
  @media(max-width:900px){.entity-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.quick-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
  @media(max-width:560px){.report-card{padding:11px}.entity-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.entity-btn{min-height:48px}.report-controls{align-items:stretch}.report-controls>.btn,.report-controls>.btn-grad,.report-controls>.btn-outline{flex:1;min-width:130px}.format-toggle{width:100%}.format-toggle button{flex:1;min-height:42px}.quick-grid{grid-template-columns:1fr}.field-head{align-items:flex-start}.result-head{align-items:flex-start;flex-wrap:wrap}}
 `}</style>
 <section className="report-card"><div className="report-title">Custom Report Builder</div><div className="entity-grid">{visibleEntities.map(e=><button key={e.value} type="button" onClick={()=>{setEntity(e.value);setFields([]);setData(null)}} className={`entity-btn${entity===e.value?" active":""}`} aria-pressed={entity===e.value}><div style={{fontSize:16}}>{e.icon}</div><div style={{fontSize:10.5,fontWeight:700,marginTop:1}}>{e.label}</div></button>)}</div><div className="field-head"><p>Select fields</p><div className="field-actions"><button type="button" onClick={selectAll} className="link-btn">Select all</button><button type="button" onClick={clearAll} className="link-btn">Clear</button></div></div><div className="field-list">{selectedEntity.fields.map(f=><button key={f} type="button" onClick={()=>toggleField(f)} className={`field-chip${selFields.includes(f)?" active":""}`} aria-pressed={selFields.includes(f)}>{selFields.includes(f)?"✓ ":""}{f}</button>)}</div><div className="report-controls"><div className="format-toggle">{(["table","json"] as const).map(f=><button type="button" key={f} onClick={()=>setFormat(f)} className={format===f?"active":""} aria-pressed={format===f}>{f==="table"?"Table":"JSON"}</button>)}</div><button type="button" onClick={runReport} disabled={loading} className="btn btn-primary">{loading?"Loading…":"Run Report"}</button>{data&&<><button type="button" onClick={()=>download("csv")} className="btn btn-secondary">CSV</button><button type="button" onClick={()=>download("json")} className="btn btn-secondary">JSON</button><button type="button" onClick={()=>window.print()} className="btn btn-secondary">Print / PDF</button></>}</div>{error&&<p className="form-error" role="alert" style={{marginTop:10}}>{error}</p>}</section>
 {data&&<section className="result-card"><div className="result-head"><b style={{fontSize:12,color:"var(--text-primary)"}}>{data.count} records — {selectedEntity.label}</b><span className="badge badge-blue">{format.toUpperCase()}</span></div>{format==="table"?<div className="result-table"><table className="data-table"><thead><tr>{activeFields.map((h,i)=><th key={h} onClick={()=>handleSort(i)} style={{cursor:"pointer"}}>{h}{sortCol===i?(sortDir==="asc"?" ↑":" ↓"):""}</th>)}</tr></thead><tbody>{sortedRows.slice(0,visibleRows).map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell==null?"—":String(cell).slice(0,80)}</td>)}</tr>)}</tbody></table>{sortedRows.length>visibleRows&&<div style={{padding:10,textAlign:"center"}}><button type="button" onClick={()=>setRows(v=>v+50)} className="btn btn-secondary">Load 50 more</button></div>}</div>:<pre className="report-json">{JSON.stringify(projectedRows.slice(0,20).map(row=>Object.fromEntries(activeFields.map((h,i)=>[h,row[i]]))),null,2)}</pre>}</section>}
 <section className="report-card"><div className="report-title">Quick Export</div><div className="quick-grid">{visibleEntities.map(e=><button key={e.value} type="button" onClick={()=>quickExport(e.value)} className="quick-btn"><span style={{fontSize:16}}>{e.icon}</span><span><b style={{display:"block",fontSize:11.5}}>{e.label}</b><small style={{color:"var(--text-muted)"}}>JSON export</small></span></button>)}</div></section>
 </div>;
}