export const dynamic="force-dynamic";
import {NextRequest,NextResponse} from "next/server";
import {db,apiKeys,sql} from "@/lib/db";
import {eq,and} from "drizzle-orm";
import crypto from "crypto";
const READ_PERMISSIONS=new Set(["read","read_write","admin"]);
async function authenticateAPIKey(req:NextRequest){const raw=req.headers.get("x-api-key")??req.headers.get("authorization")?.replace(/^Bearer\s+/i,"");if(!raw)return null;const keyHash=crypto.createHash("sha256").update(raw).digest("hex");const [key]=await db.select().from(apiKeys).where(and(eq(apiKeys.keyHash,keyHash),eq(apiKeys.isActive,true))).limit(1);if(!key||!READ_PERMISSIONS.has(String(key.permissions||"")))return null;await db.update(apiKeys).set({lastUsedAt:new Date()}).where(eq(apiKeys.id,key.id));return key}
type MetricRow={platform:string;adSpend:number|string|null;results:number|string|null;revenue:number|string|null};
export async function GET(req:NextRequest){const key=await authenticateAPIKey(req);if(!key)return NextResponse.json({error:"Invalid API key"},{status:401});const now=new Date(),monthStart=new Date(now.getFullYear(),now.getMonth(),1),rows=Array.from(await db.execute<MetricRow>(sql`select a.platform,coalesce(sum(p.spend),0) "adSpend",coalesce(sum(p.results),0) results,coalesce(sum(p.revenue),0) revenue from ad_performance_daily p join ad_campaigns a on a.id=p.campaign_id join clients c on c.id=a.client_id where a.workspace_id=${key.workspaceId} and c.workspace_id=${key.workspaceId} and c.is_active=true and a.archived_at is null and a.deleted_at is null and p.date>=${monthStart} and p.breakdown_type='TOTAL' and p.ad_set_id is null and p.ad_id is null group by a.platform`)),data=rows.map(row=>{const adSpend=Number(row.adSpend||0),revenue=Number(row.revenue||0);return{platform:row.platform,adSpend,results:Number(row.results||0),leads:Number(row.results||0),revenue,roas:adSpend?revenue/adSpend:0}});return NextResponse.json({data,period:"MTD",source:"ad_performance_daily:TOTAL",resultLabel:"Results"},{headers:{"Cache-Control":"private, no-store","X-Content-Type-Options":"nosniff"}})}
