import {test,expect} from "@playwright/test";

const password=process.env.E2E_PASSWORD||"";
const base=process.env.E2E_BASE_URL||"http://127.0.0.1:3000";
const matrix=[
 {role:"SUPER_ADMIN",email:"e2e.super@vivit.local",routes:["/dashboard","/dashboard/universe","/dashboard/media/control-center","/dashboard/creative","/dashboard/finance","/dashboard/analytics","/dashboard/ai-studio","/dashboard/settings"]},
 {role:"ACCOUNT_MANAGER",email:"e2e.account@vivit.local",routes:["/dashboard/universe","/dashboard/media/control-center","/dashboard/creative","/dashboard/calendar","/dashboard/reports","/dashboard/ai-studio","/dashboard/files","/dashboard/settings"]},
 {role:"MEDIA_BUYER",email:"e2e.media@vivit.local",routes:["/dashboard/universe","/dashboard/media/control-center","/dashboard/media/sync","/dashboard/creative","/dashboard/calendar","/dashboard/ai-studio","/dashboard/files","/dashboard/settings"]},
 {role:"CREATOR",email:"e2e.creator@vivit.local",routes:["/dashboard/creative","/dashboard/calendar","/dashboard/ai-studio","/dashboard/files","/dashboard/notifications","/dashboard/settings"]},
 {role:"ACCOUNTANT",email:"e2e.accountant@vivit.local",routes:["/dashboard/clients","/dashboard/finance","/dashboard/clients/accounts-payment","/dashboard/contracts","/dashboard/forecast","/dashboard/reports","/dashboard/files","/dashboard/settings"]},
 {role:"SALES",email:"e2e.sales@vivit.local",routes:["/dashboard/sales","/dashboard/whatsapp","/dashboard/calendar","/dashboard/reports","/dashboard/ai-studio","/dashboard/files","/dashboard/settings"]},
 {role:"CLIENT",email:"e2e.client@vivit.local",routes:["/dashboard/portal","/dashboard/calendar","/dashboard/ai-studio","/dashboard/files","/dashboard/notifications","/dashboard/settings"]},
];

async function login(page,email){
 await page.goto(`${base}/login`,{waitUntil:"load",timeout:20000});
 const emailInput=page.getByLabel("Email address");
 const passwordInput=page.getByLabel("Password");
 const signInButton=page.getByRole("button",{name:/Enter Marketing/i});
 await expect(emailInput).toBeVisible();
 await expect(passwordInput).toBeVisible();
 await expect(signInButton).toBeEnabled();
 await page.waitForFunction(()=>document.readyState==="complete");
 await emailInput.fill(email);
 await passwordInput.fill(password);
 await expect(emailInput).toHaveValue(email);
 await expect(passwordInput).toHaveValue(password);
 const authOrNavigation=Promise.race([
  page.waitForResponse(response=>response.url().includes("/api/auth/callback/credentials")&&response.request().method()==="POST"&&response.status()>=200&&response.status()<400,{timeout:20000}),
  page.waitForURL(url=>url.pathname.startsWith("/apps")||url.pathname.startsWith("/dashboard"),{timeout:20000}),
 ]);
 await Promise.all([authOrNavigation,signInButton.click()]);
 try{
  await page.waitForURL(url=>url.pathname.startsWith("/apps")||url.pathname.startsWith("/dashboard"),{timeout:20000});
 }catch(error){
  const alert=page.getByRole("alert");
  const message=await alert.count()?await alert.first().textContent():"";
  throw new Error(`Login did not leave /login for ${email}${message?`: ${message.trim()}`:""}. Current URL: ${page.url()}. ${error instanceof Error?error.message:String(error)}`);
 }
 await expect(page).not.toHaveURL(/\/login/);
}
async function switchIdentity(page,email){await page.context().clearCookies();await login(page,email)}
async function certifyPage(page,route){const response=await page.goto(`${base}${route}`,{waitUntil:"domcontentloaded",timeout:20000});expect(response?.status()??200,`${route} should not return 5xx`).toBeLessThan(500);await expect(page).not.toHaveURL(/\/login/);await expect(page.locator("body")).not.toContainText(/Application error|Internal Server Error/i);await expect(page.locator("#dashboard-content")).toBeVisible();const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth);expect(overflow,`${route} must not cause page-level horizontal overflow`).toBeLessThanOrEqual(4)}
async function expectDenied(page,route,heading){await page.goto(`${base}${route}`,{waitUntil:"domcontentloaded",timeout:20000});await page.waitForFunction(r=>location.pathname!==r,route,{timeout:10000});await expect(page).not.toHaveURL(new RegExp(`${route.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}$`));if(heading)await expect(page.getByRole("heading",{name:heading,exact:true})).toHaveCount(0)}
function languageSelect(page){return page.locator("select").filter({has:page.locator('option[value="ar"]')}).first()}
async function waitForDomQuiet(page,quietMs=400,timeout=5000){await page.evaluate(({quietMs,timeout})=>new Promise(resolve=>{let quietTimer;const done=()=>{clearTimeout(quietTimer);clearTimeout(hardTimer);observer.disconnect();resolve(true)},observer=new MutationObserver(()=>{clearTimeout(quietTimer);quietTimer=setTimeout(done,quietMs)}),hardTimer=setTimeout(done,timeout);observer.observe(document.documentElement,{subtree:true,childList:true,attributes:true,characterData:true});quietTimer=setTimeout(done,quietMs)}),{quietMs,timeout})}
async function submitServerAction(page,route,submit,settle){const pending=page.waitForResponse(response=>response.request().method()==="POST"&&new URL(response.url()).pathname===route&&Boolean(response.request().headers()["next-action"]),{timeout:20000});await submit();const response=await pending;expect(response.status(),`${route} server action should return 2xx`).toBeGreaterThanOrEqual(200);expect(response.status(),`${route} server action should return 2xx`).toBeLessThan(300);await waitForDomQuiet(page);if(settle)await settle()}

test.describe.configure({mode:"serial"});
for(const entry of matrix)test(`${entry.role} authenticates and renders its core workspace`,async({page})=>{await login(page,entry.email);for(const route of entry.routes)await certifyPage(page,route)});

test("settings persist Arabic RTL and return cleanly to English",async({page})=>{await login(page,"e2e.super@vivit.local");await certifyPage(page,"/dashboard/settings");const language=languageSelect(page);await expect(language).toBeVisible();await language.selectOption("ar");await expect(page.locator("html")).toHaveAttribute("dir","rtl");await expect(page.locator(".app-main-shell")).toHaveAttribute("dir","rtl");expect(await page.evaluate(()=>localStorage.getItem("vivit-lang"))).toBe("ar");await page.reload({waitUntil:"domcontentloaded"});await expect(page.locator("html")).toHaveAttribute("dir","rtl");expect(await page.evaluate(()=>localStorage.getItem("vivit-lang"))).toBe("ar");await languageSelect(page).selectOption("en");await expect(page.locator("html")).toHaveAttribute("dir","ltr");expect(await page.evaluate(()=>localStorage.getItem("vivit-lang"))).toBe("en")});

test("global search keyboard lifecycle traps and restores focus",async({page})=>{await login(page,"e2e.super@vivit.local");await certifyPage(page,"/dashboard");const trigger=page.getByRole("button",{name:"Open global search"});await trigger.focus();await page.keyboard.press("Control+k");const dialog=page.getByRole("dialog",{name:"Global search"});await expect(dialog).toBeVisible();await expect(page.getByLabel("Search clients, tasks, leads and more")).toBeFocused();await page.keyboard.press("Tab");await page.keyboard.press("Shift+Tab");await expect(page.getByLabel("Search clients, tasks, leads and more")).toBeFocused();await page.keyboard.press("Escape");await expect(dialog).not.toBeVisible();await expect(trigger).toBeFocused()});

test("Sales creates updates advances and archives a lead",async({page},testInfo)=>{await login(page,"e2e.sales@vivit.local");await certifyPage(page,"/dashboard/sales");const company=`E2E ${testInfo.project.name} Prospect`,add=page.locator("#add form");await add.locator('input[name="companyName"]').fill(company);await add.locator('input[name="contactPerson"]').fill("Enterprise Buyer");await add.locator('input[name="phone"]').fill("+201000000001");await add.locator('input[name="email"]').fill(`buyer-${testInfo.project.name}@example.test`);await add.locator('input[name="estimatedValue"]').fill("42000");await add.locator('select[name="source"]').selectOption("REFERRAL");await add.locator('input[name="industry"]').fill("Technology");await add.locator('textarea[name="notes"]').fill("Created by isolated enterprise browser certification");let card=page.locator(".lead-card").filter({hasText:company});await submitServerAction(page,"/dashboard/sales",()=>add.getByRole("button",{name:"Add to Pipeline"}).click(),()=>expect(card).toBeVisible({timeout:10000}));const contacted=page.locator(".stage").filter({hasText:"Contacted"}).locator(".lead-card").filter({hasText:company});await submitServerAction(page,"/dashboard/sales",()=>card.getByRole("button",{name:/Contacted/}).click(),()=>expect(contacted).toBeVisible({timeout:10000}));card=contacted;await card.locator('input[name="phone"]').fill("+201000000099");await card.locator('textarea[name="notes"]').fill("E2E contact updated");await expect(card.locator('input[name="phone"]')).toHaveValue("+201000000099");await submitServerAction(page,"/dashboard/sales",()=>card.getByRole("button",{name:"Save Contact & Notes"}).click(),()=>expect(page.locator(".lead-card").filter({hasText:company}).locator('input[name="phone"]')).toHaveValue("+201000000099",{timeout:10000}));card=page.locator(".lead-card").filter({hasText:company});await submitServerAction(page,"/dashboard/sales",()=>card.getByRole("button",{name:"Archive Lead"}).click(),()=>expect(page.locator(".lead-card").filter({hasText:company})).toHaveCount(0,{timeout:10000}))});

test("Creative delivery moves from creator through manager to client approval",async({page},testInfo)=>{const project=testInfo.project.name,taskId=`e2e-task-${project}`,title=`E2E Enterprise Creative ${project}`,route=`/dashboard/creative/${taskId}`;await login(page,"e2e.creator@vivit.local");await certifyPage(page,route);const delivery=page.locator(".ct-submit");await delivery.locator('input[name="url"]').fill(`https://example.com/${taskId}.mp4`);await delivery.locator('input[name="notes"]').fill("Enterprise E2E delivery");await submitServerAction(page,route,()=>delivery.getByRole("button",{name:"Save delivery link"}).click(),()=>expect(page.locator(".ct-stats")).toContainText("REVIEW",{timeout:10000}));await switchIdentity(page,"e2e.account@vivit.local");await certifyPage(page,route);const approve=page.getByRole("button",{name:"Approve"});await expect(approve).toBeVisible();await submitServerAction(page,route,()=>approve.click(),()=>expect(page.locator(".ct-stats")).toContainText("APPROVED",{timeout:10000}));await switchIdentity(page,"e2e.client@vivit.local");await certifyPage(page,"/dashboard/portal");const reviewCard=page.locator(".creative-card").filter({hasText:title});await expect(reviewCard).toBeVisible({timeout:10000});await submitServerAction(page,"/dashboard/portal",()=>reviewCard.getByRole("button",{name:"Approve"}).click(),()=>expect(page.locator(".creative-card").filter({hasText:title})).toHaveCount(0,{timeout:10000}));await certifyPage(page,route);await expect(page.locator(".ct-stats")).toContainText("APPROVED")});

test("Accountant configures and persists a client payment profile",async({page},testInfo)=>{const project=testInfo.project.name,company=`E2E Finance Client ${project}`,note=`Enterprise AP ${project}`;await login(page,"e2e.accountant@vivit.local");await certifyPage(page,"/dashboard/clients/accounts-payment");const setup=page.locator(".setup-card").filter({hasText:company});await expect(setup).toBeVisible({timeout:10000});await setup.locator('input[name="responsibleName"]').fill("Global Finance Contact");await setup.locator('input[name="phone"]').fill("+201111111111");await setup.locator('input[name="amountDue"]').fill("12345.67");await setup.locator('input[name="currency"]').fill("USD");await setup.locator('input[name="paymentDay"]').fill("15");await setup.locator('input[name="notes"]').fill(note);await setup.getByRole("button",{name:"Save finance setup"}).click();await expect(page.locator(".setup-card").filter({hasText:company})).toHaveCount(0,{timeout:10000});let row=page.locator(".pay-table tbody tr").filter({hasText:company});await expect(row).toBeVisible();await expect(row).toContainText("PENDING");await expect(row).toContainText(note);await page.reload({waitUntil:"domcontentloaded"});row=page.locator(".pay-table tbody tr").filter({hasText:company});await expect(row).toBeVisible();await expect(row).toContainText("PENDING");await expect(row).toContainText(note)});

test("sensitive modules deny roles outside their boundary",async({page})=>{await login(page,"e2e.creator@vivit.local");await expectDenied(page,"/dashboard/finance","Finance");await switchIdentity(page,"e2e.client@vivit.local");await expectDenied(page,"/dashboard/sales","Sales CRM");await switchIdentity(page,"e2e.accountant@vivit.local");await expectDenied(page,"/dashboard/media/control-center","Media Buying Control Center");await switchIdentity(page,"e2e.super@vivit.local");await expectDenied(page,"/dashboard/portal","E2E Global Client")});

test("mobile authenticated shell keeps navigation usable",async({browser})=>{const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),page=await context.newPage();await login(page,"e2e.creator@vivit.local");await certifyPage(page,"/dashboard/creative");const menu=page.getByRole("button",{name:/Open full menu/i});await expect(menu).toBeVisible();await menu.click();const drawer=page.getByRole("dialog",{name:"Full navigation"});await expect(drawer).toBeVisible();await page.keyboard.press("Escape");await expect(drawer).not.toBeVisible();await menu.click();await drawer.getByRole("link",{name:/Files/i}).click();await page.waitForURL(/\/dashboard\/files/);await expect(drawer).not.toBeVisible();await certifyPage(page,"/dashboard/files");await context.close()});
