export const dynamic="force-dynamic";
import {NextRequest,NextResponse} from "next/server";
import {auth} from "@/lib/auth";
import {db,clients,adCampaigns,adPerformanceDaily,sql} from "@/lib/db";
import {and,eq,inArray,gte,lte,isNull} from "drizzle-orm";
type MetricRow={campaignId?:unknown;spend?:unknown;impressions?:unknown;reach?:unknown;clicks?:unknown;results?:unknown;purchases?:unknown;addToCart?:unknown;revenue?:unknown};
type IdRow={id:unknown};
type MetricTotals={spend:number;impressions:number;reach:number;clicks:number;results:number;purchases:number;addToCart:number;revenue:number};
const n=(v:unknown)=>Number(v||0),DATE=/^\d{4}-\d{2}-\d{2}$/;
function valid(v:string){if(!DATE.test(v))return false;const d=new Date(v+"T00:00:00Z");return d.toISOString().slice(0,10)===v}
function summarize(rows:MetricRow[]){const x=rows.reduce<MetricTotals>((a,p)=>{a.spend+=n(p.spend);a.impressions+=n(p.impressions);a.reach+=n(p.reach);a.clicks+=n(p.clicks);a.results+=n(p.results);a.purchases+=n(p.purchases);a.addToCart+=n(p.addToCart);a.revenue+=n(p.revenue);return a},{spend:0,impressions:0,reach:0,clicks:0,results:0,purchases:0,addToCart:0,revenue:0});return{...x,ctr:x.impressions?x.clicks/x.impressions*100:0,roas:x.spend?x.revenue/x.spend:0,frequency:x.reach?x.impressions/x.reach:0}}
export async function GET(req:NextRequest){const s=await auth();if(!s?.user)return NextResponse.json({error:"Unauthorized"},{status:401});const role=String(s.user.role),uid=String(s.user.id),workspaceId=String(s.user.workspaceId||"");if(!workspaceId)return NextResponse.json({error:"Workspace unavailable"},{status:403});if(!["SUPER_ADMIN","ACCOUNT_MANAGER","MEDIA_BUYER"].includes(role))return NextResponse.json({error:"Forbidden"},{status:403});const from=req.nextUrl.searchParams.get("from")||"",to=req.nextUrl.searchParams.get("to")||"";if(!valid(from)||!valid(to)||from>to)return NextResponse.json({error:"Invalid date range"},{status:400});const ownership=role==="ACCOUNT_MANAGER"?eq(clients.accountManagerId,uid):role==="MEDIA_BUYER"?eq(clients.mediaBuyerId,uid):sql`true`;const owned=await db.select({id:clients.id}).from(clients).where(and(eq(clients.workspaceId,workspaceId),eq(clients.isActive,true),ownership));const clientIds=owned.map(x=>x.id);if(!clientIds.length)return NextResponse.json({portfolio:summarize([]),accounts:{},archivedSpend:0,archivedCampaigns:0});const campaigns=await db.select({id:adCampaigns.id,connectionId:adCampaigns.connectionId}).from(adCampaigns).where(and(eq(adCampaigns.workspaceId,workspaceId),inArray(adCampaigns.clientId,clientIds))),ids=campaigns.map(x=>x.id);if(!ids.length)return NextResponse.json({portfolio:summarize([]),accounts:{},archivedSpend:0,archivedCampaigns:0});const rows=await db.select().from(adPerformanceDaily).where(and(inArray(adPerformanceDaily.campaignId,ids),gte(adPerformanceDaily.date,new Date(from+"T00:00:00Z")),lte(adPerformanceDaily.date,new Date(to+"T23:59:59Z")),eq(adPerformanceDaily.breakdownType,"TOTAL"),isNull(adPerformanceDaily.adSetId),isNull(adPerformanceDaily.adId)));const byCampaign=new Map<string,MetricRow[]>();for(const r of rows)byCampaign.set(r.campaignId,[...(byCampaign.get(r.campaignId)||[]),r]);const accountMap:Record<string,MetricRow[]>={};for(const c of campaigns){const key=String(c.connectionId||"unlinked");accountMap[key]=accountMap[key]||[];accountMap[key].push(...(byCampaign.get(c.id)||[]))}const accounts=Object.fromEntries(Object.entries(accountMap).map(([k,v])=>[k,summarize(v)]));const archived=Array.from(await db.execute(sql`select c.id from ad_campaigns c where c.workspace_id=${workspaceId} and c.client_id in (${sql.join(clientIds.map(id=>sql`${id}`),sql`, `)}) and c.archived_at is not null`)) as IdRow[],archivedIds=archived.map(x=>String(x.id)),archivedRows=archivedIds.length?rows.filter(r=>archivedIds.includes(String(r.campaignId))):[];return NextResponse.json({portfolio:summarize(rows),accounts,archivedSpend:summarize(archivedRows).spend,archivedCampaigns:archivedIds.length},{headers:{"Cache-Control":"private, no-store"}})}
