// @ts-nocheck
export const dynamic="force-dynamic";
import {NextRequest,NextResponse} from "next/server";
import {auth} from "@/lib/auth";
import {db,clients,adCampaigns,adPlatformConnections,adPerformanceDaily,sql} from "@/lib/db";
import {and,eq,inArray,gte,lte,isNull} from "drizzle-orm";
const n=(v:any)=>Number(v||0),DATE=/^\d{4}-\d{2}-\d{2}$/;
function valid(v:string){if(!DATE.test(v))return false;const d=new Date(v+"T00:00:00Z");return d.toISOString().slice(0,10)===v}
function summarize(rows:any[]){const x=rows.reduce((a:any,p:any)=>{a.spend+=n(p.spend);a.impressions+=n(p.impressions);a.reach+=n(p.reach);a.clicks+=n(p.clicks);a.results+=n(p.results);a.purchases+=n(p.purchases);a.addToCart+=n(p.addToCart);a.revenue+=n(p.revenue);return a},{spend:0,impressions:0,reach:0,clicks:0,results:0,purchases:0,addToCart:0,revenue:0});return{...x,ctr:x.impressions?x.clicks/x.impressions*100:0,roas:x.spend?x.revenue/x.spend:0,frequency:x.reach?x.impressions/x.reach:0}}
export async function GET(req:NextRequest){const s=await auth();if(!s?.user)return NextResponse.json({error:"Unauthorized"},{status:401});const role=String((s.user as any).role),uid=String((s.user as any).id);if(!["SUPER_ADMIN","ACCOUNT_MANAGER","MEDIA_BUYER"].includes(role))return NextResponse.json({error:"Forbidden"},{status:403});const from=req.nextUrl.searchParams.get("from")||"",to=req.nextUrl.searchParams.get("to")||"";if(!valid(from)||!valid(to)||from>to)return NextResponse.json({error:"Invalid date range"},{status:400});const owned=await db.select({id:clients.id}).from(clients).where(and(eq(clients.isActive,true),role==="ACCOUNT_MANAGER"?eq(clients.accountManagerId,uid):role==="MEDIA_BUYER"?eq(clients.mediaBuyerId,uid):eq(clients.workspaceId,"default")));const clientIds=owned.map(x=>x.id);if(!clientIds.length)return NextResponse.json({portfolio:summarize([]),accounts:{},archivedSpend:0,archivedCampaigns:0});const campaigns=await db.select({id:adCampaigns.id,connectionId:adCampaigns.connectionId}).from(adCampaigns).where(inArray(adCampaigns.clientId,clientIds)),ids=campaigns.map(x=>x.id);if(!ids.length)return NextResponse.json({portfolio:summarize([]),accounts:{},archivedSpend:0,archivedCampaigns:0});const rows=await db.select().from(adPerformanceDaily).where(and(inArray(adPerformanceDaily.campaignId,ids),gte(adPerformanceDaily.date,new Date(from+"T00:00:00Z")),lte(adPerformanceDaily.date,new Date(to+"T23:59:59Z")),eq(adPerformanceDaily.breakdownType,"TOTAL"),isNull(adPerformanceDaily.adSetId),isNull(adPerformanceDaily.adId)));const byCampaign=new Map<string,any[]>();for(const r of rows)byCampaign.set(r.campaignId,[...(byCampaign.get(r.campaignId)||[]),r]);const accountMap:any={};for(const c of campaigns){const m=summarize(byCampaign.get(c.id)||[]),key=String(c.connectionId||"unlinked");accountMap[key]=accountMap[key]||[];accountMap[key].push(...(byCampaign.get(c.id)||[]))}const accounts=Object.fromEntries(Object.entries(accountMap).map(([k,v])=>[k,summarize(v as any[])]));const archived=Array.from(await db.execute(sql`select c.id from ad_campaigns c where c.client_id in (${sql.join(clientIds.map(id=>sql`${id}`),sql`, `)}) and c.archived_at is not null`)) as any[],archivedIds=archived.map(x=>x.id),archivedRows=archivedIds.length?rows.filter((r:any)=>archivedIds.includes(r.campaignId)):[];return NextResponse.json({portfolio:summarize(rows),accounts,archivedSpend:summarize(archivedRows).spend,archivedCampaigns:archivedIds.length},{headers:{"Cache-Control":"private, no-store"}})}
