export const dynamic="force-dynamic";
import { auth } from "@/lib/auth";
import { redirect } from "next/navigation";
import { db,clients,creativeTasks,mediaMetrics,salesLeads,financeRecords } from "@/lib/db";
import { eq,and,gte,count,sum,notInArray } from "drizzle-orm";
import { Role } from "@/lib/types";
const money=(n:number)=>`EGP ${new Intl.NumberFormat("en-US",{maximumFractionDigits:0}).format(Number(n||0))}`;
export default async function AnalyticsPage(){const session=await auth();if(!session?.user)redirect("/login");if((session.user as any).role!==Role.SUPER_ADMIN)redirect("/dashboard");const now=new Date(),monthStart=new Date(now.getFullYear(),now.getMonth(),1),year=now.getFullYear();const [clientCount,media,finance,taskCount,activeTasks,leads,won,lost]=await Promise.all([
 db.select({n:count()}).from(clients).where(eq(clients.isActive,true)),
 db.select({spend:sum(mediaMetrics.adSpend),revenue:sum(mediaMetrics.revenue),leads:sum(mediaMetrics.leads),impressions:sum(mediaMetrics.impressions),clicks:sum(mediaMetrics.clicks)}).from(mediaMetrics).where(gte(mediaMetrics.date,monthStart)),
 db.select({total:sum(financeRecords.totalRevenue),paid:sum(financeRecords.paid),outstanding:sum(financeRecords.outstanding)}).from(financeRecords).where(eq(financeRecords.year,year)),
 db.select({n:count()}).from(creativeTasks).where(gte(creativeTasks.createdAt,monthStart)),db.select({n:count()}).from(creativeTasks).where(notInArray(creativeTasks.status,["COMPLETED","REJECTED"])),db.select({n:count()}).from(salesLeads).where(notInArray(salesLeads.stage,["WON","LOST"])),db.select({n:count()}).from(salesLeads).where(eq(salesLeads.stage,"WON")),db.select({n:count()}).from(salesLeads).where(eq(salesLeads.stage,"LOST"))]);
 const m=media[0]||{},f=finance[0]||{},spend=Number(m.spend||0),revenue=Number(m.revenue||0),leadN=Number(m.leads||0),imps=Number(m.impressions||0),clicks=Number(m.clicks||0),roas=spend?revenue/spend:0,cpl=leadN?spend/leadN:0,ctr=imps?clicks/imps*100:0,total=Number(f.total||0),paid=Number(f.paid||0),out=Number(f.outstanding||0),collection=total?paid/total*100:0;
 const cards=[{l:"Active Clients",v:String(clientCount[0]?.n||0),s:"Current active accounts"},{l:"Month Ad Spend",v:money(spend),s:`${leadN} leads`},{l:"ROAS",v:`${roas.toFixed(2)}x`,s:`CPL ${money(cpl)}`},{l:"YTD Revenue",v:money(total),s:`${collection.toFixed(0)}% collected`},{l:"Outstanding",v:money(out),s:"Open receivables"},{l:"Creative This Month",v:String(taskCount[0]?.n||0),s:`${activeTasks[0]?.n||0} active`},{l:"Sales Pipeline",v:String(leads[0]?.n||0),s:`${won[0]?.n||0} won · ${lost[0]?.n||0} lost`},{l:"CTR",v:`${ctr.toFixed(2)}%`,s:`${imps.toLocaleString()} impressions`}];
 return <div style={{display:"flex",flexDirection:"column",gap:18}}><div><h1 className="page-title">Analytics</h1><p className="page-subtitle">Live agency performance from finance, media, sales and creative data</p></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:12}}>{cards.map(c=><div className="card" key={c.l}><div className="card-body"><p style={{fontSize:11,color:"var(--text-muted)",fontWeight:800,textTransform:"uppercase"}}>{c.l}</p><b style={{display:"block",fontSize:24,marginTop:5,color:"var(--text-primary)"}}>{c.v}</b><p style={{fontSize:11.5,color:"var(--text-muted)",marginTop:4}}>{c.s}</p></div></div>)}</div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:14}}><section className="card"><div className="card-body"><h2 className="card-title">Media Efficiency</h2>{[{l:"Spend",v:money(spend)},{l:"Revenue",v:money(revenue)},{l:"Leads",v:leadN.toLocaleString()},{l:"Clicks",v:clicks.toLocaleString()},{l:"CTR",v:`${ctr.toFixed(2)}%`},{l:"ROAS",v:`${roas.toFixed(2)}x`}].map(x=><div key={x.l} style={{display:"flex",justifyContent:"space-between",padding:"9px 0",borderBottom:"1px solid var(--card-border)",fontSize:12.5}}><span>{x.l}</span><b>{x.v}</b></div>)}</div></section><section className="card"><div className="card-body"><h2 className="card-title">Financial Health</h2>{[{l:"Invoiced YTD",v:money(total)},{l:"Collected",v:money(paid)},{l:"Outstanding",v:money(out)},{l:"Collection Rate",v:`${collection.toFixed(1)}%`}].map(x=><div key={x.l} style={{display:"flex",justifyContent:"space-between",padding:"11px 0",borderBottom:"1px solid var(--card-border)",fontSize:12.5}}><span>{x.l}</span><b>{x.v}</b></div>)}</div></section></div></div>}
