"use client";
import {useCallback,useEffect,useState} from "react";

type Approval={id:string;client_id:string;report_id:string;company_name:string;cadence:string;report_period_start:string;report_period_end:string;generated_at:string};
export default function CompetitorApprovalsPage(){
 const [items,setItems]=useState<Approval[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await fetch("/api/vivito/competitive-report/approval",{cache:"no-store"}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Could not load approvals");setItems(d.approvals||[])}catch(e){setError(e instanceof Error?e.message:"Could not load approvals")}finally{setLoading(false)}},[]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 async function decide(item:Approval,decision:"APPROVED"|"REJECTED"){if(decision==="APPROVED"&&!confirm(`Approve and email this report to ${item.company_name}?`))return;const note=decision==="REJECTED"?prompt("Optional rejection note")||"":"";setBusy(item.id);setError("");try{const r=await fetch("/api/vivito/competitive-report/approval",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({approvalId:item.id,decision,note})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Decision failed");await load()}catch(e){setError(e instanceof Error?e.message:"Decision failed")}finally{setBusy("")}}
 return <div style={{display:"grid",gap:18}}><div><h1 className="page-title">Competitor Report Approvals</h1><p className="page-subtitle">Review Vivito reports before anything is sent to the client.</p></div>{error&&<div className="form-error" role="alert">{error}</div>}{loading?<div className="card"><div className="empty-state">Loading approvals…</div></div>:!items.length?<div className="card"><div className="empty-state"><b>No reports waiting for approval.</b></div></div>:<div className="card"><div className="responsive-table"><table className="data-table"><thead><tr><th>Client</th><th>Cadence</th><th>Period</th><th>Report</th><th>Decision</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><b>{item.company_name}</b></td><td>{String(item.cadence||"").replaceAll("_"," ")}</td><td>{item.report_period_start} → {item.report_period_end}</td><td><a className="btn btn-ghost btn-sm" target="_blank" rel="noreferrer" href={`/api/vivito/competitive-report/${item.client_id}?runId=${item.report_id}`}>Open PDF ↗</a></td><td><div style={{display:"flex",gap:6,flexWrap:"wrap"}}><button className="btn btn-success btn-sm" disabled={busy===item.id} onClick={()=>decide(item,"APPROVED")}>Approve & send</button><button className="btn btn-danger btn-sm" disabled={busy===item.id} onClick={()=>decide(item,"REJECTED")}>Reject</button></div></td></tr>)}</tbody></table></div></div>}</div>;
}