// @ts-nocheck -- Drizzle's generated insert shape is narrower than the live schema.
export const dynamic="force-dynamic";
import { NextRequest,NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { db,fileDocuments,auditLogs,clients,creativeTasks } from "@/lib/db";
import { desc,eq,or,inArray,and } from "drizzle-orm";

const base=()=>process.env.SUPABASE_URL!;
const headers=()=>({apikey:process.env.SUPABASE_SERVICE_KEY!,Authorization:`Bearer ${process.env.SUPABASE_SERVICE_KEY!}`});
export async function GET(){const session=await auth();if(!session?.user)return NextResponse.json({error:"Unauthorized"},{status:401});const role=(session.user as any).role;const userId=(session.user as any).id;let scope:any=eq(fileDocuments.uploadedBy,userId);if(role==="SUPER_ADMIN")scope=eq(fileDocuments.workspaceId,"default");else if(role==="CLIENT"){const owned=await db.select({id:clients.id}).from(clients).where(eq(clients.userId,userId));scope=owned.length?or(eq(fileDocuments.uploadedBy,userId),inArray(fileDocuments.clientId,owned.map(x=>x.id))):eq(fileDocuments.uploadedBy,userId);}else if(role==="ACCOUNT_MANAGER"||role==="MEDIA_BUYER"){const owned=await db.select({id:clients.id}).from(clients).where(and(eq(clients.isActive,true),role==="ACCOUNT_MANAGER"?eq(clients.accountManagerId,userId):eq(clients.mediaBuyerId,userId)));scope=owned.length?or(eq(fileDocuments.uploadedBy,userId),inArray(fileDocuments.clientId,owned.map(x=>x.id))):eq(fileDocuments.uploadedBy,userId);}else if(role==="CREATOR"){const tasks=await db.select({id:creativeTasks.id}).from(creativeTasks).where(eq(creativeTasks.assignedToId,userId));scope=tasks.length?or(eq(fileDocuments.uploadedBy,userId),inArray(fileDocuments.taskId,tasks.map(x=>x.id))):eq(fileDocuments.uploadedBy,userId);}const rows=await db.select().from(fileDocuments).where(scope).orderBy(desc(fileDocuments.createdAt)).limit(100);const files=await Promise.all(rows.map(async f=>{const r=await fetch(`${base()}/storage/v1/object/sign/vivit-files/${f.storagePath}`,{method:"POST",headers:{...headers(),"Content-Type":"application/json"},body:JSON.stringify({expiresIn:900})});const d=await r.json();return {...f,url:d.signedURL?`${base()}/storage/v1${d.signedURL}`:null};}));return NextResponse.json({files});}
export async function POST(req:NextRequest){const session=await auth();if(!session?.user)return NextResponse.json({error:"Unauthorized"},{status:401});const data=await req.formData();const file=data.get("file") as File|null;if(!file)return NextResponse.json({error:"Choose a file."},{status:400});if(file.size>15*1024*1024)return NextResponse.json({error:"Maximum file size is 15 MB."},{status:400});const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"-");const userId=(session.user as any).id;const path=`${new Date().getFullYear()}/${userId}/${crypto.randomUUID()}-${safe}`;await fetch(`${base()}/storage/v1/bucket`,{method:"POST",headers:{...headers(),"Content-Type":"application/json"},body:JSON.stringify({id:"vivit-files",name:"vivit-files",public:false,file_size_limit:15728640})}).catch(()=>null);const upload=await fetch(`${base()}/storage/v1/object/vivit-files/${path}`,{method:"POST",headers:{...headers(),"Content-Type":file.type||"application/octet-stream","x-upsert":"false"},body:Buffer.from(await file.arrayBuffer())});if(!upload.ok)return NextResponse.json({error:"Upload failed. Check the Storage configuration."},{status:500});const [row]=await db.insert(fileDocuments).values({uploadedBy:userId,name:file.name,storagePath:path,mimeType:file.type,sizeBytes:file.size,category:String(data.get("category")||"GENERAL"),clientId:String(data.get("clientId")||"")||null,taskId:String(data.get("taskId")||"")||null}).returning();await db.insert(auditLogs).values({userId,action:"file_uploaded",entity:"file_documents",entityId:row.id,newValues:JSON.stringify({name:file.name,size:file.size})});return NextResponse.json({success:true,file:row});}
