"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {usePathname} from "next/navigation";
type Item={icon:string;label:string;href:string;roles:string[]};type QuickItem={icon:string;label:string;href:string};
const OPS=["SUPER_ADMIN","ACCOUNT_MANAGER","MEDIA_BUYER"],EMP=["SUPER_ADMIN","HR","ACCOUNT_MANAGER","MEDIA_BUYER","CREATOR","ACCOUNTANT","SALES"];
const SECTIONS:{label:string;items:Item[]}[]=[
 {label:"MAIN",items:[{icon:"🏠",label:"Dashboard",href:"/dashboard",roles:["SUPER_ADMIN"]},{icon:"🏢",label:"Clients",href:"/dashboard/universe",roles:OPS},{icon:"🎯",label:"Sales CRM",href:"/dashboard/sales",roles:["SUPER_ADMIN","SALES"]},{icon:"💬",label:"WhatsApp",href:"/dashboard/whatsapp",roles:[...OPS,"SALES"]},{icon:"📣",label:"Media Control",href:"/dashboard/media/control-center",roles:OPS},{icon:"🔄",label:"Platform Sync",href:"/dashboard/media/sync",roles:OPS},{icon:"🎨",label:"Creative",href:"/dashboard/creative",roles:[...OPS,"CREATOR"]},{icon:"📥",label:"Tasks Inbox",href:"/dashboard/tasks-inbox",roles:OPS},{icon:"📅",label:"Calendar",href:"/dashboard/calendar",roles:[...OPS,"CREATOR","SALES","CLIENT"]}]},
 {label:"FINANCE & HR",items:[{icon:"💰",label:"Finance",href:"/dashboard/finance",roles:["SUPER_ADMIN","ACCOUNTANT"]},{icon:"💳",label:"Accounts Payment",href:"/dashboard/clients/accounts-payment",roles:["SUPER_ADMIN","ACCOUNTANT"]},{icon:"📋",label:"Contracts",href:"/dashboard/contracts",roles:["SUPER_ADMIN","ACCOUNTANT"]},{icon:"👥",label:"HR & Team",href:"/dashboard/team",roles:["SUPER_ADMIN"]},{icon:"➕",label:"Add Employee",href:"/dashboard/team/new",roles:["SUPER_ADMIN","HR"]}]},
 {label:"ANALYTICS",items:[{icon:"📋",label:"Reports",href:"/dashboard/reports",roles:["SUPER_ADMIN","ACCOUNTANT","ACCOUNT_MANAGER","MEDIA_BUYER","SALES"]},{icon:"✅",label:"Report Approvals",href:"/dashboard/reports/competitor-approvals",roles:OPS}]},
 {label:"TOOLS",items:[{icon:"✦",label:"VIVITO",href:"/dashboard/ai-studio",roles:[...EMP,"CLIENT"]},{icon:"📁",label:"Files",href:"/dashboard/files",roles:[...EMP,"CLIENT"]},{icon:"🗄️",label:"Archive",href:"/dashboard/archive",roles:EMP},{icon:"🗑️",label:"Delete",href:"/dashboard/delete",roles:["SUPER_ADMIN"]},{icon:"🔔",label:"Notifications",href:"/dashboard/notifications",roles:[...EMP,"CLIENT"]},{icon:"⚙️",label:"Settings",href:"/dashboard/settings",roles:[...EMP,"CLIENT"]}]},
 {label:"CLIENT",items:[{icon:"🌐",label:"My Portal",href:"/dashboard/portal",roles:["CLIENT"]}]}
];
const QUICK:Record<string,QuickItem[]>={SUPER_ADMIN:[{icon:"🏠",label:"Home",href:"/apps"},{icon:"🏢",label:"Clients",href:"/dashboard/universe"},{icon:"✅",label:"Approvals",href:"/dashboard/reports/competitor-approvals"}],HR:[{icon:"🏠",label:"Home",href:"/apps"},{icon:"➕",label:"Employee",href:"/dashboard/team/new"},{icon:"🗄️",label:"Archive",href:"/dashboard/archive"}],ACCOUNT_MANAGER:[{icon:"🏠",label:"Home",href:"/apps"},{icon:"🏢",label:"Clients",href:"/dashboard/universe"},{icon:"🎨",label:"Creative",href:"/dashboard/creative"}],MEDIA_BUYER:[{icon:"🏠",label:"Home",href:"/apps"},{icon:"📣",label:"Media",href:"/dashboard/media/control-center"},{icon:"✅",label:"Approvals",href:"/dashboard/reports/competitor-approvals"}],CREATOR:[{icon:"🏠",label:"Home",href:"/apps"},{icon:"🎨",label:"Creative",href:"/dashboard/creative"},{icon:"🗄️",label:"Archive",href:"/dashboard/archive"}],ACCOUNTANT:[{icon:"🏠",label:"Home",href:"/apps"},{icon:"💰",label:"Finance",href:"/dashboard/finance"},{icon:"📋",label:"Reports",href:"/dashboard/reports"}],SALES:[{icon:"🏠",label:"Home",href:"/apps"},{icon:"🎯",label:"Sales",href:"/dashboard/sales"},{icon:"🗄️",label:"Archive",href:"/dashboard/archive"}],CLIENT:[{icon:"🏠",label:"Home",href:"/apps"},{icon:"🌐",label:"Portal",href:"/dashboard/portal"},{icon:"📁",label:"Files",href:"/dashboard/files"}]};
export function MobileNav({role,roles}:{role:string;roles?:string[]}){const path=usePathname(),[open,setOpen]=useState(false),effective=[...new Set([role,...(roles||[])])],visible=SECTIONS.map(s=>({...s,items:s.items.filter(i=>i.roles.some(r=>effective.includes(r)))})).filter(s=>s.items.length),all=visible.flatMap(s=>s.items),quick=[...new Map(effective.flatMap(r=>QUICK[r]||[]).map(i=>[i.href,i])).values()].slice(0,4),active=all.filter(i=>path===i.href||(i.href!=="/dashboard"&&path.startsWith(i.href+"/"))).sort((a,b)=>b.href.length-a.href.length)[0]?.href;useEffect(()=>{document.body.style.overflow=open?"hidden":"";return()=>{document.body.style.overflow=""}},[open]);return <>{open&&<div className="mobile-menu-backdrop" onClick={()=>setOpen(false)} aria-hidden="true"/>}<aside className={`mobile-menu-drawer${open?" open":""}`} aria-hidden={!open}><div className="mobile-menu-head"><div><strong>VIVIT</strong><span>{effective.map(r=>r.replace(/_/g," ")).join(" · ")}</span></div><button type="button" onClick={()=>setOpen(false)} aria-label="Close menu">×</button></div><nav>{visible.map(s=><section key={s.label}><p>{s.label}</p>{s.items.map(i=><Link key={i.href} href={i.href} onClick={()=>setOpen(false)} className={active===i.href?"active":""}><span>{i.icon}</span><b>{i.label}</b></Link>)}</section>)}</nav></aside><nav className="mobile-nav" aria-label="Mobile navigation">{quick.map(i=><Link key={i.href} href={i.href} onClick={()=>setOpen(false)} className={path===i.href||path.startsWith(i.href+"/")?"active":""}><span>{i.icon}</span><small>{i.label}</small></Link>)}<button type="button" className={open?"active":""} onClick={()=>setOpen(v=>!v)} aria-expanded={open} aria-label="Open full menu"><span>☰</span><small>Menu</small></button></nav></>}
