"use client";
import {useCallback,useEffect,useState} from "react";

type StoredFile={id:string;name:string;category:string;sizeBytes:number;createdAt:string;url?:string|null;clientId?:string|null;canEdit?:boolean;isArchived?:boolean};
type ClientOption={id:string;companyName:string};
const MAX=500*1024*1024;
const CATEGORIES=["GENERAL","CONTENT_PLAN","STRATEGY","BRIEF","CREATIVE","SOCIAL_POST","CONTRACT","INVOICE","FINANCE","SHEET"];

export default function FilesPage(){
 const [files,setFiles]=useState<StoredFile[]>([]),[clients,setClients]=useState<ClientOption[]>([]),[view,setView]=useState<"active"|"archived">("active"),[loading,setLoading]=useState(true),[uploading,setUploading]=useState(false),[error,setError]=useState(""),[progress,setProgress]=useState(0),[editing,setEditing]=useState<StoredFile|null>(null),[busyId,setBusyId]=useState("");
 const load=useCallback(async(next:"active"|"archived")=>{setLoading(true);setError("");try{const [r,cr]=await Promise.all([fetch(`/api/files${next==="archived"?"?view=archived":""}`,{cache:"no-store"}),fetch("/api/clients",{cache:"no-store"})]),d=await r.json().catch(()=>({})),cd=await cr.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Could not load files");setFiles(d.files||[]);if(cr.ok)setClients(cd.clients||[])}catch(e){setError(e.message)}finally{setLoading(false)}},[]);
 useEffect(()=>{const timer=setTimeout(()=>void load(view),0);return()=>clearTimeout(timer)},[load,view]);
 async function upload(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError("");setProgress(0);const form=e.currentTarget,fd=new FormData(form),file=fd.get("file") as File|null;if(!file)return setError("Choose a file first.");if(file.size>MAX)return setError("Maximum file size is 500 MB.");setUploading(true);try{const sign=await fetch("/api/files",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({op:"sign",name:file.name,size:file.size,mimeType:file.type})}),signed=await sign.json().catch(()=>({}));if(!sign.ok)throw new Error(signed.error||"Could not prepare upload");await new Promise<void>((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open("PUT",signed.uploadUrl);xhr.setRequestHeader("x-upsert","false");xhr.upload.onprogress=ev=>ev.lengthComputable&&setProgress(Math.round(ev.loaded/ev.total*100));xhr.onerror=()=>reject(new Error("Network error while uploading."));xhr.onload=()=>{if(xhr.status>=200&&xhr.status<300)return resolve();let message=`Storage rejected the file (${xhr.status}).`;try{const d=JSON.parse(xhr.responseText);message=d.message||d.error||message}catch{}reject(new Error(message))};const body=new FormData();body.append("cacheControl","3600");body.append("",file,file.name);xhr.send(body)});const complete=await fetch("/api/files",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({op:"complete",path:signed.path,name:file.name,size:file.size,mimeType:file.type,category:fd.get("category"),clientId:fd.get("clientId")||null})}),done=await complete.json().catch(()=>({}));if(!complete.ok)throw new Error(done.error||"Could not save file details");form.reset();setProgress(100);setView("active");await load("active")}catch(e){setError(e.message||"Upload failed")}finally{setUploading(false)}}
 async function saveEdit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;const fd=new FormData(e.currentTarget);setBusyId(editing.id);setError("");try{const r=await fetch("/api/files",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:editing.id,op:"edit",name:fd.get("name"),category:fd.get("category"),clientId:fd.get("clientId")||null})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Could not update file");setEditing(null);await load(view)}catch(e){setError(e.message)}finally{setBusyId("")}}
 async function lifecycle(f:StoredFile,op:"archive"|"restore"){if(!f.canEdit)return;setBusyId(f.id);setError("");try{const r=await fetch("/api/files",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:f.id,op})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Could not ${op} file`);setFiles(v=>v.filter(x=>x.id!==f.id))}catch(e){setError(e.message)}finally{setBusyId("")}}
 async function remove(f:StoredFile){if(!f.canEdit||!confirm(`Permanently delete “${f.name}”? This cannot be undone and removes the stored file.`))return;setBusyId(f.id);setError("");try{const r=await fetch("/api/files",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:f.id})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Could not delete file");setFiles(v=>v.filter(x=>x.id!==f.id))}catch(e){setError(e.message)}finally{setBusyId("")}}
 const size=(n:number)=>n>=1048576?`${(n/1048576).toFixed(1)} MB`:`${Math.max(1,Math.ceil(n/1024))} KB`;
 return <div className="files-page" style={{display:"flex",flexDirection:"column",gap:18}}>
  <div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"end",flexWrap:"wrap"}}><div><h1 className="page-title">Files & Documents</h1><p className="page-subtitle">Owner-controlled edit, archive, restore and permanent deletion</p></div><div style={{display:"flex",gap:8}}><button className={`btn ${view==="active"?"btn-primary":"btn-secondary"}`} onClick={()=>setView("active")}>Active</button><button className={`btn ${view==="archived"?"btn-primary":"btn-secondary"}`} onClick={()=>setView("archived")}>Archive</button></div></div>
  {view==="active"&&<div className="card upload-card"><div className="card-header"><p className="card-title">Upload a file</p><span className="badge badge-blue">Secure upload · 500 MB</span></div><div className="card-body"><form onSubmit={upload} className="file-upload-form"><label className="form-label">FILE<input name="file" type="file" required className="form-input" disabled={uploading}/></label><label className="form-label">CLIENT<select name="clientId" className="form-select" disabled={uploading}><option value="">Private / not linked</option>{clients.map(c=><option key={c.id} value={c.id}>{c.companyName}</option>)}</select></label><label className="form-label">CATEGORY<select name="category" className="form-select" disabled={uploading}>{CATEGORIES.map(x=><option key={x}>{x}</option>)}</select></label><button className="btn btn-primary upload-button" disabled={uploading}>{uploading?`Uploading ${progress}%`:`Upload securely ↑`}</button></form>{uploading&&<div className="upload-progress"><span style={{width:`${progress}%`}}/></div>}</div></div>}
  {error&&<div className="card" style={{borderColor:"var(--red)",padding:12,color:"var(--red)"}} role="alert">{error}</div>}
  <div className="card"><div className="card-header"><div><p className="card-title">{view==="archived"?"Archived files":"Recent files"}</p><p className="page-subtitle">{view==="archived"?"Restore files to return them to daily work.":"Archive keeps the file; Delete removes it permanently."}</p></div><span className="badge badge-gray">{files.length}</span></div><div className="card-body-flush">{loading?<div className="empty-state"><p>Loading files…</p></div>:files.length===0?<div className="empty-state"><p className="empty-state-icon">📁</p><p className="empty-state-title">{view==="archived"?"Archive is empty":"No files yet"}</p></div>:<div className="responsive-table"><table className="data-table"><thead><tr><th>File</th><th>Category</th><th>Size</th><th>Uploaded</th><th>Actions</th></tr></thead><tbody>{files.map(f=><tr key={f.id}><td data-label="File" style={{fontWeight:700}}>📄 {f.name}</td><td data-label="Category"><span className="badge badge-blue">{f.category}</span></td><td data-label="Size">{size(f.sizeBytes)}</td><td data-label="Uploaded">{new Date(f.createdAt).toLocaleDateString()}</td><td data-label="Actions"><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{f.url&&<a className="btn btn-ghost btn-sm" href={f.url} target="_blank" rel="noreferrer">Open ↗</a>}{f.canEdit&&<>{view==="active"?<><button className="btn btn-secondary btn-sm" onClick={()=>setEditing(f)} disabled={busyId===f.id}>Edit</button><button className="btn btn-secondary btn-sm" onClick={()=>lifecycle(f,"archive")} disabled={busyId===f.id}>Archive</button></>:<button className="btn btn-secondary btn-sm" onClick={()=>lifecycle(f,"restore")} disabled={busyId===f.id}>Restore</button>}<button className="btn btn-danger btn-sm" onClick={()=>remove(f)} disabled={busyId===f.id}>{busyId===f.id?"Working…":"Delete"}</button></>}</div></td></tr>)}</tbody></table></div>}</div></div>
  {editing&&<div role="dialog" aria-modal="true" onClick={()=>!busyId&&setEditing(null)} style={{position:"fixed",inset:0,zIndex:1000,background:"rgba(3,8,20,.58)",display:"grid",placeItems:"center",padding:16}}><form onSubmit={saveEdit} onClick={e=>e.stopPropagation()} className="card" style={{width:"min(520px,96vw)",padding:18,display:"grid",gap:12}}><div><h2 className="card-title">Edit file</h2><p className="page-subtitle">Only the uploader or Super Admin can change this record.</p></div><label className="form-label">FILE NAME<input name="name" defaultValue={editing.name} required maxLength={255} className="form-input"/></label><label className="form-label">CLIENT<select name="clientId" defaultValue={editing.clientId||""} className="form-select"><option value="">Private / not linked</option>{clients.map(c=><option key={c.id} value={c.id}>{c.companyName}</option>)}</select></label><label className="form-label">CATEGORY<select name="category" defaultValue={editing.category} className="form-select">{CATEGORIES.map(x=><option key={x}>{x}</option>)}</select></label><div style={{display:"flex",justifyContent:"flex-end",gap:8}}><button type="button" className="btn btn-ghost" onClick={()=>setEditing(null)} disabled={!!busyId}>Cancel</button><button className="btn btn-primary" disabled={!!busyId}>{busyId?"Saving…":"Save changes"}</button></div></form></div>}
 </div>;
}
