"use client";
import { useEffect,useState } from "react";
type StoredFile={id:string;name:string;category:string;sizeBytes:number;createdAt:string;url?:string|null};
type ClientOption={id:string;companyName:string};
const MAX=100*1024*1024;
export default function FilesPage(){
  const [files,setFiles]=useState<StoredFile[]>([]),[clients,setClients]=useState<ClientOption[]>([]),[loading,setLoading]=useState(true),[uploading,setUploading]=useState(false),[error,setError]=useState(""),[progress,setProgress]=useState(0);
  async function load(){setLoading(true);try{const [r,cr]=await Promise.all([fetch("/api/files",{cache:"no-store"}),fetch("/api/clients",{cache:"no-store"})]),d=await r.json(),cd=await cr.json();if(!r.ok)throw new Error(d.error||"Could not load files");setFiles(d.files||[]);if(cr.ok)setClients(cd.clients||[])}catch(e:any){setError(e.message)}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);
  async function upload(e:React.FormEvent<HTMLFormElement>){
    e.preventDefault();setError("");setProgress(0);const form=e.currentTarget,fd=new FormData(form),file=fd.get("file") as File|null;
    if(!file)return setError("Choose a file first.");if(file.size>MAX)return setError("Maximum file size is 100 MB.");setUploading(true);
    try{
      const sign=await fetch("/api/files",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({op:"sign",name:file.name,size:file.size,mimeType:file.type})}),signed=await sign.json();if(!sign.ok)throw new Error(signed.error||"Could not prepare upload");
      await new Promise<void>((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open("PUT",signed.uploadUrl);xhr.setRequestHeader("Content-Type",file.type||"application/octet-stream");xhr.upload.onprogress=ev=>ev.lengthComputable&&setProgress(Math.round(ev.loaded/ev.total*100));xhr.onerror=()=>reject(new Error("Network error while uploading. You can retry safely."));xhr.onload=()=>xhr.status>=200&&xhr.status<300?resolve():reject(new Error(`Storage rejected the file (${xhr.status}).`));xhr.send(file)});
      const complete=await fetch("/api/files",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({op:"complete",path:signed.path,name:file.name,size:file.size,mimeType:file.type,category:fd.get("category"),clientId:fd.get("clientId")||null})}),done=await complete.json();if(!complete.ok)throw new Error(done.error||"Could not save file details");
      form.reset();setProgress(100);await load();
    }catch(e:any){setError(e.message||"Upload failed")}finally{setUploading(false)}
  }
  const size=(n:number)=>n>=1048576?`${(n/1048576).toFixed(1)} MB`:`${Math.max(1,Math.ceil(n/1024))} KB`;
  return <div className="files-page"><div><h1 className="page-title">Files & Documents</h1><p className="page-subtitle">Fast, private storage for briefs, designs, contracts and invoices</p></div><div className="card upload-card"><div className="card-header"><p className="card-title">Upload a file</p><span className="badge badge-blue">Direct secure upload · 100 MB</span></div><div className="card-body"><form onSubmit={upload} className="file-upload-form"><label className="form-label">FILE<input name="file" type="file" required className="form-input" disabled={uploading}/></label><label className="form-label">CLIENT<select name="clientId" className="form-select" disabled={uploading}><option value="">Private / not linked</option>{clients.map(c=><option key={c.id} value={c.id}>{c.companyName}</option>)}</select></label><label className="form-label">CATEGORY<select name="category" className="form-select" disabled={uploading}><option>GENERAL</option><option>BRIEF</option><option>CREATIVE</option><option>CONTRACT</option><option>INVOICE</option><option>SHEET</option></select></label><button className="btn btn-primary upload-button" disabled={uploading}>{uploading?`Uploading ${progress}%`:`Upload securely ↑`}</button></form>{uploading&&<div className="upload-progress"><span style={{width:`${progress}%`}}/></div>}{error&&<p className="form-error" role="alert">{error}</p>}</div></div><div className="card"><div className="card-header"><p className="card-title">Recent files</p><span className="badge badge-gray">{files.length}</span></div><div className="card-body-flush">{loading?<div className="empty-state"><p>Loading files…</p></div>:files.length===0?<div className="empty-state"><p className="empty-state-icon">📁</p><p className="empty-state-title">No files yet</p><p className="empty-state-desc">Upload the first document above.</p></div>:<div className="responsive-table"><table className="data-table"><thead><tr><th>File</th><th>Category</th><th>Size</th><th>Uploaded</th><th></th></tr></thead><tbody>{files.map(f=><tr key={f.id}><td data-label="File" style={{fontWeight:700}}>📄 {f.name}</td><td data-label="Category"><span className="badge badge-blue">{f.category}</span></td><td data-label="Size">{size(f.sizeBytes)}</td><td data-label="Uploaded">{new Date(f.createdAt).toLocaleDateString()}</td><td>{f.url&&<a className="btn btn-ghost btn-sm" href={f.url} target="_blank" rel="noreferrer">Open ↗</a>}</td></tr>)}</tbody></table></div>}</div></div></div>
}
