"use client";
import { useMemo,useState } from "react";

const FAQ=[
 ["calendar","Calendar shows only the clients you are allowed to access. Sales, Account Managers and Super Admin can schedule; clients see their own approved calendar only."],
 ["creative","Creatives move from production to Review. Super Admin approval is required before a creative can appear in the client portal. Client approval can then place the item on that client's calendar."],
 ["client portal","The client portal contains approved creatives, captions, dates, content-plan/strategy files, campaign performance, invoices and the client-specific calendar."],
 ["kpi","KPIs summarize revenue, collection, sales pipeline, creative delivery, media performance and client health. Use the KPI page for the agency-wide view."],
 ["roas","ROAS = revenue attributed to ads divided by ad spend. Track it together with CPL, CPA, CTR and lead quality; a high ROAS with weak lead quality can still be misleading."],
 ["cpl","CPL = ad spend / leads. Compare it with lead quality and conversion-to-sale, not as an isolated metric."],
 ["media buying","For media buying, check objective, tracking, audience, creative, budget pacing, frequency, CTR, CPL/CPA and conversion quality before scaling."],
 ["campaign","Campaign data belongs to each client. Platform Sync connects account/campaign IDs; Media Control is where campaign performance is monitored."],
 ["content plan","Content plans and strategies are uploaded as client files. They should be linked to the client so the client and assigned creator can see the correct documents."],
 ["settings","Settings lets you change language, reminder preferences and sign out. Super Admin also manages users and permissions."],
 ["sales","Sales CRM contains all leads in one pipeline. Imported online leads are treated like normal leads rather than a separate module."],
 ["whatsapp","WhatsApp opens customer conversations from the system. Use it for follow-ups while keeping the lead/client record as the source of truth."],
];
const QUICK=["How does creative approval work?","How do I use the calendar?","Explain ROAS and CPL","Where is the content plan?","How do client approvals work?"];
function answer(q:string,role:string){const s=q.toLowerCase();for(const [k,a] of FAQ)if(s.includes(k))return a; if(/facebook|meta|tiktok|ads|media/.test(s))return "For paid media: verify tracking first, then review objective, audience, creative, spend pacing, CTR, CPL/CPA, frequency and final business results. Scale only after the conversion quality is proven."; if(/marketing|strategy|content/.test(s))return "A strong marketing plan connects the business objective to audience insight, positioning, offer, funnel, channels, content pillars, campaigns, media budget, KPIs and a measurement cadence."; return `I can help with VIVIT ERP workflows and marketing/media-buying questions. Your role is ${role.replace(/_/g," ")}. Ask me about a page, approval flow, KPI, campaign metric, calendar, content plan, client portal or a marketing decision.`}
export function SystemAssistant({role}:{role:string}){
 const [open,setOpen]=useState(false),[q,setQ]=useState(""),[msgs,setMsgs]=useState<{who:"you"|"ai";text:string}[]>([]);
 const quick=useMemo(()=>QUICK,[]); const send=(text=q)=>{const v=text.trim();if(!v)return;setMsgs(m=>[...m,{who:"you",text:v},{who:"ai",text:answer(v,role)}]);setQ("");};
 return <><button onClick={()=>setOpen(v=>!v)} aria-label="Open VIVIT Assistant" style={{position:"fixed",right:22,bottom:22,zIndex:900,width:58,height:58,borderRadius:20,border:"1px solid rgba(255,255,255,.7)",background:"linear-gradient(145deg,#7C3AED,#C52A31)",color:"white",fontSize:25,boxShadow:"0 18px 42px rgba(91,33,182,.32)",cursor:"pointer",animation:"assistantPulse 2.4s ease-in-out infinite"}}>✨</button>{open&&<div style={{position:"fixed",right:22,bottom:90,zIndex:901,width:"min(390px,calc(100vw - 28px))",height:"min(600px,72vh)",background:"rgba(255,255,255,.97)",backdropFilter:"blur(18px)",border:"1px solid #e5e7eb",borderRadius:22,boxShadow:"0 30px 80px rgba(15,23,42,.25)",display:"flex",flexDirection:"column",overflow:"hidden"}}><div style={{padding:"15px 17px",background:"linear-gradient(135deg,#241934,#7C3AED,#C52A31)",color:"#fff",display:"flex",justifyContent:"space-between"}}><div><b>VIVIT Assistant</b><div style={{fontSize:11,opacity:.78}}>System help + Marketing & Media Buying</div></div><button onClick={()=>setOpen(false)} style={{background:"transparent",border:0,color:"#fff",fontSize:18,cursor:"pointer"}}>×</button></div><div style={{padding:12,display:"flex",gap:6,overflowX:"auto",borderBottom:"1px solid #eee"}}>{quick.map(x=><button key={x} onClick={()=>send(x)} style={{whiteSpace:"nowrap",border:"1px solid #e5e7eb",background:"#fafafa",borderRadius:999,padding:"6px 9px",fontSize:10.5,cursor:"pointer"}}>{x}</button>)}</div><div style={{flex:1,overflowY:"auto",padding:14,display:"flex",flexDirection:"column",gap:9}}>{msgs.length===0&&<div style={{padding:14,borderRadius:14,background:"#f7f5fb",fontSize:12.5,lineHeight:1.65,color:"#475569"}}>Ask me how any feature works, or ask a marketing/media-buying question. I tailor system guidance to your current role.</div>}{msgs.map((m,i)=><div key={i} style={{alignSelf:m.who==="you"?"flex-end":"flex-start",maxWidth:"88%",padding:"9px 11px",borderRadius:13,background:m.who==="you"?"#7C3AED":"#f1f5f9",color:m.who==="you"?"#fff":"#334155",fontSize:12.5,lineHeight:1.55}}>{m.text}</div>)}</div><div style={{padding:12,borderTop:"1px solid #eee",display:"flex",gap:8}}><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Ask VIVIT..." style={{flex:1,border:"1px solid #dbe2ea",borderRadius:11,padding:"10px 11px",outline:"none"}}/><button onClick={()=>send()} style={{border:0,borderRadius:11,padding:"0 14px",background:"#7C3AED",color:"#fff",fontWeight:800,cursor:"pointer"}}>Send</button></div></div>}<style>{`@keyframes assistantPulse{0%,100%{transform:translateY(0) scale(1)}50%{transform:translateY(-5px) scale(1.05)}}@media(prefers-reduced-motion:reduce){button[aria-label="Open VIVIT Assistant"]{animation:none!important}}`}</style></>;
}
