export const dynamic="force-dynamic";
import {NextResponse} from "next/server";
import {auth} from "@/lib/auth";
import {db,sql} from "@/lib/db";
type Row=Record<string,unknown>;const rows=(v:unknown)=>Array.from(v as Iterable<Row>);
export async function GET(){const s=await auth();if(!s?.user)return NextResponse.json({error:"Unauthorized"},{status:401});const workspaceId=String(s.user.workspaceId||""),userId=String(s.user.id||""),role=String(s.user.role||"");if(!workspaceId)return NextResponse.json({error:"Workspace unavailable"},{status:403});const superAdmin=role==="SUPER_ADMIN";
 const clients=rows(await db.execute(superAdmin?sql`select c.id,c.company_name name,c.archived_at,c.archived_by,u.name archived_by_name,u.email archived_by_email from clients c left join users u on u.id=c.archived_by and u.workspace_id=c.workspace_id where c.workspace_id=${workspaceId} and c.archived_at is not null order by c.archived_at desc limit 150`:sql`select c.id,c.company_name name,c.archived_at,c.archived_by,u.name archived_by_name,u.email archived_by_email from clients c left join users u on u.id=c.archived_by and u.workspace_id=c.workspace_id where c.workspace_id=${workspaceId} and c.archived_at is not null and (c.archived_by=${userId} or (${role}='ACCOUNT_MANAGER' and c.account_manager_id=${userId}) or (${role}='MEDIA_BUYER' and c.media_buyer_id=${userId})) order by c.archived_at desc limit 150`));
 const tasks=rows(await db.execute(superAdmin?sql`select t.id,t.title name,t.archived_at,t.archived_by,u.name archived_by_name,u.email archived_by_email from creative_tasks t left join users u on u.id=t.archived_by and u.workspace_id=t.workspace_id where t.workspace_id=${workspaceId} and t.archived_at is not null order by t.archived_at desc limit 200`:sql`select t.id,t.title name,t.archived_at,t.archived_by,u.name archived_by_name,u.email archived_by_email from creative_tasks t left join users u on u.id=t.archived_by and u.workspace_id=t.workspace_id left join clients c on c.id=t.client_id and c.workspace_id=t.workspace_id where t.workspace_id=${workspaceId} and t.archived_at is not null and (t.archived_by=${userId} or (${role}='ACCOUNT_MANAGER' and c.account_manager_id=${userId}) or (${role}='MEDIA_BUYER' and c.media_buyer_id=${userId}) or (${role}='CREATOR' and t.assigned_to_id=${userId})) order by t.archived_at desc limit 200`));
 const leads=rows(await db.execute(superAdmin?sql`select l.id,l.company_name name,l.archived_at,l.archived_by,u.name archived_by_name,u.email archived_by_email from sales_leads l left join users u on u.id=l.archived_by and u.workspace_id=l.workspace_id where l.workspace_id=${workspaceId} and l.archived_at is not null order by l.archived_at desc limit 150`:sql`select l.id,l.company_name name,l.archived_at,l.archived_by,u.name archived_by_name,u.email archived_by_email from sales_leads l left join users u on u.id=l.archived_by and u.workspace_id=l.workspace_id where l.workspace_id=${workspaceId} and l.archived_at is not null and (l.archived_by=${userId} or (${role}='SALES' and l.sales_rep_id=${userId})) order by l.archived_at desc limit 150`));
 const campaigns=rows(await db.execute(superAdmin?sql`select a.id,a.name,a.archived_at,a.archived_by,a.client_id,u.name archived_by_name,u.email archived_by_email from ad_campaigns a left join users u on u.id=a.archived_by and u.workspace_id=a.workspace_id where a.workspace_id=${workspaceId} and a.archived_at is not null order by a.archived_at desc limit 200`:sql`select a.id,a.name,a.archived_at,a.archived_by,a.client_id,u.name archived_by_name,u.email archived_by_email from ad_campaigns a left join users u on u.id=a.archived_by and u.workspace_id=a.workspace_id left join clients c on c.id=a.client_id and c.workspace_id=a.workspace_id where a.workspace_id=${workspaceId} and a.archived_at is not null and (a.archived_by=${userId} or a.created_by=${userId} or (${role}='ACCOUNT_MANAGER' and c.account_manager_id=${userId}) or (${role}='MEDIA_BUYER' and c.media_buyer_id=${userId})) order by a.archived_at desc limit 200`));
 return NextResponse.json({clients,tasks,leads,campaigns},{headers:{"Cache-Control":"private, no-store"}})}
