// @ts-nocheck
export const dynamic="force-dynamic";
import {createHash} from "node:crypto";
import { NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { db,clients,contacts,creativeTasks,salesLeads,financeRecords,mediaMetrics,users,workspaces,auditLogs } from "@/lib/db";
import {eq,and,inArray} from "drizzle-orm";
import {recordBackupManifest} from "@/lib/vivito/enterprise-governance";
const sha256=(v:string)=>createHash("sha256").update(v).digest("hex");
export async function GET(){const session=await auth();if(!session?.user||(session.user as any).role!=="SUPER_ADMIN")return NextResponse.json({error:"Unauthorized"},{status:401});const workspaceId=String((session.user as any).workspaceId||"");if(!workspaceId)return NextResponse.json({error:"Workspace unavailable"},{status:403});const [workspaceRows,userRows,clientRows,leadRows,financeRows,mediaRows]=await Promise.all([db.select().from(workspaces).where(eq(workspaces.id,workspaceId)),db.select({id:users.id,name:users.name,email:users.email,role:users.role,isActive:users.isActive,createdAt:users.createdAt}).from(users).where(eq(users.workspaceId,workspaceId)),db.select().from(clients).where(eq(clients.workspaceId,workspaceId)),db.select().from(salesLeads).where(eq(salesLeads.workspaceId,workspaceId)),db.select().from(financeRecords).where(eq(financeRecords.workspaceId,workspaceId)),db.select().from(mediaMetrics).where(eq(mediaMetrics.workspaceId,workspaceId))]);const clientIds=clientRows.map((x:any)=>x.id);const [contactRows,taskRows]=await Promise.all([clientIds.length?db.select().from(contacts).where(inArray(contacts.clientId,clientIds)):[],db.select().from(creativeTasks).where(eq(creativeTasks.workspaceId,workspaceId))]);const generatedAt=new Date().toISOString();const payload={version:1,workspaceId,generatedAt,workspace:workspaceRows,users:userRows,clients:clientRows,contacts:contactRows,tasks:taskRows,salesLeads:leadRows,finance:financeRows,media:mediaRows};const canonical=JSON.stringify(payload);const checksum=sha256(canonical),snapshotKey=`${workspaceId}:${generatedAt}`;const body=JSON.stringify({...payload,manifest:{snapshotKey,checksum,algorithm:"sha256",recordCounts:{workspace:workspaceRows.length,users:userRows.length,clients:clientRows.length,contacts:contactRows.length,tasks:taskRows.length,salesLeads:leadRows.length,finance:financeRows.length,media:mediaRows.length}}},null,2);await recordBackupManifest({workspaceId,snapshotKey,checksum,recordCounts:{workspace:workspaceRows.length,users:userRows.length,clients:clientRows.length,contacts:contactRows.length,tasks:taskRows.length,salesLeads:leadRows.length,finance:financeRows.length,media:mediaRows.length}});await db.insert(auditLogs).values({workspaceId,userId:(session.user as any).id,action:"backup_exported",entity:"workspace",entityId:workspaceId,newValues:JSON.stringify({at:generatedAt,snapshotKey,checksum})} as any);return new NextResponse(body,{headers:{"Content-Type":"application/json","Content-Disposition":`attachment; filename="vivit-backup-${workspaceId}-${generatedAt.slice(0,10)}.json"`,"Cache-Control":"private, no-store","X-Content-Type-Options":"nosniff"}})}
