export const dynamic="force-dynamic";
import {auth} from "@/lib/auth";
import {redirect} from "next/navigation";
import {db,payroll,users,workspaces} from "@/lib/db";
import {and,eq} from "drizzle-orm";
import {Role} from "@/lib/types";
import Link from "next/link";
const WORKSPACE="default";
export default async function ConfidentialPayrollPage(){const session=await auth();if(!session?.user)redirect("/login");const role=(session.user as any).role as Role;if(![Role.SUPER_ADMIN,Role.ACCOUNTANT].includes(role))redirect("/dashboard");const now=new Date(),month=now.getMonth()+1,year=now.getFullYear();const [rows,workspace]=await Promise.all([db.select({userId:payroll.userId,name:users.name,role:users.role,baseSalary:payroll.baseSalary,bonus:payroll.bonus,deductions:payroll.deductions,netPay:payroll.netPay,status:payroll.status}).from(payroll).innerJoin(users,and(eq(users.id,payroll.userId),eq(users.workspaceId,WORKSPACE),eq(users.isActive,true))).where(and(eq(payroll.workspaceId,WORKSPACE),eq(payroll.month,month),eq(payroll.year,year))).orderBy(users.name),db.select({currency:workspaces.currency}).from(workspaces).where(eq(workspaces.id,WORKSPACE)).then(r=>r[0])]);const currency=workspace?.currency||"EGP",total=rows.reduce((s,r)=>s+Number(r.netPay||0),0),fmt=(n:number)=>{try{return new Intl.NumberFormat("en-EG",{style:"currency",currency,maximumFractionDigits:0}).format(Number(n||0))}catch{return `${Number(n||0).toLocaleString()} ${currency}`}};return <div style={{display:"flex",flexDirection:"column",gap:20}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div><h1 className="page-title">Confidential Payroll</h1><p className="page-subtitle">Visible only to Accountant and Super Admin · {month}/{year}</p></div><Link href="/dashboard/finance" className="btn btn-ghost btn-sm" style={{textDecoration:"none"}}>← Finance</Link></div><div className="kpi-card green"><div className="kpi-label">Monthly Payroll</div><div className="kpi-value">{fmt(total)}</div></div><div className="card"><div className="card-header"><p className="card-title">Employee Salaries</p><span className="badge badge-red">Confidential</span></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Employee</th><th>Role</th><th>Base</th><th>Bonus</th><th>Deductions</th><th>Net</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.userId}><td style={{fontWeight:700}}>{r.name}</td><td>{String(r.role).replace(/_/g," ")}</td><td>{fmt(r.baseSalary)}</td><td>{fmt(r.bonus)}</td><td>{fmt(r.deductions)}</td><td style={{fontWeight:800}}>{fmt(r.netPay)}</td><td><span className={`badge ${r.status==="PAID"?"badge-green":r.status==="APPROVED"?"badge-blue":"badge-gray"}`}>{r.status}</span></td></tr>)}{!rows.length&&<tr><td colSpan={7} style={{textAlign:"center",color:"var(--text-muted)"}}>No payroll rows for this period.</td></tr>}</tbody></table></div></div></div>}
