import Link from "next/link";
import BoardControls from "./BoardControls";
import {requireGroupSuperAdmin} from "@/lib/vgroup/access";
import {getVGroupSql} from "@/lib/vgroup/db";
export const dynamic="force-dynamic";

type FinanceRow={business_unit_id:string;code:string;month_revenue:number|string;month_expenses:number|string;month_net:number|string;ytd_revenue:number|string;ytd_expenses:number|string;ytd_net:number|string};
type PulseRow={business_unit_id:string;code:string;pending_approvals:number;open_exceptions:number;open_housekeeping:number;open_guest_complaints:number;open_support_tickets:number;open_sales_opportunities:number;month_net_movement:number|string};
type DecisionRow={id:string;unit_code:string|null;title:string;decision_type:string;status:string;created_at:string};
type ActionRow={id:string;unit_code:string|null;title:string;priority:string;status:string;due_at:string|null};
type ScalarRow={value:number|string};
const money=(v:number|string)=>new Intl.NumberFormat("en-EG",{style:"currency",currency:"EGP",maximumFractionDigits:0}).format(Number(v||0));
const n=(v:number|string)=>Number(v||0);

export default async function CommandCenter(){
  await requireGroupSuperAdmin();
  const sql=getVGroupSql();
  const [finance,pulse,decisions,actions,critical,openApprovals,openActions,intercompany]=await Promise.all([
    sql<FinanceRow[]>`select business_unit_id::text,code,month_revenue,month_expenses,month_net,ytd_revenue,ytd_expenses,ytd_net from vgroup.board_finance_snapshot order by code`,
    sql<PulseRow[]>`select business_unit_id::text,code,pending_approvals,open_exceptions,open_housekeeping,open_guest_complaints,open_support_tickets,open_sales_opportunities,month_net_movement from vgroup.executive_command_center order by code`,
    sql<DecisionRow[]>`select d.id::text,bu.code as unit_code,d.title,d.decision_type,d.status,d.created_at::text from vgroup.board_decisions d left join vgroup.business_units bu on bu.id=d.business_unit_id order by d.created_at desc limit 8`,
    sql<ActionRow[]>`select a.id::text,bu.code as unit_code,a.title,a.priority,a.status,a.due_at::text from vgroup.board_action_items a left join vgroup.business_units bu on bu.id=a.business_unit_id where a.status not in ('DONE','CANCELLED') order by case a.priority when 'CRITICAL' then 1 when 'HIGH' then 2 when 'MEDIUM' then 3 else 4 end,a.due_at nulls last limit 10`,
    sql<ScalarRow[]>`select count(*)::int as value from vgroup.operational_exceptions where status<>'RESOLVED' and severity in ('critical','CRITICAL','high','HIGH')`,
    sql<ScalarRow[]>`select count(*)::int as value from vgroup.approval_requests where status='pending'`,
    sql<ScalarRow[]>`select count(*)::int as value from vgroup.board_action_items where status not in ('DONE','CANCELLED')`,
    sql<ScalarRow[]>`select count(*)::int as value from vgroup.intercompany_settlements where status not in ('posted','POSTED','cancelled','CANCELLED')`
  ]);
  const total={monthRevenue:finance.reduce((s,r)=>s+n(r.month_revenue),0),monthExpenses:finance.reduce((s,r)=>s+n(r.month_expenses),0),monthNet:finance.reduce((s,r)=>s+n(r.month_net),0),ytdRevenue:finance.reduce((s,r)=>s+n(r.ytd_revenue),0),ytdExpenses:finance.reduce((s,r)=>s+n(r.ytd_expenses),0),ytdNet:finance.reduce((s,r)=>s+n(r.ytd_net),0)};
  const pulseByCode=new Map(pulse.map(r=>[r.code,r]));
  const unitAccent:Record<string,string>={marketing:"#ef4444",tech:"#38bdf8",hospitality:"#d6a84b"};
  const card={padding:20,borderRadius:22,border:"1px solid #242a35",background:"linear-gradient(145deg,rgba(255,255,255,.055),rgba(255,255,255,.018))"};
  return <main style={{minHeight:"100vh",background:"radial-gradient(circle at 10% 0%,rgba(56,189,248,.10),transparent 26%),radial-gradient(circle at 90% 4%,rgba(214,168,75,.08),transparent 24%),#07090d",color:"#f5f7fb",padding:"30px 22px",fontFamily:"Inter,system-ui,sans-serif"}}><section style={{maxWidth:1380,margin:"0 auto"}}>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:18,flexWrap:"wrap"}}><div><Link href="/group" style={{color:"#9cc9ff",textDecoration:"none",fontWeight:800}}>← Group selector</Link><div style={{fontSize:12,letterSpacing:".18em",fontWeight:900,color:"#9cc9ff",marginTop:28}}>VIVIT GROUP · BOARD CONTROL CENTER</div><h1 style={{fontSize:"clamp(38px,5vw,66px)",letterSpacing:"-.055em",margin:"8px 0 8px"}}>One board. Full control.</h1><p style={{maxWidth:900,color:"#a5afbf",lineHeight:1.7,margin:0}}>Consolidated and per-company finance, operational risk, approvals, board decisions and action tracking across Marketing, Technology and Hospitality.</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><Link href="/group/finance" style={{padding:"11px 15px",borderRadius:999,border:"1px solid #2d3748",color:"#dbeafe",textDecoration:"none",fontWeight:800}}>Group Finance</Link><Link href="/group/admin" style={{padding:"11px 15px",borderRadius:999,border:"1px solid #2d3748",color:"#dbeafe",textDecoration:"none",fontWeight:800}}>Group Admin</Link></div></div>

    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:12,margin:"28px 0 14px"}}>
      {[['Month revenue',money(total.monthRevenue),'#86efac'],['Month expenses',money(total.monthExpenses),'#fda4af'],['Month net',money(total.monthNet),total.monthNet>=0?'#86efac':'#fda4af'],['YTD revenue',money(total.ytdRevenue),'#7dd3fc'],['YTD expenses',money(total.ytdExpenses),'#fbbf24'],['YTD net',money(total.ytdNet),total.ytdNet>=0?'#86efac':'#fda4af']].map(([label,value,color])=><div key={String(label)} style={card}><div style={{fontSize:11,textTransform:"uppercase",letterSpacing:".12em",color:"#8c99aa",fontWeight:900}}>{label}</div><strong style={{display:"block",fontSize:25,marginTop:10,color:String(color)}}>{value}</strong></div>)}
    </div>

    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:12,marginBottom:18}}>{[['Critical/high risks',critical[0]?.value||0,'#f87171'],['Pending approvals',openApprovals[0]?.value||0,'#fbbf24'],['Open board actions',openActions[0]?.value||0,'#7dd3fc'],['Intercompany unsettled',intercompany[0]?.value||0,'#c4b5fd']].map(([label,value,color])=><div key={String(label)} style={{...card,borderColor:`${color}44`}}><span style={{color:"#9aa6b6",fontSize:13}}>{label}</span><strong style={{display:"block",fontSize:32,color:String(color),marginTop:5}}>{value}</strong></div>)}</div>

    <h2 style={{fontSize:22,margin:"28px 0 12px"}}>Business-unit performance</h2>
    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(330px,1fr))",gap:15}}>{finance.map(row=>{const p=pulseByCode.get(row.code);const accent=unitAccent[row.code]||'#94a3b8';return <article key={row.business_unit_id} style={{...card,borderColor:`${accent}55`,boxShadow:`0 25px 70px ${accent}0d`}}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"center"}}><div style={{textTransform:"uppercase",letterSpacing:".14em",fontSize:12,fontWeight:900,color:accent}}>{row.code}</div><Link href={row.code==='tech'?'/group/tech':row.code==='hospitality'?'/group/hospitality':'/group/marketing'} style={{color:accent,textDecoration:"none",fontWeight:900}}>Open ↗</Link></div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8,margin:"18px 0"}}><div><small style={{color:'#7f8a99'}}>Revenue</small><b style={{display:'block'}}>{money(row.month_revenue)}</b></div><div><small style={{color:'#7f8a99'}}>Expenses</small><b style={{display:'block'}}>{money(row.month_expenses)}</b></div><div><small style={{color:'#7f8a99'}}>Net</small><b style={{display:'block',color:n(row.month_net)>=0?'#86efac':'#fda4af'}}>{money(row.month_net)}</b></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:7,fontSize:13,color:"#bcc5d2"}}><span>Approvals <b>{p?.pending_approvals||0}</b></span><span>Exceptions <b>{p?.open_exceptions||0}</b></span><span>Housekeeping <b>{p?.open_housekeeping||0}</b></span><span>Guest complaints <b>{p?.open_guest_complaints||0}</b></span><span>Support tickets <b>{p?.open_support_tickets||0}</b></span><span>Sales opportunities <b>{p?.open_sales_opportunities||0}</b></span></div></article>})}</div>

    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(380px,1fr))",gap:16,marginTop:20}}><section style={card}><div style={{fontSize:12,letterSpacing:".14em",color:"#9cc9ff",fontWeight:900}}>BOARD DECISIONS</div><div style={{display:"grid",gap:9,marginTop:14}}>{decisions.length?decisions.map(d=><div key={d.id} style={{padding:"12px 0",borderBottom:"1px solid #202631"}}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><b>{d.title}</b><span style={{fontSize:11,color:'#9cc9ff'}}>{d.status}</span></div><small style={{color:'#7f8a99'}}>{d.unit_code||'GROUP'} · {d.decision_type}</small></div>):<span style={{color:'#7f8a99'}}>No board decisions yet.</span>}</div></section><section style={card}><div style={{fontSize:12,letterSpacing:".14em",color:"#9cc9ff",fontWeight:900}}>BOARD ACTION TRACKER</div><div style={{display:"grid",gap:9,marginTop:14}}>{actions.length?actions.map(a=><div key={a.id} style={{padding:"12px 0",borderBottom:"1px solid #202631"}}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><b>{a.title}</b><span style={{fontSize:11,color:a.priority==='CRITICAL'?'#f87171':a.priority==='HIGH'?'#fbbf24':'#9cc9ff'}}>{a.priority}</span></div><small style={{color:'#7f8a99'}}>{a.unit_code||'GROUP'} · {a.status}{a.due_at?` · due ${a.due_at}`:''}</small></div>):<span style={{color:'#7f8a99'}}>No open board actions.</span>}</div></section></div>
    <BoardControls/>
  </section></main>;
}
