export const dynamic="force-dynamic";
import {auth} from "@/lib/auth";
import {redirect} from "next/navigation";
import {db,notifications} from "@/lib/db";
import {eq,desc,and} from "drizzle-orm";
import {safeInternalPath} from "@/lib/safe-navigation";

async function markAllRead(){"use server";const session=await auth();if(!session?.user)throw new Error("Unauthorized");await db.update(notifications).set({isRead:true}).where(eq(notifications.userId,String(session.user.id)));const {revalidatePath}=await import("next/cache");revalidatePath("/dashboard/notifications")}
async function markOneRead(fd:FormData){"use server";const session=await auth();if(!session?.user)throw new Error("Unauthorized");const id=String(fd.get("id")||"").trim();if(!id)return;await db.update(notifications).set({isRead:true}).where(and(eq(notifications.id,id),eq(notifications.userId,String(session.user.id))));const {revalidatePath}=await import("next/cache");revalidatePath("/dashboard/notifications")}

const PRIORITY:Record<string,{icon:string;color:string;bg:string;label:string}>={urgent:{icon:"🚨",color:"var(--red)",bg:"var(--red-bg)",label:"Urgent"},high:{icon:"⚠️",color:"var(--amber)",bg:"var(--amber-bg)",label:"High"},normal:{icon:"🔔",color:"var(--vivit-blue)",bg:"rgba(33,150,243,0.08)",label:"Normal"},low:{icon:"💬",color:"var(--text-muted)",bg:"var(--bg-tertiary)",label:"Low"}};

export default async function NotificationsPage(){const session=await auth();if(!session?.user)redirect("/login");const userId=String(session.user.id);const rows=await db.select().from(notifications).where(eq(notifications.userId,userId)).orderBy(desc(notifications.createdAt)).limit(100);const allNotifs=rows.map(n=>({...n,link:safeInternalPath(n.link)})),unread=allNotifs.filter(n=>!n.isRead),read=allNotifs.filter(n=>n.isRead);
 const NotifRow=({n}:{n:any})=>{const cfg=PRIORITY[n.priority??"normal"]??PRIORITY.normal,time=new Date(n.createdAt),mins=Math.max(0,Math.floor((Date.now()-time.getTime())/60000)),timeStr=mins<60?`${mins}m ago`:mins<1440?`${Math.floor(mins/60)}h ago`:time.toLocaleDateString("en-GB",{day:"2-digit",month:"short"});return <div style={{display:"flex",alignItems:"flex-start",gap:14,padding:"14px 20px",background:n.isRead?"transparent":"rgba(33,150,243,0.03)",borderBottom:"1px solid var(--card-border)",borderLeft:`3px solid ${n.isRead?"transparent":cfg.color}`}}><div style={{width:38,height:38,borderRadius:"50%",background:cfg.bg,display:"flex",alignItems:"center",justifyContent:"center",fontSize:16,flexShrink:0,marginTop:2}}>{cfg.icon}</div><div style={{flex:1,minWidth:0}}><div style={{display:"flex",alignItems:"flex-start",justifyContent:"space-between",gap:8,marginBottom:4}}><p style={{fontSize:13.5,fontWeight:n.isRead?500:700,color:n.isRead?"var(--text-secondary)":"var(--text-primary)",lineHeight:1.4}}>{n.title}</p><div style={{display:"flex",alignItems:"center",gap:6,flexShrink:0}}><span style={{fontSize:11,color:"var(--text-muted)",whiteSpace:"nowrap"}}>{timeStr}</span><span className={`badge badge-${n.priority==="urgent"?"red":n.priority==="high"?"amber":n.priority==="normal"?"blue":"gray"}`} style={{fontSize:10}}>{cfg.label}</span></div></div><p style={{fontSize:12.5,color:"var(--text-muted)",lineHeight:1.6}}>{n.message}</p><div style={{display:"flex",gap:8,marginTop:8,alignItems:"center"}}>{n.link&&<a href={n.link} className="btn btn-ghost btn-sm" style={{textDecoration:"none",fontSize:12,padding:"4px 12px"}}>View →</a>}{!n.isRead&&<form action={markOneRead}><input type="hidden" name="id" value={n.id}/><button type="submit" className="btn btn-ghost btn-sm">Mark read</button></form>}</div></div></div>};
 return <div style={{display:"flex",flexDirection:"column",gap:20,maxWidth:800}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",flexWrap:"wrap",gap:12}}><div><h1 className="page-title">Notifications</h1><p className="page-subtitle">{unread.length} unread · {allNotifs.length} total</p></div>{unread.length>0&&<form action={markAllRead}><button type="submit" className="btn btn-ghost btn-sm">✓ Mark all as read</button></form>}</div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{Object.entries(PRIORITY).map(([key,cfg])=>{const count=allNotifs.filter(n=>n.priority===key).length;return count?<span key={key} className="badge" style={{background:cfg.bg,color:cfg.color,fontSize:12,padding:"4px 12px"}}>{cfg.icon} {cfg.label} · {count}</span>:null})}</div>{unread.length>0&&<div className="card"><div className="card-header"><p className="card-title">Unread ({unread.length})</p></div><div className="card-body-flush">{unread.map(n=><NotifRow key={n.id} n={n}/>)}</div></div>}{read.length>0&&<div className="card" style={{opacity:.8}}><div className="card-header"><p className="card-title">Earlier ({read.length})</p></div><div className="card-body-flush">{read.slice(0,30).map(n=><NotifRow key={n.id} n={n}/>)}</div></div>}{allNotifs.length===0&&<div className="card"><div className="card-body" style={{textAlign:"center",padding:"60px 24px"}}><p style={{fontSize:48,marginBottom:12}}>🎉</p><p style={{fontWeight:700,fontSize:16}}>All caught up!</p><p style={{color:"var(--text-muted)"}}>No notifications yet. They&apos;ll appear here when there&apos;s activity.vity.</p></div></div>}</div>}
