export const dynamic="force-dynamic";
import {NextResponse} from "next/server";
import {auth} from "@/lib/auth";
import {db,sql} from "@/lib/db";
const WS="default";
export async function GET(){const s=await auth();if(!s?.user)return NextResponse.json({error:"Unauthorized"},{status:401});const role=String((s.user as any).role||""),userId=String((s.user as any).id||"");if(role==="CLIENT")return NextResponse.json({actions:[]},{headers:{"Cache-Control":"private, no-store"}});const actions:any[]=[];
 if(["SUPER_ADMIN","ACCOUNT_MANAGER","ACCOUNTANT"].includes(role)){const sc=role==="ACCOUNT_MANAGER"?sql`c.account_manager_id=${userId}`:sql`true`;const due=Array.from(await db.execute(sql`select c.id client_id,c.company_name,p.amount_remaining,p.phone,p.payment_day,p.payment_status from clients c join client_payment_profiles p on p.client_id=c.id and p.workspace_id=${WS} where c.workspace_id=${WS} and c.is_active=true and c.archived_at is null and p.amount_remaining>0 and ${sc} order by p.amount_remaining desc limit 15`) as any[]);for(const x of due){const amount=Number(x.amount_remaining||0),phone=String(x.phone||"");actions.push({id:`collect:${x.client_id}`,kind:"COLLECTION",priority:amount>=25000?"HIGH":"MEDIUM",title:`Prepare collection follow-up · ${x.company_name}`,reason:`${amount.toLocaleString("en-EG")} EGP outstanding${x.payment_day?` · payment day ${x.payment_day}`:""}`,execution:phone?{action:"prepare_whatsapp",phone,message:`Hello ${x.company_name}, this is a friendly reminder regarding the outstanding balance of ${amount.toLocaleString("en-EG")} EGP. Please let us know the expected payment timing. Thank you.`}:null,href:"/dashboard/clients/accounts-payment",clientId:x.client_id})}}
 if(["SUPER_ADMIN","ACCOUNT_MANAGER"].includes(role)){const sc=role==="ACCOUNT_MANAGER"?sql`c.account_manager_id=${userId}`:sql`true`;const fatigue=Array.from(await db.execute(sql`select c.id client_id,c.company_name,a.name,coalesce(sum(p.impressions),0) impressions,coalesce(sum(p.reach),0) reach,coalesce(sum(p.spend),0) spend,coalesce(sum(p.results),0) results from ad_campaigns a join clients c on c.id=a.client_id left join ad_performance_daily p on p.campaign_id=a.id and p.date>=date_trunc('month',now()) and p.breakdown_type='TOTAL' and p.ad_set_id is null and p.ad_id is null where a.workspace_id=${WS} and c.workspace_id=${WS} and c.is_active=true and c.archived_at is null and a.archived_at is null and ${sc} group by c.id,c.company_name,a.id,a.name having coalesce(sum(p.spend),0)>500 and coalesce(sum(p.reach),0)>0 and coalesce(sum(p.impressions),0)/nullif(sum(p.reach),0)>=3 order by coalesce(sum(p.impressions),0)/nullif(sum(p.reach),0) desc limit 12`) as any[]);for(const x of fatigue){const frequency=Number(x.reach)?Number(x.impressions)/Number(x.reach):0,deadline=new Date(Date.now()+2*86400000).toISOString();actions.push({id:`creative:${x.client_id}:${x.name}`,kind:"CREATIVE_TEST",priority:"HIGH",title:`Create fatigue-response creative · ${x.company_name}`,reason:`${x.name} frequency ${frequency.toFixed(2)} after ${Number(x.spend).toFixed(0)} EGP spend`,execution:{action:"create_task",clientId:x.client_id,title:`AI Recommendation · New creative test for ${x.name}`,brief:`Create 2 fresh creative concepts for ${x.company_name} to address possible creative fatigue on campaign ${x.name}. Current frequency is ${frequency.toFixed(2)} with ${Number(x.results||0)} reported results. Preserve brand rules and learned client preferences. Deliver distinct hooks and visual angles so Media Buying can test a real creative variable.`,type:"GRAPHIC",priority:"HIGH",deadline},href:"/dashboard/media/control-center",clientId:x.client_id})}}
 const taskScope=role==="SUPER_ADMIN"?sql`true`:role==="ACCOUNT_MANAGER"?sql`c.account_manager_id=${userId}`:role==="CREATOR"?sql`t.assigned_to_id=${userId}`:role==="MEDIA_BUYER"?sql`c.media_buyer_id=${userId}`:sql`false`;if(["SUPER_ADMIN","ACCOUNT_MANAGER","CREATOR","MEDIA_BUYER"].includes(role)){const overdue=Array.from(await db.execute(sql`select t.id,t.title,c.company_name from creative_tasks t join clients c on c.id=t.client_id where t.workspace_id=${WS} and c.workspace_id=${WS} and t.archived_at is null and t.deleted_at is null and c.is_active=true and c.archived_at is null and t.status not in ('COMPLETED','REJECTED') and t.deadline<now() and ${taskScope} order by t.deadline asc limit 15`) as any[]);for(const x of overdue)actions.push({id:`overdue:${x.id}`,kind:"TASK_BLOCKER",priority:"HIGH",title:`Follow up overdue task · ${x.title}`,reason:`${x.company_name} · deadline passed`,execution:{action:"comment_task",taskId:x.id,comment:"Copilot follow-up: this task is overdue. Please update the blocker/status and next delivery time."},href:`/dashboard/creative/${x.id}`})}
 return NextResponse.json({actions:actions.slice(0,30),generatedAt:new Date().toISOString()},{headers:{"Cache-Control":"private, no-store"}})}
