export const dynamic="force-dynamic";
import {NextResponse} from "next/server";
import {auth} from "@/lib/auth";
import {db,sql} from "@/lib/db";
const WS="default";
export async function GET(){const s=await auth();if(!s?.user)return NextResponse.json({error:"Unauthorized"},{status:401});const role=String((s.user as any).role||""),userId=String((s.user as any).id||"");if(role==="CLIENT")return NextResponse.json({actions:[]});const actions:any[]=[];
 if(["SUPER_ADMIN","ACCOUNT_MANAGER","ACCOUNTANT"].includes(role)){const sc=role==="ACCOUNT_MANAGER"?sql`c.account_manager_id=${userId}`:sql`true`;const due=Array.from(await db.execute(sql`select c.id client_id,c.company_name,p.amount_remaining,p.phone,p.payment_day,p.payment_status from clients c join client_payment_profiles p on p.client_id=c.id where c.workspace_id=${WS} and c.is_active=true and p.amount_remaining>0 and ${sc} order by p.amount_remaining desc limit 15`) as any[]);for(const x of due){const amount=Number(x.amount_remaining||0),phone=String(x.phone||"");actions.push({id:`collect:${x.client_id}`,kind:"COLLECTION",priority:amount>=25000?"HIGH":"MEDIUM",title:`Prepare collection follow-up · ${x.company_name}`,reason:`${amount.toLocaleString("en-EG")} EGP outstanding${x.payment_day?` · payment day ${x.payment_day}`:""}`,execution:phone?{action:"prepare_whatsapp",phone,message:`Hello ${x.company_name}, this is a friendly reminder regarding the outstanding balance of ${amount.toLocaleString("en-EG")} EGP. Please let us know the expected payment timing. Thank you.`}:null,href:"/dashboard/clients/accounts-payment",clientId:x.client_id})}}
 if(["SUPER_ADMIN","ACCOUNT_MANAGER"].includes(role)){const sc=role==="ACCOUNT_MANAGER"?sql`c.account_manager_id=${userId}`:sql`true`;const fatigue=Array.from(await db.execute(sql`select c.id client_id,c.company_name,ac.name,coalesce((ac.reported_metrics->>'frequency')::numeric,0) frequency,coalesce((ac.reported_metrics->>'spend')::numeric,0) spend,coalesce((ac.reported_metrics->>'results')::numeric,0) results from ad_campaigns ac join clients c on c.id=ac.client_id where c.workspace_id=${WS} and c.is_active=true and ac.archived_at is null and coalesce((ac.reported_metrics->>'frequency')::numeric,0)>=3 and coalesce((ac.reported_metrics->>'spend')::numeric,0)>500 and ${sc} order by frequency desc limit 12`) as any[]);for(const x of fatigue){const deadline=new Date(Date.now()+2*86400000).toISOString();actions.push({id:`creative:${x.client_id}:${x.name}`,kind:"CREATIVE_TEST",priority:"HIGH",title:`Create fatigue-response creative · ${x.company_name}`,reason:`${x.name} frequency ${Number(x.frequency).toFixed(2)} after ${Number(x.spend).toFixed(0)} EGP spend`,execution:{action:"create_task",clientId:x.client_id,title:`AI Recommendation · New creative test for ${x.name}`,brief:`Create 2 fresh creative concepts for ${x.company_name} to address possible creative fatigue on campaign ${x.name}. Current frequency is ${Number(x.frequency).toFixed(2)} with ${Number(x.results||0)} reported results. Preserve the brand rules and learned client preferences. Deliver distinct hooks/visual angles so Media Buying can test a real creative variable.`,type:"GRAPHIC",priority:"HIGH",deadline},href:"/dashboard/media/control-center",clientId:x.client_id})}}
 const taskScope=role==="SUPER_ADMIN"?sql`true`:role==="ACCOUNT_MANAGER"?sql`c.account_manager_id=${userId}`:role==="CREATOR"?sql`t.assigned_to_id=${userId}`:role==="MEDIA_BUYER"?sql`c.media_buyer_id=${userId}`:sql`false`;if(["SUPER_ADMIN","ACCOUNT_MANAGER","CREATOR","MEDIA_BUYER"].includes(role)){const overdue=Array.from(await db.execute(sql`select t.id,t.title,c.company_name from creative_tasks t join clients c on c.id=t.client_id where t.workspace_id=${WS} and t.archived_at is null and t.deleted_at is null and c.is_active=true and t.status not in ('COMPLETED','APPROVED','REJECTED') and t.deadline<now() and ${taskScope} order by t.deadline asc limit 15`) as any[]);for(const x of overdue)actions.push({id:`overdue:${x.id}`,kind:"TASK_BLOCKER",priority:"HIGH",title:`Follow up overdue task · ${x.title}`,reason:`${x.company_name} · deadline passed`,execution:["SUPER_ADMIN","ACCOUNT_MANAGER","CREATOR","MEDIA_BUYER"].includes(role)?{action:"comment_task",taskId:x.id,comment:"Copilot follow-up: this task is overdue. Please update the blocker/status and next delivery time."}:null,href:`/dashboard/creative/${x.id}`})}
 return NextResponse.json({actions:actions.slice(0,30),generatedAt:new Date().toISOString()},{headers:{"Cache-Control":"private, no-store"}})}
