import {NextResponse} from "next/server";
import {getVGroupSql} from "@/lib/vgroup/db";
import {apiErrorResponse,requireApiBusinessUnit} from "@/lib/vgroup/api-access";
export const dynamic="force-dynamic";const uuid=/^[0-9a-f-]{36}$/i;

type OwnerRow={id:string;full_name:string;email:string|null;phone:string|null;status:string};
type PropertyRow={id:string;owner_id:string|null;name:string;property_type:string|null;city:string|null;country:string|null;bedrooms:number|null;bathrooms:number|null;max_guests:number|null;status:string};
type ReservationRow={id:string;property_id:string;source:string|null;guest_name:string;check_in:string;check_out:string;currency:string;gross_amount:number;platform_fee:number;company_commission:number;net_owner_amount:number;status:string};
type CalendarBlockRow={id:string;property_id:string;summary:string;starts_on:string;ends_on:string;source:string};
type InvoiceRow={id:string;owner_id:string;property_id:string|null;invoice_number:string;invoice_type:string;currency:string;total:number;issued_at:string;due_at:string|null;status:string;attachment_url:string|null};
type WorkOrderRow={id:string;property_id:string;title:string;description:string|null;priority:string;status:string;estimated_cost:number|null;actual_cost:number|null;created_at:string;completed_at:string|null};
type StatementRow={id:string;owner_id:string;period_start:string;period_end:string;currency:string;gross_revenue:number;total_expenses:number;total_fees:number;net_payable:number;status:string;generated_at:string;sent_at:string|null};

export async function GET(request:Request){
  try{
    const session=await requireApiBusinessUnit("hospitality");const membership=session.memberships.find(m=>m.businessUnit==="hospitality"||m.role==="GROUP_SUPER_ADMIN");const isOwner=membership?.role==="OWNER";const url=new URL(request.url);const propertyId=url.searchParams.get("propertyId")||"";if(propertyId&&!uuid.test(propertyId))return NextResponse.json({error:"invalid_property_id"},{status:400,headers:{"Cache-Control":"private, no-store"}});
    const sql=getVGroupSql();const owners=await sql<OwnerRow[]>`select id::text,full_name,email,phone,status from hospitality.owners where archived_at is null and (${isOwner}::boolean=false or user_id=${session.userId}::uuid) order by created_at desc`;const ownerIds=Array.from(owners).map(o=>String(o.id));if(isOwner&&ownerIds.length===0)return NextResponse.json({owners:[],properties:[],reservations:[],calendarBlocks:[],invoices:[],workOrders:[],statements:[],propertyScoped:Boolean(propertyId)},{headers:{"Cache-Control":"private, no-store"}});
    const allProperties:PropertyRow[]=ownerIds.length?Array.from(await sql<PropertyRow[]>`select p.id::text,p.owner_id::text,p.name,p.property_type,p.city,p.country,p.bedrooms,p.bathrooms,p.max_guests,p.status from hospitality.properties p where p.archived_at is null and p.owner_id=any(${ownerIds}::uuid[]) order by p.created_at desc`):[];
    if(propertyId&&!allProperties.some(p=>p.id===propertyId))return NextResponse.json({error:"property_not_accessible"},{status:404,headers:{"Cache-Control":"private, no-store"}});
    const properties=propertyId?allProperties.filter(p=>p.id===propertyId):allProperties;const propertyIds=properties.map(p=>String(p.id));const scopedOwnerIds=propertyId?Array.from(new Set(properties.map(p=>p.owner_id).filter(Boolean) as string[])):ownerIds;
    const reservations:ReservationRow[]=propertyIds.length?Array.from(await sql<ReservationRow[]>`select r.id::text,r.property_id::text,r.source,r.guest_name,r.check_in::text,r.check_out::text,r.currency,r.gross_amount,r.platform_fee,r.company_commission,r.net_owner_amount,r.status from hospitality.reservations r where r.archived_at is null and r.property_id=any(${propertyIds}::uuid[]) order by r.check_in desc limit 250`):[];
    const calendarBlocks:CalendarBlockRow[]=propertyIds.length?Array.from(await sql<CalendarBlockRow[]>`select b.id::text,b.property_id::text,b.summary,b.starts_on::text,b.ends_on::text,b.source from hospitality.calendar_blocks b where b.archived_at is null and b.ends_on>=current_date and b.property_id=any(${propertyIds}::uuid[]) order by b.starts_on limit 250`):[];
    const invoices:InvoiceRow[]=propertyId&&propertyIds.length?Array.from(await sql<InvoiceRow[]>`select i.id::text,i.owner_id::text,i.property_id::text,i.invoice_number,i.invoice_type,i.currency,i.total,i.issued_at,i.due_at,i.status,i.attachment_url from hospitality.invoices i where i.archived_at is null and i.property_id=any(${propertyIds}::uuid[]) order by i.issued_at desc limit 250`):scopedOwnerIds.length?Array.from(await sql<InvoiceRow[]>`select i.id::text,i.owner_id::text,i.property_id::text,i.invoice_number,i.invoice_type,i.currency,i.total,i.issued_at,i.due_at,i.status,i.attachment_url from hospitality.invoices i where i.archived_at is null and i.owner_id=any(${scopedOwnerIds}::uuid[]) order by i.issued_at desc limit 250`):[];
    const workOrders:WorkOrderRow[]=propertyIds.length?Array.from(await sql<WorkOrderRow[]>`select w.id::text,w.property_id::text,w.title,w.description,w.priority,w.status,w.estimated_cost,w.actual_cost,w.created_at,w.completed_at from hospitality.work_orders w where w.archived_at is null and w.property_id=any(${propertyIds}::uuid[]) order by w.created_at desc limit 250`):[];
    const statements:StatementRow[]=propertyId?[]:scopedOwnerIds.length?Array.from(await sql<StatementRow[]>`select s.id::text,s.owner_id::text,s.period_start,s.period_end,s.currency,s.gross_revenue,s.total_expenses,s.total_fees,s.net_payable,s.status,s.generated_at,s.sent_at from hospitality.owner_statements s where s.owner_id=any(${scopedOwnerIds}::uuid[]) order by s.period_end desc limit 100`):[];
    const scopedOwners=propertyId?Array.from(owners).filter(o=>scopedOwnerIds.includes(o.id)):Array.from(owners);
    return NextResponse.json({owners:scopedOwners,properties,reservations,calendarBlocks,invoices,workOrders,statements,propertyScoped:Boolean(propertyId)},{headers:{"Cache-Control":"private, no-store"}});
  }catch(error){return apiErrorResponse(error)}
}
