// @ts-nocheck
export const dynamic="force-dynamic";
import {auth} from "@/lib/auth";
import {redirect} from "next/navigation";
import Link from "next/link";
import {db,sql} from "@/lib/db";
import {buildOperatingIntelligence} from "@/lib/copilot/intelligence";
const WS="default",money=(v:any)=>`${Math.round(Number(v||0)).toLocaleString("en-EG")} EGP`,fmt=(v:any)=>v?new Date(v).toLocaleDateString("en-GB",{day:"2-digit",month:"short"}):"—";
export default async function TodayPage(){const s=await auth();if(!s?.user)redirect("/login");const role=String((s.user as any).role||""),userId=String((s.user as any).id||""),intel=await buildOperatingIntelligence({role,userId});
 const taskScope=role==="SUPER_ADMIN"?sql`true`:role==="ACCOUNT_MANAGER"?sql`c.account_manager_id=${userId}`:role==="MEDIA_BUYER"?sql`c.media_buyer_id=${userId}`:role==="CREATOR"?sql`t.assigned_to_id=${userId}`:role==="CLIENT"?sql`c.user_id=${userId}`:sql`false`;
 const tasks=["SUPER_ADMIN","ACCOUNT_MANAGER","MEDIA_BUYER","CREATOR","CLIENT"].includes(role)?Array.from(await db.execute(sql`select t.id,t.title,t.status,t.priority,t.deadline,c.company_name from creative_tasks t join clients c on c.id=t.client_id where t.workspace_id=${WS} and c.workspace_id=${WS} and t.archived_at is null and t.deleted_at is null and c.is_active=true and c.archived_at is null and t.status not in ('COMPLETED','REJECTED') and ${taskScope} order by case when t.deadline<now() then 0 else 1 end,t.deadline asc limit 20`) as any[]):[];
 const sales=role==="SALES"?Array.from(await db.execute(sql`select id,company_name,stage,estimated_value,probability,next_follow_up from sales_leads where workspace_id=${WS} and archived_at is null and sales_rep_id=${userId} and stage not in ('WON','LOST') order by next_follow_up asc nulls last limit 15`) as any[]):[];
 const overdue=tasks.filter((x:any)=>new Date(x.deadline).getTime()<Date.now()),today=tasks.filter((x:any)=>new Date(x.deadline).toDateString()===new Date().toDateString()),reviews=tasks.filter((x:any)=>x.status==="REVIEW"),high=tasks.filter((x:any)=>x.priority==="URGENT"||x.priority==="HIGH");const topRisks=intel.risks.slice(0,5),topOps=intel.opportunities.slice(0,5);
 return <div className="today-shell"><style>{CSS}</style><section className="today-hero"><div><span>VIVIT OPERATING SYSTEM</span><h1>Today</h1><p>{role==="SUPER_ADMIN"?"Company command center — risks, cash, delivery and decisions.":role==="CREATOR"?"Your production queue, deadlines and blockers.":role==="ACCOUNT_MANAGER"?"Your client delivery, approvals and risks.":role==="MEDIA_BUYER"?"Your client delivery and media attention queue.":role==="ACCOUNTANT"?"Collections and financial attention queue.":role==="SALES"?"Pipeline follow-ups and closing priorities.":"Your client workspace priorities."}</p></div><Link className="btn btn-primary" href="/dashboard/ai-studio/actions">Open AI Action Center</Link></section>
 <section className="today-kpis"><K label={role==="SALES"?"Open leads":"Active clients"} value={role==="SALES"?sales.length:intel.clients.length}/><K label={role==="SALES"?"Follow-ups":"Overdue tasks"} value={role==="SALES"?sales.filter((x:any)=>x.next_follow_up&&new Date(x.next_follow_up)<=new Date()).length:overdue.length}/><K label={role==="ACCOUNTANT"||role==="SUPER_ADMIN"?"Outstanding":"High priority"} value={role==="ACCOUNTANT"||role==="SUPER_ADMIN"?money(intel.summary.outstanding):high.length}/><K label={role==="SUPER_ADMIN"?"Clients at risk":"Reviews"} value={role==="SUPER_ADMIN"?intel.summary.risk:reviews.length}/></section>
 {role==="SUPER_ADMIN"&&<><section className="grid two"><Card title="Top risks" subtitle="Highest-impact issues that need a decision today">{topRisks.map((x:any)=><Row key={x.title} title={x.title} meta={x.detail} href={x.href} tone="risk"/>)}{!topRisks.length&&<Empty/>}</Card><Card title="Best opportunities" subtitle="Where action can create upside now">{topOps.map((x:any)=><Row key={x.title} title={x.title} meta={x.detail} href={x.href} tone="good"/>)}{!topOps.length&&<Empty/>}</Card></section><section className="grid two"><Card title="Team capacity" subtitle="Creator workload and overdue pressure">{intel.workload.map((x:any)=><Row key={x.id} title={`${x.name} · ${x.active} active`} meta={`${x.overdue} overdue`} href="/dashboard/creative" tone={Number(x.overdue)>0?"risk":"good"}/>)}{!intel.workload.length&&<Empty/>}</Card><Card title="Client health" subtitle="Operational score from delivery, finance and media signals">{intel.clients.slice().sort((a:any,b:any)=>a.healthScore-b.healthScore).slice(0,8).map((x:any)=><Row key={x.id} title={`${x.company_name} · ${x.healthScore}/100`} meta={x.reasons.join(" · ")||"Healthy delivery"} href={`/dashboard/clients/${x.id}`} tone={x.healthScore<70?"risk":x.healthScore<85?"warn":"good"}/>)}</Card></section></>}
 {role==="SALES"?<Card title="Next sales actions" subtitle="Follow-up order by due date">{sales.map((x:any)=><Row key={x.id} title={`${x.company_name} · ${x.stage}`} meta={`${money(x.estimated_value)} · ${Number(x.probability||0)}% · follow-up ${fmt(x.next_follow_up)}`} href="/dashboard/sales" tone="warn"/>)}{!sales.length&&<Empty/>}</Card>:role==="ACCOUNTANT"?<Card title="Collections" subtitle="Clients with outstanding balances">{intel.clients.filter((x:any)=>Number(x.outstanding)>0).sort((a:any,b:any)=>Number(b.outstanding)-Number(a.outstanding)).map((x:any)=><Row key={x.id} title={x.company_name} meta={`${money(x.outstanding)} outstanding · payment day ${x.payment_day||"—"}`} href="/dashboard/clients/accounts-payment" tone={Number(x.outstanding)>=25000?"risk":"warn"}/>)}{!intel.clients.some((x:any)=>Number(x.outstanding)>0)&&<Empty/>}</Card>:<section className="grid two"><Card title="Your priority queue" subtitle={`${today.length} due today · ${overdue.length} overdue · ${reviews.length} in review`}>{tasks.map((x:any)=><Row key={x.id} title={x.title} meta={`${x.company_name} · ${x.status.replaceAll("_"," ")} · ${fmt(x.deadline)}`} href={`/dashboard/creative/${x.id}`} tone={new Date(x.deadline)<new Date()?"risk":x.priority==="URGENT"?"risk":x.priority==="HIGH"?"warn":"normal"}/>)}{!tasks.length&&<Empty/>}</Card><Card title="Client attention" subtitle="Health, cash and delivery signals in your scope">{intel.clients.slice().sort((a:any,b:any)=>a.healthScore-b.healthScore).slice(0,10).map((x:any)=><Row key={x.id} title={`${x.company_name} · ${x.healthScore}/100`} meta={x.reasons.join(" · ")||"No blocking issues"} href={`/dashboard/clients/${x.id}`} tone={x.healthScore<70?"risk":x.healthScore<85?"warn":"good"}/>)}{!intel.clients.length&&<Empty/>}</Card></section>}
 </div>}
function K({label,value}:{label:string;value:any}){return <div className="today-kpi"><span>{label}</span><b>{value}</b></div>}function Card({title,subtitle,children}:{title:string;subtitle:string;children:any}){return <section className="today-card"><header><h2>{title}</h2><p>{subtitle}</p></header><div>{children}</div></section>}function Row({title,meta,href,tone="normal"}:{title:string;meta:string;href:string;tone?:string}){return <Link href={href} className={`today-row ${tone}`}><div><b>{title}</b><span>{meta}</span></div><strong>→</strong></Link>}function Empty(){return <div className="today-empty">Nothing needs attention here right now.</div>}
const CSS=`.today-shell{display:grid;gap:16px;max-width:1500px;margin:0 auto}.today-hero{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:22px;border:1px solid var(--card-border);background:linear-gradient(135deg,var(--card-bg),var(--bg-subtle));border-radius:22px}.today-hero span{font-size:10px;font-weight:900;letter-spacing:.14em;color:var(--text-muted)}.today-hero h1{font-size:32px;margin:4px 0}.today-hero p{color:var(--text-muted);margin:0}.today-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.today-kpi{padding:16px;border:1px solid var(--card-border);border-radius:18px;background:var(--card-bg)}.today-kpi span{display:block;font-size:10px;text-transform:uppercase;color:var(--text-muted);font-weight:800}.today-kpi b{display:block;font-size:24px;margin-top:4px}.grid.two{display:grid;grid-template-columns:1fr 1fr;gap:16px}.today-card{border:1px solid var(--card-border);border-radius:20px;background:var(--card-bg);overflow:hidden}.today-card header{padding:16px;border-bottom:1px solid var(--card-border)}.today-card h2{margin:0;font-size:17px}.today-card p{margin:4px 0 0;font-size:11px;color:var(--text-muted)}.today-row{display:flex;justify-content:space-between;align-items:center;gap:10px;padding:13px 16px;text-decoration:none;color:inherit;border-bottom:1px solid var(--card-border)}.today-row:last-child{border-bottom:0}.today-row div{display:grid;gap:3px}.today-row b{font-size:12px}.today-row span{font-size:10.5px;color:var(--text-muted)}.today-row.risk{border-left:3px solid #dc2626}.today-row.warn{border-left:3px solid #d97706}.today-row.good{border-left:3px solid #16a34a}.today-empty{padding:24px;text-align:center;color:var(--text-muted);font-size:11px}@media(max-width:820px){.today-hero{align-items:flex-start;flex-direction:column}.today-kpis,.grid.two{grid-template-columns:1fr 1fr}.today-kpi b{font-size:19px}}@media(max-width:520px){.today-kpis,.grid.two{grid-template-columns:1fr}.today-hero h1{font-size:26px}}`;
