"use client";
import {useEffect,useState} from "react";
import Link from "next/link";

type Rec={level:string;type:string;title:string;why:string;action:string;href:string;score:number};
const tone:Record<string,string>={critical:"#b91c1c",high:"#c2410c",medium:"#a16207",info:"#2563eb"};
export default function TodayPage(){const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true);useEffect(()=>{fetch("/api/copilot",{cache:"no-store"}).then(r=>r.json()).then(setData).finally(()=>setLoading(false))},[]);if(loading)return <div style={{padding:24}}>Preparing your day…</div>;if(!data||data.error)return <div className="card" style={{padding:24}}>Could not load Today.</div>;const recs:Rec[]=data.recommendations||[];const role=String(data.role||"").replace(/_/g," ");return <div style={{display:"grid",gap:18,padding:"20px clamp(14px,2vw,26px)"}}><section style={{borderRadius:24,padding:24,color:"white",background:"linear-gradient(135deg,#241934,#6d28d9 50%,#c52a31)",boxShadow:"0 24px 70px rgba(60,30,90,.2)"}}><div style={{display:"flex",justifyContent:"space-between",gap:18,flexWrap:"wrap",alignItems:"start"}}><div><div style={{fontSize:12,opacity:.75,fontWeight:800,letterSpacing:1}}>VIVIT COPILOT · {role.toUpperCase()}</div><h1 style={{fontSize:"clamp(28px,4vw,44px)",margin:"5px 0 7px",lineHeight:1.05}}>Your day, already prioritized.</h1><p style={{opacity:.83,maxWidth:700}}>I continuously rank what needs attention using your live tasks, client scope, billing signals and media data. Ask me anything, or act on the cards below.</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><Link href="/dashboard/ai-studio" className="btn btn-secondary" style={{textDecoration:"none"}}>Ask Copilot</Link>{["SUPER ADMIN","CREATOR","ACCOUNT MANAGER"].includes(role.toUpperCase())&&<Link href="/dashboard/ai-studio/image" className="btn btn-secondary" style={{textDecoration:"none"}}>Generate Creative</Link>}</div></div></section>
<section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:10}}>{[{l:"Active tasks",v:data.counts?.tasks||0},{l:"Clients in scope",v:data.counts?.clients||0},{l:"Payments due",v:data.counts?.billing||0},{l:"Campaigns read",v:data.counts?.campaigns||0}].map(x=><div className="card" key={x.l} style={{padding:16}}><div style={{fontSize:11,color:"var(--text-muted)",fontWeight:800,textTransform:"uppercase"}}>{x.l}</div><div style={{fontSize:28,fontWeight:900,marginTop:5}}>{x.v}</div></div>)}</section>
<section className="card" style={{padding:18}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",marginBottom:12}}><div><h2 style={{fontSize:20}}>What needs attention</h2><p style={{fontSize:12,color:"var(--text-muted)"}}>Ranked by urgency, financial impact and delivery risk.</p></div><div style={{fontSize:11,color:"var(--text-muted)"}}>Generated {new Date(data.freshness?.generatedAt).toLocaleTimeString()}</div></div><div style={{display:"grid",gap:10}}>{recs.length?recs.map((r,i)=><div key={`${r.title}-${i}`} style={{display:"grid",gridTemplateColumns:"6px minmax(0,1fr) auto",gap:12,alignItems:"stretch",border:"1px solid var(--card-border)",borderRadius:14,overflow:"hidden"}}><div style={{background:tone[r.level]||"#64748b"}}/><div style={{padding:"13px 0"}}><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><b style={{fontSize:14}}>{r.title}</b><span style={{fontSize:9,fontWeight:900,color:tone[r.level]||"#64748b",textTransform:"uppercase"}}>{r.level} · {r.score}/100</span></div><div style={{fontSize:12,color:"var(--text-muted)",marginTop:4}}>{r.why}</div></div><div style={{display:"grid",placeItems:"center",paddingRight:12}}><Link href={r.href} className="btn btn-primary btn-sm" style={{textDecoration:"none",whiteSpace:"nowrap"}}>{r.action}</Link></div></div>):<div style={{padding:26,textAlign:"center",color:"var(--text-muted)"}}>No urgent blockers detected. Copilot will keep watching.</div>}</div></section>
<section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(250px,1fr))",gap:12}}>{[{t:"ASK",d:"Ask anything about your work, a client, marketing strategy, content, design, editing or media buying.",href:"/dashboard/ai-studio"},{t:"ADVISE",d:"Copilot watches your live ERP signals and brings recommendations to you before you ask.",href:"/dashboard/today"},{t:"ACT",d:"Open an action card, review the prepared step, then execute it with the permissions of your role.",href:"/dashboard/tasks-inbox"}].map(x=><Link key={x.t} href={x.href} className="card" style={{padding:18,textDecoration:"none",color:"inherit"}}><div style={{fontSize:11,fontWeight:900,color:"#7c3aed",letterSpacing:1}}>{x.t}</div><b style={{display:"block",fontSize:16,marginTop:5}}>{x.d}</b></Link>)}</section></div>}
