export const dynamic="force-dynamic";
import {NextRequest,NextResponse} from "next/server";
import {auth} from "@/lib/auth";
import {db,sql} from "@/lib/db";
import {generateText} from "@/lib/copilot/provider";
const WS="default";
function roleScope(role:string,userId:string){if(role==="SUPER_ADMIN")return sql`true`;if(role==="ACCOUNT_MANAGER")return sql`c.account_manager_id=${userId}`;if(role==="MEDIA_BUYER")return sql`c.media_buyer_id=${userId}`;if(role==="CLIENT")return sql`c.user_id=${userId}`;return sql`true`}
async function context(role:string,userId:string){const scope=roleScope(role,userId);const taskScope=role==="CREATOR"?sql`t.assigned_to_id=${userId}`:scope;
 const [tasks,clients,billing,media]=await Promise.all([
  db.execute(sql`select t.id,t.title,t.status,t.priority,t.deadline,c.company_name from creative_tasks t join clients c on c.id=t.client_id where t.workspace_id=${WS} and t.archived_at is null and c.is_active=true and ${taskScope} and t.status not in ('COMPLETED','REJECTED') order by t.deadline asc limit 50`),
  ["SUPER_ADMIN","ACCOUNT_MANAGER","MEDIA_BUYER"].includes(role)?db.execute(sql`select c.id,c.company_name,c.health_score,c.churn_risk,c.monthly_retainer from clients c where c.workspace_id=${WS} and c.is_active=true and ${scope} order by c.company_name limit 50`):Promise.resolve([]),
  ["SUPER_ADMIN","ACCOUNT_MANAGER","ACCOUNTANT"].includes(role)?db.execute(sql`select c.company_name,coalesce(p.outstanding,0) outstanding,p.payment_status,p.next_due_date from clients c left join client_payment_profiles p on p.client_id=c.id where c.workspace_id=${WS} and c.is_active=true and ${scope} order by coalesce(p.outstanding,0) desc limit 50`):Promise.resolve([]),
  ["SUPER_ADMIN","ACCOUNT_MANAGER","MEDIA_BUYER","CLIENT"].includes(role)?db.execute(sql`select c.company_name,ac.name,ac.status,ac.reported_result_label,coalesce((ac.reported_metrics->>'spend')::numeric,0) spend,coalesce((ac.reported_metrics->>'results')::numeric,0) results,coalesce((ac.reported_metrics->>'costPerResult')::numeric,0) cost_per_result,coalesce((ac.reported_metrics->>'addToCart')::numeric,0) atc,coalesce((ac.reported_metrics->>'purchases')::numeric,0) purchases,coalesce((ac.reported_metrics->>'ctr')::numeric,0) ctr,ac.last_sync_at from ad_campaigns ac join clients c on c.id=ac.client_id where c.workspace_id=${WS} and c.is_active=true and ac.archived_at is null and ${scope} order by ac.last_sync_at desc nulls last limit 80`):Promise.resolve([])
 ]);
 return{tasks:Array.from(tasks as any),clients:Array.from(clients as any),billing:Array.from(billing as any),media:Array.from(media as any)};
}
function recommendationSet(role:string,ctx:any){const now=Date.now(),items:any[]=[];for(const t of ctx.tasks||[]){const due=new Date(t.deadline).getTime(),hours=(due-now)/36e5;if(hours<0)items.push({level:"critical",type:"task",title:`Overdue: ${t.title}`,why:`${t.company_name} · deadline passed`,action:"Open task",href:`/dashboard/creative/${t.id}`,score:95});else if(hours<24)items.push({level:"high",type:"task",title:`Due within 24h: ${t.title}`,why:`${t.company_name} · ${Math.max(1,Math.round(hours))}h left`,action:"Open task",href:`/dashboard/creative/${t.id}`,score:85})}
 for(const b of ctx.billing||[]){const o=Number(b.outstanding||0);if(o>0)items.push({level:o>=25000?"critical":"high",type:"finance",title:`Collect ${Number(o).toLocaleString("en-EG")} EGP from ${b.company_name}`,why:`Payment status: ${b.payment_status||"DUE"}`,action:"Open payments",href:"/dashboard/clients/accounts-payment",score:Math.min(98,70+Math.round(o/2000))})}
 for(const m of ctx.media||[]){const spend=Number(m.spend||0),r=Number(m.results||0),c=Number(m.cost_per_result||0),ctr=Number(m.ctr||0);if(spend>500&&r===0)items.push({level:"critical",type:"media",title:`${m.company_name}: ${m.name} spent without primary results`,why:`Spend ${spend.toFixed(0)} EGP · ${m.reported_result_label||"Result"} = 0`,action:"Review campaign",href:"/dashboard/media/control-center",score:94});else if(c>0&&spend>1000)items.push({level:"medium",type:"media",title:`Review cost efficiency: ${m.company_name} · ${m.name}`,why:`${m.reported_result_label||"Result"} cost ${c.toFixed(1)} EGP · CTR ${ctr.toFixed(2)}%`,action:"Open media",href:"/dashboard/media/control-center",score:60})}
 if(role==="CREATOR"&&!items.length)items.push({level:"info",type:"plan",title:"Production queue is under control",why:"No overdue or next-24h blockers detected.",action:"Open Creative",href:"/dashboard/creative",score:30});return items.sort((a,b)=>b.score-a.score).slice(0,12)}
export async function GET(){const s=await auth();if(!s?.user)return NextResponse.json({error:"Unauthorized"},{status:401});const role=String((s.user as any).role||"CLIENT"),userId=String((s.user as any).id||"");const ctx=await context(role,userId),recommendations=recommendationSet(role,ctx);return NextResponse.json({role,recommendations,counts:{tasks:ctx.tasks.length,clients:ctx.clients.length,billing:ctx.billing.filter((x:any)=>Number(x.outstanding)>0).length,campaigns:ctx.media.length},freshness:{generatedAt:new Date().toISOString(),mediaLastSync:ctx.media.map((x:any)=>x.last_sync_at).filter(Boolean).sort().at(-1)||null}},{headers:{"Cache-Control":"private, no-store"}})}
export async function POST(req:NextRequest){const s=await auth();if(!s?.user)return NextResponse.json({error:"Unauthorized"},{status:401});const role=String((s.user as any).role||"CLIENT"),userId=String((s.user as any).id||""),body=await req.json().catch(()=>({})),question=String(body.question||"").trim().slice(0,1800);if(!question)return NextResponse.json({error:"Ask a question first."},{status:400});const ctx=await context(role,userId),recs=recommendationSet(role,ctx),roleRules:Record<string,string>={CLIENT:"Answer only about this client's tasks, approvals, deadlines, media summary and visible portal information. Never expose internal notes, other clients, staff finance or agency data.",CREATOR:"Act as a creative production copilot: prioritize work, improve briefs, suggest design/content/video execution, and use assigned task context.",ACCOUNT_MANAGER:"Act as an account operations copilot: manage client priorities, tasks, approvals, communication, billing signals and marketing recommendations.",MEDIA_BUYER:"Act as a media buying copilot: analyze campaign objectives/results correctly (messages, ATC, purchases, leads), diagnose trends and recommend tests or budget actions without changing spend automatically.",ACCOUNTANT:"Act as a finance operations copilot using billing and payment context only.",SALES:"Act as a sales copilot focused on prioritization, follow-up, qualification and closing support.",SUPER_ADMIN:"Act as VIVIT's executive COO/CMO/CFO copilot. Connect operations, clients, finance, media and team execution. Surface root causes, risks, opportunities and concrete actions."};const system=`You are VIVIT Copilot. ${roleRules[role]||"Help the user do their role."}\nRules: Be proactive, decisive and practical. Distinguish LIVE ERP facts from general marketing knowledge. Never invent numbers. If data is missing say so. For marketing strategy/content/design/editing/media questions, answer as a senior practitioner. When recommending an action, state expected impact and risk. Use Arabic when the user writes Arabic. Live context is authoritative only for the supplied JSON.`;const prompt=`USER QUESTION:\n${question}\n\nLIVE ERP CONTEXT:\n${JSON.stringify(ctx).slice(0,24000)}\n\nCURRENT PROACTIVE RECOMMENDATIONS:\n${JSON.stringify(recs).slice(0,8000)}\n\nAnswer with: direct answer, then recommended next actions when useful, then Sources: list LIVE ERP modules used or 'General marketing knowledge'.`;
 try{const out=await generateText({system,prompt});return NextResponse.json({answer:out.text,provider:out.provider,sources:["Tasks",ctx.clients.length&&"Clients",ctx.billing.length&&"Billing",ctx.media.length&&"Media"].filter(Boolean),freshness:{generatedAt:new Date().toISOString()}})}catch(e:any){return NextResponse.json({error:"AI providers are temporarily unavailable. Live recommendations remain available on Today.",detail:String(e?.message||e).slice(0,300)},{status:503})}}
