// @ts-nocheck
export const dynamic="force-dynamic";
import {auth} from "@/lib/auth";
import {redirect} from "next/navigation";
import {db,creativeTasks,clients,users,sql} from "@/lib/db";
import {eq,and,notInArray,desc,inArray} from "drizzle-orm";
import {Role} from "@/lib/types";
import Link from "next/link";

const BULK_ACTIONS:Record<string,{status:string;priority?:string}>={approve:{status:"APPROVED"},complete:{status:"COMPLETED"},in_progress:{status:"IN_PROGRESS"},urgent_on:{status:"PENDING",priority:"URGENT"}};
async function bulkAction(fd:FormData){"use server";const session=await auth();if(!session?.user||![Role.SUPER_ADMIN,Role.ACCOUNT_MANAGER].includes((session.user as any).role))throw new Error("Unauthorized");const role=(session.user as any).role as Role,userId=String((session.user as any).id||""),action=String(fd.get("action")||""),ids=Array.from(new Set(fd.getAll("taskId").map(v=>String(v)).filter(Boolean))).slice(0,100),target=BULK_ACTIONS[action];if(!target||!ids.length)return;const activeOnly=sql`${creativeTasks.id} in (select id from creative_tasks where archived_at is null)`;let scope:any=and(inArray(creativeTasks.id,ids),activeOnly);if(role===Role.ACCOUNT_MANAGER){const owned=await db.select({id:clients.id}).from(clients).where(and(eq(clients.accountManagerId,userId),eq(clients.isActive,true))),ownedIds=owned.map(c=>c.id);if(!ownedIds.length)return;scope=and(inArray(creativeTasks.id,ids),inArray(creativeTasks.clientId,ownedIds),activeOnly);}await db.update(creativeTasks).set({status:target.status as any,...(target.priority?{priority:target.priority as any}:{}),updatedAt:new Date()}).where(scope);const {revalidatePath}=await import("next/cache");revalidatePath("/dashboard/tasks-inbox");revalidatePath("/dashboard/creative");}
const ICON:Record<string,string>={REEL:"🎬",GRAPHIC:"🎨",CAROUSEL:"📊",MOTION_GRAPHIC:"✨",VIDEO_EDIT:"🎥",PHOTO_SESSION:"📸",STORY:"📱",UGC:"👤"};
const PRIORITY:Record<string,string>={URGENT:"badge-red",HIGH:"badge-amber",MEDIUM:"badge-blue",LOW:"badge-gray"};

export default async function TasksInboxPage(){
 const session=await auth();if(!session?.user)redirect("/login");const role=(session.user as any).role as Role;if(![Role.SUPER_ADMIN,Role.ACCOUNT_MANAGER].includes(role))redirect("/dashboard");const userId=String((session.user as any).id||"");
 const ownedClients=role===Role.ACCOUNT_MANAGER?await db.select({id:clients.id,companyName:clients.companyName}).from(clients).where(and(eq(clients.accountManagerId,userId),eq(clients.isActive,true))):await db.select({id:clients.id,companyName:clients.companyName}).from(clients).where(eq(clients.isActive,true)),ownedIds=ownedClients.map(c=>c.id),activeStatus=notInArray(creativeTasks.status,["COMPLETED","REJECTED"]),activeOnly=sql`${creativeTasks.id} in (select id from creative_tasks where archived_at is null)`,scope=role===Role.ACCOUNT_MANAGER?(ownedIds.length?and(activeStatus,activeOnly,inArray(creativeTasks.clientId,ownedIds)):eq(creativeTasks.id,"__none__")):and(activeStatus,activeOnly);
 const [tasks,creators]=await Promise.all([db.select({id:creativeTasks.id,title:creativeTasks.title,type:creativeTasks.type,status:creativeTasks.status,priority:creativeTasks.priority,deadline:creativeTasks.deadline,clientId:creativeTasks.clientId,assignedToId:creativeTasks.assignedToId,revisionCount:creativeTasks.revisionCount,fileUrl:creativeTasks.fileUrl,brief:creativeTasks.brief,createdAt:creativeTasks.createdAt}).from(creativeTasks).where(scope).orderBy(desc(creativeTasks.updatedAt)).limit(100),db.select({id:users.id,name:users.name}).from(users).where(eq(users.role,"CREATOR"))]);
 const clientMap=Object.fromEntries(ownedClients.map(c=>[c.id,c.companyName])),creatorMap=Object.fromEntries(creators.map(c=>[c.id,c.name])),now=new Date();
 const groups=[{key:"review",label:"Awaiting Review",icon:"👀",color:"var(--amber)",items:tasks.filter(t=>t.status==="REVIEW")},{key:"overdue",label:"Overdue",icon:"🚨",color:"var(--red)",items:tasks.filter(t=>new Date(t.deadline)<now&&t.status!=="REVIEW")},{key:"revision",label:"Needs Revision",icon:"🔄",color:"var(--red)",items:tasks.filter(t=>t.status==="REVISION"&&new Date(t.deadline)>=now)},{key:"progress",label:"In Progress",icon:"⚙️",color:"var(--vivit-blue)",items:tasks.filter(t=>t.status==="IN_PROGRESS"&&new Date(t.deadline)>=now)},{key:"pending",label:"Pending",icon:"📋",color:"var(--text-muted)",items:tasks.filter(t=>t.status==="PENDING"&&new Date(t.deadline)>=now)}];
 const due=(d:Date)=>{const days=Math.ceil((d.getTime()-now.getTime())/86400000);return days<0?`${Math.abs(days)}d late`:days===0?"Due today":`${days}d left`};
 const overdueCount=tasks.filter(t=>new Date(t.deadline)<now).length;
 return <div style={{display:"grid",gap:18,minWidth:0}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div><h1 className="page-title">Tasks Inbox</h1><p className="page-subtitle">{tasks.length} active · {tasks.filter(t=>t.status==="REVIEW").length} awaiting review · {overdueCount} overdue</p></div><Link href="/dashboard/creative/new" className="btn btn-primary" style={{textDecoration:"none"}}>+ New Task</Link></div>
 <form action={bulkAction} style={{display:"grid",gap:16}}><div className="card"><div className="card-body" style={{display:"flex",gap:7,alignItems:"center",flexWrap:"wrap",padding:12}}><b style={{fontSize:11,color:"var(--text-muted)",marginRight:4}}>SELECT CARDS, THEN:</b><button name="action" value="approve" className="btn btn-primary btn-sm">Approve</button><button name="action" value="complete" className="btn btn-ghost btn-sm">Complete</button><button name="action" value="urgent_on" className="btn btn-ghost btn-sm">Set Urgent</button><button name="action" value="in_progress" className="btn btn-ghost btn-sm">In Progress</button></div></div>
 {groups.map(group=>group.items.length?<section key={group.key} className="card" style={{borderLeft:`4px solid ${group.color}`}}><div className="card-header"><div style={{display:"flex",gap:8,alignItems:"center"}}><span>{group.icon}</span><p className="card-title">{group.label}</p><span className="badge badge-gray">{group.items.length}</span></div></div><div className="card-body" style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(250px,1fr))",gap:10}}>{group.items.map(t=>{const deadline=new Date(t.deadline),late=deadline<now;return <article key={`${group.key}-${t.id}`} style={{border:"1px solid var(--card-border)",borderRadius:14,padding:12,background:"var(--card-bg)",display:"grid",gap:9}}><div style={{display:"flex",gap:9,alignItems:"flex-start"}}><input type="checkbox" name="taskId" value={t.id} aria-label={`Select ${t.title}`} style={{marginTop:4,accentColor:"var(--vivit-blue)"}}/><span style={{fontSize:21}}>{ICON[t.type]||"📁"}</span><div style={{minWidth:0,flex:1}}><Link href={`/dashboard/creative/${t.id}`} style={{fontWeight:800,fontSize:13.5,textDecoration:"none",color:"var(--text-primary)",lineHeight:1.35}}>{t.title}</Link><p style={{fontSize:11,color:"var(--text-muted)",marginTop:3}}>{clientMap[t.clientId]||"Client"} · {creatorMap[t.assignedToId]||"Unassigned"}</p></div></div><div style={{display:"flex",gap:6,flexWrap:"wrap"}}><span className={`badge ${PRIORITY[t.priority]}`}>{t.priority}</span><span className={`badge ${late?"badge-red":"badge-gray"}`}>{due(deadline)}</span><span className="badge badge-gray">{t.status.replace(/_/g," ")}</span>{t.revisionCount>0&&<span className="badge badge-red">↩ {t.revisionCount}</span>}</div><p style={{fontSize:11.5,color:"var(--text-secondary)",lineHeight:1.5,display:"-webkit-box",WebkitLineClamp:2,WebkitBoxOrient:"vertical",overflow:"hidden"}}>{t.brief}</p><div style={{display:"flex",gap:6}}>{t.fileUrl&&<a href={t.fileUrl} target="_blank" rel="noreferrer" className="btn btn-ghost btn-sm" style={{textDecoration:"none"}}>View file</a>}<Link href={`/dashboard/creative/${t.id}`} className="btn btn-primary btn-sm" style={{flex:1,textDecoration:"none",justifyContent:"center"}}>Open & Reply →</Link></div></article>})}</div></section>:null)}
 {!tasks.length&&<div className="card"><div className="empty-state"><p className="empty-state-icon">✅</p><p className="empty-state-title">Inbox is clear</p><p className="empty-state-desc">No active tasks in your current client scope.</p></div></div>}</form></div>;
}
