// @ts-nocheck -- Drizzle's generated upsert shape is narrower than the live schema.
import {NextRequest,NextResponse} from "next/server";
import {auth} from "@/lib/auth";
import {db,adPlatformConnections,auditLogs} from "@/lib/db";
import {exchangeCode,verifyState,encryptToken,OAuthPlatform} from "@/lib/ad-oauth";

async function discoverSnapAccount(accessToken:string){const headers={Authorization:`Bearer ${accessToken}`};const orgRes=await fetch("https://adsapi.snapchat.com/v1/me/organizations",{headers});const orgJson=await orgRes.json();if(!orgRes.ok)throw new Error(orgJson?.request_status||"Unable to list Snapchat organizations");for(const item of orgJson.organizations||[]){const org=item.organization||item;if(!org?.id)continue;const accountRes=await fetch(`https://adsapi.snapchat.com/v1/organizations/${org.id}/adaccounts`,{headers});const accountJson=await accountRes.json();if(!accountRes.ok)continue;const first=(accountJson.adaccounts||[])[0];const account=first?.adaccount||first;if(account?.id)return{id:String(account.id),name:String(account.name||org.name||"Snapchat Ad Account")};}throw new Error("No Snapchat ad account is available for this user");}

export async function GET(req:NextRequest,{params}:{params:Promise<{platform:string}>}){const home=new URL("/dashboard/media/sync",req.url);try{const session=await auth();if(!session?.user)throw new Error("Session expired — sign in and try again");const {platform:raw}=await params,platform=raw.toUpperCase() as OAuthPlatform;const state=verifyState(req.nextUrl.searchParams.get("state")||"");if(state.platform!==platform||state.userId!==(session.user as any).id)throw new Error("OAuth state mismatch");const error=req.nextUrl.searchParams.get("error");if(error)throw new Error(req.nextUrl.searchParams.get("error_description")||error);const code=req.nextUrl.searchParams.get("code")||req.nextUrl.searchParams.get("auth_code")||"";if(!code)throw new Error("Authorization code was not returned");const tokens=await exchangeCode(platform,code);const discovered=platform==="SNAPCHAT"&&state.adAccountId==="auto"?await discoverSnapAccount(tokens.accessToken):null;const adAccountId=discovered?.id||state.adAccountId,accountName=state.accountName||discovered?.name||`${platform} Ad Account`;const [row]=await db.insert(adPlatformConnections).values({clientId:state.clientId,platform,adAccountId,accountName,accessTokenEncrypted:encryptToken(tokens.accessToken),refreshTokenEncrypted:encryptToken(tokens.refreshToken),tokenExpiresAt:tokens.expiresIn?new Date(Date.now()+tokens.expiresIn*1000):null,status:"CONNECTED",createdBy:state.userId}).onConflictDoUpdate({target:[adPlatformConnections.platform,adPlatformConnections.adAccountId],set:{clientId:state.clientId,accountName,accessTokenEncrypted:encryptToken(tokens.accessToken),refreshTokenEncrypted:encryptToken(tokens.refreshToken),tokenExpiresAt:tokens.expiresIn?new Date(Date.now()+tokens.expiresIn*1000):null,status:"CONNECTED",syncError:null,updatedAt:new Date()}}).returning();await db.insert(auditLogs).values({userId:state.userId,action:"ad_platform_oauth_connected",entity:"ad_platform_connections",entityId:row.id,newValues:JSON.stringify({platform,adAccountId})});home.searchParams.set("oauth","success");home.searchParams.set("platform",platform);return NextResponse.redirect(home);}catch(e:any){home.searchParams.set("oauth","error");home.searchParams.set("message",String(e.message||"Connection failed").slice(0,180));return NextResponse.redirect(home);}}
