export const dynamic="force-dynamic";
import {NextRequest,NextResponse} from "next/server";
import {auth} from "@/lib/auth";
import {db,clients,adCampaigns,adPlatformConnections,sql} from "@/lib/db";
import {and,eq} from "drizzle-orm";
import {platformConfigured,syncCampaign} from "@/lib/ad-platforms";
import {connectionAccessToken} from "@/lib/ad-oauth";

const iso=(d:Date)=>d.toISOString().slice(0,10),n=(v:unknown)=>Number(v||0);
export async function POST(_req:NextRequest,{params}:{params:Promise<{campaignId:string}>}){
 const session=await auth();if(!session?.user)return NextResponse.json({error:"Unauthorized"},{status:401});
 const role=String(session.user.role||""),userId=String(session.user.id||"");if(!["SUPER_ADMIN","MEDIA_BUYER","ACCOUNT_MANAGER"].includes(role))return NextResponse.json({error:"Forbidden"},{status:403});
 const {campaignId}=await params;const [campaign]=await db.select().from(adCampaigns).where(eq(adCampaigns.id,campaignId)).limit(1);if(!campaign)return NextResponse.json({error:"Campaign not found"},{status:404});
 const active=Array.from(await db.execute(sql`select 1 from ad_campaigns where id=${campaign.id} and archived_at is null limit 1`));if(!active.length)return NextResponse.json({error:"Restore the campaign before syncing it."},{status:409});
 const [client]=await db.select({id:clients.id,mediaBuyerId:clients.mediaBuyerId,accountManagerId:clients.accountManagerId,isActive:clients.isActive}).from(clients).where(and(eq(clients.id,campaign.clientId),eq(clients.isActive,true))).limit(1);if(!client||role==="MEDIA_BUYER"&&client.mediaBuyerId!==userId||role==="ACCOUNT_MANAGER"&&client.accountManagerId!==userId)return NextResponse.json({error:"Client access denied"},{status:403});
 const connection=campaign.connectionId?(await db.select().from(adPlatformConnections).where(eq(adPlatformConnections.id,campaign.connectionId)).limit(1))[0]:(await db.select().from(adPlatformConnections).where(and(eq(adPlatformConnections.clientId,campaign.clientId),eq(adPlatformConnections.platform,campaign.platform))).limit(1))[0];if(!connection||connection.clientId!==campaign.clientId||connection.platform!==campaign.platform)return NextResponse.json({error:"Reconnect the correct ad account first."},{status:400});
 let accessToken="";try{accessToken=await connectionAccessToken(connection)}catch{accessToken="";}if(!accessToken&&!platformConfigured(campaign.platform))return NextResponse.json({error:"Platform authorization expired. Reconnect the account."},{status:400});
 const end=new Date(),start=new Date(Date.now()-30*86400000),startIso=iso(start),endIso=iso(end);
 try{
  const result=await syncCampaign({platform:campaign.platform,campaignId:campaign.externalId,adAccountId:connection.adAccountId,accessToken:accessToken||undefined,start:startIso,end:endIso});
  for(const day of result.days){const date=`${day.date} 00:00:00`,spend=n(day.spend),results=n(day.results),purchases=n(day.purchases),impressions=n(day.impressions),clicks=n(day.clicks),revenue=n(day.revenue),reach=n(day.reach),frequency=n(day.frequency),atc=Math.max(0,Math.round(n(day.addToCart))),ctr=n(day.ctr)||(impressions?clicks/impressions*100:0),cpc=n(day.cpc)||(clicks?spend/clicks:0),cpm=n(day.cpm)||(impressions?spend/impressions*1000:0),cpr=n(day.costPerResult)||(results?spend/results:0);await db.execute(sql`delete from ad_performance_daily where campaign_id=${campaign.id} and date=${date}::timestamp and breakdown_type='TOTAL' and ad_id is null`);await db.execute(sql`insert into ad_performance_daily(id,campaign_id,date,breakdown_type,breakdown_value,spend,impressions,reach,clicks,results,qualified_leads,purchases,add_to_cart,revenue,frequency,ctr,cpc,cpm,cpl,cost_per_result,cpa,roas) values(gen_random_uuid()::text,${campaign.id},${date}::timestamp,'TOTAL','ALL',${spend},${impressions},${reach},${clicks},${results},0,${purchases},${atc},${revenue},${frequency},${ctr},${cpc},${cpm},${cpr},${cpr},${purchases?spend/purchases:0},${spend?revenue/spend:0})`)}
  if(result.summary)await db.execute(sql`update ad_campaigns set reported_metrics=${JSON.stringify(result.summary)}::jsonb,reported_period_start=${startIso}::date,reported_period_end=${endIso}::date,reported_result_type=${result.summary.resultType||null},reported_result_label=${result.summary.resultLabel||null} where id=${campaign.id}`);
  await db.update(adCampaigns).set({name:result.name||campaign.name,status:result.status||campaign.status,lastSyncAt:new Date(),updatedAt:new Date()}).where(eq(adCampaigns.id,campaign.id));await db.update(adPlatformConnections).set({lastSyncAt:new Date(),syncError:null,status:"CONNECTED",updatedAt:new Date()}).where(eq(adPlatformConnections.id,connection.id));return NextResponse.json({success:true,days:result.days.length,summary:result.summary||null});
 }catch(error:unknown){const message=(error instanceof Error?error.message:"Sync failed").slice(0,700);await db.update(adPlatformConnections).set({syncError:message,status:"ERROR",updatedAt:new Date()}).where(eq(adPlatformConnections.id,connection.id));return NextResponse.json({error:message},{status:400});}
}
