export const dynamic="force-dynamic";
import {NextRequest,NextResponse} from "next/server";
import {auth} from "@/lib/auth";
import {db,clients,adCampaigns,adPlatformConnections,adPerformanceDaily} from "@/lib/db";
import {and,eq,isNull,sql} from "drizzle-orm";
import {platformConfigured,syncCampaign} from "@/lib/ad-platforms";
import {connectionAccessToken} from "@/lib/ad-oauth";

const iso=(d:Date)=>d.toISOString().slice(0,10);
export async function POST(_req:NextRequest,{params}:{params:Promise<{campaignId:string}>}){
 const session=await auth();if(!session?.user)return NextResponse.json({error:"Unauthorized"},{status:401});
 const role=String((session.user as any).role||""),userId=String((session.user as any).id||"");if(!["SUPER_ADMIN","MEDIA_BUYER"].includes(role))return NextResponse.json({error:"Forbidden"},{status:403});
 const {campaignId}=await params;const [campaign]=await db.select().from(adCampaigns).where(eq(adCampaigns.id,campaignId)).limit(1);if(!campaign)return NextResponse.json({error:"Campaign not found"},{status:404});
 const [client]=await db.select({id:clients.id,mediaBuyerId:clients.mediaBuyerId}).from(clients).where(eq(clients.id,campaign.clientId)).limit(1);if(!client||role==="MEDIA_BUYER"&&client.mediaBuyerId!==userId)return NextResponse.json({error:"Client access denied"},{status:403});
 const connection=campaign.connectionId?(await db.select().from(adPlatformConnections).where(eq(adPlatformConnections.id,campaign.connectionId)).limit(1))[0]:(await db.select().from(adPlatformConnections).where(and(eq(adPlatformConnections.clientId,campaign.clientId),eq(adPlatformConnections.platform,campaign.platform))).limit(1))[0];if(!connection)return NextResponse.json({error:"Connect the ad account first."},{status:400});
 let accessToken="";try{accessToken=await connectionAccessToken(connection)}catch{accessToken="";}if(!accessToken&&!platformConfigured(campaign.platform))return NextResponse.json({error:"Platform authorization expired. Reconnect the account."},{status:400});
 const end=new Date(),start=new Date(Date.now()-30*86400000);
 try{const result=await syncCampaign({platform:campaign.platform,campaignId:campaign.externalId,adAccountId:connection.adAccountId,accessToken:accessToken||undefined,start:iso(start),end:iso(end)});for(const day of result.days){const date=new Date(`${day.date}T00:00:00Z`);await db.delete(adPerformanceDaily).where(and(eq(adPerformanceDaily.campaignId,campaign.id),eq(adPerformanceDaily.date,date),eq(adPerformanceDaily.breakdownType,"TOTAL"),isNull(adPerformanceDaily.adId)));const cpl=day.results?day.spend/day.results:0,roas=day.spend?day.revenue/day.spend:0;await db.insert(adPerformanceDaily).values({campaignId:campaign.id,date,spend:day.spend,impressions:day.impressions,reach:day.reach,clicks:day.clicks,results:day.results,purchases:day.purchases,revenue:day.revenue,frequency:day.frequency,ctr:day.impressions?day.clicks/day.impressions*100:0,cpc:day.clicks?day.spend/day.clicks:0,cpm:day.impressions?day.spend/day.impressions*1000:0,cpl,roas});await db.execute(sql`update ad_performance_daily set add_to_cart=${Math.max(0,Math.round(day.addToCart||0))} where campaign_id=${campaign.id} and date=${date} and breakdown_type='TOTAL' and ad_id is null`);}await db.update(adCampaigns).set({name:result.name||campaign.name,status:result.status||campaign.status,lastSyncAt:new Date(),updatedAt:new Date()}).where(eq(adCampaigns.id,campaign.id));await db.update(adPlatformConnections).set({lastSyncAt:new Date(),syncError:null,status:"CONNECTED",updatedAt:new Date()}).where(eq(adPlatformConnections.id,connection.id));const totals=result.days.reduce((a,d)=>({atc:a.atc+d.addToCart,purchases:a.purchases+d.purchases}),{atc:0,purchases:0});return NextResponse.json({success:true,days:result.days.length,atc:totals.atc,purchases:totals.purchases});}catch(error:any){const message=String(error?.message||"Sync failed").slice(0,500);await db.update(adPlatformConnections).set({syncError:message,status:"ERROR",updatedAt:new Date()}).where(eq(adPlatformConnections.id,connection.id));return NextResponse.json({error:message},{status:400});}
}
