"use client";
import {useState} from "react";

type ActionProposal={op:string;summary:string;args:Record<string,unknown>;risk:"low"|"medium"|"high"|"destructive";missingFields?:string[]};
type Response={answer?:string;error?:string;actionProposal?:ActionProposal};

export function VivitoStudioConsole({role}:{role:string}){
 const prompts=role==="CLIENT"?["Show my current tasks","What is waiting for review?","What is my closest deadline?","Explain my current account status"]:role==="MEDIA_BUYER"?["Review media performance for my clients","Which campaigns need attention and why?","Check tracking health before optimization","Give me a media buying decision plan without changing anything"]:role==="ACCOUNT_MANAGER"?["Show overdue work across my clients","Which clients need attention today?","Build a client action plan","Review client health and delivery risk"]:["Executive pulse","Top media issues","Overdue tasks","Top business risks and decisions"];
 const [question,setQuestion]=useState(""),[busy,setBusy]=useState(false),[answer,setAnswer]=useState(""),[action,setAction]=useState<ActionProposal|null>(null),[state,setState]=useState<"idle"|"ready"|"running"|"done"|"failed">("idle"),[result,setResult]=useState("");
 async function ask(text=question){const q=text.trim();if(!q||busy)return;setQuestion(q);setBusy(true);setAnswer("");setAction(null);setState("idle");setResult("");try{const r=await fetch("/api/assistant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:q,attachments:[]}),cache:"no-store"});const d=await r.json().catch(()=>({})) as Response;if(!r.ok)throw new Error(d.error||"VIVITO request failed");setAnswer(d.answer||"VIVITO completed the request.");if(d.actionProposal){setAction(d.actionProposal);setState("ready")}}catch(e){setAnswer(e instanceof Error?e.message:"VIVITO request failed safely.")}finally{setBusy(false)}}
 async function execute(){if(!action||state==="running")return;if(action.missingFields?.length){setState("failed");setResult("Missing: "+action.missingFields.join(", "));return}setState("running");setResult("");try{const r=await fetch("/api/assistant/actions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({op:action.op,args:action.args,confirm:true,requestId:crypto.randomUUID()}),cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Action failed");setState("done");setResult(d?.result?.message||"Action completed successfully.")}catch(e){setState("failed");setResult(e instanceof Error?e.message:"Action failed safely.")}}
 return <div className="card" data-vivito-studio-console><div className="card-body" style={{display:"grid",gap:14}}><div><h2 className="card-title">Talk to VIVITO here</h2><p className="page-subtitle" style={{marginTop:5}}>These controls call the same live VIVITO assistant and governed action executor used by the floating assistant.</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{prompts.map(p=><button key={p} type="button" className="btn btn-secondary" disabled={busy} onClick={()=>ask(p)}>{p}</button>)}</div><div style={{display:"flex",gap:8,alignItems:"stretch"}}><input aria-label="Ask VIVITO" value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")ask()}} placeholder="Ask or command VIVITO…" style={{flex:1,minWidth:0}}/><button type="button" className="btn btn-primary" disabled={busy||!question.trim()} onClick={()=>ask()}>{busy?"Thinking…":"Ask VIVITO"}</button></div>{answer&&<div role="status" style={{padding:14,borderRadius:12,background:"var(--bg-tertiary)",whiteSpace:"pre-wrap"}}>{answer}</div>}{action&&<div className={`va-action risk-${action.risk}`} data-vivito-action-proposal><div className="va-action-top"><b>{action.op.replaceAll("_"," ")}</b><span>{action.risk}</span></div><div>{action.summary}</div>{action.missingFields?.length?<div className="va-action-missing">Missing: {action.missingFields.join(", ")}</div>:null}{state==="running"?<div role="status">Executing…</div>:state==="done"?<div className="va-action-ok">✓ {result}</div>:state==="failed"?<><div className="va-action-error">{result}</div><button type="button" onClick={execute}>Retry safely</button></>:<button type="button" disabled={Boolean(action.missingFields?.length)} onClick={execute}>{["high","destructive"].includes(action.risk)?"Confirm & execute":"Execute"}</button>}</div>}</div></div>
}
