import crypto from "crypto";
import {db,adPlatformConnections} from "@/lib/db";
import {eq} from "drizzle-orm";

// Meta OAuth production configuration is resolved server-side from Vercel secrets.
export type OAuthPlatform="META"|"TIKTOK"|"GOOGLE"|"SNAPCHAT"|"LINKEDIN";
type State={platform:OAuthPlatform;clientId:string;adAccountId:string;accountName:string;userId:string;exp:number};
type TokenSet={accessToken:string;refreshToken?:string;expiresIn?:number};

const base=()=>process.env.NEXTAUTH_URL||process.env.AUTH_URL||"http://localhost:3000";
const callback=(p:string)=>`${base()}/api/ad-oauth/${p.toLowerCase()}/callback`;
const secret=()=>process.env.OAUTH_ENCRYPTION_KEY||process.env.AUTH_SECRET||"";
const key=()=>crypto.createHash("sha256").update(secret()).digest();
const META_APP_ID="1009736748777817";
const META_CONFIG_ID="1591787738522063";

export function encryptToken(value?:string|null){if(!value)return null;if(!secret())throw new Error("OAUTH_ENCRYPTION_KEY is missing");const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv("aes-256-gcm",key(),iv);const encrypted=Buffer.concat([cipher.update(value,"utf8"),cipher.final()]);return [iv.toString("base64url"),cipher.getAuthTag().toString("base64url"),encrypted.toString("base64url")].join(".");}
export function decryptToken(value?:string|null){if(!value)return "";const [iv,tag,data]=value.split(".");const decipher=crypto.createDecipheriv("aes-256-gcm",key(),Buffer.from(iv,"base64url"));decipher.setAuthTag(Buffer.from(tag,"base64url"));return Buffer.concat([decipher.update(Buffer.from(data,"base64url")),decipher.final()]).toString("utf8");}
export function signState(input:Omit<State,"exp">){const payload=Buffer.from(JSON.stringify({...input,exp:Date.now()+10*60_000})).toString("base64url");const sig=crypto.createHmac("sha256",key()).update(payload).digest("base64url");return `${payload}.${sig}`;}
export function verifyState(value:string):State{const [payload,sig]=value.split(".");const expected=crypto.createHmac("sha256",key()).update(payload).digest("base64url");if(!sig||sig.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))throw new Error("Invalid OAuth state");const state=JSON.parse(Buffer.from(payload,"base64url").toString()) as State;if(state.exp<Date.now())throw new Error("OAuth request expired");return state;}

const credentials=(p:OAuthPlatform)=>{
 const prefix=p==="META"?"META":p;
 const clientId=process.env[`${prefix}_CLIENT_ID`]||process.env[`${prefix}_APP_ID`]||(p==="META"?META_APP_ID:"");
 const clientSecret=process.env[`${prefix}_CLIENT_SECRET`]||process.env[`${prefix}_APP_SECRET`]||"";
 if(!clientId||!clientSecret)throw new Error(`${p} OAuth Client ID/Secret are not configured in Vercel`);
 return{clientId,clientSecret};
};

export function oauthConfigured(p:string){try{credentials(p as OAuthPlatform);return!!secret()}catch{return false}}

export function authorizationUrl(platform:OAuthPlatform,state:string){const {clientId}=credentials(platform),redirect=callback(platform);if(platform==="META"){const configId=process.env.META_CONFIG_ID||META_CONFIG_ID;const q=new URLSearchParams({client_id:clientId,redirect_uri:redirect,state,response_type:"code",scope:"ads_read,ads_management,business_management"});if(configId)q.set("config_id",configId);return `https://www.facebook.com/${process.env.META_GRAPH_VERSION||"v23.0"}/dialog/oauth?${q.toString()}`;}if(platform==="GOOGLE")return `https://accounts.google.com/o/oauth2/v2/auth?client_id=${clientId}&redirect_uri=${encodeURIComponent(redirect)}&response_type=code&access_type=offline&prompt=consent&state=${encodeURIComponent(state)}&scope=${encodeURIComponent("https://www.googleapis.com/auth/adwords")}`;if(platform==="LINKEDIN")return `https://www.linkedin.com/oauth/v2/authorization?response_type=code&client_id=${clientId}&redirect_uri=${encodeURIComponent(redirect)}&state=${encodeURIComponent(state)}&scope=${encodeURIComponent("r_ads r_ads_reporting rw_ads")}`;if(platform==="SNAPCHAT")return `https://accounts.snapchat.com/login/oauth2/authorize?client_id=${clientId}&redirect_uri=${encodeURIComponent(redirect)}&response_type=code&scope=${encodeURIComponent("snapchat-marketing-api")}&state=${encodeURIComponent(state)}`;return `https://business-api.tiktok.com/portal/auth?app_id=${clientId}&state=${encodeURIComponent(state)}&redirect_uri=${encodeURIComponent(redirect)}`;}

async function parseResponse(r:Response){const text=await r.text();let data:any;try{data=JSON.parse(text)}catch{data=Object.fromEntries(new URLSearchParams(text))}if(!r.ok||data.error||data.code&&data.code!==0)throw new Error(data.error_description||data.error?.message||data.message||"OAuth token exchange failed");return data;}
export async function exchangeCode(platform:OAuthPlatform,code:string):Promise<TokenSet>{const {clientId,clientSecret}=credentials(platform),redirect=callback(platform);if(platform==="META"){const d=await parseResponse(await fetch(`https://graph.facebook.com/${process.env.META_GRAPH_VERSION||"v23.0"}/oauth/access_token?client_id=${clientId}&client_secret=${clientSecret}&redirect_uri=${encodeURIComponent(redirect)}&code=${encodeURIComponent(code)}`));return{accessToken:d.access_token,expiresIn:d.expires_in};}if(platform==="TIKTOK"){const d=await parseResponse(await fetch("https://business-api.tiktok.com/open_api/v1.3/oauth2/access_token/",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({app_id:clientId,secret:clientSecret,auth_code:code})}));const t=d.data||d;return{accessToken:t.access_token,refreshToken:t.refresh_token,expiresIn:t.expires_in};}const tokenUrl=platform==="GOOGLE"?"https://oauth2.googleapis.com/token":platform==="LINKEDIN"?"https://www.linkedin.com/oauth/v2/accessToken":"https://accounts.snapchat.com/login/oauth2/access_token";const body=new URLSearchParams({grant_type:"authorization_code",code,redirect_uri:redirect,client_id:clientId,client_secret:clientSecret});const d=await parseResponse(await fetch(tokenUrl,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body}));return{accessToken:d.access_token,refreshToken:d.refresh_token,expiresIn:d.expires_in};}

async function refresh(platform:OAuthPlatform,refreshToken:string):Promise<TokenSet>{const {clientId,clientSecret}=credentials(platform);if(platform==="TIKTOK"){const d=await parseResponse(await fetch("https://business-api.tiktok.com/open_api/v1.3/oauth2/refresh_token/",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({app_id:clientId,secret:clientSecret,grant_type:"refresh_token",refresh_token:refreshToken})}));const t=d.data||d;return{accessToken:t.access_token,refreshToken:t.refresh_token||refreshToken,expiresIn:t.expires_in};}const tokenUrl=platform==="GOOGLE"?"https://oauth2.googleapis.com/token":platform==="LINKEDIN"?"https://www.linkedin.com/oauth/v2/accessToken":"https://accounts.snapchat.com/login/oauth2/access_token";const d=await parseResponse(await fetch(tokenUrl,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"refresh_token",refresh_token:refreshToken,client_id:clientId,client_secret:clientSecret})}));return{accessToken:d.access_token,refreshToken:d.refresh_token||refreshToken,expiresIn:d.expires_in};}

export async function connectionAccessToken(connection:any){if(!connection?.accessTokenEncrypted)return"";const exp=connection.tokenExpiresAt?new Date(connection.tokenExpiresAt).getTime():0;if(!exp||exp>Date.now()+5*60_000)return decryptToken(connection.accessTokenEncrypted);const refreshToken=decryptToken(connection.refreshTokenEncrypted);if(!refreshToken)return decryptToken(connection.accessTokenEncrypted);const next=await refresh(connection.platform as OAuthPlatform,refreshToken);await db.update(adPlatformConnections).set({accessTokenEncrypted:encryptToken(next.accessToken),refreshTokenEncrypted:encryptToken(next.refreshToken||refreshToken),tokenExpiresAt:next.expiresIn?new Date(Date.now()+next.expiresIn*1000):null,status:"CONNECTED",syncError:null,updatedAt:new Date()} as any).where(eq(adPlatformConnections.id,connection.id));return next.accessToken;}
