import {db,sql} from "@/lib/db";

export type LifecycleAction="archive"|"restore"|"delete"|"restore_deleted";
export type LifecycleSpec={entity:string;table:string;labelColumn:string;ownerColumn?:string;roles:string[];statusColumn?:string;deleteAllowedStatuses?:string[];deleteBlockedMessage?:string;activeColumn?:string;category:string};

// User-managed business records only. Audit/security/telemetry/payment/payroll history
// is intentionally excluded from user lifecycle controls to preserve evidence and accounting integrity.
export const BUSINESS_LIFECYCLE_SPECS:LifecycleSpec[]=[
 {entity:"file",table:"file_documents",labelColumn:"name",ownerColumn:"uploaded_by",roles:["SUPER_ADMIN","ACCOUNT_MANAGER","CREATOR","MEDIA_BUYER"],category:"Files"},
 {entity:"media_plan",table:"media_plans",labelColumn:"name",ownerColumn:"submitted_by",roles:["SUPER_ADMIN","ACCOUNT_MANAGER","MEDIA_BUYER"],category:"Media Plans"},
 {entity:"calendar_event",table:"calendar_events",labelColumn:"title",ownerColumn:"created_by",roles:["SUPER_ADMIN","ACCOUNT_MANAGER"],category:"Calendar"},
 {entity:"leave_request",table:"leave_requests",labelColumn:"type",ownerColumn:"user_id",roles:["SUPER_ADMIN","HR"],statusColumn:"status",deleteAllowedStatuses:["PENDING","REJECTED"],deleteBlockedMessage:"Approved leave history cannot be deleted.",category:"HR"},
 {entity:"asset",table:"assets",labelColumn:"name",ownerColumn:"created_by",roles:["SUPER_ADMIN","HR"],activeColumn:"is_active",category:"Assets"},
 {entity:"vendor",table:"vendors",labelColumn:"name",ownerColumn:"created_by",roles:["SUPER_ADMIN","ACCOUNTANT"],activeColumn:"is_active",category:"Vendors"},
 {entity:"purchase_order",table:"purchase_orders",labelColumn:"po_number",ownerColumn:"created_by",roles:["SUPER_ADMIN","ACCOUNTANT"],statusColumn:"status",deleteAllowedStatuses:["PENDING","CANCELLED","DRAFT"],deleteBlockedMessage:"Approved or paid purchase orders are immutable; archive them instead.",category:"Finance"},
 {entity:"time_entry",table:"time_entries",labelColumn:"description",ownerColumn:"user_id",roles:["SUPER_ADMIN","HR"],category:"Time Entries"},
 {entity:"expense_claim",table:"expense_claims",labelColumn:"description",ownerColumn:"user_id",roles:["SUPER_ADMIN","ACCOUNTANT"],statusColumn:"status",deleteAllowedStatuses:["PENDING","REJECTED"],deleteBlockedMessage:"Approved or paid expense claims are immutable; archive them instead.",category:"Expenses"},
 {entity:"project_budget",table:"project_budgets",labelColumn:"name",ownerColumn:"created_by",roles:["SUPER_ADMIN","ACCOUNTANT","ACCOUNT_MANAGER"],category:"Budgets"},
 {entity:"proposal",table:"proposals",labelColumn:"title",ownerColumn:"created_by",roles:["SUPER_ADMIN","SALES","ACCOUNT_MANAGER"],statusColumn:"status",deleteAllowedStatuses:["DRAFT","REJECTED"],deleteBlockedMessage:"Sent or accepted proposals are business history; archive them instead.",category:"Sales"},
 {entity:"service_item",table:"service_catalog",labelColumn:"name",ownerColumn:"created_by",roles:["SUPER_ADMIN","ACCOUNTANT"],activeColumn:"is_active",category:"Service Catalog"},
 {entity:"workflow_rule",table:"workflow_rules",labelColumn:"name",ownerColumn:"created_by",roles:["SUPER_ADMIN"],activeColumn:"is_active",category:"Automation"},
 {entity:"email_campaign",table:"email_campaigns",labelColumn:"name",ownerColumn:"created_by",roles:["SUPER_ADMIN","ACCOUNT_MANAGER"],statusColumn:"status",deleteAllowedStatuses:["DRAFT"],deleteBlockedMessage:"Scheduled or sent email campaigns are communication history; archive them instead.",category:"Email Campaigns"},
 {entity:"workspace_role",table:"workspace_roles",labelColumn:"name",ownerColumn:"created_by",roles:["SUPER_ADMIN","HR"],category:"Roles"},
 {entity:"knowledge_article",table:"knowledge_base",labelColumn:"title",ownerColumn:"author_id",roles:["SUPER_ADMIN","HR","ACCOUNT_MANAGER"],activeColumn:"is_published",category:"Knowledge Base"},
 {entity:"follow_up",table:"follow_up_reminders",labelColumn:"notes",ownerColumn:"user_id",roles:["SUPER_ADMIN","SALES"],category:"Sales Follow-ups"},
 {entity:"finance_record",table:"finance_records",labelColumn:"invoice_number",ownerColumn:"created_by",roles:["SUPER_ADMIN","ACCOUNTANT"],statusColumn:"invoice_status",deleteAllowedStatuses:["DRAFT","CANCELLED"],deleteBlockedMessage:"Sent, paid or overdue invoice history cannot be deleted; archive it instead.",category:"Finance Records"},
 {entity:"company_expense",table:"company_expenses",labelColumn:"description",ownerColumn:"created_by",roles:["SUPER_ADMIN","ACCOUNTANT"],category:"Company Expenses"},
 {entity:"contract",table:"contracts",labelColumn:"title",ownerColumn:"created_by",roles:["SUPER_ADMIN","ACCOUNT_MANAGER","ACCOUNTANT"],statusColumn:"status",deleteAllowedStatuses:["DRAFT","CANCELLED","EXPIRED"],deleteBlockedMessage:"Active or signed contracts are immutable; archive them instead.",category:"Contracts"},
 {entity:"chart_account",table:"chart_of_accounts",labelColumn:"name",ownerColumn:"created_by",roles:["SUPER_ADMIN","ACCOUNTANT"],activeColumn:"is_active",category:"Chart of Accounts"},
 {entity:"journal_entry",table:"journal_entries",labelColumn:"description",ownerColumn:"created_by_id",roles:["SUPER_ADMIN","ACCOUNTANT"],statusColumn:"status",deleteAllowedStatuses:["DRAFT"],deleteBlockedMessage:"Posted journal entries cannot be deleted; use the accounting void workflow.",category:"Journal Entries"},
 {entity:"contact",table:"contacts",labelColumn:"name",ownerColumn:"created_by",roles:["SUPER_ADMIN","ACCOUNT_MANAGER"],category:"Contacts"},
];

const byEntity=new Map(BUSINESS_LIFECYCLE_SPECS.map(s=>[s.entity,s]));
export const businessLifecycleSpec=(entity:string)=>byEntity.get(entity);
const ident=(value:string)=>sql.raw(`"${value.replaceAll('"','')}"`);

export type GenericLifecycleRow={id:string;name:string;owner_id?:string|null;archived_by?:string|null;archived_at?:unknown;deleted_at?:unknown;status?:string|null;entity?:string;category?:string};
export async function loadBusinessRecord(spec:LifecycleSpec,id:string,workspaceId:string):Promise<GenericLifecycleRow|null>{const owner=spec.ownerColumn?ident(spec.ownerColumn):sql.raw("null"),status=spec.statusColumn?ident(spec.statusColumn):sql.raw("null");const result=Array.from(await db.execute(sql`select id,coalesce(${ident(spec.labelColumn)}::text,'Untitled') name,${owner}::text owner_id,archived_by,archived_at,deleted_at,${status}::text status from ${ident(spec.table)} where id=${id} and workspace_id=${workspaceId} limit 1`)) as GenericLifecycleRow[];return result[0]||null}
export function canManageBusinessRecord(spec:LifecycleSpec,row:GenericLifecycleRow,userId:string,roles:string[]){return roles.includes("SUPER_ADMIN")||row.owner_id===userId||roles.some(r=>spec.roles.includes(r))}
export function assertBusinessDeleteAllowed(spec:LifecycleSpec,row:GenericLifecycleRow){if(spec.deleteAllowedStatuses?.length&&!spec.deleteAllowedStatuses.includes(String(row.status||"")))throw new Error(spec.deleteBlockedMessage||"This record cannot be deleted in its current state.")}
export async function listManageableBusinessRecords(workspaceId:string,userId:string,roles:string[]):Promise<GenericLifecycleRow[]>{const result:GenericLifecycleRow[]=[];for(const spec of BUSINESS_LIFECYCLE_SPECS){const moduleAccess=roles.includes("SUPER_ADMIN")||spec.roles.some(r=>roles.includes(r));if(!moduleAccess&&!spec.ownerColumn)continue;const owner=spec.ownerColumn?ident(spec.ownerColumn):sql.raw("null"),status=spec.statusColumn?ident(spec.statusColumn):sql.raw("null"),access=moduleAccess?sql`true`:spec.ownerColumn?sql`${ident(spec.ownerColumn)}=${userId}`:sql`false`;const records=Array.from(await db.execute(sql`select id,coalesce(${ident(spec.labelColumn)}::text,'Untitled') name,${owner}::text owner_id,${status}::text status from ${ident(spec.table)} where workspace_id=${workspaceId} and archived_at is null and deleted_at is null and ${access} order by id desc limit 100`)) as GenericLifecycleRow[];for(const record of records)result.push({...record,entity:spec.entity,category:spec.category})}return result}
export async function mutateBusinessRecord(spec:LifecycleSpec,id:string,workspaceId:string,userId:string,action:LifecycleAction){const table=ident(spec.table),active=spec.activeColumn?ident(spec.activeColumn):null;if(action==="archive"){if(active)await db.execute(sql`update ${table} set archived_at=now(),archived_by=${userId},${active}=false where id=${id} and workspace_id=${workspaceId} and deleted_at is null`);else await db.execute(sql`update ${table} set archived_at=now(),archived_by=${userId} where id=${id} and workspace_id=${workspaceId} and deleted_at is null`)}else if(action==="restore"){if(active)await db.execute(sql`update ${table} set archived_at=null,archived_by=null,${active}=true where id=${id} and workspace_id=${workspaceId} and deleted_at is null`);else await db.execute(sql`update ${table} set archived_at=null,archived_by=null where id=${id} and workspace_id=${workspaceId} and deleted_at is null`)}else if(action==="delete"){if(active)await db.execute(sql`update ${table} set deleted_at=now(),deleted_by=${userId},archived_at=null,archived_by=null,${active}=false where id=${id} and workspace_id=${workspaceId} and deleted_at is null`);else await db.execute(sql`update ${table} set deleted_at=now(),deleted_by=${userId},archived_at=null,archived_by=null where id=${id} and workspace_id=${workspaceId} and deleted_at is null`)}else{if(active)await db.execute(sql`update ${table} set deleted_at=null,deleted_by=null,${active}=true where id=${id} and workspace_id=${workspaceId} and deleted_at is not null`);else await db.execute(sql`update ${table} set deleted_at=null,deleted_by=null where id=${id} and workspace_id=${workspaceId} and deleted_at is not null`)}}
