export const TASK_TEMPLATES = [
  {
    id: "reel_standard",
    name: "🎬 Standard Reel",
    type: "REEL",
    priority: "HIGH",
    daysToDeadline: 5,
    brief: `Create an engaging short-form video reel for social media.\n\nContent Requirements:\n- Duration: 30-60 seconds\n- Format: Vertical 9:16\n- Hook in first 3 seconds\n- Clear CTA at the end\n\nDeliverables:\n- Final edited reel (MP4, 1080x1920)\n- Thumbnail option\n- Subtitle/caption version`,
    tov: "Energetic, on-brand, engaging. Use trending audio where appropriate.",
  },
  {
    id: "graphic_post",
    name: "🎨 Social Graphic",
    type: "GRAPHIC",
    priority: "MEDIUM",
    daysToDeadline: 3,
    brief: `Design a static graphic post for social media.\n\nRequirements:\n- Square format (1:1) and Story format (9:16)\n- Brand colors only (see palette)\n- Clear headline + supporting text\n- Logo placement bottom right\n\nDeliverables:\n- PNG exports (feed + story versions)\n- Editable source file`,
    tov: "Professional, clean, visually impactful.",
  },
  {
    id: "carousel_edu",
    name: "📊 Educational Carousel",
    type: "CAROUSEL",
    priority: "MEDIUM",
    daysToDeadline: 4,
    brief: `Create an informative carousel post (5-8 slides).\n\nStructure:\n- Slide 1: Hook / Problem statement\n- Slides 2-6: Key points (one per slide)\n- Last slide: CTA + contact info\n\nRequirements:\n- Consistent design across all slides\n- Easy-to-read fonts\n- Brand colors throughout`,
    tov: "Educational, trustworthy, clear. Break down complex info simply.",
  },
  {
    id: "ugc_testimonial",
    name: "👤 UGC Testimonial",
    type: "UGC",
    priority: "HIGH",
    daysToDeadline: 7,
    brief: `Produce a user-generated content style testimonial video.\n\nStyle: Authentic, raw, casual — NOT corporate\nFormat: Vertical, talking head or lifestyle B-roll\nDuration: 45-90 seconds\n\nScript outline:\n1. Relatable problem/situation\n2. Discovery of the brand\n3. Experience + specific results\n4. Recommendation + CTA\n\nDeliverables:\n- Raw + edited version\n- Subtitled version`,
    tov: "Authentic, conversational, relatable. Like a friend recommending something.",
  },
  {
    id: "motion_graphic",
    name: "✨ Motion Graphic Ad",
    type: "MOTION_GRAPHIC",
    priority: "URGENT",
    daysToDeadline: 6,
    brief: `Create an animated motion graphic for paid advertising.\n\nRequirements:\n- Duration: 15 seconds + 30 seconds version\n- Must work without sound (add subtitles)\n- Clear brand elements throughout\n- Strong visual hook in first 2 seconds\n- CTA in last 3 seconds\n\nDeliverables:\n- MP4 exports (15s + 30s)\n- Multiple aspect ratios: 1:1, 9:16, 16:9`,
    tov: "Dynamic, attention-grabbing, professional.",
  },
  {
    id: "story_promo",
    name: "📱 Story Promotion",
    type: "STORY",
    priority: "HIGH",
    daysToDeadline: 2,
    brief: `Design a promotional Story for social media.\n\nRequirements:\n- Vertical format 9:16\n- Eye-catching design\n- Interactive element (poll, swipe up, link sticker)\n- Urgency in copy\n\nDeliverables:\n- Static version\n- Animated version (optional)`,
    tov: "Urgent, exciting, FOMO-inducing. Action-oriented language.",
  },
];
