"use client";
type Mood="calm"|"thinking"|"insight"|"warning"|"success";
export default function VivitVivito({mood="calm",message,compact=false}:{mood?:Mood;message?:string;compact?:boolean}){const label=mood==="thinking"?"Thinking":mood==="warning"?"Attention":mood==="success"?"Done":mood==="insight"?"Insight":"Ready";return <div className={`vivito-mark ${compact?"is-compact":""} mood-${mood}`} aria-live="polite" aria-label={`VIVITO: ${label}`}>{message&&<div className="vivito-bubble"><small>VIVITO</small><span>{message}</span></div>}<div className="vivito-avatar" aria-hidden="true"><i className="vivito-orbit vivito-orbit-a"/><i className="vivito-orbit vivito-orbit-b"/><span>V</span></div>{!compact&&<div className="vivito-copy"><b>VIVITO</b><small>{label}</small></div>}<style>{CSS}</style></div>}
const CSS=`
.vivito-mark{--vivito-facebook:#1877f2;--vivito-tiktok-cyan:#25f4ee;--vivito-tiktok-red:#fe2c55;--vivito-whatsapp:#25d366;--vivito-snap:#ffd800;display:flex;align-items:center;gap:10px;color:var(--text-primary)}
.vivito-avatar{width:38px;height:38px;flex:0 0 38px;border-radius:12px;display:grid;place-items:center;position:relative;isolation:isolate;overflow:hidden;background:linear-gradient(var(--card-bg),var(--card-bg)) padding-box,conic-gradient(from 210deg,var(--vivito-facebook),var(--vivito-tiktok-cyan),var(--vivito-tiktok-red),var(--vivito-whatsapp),var(--vivito-snap),var(--vivito-facebook)) border-box;color:var(--text-primary);border:1px solid transparent;box-shadow:0 5px 16px rgba(15,23,42,.12)}
.vivito-avatar:after{content:"";position:absolute;inset:5px;border-radius:9px;background:var(--text-primary);z-index:-1}.vivito-avatar>span{position:relative;z-index:3;color:var(--card-bg);font:850 16px/1 'Sora',system-ui,sans-serif;letter-spacing:-.04em}
.vivito-orbit{position:absolute;inset:2px;border-radius:50%;pointer-events:none;z-index:2;border:1px solid rgba(255,255,255,.32)}
.vivito-orbit:after{content:"";position:absolute;width:5px;height:5px;border-radius:50%;top:-2px;left:50%;transform:translateX(-50%);box-shadow:0 0 8px currentColor;background:currentColor}
.vivito-orbit-a{color:var(--vivito-tiktok-cyan);animation:vivitoOrbitA 4.8s linear infinite}.vivito-orbit-b{inset:6px;color:var(--vivito-tiktok-red);border-color:rgba(255,255,255,.18);animation:vivitoOrbitB 3.6s linear infinite reverse}.vivito-orbit-b:after{width:4px;height:4px;top:-2px;background:var(--vivito-whatsapp);color:var(--vivito-whatsapp);box-shadow:0 0 7px currentColor}
.vivito-copy{display:flex;flex-direction:column;gap:2px;min-width:0}.vivito-copy b{font:800 12px/1.2 'Sora',system-ui,sans-serif;letter-spacing:.02em}.vivito-copy small{font-size:10px;color:var(--text-muted)}
.vivito-bubble{max-width:300px;padding:9px 11px;border-radius:12px;background:var(--card-bg);border:1px solid var(--card-border);color:var(--text-primary);box-shadow:0 8px 24px rgba(15,23,42,.08)}.vivito-bubble small{display:block;font-size:9px;font-weight:800;letter-spacing:.08em;color:var(--text-muted);margin-bottom:3px}.vivito-bubble span{display:block;font-size:12px;line-height:1.5}
.vivito-mark.is-compact{gap:0}.vivito-mark.is-compact .vivito-avatar{width:34px;height:34px;flex-basis:34px;border-radius:11px}.vivito-mark.is-compact .vivito-avatar:after{inset:5px;border-radius:8px}.vivito-mark.is-compact .vivito-avatar>span{font-size:14px}.vivito-mark.is-compact .vivito-bubble{display:none}
.mood-thinking .vivito-avatar{filter:saturate(1.12)}.mood-warning .vivito-avatar{outline:2px solid rgba(245,158,11,.25)}.mood-success .vivito-avatar{outline:2px solid rgba(34,197,94,.22)}
@keyframes vivitoOrbitA{to{transform:rotate(360deg)}}@keyframes vivitoOrbitB{to{transform:rotate(360deg)}}
@media(prefers-reduced-motion:no-preference){.mood-thinking .vivito-avatar{animation:vivitoPulse 1.4s ease-in-out infinite}@keyframes vivitoPulse{50%{opacity:.82}}}
@media(prefers-reduced-motion:reduce){.vivito-orbit-a,.vivito-orbit-b,.mood-thinking .vivito-avatar{animation:none!important}}
`;
