export const dynamic="force-dynamic";
import {NextRequest,NextResponse} from "next/server";
import {auth} from "@/lib/auth";
import {db,sql} from "@/lib/db";

const WORKSPACE="default",ar=(s:string)=>/[\u0600-\u06ff]/.test(s),n=(v:any)=>Number(v||0),cairoDay=(d:Date)=>new Intl.DateTimeFormat("en-CA",{timeZone:"Africa/Cairo",year:"numeric",month:"2-digit",day:"2-digit"}).format(d),dateLabel=(d:Date,arabic:boolean)=>new Intl.DateTimeFormat(arabic?"ar-EG":"en-GB",{timeZone:"Africa/Cairo",day:"2-digit",month:"short",year:"numeric"}).format(d);
const ANTHROPIC_URL="https://api.anthropic.com/v1/messages";
async function callClaude(prompt:string,system:string){if(!process.env.ANTHROPIC_API_KEY)throw new Error("AI provider is not configured");const r=await fetch(ANTHROPIC_URL,{method:"POST",headers:{"Content-Type":"application/json","x-api-key":process.env.ANTHROPIC_API_KEY,"anthropic-version":"2023-06-01"},body:JSON.stringify({model:"claude-sonnet-4-20250514",max_tokens:2200,system,messages:[{role:"user",content:prompt}]})}),d=await r.json();if(!r.ok)throw new Error(d?.error?.message||"AI request failed");return d.content?.[0]?.text||""}
async function callGemini(prompt:string,system:string){if(!process.env.GEMINI_API_KEY)throw new Error("AI provider is not configured");const model=process.env.GEMINI_MODEL||"gemini-2.0-flash",r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${process.env.GEMINI_API_KEY}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({systemInstruction:{parts:[{text:system}]},contents:[{role:"user",parts:[{text:prompt}]}],generationConfig:{temperature:.45,maxOutputTokens:2200}})}),d=await r.json();if(!r.ok)throw new Error(d?.error?.message||"AI request failed");return d?.candidates?.[0]?.content?.parts?.map((p:any)=>p.text).join("\n")||""}
async function generate(prompt:string,system:string){if(process.env.GEMINI_API_KEY)return callGemini(prompt,system);if(process.env.ANTHROPIC_API_KEY)return callClaude(prompt,system);throw new Error("AI provider is not configured")}

async function clientScope(role:string,userId:string){if(role==="SUPER_ADMIN"){const rows:any=await db.execute(sql`select id,company_name from clients where workspace_id=${WORKSPACE} and is_active=true order by company_name`);return [...rows]}if(role==="ACCOUNT_MANAGER"){const rows:any=await db.execute(sql`select id,company_name from clients where workspace_id=${WORKSPACE} and is_active=true and account_manager_id=${userId} order by company_name`);return [...rows]}if(role==="MEDIA_BUYER"){const rows:any=await db.execute(sql`select id,company_name from clients where workspace_id=${WORKSPACE} and is_active=true and media_buyer_id=${userId} order by company_name`);return [...rows]}if(role==="CLIENT"){const rows:any=await db.execute(sql`select id,company_name from clients where workspace_id=${WORKSPACE} and is_active=true and user_id=${userId} limit 1`);return [...rows]}return[]}
async function taskContext(role:string,userId:string,clientIds:string[]){let rows:any;if(role==="CREATOR")rows=await db.execute(sql`select t.id,t.title,t.status,t.priority,t.deadline,t.client_id,c.company_name from creative_tasks t join clients c on c.id=t.client_id where t.workspace_id=${WORKSPACE} and t.archived_at is null and c.is_active=true and t.assigned_to_id=${userId} and t.status not in ('COMPLETED','REJECTED') order by t.deadline asc limit 120`);else if(clientIds.length)rows=await db.execute(sql`select t.id,t.title,t.status,t.priority,t.deadline,t.client_id,c.company_name from creative_tasks t join clients c on c.id=t.client_id where t.workspace_id=${WORKSPACE} and t.archived_at is null and c.is_active=true and t.client_id in (${sql.join(clientIds.map(id=>sql`${id}`),sql`,`)}) and t.status not in ('COMPLETED','REJECTED') order by t.deadline asc limit 120`);else rows=[];return [...rows]}
function taskAnswer(question:string,tasks:any[]){const arabic=ar(question),q=question.toLowerCase(),today=cairoDay(new Date()),todayTasks=tasks.filter(t=>cairoDay(new Date(t.deadline))===today),overdue=tasks.filter(t=>new Date(t.deadline).getTime()<Date.now()&&cairoDay(new Date(t.deadline))!==today),pending=tasks.filter(t=>t.status==="PENDING"),review=tasks.filter(t=>["REVIEW","APPROVED","REVISION"].includes(String(t.status))),soon=[...tasks].filter(t=>new Date(t.deadline)>=new Date()).sort((a,b)=>+new Date(a.deadline)-+new Date(b.deadline)).slice(0,10),line=(t:any)=>`• ${t.title} — ${t.company_name||"Client"} — ${dateLabel(new Date(t.deadline),arabic)} — ${String(t.status).replace(/_/g," ")}`;if(/today|النهارده|اليوم|انهاردة|انهارده/.test(q))return todayTasks.length?(arabic?`تاسكات النهارده (${todayTasks.length}):\n${todayTasks.map(line).join("\n")}`:`Tasks due today (${todayTasks.length}):\n${todayTasks.map(line).join("\n")}`):(arabic?"مفيش تاسكات ديدلاينها النهارده.":"No tasks are due today.");if(/overdue|late|متأخر|متاخر|فات/.test(q))return overdue.length?(arabic?`التاسكات المتأخرة (${overdue.length}):\n${overdue.slice(0,12).map(line).join("\n")}`:`Overdue tasks (${overdue.length}):\n${overdue.slice(0,12).map(line).join("\n")}`):(arabic?"مفيش تاسكات متأخرة حاليًا.":"There are no overdue tasks right now.");if(/review|approve|approval|ريفيو|مراجعة|موافق/.test(q))return review.length?(arabic?`الموجود في الـReview / Approval (${review.length}):\n${review.slice(0,12).map(line).join("\n")}`:`Review / approval queue (${review.length}):\n${review.slice(0,12).map(line).join("\n")}`):(arabic?"مفيش حاجة في الـReview حاليًا.":"Nothing is currently in review.");if(/pending|معلق|بندنج|انتظار/.test(q))return pending.length?(arabic?`Pending (${pending.length}):\n${pending.slice(0,12).map(line).join("\n")}`:`Pending (${pending.length}):\n${pending.slice(0,12).map(line).join("\n")}`):(arabic?"مفيش Pending tasks.":"There are no pending tasks.");return tasks.length?(arabic?`عندك ${tasks.length} تاسك نشطة. أقرب الديدلاينز:\n${soon.map(line).join("\n")}`:`You have ${tasks.length} active tasks. Nearest deadlines:\n${soon.map(line).join("\n")}`):(arabic?"مفيش تاسكات نشطة حاليًا.":"There are no active tasks right now.")}

export async function POST(req:NextRequest){const session=await auth();if(!session?.user)return NextResponse.json({error:"Unauthorized"},{status:401});const body=await req.json().catch(()=>({})),question=String(body.question||"").trim().slice(0,1200);if(!question)return NextResponse.json({error:"Ask a question first."},{status:400});const role=String((session.user as any).role||""),userId=String((session.user as any).id||""),clients=await clientScope(role,userId),clientIds=clients.map((c:any)=>String(c.id)),tasks=await taskContext(role,userId,clientIds);
 if(role==="CLIENT")return NextResponse.json({answer:taskAnswer(question,tasks),sources:["ERP · Creative Tasks · your client account"],mode:"tasks"},{headers:{"Cache-Control":"private, no-store"}});
 if(!["SUPER_ADMIN","ACCOUNT_MANAGER","MEDIA_BUYER","CREATOR"].includes(role))return NextResponse.json({answer:taskAnswer(question,tasks),sources:["ERP · Creative Tasks"],mode:"tasks"});
 let media:any[]=[],billing:any[]=[],clientSummary:any[]=clients;if(role==="SUPER_ADMIN"||role==="ACCOUNT_MANAGER"||role==="MEDIA_BUYER"){if(clientIds.length){const mr:any=await db.execute(sql`select c.company_name,ac.name campaign,ac.status,ac.reported_result_label,coalesce(sum(p.spend),0) spend,coalesce(sum(p.results),0) results,coalesce(sum(p.add_to_cart),0) atc,coalesce(sum(p.purchases),0) purchases,coalesce(sum(p.revenue),0) revenue,coalesce(sum(p.impressions),0) impressions,coalesce(sum(p.clicks),0) clicks from ad_campaigns ac join clients c on c.id=ac.client_id left join ad_performance_daily p on p.campaign_id=ac.id and p.date>=date_trunc('month',now()) and p.breakdown_type='TOTAL' and p.ad_set_id is null and p.ad_id is null where ac.archived_at is null and ac.client_id in (${sql.join(clientIds.map(id=>sql`${id}`),sql`,`)}) group by c.company_name,ac.id,ac.name,ac.status,ac.reported_result_label order by spend desc limit 80`);media=[...mr];const br:any=await db.execute(sql`select c.company_name,p.agreed_amount,p.paid_amount,p.outstanding,p.cycle_day,p.status from client_payment_profiles p join clients c on c.id=p.client_id where p.client_id in (${sql.join(clientIds.map(id=>sql`${id}`),sql`,`)}) order by p.outstanding desc`);billing=[...br]}}
 const overdue=tasks.filter(t=>new Date(t.deadline).getTime()<Date.now()),mediaSpend=media.reduce((s,x)=>s+n(x.spend),0),messages=media.filter(x=>String(x.reported_result_label||"").toLowerCase().includes("messag")).reduce((s,x)=>s+n(x.results),0),atc=media.reduce((s,x)=>s+n(x.atc),0),purchases=media.reduce((s,x)=>s+n(x.purchases),0),outstanding=billing.reduce((s,x)=>s+n(x.outstanding),0),context={role,activeClients:clientSummary.length,activeTasks:tasks.length,overdueTasks:overdue.length,mediaSpendMTD:mediaSpend,messagesMTD:messages,addToCartMTD:atc,purchasesMTD:purchases,outstandingEGP:outstanding,topTasks:tasks.slice(0,20),campaigns:media.slice(0,30),billing:billing.slice(0,20)};
 const system=`You are VIVIT ERP's senior marketing and operations advisor. Role: ${role}. You are expert in marketing strategy, positioning, customer research, content strategy, copywriting, art direction, graphic design critique, video editing direction, social media, Meta/TikTok/Google media buying, funnel optimization, reporting, agency operations and task management.\n\nFor questions about VIVIT, clients, campaigns, tasks or money: use ONLY the supplied ERP LIVE CONTEXT. Never invent a metric. Give concrete recommendations with numbers where the context supports them.\nFor general marketing questions: answer from established professional marketing knowledge. Do not pretend it is live web research.\nAlways separate evidence from advice. End operational/data answers with a short 'Sources used' section naming the ERP modules actually used (Creative Tasks, Media Campaigns, Client Billing). For general knowledge answers say 'Source basis: professional marketing knowledge; not live web research.'\nIf the user writes Arabic, answer Egyptian Arabic with clear English marketing terms where useful. Be concise, senior, practical and decisive.`;
 const prompt=`QUESTION:\n${question}\n\nERP LIVE CONTEXT (current access scope):\n${JSON.stringify(context)}`;try{const answer=await generate(prompt,system);return NextResponse.json({answer,sources:["ERP · Creative Tasks","ERP · Media Campaigns / Daily Performance","ERP · Client Billing"],mode:"advisor"},{headers:{"Cache-Control":"private, no-store"}})}catch(e:any){const taskLike=/task|deadline|overdue|pending|review|تاسك|ديدلاين|متأخر|مراجعة|ريفيو/i.test(question);return NextResponse.json({answer:taskLike?taskAnswer(question,tasks):`AI advisor is temporarily unavailable. Live ERP snapshot: ${clientSummary.length} active clients, ${tasks.length} active tasks (${overdue.length} overdue), media spend MTD ${Math.round(mediaSpend).toLocaleString("en-EG")} EGP, ${messages} messages, ${atc} ATC, ${purchases} purchases, and ${Math.round(outstanding).toLocaleString("en-EG")} EGP outstanding.`,sources:["ERP · Creative Tasks","ERP · Media Campaigns / Daily Performance","ERP · Client Billing"],mode:"fallback"},{status:200})}}
