export const dynamic="force-dynamic";
import {NextRequest,NextResponse} from "next/server";
import {auth} from "@/lib/auth";
import {db,financeRecords,clients,contacts,workspaces,auditLogs,paymentRecords,sql} from "@/lib/db";
import {eq,and} from "drizzle-orm";
import {canAccessClient} from "@/lib/client-access";

const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]||c));
const MONTHS=["","January","February","March","April","May","June","July","August","September","October","November","December"];
const money=(value:number,currency:string)=>{try{return new Intl.NumberFormat("en",{style:"currency",currency,maximumFractionDigits:2}).format(value)}catch{return `${value.toFixed(2)} ${currency}`}};
const wantsHtml=(req:NextRequest)=>String(req.headers.get("accept")||"").includes("text/html");
const uiRedirect=(req:NextRequest,id:string,msg:string,error=false)=>{const u=new URL(`/api/invoice/${id}`,req.url);u.searchParams.set(error?"error":"message",msg);return NextResponse.redirect(u,303)};

async function loadInvoice(id:string,workspaceId:string){
 const [record]=await db.select().from(financeRecords).where(and(eq(financeRecords.id,id),eq(financeRecords.workspaceId,workspaceId))).limit(1);
 if(!record)return null;
 const [[client],[contact],[workspace]]=await Promise.all([
  db.select().from(clients).where(and(eq(clients.id,record.clientId),eq(clients.workspaceId,workspaceId))).limit(1),
  db.select().from(contacts).where(and(eq(contacts.clientId,record.clientId),eq(contacts.isPrimary,true))).limit(1),
  db.select({currency:workspaces.currency,agencyFeePercent:workspaces.agencyFeePercent}).from(workspaces).where(eq(workspaces.id,workspaceId)).limit(1),
 ]);
 if(!client)return null;
 const currency=client.currency||workspace?.currency||"EGP";
 return {record,client,contact,workspace,currency};
}

export async function GET(req:NextRequest,context:{params:Promise<{id:string}>}){
 const session=await auth();if(!session?.user)return wantsHtml(req)?NextResponse.redirect(new URL("/login",req.url)):NextResponse.json({error:"Unauthorized"},{status:401});
 const workspaceId=String(session.user.workspaceId||"");if(!workspaceId)return NextResponse.json({error:"Workspace unavailable"},{status:403});
 const {id}=await context.params,data=await loadInvoice(id,workspaceId);if(!data)return NextResponse.json({error:"Not found"},{status:404});
 if(!(await canAccessClient(session,data.record.clientId,{finance:true})))return NextResponse.json({error:"Forbidden"},{status:403});
 const {record,client,contact,workspace,currency}=data,items=[{desc:"Monthly Retainer",amount:Number(record.retainer||0)},...(Number(record.mediaBuyingFee||0)>0?[{desc:`Media Buying Management Fee (${Number(workspace?.agencyFeePercent??20)}%)`,amount:Number(record.mediaBuyingFee)}]:[]),...(Number(record.extraServices||0)>0?[{desc:"Additional Services",amount:Number(record.extraServices)}]:[])];
 const invoiceData={invoiceNumber:record.invoiceNumber??`INV-${record.year}-${String(record.month).padStart(2,"0")}-${client.companyName.slice(0,3).toUpperCase()}`,date:new Date(record.createdAt||Date.now()).toLocaleDateString("en-GB",{day:"2-digit",month:"long",year:"numeric"}),dueDate:record.dueDate?new Date(record.dueDate).toLocaleDateString("en-GB",{day:"2-digit",month:"long",year:"numeric"}):"Upon receipt",period:`${MONTHS[record.month]} ${record.year}`,currency,client:{name:client.companyName,contact:contact?.name??"",email:contact?.email??""},items,subtotal:Number(record.totalRevenue||0),paid:Number(record.paid||0),outstanding:Number(record.outstanding||0),status:record.invoiceStatus,paymentMethod:record.paymentMethod||null,paidDate:record.paidDate||null,notes:record.notes??""};
 if(!wantsHtml(req))return NextResponse.json(invoiceData,{headers:{"Cache-Control":"private, no-store"}});
 const role=String(session.user.role||""),canApprove=role==="SUPER_ADMIN"&&record.invoiceStatus==="DRAFT",canCollect=["SUPER_ADMIN","ACCOUNTANT"].includes(role)&&["SENT","OVERDUE"].includes(String(record.invoiceStatus))&&Number(record.outstanding)>0,msg=req.nextUrl.searchParams.get("message"),error=req.nextUrl.searchParams.get("error");
 const rows=items.map(x=>`<tr><td>${esc(x.desc)}</td><td>${esc(money(x.amount,currency))}</td></tr>`).join("");
 const approve=canApprove?`<form method="post" action="/api/invoice/${esc(id)}?ui=1&action=approve"><button class="primary">Approve & Send</button></form>`:"";
 const collect=canCollect?`<form class="pay" method="post" action="/api/invoice/${esc(id)}?ui=1&action=payment"><label>Payment amount<input name="amount" type="number" min="0.01" max="${esc(Number(record.outstanding).toFixed(2))}" step="0.01" value="${esc(Number(record.outstanding).toFixed(2))}" required></label><label>Method<select name="method"><option value="bank">Bank</option><option value="cash">Cash</option></select></label><button class="primary">Record payment</button></form>`:"";
 const html=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(invoiceData.invoiceNumber)}</title><style>body{font-family:Arial,sans-serif;background:#f5f7fb;color:#172033;margin:0;padding:24px}.sheet{max-width:900px;margin:auto;background:white;border:1px solid #dde3ed;border-radius:18px;padding:28px;box-shadow:0 14px 50px #16213a12}.head{display:flex;justify-content:space-between;gap:18px;flex-wrap:wrap}.muted{color:#64748b}.status{display:inline-block;padding:6px 10px;border-radius:99px;background:#eef2ff;font-weight:700}table{width:100%;border-collapse:collapse;margin:24px 0}td,th{text-align:left;padding:12px;border-bottom:1px solid #e7ebf2}td:last-child,th:last-child{text-align:right}.totals{margin-left:auto;max-width:360px}.totals div{display:flex;justify-content:space-between;padding:7px 0}.actions{display:grid;gap:12px;margin-top:24px;padding-top:20px;border-top:1px solid #e7ebf2}.pay{display:grid;grid-template-columns:1fr 180px auto;gap:10px;align-items:end}.pay label{display:grid;gap:6px;font-size:12px;font-weight:700}input,select,button{font:inherit;padding:10px 12px;border:1px solid #cbd5e1;border-radius:9px}.primary{background:#153a70;color:white;border:0;font-weight:800;cursor:pointer}.flash{padding:10px 12px;border-radius:10px;margin:12px 0;background:#ecfdf5;color:#166534}.flash.err{background:#fef2f2;color:#991b1b}@media(max-width:700px){.pay{grid-template-columns:1fr}.sheet{padding:18px}body{padding:10px}}@media print{body{background:white;padding:0}.sheet{box-shadow:none;border:0}.actions,.flash{display:none}}</style></head><body><main class="sheet">${msg?`<div class="flash">${esc(msg)}</div>`:""}${error?`<div class="flash err">${esc(error)}</div>`:""}<div class="head"><div><div class="muted">VIVIT ERP · Invoice</div><h1>${esc(invoiceData.invoiceNumber)}</h1><div class="status">${esc(record.invoiceStatus)}</div></div><div><b>${esc(client.companyName)}</b><div class="muted">${esc(contact?.name||"")}</div><div class="muted">${esc(contact?.email||"")}</div></div></div><p class="muted">Period ${esc(invoiceData.period)} · Issued ${esc(invoiceData.date)} · Due ${esc(invoiceData.dueDate)} · Currency ${esc(currency)}</p><table><thead><tr><th>Description</th><th>Amount</th></tr></thead><tbody>${rows}</tbody></table><div class="totals"><div><span>Total</span><b>${esc(money(invoiceData.subtotal,currency))}</b></div><div><span>Paid</span><b>${esc(money(invoiceData.paid,currency))}</b></div><div><span>Outstanding</span><b>${esc(money(invoiceData.outstanding,currency))}</b></div></div><div class="actions">${approve}${collect}<button onclick="window.print()">Print / Save PDF</button><a href="/dashboard/finance">← Back to Finance</a></div></main></body></html>`;
 return new NextResponse(html,{status:200,headers:{"Content-Type":"text/html; charset=utf-8","Cache-Control":"private, no-store","X-Content-Type-Options":"nosniff","X-Frame-Options":"DENY"}});
}

export async function POST(req:NextRequest,context:{params:Promise<{id:string}>}){
 const session=await auth();if(!session?.user)return NextResponse.json({error:"Unauthorized"},{status:401});
 const workspaceId=String(session.user.workspaceId||""),userId=String(session.user.id||""),role=String(session.user.role||"");if(!workspaceId||!userId)return NextResponse.json({error:"Workspace unavailable"},{status:403});
 const {id}=await context.params,action=req.nextUrl.searchParams.get("action")||"approve",ui=req.nextUrl.searchParams.get("ui")==="1";
 try{
  if(action==="approve"){
   if(role!=="SUPER_ADMIN")throw new Error("Only Super Admin can approve and send invoices");
   const result=await db.transaction(async tx=>{await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${`invoice-approval:${workspaceId}:${id}`}))`);const [record]=await tx.select().from(financeRecords).where(and(eq(financeRecords.id,id),eq(financeRecords.workspaceId,workspaceId))).limit(1);if(!record)throw new Error("Invoice not found");if(record.invoiceStatus!=="DRAFT")throw new Error("Only draft invoices can be approved and sent");const [updated]=await tx.update(financeRecords).set({invoiceStatus:"SENT",updatedAt:new Date()}).where(and(eq(financeRecords.id,id),eq(financeRecords.workspaceId,workspaceId),eq(financeRecords.invoiceStatus,"DRAFT"))).returning({id:financeRecords.id});if(!updated)throw new Error("Invoice changed concurrently");await tx.insert(auditLogs).values({workspaceId,userId,action:"invoice_approved_sent",entity:"finance_records",entityId:id,oldValues:JSON.stringify({status:"DRAFT"}),newValues:JSON.stringify({status:"SENT"})});return updated;});
   return ui?uiRedirect(req,id,"Invoice approved and sent."):NextResponse.json({success:true,id:result.id,status:"SENT"},{headers:{"Cache-Control":"private, no-store"}});
  }
  if(action==="payment"){
   if(!["SUPER_ADMIN","ACCOUNTANT"].includes(role))throw new Error("Only Finance users can record payments");
   const form=await req.formData(),amount=Number(form.get("amount")),method=String(form.get("method")||"bank").toLowerCase();if(!Number.isFinite(amount)||amount<=0)throw new Error("Payment amount must be greater than zero");if(!["bank","cash"].includes(method))throw new Error("Unsupported payment method");
   const result=await db.transaction(async tx=>{await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${`invoice-payment:${workspaceId}:${id}`}))`);const [record]=await tx.select().from(financeRecords).where(and(eq(financeRecords.id,id),eq(financeRecords.workspaceId,workspaceId))).limit(1);if(!record)throw new Error("Invoice not found");if(!["SENT","OVERDUE"].includes(String(record.invoiceStatus)))throw new Error("Only sent or overdue invoices can receive payments");const [client]=await tx.select({id:clients.id,currency:clients.currency,isActive:clients.isActive}).from(clients).where(and(eq(clients.id,record.clientId),eq(clients.workspaceId,workspaceId))).limit(1);if(!client?.isActive)throw new Error("Inactive clients cannot receive new collections");const currentPaid=Number(record.paid||0),total=Number(record.totalRevenue||0),remaining=Math.max(0,total-currentPaid);if(amount>remaining+0.005)throw new Error("Payment exceeds the outstanding balance");const now=new Date(),nextPaid=Number((currentPaid+amount).toFixed(2)),nextOutstanding=Math.max(0,Number((total-nextPaid).toFixed(2))),nextStatus=nextOutstanding<=0.005?"PAID":record.dueDate&&new Date(record.dueDate)<now?"OVERDUE":"SENT";await tx.insert(paymentRecords).values({workspaceId,invoiceId:record.id,clientId:record.clientId,amount:Number(amount.toFixed(2)),currency:client.currency||"EGP",method,status:"COMPLETED",paidAt:now});await tx.update(financeRecords).set({paid:nextPaid,outstanding:nextOutstanding,invoiceStatus:nextStatus,paidDate:nextStatus==="PAID"?now:null,paymentMethod:method,updatedAt:now}).where(and(eq(financeRecords.id,id),eq(financeRecords.workspaceId,workspaceId)));await tx.insert(auditLogs).values({workspaceId,userId,action:nextStatus==="PAID"?"invoice_paid":"invoice_partial_payment",entity:"finance_records",entityId:id,oldValues:JSON.stringify({paid:record.paid,outstanding:record.outstanding,status:record.invoiceStatus}),newValues:JSON.stringify({amount:Number(amount.toFixed(2)),paid:nextPaid,outstanding:nextOutstanding,status:nextStatus,method,currency:client.currency})});return{nextPaid,nextOutstanding,nextStatus};});
   return ui?uiRedirect(req,id,result.nextStatus==="PAID"?"Invoice paid in full.":`Partial payment recorded. Remaining ${result.nextOutstanding.toFixed(2)}.`):NextResponse.json({success:true,...result},{headers:{"Cache-Control":"private, no-store"}});
  }
  throw new Error("Unsupported invoice action");
 }catch(error){const message=error instanceof Error?error.message:"Invoice action failed";return ui?uiRedirect(req,id,message,true):NextResponse.json({error:message},{status:/Forbidden|Only/.test(message)?403:400,headers:{"Cache-Control":"private, no-store"}})}
}