export const dynamic="force-dynamic";
import {NextRequest,NextResponse} from "next/server";
import {auth} from "@/lib/auth";
import {db,financeRecords,clients,contacts,workspaces,auditLogs} from "@/lib/db";
import {eq,and} from "drizzle-orm";
import {canAccessClient} from "@/lib/client-access";

export async function GET(req:NextRequest,context:{params:Promise<{id:string}>}){const session=await auth();if(!session?.user)return NextResponse.json({error:"Unauthorized"},{status:401});const workspaceId=String(session.user.workspaceId||"");if(!workspaceId)return NextResponse.json({error:"Workspace unavailable"},{status:403});const {id}=await context.params;const [record]=await db.select().from(financeRecords).where(and(eq(financeRecords.id,id),eq(financeRecords.workspaceId,workspaceId))).limit(1);if(!record)return NextResponse.json({error:"Not found"},{status:404});if(!(await canAccessClient(session,record.clientId,{finance:true})))return NextResponse.json({error:"Forbidden"},{status:403});const [[client],[contact],[workspace]]=await Promise.all([db.select().from(clients).where(and(eq(clients.id,record.clientId),eq(clients.workspaceId,workspaceId))).limit(1),db.select().from(contacts).where(and(eq(contacts.clientId,record.clientId),eq(contacts.isPrimary,true))).limit(1),db.select({currency:workspaces.currency,agencyFeePercent:workspaces.agencyFeePercent}).from(workspaces).where(eq(workspaces.id,workspaceId)).limit(1)]);if(!client)return NextResponse.json({error:"Client not found"},{status:404});const currency=workspace?.currency||"EGP",MONTHS=["","January","February","March","April","May","June","July","August","September","October","November","December"],invoiceData={invoiceNumber:record.invoiceNumber??`INV-${record.year}-${String(record.month).padStart(2,"0")}-${client.companyName.slice(0,3).toUpperCase()}`,date:new Date(record.createdAt||Date.now()).toLocaleDateString("en-GB",{day:"2-digit",month:"long",year:"numeric"}),dueDate:record.dueDate?new Date(record.dueDate).toLocaleDateString("en-GB",{day:"2-digit",month:"long",year:"numeric"}):"Upon receipt",period:`${MONTHS[record.month]} ${record.year}`,currency,client:{name:client.companyName,contact:contact?.name??"",email:contact?.email??""},items:[{desc:"Monthly Retainer",amount:Number(record.retainer||0)},...(Number(record.mediaBuyingFee||0)>0?[{desc:`Media Buying Management Fee (${Number(workspace?.agencyFeePercent??20)}%)`,amount:Number(record.mediaBuyingFee)}]:[]),...(Number(record.extraServices||0)>0?[{desc:"Additional Services",amount:Number(record.extraServices)}]:[])],subtotal:Number(record.totalRevenue||0),paid:Number(record.paid||0),outstanding:Number(record.outstanding||0),status:record.invoiceStatus,paymentMethod:record.paymentMethod||null,paidDate:record.paidDate||null,notes:record.notes??""};return NextResponse.json(invoiceData,{headers:{"Cache-Control":"private, no-store"}})}

export async function POST(_:NextRequest,context:{params:Promise<{id:string}>}){const session=await auth();if(!session?.user)return NextResponse.json({error:"Unauthorized"},{status:401});if(session.user.role!=="SUPER_ADMIN")return NextResponse.json({error:"Forbidden"},{status:403});const workspaceId=String(session.user.workspaceId||""),userId=String(session.user.id||"");if(!workspaceId||!userId)return NextResponse.json({error:"Workspace unavailable"},{status:403});const {id}=await context.params;const result=await db.transaction(async tx=>{const [record]=await tx.select().from(financeRecords).where(and(eq(financeRecords.id,id),eq(financeRecords.workspaceId,workspaceId))).limit(1);if(!record)return{status:404,error:"Invoice not found"};if(record.invoiceStatus!=="DRAFT")return{status:409,error:"Only draft invoices can be approved and sent"};const [updated]=await tx.update(financeRecords).set({invoiceStatus:"SENT",updatedAt:new Date()}).where(and(eq(financeRecords.id,id),eq(financeRecords.workspaceId,workspaceId),eq(financeRecords.invoiceStatus,"DRAFT"))).returning({id:financeRecords.id});if(!updated)return{status:409,error:"Invoice changed concurrently"};await tx.insert(auditLogs).values({workspaceId,userId,action:"invoice_approved_sent",entity:"finance_records",entityId:id,oldValues:JSON.stringify({status:"DRAFT"}),newValues:JSON.stringify({status:"SENT"})});return{status:200,id}});if("error" in result)return NextResponse.json({error:result.error},{status:result.status});return NextResponse.json({success:true,id:result.id,status:"SENT"},{headers:{"Cache-Control":"private, no-store"}})}