export const dynamic="force-dynamic";
import {NextRequest,NextResponse} from "next/server";
import {db,sql,notifications} from "@/lib/db";
import {buildDailyCompetitiveReport} from "@/lib/vivito/competitive-intelligence";
type DbRow=Record<string,unknown>;type CompetitiveResult={workspaceId:string;clientId:string;ok:boolean;summary?:string;error?:string;delivered?:boolean};const rows=(v:unknown):DbRow[]=>Array.from(v as Iterable<DbRow>);
const nextDue=(cadence:string)=>cadence==="DAILY"?"1 day":cadence==="EVERY_3_DAYS"?"3 days":"7 days";
const esc=(v:unknown)=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
export async function GET(req:NextRequest){
 const bearer=req.headers.get("authorization")?.replace(/^Bearer\s+/i,""),secret=req.headers.get("x-cron-secret")||bearer;if(process.env.NODE_ENV==="production"&&(!process.env.CRON_SECRET||secret!==process.env.CRON_SECRET))return NextResponse.json({error:"Unauthorized"},{status:401});
 const clients=rows(await db.execute(sql`select distinct w.workspace_id,w.client_id,c.company_name,c.account_manager_id,c.media_buyer_id,c.user_id,p.cadence,p.send_to_client,p.next_due_at from competitor_watchlists w join clients c on c.id=w.client_id and c.workspace_id=w.workspace_id left join competitive_report_preferences p on p.workspace_id=w.workspace_id and p.client_id=w.client_id where w.is_active=true and c.is_active=true`)),results:CompetitiveResult[]=[],now=new Date(),isSaturday=now.getUTCDay()===6;
 for(const c of clients){const workspaceId=String(c.workspace_id),clientId=String(c.client_id),cadence=String(c.cadence||"WEEKLY"),due=!c.next_due_at||new Date(String(c.next_due_at))<=now;try{
  const report=await buildDailyCompetitiveReport(clientId,workspaceId);
  if(!due&&!isSaturday){results.push({workspaceId,clientId,ok:true,summary:report.summary,delivered:false});continue}
  const staff=rows(await db.execute(sql`select distinct u.id,u.email,u.name,u.role from users u where u.workspace_id=${workspaceId} and u.is_active=true and u.approval_status='APPROVED' and (u.role='SUPER_ADMIN' or u.id=${String(c.account_manager_id||"")} or u.id=${String(c.media_buyer_id||"")} or (u.role='CREATOR' and exists(select 1 from creative_tasks t where t.workspace_id=${workspaceId} and t.client_id=${clientId} and t.assigned_to_id=u.id and t.archived_at is null and t.deleted_at is null)))`));const targets=[...new Set(staff.map(u=>String(u.id)).filter(Boolean))],pdfLink=`/api/competitive-intelligence/pdf?clientId=${encodeURIComponent(clientId)}`;
  const reportDate=now.toISOString().slice(0,10),deliveryCadence=isSaturday&&!due?"SATURDAY_DIGEST":cadence;
  const inserted=rows(await db.execute(sql`insert into competitive_report_deliveries(id,workspace_id,client_id,report_date,cadence,audience,status,created_at) values(${crypto.randomUUID()},${workspaceId},${clientId},${reportDate},${deliveryCadence},'INTERNAL','SENT',now()) on conflict(workspace_id,client_id,report_date,cadence,audience) do nothing returning id`));
  if(inserted.length){for(const userId of targets)await db.insert(notifications).values({userId,type:"GENERAL",priority:"normal",title:`📡 Vivito Competitive Report — ${c.company_name}`,message:`${report.summary.slice(0,1600)}\n\nOpen the branded PDF report for post links, likes, comments and views.`,link:pdfLink}).onConflictDoNothing();if(staff.length&&process.env.RESEND_API_KEY){for(const u of staff){if(!u.email)continue;await fetch("https://api.resend.com/emails",{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${process.env.RESEND_API_KEY}`},body:JSON.stringify({from:process.env.EMAIL_FROM||"VIVIT ERP <noreply@viviterp.com>",to:[u.email],subject:`Vivito Competitive Report — ${c.company_name}`,html:`<div style="font-family:Arial,sans-serif;max-width:720px;margin:auto;padding:28px;border-top:8px solid #071f40"><h2 style="color:#071f40">VIVIT Competitive Intelligence</h2><p><b>${esc(c.company_name)}</b></p><pre style="white-space:pre-wrap;font-family:Arial,sans-serif;line-height:1.55;background:#f6f7f9;padding:16px;border-radius:10px">${esc(report.summary)}</pre><p><a href="${esc(String(process.env.NEXTAUTH_URL||""))}${pdfLink}">Open branded PDF report</a></p><p style="color:#777;font-size:12px">Vivito checks public competitor sources daily. Unavailable public metrics are never invented.</p></div>`}),signal:AbortSignal.timeout(10000)}).catch(()=>{})}}}
  if(due){const interval=nextDue(cadence);await db.execute(sql`insert into competitive_report_preferences(workspace_id,client_id,cadence,send_to_client,last_sent_at,next_due_at,updated_at) values(${workspaceId},${clientId},${cadence},${Boolean(c.send_to_client)},now(),now()+${interval}::interval,now()) on conflict(workspace_id,client_id) do update set last_sent_at=now(),next_due_at=now()+${interval}::interval,updated_at=now()`)}
  if(due&&c.send_to_client&&c.user_id){const clientUser=rows(await db.execute(sql`select id,email,name from users where id=${String(c.user_id)} and workspace_id=${workspaceId} and role='CLIENT' and is_active=true and approval_status='APPROVED' limit 1`))[0];const delivery=rows(await db.execute(sql`insert into competitive_report_deliveries(id,workspace_id,client_id,report_date,cadence,audience,status,approved_by,created_at) select ${crypto.randomUUID()},${workspaceId},${clientId},${reportDate},${cadence},'CLIENT','SENT',p.approved_by,now() from competitive_report_preferences p where p.workspace_id=${workspaceId} and p.client_id=${clientId} and p.send_to_client=true and p.approved_by is not null on conflict(workspace_id,client_id,report_date,cadence,audience) do nothing returning id`));if(clientUser&&delivery.length){await db.insert(notifications).values({userId:String(clientUser.id),type:"GENERAL",priority:"normal",title:`Vivito market report — ${c.company_name}`,message:"Your latest competitor monitoring report is ready.",link:pdfLink}).onConflictDoNothing();if(clientUser.email&&process.env.RESEND_API_KEY)await fetch("https://api.resend.com/emails",{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${process.env.RESEND_API_KEY}`},body:JSON.stringify({from:process.env.EMAIL_FROM||"VIVIT ERP <noreply@viviterp.com>",to:[clientUser.email],subject:`Market monitoring report — ${c.company_name}`,html:`<div style="font-family:Arial,sans-serif;max-width:720px;margin:auto;padding:28px"><h2 style="color:#071f40">Your VIVIT market report</h2><p>The latest Vivito competitor monitoring report is ready.</p><p><a href="${esc(String(process.env.NEXTAUTH_URL||""))}${pdfLink}">Open PDF report</a></p></div>`}),signal:AbortSignal.timeout(10000)}).catch(()=>{})}}
  results.push({workspaceId,clientId,ok:true,summary:report.summary,delivered:inserted.length>0})
 }catch(e:unknown){results.push({workspaceId,clientId,ok:false,error:e instanceof Error?e.message:String(e)})}}
 return NextResponse.json({ok:true,clients:results.length,isSaturday,results},{headers:{"Cache-Control":"no-store"}})
}
