export const dynamic="force-dynamic";
import {NextRequest,NextResponse} from "next/server";
import {auth} from "@/lib/auth";
import {db,clients,financeRecords,contacts,workspaces,sql} from "@/lib/db";
import {eq,and} from "drizzle-orm";
import {canAccessClient} from "@/lib/client-access";

const MONTHS=["","January","February","March","April","May","June","July","August","September","October","November","December"];
const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
const headerSafe=(v:unknown)=>String(v??"").replace(/[\r\n]/g," ").slice(0,180);
export async function GET(req:NextRequest,context:{params:Promise<{clientId:string}>}){
 const session=await auth();if(!session?.user)return new NextResponse("Unauthorized",{status:401});const workspaceId=String(session.user.workspaceId||"");if(!workspaceId)return new NextResponse("Workspace unavailable",{status:403});const {clientId}=await context.params;if(!(await canAccessClient(session,clientId)))return new NextResponse("Forbidden",{status:403});
 const month=parseInt(req.nextUrl.searchParams.get("month")??String(new Date().getMonth()+1),10),year=parseInt(req.nextUrl.searchParams.get("year")??String(new Date().getFullYear()),10);if(!Number.isInteger(month)||month<1||month>12||!Number.isInteger(year)||year<2020||year>2100)return new NextResponse("Invalid report period",{status:400});
 const monthStart=new Date(year,month-1,1),monthEnd=new Date(year,month,0,23,59,59,999);
 const [[client],[invoice],[primaryContact],[workspace],[mAgg]]=await Promise.all([
  db.select().from(clients).where(and(eq(clients.id,clientId),eq(clients.workspaceId,workspaceId),eq(clients.isActive,true))).limit(1),
  db.select().from(financeRecords).where(and(eq(financeRecords.workspaceId,workspaceId),eq(financeRecords.clientId,clientId),eq(financeRecords.month,month),eq(financeRecords.year,year))).limit(1),
  db.select().from(contacts).where(and(eq(contacts.clientId,clientId),eq(contacts.isPrimary,true))).limit(1),
  db.select({currency:workspaces.currency}).from(workspaces).where(eq(workspaces.id,workspaceId)).limit(1),
  db.execute<{spend:number|string|null;leads:number|string|null;revenue:number|string|null}>(sql`select coalesce(sum(p.spend),0) spend,coalesce(sum(p.results),0) leads,coalesce(sum(p.revenue),0) revenue from ad_performance_daily p join ad_campaigns a on a.id=p.campaign_id where a.workspace_id=${workspaceId} and a.client_id=${clientId} and a.archived_at is null and a.deleted_at is null and p.date>=${monthStart} and p.date<=${monthEnd} and p.breakdown_type='TOTAL' and p.ad_set_id is null and p.ad_id is null`).then(r=>Array.from(r))
 ]);
 if(!client)return new NextResponse("Client not found or archived",{status:404});
 const currency=workspace?.currency||client.currency||"EGP",money=(n:unknown)=>new Intl.NumberFormat("en-EG",{style:"currency",currency,maximumFractionDigits:2}).format(Number(n||0)),spend=Number(mAgg?.spend||0),results=Number(mAgg?.leads||0),revenue=Number(mAgg?.revenue||0),roas=spend?revenue/spend:0,costPerResult=results?spend/results:0,company=esc(client.companyName),industry=esc(client.industry||"Digital Marketing"),contact=primaryContact?`${esc(primaryContact.name)}${primaryContact.email?` · ${esc(primaryContact.email)}`:""}`:"",status=esc(invoice?.invoiceStatus||"—");
 const invoiceHtml=invoice?`<section><h2>Invoice details</h2><table><tr><th>Item</th><th>Amount</th></tr><tr><td>Monthly Retainer</td><td>${money(invoice.retainer)}</td></tr>${Number(invoice.mediaBuyingFee||0)>0?`<tr><td>Media Buying Fee</td><td>${money(invoice.mediaBuyingFee)}</td></tr>`:""}${Number(invoice.extraServices||0)>0?`<tr><td>Additional Services</td><td>${money(invoice.extraServices)}</td></tr>`:""}<tr><td><b>Total</b></td><td><b>${money(invoice.totalRevenue)}</b></td></tr><tr><td>Paid</td><td>${money(invoice.paid)}</td></tr><tr><td>Outstanding</td><td>${money(invoice.outstanding)}</td></tr><tr><td>Status</td><td>${status}</td></tr></table></section>`:"";
 const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${company} — ${MONTHS[month]} ${year} Performance Report</title><style>*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;color:#172033;background:#fff}.page{max-width:900px;margin:auto}.hero{padding:34px 40px;background:#17345f;color:white}.hero h1{margin:0 0 6px;font-size:28px}.hero p{margin:4px 0;opacity:.85}.content{padding:30px 40px}.meta{display:flex;justify-content:space-between;gap:20px;border-bottom:1px solid #dfe7ef;padding-bottom:18px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:24px 0}.kpi{padding:16px;border-radius:12px;background:#f3f6f9;text-align:center}.kpi b{display:block;font-size:22px;color:#244d87}.kpi span{font-size:11px;color:#66788a;text-transform:uppercase}section{margin:24px 0}h2{font-size:15px;color:#17345f;border-bottom:1px solid #dfe7ef;padding-bottom:8px}table{width:100%;border-collapse:collapse}th,td{padding:10px 12px;border-bottom:1px solid #e7edf2;text-align:left;font-size:13px}th{background:#17345f;color:white}.note{padding:14px;border-left:4px solid #244d87;background:#f3f8fc;color:#456}.footer{padding:18px 40px;background:#f3f6f9;color:#66788a;font-size:11px;display:flex;justify-content:space-between;gap:12px}@media(max-width:700px){.grid{grid-template-columns:repeat(2,1fr)}.meta{display:block}.content,.hero,.footer{padding-left:20px;padding-right:20px}}</style></head><body><div class="page"><header class="hero"><h1>${company}</h1><p>${MONTHS[month]} ${year} — Performance Report</p><p>Generated ${esc(new Date().toLocaleDateString("en-GB"))}</p></header><main class="content"><div class="meta"><div><b>${company}</b><div>${industry}</div>${contact?`<div>${contact}</div>`:""}</div><div><b>VIVIT GROUP</b><div>Marketing Agency ERP</div></div></div><div class="grid"><div class="kpi"><b>${money(spend)}</b><span>Ad Spend</span></div><div class="kpi"><b>${results.toLocaleString()}</b><span>Results</span></div><div class="kpi"><b>${roas.toFixed(2)}×</b><span>ROAS</span></div><div class="kpi"><b>${money(revenue)}</b><span>Revenue</span></div></div>${invoiceHtml}<section><h2>Campaign performance</h2><table><tr><th>Metric</th><th>Period</th></tr><tr><td>ROAS</td><td>${roas.toFixed(2)}×</td></tr><tr><td>Cost / Result</td><td>${results?money(costPerResult):"—"}</td></tr><tr><td>Total Results</td><td>${results.toLocaleString()}</td></tr></table></section><div class="note"><b>Reporting note</b><div>Performance is calculated from connected media data for the selected reporting period.</div></div></main><footer class="footer"><span>VIVIT GROUP · Confidential</span><span>Generated by Vivit ERP</span></footer></div></body></html>`;
 return new NextResponse(html,{headers:{"Content-Type":"text/html; charset=utf-8","X-Frame-Options":"SAMEORIGIN","Cache-Control":"private, no-store","Content-Security-Policy":"default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'; frame-ancestors 'self'","X-Content-Type-Options":"nosniff","Referrer-Policy":"no-referrer","X-Report-Client":headerSafe(client.companyName),"X-Report-Period":`${MONTHS[month]} ${year}`}});
}
