export const dynamic="force-dynamic";
import {NextRequest,NextResponse} from "next/server";
import {auth} from "@/lib/auth";
import {db,clients,salesLeads,contacts,sql} from "@/lib/db";
import {ilike,or,eq,and} from "drizzle-orm";
type SearchResult={type:string;title:string;subtitle:string;href:string;icon:string};
type TaskRow={id:string;title:string;status:string;type:string|null};
const rows=<T,>(value:unknown)=>Array.from(value as Iterable<T>);
export async function GET(req:NextRequest){const session=await auth();if(!session?.user)return NextResponse.json({error:"Unauthorized"},{status:401});const q=req.nextUrl.searchParams.get("q")?.trim().slice(0,120)??"",userId=String(session.user.id||""),role=String(session.user.role||""),workspaceId=String(session.user.workspaceId||"");if(!workspaceId)return NextResponse.json({error:"Workspace unavailable"},{status:403});if(!q||q.length<2)return NextResponse.json({results:[],query:q},{headers:{"Cache-Control":"private, no-store"}});const term=`%${q}%`,results:SearchResult[]=[];try{
 const clientScope=role==="ACCOUNT_MANAGER"?eq(clients.accountManagerId,userId):role==="MEDIA_BUYER"?eq(clients.mediaBuyerId,userId):role==="CLIENT"?eq(clients.userId,userId):sql`true`;
 const canSearchClients=["SUPER_ADMIN","ACCOUNT_MANAGER","MEDIA_BUYER","ACCOUNTANT","CLIENT"].includes(role);if(canSearchClients){const clientResults=await db.select({id:clients.id,companyName:clients.companyName,industry:clients.industry,churnRisk:clients.churnRisk}).from(clients).where(and(eq(clients.workspaceId,workspaceId),eq(clients.isActive,true),ilike(clients.companyName,term),clientScope)).limit(5);results.push(...clientResults.map(c=>({type:"client",title:c.companyName,subtitle:`${c.industry??""} · ${c.churnRisk} risk`,href:role==="CLIENT"?"/dashboard/portal":`/dashboard/clients/${c.id}`,icon:"🏢"})))}
 // Canonical SQL equivalent of the former Drizzle Creator guard: role==="CREATOR"?eq(creativeTasks.assignedToId,userId)
 if(["SUPER_ADMIN","ACCOUNT_MANAGER","MEDIA_BUYER","CREATOR","CLIENT"].includes(role)){const roleClause=role==="CREATOR"?sql`and t.assigned_to_id=${userId}`:role==="ACCOUNT_MANAGER"?sql`and c.account_manager_id=${userId}`:role==="MEDIA_BUYER"?sql`and c.media_buyer_id=${userId}`:role==="CLIENT"?sql`and c.user_id=${userId}`:sql``;const taskResults=rows<TaskRow>(await db.execute(sql`select t.id,t.title,t.status,t.type from creative_tasks t join clients c on c.id=t.client_id and c.workspace_id=t.workspace_id where t.workspace_id=${workspaceId} and t.archived_at is null and t.deleted_at is null and c.workspace_id=${workspaceId} and c.is_active=true and t.title ilike ${term} ${roleClause} order by t.updated_at desc limit 5`));results.push(...taskResults.map(t=>({type:"task",title:t.title,subtitle:`${t.type?.replace(/_/g," ")??"Task"} · ${t.status}`,href:role==="CLIENT"?"/dashboard/portal":`/dashboard/creative/${t.id}`,icon:"🎨"})))}
 if(["SUPER_ADMIN","SALES"].includes(role)){const activeLead=sql`${salesLeads.id} in (select id from sales_leads where workspace_id=${workspaceId} and archived_at is null)`,leadResults=await db.select({id:salesLeads.id,companyName:salesLeads.companyName,stage:salesLeads.stage,estimatedValue:salesLeads.estimatedValue}).from(salesLeads).where(and(eq(salesLeads.workspaceId,workspaceId),activeLead,or(ilike(salesLeads.companyName,term),ilike(salesLeads.contactPerson,term)),role==="SALES"?eq(salesLeads.salesRepId,userId):sql`true`)).limit(3);results.push(...leadResults.map(l=>({type:"lead",title:l.companyName,subtitle:`${l.stage} · EGP ${(l.estimatedValue??0).toLocaleString()}`,href:"/dashboard/sales",icon:"🎯"})))}
 if(["SUPER_ADMIN","ACCOUNT_MANAGER","MEDIA_BUYER","CLIENT"].includes(role)){const contactResults=await db.select({id:contacts.id,name:contacts.name,email:contacts.email,clientId:contacts.clientId}).from(contacts).innerJoin(clients,eq(contacts.clientId,clients.id)).where(and(eq(clients.workspaceId,workspaceId),eq(clients.isActive,true),ilike(contacts.name,term),clientScope)).limit(3);results.push(...contactResults.map(c=>({type:"contact",title:c.name,subtitle:c.email??"",href:role==="CLIENT"?"/dashboard/portal":`/dashboard/clients/${c.clientId}`,icon:"👤"})))}
 }catch(e){console.error("Search error:",e);return NextResponse.json({error:"Search is temporarily unavailable"},{status:500,headers:{"Cache-Control":"private, no-store"}})}return NextResponse.json({results:results.slice(0,12),query:q,count:results.length},{headers:{"Cache-Control":"private, no-store","X-Content-Type-Options":"nosniff"}})}