export const dynamic="force-dynamic";
import {NextRequest,NextResponse} from "next/server";
import {auth} from "@/lib/auth";
import {db,clients,creativeTasks,salesLeads,contacts,sql} from "@/lib/db";
import {ilike,or,eq,and} from "drizzle-orm";

const WORKSPACE="default";
export async function GET(req:NextRequest){const session=await auth();if(!session?.user)return NextResponse.json({error:"Unauthorized"},{status:401});const q=req.nextUrl.searchParams.get("q")?.trim()??"",userId=String((session.user as any).id||""),role=String((session.user as any).role||"");if(!q||q.length<2)return NextResponse.json({results:[],query:q});const term=`%${q}%`,results:any[]=[];try{
 const canSearchClients=["SUPER_ADMIN","ACCOUNT_MANAGER","MEDIA_BUYER","SALES","ACCOUNTANT"].includes(role);if(canSearchClients){const clientResults=await db.select({id:clients.id,companyName:clients.companyName,industry:clients.industry,churnRisk:clients.churnRisk}).from(clients).where(and(eq(clients.workspaceId,WORKSPACE),eq(clients.isActive,true),ilike(clients.companyName,term),role==="ACCOUNT_MANAGER"?eq(clients.accountManagerId,userId):role==="MEDIA_BUYER"?eq(clients.mediaBuyerId,userId):sql`true`)).limit(5);results.push(...clientResults.map(c=>({type:"client",title:c.companyName,subtitle:`${c.industry??""} · ${c.churnRisk} risk`,href:`/dashboard/clients/${c.id}`,icon:"🏢"})))}
 if(["SUPER_ADMIN","ACCOUNT_MANAGER","CREATOR"].includes(role)){const activeTask=sql`${creativeTasks.id} in (select t.id from creative_tasks t join clients c on c.id=t.client_id where t.archived_at is null and c.workspace_id=${WORKSPACE} and c.is_active=true)`,taskWhere=and(activeTask,ilike(creativeTasks.title,term),role==="CREATOR"?eq(creativeTasks.assignedToId,userId):role==="ACCOUNT_MANAGER"?eq(clients.accountManagerId,userId):sql`true`),taskBase=db.select({id:creativeTasks.id,title:creativeTasks.title,status:creativeTasks.status,type:creativeTasks.type}).from(creativeTasks).innerJoin(clients,eq(creativeTasks.clientId,clients.id)),taskResults=await taskBase.where(taskWhere).limit(5);results.push(...taskResults.map(t=>({type:"task",title:t.title,subtitle:`${t.type?.replace(/_/g," ")} · ${t.status}`,href:`/dashboard/creative/${t.id}`,icon:"🎨"})))}
 if(["SUPER_ADMIN","SALES"].includes(role)){const activeLead=sql`${salesLeads.id} in (select id from sales_leads where archived_at is null)`,leadResults=await db.select({id:salesLeads.id,companyName:salesLeads.companyName,stage:salesLeads.stage,estimatedValue:salesLeads.estimatedValue}).from(salesLeads).where(and(eq(salesLeads.workspaceId,WORKSPACE),activeLead,or(ilike(salesLeads.companyName,term),ilike(salesLeads.contactPerson,term)),role==="SALES"?eq(salesLeads.salesRepId,userId):sql`true`)).limit(3);results.push(...leadResults.map(l=>({type:"lead",title:l.companyName,subtitle:`${l.stage} · EGP ${(l.estimatedValue??0).toLocaleString()}`,href:"/dashboard/sales",icon:"🎯"})))}
 if(["SUPER_ADMIN","ACCOUNT_MANAGER","MEDIA_BUYER"].includes(role)){const contactResults=await db.select({id:contacts.id,name:contacts.name,email:contacts.email,clientId:contacts.clientId}).from(contacts).innerJoin(clients,eq(contacts.clientId,clients.id)).where(and(eq(clients.workspaceId,WORKSPACE),eq(clients.isActive,true),ilike(contacts.name,term),role==="ACCOUNT_MANAGER"?eq(clients.accountManagerId,userId):role==="MEDIA_BUYER"?eq(clients.mediaBuyerId,userId):sql`true`)).limit(3);results.push(...contactResults.map(c=>({type:"contact",title:c.name,subtitle:c.email??"",href:`/dashboard/clients/${c.clientId}`,icon:"👤"})))}
 }catch(e){console.error("Search error:",e);return NextResponse.json({error:"Search is temporarily unavailable"},{status:500})}return NextResponse.json({results:results.slice(0,12),query:q,count:results.length},{headers:{"Cache-Control":"private, no-store"}})}
