"use client";
import {signIn} from "next-auth/react";import {useEffect,useState} from "react";import Image from "next/image";import Link from "next/link";import VivitFahd from "@/components/experience/VivitFahd";
const scenes=[
 ["The Hunt Begins","Move with clarity. Lead with speed."],["VIVIT Gate","Enter your operating system."],["Follow the Fahd","Your next move is already in sight."],["Desert Dawn","A new day. One clear command center."],["Night Predator","See what others miss."],["Fahd Trail","Every signal leads somewhere."],["Speed Entry","From signal to action, fast."],["The Watcher","Nothing important goes unseen."],["Portal Jump","Step into the live business."],["Executive Calm","Clarity without the noise."]
] as const;
export default function LoginPage(){const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[scene,setScene]=useState(0);
 useEffect(()=>{const last=Number(sessionStorage.getItem("vivit-login-scene")||"-1");let next=Math.floor(Math.random()*scenes.length);if(next===last)next=(next+1)%scenes.length;sessionStorage.setItem("vivit-login-scene",String(next));setScene(next)},[]);
 const login=async(e?:React.FormEvent)=>{e?.preventDefault();if(!email||!password)return;setLoading(true);setError("");const res=await signIn("credentials",{email,password,redirect:false});if(res?.error){setError("Invalid credentials. Try again.");setLoading(false)}else window.location.href="/apps"};const s=scenes[scene];
 return <main className={`vivit-login scene-${scene}`}>
  <section className="vivit-login-world"><div className="vivit-login-orbit orbit-a"/><div className="vivit-login-orbit orbit-b"/><div className="vivit-login-grain"/><div className="vivit-login-brand"><div className="vivit-login-logo"><Image src="/vivit-logo.png" alt="VIVIT" width={180} height={120} priority style={{objectFit:"contain"}}/></div><p className="vivit-login-kicker">VIVIT OPERATING EXPERIENCE</p><h1>{s[0]}</h1><p className="vivit-login-line">{s[1]}</p><div className="vivit-login-pulse"><span>LIVE BUSINESS</span><i/><span>AI GUIDED</span><i/><span>ONE SYSTEM</span></div></div><VivitFahd mood={loading?"thinking":error?"warning":"calm"} message={loading?"Opening your command center…":error?"That key did not open the gate.":undefined}/></section>
  <section className="vivit-login-panel"><div className="vivit-login-form"><p className="vivit-login-eyebrow">SECURE ACCESS</p><h2>Welcome back.</h2><p className="vivit-login-sub">Enter VIVIT and pick up exactly where the business is moving.</p><form onSubmit={login}>{error&&<div className="vivit-login-error">{error}</div>}<label>Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="you@vivitgroup.com" autoComplete="email"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required placeholder="••••••••" autoComplete="current-password"/></label><div className="vivit-login-meta"><Link href="/forgot-password">Forgot password?</Link></div><button disabled={loading}>{loading?"Entering VIVIT…":"Enter VIVIT"}<span>→</span></button></form><p className="vivit-login-request">Need access? <Link href="/signup">Request an account</Link></p><div className="vivit-login-security"><span>●</span> Protected workspace · role-based access · audited actions</div></div></section>
 </main>}
