// @ts-nocheck
export const dynamic="force-dynamic";
import {auth} from "@/lib/auth";
import {redirect} from "next/navigation";
import {db,clients,creativeTasks,calendarEvents,mediaMetrics,financeRecords,fileDocuments,notifications,auditLogs,sql} from "@/lib/db";
import {eq,and,gte,desc,sum,inArray} from "drizzle-orm";
import Link from "next/link";

const WORKSPACE="default";
function isVideo(url:string,type:string){return ["REEL","VIDEO_EDIT","MOTION_GRAPHIC"].includes(type)||/\.(mp4|webm|mov)(\?|$)/i.test(url)}
function validLogo(value:string){const raw=value.trim();if(!raw)return null;if(raw.startsWith("data:image/"))return raw;try{const u=new URL(raw);return ["https:","http:"].includes(u.protocol)?u.toString():null}catch{return null}}

async function portalAction(fd:FormData){"use server";const session=await auth();if(!session?.user||(session.user as any).role!=="CLIENT")throw new Error("Unauthorized");const userId=String((session.user as any).id),action=String(fd.get("action")||"");const [client]=await db.select().from(clients).where(and(eq(clients.workspaceId,WORKSPACE),eq(clients.userId,userId),eq(clients.isActive,true))).limit(1);if(!client)throw new Error("Client not found");
 if(action==="task_review"){const taskId=String(fd.get("taskId")||"").trim(),decision=String(fd.get("decision")||""),comment=String(fd.get("comment")||"").trim().slice(0,1000);if(!taskId||!["APPROVED","REVISION"].includes(decision))throw new Error("Invalid review request");const activeTask=sql`${creativeTasks.id} in (select id from creative_tasks where workspace_id=${WORKSPACE} and archived_at is null)`;const [task]=await db.select().from(creativeTasks).where(and(eq(creativeTasks.id,taskId),eq(creativeTasks.workspaceId,WORKSPACE),eq(creativeTasks.clientId,client.id),inArray(creativeTasks.status,["APPROVED","COMPLETED"]),activeTask)).limit(1);if(!task)throw new Error("Creative is not available for client review");const now=new Date();if(decision==="APPROVED"){await db.update(creativeTasks).set({approvedByClient:true,clientApprovalAt:now,revisionNotes:null,updatedAt:now}).where(and(eq(creativeTasks.id,task.id),eq(creativeTasks.workspaceId,WORKSPACE),activeTask));const existing=await db.select({id:calendarEvents.id}).from(calendarEvents).where(and(eq(calendarEvents.taskId,task.id),eq(calendarEvents.clientId,client.id))).limit(1);if(!existing.length)await db.insert(calendarEvents).values({clientId:client.id,taskId:task.id,title:task.title,date:task.deadline||now,platform:task.platform||"instagram",caption:task.caption||null,status:"approved"})}else{if(!comment)throw new Error("Please add revision notes");await db.update(creativeTasks).set({approvedByClient:false,status:"REVISION",revisionNotes:comment,revisionCount:(task.revisionCount||0)+1,updatedAt:now}).where(and(eq(creativeTasks.id,task.id),eq(creativeTasks.workspaceId,WORKSPACE),activeTask))}if(task.assignedToId)await db.insert(notifications).values({userId:task.assignedToId,type:"CLIENT_REVIEW",title:`Client ${decision.toLowerCase()}: ${task.title}`,message:decision==="APPROVED"?"Client approved the creative and it was added to the calendar.":comment,link:`/dashboard/creative/${task.id}`,priority:decision==="REVISION"?"high":"normal"});await db.insert(auditLogs).values({workspaceId:WORKSPACE,userId,action:`client_creative_${decision.toLowerCase()}`,entity:"creative_tasks",entityId:task.id,newValues:JSON.stringify({comment})} as any)}
 else if(action==="logo"){const raw=String(fd.get("logo")||"").slice(0,1200),logo=validLogo(raw);if(raw.trim()&&!logo)throw new Error("Logo must be a valid http(s) or image data URL");await db.update(clients).set({logo,updatedAt:new Date()}).where(and(eq(clients.id,client.id),eq(clients.workspaceId,WORKSPACE),eq(clients.isActive,true)))}else throw new Error("Invalid action");const {revalidatePath}=await import("next/cache");revalidatePath("/dashboard/portal");revalidatePath("/dashboard/calendar")}

export default async function PortalPage(){const session=await auth();if(!session?.user)redirect("/login");if((session.user as any).role!=="CLIENT")redirect("/dashboard");const userId=String((session.user as any).id),[client]=await db.select().from(clients).where(and(eq(clients.workspaceId,WORKSPACE),eq(clients.userId,userId),eq(clients.isActive,true))).limit(1);if(!client)return <div className="card"><div className="card-body" style={{padding:48,textAlign:"center"}}><h1 className="page-title">Client Portal</h1><p className="page-subtitle">No active client workspace is linked to this account.</p></div></div>;
 const now=new Date(),monthStart=new Date(now.getFullYear(),now.getMonth(),1),activeTaskOnly=sql`${creativeTasks.id} in (select id from creative_tasks where workspace_id=${WORKSPACE} and archived_at is null)`,activeFileOnly=sql`${fileDocuments.id} in (select id from file_documents where workspace_id=${WORKSPACE} and archived_at is null)`,activeCalendarTask=sql`(${calendarEvents.taskId} is null or ${calendarEvents.taskId} in (select id from creative_tasks where workspace_id=${WORKSPACE} and archived_at is null))`;
 const [metrics,creatives,calendar,docs,invoice,allCreative]=await Promise.all([
  db.select({spend:sum(mediaMetrics.adSpend),leads:sum(mediaMetrics.leads),revenue:sum(mediaMetrics.revenue),impressions:sum(mediaMetrics.impressions),clicks:sum(mediaMetrics.clicks)}).from(mediaMetrics).where(and(eq(mediaMetrics.workspaceId,WORKSPACE),eq(mediaMetrics.clientId,client.id),gte(mediaMetrics.date,monthStart))),
  db.select({id:creativeTasks.id,title:creativeTasks.title,type:creativeTasks.type,fileUrl:creativeTasks.fileUrl,caption:creativeTasks.caption,deadline:creativeTasks.deadline,platform:creativeTasks.platform,approvedByClient:creativeTasks.approvedByClient,status:creativeTasks.status}).from(creativeTasks).where(and(eq(creativeTasks.workspaceId,WORKSPACE),eq(creativeTasks.clientId,client.id),inArray(creativeTasks.status,["APPROVED","COMPLETED"]),activeTaskOnly)).orderBy(desc(creativeTasks.updatedAt)).limit(30),
  db.select({id:calendarEvents.id,title:calendarEvents.title,date:calendarEvents.date,platform:calendarEvents.platform,caption:calendarEvents.caption,status:calendarEvents.status}).from(calendarEvents).where(and(eq(calendarEvents.clientId,client.id),gte(calendarEvents.date,new Date(now.getFullYear(),now.getMonth()-1,1)),activeCalendarTask)).orderBy(calendarEvents.date).limit(30),
  db.select({id:fileDocuments.id,name:fileDocuments.name,category:fileDocuments.category,createdAt:fileDocuments.createdAt}).from(fileDocuments).where(and(eq(fileDocuments.workspaceId,WORKSPACE),eq(fileDocuments.clientId,client.id),activeFileOnly)).orderBy(desc(fileDocuments.createdAt)).limit(20),
  db.select({id:financeRecords.id,total:financeRecords.totalRevenue,paid:financeRecords.paid,outstanding:financeRecords.outstanding,status:financeRecords.invoiceStatus,dueDate:financeRecords.dueDate,invoiceNumber:financeRecords.invoiceNumber}).from(financeRecords).where(and(eq(financeRecords.workspaceId,WORKSPACE),eq(financeRecords.clientId,client.id))).orderBy(desc(financeRecords.year),desc(financeRecords.month)).limit(1),
  db.select({type:creativeTasks.type,status:creativeTasks.status}).from(creativeTasks).where(and(eq(creativeTasks.workspaceId,WORKSPACE),eq(creativeTasks.clientId,client.id),activeTaskOnly))
 ]);
 const m=metrics[0]||{},spend=Number(m.spend||0),leads=Number(m.leads||0),revenue=Number(m.revenue||0),roas=spend?revenue/spend:0,cpl=leads?spend/leads:0,currency=client.currency||"EGP",fmt=(n:number)=>{try{return new Intl.NumberFormat("en-EG",{style:"currency",currency,maximumFractionDigits:0}).format(n)}catch{return `${Math.round(n).toLocaleString()} ${currency}`}};
 const countType=(types:string[])=>{const x=allCreative.filter(t=>types.includes(t.type));return {total:x.length,done:x.filter(t=>["APPROVED","COMPLETED"].includes(t.status)).length}},reels=countType(["REEL","VIDEO_EDIT","MOTION_GRAPHIC"]),statics=countType(["GRAPHIC","STORY"]),carousels=countType(["CAROUSEL"]),inv=invoice[0],due=inv?.dueDate?new Date(inv.dueDate):null,days=due?Math.ceil((due.getTime()-now.getTime())/86400000):999,unpaid=inv&&Number(inv.outstanding||0)>0&&inv.status!=="PAID",showUpcoming=unpaid&&days<=5&&days>=0,showOverdue=unpaid&&days<=-7,plans=docs.filter(d=>/CONTENT|PLAN/i.test(d.category)),strategies=docs.filter(d=>/STRATEG/i.test(d.category)),realCreatives=creatives.filter(c=>c.fileUrl);
 return <div style={{maxWidth:1180,margin:"0 auto",display:"flex",flexDirection:"column",gap:20}}><style>{`.portal-hero{background:linear-gradient(135deg,#241934,#7C3AED 45%,#C52A31);border-radius:24px;padding:26px;color:#fff;display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap;box-shadow:0 22px 55px rgba(72,30,90,.22)}.portal-logo{width:76px;height:76px;border-radius:22px;background:#fff;display:grid;place-items:center;overflow:hidden}.portal-logo img{width:100%;height:100%;object-fit:contain}.metric-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.deliver-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.creative-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(230px,1fr));gap:18px}.ig-card{background:var(--card-bg);border:1px solid var(--card-border);border-radius:18px;overflow:hidden}.ig-media{aspect-ratio:4/5;background:#0b1020;overflow:hidden}.ig-media img,.ig-media video{width:100%;height:100%;object-fit:cover}.notice{position:sticky;top:82px;z-index:20;border-radius:16px;padding:14px 16px;font-weight:700}.portal-empty{padding:24px;border:1px dashed var(--card-border);border-radius:14px;color:var(--text-muted);text-align:center}@media(max-width:800px){.metric-grid{grid-template-columns:repeat(2,1fr)}.deliver-grid{grid-template-columns:1fr}.creative-grid{grid-template-columns:1fr 1fr}}@media(max-width:520px){.creative-grid,.metric-grid{grid-template-columns:1fr}.portal-hero{padding:18px}}`}</style>
 {showOverdue&&<div className="notice" style={{background:"#7f1d1d",color:"#fff"}}>Payment is more than 7 days overdue. This notice stays visible until payment is confirmed.</div>}{showUpcoming&&!showOverdue&&<div className="notice" style={{background:"#fef3c7",color:"#92400e"}}>Payment reminder: your next payment is due in {days} day{days===1?"":"s"}.</div>}
 <section className="portal-hero"><div style={{display:"flex",alignItems:"center",gap:16}}><div className="portal-logo">{client.logo?<img src={client.logo} alt={client.companyName}/>:<b style={{color:"#7C3AED",fontSize:26}}>{client.companyName.slice(0,2).toUpperCase()}</b>}</div><div><p style={{fontSize:12,opacity:.75}}>Welcome back</p><h1 style={{fontSize:28,margin:"3px 0"}}>{client.companyName}</h1><p style={{fontSize:12,opacity:.75}}>{client.industry||"Client Portal"}</p></div></div><form action={portalAction} style={{display:"flex",gap:6,flexWrap:"wrap"}}><input type="hidden" name="action" value="logo"/><input name="logo" defaultValue={client.logo||""} placeholder="Logo image URL" style={{height:38,borderRadius:10,border:"1px solid rgba(255,255,255,.35)",padding:"0 10px",background:"rgba(255,255,255,.12)",color:"#fff"}}/><button className="btn btn-secondary btn-sm">Save logo</button></form></section>
 <section className="metric-grid">{[{l:"Ad Spend",v:fmt(spend)},{l:"Leads",v:leads.toLocaleString()},{l:"ROAS",v:`${roas.toFixed(2)}x`},{l:"CPL",v:cpl?fmt(cpl):"—"}].map(x=><div className="card" key={x.l}><div className="card-body"><p style={{fontSize:11,color:"var(--text-muted)",fontWeight:800,textTransform:"uppercase"}}>{x.l}</p><b style={{fontSize:23}}>{x.v}</b></div></div>)}</section>
 <section className="deliver-grid">{[{l:"Reels / Video",x:reels,icon:"🎬"},{l:"Statics",x:statics,icon:"🖼️"},{l:"Carousels",x:carousels,icon:"📚"}].map(d=><div className="card" key={d.l}><div className="card-body" style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><p style={{fontSize:12,color:"var(--text-muted)"}}>{d.l}</p><b style={{fontSize:25}}>{d.x.done} / {d.x.total}</b><p style={{fontSize:11,color:"var(--text-muted)"}}>delivered / assigned</p></div><span style={{fontSize:30}}>{d.icon}</span></div></div>)}</section>
 <section className="card"><div className="card-header"><div><p className="card-title">Content Plan & Strategy</p><p style={{fontSize:12,color:"var(--text-muted)"}}>Documents uploaded for your account</p></div><Link href="/dashboard/files" className="btn btn-ghost btn-sm" style={{textDecoration:"none"}}>Open files →</Link></div><div className="card-body" style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:12}}><div><b>Content Plans</b>{plans.length?plans.map(x=><p key={x.id} style={{fontSize:12,marginTop:7}}>📄 {x.name}</p>):<p style={{fontSize:12,color:"var(--text-muted)",marginTop:7}}>No plan uploaded yet.</p>}</div><div><b>Strategies</b>{strategies.length?strategies.map(x=><p key={x.id} style={{fontSize:12,marginTop:7}}>📄 {x.name}</p>):<p style={{fontSize:12,color:"var(--text-muted)",marginTop:7}}>No strategy uploaded yet.</p>}</div></div></section>
 <section><div style={{marginBottom:12}}><h2 style={{fontSize:20}}>Creative approvals</h2><p style={{fontSize:12,color:"var(--text-muted)"}}>Only real uploaded creatives appear here.</p></div><div className="creative-grid">{realCreatives.map(c=><article className="ig-card" key={c.id}><div className="ig-media">{isVideo(c.fileUrl!,c.type)?<video src={c.fileUrl!} controls playsInline preload="metadata"/>:<img src={c.fileUrl!} alt={c.title}/>}</div><div style={{padding:13}}><div style={{display:"flex",justifyContent:"space-between",gap:8}}><b style={{fontSize:13}}>{c.title}</b><span className="badge badge-blue">{c.type}</span></div><p style={{fontSize:12,lineHeight:1.55,color:"var(--text-secondary)",marginTop:8,whiteSpace:"pre-wrap"}}>{c.caption||"No caption provided."}</p><p style={{fontSize:11,color:"var(--text-muted)",marginTop:8}}>📅 {new Date(c.deadline).toLocaleDateString("en-GB")} · {c.platform||"Social"}</p>{c.approvedByClient?<div style={{marginTop:10,padding:9,borderRadius:9,background:"var(--green-bg)",color:"var(--green)",fontWeight:800,fontSize:11}}>✓ Approved — added to your calendar</div>:<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:7,marginTop:11}}><form action={portalAction}><input type="hidden" name="action" value="task_review"/><input type="hidden" name="taskId" value={c.id}/><input type="hidden" name="decision" value="APPROVED"/><button className="btn btn-success btn-sm" style={{width:"100%"}}>Approve</button></form><details><summary className="btn btn-ghost btn-sm" style={{cursor:"pointer",listStyle:"none",textAlign:"center"}}>Revision</summary><form action={portalAction} style={{marginTop:7}}><input type="hidden" name="action" value="task_review"/><input type="hidden" name="taskId" value={c.id}/><input type="hidden" name="decision" value="REVISION"/><textarea name="comment" required placeholder="What should change?" className="form-input" rows={2}/><button className="btn btn-danger btn-sm" style={{width:"100%",marginTop:5}}>Send revision</button></form></details></div>}</div></article>)}{!realCreatives.length&&<div className="portal-empty" style={{gridColumn:"1/-1"}}>No uploaded creatives are ready for your review yet.</div>}</div></section>
 <section className="card"><div className="card-header"><div><p className="card-title">Upcoming Calendar</p><p style={{fontSize:11,color:"var(--text-muted)",marginTop:3}}>Real approved schedule items only.</p></div><Link href="/dashboard/calendar" className="btn btn-primary btn-sm" style={{textDecoration:"none"}}>Open full calendar →</Link></div><div className="card-body">{calendar.slice(0,8).map(e=><div key={e.id} style={{display:"grid",gridTemplateColumns:"100px 1fr auto",gap:10,padding:"10px 0",borderBottom:"1px solid var(--card-border)",fontSize:12}}><b>{new Date(e.date).toLocaleDateString("en-GB",{day:"2-digit",month:"short"})}</b><div><b>{e.title}</b><p style={{color:"var(--text-muted)",marginTop:2}}>{e.caption||""}</p></div><span className="badge badge-blue">{e.platform||"social"}</span></div>)}{!calendar.length&&<div className="portal-empty">No approved calendar items are scheduled yet.</div>}</div></section>
 </div>}
