import {NextRequest,NextResponse} from "next/server";
import {apiPermissionOrResponse} from "@/lib/vgroup/api-access";
import {getVGroupSql} from "@/lib/vgroup/db";
const ok=(data:unknown,status=200)=>NextResponse.json(data,{status,headers:{"Cache-Control":"no-store"}});
const bad=(code:string,message:string,status=400)=>NextResponse.json({error:{code,message}},{status,headers:{"Cache-Control":"no-store"}});
const str=(v:unknown)=>typeof v==="string"?v.trim():""; const num=(v:unknown)=>Number(v);
type Sql=ReturnType<typeof getVGroupSql>;
async function techBu(sql:Sql){const [bu]=await sql<{id:string}[]>`select id::text from vgroup.business_units where code='tech' and status='active' limit 1`;if(!bu)throw new Error("TECH_BUSINESS_UNIT_UNAVAILABLE");return bu.id}
async function techClient(sql:Sql,buId:string,id:string){const [row]=await sql`select id from tech.clients where id=${id}::uuid and business_unit_id=${buId}::uuid and archived_at is null`;return Boolean(row)}
async function techProject(sql:Sql,buId:string,id:string,clientId?:string){const [row]=clientId?await sql`select id from tech.projects where id=${id}::uuid and business_unit_id=${buId}::uuid and client_id=${clientId}::uuid and archived_at is null`:await sql`select id from tech.projects where id=${id}::uuid and business_unit_id=${buId}::uuid and archived_at is null`;return Boolean(row)}
export async function GET(){const auth=await apiPermissionOrResponse("tech","projects:view");if(auth instanceof NextResponse)return auth;const sql=getVGroupSql();const buId=await techBu(sql);const [summary]=await sql`select
 (select count(*)::int from tech.sales_leads where business_unit_id=${buId}::uuid and status in ('new','qualified')) leads_open,
 (select count(*)::int from tech.sales_opportunities where business_unit_id=${buId}::uuid and stage not in ('won','lost')) opportunities_open,
 (select coalesce(sum(expected_value*probability/100),0)::numeric from tech.sales_opportunities where business_unit_id=${buId}::uuid and stage not in ('won','lost')) weighted_pipeline,
 (select count(*)::int from tech.proposals where business_unit_id=${buId}::uuid and status in ('draft','internal_review','approved_internal','sent')) proposals_open,
 (select count(*)::int from tech.client_contracts where business_unit_id=${buId}::uuid and status='active') contracts_active,
 (select count(*)::int from tech.support_tickets where business_unit_id=${buId}::uuid and status not in ('resolved','closed')) tickets_open,
 (select count(*)::int from tech.trial_extension_requests where business_unit_id=${buId}::uuid and status='pending') trial_extensions_pending,
 (select count(*)::int from tech.upsell_opportunities where business_unit_id=${buId}::uuid and stage not in ('won','lost')) upsells_open`;
 const pipeline=await sql`select id::text,name,stage,probability,expected_value,currency,expected_close from tech.sales_opportunities where business_unit_id=${buId}::uuid and stage not in ('won','lost') order by expected_close nulls last,created_at desc limit 50`;return ok({summary,pipeline})}
export async function POST(request:NextRequest){const session=await apiPermissionOrResponse("tech","projects:update");if(session instanceof NextResponse)return session;const sql=getVGroupSql();const buId=await techBu(sql);let body:Record<string,unknown>;try{body=await request.json()}catch{return bad("INVALID_JSON","Invalid JSON body")}const operation=str(body.operation);try{switch(operation){
 case "lead":{const companyName=str(body.companyName);if(!companyName)return bad("INVALID_LEAD","companyName is required");const [row]=await sql`insert into tech.sales_leads(business_unit_id,company_name,contact_name,email,phone,source,status,owner_id,estimated_value,currency) values(${buId}::uuid,${companyName},${str(body.contactName)||null},${str(body.email)||null},${str(body.phone)||null},${str(body.source)||null},'new',${session.userId}::uuid,${num(body.estimatedValue)||0},${str(body.currency)||"EGP"}) returning id::text,status`;return ok(row,201)}
 case "opportunity":{const name=str(body.name),leadId=str(body.leadId),clientId=str(body.clientId);if(!name)return bad("INVALID_OPPORTUNITY","name is required");if(leadId){const [lead]=await sql`select id from tech.sales_leads where id=${leadId}::uuid and business_unit_id=${buId}::uuid`;if(!lead)return bad("LEAD_NOT_FOUND","Tech lead not found",404)}if(clientId&&!await techClient(sql,buId,clientId))return bad("CLIENT_NOT_FOUND","Tech client not found",404);const [row]=await sql`insert into tech.sales_opportunities(business_unit_id,lead_id,client_id,name,stage,probability,expected_value,currency,expected_close,owner_id) values(${buId}::uuid,${leadId||null}::uuid,${clientId||null}::uuid,${name},${str(body.stage)||"discovery"},${num(body.probability)||10},${num(body.expectedValue)||0},${str(body.currency)||"EGP"},${str(body.expectedClose)||null}::date,${session.userId}::uuid) returning id::text,stage`;return ok(row,201)}
 case "proposal":{const clientId=str(body.clientId),title=str(body.title),opportunityId=str(body.opportunityId);if(!clientId||!title)return bad("INVALID_PROPOSAL","clientId and title are required");if(!await techClient(sql,buId,clientId))return bad("CLIENT_NOT_FOUND","Client not found",404);if(opportunityId){const [opportunity]=await sql`select id from tech.sales_opportunities where id=${opportunityId}::uuid and business_unit_id=${buId}::uuid and (client_id is null or client_id=${clientId}::uuid)`;if(!opportunity)return bad("OPPORTUNITY_CLIENT_MISMATCH","Opportunity does not belong to Tech client",409)}const [row]=await sql`insert into tech.proposals(business_unit_id,opportunity_id,client_id,title,currency,scope_snapshot,commercial_terms,total,estimated_cost,status,valid_until,created_by) values(${buId}::uuid,${opportunityId||null}::uuid,${clientId}::uuid,${title},${str(body.currency)||"EGP"},${JSON.stringify(body.scope??[])}::jsonb,${JSON.stringify(body.commercialTerms??{})}::jsonb,${num(body.total)||0},${num(body.estimatedCost)||0},'internal_review',${str(body.validUntil)||null}::date,${session.userId}::uuid) returning id::text,status`;return ok(row,201)}
 case "support_ticket":{const clientId=str(body.clientId),subject=str(body.subject),projectId=str(body.projectId),supportContractId=str(body.supportContractId),subscriptionId=str(body.subscriptionId);if(!clientId||!subject)return bad("INVALID_TICKET","clientId and subject are required");if(!await techClient(sql,buId,clientId))return bad("CLIENT_NOT_FOUND","Client not found",404);if(projectId&&!await techProject(sql,buId,projectId,clientId))return bad("PROJECT_CLIENT_MISMATCH","Project does not belong to Tech client",409);if(supportContractId){const [contract]=await sql`select id from tech.support_contracts where id=${supportContractId}::uuid and business_unit_id=${buId}::uuid and client_id=${clientId}::uuid and (${projectId||null}::uuid is null or project_id is null or project_id=${projectId||null}::uuid)`;if(!contract)return bad("SUPPORT_CONTRACT_MISMATCH","Support contract is outside the selected Tech client/project",409)}if(subscriptionId){const [subscription]=await sql`select id from tech.subscriptions where id=${subscriptionId}::uuid and business_unit_id=${buId}::uuid and client_id=${clientId}::uuid`;if(!subscription)return bad("SUBSCRIPTION_CLIENT_MISMATCH","Subscription does not belong to Tech client",409)}const [row]=await sql`insert into tech.support_tickets(business_unit_id,client_id,project_id,support_contract_id,subscription_id,subject,description,severity,status,assigned_to,response_due_at,resolution_due_at) values(${buId}::uuid,${clientId}::uuid,${projectId||null}::uuid,${supportContractId||null}::uuid,${subscriptionId||null}::uuid,${subject},${str(body.description)||null},${str(body.severity)||"normal"},'open',${str(body.assignedTo)||null}::uuid,${str(body.responseDueAt)||null}::timestamptz,${str(body.resolutionDueAt)||null}::timestamptz) returning id::text,status`;return ok(row,201)}
 case "trial_extension":{const subscriptionId=str(body.subscriptionId),requestedUntil=str(body.requestedUntil),reason=str(body.reason);if(!subscriptionId||!requestedUntil||!reason)return bad("INVALID_TRIAL_EXTENSION","subscriptionId, requestedUntil and reason are required");const [sub]=await sql`select id from tech.subscriptions where id=${subscriptionId}::uuid and business_unit_id=${buId}::uuid and status='trialing'`;if(!sub)return bad("TRIAL_NOT_FOUND","Trial subscription not found",404);const [row]=await sql`insert into tech.trial_extension_requests(business_unit_id,subscription_id,requested_until,reason,status,requested_by) values(${buId}::uuid,${subscriptionId}::uuid,${requestedUntil}::timestamptz,${reason},'pending',${session.userId}::uuid) returning id::text,status`;return ok(row,201)}
 case "handover_item":{const projectId=str(body.projectId),category=str(body.category),title=str(body.title);if(!projectId||!category||!title)return bad("INVALID_HANDOVER","projectId, category and title are required");if(!await techProject(sql,buId,projectId))return bad("PROJECT_NOT_FOUND","Project not found",404);const [row]=await sql`insert into tech.delivery_handover_items(project_id,category,title,reference,status) values(${projectId}::uuid,${category},${title},${str(body.reference)||null},'pending') returning id::text,status`;return ok(row,201)}
 default:return bad("UNSUPPORTED_OPERATION","Unsupported Tech sales/delivery operation")}}catch(error){const message=error instanceof Error?error.message:"TECH_SALES_DELIVERY_FAILED";return bad("TECH_SALES_DELIVERY_FAILED",message,409)}}
