import { VIVITO_ACADEMY } from "./foundation";
import { VIVITO_INGESTED_BATCH_01_CONTEXT } from "./ingested-batch-01";
import { VIVITO_INGESTED_BATCH_02_CONTEXT } from "./ingested-batch-02";
import { VIVITO_SOURCE_NOTES_CONTEXT,VIVITO_SOURCE_NOTES_BATCH_03 } from "./source-notes-batch-03";
import { VIVITO_SOURCE_NOTES_BATCH_04_CONTEXT } from "./source-notes-batch-04";
import { VIVITO_SOURCE_NOTES_BATCH_05_CONTEXT } from "./source-notes-batch-05";
import { VIVITO_TRAINING_BATCH_06_CONTEXT } from "./training-batch-06";
import { VIVITO_TRAINING_BATCH_07_CONTEXT } from "./training-batch-07";
import { VIVITO_TRAINING_BATCH_08_CONTEXT,VIVITO_MBA_DBA_OPERATING_DOCTRINE } from "./training-batch-08-mba-dba";
import { VIVITO_TRAINING_BATCH_09_CONTEXT,VIVITO_DELIVERABLE_OPERATING_DOCTRINE } from "./training-batch-09-deliverables";
import { VIVITO_DELIVERABLE_BLUEPRINTS_CONTEXT,VIVITO_DELIVERABLE_DESIGN_DOCTRINE } from "./deliverable-blueprints";
import { VIVITO_TRAINING_BATCH_10_CONTEXT,VIVITO_PDF_MASTER_DOCTRINE } from "./training-batch-10-pdf-mastery";
import { VIVITO_TRAINING_BATCH_11_CONTEXT,VIVITO_CREATIVE_OPS_DOCTRINE } from "./training-batch-11-creative-ops";
import { VIVITO_COMPETITIVE_INTELLIGENCE_DOCTRINE,VIVITO_TRAINING_BATCH_12_CONTEXT } from "./training-batch-12-competitive-intelligence";
import { VIVITO_MASTERY_DOCTRINE,VIVITO_TRAINING_BATCH_13_CONTEXT } from "./training-batch-13-mastery";
import { VIVITO_MEDICAL_MARKETING_DOCTRINE,VIVITO_TRAINING_BATCH_14_CONTEXT } from "./training-batch-14-medical-marketing";
import { VIVITO_REAL_ESTATE_MARKETING_DOCTRINE,VIVITO_TRAINING_BATCH_15_CONTEXT } from "./training-batch-15-real-estate-marketing";
import { VIVITO_OMNI_INDUSTRY_DOCTRINE,VIVITO_TRAINING_BATCH_16_CONTEXT } from "./training-batch-16-omni-industry";
import { VIVITO_DECISION_INTELLIGENCE_V2_DOCTRINE,VIVITO_TRAINING_BATCH_17_CONTEXT } from "./training-batch-17-decision-intelligence-v2";
import { VIVITO_REASONING_CORE_V3_DOCTRINE,VIVITO_TRAINING_BATCH_18_CONTEXT } from "./training-batch-18-reasoning-core-v3";
import { VIVITO_AUTONOMOUS_STRATEGIC_BRAIN_DOCTRINE,VIVITO_TRAINING_BATCH_19_CONTEXT } from "./training-batch-19-autonomous-strategic-brain";
import { VIVITO_MEMORY_LEARNING_INTELLIGENCE_DOCTRINE,VIVITO_TRAINING_BATCH_20_CONTEXT } from "./training-batch-20-memory-learning-intelligence";
import { VIVITO_BUSINESS_ECONOMICS_CAPITAL_ALLOCATION_DOCTRINE,VIVITO_TRAINING_BATCH_21_CONTEXT } from "./training-batch-21-business-economics-capital-allocation";
import { VIVITO_EXECUTIVE_COUNCIL_PROTOCOL,VIVITO_TRAINING_BATCH_22_CONTEXT } from "./training-batch-22-multi-agent-executive-brain";
import { VIVITO_PLANNING_UNDER_UNCERTAINTY_DOCTRINE,VIVITO_TRAINING_BATCH_23_CONTEXT } from "./training-batch-23-planning-under-uncertainty";
import { VIVITO_HUMAN_BEHAVIOR_PSYCHOLOGY_DOCTRINE,VIVITO_TRAINING_BATCH_24_CONTEXT } from "./training-batch-24-human-behavior-psychology";
import { VIVITO_NEGOTIATION_GAME_THEORY_DOCTRINE,VIVITO_TRAINING_BATCH_25_CONTEXT } from "./training-batch-25-negotiation-game-theory";
import { VIVITO_SELF_IMPROVING_INTELLIGENCE_DOCTRINE,VIVITO_TRAINING_BATCH_26_CONTEXT } from "./training-batch-26-self-improving-intelligence-loop";
import { VIVITO_ARTIFACT_DOCTRINE } from "./artifact-intelligence";

const VIVITO_FOUNDATION_CONTEXT=VIVITO_ACADEMY.map(d=>`## ${d.name}\nSources: ${d.sources.join(", ")}\n${d.principles.map(x=>`- ${x}`).join("\n")}`).join("\n\n");

export const VIVITO_ACADEMY_CONTEXT=[
  VIVITO_FOUNDATION_CONTEXT,
  "# INGESTED LESSONS — BATCH 01",VIVITO_INGESTED_BATCH_01_CONTEXT,
  "# INGESTED LESSONS — BATCH 02",VIVITO_INGESTED_BATCH_02_CONTEXT,
  "# VERIFIED PLATFORM NOTES — BATCH 04",VIVITO_SOURCE_NOTES_BATCH_04_CONTEXT,
  "# META SPECIALIST NOTES — BATCH 05",VIVITO_SOURCE_NOTES_BATCH_05_CONTEXT,
  "# AGENCY OPERATING MASTERY — BATCH 06",VIVITO_TRAINING_BATCH_06_CONTEXT,
  "# ADVANCED JUDGMENT & CROSS-FUNCTIONAL MASTERY — BATCH 07",VIVITO_TRAINING_BATCH_07_CONTEXT,
  "# MBA + DBA BUSINESS & MARKETING MASTERY — BATCH 08",VIVITO_MBA_DBA_OPERATING_DOCTRINE,VIVITO_TRAINING_BATCH_08_CONTEXT,
  "# STRATEGY, RESEARCH & DELIVERABLE MASTERY — BATCH 09",VIVITO_DELIVERABLE_OPERATING_DOCTRINE,VIVITO_DELIVERABLE_DESIGN_DOCTRINE,VIVITO_DELIVERABLE_BLUEPRINTS_CONTEXT,VIVITO_TRAINING_BATCH_09_CONTEXT,
  "# EXECUTIVE PDF DESIGN & PRODUCTION MASTERY — BATCH 10",VIVITO_PDF_MASTER_DOCTRINE,VIVITO_TRAINING_BATCH_10_CONTEXT,
  "# VISUAL, RESEARCH, CONTENT, SHEETS & REELS MASTERY — BATCH 11",VIVITO_ARTIFACT_DOCTRINE,VIVITO_CREATIVE_OPS_DOCTRINE,VIVITO_TRAINING_BATCH_11_CONTEXT,
  "# COMPETITIVE INTELLIGENCE & DAILY SOCIAL MONITORING — BATCH 12",VIVITO_COMPETITIVE_INTELLIGENCE_DOCTRINE,VIVITO_TRAINING_BATCH_12_CONTEXT,
  "# INTEGRATED MASTER MINDSET — BATCH 13",VIVITO_MASTERY_DOCTRINE,VIVITO_TRAINING_BATCH_13_CONTEXT,
  "# MEDICAL MARKETING MASTERY — BATCH 14",VIVITO_MEDICAL_MARKETING_DOCTRINE,VIVITO_TRAINING_BATCH_14_CONTEXT,
  "# REAL ESTATE MARKETING MASTERY — BATCH 15",VIVITO_REAL_ESTATE_MARKETING_DOCTRINE,VIVITO_TRAINING_BATCH_15_CONTEXT,
  "# OMNI-INDUSTRY BUSINESS & MARKETING MASTERY — BATCH 16",VIVITO_OMNI_INDUSTRY_DOCTRINE,VIVITO_TRAINING_BATCH_16_CONTEXT,
  "# DECISION INTELLIGENCE V2 — BATCH 17",VIVITO_DECISION_INTELLIGENCE_V2_DOCTRINE,VIVITO_TRAINING_BATCH_17_CONTEXT,
  "# REASONING CORE V3 — BATCH 18",VIVITO_REASONING_CORE_V3_DOCTRINE,VIVITO_TRAINING_BATCH_18_CONTEXT,
  "# AUTONOMOUS STRATEGIC BRAIN — BATCH 19",VIVITO_AUTONOMOUS_STRATEGIC_BRAIN_DOCTRINE,VIVITO_TRAINING_BATCH_19_CONTEXT,
  "# MEMORY & LEARNING INTELLIGENCE — BATCH 20",VIVITO_MEMORY_LEARNING_INTELLIGENCE_DOCTRINE,VIVITO_TRAINING_BATCH_20_CONTEXT,
  "# BUSINESS ECONOMICS & CAPITAL ALLOCATION — BATCH 21",VIVITO_BUSINESS_ECONOMICS_CAPITAL_ALLOCATION_DOCTRINE,VIVITO_TRAINING_BATCH_21_CONTEXT,
  "# MULTI-AGENT EXECUTIVE BRAIN — BATCH 22",VIVITO_EXECUTIVE_COUNCIL_PROTOCOL,VIVITO_TRAINING_BATCH_22_CONTEXT,
  "# PLANNING UNDER UNCERTAINTY — BATCH 23",VIVITO_PLANNING_UNDER_UNCERTAINTY_DOCTRINE,VIVITO_TRAINING_BATCH_23_CONTEXT,
  "# HUMAN BEHAVIOR & PSYCHOLOGY — BATCH 24",VIVITO_HUMAN_BEHAVIOR_PSYCHOLOGY_DOCTRINE,VIVITO_TRAINING_BATCH_24_CONTEXT,
  "# NEGOTIATION & GAME THEORY — BATCH 25",VIVITO_NEGOTIATION_GAME_THEORY_DOCTRINE,VIVITO_TRAINING_BATCH_25_CONTEXT,
  "# SELF-IMPROVING INTELLIGENCE LOOP — BATCH 26",VIVITO_SELF_IMPROVING_INTELLIGENCE_DOCTRINE,VIVITO_TRAINING_BATCH_26_CONTEXT,
].join("\n\n");

export { VIVITO_ACADEMY,VIVITO_SOURCE_NOTES_CONTEXT,VIVITO_SOURCE_NOTES_BATCH_03 as VIVITO_SOURCE_NOTES };

export const VIVITO_ACADEMY_TESTS=[
 {domain:"Media Buying",question:"A Meta messaging campaign spent 4,000 EGP and generated 200 messaging conversations. What is the primary result and CPR?",mustInclude:["200","20","messag"]},
 {domain:"Media Buying",question:"A sales campaign has strong CTR but weak purchases. What should I investigate before increasing budget?",mustInclude:["offer","landing","checkout"]},
 {domain:"Business",question:"Should I scale a service that has high revenue but negative contribution margin?",mustInclude:["margin","no"]},
 {domain:"Content",question:"How should I improve a video that loses most viewers in the opening seconds?",mustInclude:["hook","first"]},
 {domain:"Design",question:"What should I review first in a cluttered social design?",mustInclude:["hierarchy"]},
 {domain:"Account Management",question:"What should a client performance review include?",mustInclude:["goal","performance","action"]},
 {domain:"Analytics",question:"Ads Manager and backend purchases disagree. What should I do?",mustInclude:["tracking","attribution"]},
 {domain:"Ecommerce",question:"Is a high ROAS enough to prove an ecommerce campaign is profitable?",mustInclude:["margin","no"]},
 {domain:"Sales",question:"A prospect says the price is too high. Should I immediately discount?",mustInclude:["objection"]},
 {domain:"Automation",question:"Should an AI automatically publish an irreversible client commitment without approval?",mustInclude:["approval","no"]}
];