type ExternalCampaignWriteInput={platform:string;campaignId:string;adAccountId:string;accessToken:string;status?:string;dailyBudget?:number;lifetimeBudget?:number;currency?:string};
export type ExternalCampaignWriteResult={platform:string;campaignId:string;applied:string[];providerRequest:string;providerResponse?:unknown};
const TIMEOUT=15000;
const finite=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)&&v>=0;
const status=(v?:string)=>String(v||"").trim().toUpperCase();
type ProviderResponse={error?:string|{message?:string};message?:string;code?:number|string;request_status?:string;raw?:string;[key:string]:unknown};
type LinkedInPatch={status?:string;dailyBudget?:{amount:string;currencyCode:string};totalBudget?:{amount:string;currencyCode:string}};
type SnapchatCampaign={id:string;ad_account_id:string;status?:string;daily_budget_micro?:number;lifetime_spend_cap_micro?:number};
const json=async(url:string,init:RequestInit):Promise<ProviderResponse>=>{const r=await fetch(url,{...init,cache:"no-store",signal:AbortSignal.timeout(TIMEOUT)});const text=await r.text();let d:ProviderResponse={};try{d=text?JSON.parse(text) as ProviderResponse:{}}catch{d={raw:text.slice(0,500)}}const errorMessage=typeof d.error==="string"?d.error:d.error?.message;if(!r.ok||d.error||d.code&&Number(d.code)!==0||d.request_status&&d.request_status!=="SUCCESS")throw new Error(errorMessage||d.message||`Provider mutation failed (${r.status})`);return d};
const digits=(v:string)=>String(v||"").replace(/\D/g,"");
const zeroDecimal=new Set(["BIF","CLP","DJF","GNF","JPY","KMF","KRW","MGA","PYG","RWF","UGX","VND","VUV","XAF","XOF","XPF"]);
const metaMinor=(amount:number,currency:string)=>Math.round(amount*(zeroDecimal.has(currency.toUpperCase())?1:100));

async function meta(i:ExternalCampaignWriteInput):Promise<ExternalCampaignWriteResult>{
 const v=process.env.META_GRAPH_VERSION||"v23.0",body=new URLSearchParams(),applied:string[]=[];if(i.status){const s=status(i.status);if(!["ACTIVE","PAUSED"].includes(s))throw new Error("Meta campaign status must be ACTIVE or PAUSED.");body.set("status",s);applied.push("status")}if(finite(i.dailyBudget)){body.set("daily_budget",String(metaMinor(i.dailyBudget!,i.currency||"USD")));applied.push("dailyBudget")}if(finite(i.lifetimeBudget)){body.set("lifetime_budget",String(metaMinor(i.lifetimeBudget!,i.currency||"USD")));applied.push("lifetimeBudget")}if(!applied.length)throw new Error("No Meta-supported campaign fields were supplied.");body.set("access_token",i.accessToken);const url=`https://graph.facebook.com/${v}/${encodeURIComponent(i.campaignId)}`,d=await json(url,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body});return{platform:"META",campaignId:i.campaignId,applied,providerRequest:`POST /${i.campaignId}`,providerResponse:d}}

async function tiktok(i:ExternalCampaignWriteInput):Promise<ExternalCampaignWriteResult>{
 if(!i.adAccountId)throw new Error("TikTok advertiser ID is required.");const applied:string[]=[];let last:unknown=null;if(i.status){const s=status(i.status),operation=s==="ACTIVE"||s==="ENABLE"?"ENABLE":s==="PAUSED"||s==="DISABLE"?"DISABLE":"";if(!operation)throw new Error("TikTok campaign status must be ACTIVE/ENABLE or PAUSED/DISABLE.");last=await json("https://business-api.tiktok.com/open_api/v1.3/campaign/status/update/",{method:"POST",headers:{"Access-Token":i.accessToken,"Content-Type":"application/json"},body:JSON.stringify({advertiser_id:String(i.adAccountId),campaign_ids:[String(i.campaignId)],operation_status:operation})});applied.push("status")}
 if(finite(i.dailyBudget)||finite(i.lifetimeBudget)){if(finite(i.dailyBudget)&&finite(i.lifetimeBudget))throw new Error("TikTok campaign update accepts one budget value at a time in VIVITO.");const budget=finite(i.dailyBudget)?i.dailyBudget:i.lifetimeBudget;last=await json("https://business-api.tiktok.com/open_api/v1.3/campaign/update/",{method:"POST",headers:{"Access-Token":i.accessToken,"Content-Type":"application/json"},body:JSON.stringify({advertiser_id:String(i.adAccountId),campaign_id:String(i.campaignId),budget})});applied.push(finite(i.dailyBudget)?"dailyBudget":"lifetimeBudget")}
 if(!applied.length)throw new Error("No TikTok-supported campaign fields were supplied.");return{platform:"TIKTOK",campaignId:i.campaignId,applied,providerRequest:"campaign/status/update + campaign/update",providerResponse:last}}

async function google(i:ExternalCampaignWriteInput):Promise<ExternalCampaignWriteResult>{
 if(!i.adAccountId)throw new Error("Google Ads customer ID is required.");if(finite(i.dailyBudget)||finite(i.lifetimeBudget))throw new Error("Google campaign budgets use a separate CampaignBudget resource. VIVITO will not guess that resource; link it before external budget mutation.");if(!i.status)throw new Error("No Google-supported campaign fields were supplied.");const raw=status(i.status),s=raw==="ACTIVE"?"ENABLED":raw;if(!["ENABLED","PAUSED"].includes(s))throw new Error("Google campaign status must be ACTIVE/ENABLED or PAUSED.");const customer=digits(i.adAccountId),version=process.env.GOOGLE_ADS_VERSION||"v25",dev=process.env.GOOGLE_ADS_DEVELOPER_TOKEN;if(!dev)throw new Error("Google Ads developer token is not configured.");const body={operations:[{updateMask:"status",update:{resourceName:`customers/${customer}/campaigns/${i.campaignId}`,status:s}}]};const d=await json(`https://googleads.googleapis.com/${version}/customers/${customer}/campaigns:mutate`,{method:"POST",headers:{Authorization:`Bearer ${i.accessToken}`,"developer-token":dev,"login-customer-id":process.env.GOOGLE_ADS_LOGIN_CUSTOMER_ID||"","Content-Type":"application/json"},body:JSON.stringify(body)});return{platform:"GOOGLE",campaignId:i.campaignId,applied:["status"],providerRequest:`POST /${version}/customers/${customer}/campaigns:mutate`,providerResponse:d}}

async function linkedin(i:ExternalCampaignWriteInput):Promise<ExternalCampaignWriteResult>{
 if(!i.adAccountId)throw new Error("LinkedIn ad account ID is required.");const set:LinkedInPatch={},applied:string[]=[];if(i.status){const s=status(i.status);if(!["ACTIVE","PAUSED","ARCHIVED","PENDING_DELETION"].includes(s))throw new Error("Unsupported LinkedIn campaign status.");set.status=s;applied.push("status")}const currency=String(i.currency||"USD").toUpperCase();if(finite(i.dailyBudget)){set.dailyBudget={amount:String(i.dailyBudget),currencyCode:currency};applied.push("dailyBudget")}if(finite(i.lifetimeBudget)){set.totalBudget={amount:String(i.lifetimeBudget),currencyCode:currency};applied.push("lifetimeBudget")}if(!applied.length)throw new Error("No LinkedIn-supported campaign fields were supplied.");const version=process.env.LINKEDIN_VERSION||"202607",url=`https://api.linkedin.com/rest/adAccounts/${encodeURIComponent(i.adAccountId)}/adCampaigns/${encodeURIComponent(i.campaignId)}`,d=await json(url,{method:"POST",headers:{Authorization:`Bearer ${i.accessToken}`,"LinkedIn-Version":version,"X-Restli-Protocol-Version":"2.0.0","X-RestLi-Method":"PARTIAL_UPDATE","Content-Type":"application/json"},body:JSON.stringify({patch:{$set:set}})});return{platform:"LINKEDIN",campaignId:i.campaignId,applied,providerRequest:"POST adCampaigns/{id} PARTIAL_UPDATE",providerResponse:d}}

async function snapchat(i:ExternalCampaignWriteInput):Promise<ExternalCampaignWriteResult>{
 if(!i.adAccountId)throw new Error("Snapchat ad account ID is required.");const campaign:SnapchatCampaign={id:i.campaignId,ad_account_id:i.adAccountId},applied:string[]=[];if(i.status){const s=status(i.status);if(!["ACTIVE","PAUSED"].includes(s))throw new Error("Snapchat campaign status must be ACTIVE or PAUSED.");campaign.status=s;applied.push("status")}if(finite(i.dailyBudget)){campaign.daily_budget_micro=Math.round(i.dailyBudget!*1_000_000);applied.push("dailyBudget")}if(finite(i.lifetimeBudget)){campaign.lifetime_spend_cap_micro=Math.round(i.lifetimeBudget!*1_000_000);applied.push("lifetimeBudget")}if(!applied.length)throw new Error("No Snapchat-supported campaign fields were supplied.");const url=`https://adsapi.snapchat.com/v1/adaccounts/${encodeURIComponent(i.adAccountId)}/campaigns`,d=await json(url,{method:"PUT",headers:{Authorization:`Bearer ${i.accessToken}`,"Content-Type":"application/json"},body:JSON.stringify({campaigns:[campaign]})});return{platform:"SNAPCHAT",campaignId:i.campaignId,applied,providerRequest:"PUT /v1/adaccounts/{id}/campaigns",providerResponse:d}}

export const VIVITO_EXTERNAL_WRITE_CAPABILITIES={META:["status","dailyBudget","lifetimeBudget"],TIKTOK:["status","dailyBudget","lifetimeBudget"],GOOGLE:["status"],SNAPCHAT:["status","dailyBudget","lifetimeBudget"],LINKEDIN:["status","dailyBudget","lifetimeBudget"]} as const;
export async function mutateExternalCampaign(input:ExternalCampaignWriteInput){const p=String(input.platform||"").toUpperCase();if(!input.campaignId||!input.accessToken)throw new Error("Campaign ID and provider access token are required.");if(p==="META")return meta({...input,platform:p});if(p==="TIKTOK")return tiktok({...input,platform:p});if(p==="GOOGLE")return google({...input,platform:p});if(p==="SNAPCHAT")return snapchat({...input,platform:p});if(p==="LINKEDIN")return linkedin({...input,platform:p});throw new Error(`External campaign writes are not supported for ${p||"this platform"}.`)}
