import type {VivitoContentPlan,VivitoPdfSpec,VivitoPresentation,VivitoWorkbook} from "./artifact-intelligence";

export type VivitoArtifactKind="pdf"|"pptx"|"xlsx"|"content-plan";
export type VivitoArtifactProposal={kind:VivitoArtifactKind;title:string;fileName:string;summary:string;pdf?:VivitoPdfSpec;presentation?:VivitoPresentation;workbook?:VivitoWorkbook;contentPlan?:VivitoContentPlan};
const q=(s:string)=>String(s||"").toLowerCase();
export function likelyVivitoVisionIntent(question:string,attachments:{mimeType:string}[]=[]){const hasImage=attachments.some(a=>String(a.mimeType).toLowerCase().startsWith("image/"));if(!hasImage)return false;return /(حلل|حلّل|شوف|شايف|الصوره|الصورة|ديزاين|design|image|photo|visual|راجع|review|analy[sz]e|اقرا|اقرأ|read)/i.test(question)||question.trim().length<80}
export function likelyVivitoResearchIntent(question:string){return /(سيرش|ابحث|بحث سوق|ماركت ريسيرش|market research|competitor|منافس|سعر السوق|market size|tam|sam|som|trend|ترند|latest|current|دلوقتي|حاليا|حاليًا|2026|benchmark|industry report|regulation|قانون|platform update)/i.test(question)}
export function likelyVivitoArtifactIntent(question:string){return /(pdf|pptx|powerpoint|برزنتيشن|presentation|deck|استراتيجي|strategy deck|marketing plan|ماركتنج بلان|media buying plan|ميديا باينج|swot|pestel|pastel|market research|marketing research|content plan|خطة محتوى|خطة محتوي|excel|اكسل|xlsx|sheet|شيت|workbook)/i.test(question)}
export function requestedArtifactKind(question:string):VivitoArtifactKind{const s=q(question);if(/excel|اكسل|xlsx|sheet|شيت|workbook|content plan|خطة محتوى|خطة محتوي/.test(s))return /content plan|خطة محتوى|خطة محتوي/.test(s)?"content-plan":"xlsx";if(/pptx|powerpoint|برزنتيشن|presentation|deck/.test(s))return"pptx";return"pdf"}
export function buildVivitoArtifactPlannerSystem(kind:VivitoArtifactKind){const common=`You are VIVITO Artifact Architect. Return ONLY strict JSON. Never claim a file exists; you only return a structured artifact specification. Use the user's language. Build executive-grade deliverables with one dominant message per page/slide/sheet, evidence, implication, clear hierarchy, concise copy, sources/methodology when research is involved, and no invented statistics.`;if(kind==="pdf")return`${common}\nJSON schema: {"kind":"pdf","title":"...","fileName":"...","summary":"...","pdf":{"title":"...","subtitle":"...","author":"VIVITO","theme":{"accent":[0.77,0.09,0.13],"dark":false},"pages":[{"title":"assertion title","eyebrow":"section","blocks":[{"type":"body|bullet|metric|callout|subtitle|title|quote|divider","text":"..."},{"type":"table","headers":["..."],"rows":[["..."]]},{"type":"chart","title":"...","data":[{"label":"...","value":12}]}],"footer":"source / section"}]}}. Use 8-24 pages depending on scope. Include executive summary, diagnosis, strategic choices, actions, KPIs, roadmap, risks and appendix/methodology when relevant.`;if(kind==="pptx")return`${common}\nJSON schema: {"kind":"pptx","title":"...","fileName":"...","summary":"...","presentation":{"title":"...","subtitle":"...","author":"VIVITO","audience":"CEO/CMO/Client","objective":"decision to enable","slides":[{"title":"assertion headline","subtitle":"optional section cue","body":["evidence-led point","implication","recommended action"],"metrics":[{"label":"Metric","value":"12%","delta":"+2pp"}],"sources":["source/date"],"speakerNotes":"optional"}]}}. Use 8-24 slides depending on scope. Titles must state conclusions, not topics. Include executive summary, diagnosis, strategic choices, economics, roadmap, KPIs, risks and appendix where relevant. Keep slide density low and do not dump prose.`;if(kind==="content-plan")return`${common}\nJSON schema: {"kind":"content-plan","title":"...","fileName":"...","summary":"...","contentPlan":{"brand":"...","period":"...","objectives":["..."],"audiences":["..."],"pillars":[{"name":"...","role":"...","share":25}],"rows":[{"date":"YYYY-MM-DD","platform":"Instagram","pillar":"...","format":"Reel","objective":"...","topic":"...","hook":"...","captionDirection":"...","cta":"...","kpi":"...","owner":"","status":"PLANNED"}]}}. Produce an operational calendar. Every row must be executable. Balance funnel roles and content pillars.`;return`${common}\nJSON schema: {"kind":"xlsx","title":"...","fileName":"...","summary":"...","workbook":{"title":"...","sheets":[{"name":"Summary","columns":["..."],"rows":[["..."]]},{"name":"Plan","columns":["..."],"rows":[["..."]]}]}}. Separate inputs, calculations/logic, outputs and notes into sensible sheets. Use stable row grain and management-ready summaries.`}
function fence(s:string){const t=s.trim();return t.startsWith("```")?t.replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"").trim():t}
export function parseVivitoArtifactProposal(raw:string,kind:VivitoArtifactKind):VivitoArtifactProposal|null{try{const x=JSON.parse(fence(raw));if(x?.kind!==kind)return null;const base={kind,title:String(x.title||"VIVITO Artifact").slice(0,160),fileName:String(x.fileName||"vivito-artifact").replace(/[^a-zA-Z0-9._-]/g,"-").slice(0,80),summary:String(x.summary||"").slice(0,600)} as VivitoArtifactProposal;if(kind==="pdf"&&x.pdf?.pages?.length)return{...base,pdf:x.pdf};if(kind==="pptx"&&x.presentation?.slides?.length)return{...base,presentation:x.presentation};if(kind==="content-plan"&&x.contentPlan?.rows?.length)return{...base,contentPlan:x.contentPlan};if(kind==="xlsx"&&x.workbook?.sheets?.length)return{...base,workbook:x.workbook};return null}catch{return null}}
