import {normalizeVivitoLanguage} from "./language";
export type CompetitiveChatPlan={op:"setup"|"report"|"none";clientName:string;competitors:{name:string;urls:string[]}[]};
type UnknownRecord=Record<string,unknown>;
const RE=/(منافس|منافسين|competitor|راقب|راقبلي|monitor|tracking|تراك|social watch|تقرير المنافسين|competitive)/i;
const record=(value:unknown):UnknownRecord=>value&&typeof value==="object"&&!Array.isArray(value)?Object.fromEntries(Object.entries(value)):{};
export function likelyCompetitiveChatIntent(question:string){const n=normalizeVivitoLanguage(question).normalized;return RE.test(question)||RE.test(n)}
export function buildCompetitivePlannerSystem(){return `You are VIVITO Competitive Intelligence Planner. Return ONLY JSON: {"op":"setup|report|none","clientName":"","competitors":[{"name":"","urls":[]}]}. Understand Arabic, Egyptian, English, mixed language and Franco. Use setup when the user asks to monitor/watch/track competitors and provides or refers to competitor social URLs. Use report when the user asks for today's/latest competitor report. Preserve social URLs exactly. clientName is the VIVIT client/brand whose competitors are being watched, NOT the competitor name. For setup, group URLs under the correct competitor name when explicitly stated; if names are unclear, use a short host/handle-derived name rather than inventing a brand. Never invent URLs.`}
function strip(raw:string){const t=raw.trim();return t.startsWith("```")?t.replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"").trim():t}
export function parseCompetitiveChatPlan(raw:string):CompetitiveChatPlan|null{try{const parsed:unknown=JSON.parse(strip(raw)),p=record(parsed),op=String(p.op||"none");if(!["setup","report","none"].includes(op)||op==="none")return null;const competitors=Array.isArray(p.competitors)?p.competitors.slice(0,20).map(value=>{const x=record(value),urls=Array.isArray(x.urls)?x.urls.map(String).filter(u=>/^https:\/\//i.test(u)).slice(0,12):[];return{name:String(x.name||"").trim().slice(0,180),urls}}).filter(x=>x.name||x.urls.length):[];return{op:op==="setup"?"setup":"report",clientName:String(p.clientName||"").trim().slice(0,180),competitors}}catch{return null}}
