import {createHash} from "node:crypto";
import {db,sql,notifications,auditLogs} from "@/lib/db";
import {decideVivitoApproval} from "./approval-policy";
import {executeVivitoAction} from "./executor";
import {executeVivitoOperatorAction,isVivitoOperatorAction} from "./executor-operator";
import type {VivitoActionOp} from "./action-engine";
import {assertAutonomyAllowed,claimNotification,consumeResource,preflightDecision,recordValue} from "./enterprise-governance";

type JsonData=string|number|boolean|null|Date|JsonData[]|{[key:string]:JsonData|undefined};
type JsonObject={[key:string]:JsonData|undefined};
type SchemaRow={e:string|null;o:string|null;l:string|null;a:string|null;j:string|null;s:string|null;g:string|null;u:string|null;p:string|null};
type Actor={id:string;name:string;role:string;workspace_id:string};
type WorkspaceRow={workspace_id:string|null};
type IdRow={id:string};
type OwnerRow={account_manager_id:string|null};
type InsertedEventRow={id:string;status:string};
type CompetitorReportRow={client_id:string;report_date:string|Date;report_json:JsonData;company_name:string};
type CompetitorDetail={error?:JsonData;newPosts?:JsonData[];delta?:{followers?:number|string|null};competitor?:JsonData;profileUrl?:JsonData;source?:JsonData};
type CompetitorSignal={competitor:string;newPosts:number;followerDelta:number|null;profileUrl:string;source:string};
type OverdueRow={id:string;client_id:string;title:string;deadline:string|Date;company_name:string};
type RiskRow={id:string;company_name:string;health_score:number|string|null;churn_risk:string|null;churn_probability:number|string|null};
type InvoiceRow={id:string;client_id:string;invoice_number:string|null;outstanding:number|string|null;due_date:string|Date};
type MediaRow={client_id:string;company_name:string;campaign_id:string;campaign_name:string;spend:number|string;results:number|string;revenue:number|string};
type EventRow={id:string;workspace_id:string;client_id:string|null;signal_type:string;action_op:string;action_args:JsonData;approval_mode:string;status:string;actor_id:string;evidence:JsonData;execution_result:JsonData;confidence_before:number|string|null;evidence_quality:number|string|null;decision_route:string|null;retry_count:number|string|null;max_retries:number|string|null};
type TaskOutcomeRow={id:string;status:string;completed_at:string|Date|null;updated_at:string|Date|null};
type MediaOutcomeRow={id:string;status:string;spend:number|string;results:number|string;revenue:number|string};
type OutcomeDueRow={id:string;event_id:string;horizon_hours:number|string;baseline:JsonData;action_op:string;action_args:JsonData;evidence:JsonData;execution_result:JsonData;client_id:string|null;confidence_before:number|string|null};
type ProposalResult={duplicate:boolean;mode:string;eventId:string|null;executed?:boolean;retryScheduled?:boolean};
type EnterpriseDecision={decisionVersion?:string;evidenceQuality?:number;confidence?:number;route?:{mode?:string;reason?:string};simulation?:JsonData};
type ObserveInput={action_op:string;action_args:JsonData;baseline?:JsonData;evidence?:JsonData;execution_result?:JsonData};
type ObservedOutcome=
 |{kind:"TASK";entityId:string;status:string;completedAt:string|Date|null}
 |{kind:"MEDIA";campaignId:string;status:string;spend24h:number;results24h:number;revenue24h:number;baseline:JsonObject}
 |{kind:"GENERIC";baseline:JsonObject};

type AuditInsert=typeof auditLogs.$inferInsert;
type NotificationInsert=typeof notifications.$inferInsert;

const asObject=(value:JsonData|undefined):JsonObject=>value&&typeof value==="object"&&!Array.isArray(value)&&!(value instanceof Date)?value:{};
const parseJson=(value:JsonData|undefined):JsonObject=>{try{return typeof value==="string"?asObject(JSON.parse(value) as JsonData):asObject(value)}catch{return{}}};
const clean=(value:unknown,n=1000)=>String(value??"").replace(/\s+/g," ").trim().slice(0,n);
const errorText=(value:unknown,n=900)=>clean(value instanceof Error?value.message:value,n);
const hours=(n:number)=>new Date(Date.now()+n*3600000);
const day=()=>new Date().toISOString().slice(0,10);
const clamp=(n:number,min=0,max=1)=>Math.min(max,Math.max(min,n));
const fingerprint=(value:JsonData|undefined)=>createHash("sha256").update(JSON.stringify(value??null)).digest("hex");
const jsonString=(value:JsonData|undefined)=>JSON.stringify(value??{});

export type DirectCycleResult={ok:boolean;workspaceId?:string;signals:number;autoExecuted:number;queued:number;retried:number;outcomesChecked:number;errors:string[]};

async function ensureSchema(){
 const [r]=Array.from(await db.execute(sql<SchemaRow>`select to_regclass('public.vivito_autonomy_events') e,to_regclass('public.vivito_outcome_checks') o,to_regclass('public.vivito_learning_signals') l,to_regclass('public.vivito_approval_events') a,to_regclass('public.vivito_decision_journal') j,to_regclass('public.vivito_escalations') s,to_regclass('public.vivito_governance_controls') g,to_regclass('public.vivito_resource_usage') u,to_regclass('public.vivito_knowledge_provenance') p`));
 if(!r?.e||!r.o||!r.l||!r.a||!r.j||!r.s||!r.g||!r.u||!r.p)throw new Error("vivito-direct-schema-v3-not-ready");
}
async function systemActor():Promise<Actor>{
 const id=clean(process.env.VIVITO_AUTONOMY_ACTOR_ID,120);if(!id)throw new Error("vivito-autonomy-actor-not-configured");
 const [actor]=Array.from(await db.execute(sql<Actor>`select id,name,role,workspace_id from users where id=${id} and role='SUPER_ADMIN' and is_active=true and approval_status='APPROVED' limit 1`));
 if(!actor)throw new Error("vivito-autonomy-actor-invalid");return actor;
}
export async function resolveVivitoWorkspaceForUser(userId:string){
 const [user]=Array.from(await db.execute(sql<WorkspaceRow>`select workspace_id from users where id=${userId} and is_active=true and approval_status='APPROVED' limit 1`));
 if(!user?.workspace_id)throw new Error("active-user-workspace-not-found");return user.workspace_id;
}
export async function resolveVivitoAutonomyWorkspace(){return (await systemActor()).workspace_id}
async function execute(op:VivitoActionOp,args:JsonObject,role:string,userId:string,workspaceId:string){if(!workspaceId)throw new Error("direct-workspace-required");return isVivitoOperatorAction(op)?executeVivitoOperatorAction(op,args,role,userId,workspaceId):executeVivitoAction(op,args,role,userId,workspaceId)}
async function audit(workspaceId:string,userId:string,action:string,entityId:string,payload:JsonData){
 const value:AuditInsert={workspaceId,userId,action,entity:"VIVITO_DIRECT",entityId,newValues:JSON.stringify(payload)};await db.insert(auditLogs).values(value);
}

async function notifyTargets(workspaceId:string,clientId:string|null,title:string,message:string,priority="normal",dedupeKey?:string){
 if(dedupeKey&&!(await claimNotification(workspaceId,dedupeKey,24)))return;
 const targets=clientId
  ?Array.from(await db.execute(sql<IdRow>`select id from users where workspace_id=${workspaceId} and is_active=true and approval_status='APPROVED' and (role='SUPER_ADMIN' or id=(select account_manager_id from clients where id=${clientId} and workspace_id=${workspaceId}) or id=(select media_buyer_id from clients where id=${clientId} and workspace_id=${workspaceId}))`))
  :Array.from(await db.execute(sql<IdRow>`select id from users where workspace_id=${workspaceId} and role='SUPER_ADMIN' and is_active=true and approval_status='APPROVED'`));
 for(const user of targets){const value:NotificationInsert={userId:user.id,type:"GENERAL",priority,title,message:message.slice(0,1800),link:clientId?`/dashboard/clients/${clientId}`:"/dashboard/ai-studio/operations"};await db.insert(notifications).values(value).onConflictDoNothing()}
}
async function journal(workspaceId:string,eventId:string|null,clientId:string|null,signalType:string,op:string,evidence:JsonData,status:string,rationale:string,expectedOutcome?:string,enterprise:EnterpriseDecision={}){
 await db.execute(sql`insert into vivito_decision_journal(id,workspace_id,event_id,client_id,decision_type,signal_type,evidence_summary,rationale_summary,expected_outcome,decision_status,decision_version,evidence_quality,confidence,evidence,decision,simulation) values(${crypto.randomUUID()},${workspaceId},${eventId},${clientId},${op},${signalType},${jsonString(evidence)}::jsonb,${clean(rationale,1800)},${expectedOutcome?clean(expectedOutcome,900):null},${status},${enterprise.decisionVersion||'direct-v3'},${Number(enterprise.evidenceQuality||0)},${Number(enterprise.confidence||0)},${jsonString(evidence)}::jsonb,${JSON.stringify({op,route:enterprise.route||null})}::jsonb,${JSON.stringify(enterprise.simulation||null)}::jsonb)`);
}
async function updateJournal(workspaceId:string,eventId:string,status:string,outcome?:JsonData){await db.execute(sql`update vivito_decision_journal set decision_status=${status},outcome=coalesce(${outcome===undefined?null:jsonString(outcome)}::jsonb,outcome),updated_at=now() where workspace_id=${workspaceId} and event_id=${eventId}`)}
async function escalate(workspaceId:string,eventId:string|null,clientId:string|null,severity:"LOW"|"MEDIUM"|"HIGH"|"CRITICAL",dedupeKey:string,message:string){
 const [owner]=clientId?Array.from(await db.execute(sql<OwnerRow>`select account_manager_id from clients where id=${clientId} and workspace_id=${workspaceId} limit 1`)):[];
 await db.execute(sql`insert into vivito_escalations(id,workspace_id,event_id,client_id,assigned_to_id,severity,status,dedupe_key,message) values(${crypto.randomUUID()},${workspaceId},${eventId},${clientId},${owner?.account_manager_id||null},${severity},'OPEN',${dedupeKey},${clean(message,1800)}) on conflict(workspace_id,dedupe_key) do update set severity=excluded.severity,message=excluded.message,updated_at=now() where vivito_escalations.status<>'RESOLVED'`);
}
async function scheduleOutcomes(workspaceId:string,eventId:string,baseline:JsonData){for(const h of [24,48,72])await db.execute(sql`insert into vivito_outcome_checks(id,workspace_id,event_id,horizon_hours,due_at,status,baseline) values(${crypto.randomUUID()},${workspaceId},${eventId},${h},${hours(h)},'PENDING',${jsonString(baseline)}::jsonb) on conflict(event_id,horizon_hours) do nothing`)}

async function persistProposal(input:{workspaceId:string;key:string;signalType:string;clientId:string|null;op:VivitoActionOp;args:JsonObject;evidence:JsonObject;actor:Actor;confidence?:number;expectedOutcome?:string}):Promise<ProposalResult>{
 const {workspaceId}=input;
 if(input.clientId){const [client]=Array.from(await db.execute(sql<IdRow>`select id from clients where id=${input.clientId} and workspace_id=${workspaceId} and is_active=true limit 1`));if(!client)throw new Error("direct-signal-client-out-of-scope")}
 const confidence=clamp(Number(input.confidence??0.7));
 const pre=await preflightDecision({workspaceId,clientId:input.clientId,actionOp:String(input.op),signalType:input.signalType,evidence:input.evidence,confidence,baseline:input.evidence,decisionVersion:'direct-v3'});
 const policy=decideVivitoApproval(input.op,String(input.actor.role));
 const mode=policy.mode==='BLOCK'?'BLOCK':(!pre.allowed&&policy.mode==='AUTO'?'CONFIRM':policy.mode),id=crypto.randomUUID(),learningFingerprint=fingerprint({clientId:input.clientId,signalType:input.signalType,op:input.op,evidence:input.evidence});
 const status=mode==='AUTO'?'EXECUTING':mode==='BLOCK'?'BLOCKED':'AWAITING_CONFIRMATION';
 const inserted=Array.from(await db.execute(sql<InsertedEventRow>`insert into vivito_autonomy_events(id,workspace_id,idempotency_key,signal_type,client_id,action_op,action_args,approval_mode,status,actor_id,evidence,confidence_before,evidence_quality,decision_route,simulation,policy_version,decision_version,learning_fingerprint) values(${id},${workspaceId},${input.key},${input.signalType},${input.clientId},${input.op},${jsonString(input.args)}::jsonb,${mode},${status},${input.actor.id},${jsonString(input.evidence)}::jsonb,${confidence},${pre.evidenceQuality},${pre.route.mode},${JSON.stringify(pre.simulation)}::jsonb,${pre.policyVersion},'direct-v3',${learningFingerprint}) on conflict(workspace_id,idempotency_key) do nothing returning id,status`));
 if(!inserted.length)return{duplicate:true,mode,eventId:null};
 await journal(workspaceId,id,input.clientId,input.signalType,input.op,input.evidence,mode==='AUTO'?'PROPOSED':mode==='BLOCK'?'BLOCKED':'AWAITING_CONFIRMATION',pre.allowed?policy.reason:`${pre.route.reason}; ${policy.reason}`,input.expectedOutcome,{decisionVersion:'direct-v3',evidenceQuality:pre.evidenceQuality,confidence,route:pre.route,simulation:pre.simulation});
 if(mode==='BLOCK'){await audit(workspaceId,input.actor.id,"vivito_direct_blocked",id,{op:input.op,reason:policy.reason});return{duplicate:false,mode,eventId:id}}
 if(mode!=='AUTO'){
  await notifyTargets(workspaceId,input.clientId,`VIVITO approval needed · ${input.op}`,`${pre.allowed?policy.reason:`${pre.route.reason}; human review required`}\nSignal: ${input.signalType}\nEvidence: ${clean(JSON.stringify(input.evidence),900)}`,policy.risk==='high'?"high":"normal",`approval:${id}`);
  await audit(workspaceId,input.actor.id,"vivito_direct_confirmation_queued",id,{op:input.op,policy:{mode:policy.mode,risk:policy.risk,reason:policy.reason},preflight:{mode:pre.route.mode,reason:pre.route.reason}});return{duplicate:false,mode,eventId:id};
 }
 try{
  await assertAutonomyAllowed({workspaceId,clientId:input.clientId,actionOp:String(input.op)});await consumeResource(workspaceId,'ACTION',1);
  await db.execute(sql`update vivito_autonomy_events set last_attempt_at=now() where id=${id} and workspace_id=${workspaceId}`);
  const result=await execute(input.op,input.args,input.actor.role,input.actor.id,workspaceId);
  await db.execute(sql`update vivito_autonomy_events set status='EXECUTED',execution_result=${JSON.stringify(result)}::jsonb,executed_at=now(),updated_at=now() where id=${id} and workspace_id=${workspaceId}`);await updateJournal(workspaceId,id,"EXECUTED");
  await scheduleOutcomes(workspaceId,id,{signalType:input.signalType,evidence:input.evidence,result:result as JsonData,confidence});
  const resultMessage=result&&typeof result==="object"&&"message" in result?clean(result.message,700):"Safe AUTO action completed.";
  await notifyTargets(workspaceId,input.clientId,`VIVITO acted automatically · ${input.op}`,`${resultMessage}\nEvidence: ${clean(JSON.stringify(input.evidence),800)}`,"normal",`executed:${id}`);await audit(workspaceId,input.actor.id,"vivito_direct_auto_executed",id,{op:input.op,result:result as JsonData});return{duplicate:false,mode,eventId:id,executed:true};
 }catch(error){const msg=errorText(error);await db.execute(sql`update vivito_autonomy_events set status='RETRY_SCHEDULED',retry_count=1,next_retry_at=${hours(1)},last_error=${msg},last_attempt_at=now(),updated_at=now() where id=${id} and workspace_id=${workspaceId}`);await updateJournal(workspaceId,id,"RETRY_SCHEDULED");await audit(workspaceId,input.actor.id,"vivito_direct_retry_scheduled",id,{op:input.op,error:msg});return{duplicate:false,mode,eventId:id,executed:false,retryScheduled:true}}
}

function competitorSignals(report:CompetitorReportRow):CompetitorSignal[]{const data=parseJson(report.report_json),details=Array.isArray(data.details)?data.details:[];return details.flatMap(raw=>{const d=asObject(raw);if(d.error)return[];const newPosts=Array.isArray(d.newPosts)?d.newPosts.length:0,delta=asObject(d.delta),fd=delta.followers==null?null:Number(delta.followers);if(newPosts<2&&(fd==null||Math.abs(fd)<50))return[];return[{competitor:clean(d.competitor,160)||"Competitor",newPosts,followerDelta:fd,profileUrl:clean(d.profileUrl,900),source:clean(d.source,160)||'PUBLIC_MONITOR'}]})}
async function collectAndAct(actor:Actor){const workspaceId=actor.workspace_id;let signals=0,autoExecuted=0,queued=0;
 const reports=Array.from(await db.execute(sql<CompetitorReportRow>`select r.client_id,r.report_date,r.report_json,c.company_name from competitor_daily_reports r join clients c on c.id=r.client_id and c.workspace_id=r.workspace_id where r.workspace_id=${workspaceId} and r.report_date>=current_date-1 and c.is_active=true order by r.created_at desc limit 100`));const seen=new Set<string>();
 for(const r of reports){if(seen.has(r.client_id))continue;seen.add(r.client_id);for(const s of competitorSignals(r)){signals++;const p=await persistProposal({workspaceId,key:`competitor:${r.client_id}:${s.competitor}:${day()}`,signalType:"COMPETITOR_SURGE",clientId:r.client_id,op:"create_task",args:{clientName:r.company_name,title:`Competitor response brief — ${s.competitor}`,brief:`VIVITO detected an observed public competitor move. Review evidence, identify implication and prepare a differentiated response. Evidence: ${s.newPosts} new post(s); follower delta: ${s.followerDelta??"unavailable"}; source: ${s.profileUrl||"public monitored profile"}.`,deadline:new Date(Date.now()+48*3600000).toISOString(),type:"GRAPHIC",priority:"HIGH"},evidence:{...s,sources:[s.profileUrl||s.source],observed:true},actor,confidence:0.78,expectedOutcome:"A reviewed response brief is created within 48 hours."});if(p.executed)autoExecuted++;else if(!p.duplicate&&["CONFIRM","SUPER_ADMIN_CONFIRM"].includes(p.mode))queued++}}
 const overdue=Array.from(await db.execute(sql<OverdueRow>`select t.id,t.client_id,t.title,t.deadline,c.company_name from creative_tasks t join clients c on c.id=t.client_id and c.workspace_id=t.workspace_id where t.workspace_id=${workspaceId} and c.is_active=true and t.deadline<now() and t.status not in ('COMPLETED','REJECTED') and t.archived_at is null order by t.deadline asc limit 100`));
 for(const t of overdue){signals++;const age=Math.max(1,Math.floor((Date.now()-new Date(t.deadline).getTime())/86400000));await escalate(workspaceId,null,t.client_id,age>=3?"HIGH":"MEDIUM",`overdue:${t.id}:${day()}`,`Task “${clean(t.title,180)}” is ${age} day(s) overdue.`);await notifyTargets(workspaceId,t.client_id,"VIVITO delivery risk",`Task “${clean(t.title,180)}” is overdue by ${age} day(s). Review owner, blocker and next action.`,age>=3?"high":"normal",`overdue:${t.id}:${day()}`)}
 const risky=Array.from(await db.execute(sql<RiskRow>`select id,company_name,health_score,churn_risk,churn_probability from clients where workspace_id=${workspaceId} and is_active=true and (coalesce(health_score,100)<60 or churn_risk in ('HIGH','CRITICAL') or coalesce(churn_probability,0)>=0.6) limit 100`));
 for(const c of risky){signals++;await escalate(workspaceId,null,c.id,"HIGH",`client-risk:${c.id}:${day()}`,`Client risk observed: health ${c.health_score}; churn risk ${c.churn_risk}; probability ${c.churn_probability}.`);await journal(workspaceId,null,c.id,"CLIENT_HEALTH_RISK","review_client_health",{id:c.id,companyName:c.company_name,healthScore:c.health_score===null?null:Number(c.health_score),churnRisk:c.churn_risk,churnProbability:c.churn_probability===null?null:Number(c.churn_probability)},"PROPOSED","Observed client-health fields crossed the internal risk threshold.","Account owner reviews causes and corrective actions.")}
 const invoices=Array.from(await db.execute(sql<InvoiceRow>`select f.id,f.client_id,f.invoice_number,f.outstanding,f.due_date from finance_records f join clients c on c.id=f.client_id and c.workspace_id=f.workspace_id where f.workspace_id=${workspaceId} and c.is_active=true and coalesce(f.outstanding,0)>0 and f.due_date<now() order by f.due_date asc limit 100`));
 for(const f of invoices){signals++;await escalate(workspaceId,null,f.client_id,"HIGH",`invoice-overdue:${f.id}:${day()}`,`Outstanding invoice ${f.invoice_number||f.id} is overdue. Amount due: ${Number(f.outstanding||0)}.`)}
 const media=Array.from(await db.execute(sql<MediaRow>`select c.id client_id,c.company_name,ac.id campaign_id,ac.name campaign_name,coalesce(sum(p.spend),0)::float spend,coalesce(sum(p.results),0)::float results,coalesce(sum(p.revenue),0)::float revenue from ad_campaigns ac join clients c on c.id=ac.client_id and c.workspace_id=ac.workspace_id left join ad_performance_daily p on p.campaign_id=ac.id and p.date>=now()-interval '24 hours' and p.breakdown_type='TOTAL' and p.ad_set_id is null and p.ad_id is null where ac.workspace_id=${workspaceId} and c.is_active=true and ac.archived_at is null group by c.id,c.company_name,ac.id,ac.name having coalesce(sum(p.spend),0)>=500 order by spend desc limit 100`));
 for(const m of media){const spend=Number(m.spend||0),results=Number(m.results||0);if(results>0)continue;signals++;const evidence:JsonObject={campaignId:m.campaign_id,campaign:m.campaign_name,spend24h:spend,results24h:results,revenue24h:Number(m.revenue||0),sources:[`internal:ad_performance_daily:${m.campaign_id}`],observed:true};const sync=await persistProposal({workspaceId,key:`media-sync:${m.campaign_id}:${day()}`,signalType:"MEDIA_ZERO_RESULT_SPEND",clientId:m.client_id,op:"sync_campaign",args:{campaignId:m.campaign_id},evidence,actor,confidence:0.9,expectedOutcome:"Refresh internal campaign evidence before any optimization decision."});if(sync.executed)autoExecuted++;if(spend>=1000){const pause=await persistProposal({workspaceId,key:`media-pause-review:${m.campaign_id}:${day()}`,signalType:"MEDIA_ZERO_RESULT_HIGH_SPEND",clientId:m.client_id,op:"update_campaign",args:{campaignId:m.campaign_id,status:"PAUSED"},evidence:{...evidence,recommendation:"Pause requires human confirmation; no automatic provider mutation."},actor,confidence:0.82,expectedOutcome:"Human reviews a high-spend zero-result campaign before a status change."});if(!pause.duplicate&&["CONFIRM","SUPER_ADMIN_CONFIRM"].includes(pause.mode))queued++}}
 return{signals,autoExecuted,queued}}

async function retryDue(actor:Actor){const workspaceId=actor.workspace_id,due=Array.from(await db.execute(sql<EventRow>`select id,workspace_id,client_id,signal_type,action_op,action_args,approval_mode,status,actor_id,evidence,execution_result,confidence_before,evidence_quality,decision_route,retry_count,max_retries from vivito_autonomy_events where workspace_id=${workspaceId} and status='RETRY_SCHEDULED' and next_retry_at<=now() and retry_count<max_retries order by next_retry_at limit 50`));let retried=0;for(const event of due){try{if(String(event.decision_route||'POLICY')!=='POLICY'||Number(event.evidence_quality||0)<.5){await db.execute(sql`update vivito_autonomy_events set status='AWAITING_CONFIRMATION',approval_mode='CONFIRM',next_retry_at=null,updated_at=now() where id=${event.id} and workspace_id=${workspaceId}`);await updateJournal(workspaceId,event.id,'AWAITING_CONFIRMATION');continue}const op=String(event.action_op) as VivitoActionOp;await assertAutonomyAllowed({workspaceId,clientId:event.client_id,actionOp:op});await consumeResource(workspaceId,'ACTION',1);const result=await execute(op,parseJson(event.action_args),actor.role,actor.id,workspaceId);await db.execute(sql`update vivito_autonomy_events set status='EXECUTED',execution_result=${JSON.stringify(result)}::jsonb,executed_at=now(),last_attempt_at=now(),next_retry_at=null,updated_at=now() where id=${event.id} and workspace_id=${workspaceId}`);await updateJournal(workspaceId,event.id,"EXECUTED");await scheduleOutcomes(workspaceId,event.id,{signalType:event.signal_type,evidence:parseJson(event.evidence),result:result as JsonData,confidence:Number(event.confidence_before||0.6)});retried++}catch(error){const next=Number(event.retry_count||0)+1,terminal=next>=Number(event.max_retries||3);await db.execute(sql`update vivito_autonomy_events set retry_count=${next},status=${terminal?'FAILED':'RETRY_SCHEDULED'},next_retry_at=${terminal?null:hours(Math.min(6,next*2))},last_attempt_at=now(),last_error=${errorText(error)},updated_at=now() where id=${event.id} and workspace_id=${workspaceId}`);await updateJournal(workspaceId,event.id,terminal?"FAILED":"RETRY_SCHEDULED");if(terminal)await escalate(workspaceId,event.id,event.client_id,"HIGH",`retry-exhausted:${event.id}`,`VIVITO safe action exhausted ${next} attempts and requires review.`)}}return retried}

async function observe(workspaceId:string,event:ObserveInput):Promise<ObservedOutcome>{const op=event.action_op,args=parseJson(event.action_args),baseline=parseJson(event.baseline);if(op==="create_task"){const id=clean(parseJson(event.execution_result).entityId,120);const [task]=id?Array.from(await db.execute(sql<TaskOutcomeRow>`select id,status,completed_at,updated_at from creative_tasks where id=${id} and workspace_id=${workspaceId} limit 1`)):[];return{kind:"TASK",entityId:id,status:task?.status||"MISSING",completedAt:task?.completed_at||null}}
 if(["sync_campaign","update_campaign"].includes(op)){const id=clean(args.campaignId||parseJson(event.evidence).campaignId,120);const [media]=id?Array.from(await db.execute(sql<MediaOutcomeRow>`select ac.id,ac.status,coalesce(sum(p.spend),0)::float spend,coalesce(sum(p.results),0)::float results,coalesce(sum(p.revenue),0)::float revenue from ad_campaigns ac left join ad_performance_daily p on p.campaign_id=ac.id and p.date>=now()-interval '24 hours' and p.breakdown_type='TOTAL' and p.ad_set_id is null and p.ad_id is null where ac.id=${id} and ac.workspace_id=${workspaceId} group by ac.id,ac.status`)):[];return{kind:"MEDIA",campaignId:id,status:media?.status||"MISSING",spend24h:Number(media?.spend||0),results24h:Number(media?.results||0),revenue24h:Number(media?.revenue||0),baseline}}
 return{kind:"GENERIC",baseline}}
async function checkOutcomes(actor:Actor){const workspaceId=actor.workspace_id,due=Array.from(await db.execute(sql<OutcomeDueRow>`select o.id,o.event_id,o.horizon_hours,o.baseline,e.action_op,e.action_args,e.evidence,e.execution_result,e.client_id,e.confidence_before from vivito_outcome_checks o join vivito_autonomy_events e on e.id=o.event_id and e.workspace_id=o.workspace_id where o.workspace_id=${workspaceId} and o.status='PENDING' and o.due_at<=now() and e.status='EXECUTED' order by o.due_at limit 100`));let checked=0;for(const x of due){try{const observed=await observe(workspaceId,x);let state="OPEN",assessment="Observed outcome recorded; no causal attribution is assumed.",delta=-0.02;if(observed.kind==="TASK"){state=observed.status==="COMPLETED"?"SUCCESS":"OPEN";assessment=state==="SUCCESS"?"Operational follow-through completed.":"Operational follow-through is still open.";delta=state==="SUCCESS"?0.08:-0.03}if(observed.kind==="MEDIA"){state=observed.results24h>0?"IMPROVED":"NEEDS_REVIEW";assessment=state==="IMPROVED"?"Results are observable after the action window; causality is not assumed.":"Zero-result spend signal still persists; escalate for review.";delta=state==="IMPROVED"?0.05:-0.08}const before=clamp(Number(x.confidence_before||0.6)),after=clamp(before+delta);await db.execute(sql`update vivito_outcome_checks set status='CHECKED',checked_at=now(),observed=${JSON.stringify(observed)}::jsonb,assessment=${assessment} where id=${x.id} and workspace_id=${workspaceId}`);await db.execute(sql`update vivito_autonomy_events set outcome_state=${state},confidence_after=${after},updated_at=now() where id=${x.event_id} and workspace_id=${workspaceId}`);await db.execute(sql`insert into vivito_learning_signals(id,workspace_id,event_id,kind,text,scope_type,scope_id,source,evidence,outcome_state,confidence,lesson) values(${crypto.randomUUID()},${workspaceId},${x.event_id},'OUTCOME',${`VIVITO ${x.horizon_hours}h outcome: ${assessment}`},'CLIENT',${x.client_id||null},'DIRECT_OPERATOR',${JSON.stringify({eventId:x.event_id,observed})}::jsonb,${state},${after},${state==='SUCCESS'||state==='IMPROVED'?'Retain the bounded decision pattern; continue measurement.':'Do not scale this decision from this observation; require review or more evidence.'})`);await updateJournal(workspaceId,x.event_id,"CHECKED",observed);if(observed.kind==='MEDIA')await recordValue(workspaceId,x.event_id,observed.spend24h,observed.revenue24h,'EGP',`OUTCOME_${x.horizon_hours}H`);else await recordValue(workspaceId,x.event_id,0,state==='SUCCESS'?1:0,'EGP',`OUTCOME_${x.horizon_hours}H`);if(state==="NEEDS_REVIEW")await escalate(workspaceId,x.event_id,x.client_id,"HIGH",`outcome-persists:${x.event_id}:${x.horizon_hours}`,assessment);checked++}catch(error){await db.execute(sql`update vivito_outcome_checks set status='ERROR',checked_at=now(),assessment=${errorText(error)} where id=${x.id} and workspace_id=${workspaceId}`)}}return checked}

export async function runVivitoDirectCycle():Promise<DirectCycleResult>{const errors:string[]=[];let signals=0,autoExecuted=0,queued=0,retried=0,outcomesChecked=0;try{await ensureSchema();const actor=await systemActor();await assertAutonomyAllowed({workspaceId:actor.workspace_id});retried=await retryDue(actor);const cycle=await collectAndAct(actor);signals=cycle.signals;autoExecuted=cycle.autoExecuted;queued=cycle.queued;outcomesChecked=await checkOutcomes(actor);return{ok:true,workspaceId:actor.workspace_id,signals,autoExecuted,queued,retried,outcomesChecked,errors}}catch(error){errors.push(errorText(error));return{ok:false,signals,autoExecuted,queued,retried,outcomesChecked,errors}}}

async function scopedEvent(eventId:string,workspaceId:string,role:string,userId:string):Promise<EventRow>{
 const query=role==="SUPER_ADMIN"
  ?sql<EventRow>`select e.id,e.workspace_id,e.client_id,e.signal_type,e.action_op,e.action_args,e.approval_mode,e.status,e.actor_id,e.evidence,e.execution_result,e.confidence_before,e.evidence_quality,e.decision_route,e.retry_count,e.max_retries from vivito_autonomy_events e where e.id=${eventId} and e.workspace_id=${workspaceId} limit 1`
  :role==="ACCOUNT_MANAGER"
   ?sql<EventRow>`select e.id,e.workspace_id,e.client_id,e.signal_type,e.action_op,e.action_args,e.approval_mode,e.status,e.actor_id,e.evidence,e.execution_result,e.confidence_before,e.evidence_quality,e.decision_route,e.retry_count,e.max_retries from vivito_autonomy_events e join clients c on c.id=e.client_id and c.workspace_id=e.workspace_id where e.id=${eventId} and e.workspace_id=${workspaceId} and c.account_manager_id=${userId} limit 1`
   :role==="MEDIA_BUYER"
    ?sql<EventRow>`select e.id,e.workspace_id,e.client_id,e.signal_type,e.action_op,e.action_args,e.approval_mode,e.status,e.actor_id,e.evidence,e.execution_result,e.confidence_before,e.evidence_quality,e.decision_route,e.retry_count,e.max_retries from vivito_autonomy_events e join clients c on c.id=e.client_id and c.workspace_id=e.workspace_id where e.id=${eventId} and e.workspace_id=${workspaceId} and c.media_buyer_id=${userId} limit 1`
    :null;
 if(!query)throw new Error("direct-event-role-not-authorized");const [event]=Array.from(await db.execute(query));if(!event)throw new Error("direct-event-not-found-or-out-of-scope");return event;
}
export async function decideVivitoDirectEvent(eventId:string,decision:"approve"|"reject",reason:string,role:string,userId:string,workspaceId:string){await ensureSchema();const event=await scopedEvent(eventId,workspaceId,role,userId);if(event.status!=="AWAITING_CONFIRMATION")throw new Error("direct-event-not-awaiting-confirmation");if(decision==="reject"){await db.execute(sql`update vivito_autonomy_events set status='REJECTED',rejected_by=${userId},rejected_at=now(),rejection_reason=${clean(reason,1200)},updated_at=now() where id=${eventId} and workspace_id=${workspaceId} and status='AWAITING_CONFIRMATION'`);await db.execute(sql`insert into vivito_approval_events(id,workspace_id,event_id,actor_id,decision,reason) values(${crypto.randomUUID()},${workspaceId},${eventId},${userId},'REJECTED',${clean(reason,1200)})`);await updateJournal(workspaceId,eventId,"REJECTED");await audit(workspaceId,userId,"vivito_direct_rejected",eventId,{op:event.action_op,reason:clean(reason,1200)});return{ok:true,status:"REJECTED"}}
 const op=event.action_op as VivitoActionOp,approval=decideVivitoApproval(op,role);if(approval.mode==="BLOCK"||approval.mode==="AUTO")throw new Error("direct-event-confirmation-policy-mismatch");if(approval.mode==="SUPER_ADMIN_CONFIRM"&&role!=="SUPER_ADMIN")throw new Error("super-admin-confirmation-required");try{await assertAutonomyAllowed({workspaceId,clientId:event.client_id,actionOp:op});await consumeResource(workspaceId,'ACTION',1);const result=await execute(op,parseJson(event.action_args),role,userId,workspaceId);await db.execute(sql`update vivito_autonomy_events set status='EXECUTED',execution_result=${JSON.stringify(result)}::jsonb,confirmed_by=${userId},confirmed_at=now(),executed_at=now(),last_attempt_at=now(),updated_at=now() where id=${eventId} and workspace_id=${workspaceId} and status='AWAITING_CONFIRMATION'`);await db.execute(sql`insert into vivito_approval_events(id,workspace_id,event_id,actor_id,decision,reason) values(${crypto.randomUUID()},${workspaceId},${eventId},${userId},'APPROVED',${clean(reason,1200)})`);await scheduleOutcomes(workspaceId,eventId,{signalType:event.signal_type,evidence:parseJson(event.evidence),result:result as JsonData,confidence:Number(event.confidence_before||0.7)});await updateJournal(workspaceId,eventId,"EXECUTED");await audit(workspaceId,userId,"vivito_direct_confirmed_executed",eventId,{op,result:result as JsonData});return{ok:true,status:"EXECUTED",result}}catch(error){await db.execute(sql`update vivito_autonomy_events set status='FAILED',confirmed_by=${userId},confirmed_at=now(),last_error=${errorText(error)},last_attempt_at=now(),updated_at=now() where id=${eventId} and workspace_id=${workspaceId}`);await updateJournal(workspaceId,eventId,"FAILED");throw error}}
export async function confirmVivitoDirectEvent(eventId:string,role:string,userId:string,workspaceId?:string){return decideVivitoDirectEvent(eventId,"approve","Explicit confirmation",role,userId,workspaceId||await resolveVivitoWorkspaceForUser(userId))}

export async function markVivitoDirectRollback(input:{eventId:string;workspaceId:string;role:string;userId:string;rollbackResult:JsonData}){if(input.role!=="SUPER_ADMIN")throw new Error('super-admin-required');const event=await scopedEvent(input.eventId,input.workspaceId,input.role,input.userId);if(event.status!=='EXECUTED')throw new Error('direct-event-not-executed');await db.execute(sql`update vivito_autonomy_events set status='ROLLED_BACK',rolled_back_at=now(),rolled_back_by=${input.userId},rollback_result=${jsonString(input.rollbackResult)}::jsonb,updated_at=now() where id=${input.eventId} and workspace_id=${input.workspaceId} and status='EXECUTED'`);await updateJournal(input.workspaceId,input.eventId,'CHECKED',{rolledBack:true,result:input.rollbackResult});await audit(input.workspaceId,input.userId,'vivito_direct_rolled_back',input.eventId,{result:input.rollbackResult});return{ok:true,status:'ROLLED_BACK'}}
