import {db,sql,notifications,auditLogs} from "@/lib/db";
import {decideVivitoApproval} from "./approval-policy";
import {executeVivitoAction} from "./executor";
import {executeVivitoOperatorAction,isVivitoOperatorAction} from "./executor-operator";
import type {VivitoActionOp} from "./action-engine";

const W="default";
const rows=(v:any)=>Array.from(v as any) as any[];
const j=(v:any)=>{try{return typeof v==="string"?JSON.parse(v):v||{}}catch{return{}}};
const clean=(v:any,n=1000)=>String(v??"").replace(/\s+/g," ").trim().slice(0,n);
const hours=(n:number)=>new Date(Date.now()+n*3600000);
const day=()=>new Date().toISOString().slice(0,10);

export type DirectCycleResult={ok:boolean;signals:number;autoExecuted:number;queued:number;outcomesChecked:number;errors:string[]};

async function ensureSchema(){const [r]=rows(await db.execute(sql`select to_regclass('public.vivito_autonomy_events') e,to_regclass('public.vivito_outcome_checks') o,to_regclass('public.vivito_learning_signals') l`));if(!r?.e||!r?.o||!r?.l)throw new Error("vivito-direct-schema-not-ready")}
async function systemActor(){const id=clean(process.env.VIVITO_AUTONOMY_ACTOR_ID,120);if(!id)throw new Error("vivito-autonomy-actor-not-configured");const a=rows(await db.execute(sql`select id,name,role from users where id=${id} and workspace_id=${W} and role='SUPER_ADMIN' and is_active=true and approval_status='APPROVED' limit 1`))[0];if(!a)throw new Error("vivito-autonomy-actor-invalid");return a}
async function execute(op:VivitoActionOp,args:any,role:string,userId:string){return isVivitoOperatorAction(op)?executeVivitoOperatorAction(op,args,role,userId):executeVivitoAction(op,args,role,userId)}
async function audit(userId:string,action:string,entityId:string,payload:any){await db.insert(auditLogs).values({workspaceId:W,userId,action,entity:"VIVITO_DIRECT",entityId,newValues:JSON.stringify(payload)} as any)}

async function notifyTargets(clientId:string|null,title:string,message:string,priority="normal"){
 const targets=clientId?rows(await db.execute(sql`select id from users where workspace_id=${W} and is_active=true and (role='SUPER_ADMIN' or id=(select account_manager_id from clients where id=${clientId}) or id=(select media_buyer_id from clients where id=${clientId}))`)):rows(await db.execute(sql`select id from users where workspace_id=${W} and role='SUPER_ADMIN' and is_active=true`));
 for(const u of targets)await db.insert(notifications).values({userId:String(u.id),type:"GENERAL",priority,title,message:message.slice(0,1800),link:clientId?`/dashboard/clients/${clientId}`:"/dashboard/ai-studio"} as any).onConflictDoNothing();
}

async function scheduleOutcomes(eventId:string,baseline:any){for(const h of [24,48,72])await db.execute(sql`insert into vivito_outcome_checks(id,workspace_id,event_id,horizon_hours,due_at,status,baseline) values(${crypto.randomUUID()},${W},${eventId},${h},${hours(h)},'PENDING',${JSON.stringify(baseline)}::jsonb) on conflict(event_id,horizon_hours) do nothing`)}

async function persistProposal(input:{key:string;signalType:string;clientId:string|null;op:VivitoActionOp;args:any;evidence:any;actor:any}){
 const approval=decideVivitoApproval(input.op,String(input.actor.role));
 const id=crypto.randomUUID();
 const inserted=rows(await db.execute(sql`insert into vivito_autonomy_events(id,workspace_id,idempotency_key,signal_type,client_id,action_op,action_args,approval_mode,status,actor_id,evidence) values(${id},${W},${input.key},${input.signalType},${input.clientId},${input.op},${JSON.stringify(input.args)}::jsonb,${approval.mode},${approval.mode==='AUTO'?'EXECUTING':approval.mode==='BLOCK'?'BLOCKED':'AWAITING_CONFIRMATION'},${String(input.actor.id)},${JSON.stringify(input.evidence)}::jsonb) on conflict(idempotency_key) do nothing returning id,status`));
 if(!inserted.length)return{duplicate:true,mode:approval.mode,eventId:null};
 if(approval.mode==="BLOCK"){await audit(String(input.actor.id),"vivito_direct_blocked",id,{op:input.op,reason:approval.reason});return{duplicate:false,mode:approval.mode,eventId:id}}
 if(approval.mode!=="AUTO"){
  await notifyTargets(input.clientId,`VIVITO approval needed · ${input.op}`,`${approval.reason}\nSignal: ${input.signalType}\nEvidence: ${clean(JSON.stringify(input.evidence),900)}`,approval.risk==="high"?"high":"normal");
  await audit(String(input.actor.id),"vivito_direct_confirmation_queued",id,{op:input.op,approval});
  return{duplicate:false,mode:approval.mode,eventId:id};
 }
 try{
  const result=await execute(input.op,input.args,String(input.actor.role),String(input.actor.id));
  await db.execute(sql`update vivito_autonomy_events set status='EXECUTED',execution_result=${JSON.stringify(result)}::jsonb,executed_at=now(),updated_at=now() where id=${id}`);
  await scheduleOutcomes(id,{signalType:input.signalType,evidence:input.evidence,result});
  await notifyTargets(input.clientId,`VIVITO acted automatically · ${input.op}`,`${clean((result as any)?.message||"Safe AUTO action completed.",700)}\nEvidence: ${clean(JSON.stringify(input.evidence),800)}`);
  await audit(String(input.actor.id),"vivito_direct_auto_executed",id,{op:input.op,result});
  return{duplicate:false,mode:approval.mode,eventId:id,executed:true};
 }catch(e:any){const msg=clean(e?.message||e,900);await db.execute(sql`update vivito_autonomy_events set status='FAILED',last_error=${msg},updated_at=now() where id=${id}`);await audit(String(input.actor.id),"vivito_direct_auto_failed",id,{op:input.op,error:msg});throw e}
}

function competitorSignals(report:any){const data=j(report.report_json),details=Array.isArray(data.details)?data.details:[];return details.flatMap((d:any)=>{if(d?.error)return[];const newPosts=Array.isArray(d?.newPosts)?d.newPosts.length:0,fd=d?.delta?.followers==null?null:Number(d.delta.followers);if(newPosts<2&&(fd==null||Math.abs(fd)<50))return[];return[{competitor:clean(d.competitor,160)||"Competitor",newPosts,followerDelta:fd,profileUrl:clean(d.profileUrl,900)}]})}

async function collectAndAct(actor:any){let signals=0,autoExecuted=0,queued=0;
 const reports=rows(await db.execute(sql`select r.client_id,r.report_date,r.report_json,c.company_name from competitor_daily_reports r join clients c on c.id=r.client_id where r.workspace_id=${W} and r.report_date>=current_date-1 and c.is_active=true order by r.created_at desc limit 100`));
 const seen=new Set<string>();
 for(const r of reports){if(seen.has(String(r.client_id)))continue;seen.add(String(r.client_id));for(const s of competitorSignals(r)){signals++;const deadline=new Date(Date.now()+48*3600000).toISOString();const key=`competitor:${r.client_id}:${s.competitor}:${day()}`;const p=await persistProposal({key,signalType:"COMPETITOR_SURGE",clientId:String(r.client_id),op:"create_task",args:{clientName:String(r.company_name),title:`Competitor response brief — ${s.competitor}`,brief:`VIVITO detected a public competitor move. Review the observed evidence, identify the strategic implication, and prepare a response brief without copying the competitor. Public evidence: ${s.newPosts} new post(s); follower delta: ${s.followerDelta??"unavailable"}; source: ${s.profileUrl||"public monitored profile"}.`,deadline,type:"GRAPHIC",priority:"HIGH"},evidence:s,actor});if((p as any).executed)autoExecuted++;else if(!(p as any).duplicate&&["CONFIRM","SUPER_ADMIN_CONFIRM"].includes(String((p as any).mode)))queued++}}
 const media=rows(await db.execute(sql`select c.id client_id,c.company_name,ac.id campaign_id,ac.name campaign_name,coalesce(sum(p.spend),0)::float spend,coalesce(sum(p.results),0)::float results,coalesce(sum(p.revenue),0)::float revenue from ad_campaigns ac join clients c on c.id=ac.client_id left join ad_performance_daily p on p.campaign_id=ac.id and p.date>=now()-interval '24 hours' and p.breakdown_type='TOTAL' and p.ad_set_id is null and p.ad_id is null where ac.workspace_id=${W} and c.workspace_id=${W} and c.is_active=true and ac.archived_at is null group by c.id,c.company_name,ac.id,ac.name having coalesce(sum(p.spend),0)>=500 order by spend desc limit 100`));
 for(const m of media){const spend=Number(m.spend||0),results=Number(m.results||0);if(results>0)continue;signals++;const evidence={campaignId:m.campaign_id,campaign:m.campaign_name,spend24h:spend,results24h:results,revenue24h:Number(m.revenue||0)};const sync=await persistProposal({key:`media-sync:${m.campaign_id}:${day()}`,signalType:"MEDIA_ZERO_RESULT_SPEND",clientId:String(m.client_id),op:"sync_campaign",args:{campaignId:String(m.campaign_id)},evidence,actor});if((sync as any).executed)autoExecuted++;if(spend>=1000){const pause=await persistProposal({key:`media-pause-review:${m.campaign_id}:${day()}`,signalType:"MEDIA_ZERO_RESULT_HIGH_SPEND",clientId:String(m.client_id),op:"update_campaign",args:{campaignId:String(m.campaign_id),status:"PAUSED"},evidence:{...evidence,recommendation:"Pause requires human confirmation; no automatic budget/status mutation."},actor});if(!(pause as any).duplicate&&["CONFIRM","SUPER_ADMIN_CONFIRM"].includes(String((pause as any).mode)))queued++}}
 return{signals,autoExecuted,queued}}

async function observe(event:any){const op=String(event.action_op),args=j(event.action_args),baseline=j(event.baseline);if(op==="create_task"){const id=String(j(event.execution_result)?.entityId||"");const t=id?rows(await db.execute(sql`select id,status,completed_at,updated_at from creative_tasks where id=${id} limit 1`))[0]:null;return{kind:"TASK",entityId:id,status:t?.status||"MISSING",completedAt:t?.completed_at||null}}
 if(["sync_campaign","update_campaign"].includes(op)){const id=String(args.campaignId||j(event.evidence)?.campaignId||"");const m=id?rows(await db.execute(sql`select ac.id,ac.status,coalesce(sum(p.spend),0)::float spend,coalesce(sum(p.results),0)::float results,coalesce(sum(p.revenue),0)::float revenue from ad_campaigns ac left join ad_performance_daily p on p.campaign_id=ac.id and p.date>=now()-interval '24 hours' and p.breakdown_type='TOTAL' and p.ad_set_id is null and p.ad_id is null where ac.id=${id} group by ac.id,ac.status`))[0]:null;return{kind:"MEDIA",campaignId:id,status:m?.status||"MISSING",spend24h:Number(m?.spend||0),results24h:Number(m?.results||0),revenue24h:Number(m?.revenue||0),baseline}}
 return{kind:"GENERIC",baseline}}

async function checkOutcomes(actor:any){const due=rows(await db.execute(sql`select o.id,o.event_id,o.horizon_hours,o.baseline,e.action_op,e.action_args,e.evidence,e.execution_result,e.client_id from vivito_outcome_checks o join vivito_autonomy_events e on e.id=o.event_id where o.workspace_id=${W} and o.status='PENDING' and o.due_at<=now() and e.status='EXECUTED' order by o.due_at limit 100`));let checked=0;for(const x of due){try{const observed=await observe(x);let assessment="Observed outcome recorded; no causal claim.";if(observed.kind==="TASK")assessment=observed.status==="COMPLETED"?"Operational follow-through completed.":"Operational follow-through is still open.";if(observed.kind==="MEDIA")assessment=Number(observed.results24h)>0?"Results are now observable after the action window; attribution is not assumed.":"Zero-result spend signal still persists; escalate for review.";await db.execute(sql`update vivito_outcome_checks set status='CHECKED',checked_at=now(),observed=${JSON.stringify(observed)}::jsonb,assessment=${assessment} where id=${String(x.id)}`);await db.execute(sql`insert into vivito_learning_signals(id,workspace_id,kind,text,scope_type,scope_id,source,evidence) values(${crypto.randomUUID()},${W},'OUTCOME',${`VIVITO ${x.horizon_hours}h outcome: ${assessment}`},'CLIENT',${x.client_id||null},'DIRECT_OPERATOR',${JSON.stringify({eventId:x.event_id,observed})}::jsonb)`);if(assessment.includes("persists"))await notifyTargets(x.client_id?String(x.client_id):null,"VIVITO escalation · signal persists",assessment,"high");checked++}catch(e:any){await db.execute(sql`update vivito_outcome_checks set status='ERROR',checked_at=now(),assessment=${clean(e?.message||e,900)} where id=${String(x.id)}`)}}return checked}

export async function runVivitoDirectCycle():Promise<DirectCycleResult>{const errors:string[]=[];let signals=0,autoExecuted=0,queued=0,outcomesChecked=0;try{await ensureSchema();const actor=await systemActor();const a=await collectAndAct(actor);signals=a.signals;autoExecuted=a.autoExecuted;queued=a.queued;outcomesChecked=await checkOutcomes(actor);return{ok:true,signals,autoExecuted,queued,outcomesChecked,errors}}catch(e:any){errors.push(clean(e?.message||e,900));return{ok:false,signals,autoExecuted,queued,outcomesChecked,errors}}}

export async function confirmVivitoDirectEvent(eventId:string,role:string,userId:string){await ensureSchema();const e=rows(await db.execute(sql`select * from vivito_autonomy_events where id=${eventId} and workspace_id=${W} limit 1`))[0];if(!e)throw new Error("direct-event-not-found");if(!["AWAITING_CONFIRMATION"].includes(String(e.status)))throw new Error("direct-event-not-awaiting-confirmation");const op=String(e.action_op) as VivitoActionOp,approval=decideVivitoApproval(op,role);if(approval.mode==="BLOCK"||approval.mode==="AUTO")throw new Error("direct-event-confirmation-policy-mismatch");if(approval.mode==="SUPER_ADMIN_CONFIRM"&&role!=="SUPER_ADMIN")throw new Error("super-admin-confirmation-required");const args=j(e.action_args);try{const result=await execute(op,args,role,userId);await db.execute(sql`update vivito_autonomy_events set status='EXECUTED',execution_result=${JSON.stringify(result)}::jsonb,confirmed_by=${userId},confirmed_at=now(),executed_at=now(),updated_at=now() where id=${eventId} and status='AWAITING_CONFIRMATION'`);await scheduleOutcomes(eventId,{signalType:e.signal_type,evidence:j(e.evidence),result});await audit(userId,"vivito_direct_confirmed_executed",eventId,{op,result});return{ok:true,result}}catch(err:any){await db.execute(sql`update vivito_autonomy_events set status='FAILED',confirmed_by=${userId},confirmed_at=now(),last_error=${clean(err?.message||err,900)},updated_at=now() where id=${eventId}`);throw err}}
