import {db,sql} from "@/lib/db";
const W="default"; const rows=(x:any)=>Array.from(x as any) as any[];
export type Scope={clientId?:string|null;actionOp?:string|null};
export async function assertAutonomyAllowed(scope:Scope={}){const c=rows(await db.execute(sql`select scope_type,scope_id,autonomy_enabled,kill_switch from vivito_governance_controls where workspace_id=${W} and ((scope_type='WORKSPACE' and scope_id is null) or (scope_type='CLIENT' and scope_id=${scope.clientId||null}) or (scope_type='ACTION' and scope_id=${scope.actionOp||null}))`));if(c.some(x=>x.kill_switch||!x.autonomy_enabled))throw new Error("vivito-autonomy-disabled-by-governance");return true}
export function assessEvidence(e:any){const sources=Array.isArray(e?.sources)?e.sources.filter(Boolean):[];const stale=!!e?.stale,contradictory=!!e?.contradictory,missing=!!e?.missing;let q=Math.min(1,sources.length/2);if(stale)q-=.25;if(contradictory)q-=.35;if(missing)q-=.4;return Math.max(0,Number(q.toFixed(2)))}
export function routeByConfidence(confidence:number,evidenceQuality:number){if(evidenceQuality<.5)return{mode:"HUMAN_REVIEW",reason:"insufficient-evidence"};if(confidence<.7)return{mode:"HUMAN_REVIEW",reason:"low-confidence"};return{mode:"POLICY",reason:"confidence-sufficient"}}
export function simulateDecision(input:{baseline:any;action:any}){return{mode:"SANDBOX",executed:false,baseline:input.baseline,proposed:input.action,warning:"Counterfactual estimate only; no causal claim and no external write."}}
export async function journal(input:{clientId?:string|null;eventId?:string|null;version:string;provider?:string|null;evidence:any;decision:any;confidence:number;simulation?:any}){const quality=assessEvidence(input.evidence);const id=crypto.randomUUID();await db.execute(sql`insert into vivito_decision_journal(id,workspace_id,client_id,event_id,decision_version,model_provider,evidence_quality,confidence,evidence,decision,simulation) values(${id},${W},${input.clientId||null},${input.eventId||null},${input.version},${input.provider||null},${quality},${input.confidence},${JSON.stringify(input.evidence)}::jsonb,${JSON.stringify(input.decision)}::jsonb,${JSON.stringify(input.simulation||null)}::jsonb)`);return{id,evidenceQuality:quality}}
export async function saveCheckpoint(runKey:string,state:any,status="RUNNING"){await db.execute(sql`insert into vivito_runtime_checkpoints(id,workspace_id,run_key,state,status,lease_until) values(${crypto.randomUUID()},${W},${runKey},${JSON.stringify(state)}::jsonb,${status},now()+interval '10 minutes') on conflict(run_key) do update set state=excluded.state,status=excluded.status,attempt=vivito_runtime_checkpoints.attempt+1,lease_until=excluded.lease_until,updated_at=now()`)}
export async function recordEval(metric:string,value:number,baseline:number){const drift=baseline>0&&Math.abs(value-baseline)/baseline>.2;await db.execute(sql`insert into vivito_eval_metrics(id,workspace_id,metric_name,value,baseline,drift_detected) values(${crypto.randomUUID()},${W},${metric},${value},${baseline},${drift}) on conflict(workspace_id,metric_date,metric_name) do update set value=excluded.value,baseline=excluded.baseline,drift_detected=excluded.drift_detected`);return{drift}}
export async function recordValue(eventId:string,cost:number,value:number,currency="EGP"){await db.execute(sql`insert into vivito_value_ledger(id,workspace_id,event_id,cost_amount,value_amount,currency,evidence) values(${crypto.randomUUID()},${W},${eventId},${cost},${value},${currency},${JSON.stringify({roi:cost>0?(value-cost)/cost:null,noCausalClaim:true})}::jsonb)`)}
export async function setKillSwitch(input:{scopeType:"WORKSPACE"|"CLIENT"|"ACTION";scopeId?:string|null;enabled:boolean;userId:string}){await db.execute(sql`insert into vivito_governance_controls(id,workspace_id,scope_type,scope_id,autonomy_enabled,kill_switch,updated_by) values(${crypto.randomUUID()},${W},${input.scopeType},${input.scopeId||null},${!input.enabled},${input.enabled},${input.userId}) on conflict(workspace_id,scope_type,scope_id) do update set autonomy_enabled=excluded.autonomy_enabled,kill_switch=excluded.kill_switch,updated_by=excluded.updated_by,updated_at=now()`);return{ok:true}}
export const providerBoundary={businessLogicProviderIndependent:true,externalWritesRequireConfiguredExecutor:true};
