import {db,clients,contacts,users,creativeTasks,calendarEvents,fileDocuments,salesLeads,salesActivities,auditLogs,workspaces,sql} from "@/lib/db";
import {AsyncLocalStorage} from "node:async_hooks";
import {VIVITO_ACTION_CATALOG,type VivitoActionOp} from "./action-engine";
import {VivitoActionError,type VivitoActionArgs} from "./executor";

type Scalar=string|number|boolean|null|Date;
type ClientRow={id:string;company_name:string;account_manager_id:string|null;media_buyer_id:string|null;user_id:string|null;is_active:boolean;archived_at:string|Date|null};
type StaffRow={id:string;name:string;role:string};
type TaskRow={id:string;title:string;client_id:string;company_name:string;account_manager_id:string|null;status:string};
type FileRow={id:string;name:string;uploaded_by:string;client_id:string|null;mime_type:string|null;archived_at:string|Date|null};
type CalendarRow={id:string;title:string;status:string;client_id:string;company_name:string;account_manager_id:string|null;media_buyer_id:string|null};
type LeadStage=NonNullable<typeof salesLeads.$inferSelect["stage"]>;
type LeadRow={id:string;company_name:string;contact_person:string;phone:string|null;email:string|null;stage:LeadStage;client_id:string|null;industry:string|null;notes:string|null};
type IdRow={id:string};

const workspaceContext=new AsyncLocalStorage<string>();
const tenantId=()=>{const id=workspaceContext.getStore();if(!id)throw new VivitoActionError("Workspace unavailable.",403);return id};
const clean=(value:unknown,n=500)=>String(value??"").trim().slice(0,n);
const own=(value:object,key:string)=>Object.prototype.hasOwnProperty.call(value,key);
const num=(value:unknown)=>{const x=Number(value);if(!Number.isFinite(x)||x<0)throw new VivitoActionError("A valid non-negative number is required.");return Number(x.toFixed(2))};
const date=(value:unknown,label="date")=>{const d=new Date(String(value||""));if(Number.isNaN(d.getTime()))throw new VivitoActionError(`A valid ${label} is required.`);return d};
const email=(value:unknown)=>{const s=clean(value,254);if(s&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s))throw new VivitoActionError("Invalid email address.");return s||null};
const arg=(args:VivitoActionArgs,key:string)=>args[key];
async function audit(userId:string,action:string,entity:string,entityId:string,payload:unknown={}){const value:typeof auditLogs.$inferInsert={workspaceId:tenantId(),userId,action,entity,entityId,newValues:JSON.stringify(payload)};await db.insert(auditLogs).values(value)}
function authorize(role:string,op:VivitoActionOp){const meta=VIVITO_ACTION_CATALOG[op];if(!meta||!meta.roles.includes(role))throw new VivitoActionError("You do not have permission to execute this action.",403)}

async function client(refRaw:unknown,role:string,userId:string):Promise<ClientRow>{
 const ref=clean(refRaw,180);if(!ref)throw new VivitoActionError("Client name is required.");
 let found=Array.from(await db.execute<ClientRow>(sql`select id,company_name,account_manager_id,media_buyer_id,user_id,is_active,archived_at from clients where workspace_id=${tenantId()} and is_active=true and archived_at is null and (id=${ref} or lower(company_name)=lower(${ref})) limit 3`));
 if(!found.length)found=Array.from(await db.execute<ClientRow>(sql`select id,company_name,account_manager_id,media_buyer_id,user_id,is_active,archived_at from clients where workspace_id=${tenantId()} and is_active=true and archived_at is null and company_name ilike ${`%${ref}%`} order by company_name limit 6`));
 if(!found.length)throw new VivitoActionError(`Client “${ref}” was not found.`,404);if(found.length>1)throw new VivitoActionError(`Client name “${ref}” is ambiguous.`,409,{candidates:found.map(x=>({id:x.id,name:x.company_name}))});
 const c=found[0];if(role==="ACCOUNT_MANAGER"&&c.account_manager_id!==userId)throw new VivitoActionError("This client is outside your Account Manager scope.",403);if(role==="MEDIA_BUYER"&&c.media_buyer_id!==userId)throw new VivitoActionError("This client is outside your Media Buyer scope.",403);if(role==="CLIENT"&&c.user_id!==userId)throw new VivitoActionError("This client is outside your portal scope.",403);return c;
}
async function staff(refRaw:unknown,rolesWanted:string[]):Promise<StaffRow>{const ref=clean(refRaw,180);if(!ref)throw new VivitoActionError("Team member name is required.");let found=Array.from(await db.execute<StaffRow>(sql`select id,name,role from users where workspace_id=${tenantId()} and is_active=true and role in (${sql.join(rolesWanted.map(x=>sql`${x}`),sql`,`)}) and (id=${ref} or lower(name)=lower(${ref})) limit 3`));if(!found.length)found=Array.from(await db.execute<StaffRow>(sql`select id,name,role from users where workspace_id=${tenantId()} and is_active=true and role in (${sql.join(rolesWanted.map(x=>sql`${x}`),sql`,`)}) and name ilike ${`%${ref}%`} order by name limit 6`));if(!found.length)throw new VivitoActionError(`Team member “${ref}” was not found.`,404);if(found.length>1)throw new VivitoActionError(`Team member name “${ref}” is ambiguous.`,409,{candidates:found});return found[0]}
async function task(args:VivitoActionArgs,role:string,userId:string):Promise<TaskRow>{const id=clean(arg(args,"taskId"),100),title=clean(arg(args,"taskTitle"),180),c=title?await client(arg(args,"clientName"),role,userId):null;let found:TaskRow[]=id?Array.from(await db.execute<TaskRow>(sql`select t.id,t.title,t.client_id,t.status,c.company_name,c.account_manager_id from creative_tasks t join clients c on c.id=t.client_id where t.id=${id} and t.workspace_id=${tenantId()} and t.archived_at is null and c.workspace_id=${tenantId()} and c.is_active=true limit 2`)):c&&title?Array.from(await db.execute<TaskRow>(sql`select t.id,t.title,t.client_id,t.status,c.company_name,c.account_manager_id from creative_tasks t join clients c on c.id=t.client_id where t.workspace_id=${tenantId()} and t.client_id=${c.id} and t.archived_at is null and lower(t.title)=lower(${title}) limit 3`)):[];if(!found.length&&c&&title)found=Array.from(await db.execute<TaskRow>(sql`select t.id,t.title,t.client_id,t.status,c.company_name,c.account_manager_id from creative_tasks t join clients c on c.id=t.client_id where t.workspace_id=${tenantId()} and t.client_id=${c.id} and t.archived_at is null and t.title ilike ${`%${title}%`} order by t.created_at desc limit 6`));if(!found.length)throw new VivitoActionError("Task was not found.",404);if(found.length>1)throw new VivitoActionError("Task title is ambiguous.",409,{candidates:found.map(x=>({id:x.id,title:x.title,client:x.company_name}))});const t=found[0];if(role==="ACCOUNT_MANAGER"&&t.account_manager_id!==userId)throw new VivitoActionError("This task is outside your Account Manager scope.",403);return t}

async function updateClient(args:VivitoActionArgs,role:string,userId:string){
 const c=await client(arg(args,"clientName"),role,userId),sets:Record<string,Scalar>={},changed:Record<string,unknown>={};
 const textFields:[string,string,number][]=[["companyName","company_name",160],["industry","industry",100],["website","website",500],["facebookUrl","facebook_url",500],["instagramUrl","instagram_url",500],["metaAdsLink","meta_ads_link",500],["googleAdsLink","google_ads_link",500],["tiktokAdsLink","tiktok_ads_link",500],["snapchatAdsLink","snapchat_ads_link",500],["internalNotes","internal_notes",2000]];
 for(const [key,col,max] of textFields)if(own(args,key)){const v=clean(arg(args,key),max);if(key==="companyName"&&v.length<2)throw new VivitoActionError("Company name is required.");sets[col]=v||null;changed[key]=v||null}
 if(own(args,"companyName")){const companyName=clean(arg(args,"companyName"),160),dup=Array.from(await db.execute<IdRow>(sql`select id from clients where workspace_id=${tenantId()} and lower(company_name)=lower(${companyName}) and id<>${c.id} limit 1`));if(dup.length)throw new VivitoActionError("A client with this company name already exists.",409)}
 const commercial=["monthlyRetainer","mediaBudget","contractValue","contractStart","contractEnd","accountManagerName","mediaBuyerName"];
 if(role!=="SUPER_ADMIN"&&commercial.some(k=>own(args,k)))throw new VivitoActionError("Only Super Admin can change commercial terms or account ownership.",403);
 if(role==="SUPER_ADMIN"){
  for(const [key,col] of [["monthlyRetainer","monthly_retainer"],["mediaBudget","media_budget"],["contractValue","contract_value"]] as const)if(own(args,key)){sets[col]=num(arg(args,key));changed[key]=sets[col]}
  if(own(args,"contractStart")){sets.contract_start=arg(args,"contractStart")?date(arg(args,"contractStart"),"contract start"):null;changed.contractStart=arg(args,"contractStart")||null}if(own(args,"contractEnd")){sets.contract_end=arg(args,"contractEnd")?date(arg(args,"contractEnd"),"contract end"):null;changed.contractEnd=arg(args,"contractEnd")||null}
  const contractStart=sets.contract_start instanceof Date?sets.contract_start:null,contractEnd=sets.contract_end instanceof Date?sets.contract_end:null;if(contractStart&&contractEnd&&contractEnd<contractStart)throw new VivitoActionError("Contract end date must be on or after start date.");
  if(own(args,"accountManagerName")){const u=clean(arg(args,"accountManagerName"))?await staff(arg(args,"accountManagerName"),["ACCOUNT_MANAGER"]):null;sets.account_manager_id=u?.id||null;changed.accountManager=u?.name||null}
  if(own(args,"mediaBuyerName")){const u=clean(arg(args,"mediaBuyerName"))?await staff(arg(args,"mediaBuyerName"),["MEDIA_BUYER"]):null;sets.media_buyer_id=u?.id||null;changed.mediaBuyer=u?.name||null}
 }
 const entries=Object.entries(sets);if(!entries.length)throw new VivitoActionError("No client fields were supplied to update.");
 const fragments=entries.map(([k,v])=>sql`${sql.raw(k)}=${v}`);await db.execute(sql`update clients set ${sql.join(fragments,sql`,`)},updated_at=now() where id=${c.id} and workspace_id=${tenantId()}`);await audit(userId,"vivito_client_updated","clients",c.id,changed);return{success:true,action:"update_client",entityId:c.id,message:`Client ${c.company_name} updated.`,link:`/dashboard/clients/${c.id}`};
}

async function addContact(args:VivitoActionArgs,role:string,userId:string){const c=await client(arg(args,"clientName"),role,userId),name=clean(arg(args,"contactName"),160);if(!name)throw new VivitoActionError("Contact name is required.");const isPrimary=Boolean(arg(args,"isPrimary"));let id="";await db.transaction(async tx=>{if(isPrimary)await tx.execute(sql`update contacts set is_primary=false where client_id=${c.id}`);const contactValue:typeof contacts.$inferInsert={clientId:c.id,name,title:clean(arg(args,"title"),120)||null,email:email(arg(args,"email")),phone:clean(arg(args,"phone"),60)||null,whatsapp:clean(arg(args,"whatsapp")||arg(args,"phone"),60)||null,isPrimary};const [row]=await tx.insert(contacts).values(contactValue).returning();id=row.id;const auditValue:typeof auditLogs.$inferInsert={workspaceId:tenantId(),userId,action:"vivito_client_contact_added",entity:"contacts",entityId:row.id,newValues:JSON.stringify({clientId:c.id,clientName:c.company_name,name,isPrimary})};await tx.insert(auditLogs).values(auditValue)});return{success:true,action:"add_client_contact",entityId:id,message:`Contact ${name} added to ${c.company_name}.`,link:`/dashboard/clients/${c.id}`}}

const TASK_TRANSITIONS:Record<string,string[]>={PENDING:["IN_PROGRESS"],IN_PROGRESS:["REVIEW"],REVIEW:["APPROVED","REVISION"],REVISION:["IN_PROGRESS","REVIEW"],APPROVED:["COMPLETED"],REJECTED:[],COMPLETED:[]};
async function updateTask(args:VivitoActionArgs,role:string,userId:string){const t=await task(args,role,userId),sets:Record<string,Scalar>={},changed:Record<string,unknown>={};if(own(args,"title")){const v=clean(arg(args,"title"),180);if(!v)throw new VivitoActionError("Task title cannot be empty.");sets.title=v;changed.title=v}if(own(args,"brief")){const v=clean(arg(args,"brief"),5000);if(!v)throw new VivitoActionError("Task brief cannot be empty.");sets.brief=v;changed.brief=true}if(own(args,"deadline")){const deadline=date(arg(args,"deadline"),"deadline");sets.deadline=deadline;changed.deadline=deadline.toISOString()}if(own(args,"priority")){const v=clean(arg(args,"priority"),20).toUpperCase();if(!["LOW","MEDIUM","HIGH","URGENT"].includes(v))throw new VivitoActionError("Invalid task priority.");sets.priority=v;changed.priority=v}if(own(args,"type")){const v=clean(arg(args,"type"),30).toUpperCase();if(!["GRAPHIC","CAROUSEL","MOTION_GRAPHIC","VIDEO_EDIT","PHOTO_SESSION","REEL","STORY","UGC"].includes(v))throw new VivitoActionError("Invalid task type.");sets.type=v;changed.type=v}if(own(args,"status")){const v=clean(arg(args,"status"),30).toUpperCase(),from=t.status;if(!(TASK_TRANSITIONS[from]||[]).includes(v))throw new VivitoActionError(`Invalid task transition: ${from} → ${v}.`,409);sets.status=v;changed.status={from,to:v};if(v==="COMPLETED")sets.completed_at=new Date()}
 const entries=Object.entries(sets);if(!entries.length)throw new VivitoActionError("No task fields were supplied to update.");const fragments=entries.map(([k,v])=>sql`${sql.raw(k)}=${v}`);await db.execute(sql`update creative_tasks set ${sql.join(fragments,sql`,`)},updated_at=now() where id=${t.id} and workspace_id=${tenantId()} and archived_at is null`);await audit(userId,"vivito_task_updated","creative_tasks",t.id,changed);return{success:true,action:"update_task",entityId:t.id,message:`Task ${t.title} updated.`,link:`/dashboard/creative/${t.id}`}}
async function reassignTask(args:VivitoActionArgs,role:string,userId:string){const t=await task(args,role,userId),u=await staff(arg(args,"assigneeName"),["CREATOR"]);await db.transaction(async tx=>{await tx.execute(sql`update creative_tasks set assigned_to_id=${u.id},updated_at=now() where id=${t.id} and workspace_id=${tenantId()} and archived_at is null`);await tx.execute(sql`insert into notifications(id,user_id,type,title,message,link,priority,is_read,created_at) values(gen_random_uuid()::text,${u.id},'TASK_ASSIGNED',${`VIVITO assigned: ${t.title}`},${t.company_name||"Client"},${`/dashboard/creative/${t.id}`},'normal',false,now())`);const auditValue:typeof auditLogs.$inferInsert={workspaceId:tenantId(),userId,action:"vivito_task_reassigned",entity:"creative_tasks",entityId:t.id,newValues:JSON.stringify({assigneeId:u.id,assigneeName:u.name})};await tx.insert(auditLogs).values(auditValue)});return{success:true,action:"reassign_task",entityId:t.id,message:`Task ${t.title} assigned to ${u.name}.`,link:`/dashboard/creative/${t.id}`}}

async function schedulePost(args:VivitoActionArgs,role:string,userId:string){const c=await client(arg(args,"clientName"),role,userId),fileId=clean(arg(args,"fileId"),100),title=clean(arg(args,"title"),160),platform=clean(arg(args,"platform"),40).toLowerCase(),when=date(arg(args,"date"),"schedule date");if(!fileId||!title||!platform)throw new VivitoActionError("Client, title, platform, date, and uploaded asset are required.");const [f]=Array.from(await db.execute<FileRow>(sql`select id,name,uploaded_by,client_id,mime_type,archived_at from file_documents where id=${fileId} and workspace_id=${tenantId()} limit 1`));if(!f||f.archived_at)throw new VivitoActionError("Uploaded asset is unavailable.",404);if(role!=="SUPER_ADMIN"&&f.uploaded_by!==userId)throw new VivitoActionError("You can only schedule an asset you uploaded.",403);if(!/^(image|video)\//.test(f.mime_type||""))throw new VivitoActionError("Scheduled posts require an image or video.");let taskId:string|null=null;if(clean(arg(args,"taskTitle"))||clean(arg(args,"taskId"))){const t=await task(args,role,userId);if(t.client_id!==c.id)throw new VivitoActionError("Task does not belong to the selected client.",409);if(!["APPROVED","COMPLETED"].includes(t.status))throw new VivitoActionError("Only approved/completed creative tasks can be scheduled.",409);taskId=t.id}
 let eventId="";await db.transaction(async tx=>{await tx.execute(sql`update file_documents set client_id=${c.id},category='SOCIAL_POST' where id=${fileId} and workspace_id=${tenantId()}`);const eventValue:typeof calendarEvents.$inferInsert={clientId:c.id,taskId,title,date:when,platform,caption:clean(arg(args,"caption"),4000)||null,hashtags:`asset:${fileId}`,status:"scheduled"};const [event]=await tx.insert(calendarEvents).values(eventValue).returning();eventId=event.id;const auditValue:typeof auditLogs.$inferInsert={workspaceId:tenantId(),userId,action:"vivito_calendar_post_scheduled",entity:"calendar_events",entityId:event.id,newValues:JSON.stringify({clientId:c.id,clientName:c.company_name,fileId,taskId,title,date:when.toISOString(),platform})};await tx.insert(auditLogs).values(auditValue)});return{success:true,action:"schedule_post",entityId:eventId,message:`Post ${title} scheduled for ${c.company_name}.`,link:"/dashboard/calendar"}}
async function markPosted(args:VivitoActionArgs,role:string,userId:string){const id=clean(arg(args,"eventId"),100),title=clean(arg(args,"eventTitle"),180),c=title?await client(arg(args,"clientName"),role,userId):null;const found:CalendarRow[]=id?Array.from(await db.execute<CalendarRow>(sql`select e.id,e.title,e.status,e.client_id,c.company_name,c.account_manager_id,c.media_buyer_id from calendar_events e join clients c on c.id=e.client_id where e.id=${id} and c.workspace_id=${tenantId()} limit 2`)):c&&title?Array.from(await db.execute<CalendarRow>(sql`select e.id,e.title,e.status,e.client_id,c.company_name,c.account_manager_id,c.media_buyer_id from calendar_events e join clients c on c.id=e.client_id where e.client_id=${c.id} and lower(e.title)=lower(${title}) order by e.date desc limit 3`)):[];if(!found.length)throw new VivitoActionError("Calendar post was not found.",404);if(found.length>1)throw new VivitoActionError("Calendar post title is ambiguous.",409,{candidates:found});const e=found[0];if(role==="ACCOUNT_MANAGER"&&e.account_manager_id!==userId)throw new VivitoActionError("Post is outside your client scope.",403);if(role==="MEDIA_BUYER"&&e.media_buyer_id!==userId)throw new VivitoActionError("Post is outside your client scope.",403);if(e.status==="posted")throw new VivitoActionError("Post is already marked as posted.",409);await db.execute(sql`update calendar_events set status='posted',updated_at=now() where id=${e.id}`);await audit(userId,"vivito_calendar_post_marked_posted","calendar_events",e.id,{title:e.title,clientName:e.company_name});return{success:true,action:"mark_posted",entityId:e.id,message:`Post ${e.title} marked as posted.`,link:"/dashboard/calendar"}}

const LEAD_TRANSITIONS:Record<LeadStage,readonly LeadStage[]>={NEW_LEAD:["CONTACTED","LOST"],CONTACTED:["QUALIFIED","LOST"],QUALIFIED:["PROPOSAL_SENT","LOST"],PROPOSAL_SENT:["NEGOTIATION","LOST"],NEGOTIATION:["WON","LOST"],WON:[],LOST:[]};
const LEAD_PROB:Record<LeadStage,number>={NEW_LEAD:5,CONTACTED:15,QUALIFIED:40,PROPOSAL_SENT:60,NEGOTIATION:80,WON:100,LOST:0};
const LEAD_STAGES:ReadonlySet<string>=new Set(Object.keys(LEAD_TRANSITIONS));
const isLeadStage=(value:string):value is LeadStage=>LEAD_STAGES.has(value);
async function lead(refRaw:unknown,role:string,userId:string):Promise<LeadRow>{const ref=clean(refRaw,180);if(!ref)throw new VivitoActionError("Lead company name is required.");const owner=role==="SALES"?sql`and sales_rep_id=${userId}`:sql``;let found=Array.from(await db.execute<LeadRow>(sql`select id,company_name,contact_person,phone,email,stage,client_id,industry,notes from sales_leads where workspace_id=${tenantId()} and archived_at is null ${owner} and (id=${ref} or lower(company_name)=lower(${ref})) limit 3`));if(!found.length)found=Array.from(await db.execute<LeadRow>(sql`select id,company_name,contact_person,phone,email,stage,client_id,industry,notes from sales_leads where workspace_id=${tenantId()} and archived_at is null ${owner} and company_name ilike ${`%${ref}%`} order by updated_at desc limit 6`));if(!found.length)throw new VivitoActionError(`Lead “${ref}” was not found.`,404);if(found.length>1)throw new VivitoActionError(`Lead “${ref}” is ambiguous.`,409,{candidates:found.map(x=>({id:x.id,companyName:x.company_name,stage:x.stage}))});return found[0]}
async function createLead(args:VivitoActionArgs,userId:string){const companyName=clean(arg(args,"companyName"),160),contactPerson=clean(arg(args,"contactPerson"),160),estimatedValue=num(arg(args,"estimatedValue"));if(!companyName||!contactPerson)throw new VivitoActionError("Lead company and contact person are required.");const value:typeof salesLeads.$inferInsert={workspaceId:tenantId(),companyName,contactPerson,phone:clean(arg(args,"phone"),40)||null,email:email(arg(args,"email")),source:clean(arg(args,"source"),40)||"WEBSITE",estimatedValue,stage:"NEW_LEAD",probability:5,industry:clean(arg(args,"industry"),100)||null,notes:clean(arg(args,"notes"),3000)||null,salesRepId:userId};const [row]=await db.insert(salesLeads).values(value).returning();await audit(userId,"vivito_lead_created","sales_leads",row.id,{companyName,estimatedValue});return{success:true,action:"create_lead",entityId:row.id,message:`Lead ${companyName} created.`,link:"/dashboard/sales"}}
async function updateLead(args:VivitoActionArgs,role:string,userId:string){const l=await lead(arg(args,"leadCompanyName"),role,userId),sets:Record<string,Scalar>={},changed:Record<string,unknown>={};for(const [key,col,max] of [["contactPerson","contact_person",160],["phone","phone",40],["industry","industry",100],["notes","notes",3000]] as [string,string,number][])if(own(args,key)){sets[col]=clean(arg(args,key),max)||null;changed[key]=sets[col]}if(own(args,"email")){sets.email=email(arg(args,"email"));changed.email=Boolean(sets.email)}if(own(args,"estimatedValue")){sets.estimated_value=num(arg(args,"estimatedValue"));changed.estimatedValue=sets.estimated_value}if(own(args,"nextFollowUp")){sets.next_follow_up=arg(args,"nextFollowUp")?date(arg(args,"nextFollowUp"),"next follow-up"):null;changed.nextFollowUp=arg(args,"nextFollowUp")||null}if(own(args,"expectedClose")){sets.expected_close=arg(args,"expectedClose")?date(arg(args,"expectedClose"),"expected close"):null;changed.expectedClose=arg(args,"expectedClose")||null}const entries=Object.entries(sets);if(!entries.length)throw new VivitoActionError("No lead fields were supplied to update.");const frags=entries.map(([k,v])=>sql`${sql.raw(k)}=${v}`);await db.transaction(async tx=>{await tx.execute(sql`update sales_leads set ${sql.join(frags,sql`,`)},updated_at=now() where id=${l.id} and workspace_id=${tenantId()}`);const activity:typeof salesActivities.$inferInsert={leadId:l.id,userId,type:"note",notes:"Updated by VIVITO",outcome:"lead_updated"};await tx.insert(salesActivities).values(activity);const auditValue:typeof auditLogs.$inferInsert={workspaceId:tenantId(),userId,action:"vivito_lead_updated",entity:"sales_leads",entityId:l.id,newValues:JSON.stringify(changed)};await tx.insert(auditLogs).values(auditValue)});return{success:true,action:"update_lead",entityId:l.id,message:`Lead ${l.company_name} updated.`,link:"/dashboard/sales"}}
async function moveLead(args:VivitoActionArgs,role:string,userId:string){const l=await lead(arg(args,"leadCompanyName"),role,userId),stageRaw=clean(arg(args,"stage"),40).toUpperCase();if(!isLeadStage(stageRaw)||!LEAD_TRANSITIONS[l.stage].includes(stageRaw))throw new VivitoActionError(`Invalid sales transition: ${l.stage} → ${stageRaw}.`,409);const stage=stageRaw;let clientId=l.client_id||null;await db.transaction(async tx=>{if(stage==="WON"&&!clientId){const existing=Array.from(await tx.execute<IdRow>(sql`select id from clients where workspace_id=${tenantId()} and is_active=true and lower(company_name)=lower(${l.company_name}) limit 1`));if(existing[0])clientId=existing[0].id;else{const [ws]=await tx.select({currency:workspaces.currency}).from(workspaces).where(sql`${workspaces.id}=${tenantId()}`).limit(1),clientValue:typeof clients.$inferInsert={workspaceId:tenantId(),companyName:l.company_name,industry:l.industry||null,currency:ws?.currency||"EGP",internalNotes:l.notes||null,isActive:true},[created]=await tx.insert(clients).values(clientValue).returning();clientId=created.id;if(l.contact_person){const contactValue:typeof contacts.$inferInsert={clientId,name:l.contact_person,email:l.email||null,phone:l.phone||null,whatsapp:l.phone||null,isPrimary:true};await tx.insert(contacts).values(contactValue)}}}await tx.execute(sql`update sales_leads set stage=${stage},probability=${LEAD_PROB[stage]},updated_at=now(),won_at=${stage==="WON"?new Date():null},lost_reason=${stage==="LOST"?"Deal not closed":null},client_id=${clientId} where id=${l.id} and workspace_id=${tenantId()}`);const activity:typeof salesActivities.$inferInsert={leadId:l.id,userId,type:"stage_change",notes:`${l.stage} → ${stage}`,outcome:stage,nextActionDate:null};await tx.insert(salesActivities).values(activity);const auditValue:typeof auditLogs.$inferInsert={workspaceId:tenantId(),userId,action:stage==="WON"?"vivito_lead_converted":"vivito_lead_stage_changed",entity:"sales_leads",entityId:l.id,newValues:JSON.stringify({from:l.stage,to:stage,clientId})};await tx.insert(auditLogs).values(auditValue)});return{success:true,action:"move_lead",entityId:l.id,message:`Lead ${l.company_name} moved from ${l.stage} to ${stage}.`,link:clientId&&stage==="WON"?`/dashboard/clients/${clientId}`:"/dashboard/sales"}}
async function archiveLead(args:VivitoActionArgs,role:string,userId:string){const l=await lead(arg(args,"leadCompanyName"),role,userId);await db.execute(sql`update sales_leads set archived_at=now(),archived_by=${userId},updated_at=now() where id=${l.id} and workspace_id=${tenantId()} and archived_at is null`);await audit(userId,"vivito_lead_archived","sales_leads",l.id,{companyName:l.company_name});return{success:true,action:"archive_lead",entityId:l.id,message:`Lead ${l.company_name} archived.`,link:"/dashboard/sales"}}

export const VIVITO_EXTENDED_ACTIONS=new Set<VivitoActionOp>(["update_client","add_client_contact","update_task","reassign_task","schedule_post","mark_posted","create_lead","update_lead","move_lead","archive_lead"]);
export function isVivitoExtendedAction(op:VivitoActionOp){return VIVITO_EXTENDED_ACTIONS.has(op)}
export async function executeVivitoExtendedAction(op:VivitoActionOp,args:VivitoActionArgs,role:string,userId:string,workspaceId:string){if(!workspaceId)throw new VivitoActionError("Workspace unavailable.",403);return workspaceContext.run(workspaceId,async()=>{authorize(role,op);if(op==="update_client")return updateClient(args,role,userId);if(op==="add_client_contact")return addContact(args,role,userId);if(op==="update_task")return updateTask(args,role,userId);if(op==="reassign_task")return reassignTask(args,role,userId);if(op==="schedule_post")return schedulePost(args,role,userId);if(op==="mark_posted")return markPosted(args,role,userId);if(op==="create_lead")return createLead(args,userId);if(op==="update_lead")return updateLead(args,role,userId);if(op==="move_lead")return moveLead(args,role,userId);if(op==="archive_lead")return archiveLead(args,role,userId);throw new VivitoActionError("Unsupported extended VIVITO action.")})}
