import {createHash,randomBytes} from "node:crypto";
import {AsyncLocalStorage} from "node:async_hooks";
import {db,auditLogs,sql} from "@/lib/db";
import {VivitoActionError} from "./executor";
import {VIVITO_ACTION_CATALOG,type VivitoActionOp} from "./action-engine";
import {connectionAccessToken} from "@/lib/ad-oauth";
import {syncCampaign} from "@/lib/ad-platforms";

const workspaceContext=new AsyncLocalStorage<string>();
const tenantId=()=>{const id=workspaceContext.getStore();if(!id)throw new VivitoActionError("Workspace unavailable.",403);return id};
const OPERATOR_OPS=new Set<VivitoActionOp>([
 "create_user","update_user","set_user_active","create_leave_request","decide_leave","upsert_payroll","set_payroll_status",
 "create_contract","update_contract","update_workspace_settings","send_email","send_whatsapp","create_api_key","revoke_api_key",
 "create_webhook","revoke_webhook","sync_campaign","update_campaign","start_integration","disconnect_integration","export_data",
 "generate_report","update_onboarding","record_nps","create_referral","bulk_update_tasks","bulk_remind_clients"
]);
export function isVivitoOperatorAction(op:VivitoActionOp){return OPERATOR_OPS.has(op)}
const clean=(v:unknown,n=500)=>String(v??"").trim().slice(0,n);
const rows=(v:unknown)=>Array.from(v as any) as any[];
const n=(v:unknown)=>{const x=Number(v);if(!Number.isFinite(x))throw new VivitoActionError("A valid number is required.");return x};
const nonneg=(v:unknown)=>{const x=n(v);if(x<0)throw new VivitoActionError("Value cannot be negative.");return Number(x.toFixed(2))};
const date=(v:unknown)=>{const d=new Date(String(v||""));if(Number.isNaN(d.getTime()))throw new VivitoActionError("A valid date is required.");return d};
const email=(v:unknown)=>clean(v,254).toLowerCase();
const validEmail=(v:string)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);
async function audit(userId:string,action:string,entity:string,entityId:string,payload:unknown={}){await db.insert(auditLogs).values({workspaceId:tenantId(),userId,action,entity,entityId,newValues:JSON.stringify(payload)})}
function authorize(role:string,op:VivitoActionOp){const meta=VIVITO_ACTION_CATALOG[op];if(!meta||!meta.roles.includes(role))throw new VivitoActionError("You do not have permission to execute this action.",403)}
async function uniqueByName(table:string,nameCol:string,refRaw:unknown,extra=sql``){const ref=clean(refRaw,180);if(!ref)throw new VivitoActionError("A name is required.");let found=rows(await db.execute(sql`select * from ${sql.identifier(table)} where workspace_id=${tenantId()} and (id=${ref} or lower(${sql.identifier(nameCol)})=lower(${ref})) ${extra} limit 3`));if(!found.length)found=rows(await db.execute(sql`select * from ${sql.identifier(table)} where workspace_id=${tenantId()} and ${sql.identifier(nameCol)} ilike ${`%${ref}%`} ${extra} order by ${sql.identifier(nameCol)} limit 6`));if(!found.length)throw new VivitoActionError(`“${ref}” was not found.`,404);if(found.length>1)throw new VivitoActionError(`“${ref}” is ambiguous.`,409,{candidates:found.map(x=>({id:x.id,name:x[nameCol]}))});return found[0]}
async function user(ref:unknown,activeOnly=false){const extra=activeOnly?sql`and is_active=true`:sql``;return uniqueByName("users","name",ref,extra)}
async function client(ref:unknown){return uniqueByName("clients","company_name",ref,sql`and is_active=true and archived_at is null`)}
async function campaign(ref:unknown){const r=clean(ref,180);if(!r)throw new VivitoActionError("Campaign name is required.");let found=rows(await db.execute(sql`select c.*,cl.company_name,cl.account_manager_id,cl.media_buyer_id from ad_campaigns c join clients cl on cl.id=c.client_id where c.workspace_id=${tenantId()} and cl.workspace_id=${tenantId()} and c.archived_at is null and (c.id=${r} or lower(c.name)=lower(${r})) limit 3`));if(!found.length)found=rows(await db.execute(sql`select c.*,cl.company_name,cl.account_manager_id,cl.media_buyer_id from ad_campaigns c join clients cl on cl.id=c.client_id where c.workspace_id=${tenantId()} and cl.workspace_id=${tenantId()} and c.archived_at is null and c.name ilike ${`%${r}%`} order by c.updated_at desc limit 6`));if(!found.length)throw new VivitoActionError("Campaign was not found.",404);if(found.length>1)throw new VivitoActionError("Campaign name is ambiguous.",409,{candidates:found.map(x=>({id:x.id,name:x.name,client:x.company_name}))});return found[0]}

async function createUser(args:any,userId:string){const name=clean(args.name,160),mail=email(args.email),role=clean(args.role,40).toUpperCase();const roles=["SUPER_ADMIN","ACCOUNTANT","ACCOUNT_MANAGER","MEDIA_BUYER","CREATOR","SALES","CLIENT"];if(!name||!validEmail(mail)||!roles.includes(role))throw new VivitoActionError("Name, valid email and valid role are required.");const dupe=rows(await db.execute(sql`select id from users where lower(email)=lower(${mail}) limit 1`));if(dupe.length)throw new VivitoActionError("A user with this email already exists.",409);const temp=randomBytes(24).toString("base64url"),bcryptMod:any=await import("bcryptjs"),bcrypt:any=bcryptMod.default??bcryptMod,hash=await bcrypt.hash(temp,12);const id=crypto.randomUUID();await db.execute(sql`insert into users(id,workspace_id,name,email,password,role,phone,is_active,approval_status,created_at,updated_at) values(${id},${tenantId()},${name},${mail},${hash},${role},${clean(args.phone,60)||null},true,'APPROVED',now(),now())`);await audit(userId,"vivito_user_created","users",id,{name,email:mail,role});return{success:true,action:"create_user",entityId:id,message:`User ${name} created.`,temporaryPassword:temp,security:"Temporary password is shown once; require reset after first sign-in.",link:"/dashboard/team"}}
async function updateUser(op:VivitoActionOp,args:any,userId:string){const u=await user(args.userName||args.email,false);if(op==="set_user_active"){const active=Boolean(args.active);await db.execute(sql`update users set is_active=${active},updated_at=now() where id=${u.id} and workspace_id=${tenantId()}`);await audit(userId,active?"vivito_user_activated":"vivito_user_deactivated","users",u.id,{name:u.name});return{success:true,action:op,entityId:u.id,message:`${u.name} ${active?"activated":"deactivated"}.`}}const sets:any={};if(args.name!==undefined)sets.name=clean(args.name,160);if(args.phone!==undefined)sets.phone=clean(args.phone,60)||null;if(args.role!==undefined){const role=clean(args.role,40).toUpperCase();if(!["SUPER_ADMIN","ACCOUNTANT","ACCOUNT_MANAGER","MEDIA_BUYER","CREATOR","SALES","CLIENT"].includes(role))throw new VivitoActionError("Invalid role.");sets.role=role}if(!Object.keys(sets).length)throw new VivitoActionError("No user fields were supplied to update.");if(sets.name!==undefined)await db.execute(sql`update users set name=${sets.name},updated_at=now() where id=${u.id} and workspace_id=${tenantId()}`);if(sets.phone!==undefined)await db.execute(sql`update users set phone=${sets.phone},updated_at=now() where id=${u.id} and workspace_id=${tenantId()}`);if(sets.role!==undefined)await db.execute(sql`update users set role=${sets.role},updated_at=now() where id=${u.id} and workspace_id=${tenantId()}`);await audit(userId,"vivito_user_updated","users",u.id,sets);return{success:true,action:op,entityId:u.id,message:`User ${u.name} updated.`}}

async function createLeave(args:any,role:string,userId:string){const target=role==="SUPER_ADMIN"&&clean(args.userName)?await user(args.userName,true):await uniqueByName("users","name",userId,sql`and is_active=true`);if(role!=="SUPER_ADMIN"&&target.id!==userId)throw new VivitoActionError("You can only create your own leave request.",403);const from=date(args.fromDate),to=date(args.toDate);if(to<from)throw new VivitoActionError("Leave end date must be after start date.");const days=Math.max(1,Math.ceil((to.getTime()-from.getTime())/86400000)+1),type=clean(args.type||"Annual",40),id=crypto.randomUUID();await db.execute(sql`insert into leave_requests(id,user_id,workspace_id,type,from_date,to_date,days,status,reason,created_at) values(${id},${target.id},${tenantId()},${type},${from},${to},${days},'PENDING',${clean(args.reason,1000)||null},now())`);await audit(userId,"vivito_leave_requested","leave_requests",id,{targetUserId:target.id,type,days});return{success:true,action:"create_leave_request",entityId:id,message:`Leave request created for ${target.name}.`,link:"/dashboard/team"}}
async function decideLeave(args:any,userId:string){const id=clean(args.leaveId,100);if(!id)throw new VivitoActionError("leaveId is required.");const decision=clean(args.decision,20).toUpperCase();if(!["APPROVED","REJECTED"].includes(decision))throw new VivitoActionError("Decision must be APPROVED or REJECTED.");const r=rows(await db.execute(sql`update leave_requests set status=${decision},approved_by=${userId},approved_at=now() where id=${id} and workspace_id=${tenantId()} and status='PENDING' returning id,user_id`));if(!r.length)throw new VivitoActionError("Pending leave request was not found.",404);await audit(userId,"vivito_leave_decided","leave_requests",id,{decision});return{success:true,action:"decide_leave",entityId:id,message:`Leave request ${decision.toLowerCase()}.`}}

async function payrollAction(op:VivitoActionOp,args:any,userId:string){const u=await user(args.userName,true),month=Math.trunc(n(args.month)),year=Math.trunc(n(args.year));if(month<1||month>12||year<2020||year>2100)throw new VivitoActionError("Valid payroll month/year required.");if(op==="upsert_payroll"){const base=nonneg(args.baseSalary),bonus=nonneg(args.bonus||0),deductions=nonneg(args.deductions||0),net=Math.max(0,base+bonus-deductions);await db.execute(sql`insert into payroll(id,user_id,workspace_id,month,year,base_salary,bonus,deductions,net_pay,status,notes,created_at,updated_at) values(${crypto.randomUUID()},${u.id},${tenantId()},${month},${year},${base},${bonus},${deductions},${net},'DRAFT',${clean(args.notes,1000)||null},now(),now()) on conflict (user_id,month,year) do update set base_salary=excluded.base_salary,bonus=excluded.bonus,deductions=excluded.deductions,net_pay=excluded.net_pay,notes=excluded.notes,updated_at=now()`).catch(async()=>{const old=rows(await db.execute(sql`select id from payroll where workspace_id=${tenantId()} and user_id=${u.id} and month=${month} and year=${year} limit 1`));if(old.length)await db.execute(sql`update payroll set base_salary=${base},bonus=${bonus},deductions=${deductions},net_pay=${net},notes=${clean(args.notes,1000)||null},updated_at=now() where id=${old[0].id}`);else await db.execute(sql`insert into payroll(id,user_id,workspace_id,month,year,base_salary,bonus,deductions,net_pay,status,notes,created_at,updated_at) values(${crypto.randomUUID()},${u.id},${tenantId()},${month},${year},${base},${bonus},${deductions},${net},'DRAFT',${clean(args.notes,1000)||null},now(),now())`)});await audit(userId,"vivito_payroll_upserted","payroll",`${u.id}:${year}-${month}`,{base,bonus,deductions,net});return{success:true,action:op,message:`Payroll updated for ${u.name}. Net pay ${net}.`,link:"/dashboard/finance/payroll"}}
 const status=clean(args.status,20).toUpperCase();if(!["DRAFT","APPROVED","PAID"].includes(status))throw new VivitoActionError("Payroll status must be DRAFT, APPROVED or PAID.");const r=rows(await db.execute(sql`update payroll set status=${status},paid_at=${status==="PAID"?new Date():null},updated_at=now() where workspace_id=${tenantId()} and user_id=${u.id} and month=${month} and year=${year} returning id`));if(!r.length)throw new VivitoActionError("Payroll record was not found.",404);await audit(userId,"vivito_payroll_status","payroll",r[0].id,{status});return{success:true,action:op,entityId:r[0].id,message:`Payroll for ${u.name} marked ${status}.`}}

async function contractAction(op:VivitoActionOp,args:any,userId:string){const c=await client(args.clientName);if(op==="create_contract"){const title=clean(args.title,180),type=clean(args.type||"RETAINER",30).toUpperCase(),value=nonneg(args.value),start=date(args.startDate),end=date(args.endDate);if(!title||end<start)throw new VivitoActionError("Valid contract title and date range required.");const id=crypto.randomUUID();await db.execute(sql`insert into contracts(id,client_id,title,type,value,start_date,end_date,auto_renew,renewal_days,status,document_url,notes,created_at,updated_at) values(${id},${c.id},${title},${type},${value},${start},${end},${Boolean(args.autoRenew)},${Math.max(1,Math.trunc(Number(args.renewalDays||30)))},'ACTIVE',${clean(args.documentUrl,1000)||null},${clean(args.notes,2000)||null},now(),now())`);await audit(userId,"vivito_contract_created","contracts",id,{clientId:c.id,title,value});return{success:true,action:op,entityId:id,message:`Contract ${title} created for ${c.company_name}.`,link:"/dashboard/contracts"}}
 const id=clean(args.contractId,100);if(!id)throw new VivitoActionError("contractId is required.");const status=args.status?clean(args.status,30).toUpperCase():null;if(status&&!['ACTIVE','EXPIRED','RENEWED','CANCELLED'].includes(status))throw new VivitoActionError("Invalid contract status.");const r=rows(await db.execute(sql`update contracts set status=coalesce(${status},status),value=coalesce(${args.value!==undefined?nonneg(args.value):null},value),end_date=coalesce(${args.endDate?date(args.endDate):null},end_date),auto_renew=coalesce(${args.autoRenew!==undefined?Boolean(args.autoRenew):null},auto_renew),notes=coalesce(${args.notes!==undefined?clean(args.notes,2000):null},notes),updated_at=now() where id=${id} and client_id=${c.id} returning id`));if(!r.length)throw new VivitoActionError("Contract was not found for this client.",404);await audit(userId,"vivito_contract_updated","contracts",id,{status});return{success:true,action:op,entityId:id,message:`Contract updated for ${c.company_name}.`}}

async function settings(args:unknown,userId:string){const allowed=["name","primaryColor","logoUrl","faviconUrl","customDomain","currency","agencyFeePercent","timezone","billingEmail"];const changes:object={};for(const k of allowed)if(args[k]!==undefined)(changes as unknown)[k]=args[k];if(!Object.keys(changes).length)throw new VivitoActionError("No workspace settings were supplied.");const col:unknown={name:"name",primaryColor:"primary_color",logoUrl:"logo_url",faviconUrl:"favicon_url",customDomain:"custom_domain",currency:"currency",agencyFeePercent:"agency_fee_percent",timezone:"timezone",billingEmail:"billing_email"};for(const [k,v] of Object.entries(changes)){const value=k==="agencyFeePercent"?nonneg(v):clean(v,500)||null;await db.execute(sql`update workspaces set ${sql.identifier(col[k])}=${value},updated_at=now() where id=${tenantId()} or slug='vivit-group'`)}await audit(userId,"vivito_workspace_settings_updated","workspaces",tenantId(),changes);return{success:true,action:"update_workspace_settings",entityId:tenantId(),message:"Workspace settings updated.",link:"/dashboard/settings"}}

async function sendEmail(args:any,userId:string){const to=email(args.to),subject=clean(args.subject,200),body=clean(args.body,10000);if(!validEmail(to)||!subject||!body)throw new VivitoActionError("Valid recipient, subject and body are required.");const key=process.env.RESEND_API_KEY;if(!key)throw new VivitoActionError("Email provider is not configured.",503);const html=`<div style="font-family:Arial,sans-serif;white-space:pre-wrap">${body.replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]!))}</div>`;const r=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({from:process.env.EMAIL_FROM??"VIVIT ERP <noreply@viviterp.com>",to:[to],subject,html}),signal:AbortSignal.timeout(8000)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new VivitoActionError("Email provider rejected the request.",502);await db.execute(sql`insert into email_logs(id,"to",subject,type,status,resend_id,created_at) values(${crypto.randomUUID()},${to},${subject},'vivito_custom','sent',${d.id||null},now())`);await audit(userId,"vivito_email_sent","email_logs",d.id||crypto.randomUUID(),{to,subject});return{success:true,action:"send_email",entityId:d.id||null,message:`Email sent to ${to}.`}}
async function sendWhatsApp(args:any,userId:string){const token=process.env.WHATSAPP_TOKEN,phoneId=process.env.WHATSAPP_PHONE_ID;if(!token||!phoneId)throw new VivitoActionError("WhatsApp Cloud API is not configured.",503);const to=clean(args.to,40).replace(/\D/g,""),body=clean(args.body,4096);if(to.length<8||!body)throw new VivitoActionError("International phone number and message are required.");const id=crypto.randomUUID();await db.execute(sql`insert into whatsapp_messages(id,"to",template,body,client_id,status,created_at) values(${id},${to},'custom',${body},${args.clientName?(await client(args.clientName)).id:null},'PENDING',now())`);const version=process.env.WHATSAPP_GRAPH_VERSION||process.env.META_GRAPH_VERSION||"v23.0";const r=await fetch(`https://graph.facebook.com/${version}/${encodeURIComponent(phoneId)}/messages`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({messaging_product:"whatsapp",to,type:"text",text:{preview_url:false,body}}),signal:AbortSignal.timeout(8000)});const d=await r.json().catch(()=>({})),msgId=d?.messages?.[0]?.id;if(!r.ok||!msgId){await db.execute(sql`update whatsapp_messages set status='FAILED' where id=${id}`);throw new VivitoActionError(d?.error?.message||"WhatsApp rejected the message.",502)}await db.execute(sql`update whatsapp_messages set status='SENT',wa_message_id=${msgId} where id=${id}`);await audit(userId,"vivito_whatsapp_sent","whatsapp_messages",id,{to,messageId:msgId});return{success:true,action:"send_whatsapp",entityId:id,message:`WhatsApp message sent to ${to}.`}}

async function apiKeyAction(op:VivitoActionOp,args:any,userId:string){if(op==="create_api_key"){const name=clean(args.name,120)||"VIVITO key",perm=clean(args.permissions||"read",20).toLowerCase();if(!["read","write","admin"].includes(perm))throw new VivitoActionError("API key permissions must be read, write or admin.");const raw=`viv_${randomBytes(30).toString("base64url")}`,hash=createHash("sha256").update(raw).digest("hex"),id=crypto.randomUUID();await db.execute(sql`insert into api_keys(id,workspace_id,user_id,name,key_hash,key_prefix,permissions,is_active,created_at) values(${id},${tenantId()},${userId},${name},${hash},${raw.slice(0,8)},${perm},true,now())`);await audit(userId,"vivito_api_key_created","api_keys",id,{name,permissions:perm,prefix:raw.slice(0,8)});return{success:true,action:op,entityId:id,message:"API key created. Copy it now; it will not be shown again.",apiKey:raw}}
 const id=clean(args.apiKeyId,100);if(!id)throw new VivitoActionError("apiKeyId is required.");const r=rows(await db.execute(sql`update api_keys set is_active=false where id=${id} and workspace_id=${tenantId()} and is_active=true returning id`));if(!r.length)throw new VivitoActionError("Active API key was not found.",404);await audit(userId,"vivito_api_key_revoked","api_keys",id,{});return{success:true,action:op,entityId:id,message:"API key revoked."}}
async function webhookAction(op:VivitoActionOp,args:any,userId:string){if(op==="create_webhook"){let url:URL;try{url=new URL(clean(args.url,1000))}catch{throw new VivitoActionError("Valid webhook URL required.")}if(url.protocol!=="https:")throw new VivitoActionError("Webhook URL must use HTTPS.");if(["localhost","127.0.0.1","::1"].includes(url.hostname)||/^10\.|^192\.168\.|^172\.(1[6-9]|2\d|3[01])\./.test(url.hostname))throw new VivitoActionError("Private/local webhook destinations are blocked.");const events=Array.isArray(args.events)?args.events.map((x:unknown)=>clean(x,80)).filter(Boolean):[];if(!events.length)throw new VivitoActionError("At least one webhook event is required.");const secret=randomBytes(32).toString("hex"),id=crypto.randomUUID();await db.execute(sql`insert into webhooks(id,workspace_id,url,events,secret,is_active,fail_count,created_at) values(${id},${tenantId()},${url.toString()},${JSON.stringify(events)},${secret},true,0,now())`);await audit(userId,"vivito_webhook_created","webhooks",id,{url:url.toString(),events});return{success:true,action:op,entityId:id,message:"Webhook created.",secret,security:"Webhook secret is shown once."}}
 const id=clean(args.webhookId,100);if(!id)throw new VivitoActionError("webhookId is required.");const r=rows(await db.execute(sql`update webhooks set is_active=false where id=${id} and workspace_id=${tenantId()} and is_active=true returning id`));if(!r.length)throw new VivitoActionError("Active webhook was not found.",404);await audit(userId,"vivito_webhook_revoked","webhooks",id,{});return{success:true,action:op,entityId:id,message:"Webhook disabled."}}

async function campaignAction(op:VivitoActionOp,args:any,role:string,userId:string){const c=await campaign(args.campaignName||args.campaignId);if(role==="ACCOUNT_MANAGER"&&c.account_manager_id!==userId||role==="MEDIA_BUYER"&&c.media_buyer_id!==userId)throw new VivitoActionError("Campaign is outside your client scope.",403);if(op==="sync_campaign"){const conn=rows(await db.execute(sql`select * from ad_platform_connections where id=${c.connection_id} and workspace_id=${tenantId()} limit 1`))[0];if(!conn)throw new VivitoActionError("Campaign connection was not found.",404);let token="";try{token=await connectionAccessToken({id:conn.id,accessTokenEncrypted:conn.access_token_encrypted,refreshTokenEncrypted:conn.refresh_token_encrypted,tokenExpiresAt:conn.token_expires_at,platform:conn.platform,adAccountId:conn.ad_account_id} as unknown)}catch{}const end=new Date(),start=new Date(Date.now()-30*86400000),iso=(d:Date)=>d.toISOString().slice(0,10);const result=await syncCampaign({platform:c.platform,campaignId:c.external_id,adAccountId:conn.ad_account_id,accessToken:token||undefined,start:iso(start),end:iso(end)});await db.execute(sql`update ad_campaigns set name=coalesce(${result.name||null},name),status=coalesce(${result.status||null},status),last_sync_at=now(),updated_at=now() where id=${c.id}`);await audit(userId,"vivito_campaign_synced","ad_campaigns",c.id,{days:result.days.length});return{success:true,action:op,entityId:c.id,message:`Campaign ${c.name} synced (${result.days.length} days).`,link:"/dashboard/media/control-center"}}
 const allowed:any={};if(args.dailyBudget!==undefined)allowed.daily_budget=nonneg(args.dailyBudget);if(args.lifetimeBudget!==undefined)allowed.lifetime_budget=nonneg(args.lifetimeBudget);if(args.targetCpl!==undefined)allowed.target_cpl=nonneg(args.targetCpl);if(args.targetCpa!==undefined)allowed.target_cpa=nonneg(args.targetCpa);if(args.targetRoas!==undefined)allowed.target_roas=nonneg(args.targetRoas);if(args.status!==undefined)allowed.status=clean(args.status,30).toUpperCase();if(!Object.keys(allowed).length)throw new VivitoActionError("No campaign control fields supplied.");for(const [k,v] of Object.entries(allowed))await db.execute(sql`update ad_campaigns set ${sql.identifier(k)}=${v},updated_at=now() where id=${c.id}`);await audit(userId,"vivito_campaign_updated","ad_campaigns",c.id,allowed);return{success:true,action:op,entityId:c.id,message:`Campaign ${c.name} controls updated in VIVIT.`,warning:"External ad-platform mutation requires the provider-specific write API; VIVIT's authoritative control record is updated and sync will reconcile reported state.",link:"/dashboard/media/control-center"}}
async function integrationAction(op:VivitoActionOp,args:any,userId:string){const platform=clean(args.platform,30).toUpperCase();if(!["META","GOOGLE","TIKTOK","SNAPCHAT","LINKEDIN"].includes(platform))throw new VivitoActionError("Unsupported integration platform.");if(op==="start_integration")return{success:true,action:op,message:`Open authorization to connect ${platform}.`,link:`/api/ad-oauth/${platform.toLowerCase()}/start`};const c=await client(args.clientName);const r=rows(await db.execute(sql`update ad_platform_connections set status='DISCONNECTED',access_token_encrypted=null,refresh_token_encrypted=null,updated_at=now() where workspace_id=${tenantId()} and client_id=${c.id} and platform=${platform} returning id`));if(!r.length)throw new VivitoActionError("Connected account was not found.",404);await audit(userId,"vivito_integration_disconnected","ad_platform_connections",r[0].id,{clientId:c.id,platform});return{success:true,action:op,entityId:r[0].id,message:`${platform} disconnected from ${c.company_name}.`}}

async function exportReport(op:VivitoActionOp,args:any){if(op==="export_data"){const entity=clean(args.entity,40).toLowerCase();const allowed=["clients","tasks","finance","media","sales"];if(!allowed.includes(entity))throw new VivitoActionError("Export entity must be clients, tasks, finance, media or sales.");return{success:true,action:op,message:`${entity} export is ready.`,link:`/api/export?entity=${encodeURIComponent(entity)}`}}const c=args.clientName?await client(args.clientName):null,period=clean(args.period,20);if(c)return{success:true,action:op,message:`Report workspace opened for ${c.company_name}.`,link:`/dashboard/monthly-reports?clientId=${encodeURIComponent(c.id)}${period?`&period=${encodeURIComponent(period)}`:""}`};return{success:true,action:op,message:"Reports workspace opened.",link:"/dashboard/reports"}}
async function opsData(op:VivitoActionOp,args:any,userId:string){if(op==="update_onboarding"){const c=await client(args.clientName),step=clean(args.stepId,100);if(!step)throw new VivitoActionError("stepId is required.");const completed=args.completed!==false;const found=rows(await db.execute(sql`select id from onboarding_progress where client_id=${c.id} and step_id=${step} limit 1`));const id=found[0]?.id||crypto.randomUUID();if(found.length)await db.execute(sql`update onboarding_progress set completed=${completed},completed_at=${completed?new Date():null},completed_by=${completed?userId:null},notes=${clean(args.notes,1000)||null} where id=${id}`);else await db.execute(sql`insert into onboarding_progress(id,client_id,step_id,completed,completed_at,completed_by,notes,created_at) values(${id},${c.id},${step},${completed},${completed?new Date():null},${completed?userId:null},${clean(args.notes,1000)||null},now())`);await audit(userId,"vivito_onboarding_updated","onboarding_progress",id,{clientId:c.id,step,completed});return{success:true,action:op,entityId:id,message:`Onboarding step ${step} updated for ${c.company_name}.`}}
 if(op==="record_nps"){const c=await client(args.clientName),score=Math.trunc(n(args.score));if(score<0||score>10)throw new VivitoActionError("NPS score must be 0–10.");const now=new Date(),id=crypto.randomUUID();await db.execute(sql`insert into client_feedback(id,client_id,score,comment,month,year,created_at) values(${id},${c.id},${score},${clean(args.comment,2000)||null},${now.getMonth()+1},${now.getFullYear()},now())`);await db.execute(sql`update clients set nps_score=${score},updated_at=now() where id=${c.id}`);await audit(userId,"vivito_nps_recorded","client_feedback",id,{clientId:c.id,score});return{success:true,action:op,entityId:id,message:`NPS ${score}/10 recorded for ${c.company_name}.`}}
 const referred=email(args.email);if(!validEmail(referred))throw new VivitoActionError("Valid referral email required.");const code=randomBytes(8).toString("hex").toUpperCase(),id=crypto.randomUUID();await db.execute(sql`insert into referrals(id,referrer_id,referred_email,code,status,discount_pct,created_at) values(${id},${userId},${referred},${code},'PENDING',${nonneg(args.discountPct??20)},now())`);await audit(userId,"vivito_referral_created","referrals",id,{email:referred,code});return{success:true,action:op,entityId:id,message:`Referral created for ${referred}.`,code}}
async function bulk(op:VivitoActionOp,args:any,userId:string){if(op==="bulk_update_tasks"){const status=args.status?clean(args.status,30).toUpperCase():null,priority=args.priority?clean(args.priority,30).toUpperCase():null;if(!status&&!priority)throw new VivitoActionError("Bulk task status or priority is required.");const clientId=args.clientName?(await client(args.clientName)).id:null;const overdue=Boolean(args.overdue);const candidateRows=rows(await db.execute(sql`select id from creative_tasks where workspace_id=${tenantId()} and archived_at is null ${clientId?sql`and client_id=${clientId}`:sql``} ${overdue?sql`and deadline<now() and status not in ('COMPLETED','REJECTED')`:sql``} order by id limit 201`));if(candidateRows.length>200)throw new VivitoActionError("Bulk operation exceeded the 200-record safety cap.",409);const ids=candidateRows.map(x=>String(x.id));const idList=sql.join(ids.map(id=>sql`${id}`),sql`,`);const affected=ids.length?rows(await db.execute(sql`update creative_tasks set status=coalesce(${status},status),priority=coalesce(${priority},priority),updated_at=now() where workspace_id=${tenantId()} and id in (${idList}) returning id`)):[];await audit(userId,"vivito_bulk_tasks_updated","creative_tasks","bulk",{count:affected.length,status,priority,clientId,overdue});return{success:true,action:op,message:`Updated ${affected.length} tasks.`,count:affected.length}}
 const min=nonneg(args.minimumOutstanding||0);const clientsDue=rows(await db.execute(sql`select c.id,c.company_name,coalesce(sum(f.outstanding),0)::float outstanding from clients c join finance_records f on f.client_id=c.id where c.workspace_id=${tenantId()} and c.is_active=true and f.workspace_id=${tenantId()} and f.outstanding>${min} group by c.id,c.company_name limit 100`));for(const x of clientsDue)await db.execute(sql`insert into notifications(id,user_id,type,title,message,link,priority,created_at) select gen_random_uuid()::text,u.id,'PAYMENT_REMINDER',${`Payment follow-up: ${x.company_name}`},${`Outstanding balance: ${Number(x.outstanding).toFixed(2)}`},'/dashboard/clients/accounts-payment','high',now() from users u where u.workspace_id=${tenantId()} and u.role in ('SUPER_ADMIN','ACCOUNTANT') and u.is_active=true`);await audit(userId,"vivito_bulk_payment_reminders","notifications","bulk",{clients:clientsDue.length});return{success:true,action:op,message:`Created payment follow-up reminders for ${clientsDue.length} clients.`,count:clientsDue.length}}

export async function executeVivitoOperatorAction(op:VivitoActionOp,args:unknown,role:string,userId:string,workspaceId:string){if(!workspaceId)throw new VivitoActionError("Workspace unavailable.",403);return workspaceContext.run(workspaceId,async()=>{authorize(role,op);if(op==="create_user")return createUser(args,userId);if(op==="update_user"||op==="set_user_active")return updateUser(op,args,userId);if(op==="create_leave_request")return createLeave(args,role,userId);if(op==="decide_leave")return decideLeave(args,userId);if(op==="upsert_payroll"||op==="set_payroll_status")return payrollAction(op,args,userId);if(op==="create_contract"||op==="update_contract")return contractAction(op,args,userId);if(op==="update_workspace_settings")return settings(args,userId);if(op==="send_email")return sendEmail(args,userId);if(op==="send_whatsapp")return sendWhatsApp(args,userId);if(op==="create_api_key"||op==="revoke_api_key")return apiKeyAction(op,args,userId);if(op==="create_webhook"||op==="revoke_webhook")return webhookAction(op,args,userId);if(op==="sync_campaign"||op==="update_campaign")return campaignAction(op,args,role,userId);if(op==="start_integration"||op==="disconnect_integration")return integrationAction(op,args,userId);if(op==="export_data"||op==="generate_report")return exportReport(op,args);if(op==="update_onboarding"||op==="record_nps"||op==="create_referral")return opsData(op,args,userId);if(op==="bulk_update_tasks"||op==="bulk_remind_clients")return bulk(op,args,userId);throw new VivitoActionError("Unsupported Full Operator action.",400)})}
