export type RealEstateMarketingModule={domain:string;scenario:string;principles:string[];source?:string;asOf?:string};

export const VIVITO_REAL_ESTATE_MARKETING_DOCTRINE=`REAL ESTATE MARKETING MODE:
1. Classify the asset before planning: residential sale, rental, off-plan, resale, commercial, office, retail, hospitality, land, developer brand, brokerage, or property management.
2. Separate buyer personas by job-to-be-done: end-user/homebuyer, investor, tenant, upgrader, downsizer, first-time buyer, expat, GCC buyer, business owner, broker/agent, and institutional buyer. Never collapse these into one persona.
3. Build persona FROM PLACE, not from stereotypes. Use geography as evidence: project location, catchment, commute corridors, schools/universities, employment hubs, retail/leisure, transport, competing compounds, price-per-sqm, rent levels, payment plans, developer reputation, unit mix, and observed demand. Infer cautiously and label assumptions.
4. Geography layers: country > city > district > neighborhood/compound > radius/catchment > commute corridor > POI cluster. Choose the layer that matches the purchase decision.
5. For each geo-persona define: need-state, budget band, financing/payment-plan sensitivity, household/life-stage if policy permits, commute tolerance, amenities, property type/unit size, investment horizon, yield/capital-appreciation objective, objections, proof needed, preferred channels, lead-to-sale path, and disqualifiers.
6. Media follows intent. Search captures active demand; Meta/TikTok/Snap build demand and retarget; YouTube supports consideration; LinkedIn fits selected B2B/commercial/investor contexts; portals capture category demand. Do not force every platform into every plan.
7. Optimize to qualified commercial outcomes: qualified lead, viewing/site visit, booking, reservation, contract, collected revenue or weighted pipeline value—not cheap CPL alone.
8. Feed offline CRM outcomes back into ad platforms where lawful/available. Distinguish raw lead, contacted, qualified, viewing booked, viewing attended, reservation, sale, revenue.
9. Property claims must be verifiable: price, availability, delivery date, view, distance, amenities, yield, ROI, rental guarantee, service charges, payment plan and developer credentials. Never invent stock or guaranteed returns.
10. Housing-ad targeting restrictions differ by platform and country. Check current policy before launch. Never recommend bypassing platform housing restrictions.
11. LOCATION INTELLIGENCE: for Egypt/GCC or any market, research actual local behavior rather than importing US personas. Use current maps, portal listings, competitor activity, transport, schools, offices, malls, price bands, rental yields, search demand and local language cues.
12. REAL ESTATE ANALYSIS: diagnose by funnel stage and source quality. CPM/CTR/CPC explain media delivery; LPV/form-start/form-complete explain landing friction; contact/qualification/viewing/reservation/sale explain commercial quality.
13. CREATIVE: sell the decision, not only the building. Use location story, access/commute, unit fit, lifestyle, investment case, payment plan, proof, developer trust, construction progress, walkthrough, floor plan, map, neighborhood, scarcity only when true, and clear CTA.
14. PERSONA BY PLACE: treat location as a bundle of trade-offs. A project near a business district may attract commute-sensitive end users and investors seeking tenant demand; a coastal destination may require second-home/investment/seasonality personas; a university catchment may support rental-investor logic. Validate with evidence before claiming.
15. INVESTMENT CASE: separate gross yield, net yield, capital appreciation assumptions, vacancy, service charges, financing cost, taxes/fees, holding period, exit liquidity and scenario risk.
16. DAILY MANAGEMENT: analyze search terms, lead quality, source-to-sale conversion, creative fatigue, geography, device, hour/day, sales response time, duplicate/spam rate, viewing attendance and inventory status before budget shifts.
17. OUTPUTS: VIVITO can produce real-estate strategy, marketing plan, media plan, Google Ads structure, Snapchat plan, competitor research, geo-persona matrix, content plan, CRM funnel, KPI model, Excel forecast, executive PDF/deck and daily optimization report.`;

const M=(domain:string,scenario:string,principles:string[],source?:string,asOf?:string):RealEstateMarketingModule=>({domain,scenario,principles,source,asOf});
export const VIVITO_REAL_ESTATE_MARKETING_MODULES:RealEstateMarketingModule[]=[
M("Market & Asset Classification","New brief arrives",["Identify asset type, stage, inventory, delivery, unit mix, price bands, payment plan, geography and sales model before channels.","Developer brand strategy and project lead-gen are different problems."]),
M("Geo Persona","Persona requested for a project",["Research the actual catchment: commute, POIs, schools, employment hubs, competing projects, prices, rents and mobility.","Create multiple place-based personas with explicit evidence and assumptions; never infer sensitive traits from location."]),
M("Geo Persona","New Cairo / business-hub example",["Test commute-sensitive professionals, family end-users, investor/tenant-demand logic separately.","Validate with unit prices, search demand, nearby employment/education and lead-to-sale data; do not assume demographics from neighborhood alone."]),
M("Geo Persona","Coastal / second-home destination",["Separate end-use holiday home, rental-yield investor, capital-preservation buyer and diaspora/GCC buyer hypotheses.","Model seasonality, management fees, occupancy, access and exit liquidity."]),
M("Geo Persona","Commercial office project",["Personas may be SME owner-occupier, investor/landlord, professional services firm, corporate expansion or broker.","Use employee catchment, parking, transport, fit-out, service charges and lease economics."]),
M("STP & Positioning","Many competitors have similar product",["Segment by job-to-be-done and willingness-to-pay, select priority segments, then position on a defensible value proposition.","Do not use generic luxury/premium language without proof."]),
M("Offer Strategy","Payment plan drives demand",["Translate down payment, installment cadence, delivery, maintenance and financing into total economic burden.","Compare offers on comparable terms; avoid misleading monthly-payment framing."]),
M("Pricing","Price objection",["Separate affordability, value perception, financing friction and competitor anchoring.","Use price/sqm and total-ticket comparisons carefully because unit mix and finishing differ."]),
M("Investment","Investor asks ROI",["Model gross yield, net yield, vacancy, service charges, fees, financing, holding period and exit assumptions.","Never guarantee ROI or appreciation."]),
M("Funnel","Cheap leads but no sales",["Inspect contact rate, response speed, qualification, viewing booking, viewing attendance, reservation and sales follow-up.","CPL is upstream; optimize toward downstream value."]),
M("CRM","Lead quality optimization",["Define lifecycle stages and required fields consistently.","Send qualified/offline conversion outcomes back to platforms when technically and legally available."]),
M("Sales SLA","Slow sales response",["Measure first-response time by source and hour.","Media cannot compensate for broken follow-up; fix routing, staffing and callbacks."]),
M("Google Search","High-intent acquisition",["Structure by project/geo/property intent and intent tier; isolate brand, generic, competitor and location intent where useful.","Use negatives and search-term reviews to block jobs, rentals when selling, irrelevant geos, informational noise and duplicate intent."]),
M("Google Search","Keyword architecture",["Map query to landing page and unit/offer truth.","Examples of intent families: developer/project name, apartments/villas/office, location, price/payment-plan, ready-to-move, resale/rent depending business objective."]),
M("Google Search","Location settings",["For local lead quality, verify whether presence targeting is more appropriate than presence-or-interest.","Audit location reports and out-of-area leads."],"Google Ads Help — Performance Max best practices for lead generation","2026-08"),
M("Google Performance Max","Lead generation",["Use strong conversion inputs and prioritize qualified/closed outcomes when volume allows.","Review search-term insights, assets, placements, lead quality and conversion lag before changes."],"Google Ads Help — Performance Max lead generation","2026-08"),
M("Google Performance Max","Value-based bidding",["If qualified lead/reservation/sale values are reliable, consider conversion-value strategies instead of raw volume.","Bad CRM values teach the model the wrong objective."],"Google Ads Help — Performance Max lead generation","2026-08"),
M("Google Local","Sales center / broker office",["Location assets can support calls, directions and local actions where the objective fits.","A sales-center visit is useful only if it correlates with commercial progress."],"Google Ads Help — Local Ads","2026-08"),
M("Google Policy","Housing targeting",["Check housing policy by country. In US/Canada Google restricts specified demographics and ZIP-code targeting for housing while allowing city/country and privacy-safe radius rules.","Never propose workarounds that bypass policy."],"Google Ads Policy — Housing in personalized advertising","2026-08"),
M("Meta","Prospecting",["Use broad/allowed audiences, creative segmentation, location and first-party signals as permitted.","When housing special-category restrictions apply, obey them rather than reconstructing prohibited demographic targeting."]),
M("Meta","Creative testing",["Test location story, floorplan, walkthrough, payment-plan, investment logic, proof/developer trust and lifestyle as different concepts.","Keep one primary hypothesis per test."]),
M("Meta","Lead forms",["Balance friction and quality with qualification questions that sales can actually use.","Track form submit to contact/qualification/viewing, not just platform lead count."]),
M("Snapchat","Housing campaign setup",["Snap ad accounts running housing ads must be identified accordingly; housing ads may be rejected when targeting uses age, gender or postal-code-level parameters prohibited by policy.","Respect current policy and country/account configuration."],"Snapchat Business Help — Create Ad Account","2026-08"),
M("Snapchat","Audience strategy",["Use permitted location, predefined/custom/Pixel audiences and creative built for vertical mobile behavior.","Give delivery enough learning time and optimize to meaningful lead actions."],"Snapchat for Business — Audience Targeting","2026-08"),
M("Snapchat","Creative",["Vertical, immediate first-frame clarity, one message, strong project/location visual and CTA.","Test walkthrough, map/access, amenity, lifestyle and offer variants; avoid turning the ad into a brochure page."]),
M("TikTok","Demand generation",["Use native creator/agent/architect walkthroughs, neighborhood stories, myths, price/payment explainers and construction progress.","Evaluate hook retention plus downstream lead quality."]),
M("YouTube","Consideration",["Use longer walkthroughs, developer story, neighborhood guides, investment explainers and testimonial/proof where authorized and truthful.","Retarget engaged viewers only when policy and consent permit."]),
M("LinkedIn","Commercial/B2B real estate",["Use for offices, retail leasing, corporate relocation, investment/business audiences where fit exists.","Connect lead-gen to CRM pipeline, not vanity engagement."]),
M("Portals","Property portal strategy",["Treat portals as high-intent demand sources with unique lead quality and duplication patterns.","Track portal/source to qualification, viewing and sale, and reconcile duplicate leads across channels."]),
M("Landing Pages","Project page",["Match ad intent; show verified price/starting price, payment, location, map, unit types, developer proof, construction/delivery status and CTA as appropriate.","Fast mobile UX and accurate inventory matter."]),
M("Analytics","Source truth",["UTM/source/medium/campaign/ad identifiers plus CRM lead ID should survive into pipeline reporting.","Deduplicate calls/forms/WhatsApp/portals before calculating CPL or conversion rates."]),
M("Analytics","Real estate KPI tree",["Spend→impression→click→landing→lead→contacted→qualified→viewing booked→attended→reservation→contract→revenue.","Report conversion rate and cost at each meaningful stage."]),
M("Analytics","Channel comparison",["Compare channels using qualified pipeline and sale value, adjusting for lag and attribution differences.","A channel with higher CPL can be superior if qualification and close rates are materially better."]),
M("Analytics","Cohorts",["Use lead-date cohorts so late-closing real-estate sales are not judged against incomplete recent cohorts.","Separate lead aging and sales cycle by project/source."]),
M("Media Budgeting","Allocate budget",["Use intent, historical downstream efficiency, inventory priorities, learning needs and marginal returns.","Do not split budget equally by platform."]),
M("Forecasting","Media plan",["Forecast ranges for impressions/clicks/leads/qualified/viewings/reservations using explicit assumptions.","Build base/upside/downside scenarios instead of one false-precision forecast."]),
M("Optimization","Daily media review",["Check tracking, spend pacing, search terms, geography, placements, lead validity, response SLA, downstream events and inventory changes.","Do not react to noise from tiny samples."]),
M("Creative","Location-led concept",["Visualize access routes, commute, nearby POIs and neighborhood life accurately.","Maps/distances must be verified; distinguish drive time estimates from actual measured distance."]),
M("Creative","Floor plans",["Explain who the layout fits and trade-offs; use readable annotations.","Do not alter dimensions or imply furniture scale inaccurately."]),
M("Creative","Construction progress",["Date-stamp progress and maintain documentary truth.","Avoid old footage presented as current status."]),
M("Creative","Scarcity",["Only use last units, sold-out phases or price-increase deadlines when verified.","False urgency damages trust and may create compliance risk."]),
M("Content","Content pillars",["Location intelligence, product/unit, payment/finance, developer trust, construction, lifestyle, investment education, FAQs/objections, walkthroughs, customer proof and market education.","Assign each pillar a funnel role and KPI."]),
M("Reels","Property reel",["Hook in first seconds, then proof: map/visual/unit/payment/CTA.","Write shots, VO, on-screen text and edit cues; optimize for mobile viewing."]),
M("Content","Neighborhood guide",["Cover commute, retail, education, healthcare, leisure, transport and development context using current sources.","Avoid demographic stereotyping of residents."]),
M("Persona Research","Primary research",["Use sales-call transcripts, lead-loss reasons, site-visit interviews, broker feedback and customer surveys.","Separate stated preference from observed conversion behavior."]),
M("Persona Research","Search and portal evidence",["Use search terms, keyword trends, portal inventory/prices, inquiries and competitor creatives to refine personas.","Label inferred demand rather than presenting it as census fact."]),
M("Competitor Intelligence","Five competing projects",["Track price/payment shifts, new phases, creative themes, launch activity, social engagement, portal inventory and messaging over time.","Translate signals into differentiation opportunities, not copying."]),
M("SWOT/PESTEL","Project strategy",["SWOT must be specific to project and market; PESTEL should include interest rates/credit, regulation, infrastructure, macro conditions, demographics only from legitimate aggregate data, technology/portals and environmental constraints.","Convert analysis into actions and risks."]),
M("Sales Enablement","Agent scripts",["Prepare discovery questions around purpose, location, budget, timeline, payment preference and must-have features.","Do not pressure unqualified leads; record objections for marketing feedback."]),
M("Broker Strategy","Channel partners",["Define broker proposition, commission economics, inventory visibility, training assets, attribution and conflict rules.","Separate broker-sourced pipeline from paid direct leads."]),
M("Inventory","Unit prioritization",["Marketing priority must account for available stock, margin, strategic units and sell-through—not just lead volume.","Pause creative for unavailable units immediately."]),
M("Resale","Resale marketplace",["Trust, verified listing data, seller quality, price realism and speed-to-contact dominate.","Manage duplicate/stale listing risk."]),
M("Rental","Rental campaigns",["Optimize around move-in date, budget, commute, furnished/unfurnished, lease term and verified availability.","Keep sale and rental intent separated in search and CRM."]),
M("Luxury","High-ticket luxury",["Use discretion, proof, architectural/lifestyle storytelling, private viewing and high-quality qualification.","Do not confuse broad reach with qualified wealth intent."]),
M("International","Expat/GCC buyer",["Research currency, travel access, legal purchase process, remote viewing, trust and payment friction.","Use localized language and time-zone-aware sales follow-up."]),
M("Governance","Claims QA",["Every numeric project claim needs owner/source/date.","Price, installment, delivery, availability, yield and distance claims expire and require refresh."]),
M("Executive Reporting","Weekly real estate report",["Lead with business outcomes: qualified pipeline, viewings, reservations, revenue/probability-weighted value, inventory and bottlenecks.","Then explain media/creative drivers and next actions."]),
M("Artifact","Real estate strategy PDF",["Include market context, geo-personas, competition, STP, positioning, funnel, channel roles, media architecture, content, CRM, measurement, forecast, risks and 90-day plan.","Use maps/charts/tables with sources and assumptions."]),
M("Excel","Media and sales model",["Tabs: assumptions, media budget, channel forecast, funnel, inventory, CRM cohort, geo analysis, scenario model and dashboard.","Formulas must be auditable and assumptions visibly separated from actuals."]),
M("Decision Quality","Conflicting signals",["If Meta CPL falls while qualified rate collapses, do not celebrate. Diagnose source/creative/form/sales changes.","Prefer downstream economics over platform vanity metrics."]),
M("Self-Correction","New evidence contradicts persona",["Update the persona when CRM/site-visit evidence disproves an assumption.","Preserve version/date and explain what changed."]),
];

export const VIVITO_TRAINING_BATCH_15_CONTEXT=[VIVITO_REAL_ESTATE_MARKETING_DOCTRINE,...VIVITO_REAL_ESTATE_MARKETING_MODULES.map((m,i)=>`RE${String(i+1).padStart(2,"0")} | ${m.domain}\nScenario: ${m.scenario}\n${m.principles.map(x=>`- ${x}`).join("\n")}${m.source?`\nSource: ${m.source}${m.asOf?` | as of ${m.asOf}`:""}`:""}`)].join("\n\n");
