export type VivitoPdfMasteryRule={domain:string;principle:string;practice:string;qa:string[];source?:string};

export const VIVITO_TRAINING_BATCH_10:VivitoPdfMasteryRule[]=[
{domain:"PDF Product Thinking",principle:"Treat the PDF as a finished executive product, not a text export.",practice:"Define audience, decision, reading mode, page format, visual tone, information density and narrative before designing pages.",qa:["One audience per document","Clear decision objective","Screen-first or print-first choice is explicit"]},
{domain:"Narrative Architecture",principle:"Every PDF must have a beginning, middle and decision-oriented end.",practice:"Use cover > executive summary > evidence > diagnosis > strategic choices > plan > KPIs > risks > appendix. Remove pages that do not advance the decision.",qa:["No orphan pages","No duplicated insight","Executive summary can stand alone"]},
{domain:"Page Story",principle:"One page should communicate one dominant message.",practice:"Use assertion-style headlines, then prove the assertion with one dominant chart, matrix, diagram or structured evidence block.",qa:["One dominant takeaway","Title says the conclusion","Evidence supports title"]},
{domain:"Grid System",principle:"Use a consistent grid and spacing system across every page.",practice:"Build pages on repeatable margins, columns, gutters and baseline spacing; align visual edges across pages.",qa:["Consistent margins","No floating arbitrary alignment","Spacing scale is repeatable"]},
{domain:"Typography",principle:"Typography must create hierarchy before decoration.",practice:"Use a restrained type scale for eyebrow, title, subtitle, body, labels and footnotes. Keep body text comfortably readable and line lengths controlled.",qa:["Clear hierarchy at a glance","No tiny body text","No more type styles than necessary"]},
{domain:"Arabic Typography",principle:"Arabic is designed natively, not treated as mirrored English.",practice:"Use fonts with strong Arabic shaping, appropriate line height, proper RTL alignment, punctuation handling and numerals appropriate to the audience.",qa:["No broken glyph joining","RTL reading order is correct","Arabic line spacing is generous enough"]},
{domain:"Bilingual Layout",principle:"Arabic-English PDFs require deliberate bilingual composition.",practice:"Choose either mirrored bilingual pages, language-separated sections or controlled bilingual blocks; do not randomly mix directional flows.",qa:["Reading direction is obvious","English terms do not break Arabic flow","Labels stay aligned"]},
{domain:"Visual Hierarchy",principle:"The eye should know where to look first, second and third.",practice:"Use scale, position, whitespace and contrast to prioritize evidence. Avoid equal-weight cards everywhere.",qa:["One focal point","Secondary information is visually subordinate","Footnotes never compete with headlines"]},
{domain:"Whitespace",principle:"Premium PDFs use whitespace as structure, not leftover space.",practice:"Leave deliberate breathing room around key numbers, charts and conclusions; reduce content before reducing whitespace.",qa:["No crowded edges","No page filled to 100% density","Important content has breathing room"]},
{domain:"Color System",principle:"Color communicates hierarchy and meaning.",practice:"Use brand colors as accents, semantic colors consistently, and neutral backgrounds for readability. Do not use every brand color on every page.",qa:["Consistent semantic color use","High text contrast","Accent color reserved for priority"]},
{domain:"Cover Design",principle:"The cover establishes credibility before the first data point.",practice:"Use strong title, subtitle, client/brand identity, date/version and one restrained visual idea; avoid template-looking covers overloaded with shapes.",qa:["Title readable instantly","Brand identity clear","No decorative clutter"]},
{domain:"Section Openers",principle:"Long PDFs need visual rhythm.",practice:"Use section divider pages sparingly to reset attention and communicate what the reader is entering.",qa:["Divider adds orientation","Section naming is specific","Style differs from evidence pages"]},
{domain:"Executive Summary",principle:"Executives should understand the document without reading all pages.",practice:"Summarize situation, 3-5 key findings, implications, decisions and immediate actions in a visually prioritized page or spread.",qa:["No generic recap","Contains decisions","Contains economic or strategic implication"]},
{domain:"Charts",principle:"Charts exist to prove a point, not to decorate.",practice:"Choose chart by question: trend=line, comparison=bar, composition=stacked bar, relationship=scatter, funnel=funnel/waterfall only when justified. Highlight the decision-relevant series.",qa:["Chart answers one question","Axes not deceptive","Labels readable","No unnecessary 3D"]},
{domain:"Tables",principle:"Raw tables are not designed evidence.",practice:"Edit, rank, group and visually prioritize rows/columns. Use direct labels, subtle rules and emphasis on decision-relevant values.",qa:["No spreadsheet dump","Headers remain visible","Units and periods explicit"]},
{domain:"Matrices",principle:"Matrices are useful only when axes are meaningful.",practice:"Define axes, scoring method and evidence before plotting competitors, priorities or opportunities.",qa:["Axes have definitions","Positions trace to evidence","No fake precision"]},
{domain:"SWOT / PESTEL Pages",principle:"Framework pages must lead to implications.",practice:"For every factor show evidence, impact, likelihood/time horizon where relevant, then convert into strategic actions or TOWS priorities.",qa:["No dictionary SWOT","Internal/external distinction correct","Priorities are ranked"]},
{domain:"Icons & Illustration",principle:"Visual assets must clarify, not infantilize the document.",practice:"Use one coherent icon family and purposeful illustrations; prefer diagrams or photography when they communicate evidence better.",qa:["Consistent icon style","No mixed clip-art families","No visual with no information value"]},
{domain:"Photography",principle:"Photography must support brand and context.",practice:"Use high-resolution, compositionally useful images with consistent treatment; avoid generic stock-photo clichés when authentic assets exist.",qa:["No pixelation","Image crop supports layout","Usage rights known when required"]},
{domain:"Image Quality",principle:"Raster assets must survive export at intended viewing size.",practice:"Use adequate effective resolution, avoid repeatedly rescaling compressed screenshots, and prefer SVG/PDF/vector for logos, icons and charts.",qa:["No blurry logos","No stretched images","Screenshots legible at 100%"]},
{domain:"Vector Discipline",principle:"Text, logos, icons and charts should remain vector whenever practical.",practice:"Do not rasterize whole pages or charts unless absolutely necessary; preserve crispness and editability upstream.",qa:["Text remains searchable","Logos stay sharp","Charts not flattened unnecessarily"]},
{domain:"Data Labels",principle:"Every important number needs context.",practice:"Include unit, period, geography, denominator and source when relevant; distinguish actual, forecast, target and estimate visually.",qa:["No contextless percentages","Forecast not presented as actual","Currency and period explicit"]},
{domain:"Sources",principle:"Source quality is part of design credibility.",practice:"Use compact page-level source footnotes plus a detailed source appendix/ledger. Include source name, title, date, URL or internal reference and access date where useful.",qa:["No fabricated citation","No unsupported major statistic","Source matches claim"]},
{domain:"Footnotes",principle:"Footnotes must be readable without dominating the page.",practice:"Use a consistent footnote zone, smaller but legible type, stable numbering or source labels and enough contrast.",qa:["Footnotes do not clip","Source text remains readable","Footnote style is consistent"]},
{domain:"Methodology",principle:"Research PDFs must expose how conclusions were produced.",practice:"Include methodology, scope, sample, dates, source hierarchy, limitations and fact-vs-inference conventions before or within findings.",qa:["Method can be audited","Limitations are visible","No implied certainty beyond evidence"]},
{domain:"Appendix",principle:"Move detail out of the executive flow without losing traceability.",practice:"Place detailed methods, full tables, assumptions, definitions, source ledger and calculations in appendix sections with clear navigation.",qa:["Core story remains concise","Appendix referenced from main body","Definitions are findable"]},
{domain:"Navigation",principle:"Professional PDFs are easy to navigate.",practice:"Use table of contents for long documents, bookmarks when the renderer supports them, page numbers and consistent section labels.",qa:["Page numbers correct","TOC matches pages","Bookmarks mirror document hierarchy where supported"]},
{domain:"Accessibility",principle:"Premium means usable by more readers, not only visually polished.",practice:"When renderer capability allows, generate searchable text, tagged structure, logical reading order, document language/title, accessible links and alt text for informative non-text content.",qa:["Text searchable","Reading order logical","Document language set","Alt text present where needed"],source:"Adobe PDF Accessibility; PDF Association PDF/UA"},
{domain:"PDF/UA Awareness",principle:"For accessibility-critical outputs, design with PDF/UA-compatible structure in mind.",practice:"Preserve semantic headings, paragraphs, lists, tables and figures so the renderer can generate tagged PDF with logical structure instead of retrofitting accessibility later.",qa:["Semantic structure exists upstream","Tables have real headers","Decorative elements can be marked artifact"],source:"ISO 14289 / PDF Association"},
{domain:"Links",principle:"Links must look intentional and work after export.",practice:"Use meaningful link text, consistent styling and test every external/internal link after PDF creation.",qa:["No broken links","No raw long URL in body unless necessary","Clickable area matches text"]},
{domain:"Metadata",principle:"A finished PDF has professional metadata.",practice:"Set document title, author/organization, subject, keywords when relevant, language, version/date and filename conventions.",qa:["Filename professional","Title metadata matches cover","Version/date correct"]},
{domain:"Filename & Versioning",principle:"The artifact name is part of delivery quality.",practice:"Use client_project_deliverable_version_date or equivalent controlled naming; never ship final-final-v7.pdf.",qa:["No ambiguous filename","Version traceable","Client name spelled correctly"]},
{domain:"Screen-first Export",principle:"Most strategy PDFs are read on laptops and phones.",practice:"Prioritize RGB-friendly contrast, moderate file size, clickable links, readable type and page dimensions that work on common screens.",qa:["Readable at fit-width","No giant print-only margins","File opens quickly"]},
{domain:"Print-first Export",principle:"Print PDFs need different production controls.",practice:"When print is requested, manage page size, bleed, trim, color profile, image resolution and printer requirements explicitly instead of assuming screen export settings.",qa:["Bleed/trim correct when needed","Printer spec followed","No unexpected RGB/CMYK issue"]},
{domain:"Compression",principle:"Optimize file size without visible degradation.",practice:"Compress oversized raster images intelligently, subset/embed fonts as supported, keep vector content vector and avoid needless duplicate assets.",qa:["No visible JPEG artifacts","File size proportionate","Text remains crisp"]},
{domain:"Font Embedding",principle:"The PDF should not change appearance on another device.",practice:"Use licensed embeddable fonts and ensure glyph coverage for Arabic/English; validate embedded/subset fonts after export when renderer supports it.",qa:["No font substitution","Arabic glyphs preserved","Weight mappings correct"]},
{domain:"Overflow Prevention",principle:"Nothing may clip, collide or overflow page bounds.",practice:"Run layout checks before export and inspect every page after rendering at full size.",qa:["Zero clipped text","Zero overlapping labels","No off-page objects"]},
{domain:"Page Balance",principle:"Pages should feel intentionally composed, not randomly filled.",practice:"Balance visual mass across the page and sequence dense pages with lighter pages to create rhythm.",qa:["No accidental dead corner","No repetitive card wall","Dense pages are justified"]},
{domain:"Consistency QA",principle:"Professional quality is cumulative consistency.",practice:"Audit title positions, margins, page numbers, chart styles, capitalization, date formats, currency formats, icon style and source formatting across all pages.",qa:["No style drift","Formats consistent","Repeated components are identical"]},
{domain:"Content QA",principle:"Beautiful wrong content is still wrong.",practice:"Verify calculations, totals, chart labels, spelling, brand names, dates, currencies, references and recommendations against source data before export.",qa:["Numbers reconcile","No unsupported claim","No typo in key title"]},
{domain:"Visual QA",principle:"Inspect the rendered PDF, not only the source layout.",practice:"Render and inspect every page for clipping, font fallback, image corruption, bad line breaks, transparency issues, spacing and contrast.",qa:["Every page inspected","No render-only defects","RTL remains correct after export"]},
{domain:"Narrative QA",principle:"The final PDF must tell one coherent story.",practice:"Read only page titles in sequence; if the storyline does not make sense, rewrite or reorder pages before delivery.",qa:["Titles alone form a logical argument","No conclusion appears before evidence","Recommendations trace to findings"]},
{domain:"Executive Standard",principle:"A premium PDF should feel boardroom-ready.",practice:"Prefer fewer stronger messages, quantified implications, explicit choices, named owners and timelines over decorative volume.",qa:["Can be presented without apology","Decision is obvious","Next action is obvious"]}
];

export const VIVITO_PDF_MASTER_DOCTRINE=`
VIVITO EXECUTIVE PDF MASTER DOCTRINE
A professional PDF is a designed decision system. Never dump generated prose into pages.
Before layout: define audience, objective, storyline, format, language direction, evidence hierarchy and visual system.
During layout: one dominant message per page; assertion title; one main visual; consistent grid, typography, spacing and sources.
For Arabic: use true RTL composition, correct shaping and bilingual layout rules; never mirror English blindly.
For research: every important claim must be traceable; facts, inference and recommendations must not be visually conflated.
For accessibility-capable renderers: preserve semantic structure, searchable text, logical reading order, document language, tagged headings/tables/figures and alt text.
Before delivery: run CONTENT QA + VISUAL QA + ACCESSIBILITY QA + NAVIGATION QA + EXPORT QA + NARRATIVE QA on every page.
Never claim 100% quality as a fact before rendered-file inspection. The quality target is zero known defects, full traceability and boardroom-ready presentation.
Never claim a PDF binary exists unless an actual renderer produced a file and the file passed post-render QA.
`;

export const VIVITO_TRAINING_BATCH_10_CONTEXT=VIVITO_TRAINING_BATCH_10.map((x,i)=>`### PDF Mastery ${i+1} — ${x.domain}\nPrinciple: ${x.principle}\nPractice: ${x.practice}\nQA: ${x.qa.join(" | ")}${x.source?`\nSource: ${x.source}`:""}`).join("\n\n");