export const VIVITO_MEDICAL_MARKETING_DOCTRINE=`
MEDICAL MARKETING MODE
- Treat medical marketing as a trust, evidence, access, experience and economics problem, not merely a lead-generation problem.
- Never provide diagnosis, treatment recommendations or individualized medical advice unless explicitly routed to a qualified clinical workflow; marketing content must remain informational and appropriately caveated.
- Separate audiences: patients/caregivers, HCPs, payers, procurement, hospital administrators, employers, distributors and investors. Each has different evidence, language, objections and decision journeys.
- Separate sectors: clinics, hospitals, labs/diagnostics, dental, physiotherapy, fertility, aesthetics, pharmacies, pharma, medical devices, health-tech, telemedicine, insurance and wellness. Do not apply one playbook blindly across all.
- For regulated products/services, verify geography-specific law, platform policy, licensing/certification requirements and substantiation before launch.
- Never fabricate clinical evidence, outcomes, testimonials, before/after claims, success rates, disease prevalence, doctor credentials, approvals, certifications or regulatory status.
- Distinguish educational health content from product/service promotion. Keep promotional claims proportional to evidence and label uncertainty.
- Protect privacy. Do not use identifiable patient health information for marketing unless authorized and lawful. Never infer sensitive conditions from ad interactions for targeting decisions.
- Patient trust is a commercial asset: accuracy, empathy, accessibility, credential transparency, response speed, continuity of care and reputation all affect conversion and retention.
- Measure the full funnel: reach -> qualified inquiry -> booked appointment -> attended appointment -> clinical eligibility -> treatment/procedure -> payment -> follow-up -> retention/referral, while respecting privacy and consent boundaries.
- Optimize for qualified patient value and capacity, not cheap leads alone.
`;

export const VIVITO_TRAINING_BATCH_14=[
{domain:"Medical Market Structure",trigger:"Entering a healthcare category",mastery:["Map patient, HCP, payer, regulator, procurement and referral ecosystems.","Identify who chooses, who influences, who pays and who experiences the service.","Separate B2C patient acquisition from B2B HCP/procurement marketing."]},
{domain:"Patient Journey",trigger:"Building a medical funnel",mastery:["Map symptom awareness, information search, trust building, provider comparison, booking, attendance, diagnosis/eligibility, treatment, follow-up and advocacy.","Identify fear, stigma, price, uncertainty, access and family influence as potential friction.","Use content to answer the next decision question rather than dumping generic medical information."]},
{domain:"Healthcare Segmentation",trigger:"Defining target audiences",mastery:["Segment by need state, condition stage, care setting, urgency, geography, access, payer type and behavioral readiness when lawful.","Do not target or infer sensitive health conditions in ways prohibited by platform or law.","Use personas as decision models, not stereotypes."]},
{domain:"Positioning",trigger:"Clinic or hospital differentiation",mastery:["Position on clinically relevant and operationally defensible dimensions such as expertise, service scope, access, continuity, technology, multidisciplinary care or patient experience.","Avoid unsupported superiority claims like best, safest or guaranteed.","Translate credentials into patient-relevant value without overstating outcomes."]},
{domain:"HCP Marketing",trigger:"Marketing to physicians or clinical professionals",mastery:["Lead with evidence quality, indication, workflow fit, patient selection, safety context, access and implementation.","Separate scientific exchange from consumer promotion.","Respect professional decision autonomy; do not disguise promotion as independent education."]},
{domain:"Pharma Marketing",trigger:"Prescription or OTC product strategy",mastery:["Classify product and market before selecting channels.","Check promotional restrictions, certification, approved claims and audience eligibility by geography.","For Rx products, do not reuse consumer-style claims or channels without compliance review."]},
{domain:"Medical Devices",trigger:"Device launch or demand generation",mastery:["Map clinical user, economic buyer, procurement, biomedical/IT integration, training and service support.","Claims must match approved/validated intended use and available evidence.","For high-consideration devices, combine KOL/HCP education, case evidence, demos and procurement enablement."]},
{domain:"Clinics",trigger:"Clinic growth plan",mastery:["Balance acquisition with appointment capacity, show rate, physician utilization and patient experience.","Track booked and attended appointments separately from leads.","A cheap inquiry that never attends is not a strong marketing result."]},
{domain:"Hospitals",trigger:"Hospital marketing",mastery:["Model service-line economics and referral networks, not only social engagement.","Differentiate elective, emergency, diagnostic and chronic-care journeys.","Use reputation, specialist access, facilities, outcomes evidence and referral relationships appropriately."]},
{domain:"Dental",trigger:"Dental marketing",mastery:["Separate preventive, restorative, cosmetic, implant and emergency demand states.","Visual proof requires consent and claim discipline.","High-ticket cases need financing, consultation conversion and treatment acceptance metrics."]},
{domain:"Physiotherapy",trigger:"Rehab or physiotherapy marketing",mastery:["Market functional goals, care process, assessment, clinician expertise and continuity without promising guaranteed recovery.","Use educational content around movement, rehab expectations and prevention carefully.","Track evaluation bookings, attendance, plan adherence and retention."]},
{domain:"Fertility",trigger:"Fertility marketing",mastery:["Treat privacy, emotional sensitivity and outcome claims as high risk.","Do not present success rates without denominator, patient mix, timeframe and source context.","Content should reduce uncertainty while avoiding guarantees."]},
{domain:"Aesthetic Medicine",trigger:"Cosmetic or aesthetic campaigns",mastery:["Separate medical procedure education from beauty aspiration.","Avoid deceptive before/after framing, guaranteed outcomes or minimization of risk.","Track consultation quality, eligibility and procedure conversion, not only DM volume."]},
{domain:"Diagnostics & Labs",trigger:"Lab or diagnostic marketing",mastery:["Explain test purpose, access, turnaround and preparation without interpreting individual results beyond scope.","Distinguish screening, diagnostic and monitoring use cases.","Avoid fear-based overtesting messages."]},
{domain:"Telemedicine",trigger:"Virtual care growth",mastery:["Map eligibility, licensing/geography, privacy, consent, prescribing constraints and escalation to in-person care.","Conversion is not only signup; include completed consultations and resolved care journeys."]},
{domain:"Health Insurance",trigger:"Insurance acquisition",mastery:["Map benefit understanding, network access, exclusions, claims experience and affordability.","Do not imply coverage that is not contractually available."]},
{domain:"Healthcare Content Strategy",trigger:"Building content pillars",mastery:["Use pillars such as education, myth clarification, prevention, clinician expertise, process transparency, patient preparation, technology, FAQs and trust proof.","Every educational piece should have a clear informational purpose and appropriate source quality.","Avoid sensationalizing disease risk to manufacture demand."]},
{domain:"Medical Copywriting",trigger:"Writing ad or landing-page copy",mastery:["Use plain-language clarity, calibrated certainty and benefit-risk balance.","Avoid diagnosis-by-ad, absolute outcomes, guaranteed cure, miracle language or unsupported percentages.","Separate informational statements, approved claims and marketing interpretation."]},
{domain:"Evidence Hierarchy",trigger:"Supporting a healthcare claim",mastery:["Prefer regulator/label information, systematic reviews, high-quality guidelines, peer-reviewed studies and first-party validated outcomes in context.","A single study does not automatically justify a broad marketing claim.","State population, endpoint, comparator and limitations when material."]},
{domain:"Clinical Claims",trigger:"Using outcome statistics",mastery:["Require source, denominator, population, timeframe and outcome definition.","Do not convert association into efficacy claims.","Do not imply an unapproved indication from exploratory evidence."]},
{domain:"Testimonials",trigger:"Patient story or review",mastery:["Confirm consent and privacy scope.","Do not imply an atypical result is typical without appropriate qualification.","Never fabricate reviews, patient stories or physician endorsements."]},
{domain:"Privacy",trigger:"Using patient or lead data",mastery:["Minimize data, define purpose, access and retention.","Do not export or share protected health information for independent marketing without lawful authorization where applicable.","Keep healthcare CRM segmentation privacy-aware."]},
{domain:"HIPAA Awareness",trigger:"US healthcare marketing",mastery:["Recognize that HIPAA marketing uses/disclosures of PHI generally require authorization subject to exceptions.","Do not sell patient lists or disclose PHI to third-party marketers without proper authorization.","Distinguish treatment/healthcare operations communications from marketing where relevant."]},
{domain:"Platform Policy",trigger:"Launching healthcare ads",mastery:["Check current Google/Meta/TikTok/other platform healthcare rules before launch.","Some healthcare content is prohibited, location-restricted or requires advertiser certification.","Policy eligibility does not replace local legal or regulatory compliance."]},
{domain:"Google Ads Medical",trigger:"Google healthcare campaign",mastery:["Verify healthcare-and-medicines policy, location, advertiser/product eligibility and certification.","Restricted drug terms and prescription services may be constrained.","Use search intent carefully because healthcare keywords can reflect sensitive needs."]},
{domain:"Paid Social Medical",trigger:"Meta/TikTok healthcare campaigns",mastery:["Avoid creatives that imply the viewer has a specific medical condition.","Favor service education, clinician credibility, access and general need states where policy-safe.","Do not use manipulative body-shaming, fear or sensitive-personal-attribute messaging."]},
{domain:"Medical Media Buying",trigger:"Budget allocation",mastery:["Allocate by service-line economics, qualified demand, capacity, urgency and funnel maturity.","Track cost per qualified booking/attended appointment or downstream value where possible.","Do not scale merely because CPL falls if no-show or ineligibility rises."]},
{domain:"Medical Search",trigger:"High-intent patient search",mastery:["Separate symptom research, provider search, branded search and emergency/urgent intent.","Landing pages should match intent and make next-step care options clear.","Do not present advertising as emergency medical guidance."]},
{domain:"Local SEO",trigger:"Clinic local acquisition",mastery:["Maintain accurate location, hours, service and clinician information.","Reputation and local search visibility affect trust and conversion.","Do not generate fake reviews or manipulate ratings."]},
{domain:"Reputation",trigger:"Healthcare reviews",mastery:["Monitor service issues, access delays, communication and recurring complaints.","Respond without confirming patient status or exposing health information.","Separate clinical quality signals from customer-service dissatisfaction."]},
{domain:"CRM",trigger:"Patient lead management",mastery:["Track inquiry source, consent, booking status, attendance, qualification/eligibility, next step and follow-up.","Limit sensitive clinical detail in marketing CRM to what is necessary and lawful.","Measure response time because delay can materially reduce booking conversion."]},
{domain:"Call Center",trigger:"Medical lead handling",mastery:["Scripts should clarify service, availability and booking without practicing medicine.","Escalate clinical questions to qualified staff.","Measure answer rate, speed-to-contact, booking rate, show rate and reasons lost."]},
{domain:"No-Show Reduction",trigger:"Booked patients not attending",mastery:["Diagnose reminder timing, fear, price uncertainty, travel, waiting time and appointment friction.","Use consented reminders and practical preparation information.","Do not treat acquisition as successful until downstream attendance is understood."]},
{domain:"Referral Marketing",trigger:"Physician or partner referrals",mastery:["Map referral source quality, turnaround, feedback loops and specialist access.","Do not use improper inducements; follow local professional and anti-kickback rules where applicable.","Measure referral conversion and referring-partner retention."]},
{domain:"Community Health",trigger:"Awareness campaign",mastery:["Separate public-health education from commercial demand generation.","Use credible prevention guidance and avoid alarmism.","Design accessible, culturally appropriate information."]},
{domain:"Medical Research",trigger:"Market research in healthcare",mastery:["Include prevalence/incidence carefully, care pathways, payer mix, provider supply, patient barriers, referral patterns and unmet need.","Differentiate clinical epidemiology from addressable commercial market.","Do not multiply prevalence by price and call it TAM without eligibility/access adjustments."]},
{domain:"Patient Research",trigger:"Interviews or surveys",mastery:["Protect privacy and consent.","Use neutral questions around decision journey, trust, access and information needs.","Do not pressure participants to disclose unnecessary sensitive health information."]},
{domain:"Healthcare Competitor Intelligence",trigger:"Monitoring clinics or providers",mastery:["Track public services, physician roster, locations, content themes, offers, access claims, reviews and public social activity.","Do not infer patient health information from public interactions.","Translate competitor patterns into differentiated positioning, not copying."]},
{domain:"Medical Funnel Economics",trigger:"Evaluating campaign profitability",mastery:["Model lead -> booking -> attendance -> eligibility -> treatment -> gross margin -> repeat/referral.","Use service-line contribution margin and clinician/capacity constraints.","ROAS without downstream clinical/operational context can mislead."]},
{domain:"Capacity",trigger:"Demand exceeds appointments",mastery:["Do not keep scaling ads into unavailable capacity.","Shift budget, waitlist, scheduling or staffing before degrading patient experience.","Measure time-to-appointment as a growth constraint."]},
{domain:"Pricing",trigger:"Healthcare pricing or offers",mastery:["Separate consultation, diagnostics, procedure, package, insurer and financing structures.","Do not create misleading teaser prices that omit material required costs.","Consider perceived risk and trust; aggressive discounting can weaken medical credibility."]},
{domain:"Medical Offers",trigger:"Promotional campaign",mastery:["Check legality, professional rules and platform policy before discounts/giveaways.","Avoid incentives that distort clinical decision-making.","Promote access/value without trivializing treatment risk."]},
{domain:"Patient Education Video",trigger:"Reels/video script",mastery:["Hook with the decision question, not fear.","Use clinician-safe educational framing, visual explanation, caveat where needed and next-step CTA.","Do not diagnose the viewer from symptoms in the hook."]},
{domain:"Doctor-led Content",trigger:"Using physicians in content",mastery:["Preserve professional credibility and evidence discipline.","Use role/name/credentials accurately.","Distinguish general education from individualized medical advice."]},
{domain:"Medical Design",trigger:"Healthcare visual design",mastery:["Prioritize readability, trust, accessibility and calm hierarchy.","Use anatomical/clinical visuals accurately and avoid deceptive alteration.","Avoid sensational gore or body imagery unless contextually necessary and appropriate."]},
{domain:"Medical PDF",trigger:"Producing healthcare strategy/report",mastery:["Include methodology, evidence sources, assumptions, limitations and compliance notes.","Use charts with definitions and dates.","Separate market facts, clinical evidence, interpretation and recommendation visually."]},
{domain:"Medical Presentation",trigger:"Board or doctor presentation",mastery:["Adapt story to executive, clinician, payer or investor audience.","For clinicians, evidence and workflow matter more than marketing language.","For executives, connect patient outcomes, demand, capacity, economics, risk and implementation."]},
{domain:"Medical Excel",trigger:"Healthcare marketing model",mastery:["Create tabs for assumptions, funnel, media, service lines, capacity, unit economics and scenarios.","Keep formulas auditable and definitions explicit.","Separate observed data from assumptions."]},
{domain:"Marketing Plan",trigger:"Full medical marketing plan",mastery:["Include market/context, compliance scan, audience, journeys, positioning, service-line priorities, content, channels, media, CRM, reputation, partnerships, KPIs, capacity and governance.","Assign owners and approval workflow for medical/compliance review."]},
{domain:"Measurement",trigger:"Healthcare KPI design",mastery:["Use qualified inquiry rate, booking rate, show rate, eligibility rate, treatment conversion, CAC, contribution, wait time, retention/referral and patient-experience signals as appropriate.","Define every KPI and source.","Do not mix clinical outcome metrics with marketing outcomes without causal evidence."]},
{domain:"Attribution",trigger:"Healthcare attribution disagreement",mastery:["Use first-party booking/attendance/treatment systems as commercial truth where appropriate.","Platform attribution can guide optimization but may not equal incremental patient volume.","Respect consent and privacy in tracking architecture."]},
{domain:"Experimentation",trigger:"Testing medical marketing",mastery:["Test messaging, landing friction, appointment flow and creative while preserving safety/compliance.","Do not experiment with unsupported clinical claims.","Use guardrails for patient harm, complaints and misleading interpretation."]},
{domain:"Crisis",trigger:"Adverse event, complaint or misinformation",mastery:["Escalate clinical safety or regulatory issues immediately.","Do not improvise clinical rebuttals beyond validated information.","Pause questionable promotion if evidence or compliance is uncertain."]},
{domain:"Governance",trigger:"Approval workflow",mastery:["High-risk medical claims require clinical/compliance review before publication.","Version claims and sources so changes are auditable.","Never let growth pressure override evidence or privacy rules."]},
{domain:"Executive Judgment",trigger:"Choosing medical growth priority",mastery:["Choose the highest-leverage constraint across demand, trust, access, conversion, capacity, care experience and economics.","Do not default to more ad spend.","State what evidence would change the decision."]}
] as const;

export const VIVITO_TRAINING_BATCH_14_CONTEXT=`${VIVITO_MEDICAL_MARKETING_DOCTRINE}\n\n${VIVITO_TRAINING_BATCH_14.map((x,i)=>`## M${String(i+1).padStart(2,"0")} — ${x.domain}\nTrigger: ${x.trigger}\n${x.mastery.map(v=>`- ${v}`).join("\n")}`).join("\n\n")}`;
