export type VivitoDecisionCard={
 id:string;domain:string;trigger:string;diagnose:string[];decide:string[];guardrails:string[];source?:string;asOf?:string;
};

const C=(id:string,domain:string,trigger:string,diagnose:string[],decide:string[],guardrails:string[],source?:string,asOf?:string):VivitoDecisionCard=>({id,domain,trigger,diagnose,decide,guardrails,source,asOf});

export const VIVITO_TRAINING_BATCH_06:VivitoDecisionCard[]=[
 C("P01","Performance","Cost per result rises materially",["Compare equal-length periods before reacting","Separate CPM, CTR, CVR and frequency effects","Check tracking and offer/landing changes before blaming media"],["Fix the highest-confidence bottleneck first","If signal is weak, hold or reduce change size rather than making many edits"],["Never infer a cause from one metric alone","Do not scale a campaign whose unit economics are already bad"]),
 C("P02","Performance","Strong CTR but weak purchases/leads",["Treat click quality and post-click conversion as separate stages","Inspect landing speed, offer-message match, checkout/form friction and sales follow-up"],["Keep winning attention while testing the downstream bottleneck","Change one major causal variable per test where practical"],["Do not call the creative a winner based on CTR alone","Do not increase spend until conversion integrity is understood"]),
 C("P03","Performance","Campaign is profitable and stable and user asks to scale",["Confirm contribution economics, tracking health, delivery stability and capacity","Check whether recent improvement has enough volume to be credible"],["Prefer controlled stepwise scaling with explicit stop-loss guardrails","Monitor marginal CPA/ROAS, not only blended averages"],["Never promise linear scale","Do not let platform ROAS override negative margin or cash constraints"]),
 C("P04","Performance","Frequency rises while CTR falls",["Check whether the decline is concentrated by audience, placement or creative","Distinguish audience saturation from weak new creative"],["Refresh hooks/concepts before blindly expanding budget","Broaden audience only when targeting is plausibly the constraint"],["Frequency is a signal, not a universal threshold","Do not diagnose fatigue from frequency alone"]),

 C("M01","Measurement","Ads platform conversions disagree with backend",["Confirm event definitions, attribution windows, deduplication, time zone and order status","Use backend/first-party records for actual commercial truth while preserving platform attribution for optimization analysis"],["State both numbers and why they can differ","Repair measurement before making aggressive optimization claims"],["Never silently choose the more flattering number","Never merge unlike conversion definitions"]),
 C("M02","Measurement","Tracking is broken or recently changed",["Determine which events are missing, duplicated, delayed or stale","Check whether the affected event is an optimization signal or only reporting"],["Prioritize measurement repair before budget optimization when causally material","Mark recommendations provisional until post-fix data stabilizes"],["Do not optimize from corrupted conversion data","Do not invent missing conversions"]),
 C("M03","Measurement","Platform performance looks strong but business lift is unclear",["Separate attribution from incrementality","Look for controlled experiments, holdouts, lift studies or independent business outcomes"],["Use attribution for day-to-day optimization and experiments for causal confidence","State when evidence proves correlation rather than incrementality"],["A high attributed ROAS does not automatically prove incremental profit"],"TikTok for Business — measurement guidance","2026-08-24"),
 C("M04","Measurement","User asks for a decision on stale/incomplete data",["Identify last sync and missing periods","Separate facts from assumptions"],["Give the best bounded decision that can be made now","Name exactly what fresh evidence would change it"],["Never fabricate freshness","Lower confidence when evidence is stale"]),

 C("CR01","Creative","Video loses viewers in opening seconds",["Judge the first frame, first spoken line, visual movement and immediate relevance","Check whether the benefit/problem appears before brand exposition"],["Rewrite the first 1–2 seconds around a stronger tension, outcome, proof or curiosity hook","Keep the rest of the asset as stable as possible for a clean hook test"],["Do not fix weak retention by adding more information","Do not assume polished production beats native relevance"]),
 C("CR02","Creative","A winning ad is fatiguing",["Identify what actually won: concept, hook, proof, offer, creator or format","Check whether performance decay is audience-specific"],["Create variants around the winning concept before abandoning it","Diversify angle, hook, proof and format systematically"],["Do not make ten cosmetic variants and call it diversification","Preserve the core customer motivator when it is still valid"]),
 C("CR03","Creative","Creative test changes many variables at once",["List changed variables: audience, bid, offer, hook, visual, CTA, landing","Determine whether the result can be attributed"],["Design the next test to isolate the highest-value uncertainty","Use multi-variable exploration only when learning speed matters more than causal precision"],["Do not claim causality from a confounded test"]),
 C("CR04","Creative","Reels/TikTok-style vertical asset is requested",["Check 9:16 composition, safe zones, audio/context and native pacing","Assess whether the creative feels made for the placement"],["Build mobile-first and test placement-native variants","Use A/B testing where the decision is material"],["Do not simply crop a horizontal ad and assume equivalence"],"Meta for Business — Reels ads guidance","2026"),

 C("CO01","Content","Engagement is high but pipeline/sales are weak",["Map content to funnel role and intended action","Check audience relevance, offer bridge and CTA clarity"],["Keep high-attention formats but introduce proof, problem-solution and conversion-oriented content","Measure downstream action, not likes alone"],["Do not label content successful from vanity metrics alone"]),
 C("CO02","Content","Content calendar feels repetitive",["Audit pillars, audience jobs, funnel stages, formats and proof types","Identify overused topic/format combinations"],["Build variation across education, proof, objection, culture, offer and conversion intent","Keep a coherent brand point of view while varying execution"],["Novelty without strategy is not a content plan"]),
 C("CO03","Content","User asks for a stronger caption/script",["Identify audience, single message, desired action and evidence","Remove generic claims the brand cannot prove"],["Lead with relevance, build one persuasive path, finish with one primary CTA","Match tone to brand and user language"],["Do not overload with multiple competing CTAs","Do not fabricate social proof"]),
 C("CO04","Content","Gen Z tone is requested",["Identify the community context and how the audience actually speaks","Separate natural code-switching from forced slang"],["Use concise conversational phrasing and culturally appropriate references","Keep the brand recognizable"],["Never force slang that harms trust or clarity"]),

 C("S01","Sales","Leads are cheap but close rate is weak",["Inspect qualification, source, response speed, contact rate, discovery quality and objection patterns","Compare sales outcomes by campaign/source before blaming lead volume"],["Fix handoff and qualification bottlenecks, then feed quality outcomes back to media","Prioritize speed-to-lead and structured follow-up"],["Cheap CPL is not success if qualified pipeline deteriorates"]),
 C("S02","Sales","Prospect says price is too high",["Clarify whether objection is budget, value, trust, timing or comparison","Re-anchor on outcome, scope and cost of the problem"],["Address the real objection before considering a discount","If discounting, trade it for scope, term, payment timing or commitment"],["Do not immediately discount without diagnosis"]),
 C("S03","Sales","Proposal sent but prospect is silent",["Check decision process, next step, stakeholder and prior objections","Review whether the proposal has a clear business case and deadline"],["Follow up with a specific reason and next action, not repeated 'checking in' messages","Create a defined follow-up sequence with stop conditions"],["Do not fabricate urgency","Do not spam"]),
 C("S04","Sales","Lead is moved to WON",["Confirm commercial agreement and required onboarding data","Check whether the account owner and handoff are defined"],["Create/reuse the client record, preserve source attribution, create handoff tasks and next milestones","Capture what was sold so delivery does not inherit ambiguity"],["Do not mark WON solely because a proposal was sent"]),

 C("B01","Business","Revenue grows while contribution margin is negative",["Separate revenue, gross margin, contribution margin, CAC and operating costs","Identify whether growth worsens cash needs"],["Stop treating top-line growth as success until economics are repaired","Change price, cost-to-serve, mix or acquisition economics before aggressive scale"],["Never recommend scaling negative contribution economics just because ROAS/revenue looks high"]),
 C("B02","Business","User wants a discount to increase conversion",["Estimate conversion lift required to offset margin loss","Check brand positioning and future price anchoring"],["Test value packaging, guarantee, payment terms or scope before permanent price cuts","If discounting, make it bounded and measurable"],["Do not optimize conversion rate at the expense of profitable revenue"]),
 C("B03","Business","Demand exceeds delivery capacity",["Identify bottleneck resource, SLA risk, queue length and margin by segment","Estimate cost of quality failure/churn"],["Throttle low-quality demand, prioritize profitable segments, increase capacity or change service design","Align media/sales pace with delivery capacity"],["Do not keep scaling acquisition into an overloaded operation"]),
 C("B04","Business","User asks which KPI matters",["Start from business objective and economic constraint","Map leading indicators to the final commercial outcome"],["Choose one primary outcome plus a small set of causal leading indicators","Define the metric precisely"],["Do not use impressions/reach as the main business KPI when the goal is leads or sales"]),

 C("A01","Account","Client says ads are bad while numbers look good",["Clarify which business outcome the client cares about","Compare platform metrics with lead quality, sales, margin, delivery and expectations"],["Acknowledge the client concern, show the evidence chain and agree on the business metric that decides success","Create a corrective plan for any gap outside media"],["Do not dismiss the client because platform metrics are green","Do not agree with blame unsupported by evidence"]),
 C("A02","Account","Client approvals are delaying delivery",["Measure approval latency and which work is blocked","Separate agency delay from client dependency"],["Create explicit approval deadlines, escalation path and dependency visibility","Re-plan dates when client delay changes feasible delivery"],["Do not hide dependency risk until deadline day"]),
 C("A03","Account","Client health is deteriorating",["Review performance, communication, revision load, unpaid balance, missed expectations and stakeholder sentiment","Identify the earliest controllable cause"],["Create a retention plan with owner, date and measurable recovery signal","Escalate high-churn-risk accounts early"],["Do not rely on a health score without reading underlying evidence"]),
 C("A04","Account","Scope creep appears",["Compare request to contracted deliverables and prior approvals","Estimate capacity and margin impact"],["Clarify trade-off: replace scope, add fee, extend timeline or decline","Document the decision"],["Do not silently absorb recurring scope that destroys delivery quality or margin"]),

 C("O01","Operations","Many tasks are overdue",["Group by root blocker, owner, client and dependency","Distinguish overloaded capacity from poor prioritization or approval blocks"],["Unblock the constraint first, then rebalance workload and reset feasible deadlines","Use WIP limits when too many jobs are simultaneously open"],["Do not simply mark everything urgent"]),
 C("O02","Operations","One team member is overloaded",["Count active work weighted by effort/urgency and deadline collision","Identify work that can be deferred, reassigned or reduced"],["Protect the critical path and rebalance before adding more work","Escalate recurring capacity mismatch as a planning problem"],["Do not judge workload from task count alone"]),
 C("O03","Operations","A workflow step repeatedly fails",["Find whether failure is people, process, data, tool or dependency","Look for repeated audit events and handoff ambiguity"],["Fix the system constraint, then standardize the improved handoff","Automate only after the process rule is clear"],["Do not automate a broken process faster"]),
 C("O04","Operations","User gives a complex multi-step ERP command",["Resolve dependencies and missing fields before execution","Determine highest risk across all steps"],["Order steps so downstream actions use validated upstream records","Stop on first failure and report completed steps"],["Never invent entity IDs","Never continue after a failed dependency"]),

 C("F01","Finance","Client says they paid an amount",["Resolve the client and outstanding invoices","Check amount, currency, duplicate payment risk and current balances"],["Allocate payment transactionally according to system policy and update payment history","Return the remaining balance clearly"],["Never create money movement from an ambiguous client","Never over-allocate beyond outstanding balance"]),
 C("F02","Finance","User asks whether a client/campaign is profitable",["Separate revenue from cash collected and from contribution profit","Include media cost, fees, fulfillment/cost-to-serve where available"],["State which profit definition is being used","If cost data is missing, say profitability cannot be proven"],["ROAS is not profit"]),
 C("F03","Finance","Receivables are overdue",["Prioritize by amount, age, client risk and relationship context","Check whether invoice/dispute data is complete"],["Create a bounded collections sequence with owner and next date","Escalate large/old balances according to policy"],["Do not send external reminders without authorized recipient and confirmation when required"]),
 C("F04","Finance","User wants to cut an expense",["Classify expense as revenue-enabling, risk-control, productivity or discretionary","Estimate operational consequence of removal"],["Cut low-value recurring cost before capacity/revenue-critical cost","Measure savings against lost output or risk"],["Cheaper is not automatically better"]),

 C("X01","Execution","User asks VIVITO to delete or irreversibly change data",["Resolve exact entity and dependencies","Check role and approval policy"],["Use dry-run/preview where useful and require the prescribed confirmation","Audit the final mutation"],["Never auto-execute destructive actions","Never bypass dependency checks"]),
 C("X02","Execution","User command is ambiguous: similar client/task/person names",["Return candidate ambiguity rather than guessing","Use trusted IDs only after resolution"],["Ask for the minimum disambiguating information in product flow","Execute only after one authorized match remains"],["Never choose the first fuzzy match for a write"]),
 C("X03","Execution","Bulk command affects many records",["Bound the query and preview affected count","Check every record remains in caller scope"],["Use a dry run before high-impact bulk writes","Stop if scope or transition rules are invalid"],["Never translate 'كل حاجة' into an unbounded database mutation"]),
 C("X04","Execution","External ad-platform mutation is requested",["Verify connected account, external campaign ID, token availability and provider-supported field","Distinguish local desired state from provider-confirmed state"],["Call the provider and report success only after provider acceptance","If provider fails, report local/external state separately and audit failure"],["Never claim an external change succeeded from a local database update alone"]),

 C("PL01","Platform — Google Ads","Smart Bidding decision",["Use accurate conversion/conversion-value signals and align bid strategy with business objective","Evaluate over a meaningful period instead of reacting to daily noise"],["Use conversion-based strategies for volume goals and value-based strategies when conversion values represent business value","Treat 2026 label changes as naming changes, not behavior changes"],["Do not optimize to low-value conversions simply because they are plentiful"],"Google Ads Help — Smart Bidding & conversion value","2026-08"),
 C("PL02","Platform — TikTok","TikTok performance campaign is unstable",["Check data connections, campaign structure, creative health and measurement before scaling","Use attribution for operational optimization and experiments/lift for causal questions"],["Keep structure learnable, refresh creative systematically and scale only when measurement is trustworthy","Use the measurement approach that matches the question"],["Do not use one attribution view as proof of incrementality"],"TikTok for Business — Performance Fundamentals & Measurement","2026-08"),
 C("PL03","Platform — Meta","Reels performance improvement",["Check native 9:16 execution, safe-zone readability, audio and placement fit","Use placement-native creative tests"],["Prefer native Reels variants and controlled A/B tests when deciding whether the format change caused lift","Use Advantage placements/creative only when consistent with campaign objective and measurement"],["Do not confuse automated placement recommendations with guaranteed profitability"],"Meta for Business — Reels ads","2026"),
 C("PL04","Platform — LinkedIn","B2B campaign generates activity but uncertain ROI",["Define the valuable conversion and ensure conversion tracking maps to it","Connect lead/conversion outcomes to CRM pipeline when available"],["Optimize toward qualified commercial outcomes, not clicks alone","Use conversion tracking to understand campaign contribution"],["Do not equate form fills with revenue without downstream qualification"],"LinkedIn Ads — conversion tracking guidance","2026-08"),
];

export const VIVITO_TRAINING_BATCH_06_CONTEXT=VIVITO_TRAINING_BATCH_06.map(card=>[
 `## ${card.id} — ${card.domain}`,
 `Trigger: ${card.trigger}`,
 `Diagnose: ${card.diagnose.join(" | ")}`,
 `Decision: ${card.decide.join(" | ")}`,
 `Guardrails: ${card.guardrails.join(" | ")}`,
 card.source?`Source anchor: ${card.source}${card.asOf?` (checked ${card.asOf})`:""}`:"",
].filter(Boolean).join("\n")).join("\n\n");
