type DemoPost={day:number;title:string;platform:string;image:string;time:string};
const MONTHS=["January","February","March","April","May","June","July","August","September","October","November","December"];
const DAYS=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];

export function ClientCalendarDemo({companyName}:{companyName:string}){
 const now=new Date(),year=now.getFullYear(),month=now.getMonth(),firstDay=new Date(year,month,1).getDay(),daysInMonth=new Date(year,month+1,0).getDate();
 const clamp=(n:number)=>Math.min(daysInMonth,Math.max(1,n));
 const posts:DemoPost[]=[
  {day:clamp(5),title:"Campaign Launch Reel",platform:"Instagram",image:"/demo-creative-1.svg",time:"7:00 PM"},
  {day:clamp(12),title:"Brand Story Static",platform:"Facebook",image:"/demo-creative-2.svg",time:"5:30 PM"},
  {day:clamp(19),title:"3 Tips Carousel",platform:"Instagram",image:"/demo-creative-3.svg",time:"8:00 PM"},
  {day:clamp(25),title:"Weekend Engagement Post",platform:"LinkedIn",image:"/demo-creative-2.svg",time:"1:00 PM"}
 ];
 const cells=Array.from({length:firstDay+daysInMonth},(_,i)=>i<firstDay?null:i-firstDay+1);
 return <div style={{display:"flex",flexDirection:"column",gap:18,maxWidth:1180,margin:"0 auto"}}>
  <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div><div style={{display:"inline-flex",padding:"5px 10px",borderRadius:999,background:"#f3e8ff",color:"#7c3aed",fontSize:11,fontWeight:800,marginBottom:8}}>DEMO PREVIEW</div><h1 className="page-title">Content Calendar</h1><p className="page-subtitle">This is how {companyName}&apos;s approved content schedule will look once posts are added.</p></div><div style={{padding:"9px 16px",borderRadius:10,background:"var(--vivit-gradient)",color:"#fff",fontWeight:800}}>{MONTHS[month]} {year}</div></div>
  <div style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:12}}>{posts.slice(0,3).map(p=><div key={p.title} className="card" style={{overflow:"hidden"}}><div style={{display:"grid",gridTemplateColumns:"78px 1fr",gap:12,padding:10,alignItems:"center"}}><img src={p.image} alt="Demo scheduled creative" style={{width:78,height:96,objectFit:"cover",borderRadius:10}}/><div><b style={{fontSize:13}}>{p.title}</b><p style={{fontSize:11,color:"var(--text-muted)",marginTop:5}}>{p.platform} · {p.time}</p><span style={{display:"inline-block",marginTop:9,padding:"4px 8px",borderRadius:999,background:"var(--green-bg)",color:"var(--green)",fontSize:10,fontWeight:800}}>Approved</span></div></div></div>)}</div>
  <section className="card" style={{overflow:"hidden"}}><div style={{padding:16,borderBottom:"1px solid var(--card-border)",display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><b>Monthly schedule</b><p style={{fontSize:11,color:"var(--text-muted)",marginTop:3}}>Click-free preview with sample post thumbnails</p></div><span style={{fontSize:12,color:"var(--text-muted)"}}>{posts.length} demo posts</span></div><div style={{overflowX:"auto"}}><div style={{minWidth:760,padding:12}}><div style={{display:"grid",gridTemplateColumns:"repeat(7,1fr)",gap:6,marginBottom:6}}>{DAYS.map(d=><div key={d} style={{textAlign:"center",fontSize:11,fontWeight:800,color:"var(--text-muted)",padding:8}}>{d}</div>)}</div><div style={{display:"grid",gridTemplateColumns:"repeat(7,1fr)",gap:6}}>{cells.map((day,i)=>{const p=day?posts.find(x=>x.day===day):null;return <div key={i} style={{minHeight:126,border:"1px solid var(--card-border)",borderRadius:12,padding:8,background:day===now.getDate()?"var(--bg-tertiary)":"var(--card-bg)"}}>{day&&<><b style={{fontSize:11,color:"var(--text-secondary)"}}>{day}</b>{p&&<div style={{marginTop:7,borderRadius:9,overflow:"hidden",border:"1px solid var(--card-border)"}}><img src={p.image} alt="" style={{width:"100%",height:58,objectFit:"cover",display:"block"}}/><div style={{padding:6}}><p style={{fontSize:9.5,fontWeight:800,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{p.title}</p><p style={{fontSize:8.5,color:"var(--text-muted)",marginTop:2}}>{p.time}</p></div></div>}</>}</div>})}</div></div></div></section>
  <div style={{padding:13,background:"#fff7ed",border:"1px solid #fed7aa",borderRadius:12,color:"#9a3412",fontSize:12}}><b>Preview only:</b> these sample images and dates are not saved to your account. Real approved creatives will replace them automatically.</div>
  <style>{`@media(max-width:760px){.card-demo-grid{grid-template-columns:1fr!important}} @media(max-width:700px){div[style*="repeat(3,minmax(0,1fr))"]{grid-template-columns:1fr!important}}`}</style>
 </div>
}
