// @ts-nocheck
export const dynamic="force-dynamic";
import {auth} from "@/lib/auth";
import {redirect} from "next/navigation";
import {db,salesLeads} from "@/lib/db";
import {eq,desc,and} from "drizzle-orm";
import {Role} from "@/lib/types";
import Link from "next/link";

const STAGES=[{key:"NEW_LEAD",label:"New",icon:"🌱",color:"#64748B",probability:5},{key:"CONTACTED",label:"Contacted",icon:"📞",color:"#3B82F6",probability:15},{key:"QUALIFIED",label:"Qualified",icon:"✅",color:"#8B5CF6",probability:40},{key:"PROPOSAL_SENT",label:"Proposal",icon:"📋",color:"#F59E0B",probability:60},{key:"NEGOTIATION",label:"Negotiation",icon:"🤝",color:"#EF4444",probability:80},{key:"WON",label:"Won",icon:"🏆",color:"#10B981",probability:100},{key:"LOST",label:"Lost",icon:"✕",color:"#94A3B8",probability:0}];
const money=(n:any)=>new Intl.NumberFormat("en-EG",{style:"currency",currency:"EGP",maximumFractionDigits:0}).format(Number(n||0));
const sourceLabel=(v:any)=>{const s=String(v||"OTHER").toUpperCase();return s.includes("AMAN")?"ONLINE":s.replace(/_/g," ")};
async function allowedLead(id:string,session:any){const role=(session.user as any).role as Role,userId=String((session.user as any).id);const [lead]=await db.select({id:salesLeads.id,salesRepId:salesLeads.salesRepId}).from(salesLeads).where(eq(salesLeads.id,id)).limit(1);if(!lead||(role!==Role.SUPER_ADMIN&&lead.salesRepId!==userId))throw new Error("Unauthorized");return {lead,role,userId}}
async function moveLead(fd:FormData){"use server";const session=await auth();if(!session?.user||![Role.SUPER_ADMIN,Role.SALES].includes((session.user as any).role))throw new Error("Unauthorized");const id=String(fd.get("id")||""),stage=String(fd.get("stage")||""),cfg=STAGES.find(s=>s.key===stage);if(!id||!cfg)throw new Error("Invalid stage");const {role,userId}=await allowedLead(id,session);await db.update(salesLeads).set({stage:stage as any,probability:cfg.probability,updatedAt:new Date(),wonAt:stage==="WON"?new Date():null,lostReason:stage==="LOST"?"Deal not closed":null}).where(role===Role.SUPER_ADMIN?eq(salesLeads.id,id):and(eq(salesLeads.id,id),eq(salesLeads.salesRepId,userId)));const {revalidatePath}=await import("next/cache");revalidatePath("/dashboard/sales");}
async function saveNotes(fd:FormData){"use server";const session=await auth();if(!session?.user||![Role.SUPER_ADMIN,Role.SALES].includes((session.user as any).role))throw new Error("Unauthorized");const id=String(fd.get("id")||""),notes=String(fd.get("notes")||"").trim().slice(0,3000),phone=String(fd.get("phone")||"").trim().slice(0,40);const {role,userId}=await allowedLead(id,session);await db.update(salesLeads).set({notes:notes||null,phone:phone||null,updatedAt:new Date()}).where(role===Role.SUPER_ADMIN?eq(salesLeads.id,id):and(eq(salesLeads.id,id),eq(salesLeads.salesRepId,userId)));const {revalidatePath}=await import("next/cache");revalidatePath("/dashboard/sales");}
async function createLead(fd:FormData){"use server";const session=await auth();if(!session?.user||![Role.SUPER_ADMIN,Role.SALES].includes((session.user as any).role))throw new Error("Unauthorized");const clean=(v:any,m=300)=>String(v||"").trim().slice(0,m),companyName=clean(fd.get("companyName"),160),contactPerson=clean(fd.get("contactPerson"),160),estimatedValue=Number(fd.get("estimatedValue"));if(!companyName||!contactPerson||!Number.isFinite(estimatedValue)||estimatedValue<0)throw new Error("Invalid lead");await db.insert(salesLeads).values({companyName,contactPerson,phone:clean(fd.get("phone"),40)||null,email:clean(fd.get("email"),180)||null,source:(clean(fd.get("source"),40)||"WEBSITE") as any,estimatedValue,stage:"NEW_LEAD",probability:5,industry:clean(fd.get("industry"),100)||null,notes:clean(fd.get("notes"),3000)||null,salesRepId:String((session.user as any).id)});const {revalidatePath}=await import("next/cache");revalidatePath("/dashboard/sales");}

export default async function SalesPage(){const session=await auth();if(!session?.user)redirect("/login");const role=(session.user as any).role as Role;if(![Role.SUPER_ADMIN,Role.SALES].includes(role))redirect("/dashboard");const leads=await db.select().from(salesLeads).where(role===Role.SUPER_ADMIN?eq(salesLeads.workspaceId,"default"):eq(salesLeads.salesRepId,String((session.user as any).id))).orderBy(desc(salesLeads.updatedAt));const active=leads.filter(l=>!["WON","LOST"].includes(l.stage)),won=leads.filter(l=>l.stage==="WON"),closed=leads.filter(l=>["WON","LOST"].includes(l.stage)),pipeline=active.reduce((s,l)=>s+Number(l.estimatedValue||0)*Number(l.probability||0)/100,0),wonValue=won.reduce((s,l)=>s+Number(l.estimatedValue||0),0),winRate=closed.length?Math.round(won.length/closed.length*100):0;
return <div className="sales-page"><style>{`.sales-page{display:flex;flex-direction:column;gap:18px;min-width:0}.sales-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;flex-wrap:wrap}.sales-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.sales-kpi{background:var(--card-bg);border:1px solid var(--card-border);border-radius:16px;padding:16px}.sales-kpi span{font-size:12px;color:var(--text-muted);font-weight:650}.sales-kpi b{display:block;margin-top:6px;font-size:22px}.pipeline-wrap{overflow-x:auto;padding-bottom:8px}.pipeline{display:flex;gap:12px;min-width:max-content}.stage{width:270px;background:var(--bg-tertiary);border:1px solid var(--card-border);border-radius:16px;overflow:hidden}.stage-head{padding:11px 12px;background:var(--card-bg);display:flex;justify-content:space-between;border-bottom:3px solid var(--stage)}.stage-list{padding:8px;display:flex;flex-direction:column;gap:8px;max-height:560px;overflow-y:auto}.lead-card{background:var(--card-bg);border:1px solid var(--card-border);border-radius:12px;padding:11px}.lead-card h3{font-size:13px;margin:0 0 3px}.lead-card p{font-size:11px;color:var(--text-muted);margin:2px 0}.lead-phone{display:inline-flex;gap:5px;align-items:center;margin-top:5px;font-size:11px;font-weight:750;color:var(--vivit-blue);text-decoration:none}.lead-meta{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-top:8px}.lead-move{display:flex;gap:5px;margin-top:9px}.lead-move form{flex:1}.lead-move button{width:100%;height:31px;border-radius:8px;border:1px solid var(--card-border);background:var(--bg-tertiary);font-size:10.5px;font-weight:700;cursor:pointer}.lead-notes{margin-top:9px;padding-top:9px;border-top:1px solid var(--card-border)}.lead-notes textarea{min-height:58px;font-size:11px}.sales-form-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.sales-table-wrap{overflow:auto}@media(max-width:900px){.sales-kpis{grid-template-columns:repeat(2,1fr)}.sales-form-grid{grid-template-columns:1fr 1fr}}@media(max-width:560px){.sales-kpis,.sales-form-grid{grid-template-columns:1fr}.stage{width:min(86vw,300px)}}`}</style>
<div className="sales-head"><div><h1 className="page-title">Sales CRM</h1><p className="page-subtitle">{active.length} active leads · {money(pipeline)} weighted pipeline</p></div><Link href="#add" className="btn btn-primary" style={{textDecoration:"none"}}>+ New Lead</Link></div>
<div className="sales-kpis"><div className="sales-kpi"><span>Active leads</span><b>{active.length}</b></div><div className="sales-kpi"><span>Weighted pipeline</span><b>{money(pipeline)}</b></div><div className="sales-kpi"><span>Total won</span><b>{money(wonValue)}</b></div><div className="sales-kpi"><span>Win rate</span><b>{winRate}%</b></div></div>
<div className="card"><div className="card-header"><p className="card-title">Pipeline Board</p><span className="badge badge-amber">{active.length} Active</span></div><div className="card-body"><div className="pipeline-wrap"><div className="pipeline">{STAGES.map((stage,idx)=>{const stageLeads=leads.filter(l=>l.stage===stage.key);return <div className="stage" key={stage.key} style={{"--stage":stage.color} as any}><div className="stage-head"><b>{stage.icon} {stage.label}</b><span className="badge badge-gray">{stageLeads.length}</span></div><div className="stage-list">{stageLeads.map(lead=><div className="lead-card" key={lead.id}><h3>{lead.companyName}</h3><p>{lead.contactPerson||"No contact"}</p>{lead.phone?<a href={`tel:${lead.phone}`} className="lead-phone">📞 {lead.phone}</a>:<p>Phone not added</p>}<div className="lead-meta"><b>{money(lead.estimatedValue)}</b><span className="badge">{sourceLabel(lead.source)}</span></div>{!["WON","LOST"].includes(stage.key)&&<div className="lead-move">{stage.key!=="NEGOTIATION"&&idx<STAGES.length-2&&<form action={moveLead}><input type="hidden" name="id" value={lead.id}/><input type="hidden" name="stage" value={STAGES[idx+1].key}/><button>Advance →</button></form>}{stage.key==="NEGOTIATION"&&<form action={moveLead}><input type="hidden" name="id" value={lead.id}/><input type="hidden" name="stage" value="WON"/><button>Won ✓</button></form>}<form action={moveLead}><input type="hidden" name="id" value={lead.id}/><input type="hidden" name="stage" value="LOST"/><button>Lost</button></form></div>}<form action={saveNotes} className="lead-notes"><input type="hidden" name="id" value={lead.id}/><label className="form-label">Phone<input name="phone" defaultValue={lead.phone||""} className="form-input" style={{height:34,fontSize:11}}/></label><label className="form-label" style={{marginTop:6}}>Notes<textarea name="notes" defaultValue={lead.notes||""} className="form-input" placeholder="Call notes, objections, next step…"/></label><button className="btn btn-ghost btn-sm" style={{width:"100%",marginTop:6}}>Save Contact & Notes</button></form></div>)}{!stageLeads.length&&<div style={{padding:18,textAlign:"center",fontSize:11,color:"var(--text-muted)"}}>No leads</div>}</div></div>})}</div></div></div></div>
<div className="card" id="add"><div className="card-header"><p className="card-title">Add New Lead</p></div><div className="card-body"><form action={createLead}><div className="sales-form-grid"><label className="form-label">Company Name *<input name="companyName" required className="form-input"/></label><label className="form-label">Contact Person *<input name="contactPerson" required className="form-input"/></label><label className="form-label">Phone<input name="phone" className="form-input"/></label><label className="form-label">Email<input name="email" type="email" className="form-input"/></label><label className="form-label">Estimated Value (EGP) *<input name="estimatedValue" type="number" min="0" required className="form-input"/></label><label className="form-label">Lead Source<select name="source" className="form-select">{["REFERRAL","INSTAGRAM","FACEBOOK","WEBSITE","COLD_CALL","ONLINE","OTHER"].map(s=><option key={s}>{s}</option>)}</select></label><label className="form-label">Industry<input name="industry" className="form-input"/></label></div><label className="form-label" style={{display:"block",marginTop:12}}>Notes<textarea name="notes" rows={3} className="form-input" style={{resize:"vertical"}} placeholder="Initial notes, needs, objections, next action…"/></label><button className="btn btn-primary" style={{marginTop:12}}>Add to Pipeline</button></form></div></div>
<div className="card"><div className="card-header"><p className="card-title">All Leads ({leads.length})</p></div><div className="card-body-flush sales-table-wrap"><table className="data-table"><thead><tr><th>Company</th><th>Contact</th><th>Phone</th><th>Notes</th><th>Value</th><th>Stage</th><th>Source</th></tr></thead><tbody>{leads.slice(0,80).map(l=><tr key={l.id}><td><b>{l.companyName}</b><div style={{fontSize:11,color:"var(--text-muted)"}}>{l.industry||"—"}</div></td><td>{l.contactPerson||"—"}</td><td>{l.phone?<a href={`tel:${l.phone}`}>{l.phone}</a>:"—"}</td><td style={{maxWidth:250,whiteSpace:"normal",fontSize:11.5}}>{l.notes||"—"}</td><td>{money(l.estimatedValue)}</td><td>{STAGES.find(s=>s.key===l.stage)?.label||l.stage}</td><td>{sourceLabel(l.source)}</td></tr>)}</tbody></table></div></div></div>;
}
