// @ts-nocheck
export const dynamic="force-dynamic";
import { auth } from "@/lib/auth";
import { redirect } from "next/navigation";
import { db,salesLeads } from "@/lib/db";
import { eq,desc,and } from "drizzle-orm";
import { Role } from "@/lib/types";
import Link from "next/link";

const STAGES=[
 {key:"NEW_LEAD",label:"New",icon:"🌱",color:"#64748B",probability:5},
 {key:"CONTACTED",label:"Contacted",icon:"📞",color:"#3B82F6",probability:15},
 {key:"QUALIFIED",label:"Qualified",icon:"✅",color:"#8B5CF6",probability:40},
 {key:"PROPOSAL_SENT",label:"Proposal",icon:"📋",color:"#F59E0B",probability:60},
 {key:"NEGOTIATION",label:"Negotiation",icon:"🤝",color:"#EF4444",probability:80},
 {key:"WON",label:"Won",icon:"🏆",color:"#10B981",probability:100},
 {key:"LOST",label:"Lost",icon:"✕",color:"#94A3B8",probability:0},
];
const money=(n:any)=>new Intl.NumberFormat("en-EG",{style:"currency",currency:"EGP",maximumFractionDigits:0}).format(Number(n||0));
const sourceLabel=(v:any)=>{const s=String(v||"OTHER").toUpperCase();return s.includes("AMAN")?"ONLINE":s.replace(/_/g," ")};

async function moveLead(fd:FormData){"use server";const session=await auth();if(!session?.user||![Role.SUPER_ADMIN,Role.SALES].includes((session.user as any).role))throw new Error("Unauthorized");const id=String(fd.get("id")||""),stage=String(fd.get("stage")||"");const cfg=STAGES.find(s=>s.key===stage);if(!id||!cfg)throw new Error("Invalid stage");const role=(session.user as any).role as Role,userId=String((session.user as any).id);const [lead]=await db.select({id:salesLeads.id,salesRepId:salesLeads.salesRepId}).from(salesLeads).where(eq(salesLeads.id,id)).limit(1);if(!lead||(role!==Role.SUPER_ADMIN&&lead.salesRepId!==userId))throw new Error("Unauthorized");await db.update(salesLeads).set({stage:stage as any,probability:cfg.probability,updatedAt:new Date(),wonAt:stage==="WON"?new Date():null,lostReason:stage==="LOST"?"Deal not closed":null}).where(role===Role.SUPER_ADMIN?eq(salesLeads.id,id):and(eq(salesLeads.id,id),eq(salesLeads.salesRepId,userId)));const {revalidatePath}=await import("next/cache");revalidatePath("/dashboard/sales");}
async function createLead(fd:FormData){"use server";const session=await auth();if(!session?.user||![Role.SUPER_ADMIN,Role.SALES].includes((session.user as any).role))throw new Error("Unauthorized");const clean=(v:any,m=300)=>String(v||"").trim().slice(0,m);const companyName=clean(fd.get("companyName"),160),contactPerson=clean(fd.get("contactPerson"),160),estimatedValue=Number(fd.get("estimatedValue"));if(!companyName||!contactPerson||!Number.isFinite(estimatedValue)||estimatedValue<0)throw new Error("Invalid lead");await db.insert(salesLeads).values({companyName,contactPerson,phone:clean(fd.get("phone"),40)||null,source:(clean(fd.get("source"),40)||"WEBSITE") as any,estimatedValue,stage:"NEW_LEAD",probability:5,industry:clean(fd.get("industry"),100)||null,notes:clean(fd.get("notes"),2000)||null,salesRepId:String((session.user as any).id)});const {revalidatePath}=await import("next/cache");revalidatePath("/dashboard/sales");}

export default async function SalesPage(){
 const session=await auth();if(!session?.user)redirect("/login");const role=(session.user as any).role as Role;if(![Role.SUPER_ADMIN,Role.SALES].includes(role))redirect("/dashboard");
 const leads=await db.select().from(salesLeads).where(role===Role.SUPER_ADMIN?eq(salesLeads.workspaceId,"default"):eq(salesLeads.salesRepId,String((session.user as any).id))).orderBy(desc(salesLeads.updatedAt));
 const active=leads.filter(l=>!["WON","LOST"].includes(l.stage)),won=leads.filter(l=>l.stage==="WON"),closed=leads.filter(l=>["WON","LOST"].includes(l.stage));
 const pipeline=active.reduce((s,l)=>s+Number(l.estimatedValue||0)*Number(l.probability||0)/100,0),wonValue=won.reduce((s,l)=>s+Number(l.estimatedValue||0),0),winRate=closed.length?Math.round(won.length/closed.length*100):0;
 return <div className="sales-page"><style>{`
 .sales-page{display:flex;flex-direction:column;gap:18px;min-width:0}.sales-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;flex-wrap:wrap}.sales-actions{display:flex;gap:8px;flex-wrap:wrap}.sales-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.sales-kpi{background:var(--card-bg);border:1px solid var(--card-border);border-radius:16px;padding:16px;box-shadow:var(--shadow-sm)}.sales-kpi span{font-size:12px;color:var(--text-muted);font-weight:650}.sales-kpi b{display:block;margin-top:6px;font-size:22px;color:var(--text-primary)}.pipeline-wrap{overflow-x:auto;padding:2px 2px 8px;scroll-snap-type:x proximity}.pipeline{display:flex;gap:12px;min-width:max-content}.stage{width:240px;background:var(--bg-tertiary);border:1px solid var(--card-border);border-radius:16px;overflow:hidden;scroll-snap-align:start}.stage-head{padding:11px 12px;background:var(--card-bg);display:flex;justify-content:space-between;align-items:center;border-bottom:3px solid var(--stage)}.stage-head b{font-size:12px;color:var(--text-primary)}.stage-count{font-size:10px;font-weight:800;padding:3px 7px;border-radius:999px;background:var(--bg-tertiary)}.stage-list{padding:8px;display:flex;flex-direction:column;gap:7px;max-height:430px;overflow-y:auto}.lead-card{background:var(--card-bg);border:1px solid var(--card-border);border-radius:12px;padding:11px}.lead-card h3{font-size:13px;color:var(--text-primary);margin:0 0 3px}.lead-card p{font-size:11px;color:var(--text-muted);margin:0}.lead-meta{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-top:9px}.lead-meta b{font-size:12px;color:var(--vivit-blue)}.lead-move{display:flex;gap:5px;margin-top:9px}.lead-move form{flex:1}.lead-move button{width:100%;height:32px;border-radius:8px;border:1px solid var(--card-border);background:var(--bg-tertiary);color:var(--text-primary);font:inherit;font-size:10.5px;font-weight:700;cursor:pointer}.sales-form-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.sales-table-wrap{overflow:auto}.sales-mobile-list{display:none}.mobile-lead{background:var(--card-bg);border:1px solid var(--card-border);border-radius:14px;padding:13px;display:flex;flex-direction:column;gap:8px}.mobile-row{display:flex;justify-content:space-between;gap:10px}.mobile-row span:first-child{font-size:11px;color:var(--text-muted)}.mobile-row span:last-child{font-size:12px;color:var(--text-primary);text-align:right}@media(max-width:900px){.sales-kpis{grid-template-columns:repeat(2,minmax(0,1fr))}.sales-form-grid{grid-template-columns:1fr 1fr}.sales-table-wrap{display:none}.sales-mobile-list{display:grid;gap:9px}}@media(max-width:560px){.sales-actions{width:100%}.sales-actions a{flex:1;text-align:center}.sales-kpis{grid-template-columns:1fr 1fr}.sales-form-grid{grid-template-columns:1fr}.stage{width:min(82vw,280px)}}
 `}</style>
 <div className="sales-head"><div><h1 className="page-title">Sales CRM</h1><p className="page-subtitle">{active.length} active leads · {money(pipeline)} weighted pipeline</p></div><div className="sales-actions"><Link href="#add" className="btn btn-primary" style={{textDecoration:"none"}}>+ New Lead</Link></div></div>
 <div className="sales-kpis"><div className="sales-kpi"><span>Active leads</span><b>{active.length}</b></div><div className="sales-kpi"><span>Weighted pipeline</span><b>{money(pipeline)}</b></div><div className="sales-kpi"><span>Total won</span><b>{money(wonValue)}</b></div><div className="sales-kpi"><span>Win rate</span><b>{winRate}%</b></div></div>
 <div className="card"><div className="card-header"><p className="card-title">Pipeline Board</p><span className="badge badge-amber">{active.length} Active</span></div><div className="card-body"><div className="pipeline-wrap"><div className="pipeline">{STAGES.map((stage,idx)=>{const stageLeads=leads.filter(l=>l.stage===stage.key);return <div className="stage" key={stage.key} style={{"--stage":stage.color} as any}><div className="stage-head"><b>{stage.icon} {stage.label}</b><span className="stage-count">{stageLeads.length}</span></div><div className="stage-list">{stageLeads.map(lead=><div className="lead-card" key={lead.id}><h3>{lead.companyName}</h3><p>{lead.contactPerson||"No contact"}</p><div className="lead-meta"><b>{money(lead.estimatedValue)}</b><span className="badge">{sourceLabel(lead.source)}</span></div>{!["WON","LOST"].includes(stage.key)&&<div className="lead-move">{stage.key!=="NEGOTIATION"&&idx<STAGES.length-2&&<form action={moveLead}><input type="hidden" name="id" value={lead.id}/><input type="hidden" name="stage" value={STAGES[idx+1].key}/><button type="submit">Advance →</button></form>}{stage.key==="NEGOTIATION"&&<form action={moveLead}><input type="hidden" name="id" value={lead.id}/><input type="hidden" name="stage" value="WON"/><button type="submit">Won ✓</button></form>}<form action={moveLead}><input type="hidden" name="id" value={lead.id}/><input type="hidden" name="stage" value="LOST"/><button type="submit">Lost</button></form></div>}</div>)}{!stageLeads.length&&<div style={{padding:18,textAlign:"center",fontSize:11,color:"var(--text-muted)"}}>No leads</div>}</div></div>})}</div></div></div></div>
 <div className="card" id="add"><div className="card-header"><p className="card-title">Add New Lead</p></div><div className="card-body"><form action={createLead}><div className="sales-form-grid"><div><label className="form-label">Company Name *</label><input name="companyName" required className="form-input"/></div><div><label className="form-label">Contact Person *</label><input name="contactPerson" required className="form-input"/></div><div><label className="form-label">Phone</label><input name="phone" className="form-input"/></div><div><label className="form-label">Estimated Value (EGP) *</label><input name="estimatedValue" type="number" min="0" required className="form-input"/></div><div><label className="form-label">Lead Source</label><select name="source" className="form-select">{["REFERRAL","INSTAGRAM","FACEBOOK","WEBSITE","COLD_CALL","ONLINE","OTHER"].map(s=><option key={s}>{s}</option>)}</select></div><div><label className="form-label">Industry</label><input name="industry" className="form-input"/></div></div><div style={{marginTop:12}}><label className="form-label">Notes</label><textarea name="notes" rows={2} className="form-input" style={{resize:"vertical"}}/></div><button className="btn btn-primary" type="submit" style={{marginTop:12}}>Add to Pipeline</button></form></div></div>
 <div className="card"><div className="card-header"><p className="card-title">All Leads ({leads.length})</p></div><div className="card-body-flush sales-table-wrap"><table className="data-table"><thead><tr><th>Company</th><th>Contact</th><th>Value</th><th>Stage</th><th>Source</th><th>Updated</th></tr></thead><tbody>{leads.slice(0,50).map(l=><tr key={l.id}><td><b>{l.companyName}</b><div style={{fontSize:11,color:"var(--text-muted)"}}>{l.industry||"—"}</div></td><td>{l.contactPerson||"—"}</td><td>{money(l.estimatedValue)}</td><td>{STAGES.find(s=>s.key===l.stage)?.label||l.stage}</td><td>{sourceLabel(l.source)}</td><td>{new Date(l.updatedAt).toLocaleDateString("en-GB")}</td></tr>)}</tbody></table></div><div className="card-body sales-mobile-list">{leads.slice(0,50).map(l=><div className="mobile-lead" key={l.id}><div><b style={{color:"var(--text-primary)"}}>{l.companyName}</b><div style={{fontSize:11,color:"var(--text-muted)"}}>{l.contactPerson||"No contact"}</div></div><div className="mobile-row"><span>Value</span><span>{money(l.estimatedValue)}</span></div><div className="mobile-row"><span>Stage</span><span>{STAGES.find(s=>s.key===l.stage)?.label||l.stage}</span></div><div className="mobile-row"><span>Source</span><span>{sourceLabel(l.source)}</span></div></div>)}</div></div>
 </div>;
}
