"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";

type Platform="META"|"TIKTOK";
export default function PlatformIntegrationsPage(){
 const[data,setData]=useState<any>({clients:[],accounts:[],campaigns:[],configured:{}}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function load(){setLoading(true);const r=await fetch("/api/platform-link",{cache:"no-store"});const d=await r.json();if(r.ok)setData(d);else setMessage(d.error||"Could not load integrations.");setLoading(false)}useEffect(()=>{load()},[]);
 async function linkCampaign(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const f=e.currentTarget,body=Object.fromEntries(new FormData(f).entries());const r=await fetch("/api/platform-link",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...body,op:"link",syncNow:true})}),d=await r.json();setMessage(r.ok?(d.sync?.ok?`Linked and synced ${d.sync.days} day(s).`:`IDs linked. ${d.sync?.error||"Authorize the API to start live sync."}`):d.error||"Could not link campaign.");if(r.ok){f.reset();await load()}setBusy(false)}
 async function sync(id:string){setBusy(true);setMessage("");const r=await fetch("/api/platform-link",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({op:"sync",internalCampaignId:id})}),d=await r.json();setMessage(r.ok?`Synced ${d.days} day(s).`:d.error||"Sync failed.");if(r.ok)await load();setBusy(false)}
 const accounts=useMemo(()=>new Map(data.accounts.map((a:any)=>[a.id,a])),[data.accounts]);const clientName=(id:string)=>data.clients.find((c:any)=>c.id===id)?.name||"Client";
 if(loading)return <div className="card"><div className="empty-state">Loading platform integrations…</div></div>;
 return <div style={{display:"grid",gap:18}}>
  <div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"flex-start",flexWrap:"wrap"}}><div><h1 className="page-title">Platform Integrations</h1><p className="page-subtitle">Enter the ad account ID and campaign ID. VIVIT stores the mapping and pulls live performance when API authorization is available.</p></div><Link href="/dashboard/whatsapp" className="btn btn-success" style={{textDecoration:"none"}}>💬 WhatsApp Workspace</Link></div>
  {message&&<div className={message.toLowerCase().includes("fail")||message.toLowerCase().includes("could not")||message.toLowerCase().includes("error")?"media-error":"media-success"}>{message}</div>}
  <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">{(["META","TIKTOK"] as Platform[]).map(platform=><div className="card" key={platform}>
   <div className="card-header"><div><p className="card-title">{platform==="META"?"Meta Ads":"TikTok Ads"}</p><p className="page-subtitle" style={{margin:0}}>{data.configured?.[platform]?"API authorization detected — IDs will sync immediately.":"ID linking works now. Add/authorize platform credentials to pull live data."}</p></div><span className={`badge ${data.configured?.[platform]?"badge-green":"badge-amber"}`}>{data.configured?.[platform]?"API READY":"ID MODE"}</span></div>
   <div className="card-body"><form className="media-form" onSubmit={linkCampaign}><input type="hidden" name="platform" value={platform}/><label>Client<select name="clientId" required className="form-select"><option value="">Select client</option>{data.clients.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>{platform==="META"?"Ad Account ID":"Advertiser ID"}<input name="adAccountId" required inputMode="numeric" className="form-input" placeholder={platform==="META"?"123456789012345":"7123456789012345678"}/></label><label>Campaign ID<input name="campaignId" required inputMode="numeric" className="form-input" placeholder="Campaign ID"/></label><label>Account name (optional)<input name="accountName" className="form-input" placeholder="Brand Ad Account"/></label><label>Campaign name (optional)<input name="campaignName" className="form-input" placeholder="August Leads"/></label><button className="btn btn-primary" disabled={busy}>Link IDs & Sync →</button></form></div>
  </div>)}</div>
  <div className="card"><div className="card-header"><div><p className="card-title">Linked campaigns</p><p className="page-subtitle" style={{margin:0}}>Account ID and Campaign ID stay visible for audit and manual verification.</p></div></div><div className="card-body-flush"><div className="table-scroll"><table className="data-table"><thead><tr><th>Client</th><th>Platform</th><th>Account ID</th><th>Campaign</th><th>Campaign ID</th><th>Status</th><th>Last sync</th><th></th></tr></thead><tbody>{data.campaigns.map((c:any)=>{const a:any=accounts.get(c.connectionId);return <tr key={c.id}><td>{clientName(c.clientId)}</td><td>{c.platform}</td><td><code>{a?.adAccountId||"—"}</code></td><td><strong>{c.name}</strong></td><td><code>{c.externalId}</code></td><td><span className="badge badge-blue">{c.status}</span></td><td>{c.lastSyncAt?new Date(c.lastSyncAt).toLocaleString():"Not synced"}</td><td><button className="btn btn-ghost btn-sm" disabled={busy||!["META","TIKTOK"].includes(c.platform)} onClick={()=>sync(c.id)}>Sync</button></td></tr>})}</tbody></table></div>{!data.campaigns.length&&<div className="empty-state">No campaigns linked yet.</div>}</div></div>
  <div className="card"><div className="card-body" style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div><strong>WhatsApp</strong><p className="page-subtitle" style={{margin:"4px 0 0"}}>Open chats directly without API. Send from inside VIVIT when WhatsApp Cloud API credentials are configured.</p></div><Link href="/dashboard/whatsapp" className="btn btn-success" style={{textDecoration:"none"}}>Open WhatsApp →</Link></div></div>
 </div>;
}
