import fs from "node:fs";
import path from "node:path";
const root=process.cwd(),read=f=>fs.readFileSync(path.join(root,f),"utf8"),checks=[],check=(name,ok)=>checks.push({name,ok:Boolean(ok)});
const list=read("app/dashboard/clients/page.tsx"),detail=read("app/dashboard/clients/[id]/page.tsx"),guard=read("app/dashboard/clients/[id]/layout.tsx"),edit=read("app/dashboard/clients/[id]/edit/page.tsx"),newPage=read("app/dashboard/clients/new/page.tsx"),form=read("components/clients/NewClientForm.tsx"),api=read("app/api/clients/route.ts"),lifecycle=read("app/api/lifecycle/route.ts"),archive=read("app/dashboard/archive/page.tsx"),deleted=read("app/dashboard/delete/page.tsx"),migration=read("db/migrations/20260901_hr_lifecycle_reporting_contract.sql"),actions=read("lib/actions/index.ts");
check("Clients list remains role protected",list.includes("session")&&list.includes("ACCOUNT_MANAGER"));
check("Account Manager client list remains ownership scoped",list.includes("accountManagerId")&&list.includes("userId"));
check("Media Buyer client list remains ownership scoped",list.includes("mediaBuyerId")&&list.includes("userId"));
check("Client detail keeps centralized active-record guard",guard.includes("isActive")&&guard.includes("redirect"));
check("New client page honors effective create roles",newPage.includes("hasEffectiveRole(session.user")&&newPage.includes('["SUPER_ADMIN","ACCOUNT_MANAGER","ACCOUNTANT"]'));
check("New client assignment picker includes secondary roles and workspace scope",newPage.includes("user_role_assignments")&&newPage.includes("u.workspace_id=${workspaceId}")&&newPage.includes("ura.workspace_id=u.workspace_id"));
check("New client form requires report frequency",form.includes('name="reportFrequency"')&&form.includes("EVERY_3_DAYS")&&form.includes("WEEKLY"));
check("New client form starts with one competitor",form.includes("[emptyCompetitor()]")&&form.includes("Competitors *"));
check("New client form caps competitors at five",form.includes("current.length>=5")&&form.includes("competitors.length>=5"));
check("Competitor form requires Facebook Instagram TikTok",form.includes("FACEBOOK *")&&form.includes("INSTAGRAM *")&&form.includes("TIKTOK *")&&form.match(/required type="url"/g)?.length>=3);
check("Client API rejects fewer than 1 or more than 5 competitors",api.includes("value.length<1||value.length>5"));
check("Client API requires all three competitor social links",api.includes("!item.facebook||!item.instagram||!item.tiktok")&&api.includes("Facebook, Instagram and TikTok links"));
check("Client API validates social profile URLs",api.includes("validUrl")&&api.includes("facebook")&&api.includes("instagram")&&api.includes("tiktok"));
check("Client create authorization honors effective roles",api.includes("hasEffectiveRole(session.user")&&api.includes('["SUPER_ADMIN","ACCOUNT_MANAGER","ACCOUNTANT"]'));
check("Client API accepts workspace-scoped secondary AM and Media Buyer roles",api.includes("user_role_assignments ura")&&api.includes("ura.workspace_id=u.workspace_id")&&api.includes("ura.role='ACCOUNT_MANAGER'")&&api.includes("ura.role='MEDIA_BUYER'"));
check("Client API validates report cadence allowlist",api.includes('["DAILY","EVERY_3_DAYS","WEEKLY"]'));
check("Client and competitor setup share one transaction",api.includes("db.transaction")&&api.includes("competitor_watchlists")&&api.includes("competitor_social_profiles"));
check("Client create rejects duplicate company names",api.includes("already exists")&&api.includes("status:409"));
check("Client create validates portal ownership",api.includes("valid active approved client portal user")&&api.includes("already linked to another client"));
check("Client create validates AM/Media Buyer assignment",api.includes("valid active account manager")&&api.includes("valid active media buyer"));
check("Client create validates contract date order",api.includes("Contract end date must be on or after the start date"));
check("Client form exposes error and saving states",form.includes("setError")&&form.includes("Creating client…")&&form.includes('role="alert"'));
check("Lifecycle supports client archive delete restore",lifecycle.includes('entity==="client"')&&lifecycle.includes('action==="archive"')&&lifecycle.includes('action==="restore_deleted"'));
check("Client delete is soft delete with actor",lifecycle.includes("update clients set is_active=false,deleted_at=now(),deleted_by=${userId}")&&!lifecycle.includes("delete from clients where id=${id}"));
check("Client creator or manager can delete/archive owned client",lifecycle.includes("r.created_by===userId")&&lifecycle.includes("r.account_manager_id===userId"));
check("Archive Center is ledger-driven and labels clients",archive.includes('client:"Clients"')&&archive.includes("actor_name")&&archive.includes("archiveData.items||[]"));
check("Delete Center is ledger-driven and labels clients",deleted.includes('client:"Clients"')&&deleted.includes("actor_name")&&deleted.includes("d.items||[]"));
check("Migration persists cadence and lifecycle fields",migration.includes("report_frequency")&&migration.includes("report_last_sent_at")&&migration.includes("archived_by")&&migration.includes("deleted_by"));
check("Existing client update action remains present",actions.includes("export async function updateClient"));
check("Existing client edit UI remains present",edit.includes("Save client"));
check("Client detail communication log remains present",detail.includes("sales_activities")||detail.includes("activity"));
const failed=checks.filter(c=>!c.ok);for(const c of checks)console.log(`${c.ok?"PASS":"FAIL"}  ${c.name}`);console.log(`\n${checks.length-failed.length}/${checks.length} client/competitor lifecycle checks passed.`);if(failed.length)process.exit(1);