import fs from "node:fs";
import path from "node:path";
const root=process.cwd(),failures=[],checks=[];
const read=f=>fs.readFileSync(path.join(root,f),"utf8");
const pass=(name,ok,detail="")=>{checks.push({name,ok,detail});if(!ok)failures.push(`${name}${detail?`: ${detail}`:""}`)};
const walk=dir=>fs.existsSync(path.join(root,dir))?fs.readdirSync(path.join(root,dir),{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(dir,e.name)):[path.join(dir,e.name)]):[];
const pages=new Set(walk("app/dashboard").filter(f=>f.endsWith("/page.tsx")).map(f=>"/"+path.dirname(f).replaceAll("\\","/").replace(/^app\//,"")));
const sources=[...walk("app"),...walk("components")].filter(f=>/\.(tsx?|jsx?)$/.test(f)),internalLinks=new Set();
for(const file of sources){const source=read(file);for(const m of source.matchAll(/(?:href=|router\.(?:push|replace)\(|window\.location\.(?:assign|replace)\()[{(]?\s*["'`]\/dashboard\/([^"'`?#)]*)/g))internalLinks.add(`/dashboard/${m[1].replace(/\/$/,"")}`)}
const routeExists=href=>pages.has(href)||[...pages].some(page=>{const p="^"+page.replace(/[.*+?^${}()|[\]\\]/g,"\\$&").replace(/\\\[[^/]+\\\]/g,"[^/]+")+"$";return new RegExp(p).test(href.replace(/\$\{[^}]+\}/g,"preview-id"))});
const broken=[...internalLinks].filter(h=>!routeExists(h));pass("All static dashboard links resolve",broken.length===0,broken.join(", "));
const proxy=read("proxy.ts"),sidebar=read("components/layout/Sidebar.tsx"),mobile=read("components/layout/MobileNav.tsx"),calendarPage=read("app/dashboard/calendar/page.tsx"),calendar=read("components/calendar/CalendarClient.tsx"),filesApi=read("app/api/files/route.ts"),filesPage=read("app/dashboard/files/page.tsx"),lifecycleApi=read("app/api/lifecycle/route.ts"),archivePage=read("app/dashboard/archive/page.tsx"),creativePage=read("app/dashboard/creative/page.tsx"),salesPage=read("app/dashboard/sales/page.tsx"),clientPage=read("app/dashboard/clients/page.tsx"),clientApi=read("app/api/clients/route.ts"),reports=read("components/reports/ReportsClient.tsx"),ai=read("app/api/ai/route.ts"),assistant=read("app/api/assistant/route.ts"),layout=read("app/layout.tsx"),tasksInbox=read("app/dashboard/tasks-inbox/page.tsx"),actions=read("lib/actions/index.ts"),bulkApi=read("app/api/bulk/route.ts"),monthlySummary=read("app/api/monthly-summary/[clientId]/route.ts"),pdfReport=read("app/api/pdf-report/[clientId]/route.ts"),media=read("app/dashboard/media/page.tsx"),health=read("app/api/health/route.ts");
for(const route of ["/dashboard/revenue-attribution","/dashboard/nps","/dashboard/onboarding","/dashboard/monthly-reports","/dashboard/marketplace","/dashboard/budget","/dashboard/archive"])pass(`Proxy protects ${route}`,proxy.includes(route));
pass("Next 16 proxy convention is used",fs.existsSync(path.join(root,"proxy.ts"))&&!fs.existsSync(path.join(root,"middleware.ts")));
pass("Calendar navigation and proxy agree for CLIENT",sidebar.includes('label:"Calendar"')&&proxy.includes('"/dashboard/calendar"')&&proxy.includes('"SALES","CLIENT"'));
pass("FAHD navigation and proxy agree",sidebar.includes('label:"FAHD"')&&sidebar.includes('href:"/dashboard/ai-studio"')&&proxy.includes('"/dashboard/ai-studio"')&&proxy.includes('"CREATOR","SALES","ACCOUNTANT","CLIENT"'));
pass("Archive navigation and proxy agree",sidebar.includes('label:"Archive"')&&proxy.includes('"/dashboard/archive"')&&proxy.includes('"SUPER_ADMIN","ACCOUNT_MANAGER","SALES"'));
pass("Mobile CLIENT calendar is not dead navigation",mobile.includes('href:"/dashboard/calendar"')&&proxy.includes('"/dashboard/calendar"'));
pass("Calendar page allows CLIENT and SALES read access",calendarPage.includes("Role.CLIENT")&&calendarPage.includes("Role.SALES"));
pass("Calendar management excludes SALES",calendarPage.includes("const canManage=[Role.SUPER_ADMIN,Role.ACCOUNT_MANAGER].includes(role)"));
pass("Archived tasks excluded from calendar task sources",calendarPage.includes("archived_at is null"));
pass("Scheduled posts require media",/assetFileId/.test(calendar)&&/required/.test(calendar)&&/!assetFileId/.test(calendar));
pass("Scheduled posts accept images and video",/image\/\*,video\/\*/.test(calendar));
pass("Files support 500 MB",/500\s*\*\s*1024\s*\*\s*1024/.test(filesApi)&&/500\s*\*\s*1024\s*\*\s*1024/.test(filesPage));
pass("Files API supports owner/admin edit",/export async function PATCH/.test(filesApi)&&/uploadedBy/.test(filesApi)&&/SUPER_ADMIN/.test(filesApi));
pass("Files API supports owner/admin delete",/export async function DELETE/.test(filesApi)&&/uploadedBy/.test(filesApi)&&/SUPER_ADMIN/.test(filesApi));
pass("Files support archive and restore",filesApi.includes('op==="archive"')&&filesApi.includes('op==="restore"')&&filesPage.includes("Archive")&&filesPage.includes("Restore"));
pass("Archived files excluded from active view",filesApi.includes("archived_at is null")&&filesApi.includes("archived_at is not null"));
pass("Files UI exposes edit/delete actions",/Edit/.test(filesPage)&&/Delete/.test(filesPage));
pass("File storage bucket self-heals",/ensureBucket/.test(filesApi));pass("File links are role/client scoped",/validateLinks/.test(filesApi)&&/ACCOUNT_MANAGER/.test(filesApi)&&/MEDIA_BUYER/.test(filesApi));
pass("Lifecycle API has archive restore delete",lifecycleApi.includes('"archive","restore","delete"')&&lifecycleApi.includes("client_archived")&&lifecycleApi.includes("task_archived")&&lifecycleApi.includes("lead_archived"));
pass("Client permanent delete is admin only",lifecycleApi.includes("Only Super Admin can permanently delete a client"));
pass("Hard delete blocks linked client data",lifecycleApi.includes("Archive it instead of permanent deletion")&&lifecycleApi.includes("dependencies"));
pass("Task hard delete blocks linked files/calendar/comments",lifecycleApi.includes("linked files, comments, or calendar items")&&lifecycleApi.includes("task_comments"));
pass("Converted leads cannot hard delete",lifecycleApi.includes("converted to a client"));
pass("Archive Center exposes restore and permanent delete",archivePage.includes("Restore")&&archivePage.includes("Delete permanently"));
pass("Creative board excludes archived tasks",creativePage.includes("archived_at is null")&&creativePage.includes("archiveTask"));
pass("Task Inbox excludes archived tasks",tasksInbox.includes("archived_at is null"));
pass("Assistant excludes archived tasks",assistant.includes("archived_at is null"));
pass("Sales CRM excludes archived leads",salesPage.includes("archived_at is null")&&salesPage.includes("archiveLead"));
pass("Clients expose archive flow",clientPage.includes("archiveClient")&&clientPage.includes("/dashboard/archive"));
pass("Client creation remains role-gated",/SUPER_ADMIN/.test(clientApi)&&/ACCOUNT_MANAGER/.test(clientApi));
pass("Reports render UI instead of raw endpoint navigation",reports.includes("fetch(")&&!/window\.location\s*=\s*["'`]\/api\/reports/.test(reports));
pass("AI requires a configured provider",ai.includes("AI provider is not configured")&&!ai.includes("Smart draft (local mode)"));pass("AI financial prompts use EGP",ai.includes(" EGP"));pass("AI client context is authorization scoped",ai.includes("canAccessClient")&&ai.includes("hydrateClientContext"));pass("Assistant handles task/deadline questions",/deadline|due today|overdue/i.test(assistant));pass("Mobile viewport is explicit",/device-width/.test(layout));
pass("Account Manager task inbox is client-scoped",tasksInbox.includes("clients.accountManagerId")&&tasksInbox.includes("inArray(creativeTasks.clientId"));
pass("Task inbox mutations are scoped",/owned|scope|accountManagerId|managedClient/i.test(tasksInbox));
pass("Notification delete is owner scoped",/deleteNotification[\s\S]*notifications\.userId/.test(actions));pass("Task create stores creator ownership",/createdById:\s*session\.user\.id/.test(actions));pass("Task mutations check access",/taskForAccess/.test(actions)&&/requireClientAccess/.test(actions));
pass("Bulk API has explicit task transition allowlist",bulkApi.includes("const TRANSITIONS")&&bulkApi.includes("from=TRANSITIONS[target]")&&bulkApi.includes("Invalid task IDs or transition"));pass("Bulk task writes scope Account Managers",bulkApi.includes("managedClientIds")&&bulkApi.includes("inArray(creativeTasks.clientId,owned)"));pass("Monthly summary validates client access",monthlySummary.includes("canAccessClient"));pass("Monthly summary validates report period",monthlySummary.includes("month<1||month>12")&&monthlySummary.includes("year<2020||year>2100"));pass("PDF report validates client access",pdfReport.includes("canAccessClient"));pass("Media metric writes validate client ownership",media.includes("Invalid client or platform")&&media.includes("Forbidden"));
const packageVersion=JSON.parse(read("package.json")).version;pass("Health reports package version",health.includes("pkg.version")||health.includes(`\"${packageVersion}\"`));
for(const c of checks)console.log(`${c.ok?"PASS":"FAIL"}  ${c.name}${c.detail?` — ${c.detail}`:""}`);console.log(`\n${checks.length-failures.length}/${checks.length} static QA checks passed.`);if(failures.length)process.exit(1);
