import {renderVivitoPdf} from "../lib/vivito/pdf-renderer";
import {renderVivitoPrintHtml,vivitoPdfNeedsPrintRenderer} from "../lib/vivito/print-renderer";
import {renderVivitoXlsx} from "../lib/vivito/xlsx-renderer";
import {contentPlanToWorkbook,type VivitoContentPlan,type VivitoPdfSpec} from "../lib/vivito/artifact-intelligence";
import {likelyVivitoArtifactIntent,likelyVivitoResearchIntent,likelyVivitoVisionIntent,requestedArtifactKind} from "../lib/vivito/artifact-router";

let pass=0,fail=0;const check=(name:string,ok:boolean)=>{console.log(`${ok?"PASS":"FAIL"}  ${name}`);if(ok)pass++;else fail++};
const latin:VivitoPdfSpec={title:"VIVITO Strategy",pages:[{title:"Growth requires focus",blocks:[{type:"metric",text:"+24%"},{type:"body",text:"Prioritize profitable segments."}]}]};
const arabic:VivitoPdfSpec={title:"استراتيجية النمو",pages:[{title:"النمو يحتاج تركيز",blocks:[{type:"callout",text:"ركز على الشرائح الأعلى ربحية"},{type:"chart",title:"الأداء",data:[{label:"وعي",value:30},{label:"تحويل",value:70}]},{type:"table",headers:["المحور","القرار"],rows:[["السعر","اختبار مرن"]]}]}]};
const pdf=renderVivitoPdf(latin);check("Latin PDF renderer emits real PDF bytes",new TextDecoder().decode(pdf.slice(0,5))==="%PDF-");
check("Arabic rich PDF selects print renderer",vivitoPdfNeedsPrintRenderer(arabic));const html=renderVivitoPrintHtml(arabic);check("Print renderer preserves RTL",html.includes('dir="rtl"'));check("Print renderer contains charts",html.includes("bar-track"));check("Print renderer contains tables",html.includes("<table"));check("Print renderer has A4 print CSS",html.includes("@page{size:A4"));check("Print renderer has print color fidelity",html.includes("print-color-adjust:exact"));
const plan:VivitoContentPlan={brand:"VIVIT",period:"2026-09",objectives:["Qualified demand"],audiences:["SME owners"],pillars:[{name:"Proof",role:"Consideration",share:100}],rows:[{date:"2026-09-01",platform:"Instagram",pillar:"Proof",format:"Reel",objective:"Trust",topic:"Case study",hook:"Before you spend more",captionDirection:"Evidence first",cta:"DM",kpi:"Qualified DMs"}]};const wb=contentPlanToWorkbook(plan);check("Content plan becomes a multi-sheet workbook",wb.sheets.length>=2&&wb.sheets[0].rows.length===1);const xlsx=renderVivitoXlsx(wb);check("XLSX renderer emits ZIP/OOXML bytes",xlsx[0]===0x50&&xlsx[1]===0x4b);
check("Vision router detects image review",likelyVivitoVisionIntent("حلل الديزاين ده",[{mimeType:"image/png"}]));check("Vision router ignores no-image request",!likelyVivitoVisionIntent("حلل الديزاين ده",[]));check("Research router detects current competitor research",likelyVivitoResearchIntent("اعمل سيرش حالي على المنافسين في مصر"));check("Artifact router detects PDF strategy",likelyVivitoArtifactIntent("اعمل marketing strategy PDF"));check("Artifact router detects Excel content plan",requestedArtifactKind("اعمل content plan على Excel")==="content-plan");
console.log(`\n${pass}/${pass+fail} VIVITO Artifact V2 runtime checks passed.`);if(fail)process.exit(1);
