"use client";
import {useCallback,useState} from "react";
import {usePathname} from "next/navigation";
type Campaign={id:string;name:string;status:string;archived_at?:string|null;archived_by_name?:string|null};
export function CampaignLifecycleRuntime({role}:{role:string}){
 const path=usePathname(),m=path.match(/^\/dashboard\/clients\/([^/]+)$/),clientId=m?.[1]||"",[open,setOpen]=useState(false),[items,setItems]=useState<Campaign[]>([]),[busy,setBusy]=useState(""),[error,setError]=useState("");
 const enabled=Boolean(clientId&&["SUPER_ADMIN","ACCOUNT_MANAGER","MEDIA_BUYER"].includes(role));
 const load=useCallback(async()=>{if(!enabled)return;const r=await fetch(`/api/campaign-lifecycle?clientId=${encodeURIComponent(clientId)}`,{cache:"no-store"}),d=await r.json().catch(()=>({}));if(r.ok)setItems(Array.isArray(d.campaigns)?d.campaigns:[]);else setError(d.error||"Could not load campaigns")},[clientId,enabled]);
 if(!enabled)return null;
 async function toggle(){const next=!open;setOpen(next);if(next)await load()}
 async function act(id:string,action:"archive"|"restore"|"delete"){if(action==="delete"&&!confirm("Delete this archived campaign permanently? Reporting history may prevent deletion."))return;setBusy(id+action);setError("");try{const r=await fetch("/api/campaign-lifecycle",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,action})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Campaign lifecycle action failed");await load()}catch(e){setError(e instanceof Error?e.message:"Campaign lifecycle action failed")}finally{setBusy("")}}
 return <div style={{position:"fixed",left:22,bottom:22,zIndex:1185}}><button type="button" className="btn btn-secondary" onClick={()=>void toggle()}>Campaign archive/delete</button>{open&&<div style={{position:"absolute",left:0,bottom:52,width:"min(430px,calc(100vw - 32px))",maxHeight:"60vh",overflow:"auto",padding:12,borderRadius:16,background:"var(--card-bg)",border:"1px solid var(--card-border)",boxShadow:"0 16px 42px rgba(15,23,42,.22)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:8}}><b>Campaign lifecycle</b><button type="button" className="btn btn-ghost btn-sm" onClick={()=>setOpen(false)}>Close</button></div>{error&&<p role="alert" style={{fontSize:11,color:"var(--red)",marginTop:8}}>{error}</p>}<div style={{display:"grid",gap:8,marginTop:10}}>{items.map(c=><div key={c.id} style={{padding:10,border:"1px solid var(--card-border)",borderRadius:12}}><div><b style={{fontSize:12}}>{c.name}</b><div style={{fontSize:10,color:"var(--text-muted)"}}>{c.archived_at?`Archived${c.archived_by_name?` by ${c.archived_by_name}`:""}`:c.status}</div></div><div style={{display:"flex",gap:6,marginTop:8,flexWrap:"wrap"}}>{c.archived_at?<><button type="button" className="btn btn-secondary btn-sm" disabled={Boolean(busy)} onClick={()=>void act(c.id,"restore")}>Restore</button><button type="button" className="btn btn-danger btn-sm" disabled={Boolean(busy)} onClick={()=>void act(c.id,"delete")}>Delete</button></>:<button type="button" className="btn btn-ghost btn-sm" disabled={Boolean(busy)} onClick={()=>void act(c.id,"archive")}>Archive</button>}</div></div>)}{!items.length&&<p style={{fontSize:11,color:"var(--text-muted)"}}>No campaigns found.</p>}</div></div>}</div>;
}
