"use client";
import {useCallback,useEffect,useState} from "react";

type Campaign={id:string;name:string;platform?:string;clientName?:string;archived_at?:string|null};
type Payload={campaigns?:Campaign[];archivedCampaigns?:Campaign[];error?:string};
export function CampaignLifecyclePanel(){
 const [active,setActive]=useState<Campaign[]>([]),[archived,setArchived]=useState<Campaign[]>([]),[busy,setBusy]=useState(""),[error,setError]=useState("");
 const load=useCallback(async()=>{try{const r=await fetch("/api/media-control-v2",{cache:"no-store"}),d=await r.json().catch(()=>({})) as Payload;if(!r.ok)throw new Error(d.error||"Could not load campaigns");setActive(d.campaigns||[]);setArchived(d.archivedCampaigns||[])}catch(e){setError(e instanceof Error?e.message:"Could not load campaigns")}},[]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 async function lifecycle(campaign:Campaign,action:"archive"|"delete"|"restore"){if(action==="delete"&&!confirm(`Move “${campaign.name}” to Delete Center?`))return;setBusy(`${action}:${campaign.id}`);setError("");try{const r=await fetch("/api/lifecycle",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({entity:"campaign",id:campaign.id,action})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Campaign action failed");await load()}catch(e){setError(e instanceof Error?e.message:"Campaign action failed")}finally{setBusy("")}}
 const row=(campaign:Campaign,isArchived:boolean)=><div key={campaign.id} style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,padding:"10px 0",borderBottom:"1px solid var(--card-border)"}}><div style={{minWidth:0}}><b style={{display:"block",whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{campaign.name}</b><small style={{color:"var(--text-muted)"}}>{campaign.platform||"Campaign"}{campaign.clientName?` · ${campaign.clientName}`:""}</small></div><div style={{display:"flex",gap:6,flexWrap:"wrap",justifyContent:"flex-end"}}>{isArchived?<button className="btn btn-secondary btn-sm" disabled={busy.endsWith(campaign.id)} onClick={()=>lifecycle(campaign,"restore")}>Restore</button>:<button className="btn btn-secondary btn-sm" disabled={busy.endsWith(campaign.id)} onClick={()=>lifecycle(campaign,"archive")}>Archive</button>}<button className="btn btn-danger btn-sm" disabled={busy.endsWith(campaign.id)} onClick={()=>lifecycle(campaign,"delete")}>Delete</button></div></div>;
 return <section className="card"><div className="card-header"><div><p className="card-title">Campaign Lifecycle</p><p className="page-subtitle">Archive keeps the campaign in your Archive Center. Delete moves it to the Super Admin Delete Center with your name recorded.</p></div><span className="badge badge-gray">{active.length+archived.length}</span></div><div className="card-body">{error&&<div className="form-error" role="alert">{error}</div>}<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:18}}><div><h3 style={{fontSize:13,marginBottom:8}}>Active campaigns</h3>{active.length?active.map(c=>row(c,false)):<p className="page-subtitle">No active campaigns.</p>}</div><div><h3 style={{fontSize:13,marginBottom:8}}>Archived campaigns</h3>{archived.length?archived.map(c=>row(c,true)):<p className="page-subtitle">No archived campaigns.</p>}</div></div></div></section>;
}