"use client";
import {useEffect,useMemo,useState} from "react";
const money=(v:any,c="EGP")=>new Intl.NumberFormat("en-EG",{style:"currency",currency:c||"EGP",maximumFractionDigits:2}).format(Number(v||0));
const num=(v:any)=>Number(v||0);
function Kpi({label,value,sub}:{label:string;value:string;sub?:string}){return <div style={{background:"var(--card-bg)",border:"1px solid var(--card-border)",borderRadius:16,padding:"16px 18px",minHeight:96,boxShadow:"0 6px 18px rgba(15,23,42,.04)"}}><div style={{fontSize:11,fontWeight:800,color:"var(--text-muted)",letterSpacing:.4,textTransform:"uppercase"}}>{label}</div><div style={{fontSize:24,fontWeight:900,marginTop:8,color:"var(--text-primary)"}}>{value}</div>{sub&&<div style={{fontSize:10.5,color:"var(--text-muted)",marginTop:4}}>{sub}</div>}</div>}
export function MediaControlV2(){
 const[data,setData]=useState<any>({campaigns:[],accountGroups:[],clients:[],range:{}}),[loading,setLoading]=useState(true),[msg,setMsg]=useState(""),[tab,setTab]=useState("overview"),[syncing,setSyncing]=useState<string|null>(null);
 async function load(){setLoading(true);const r=await fetch('/api/media-control-v2',{cache:'no-store'});setData(await r.json());setLoading(false)}
 useEffect(()=>{load();const t=setInterval(()=>load(),30000);return()=>clearInterval(t)},[]);
 async function act(op:string,id:string){if(op==='delete_campaign'&&!confirm('Delete this campaign from VIVIT permanently? Meta campaign itself will not be deleted.'))return;const r=await fetch('/api/media-control-v2',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({op,campaignId:id})}),d=await r.json().catch(()=>({}));setMsg(r.ok?(op==='archive_campaign'?'Campaign archived.':'Campaign deleted from VIVIT.'):d.error||'Action failed');if(r.ok)load()}
 async function sync(id:string){setSyncing(id);const r=await fetch('/api/media-control-v2',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({op:'sync_campaign',campaignId:id,from:data.range?.start,to:data.range?.end})}),d=await r.json().catch(()=>({}));setMsg(r.ok?'Campaign synced from Meta.':d.error||'Sync failed');setSyncing(null);if(r.ok)load()}
 const total=useMemo(()=>data.campaigns?.reduce((a:any,c:any)=>{const m=c.metrics||{};for(const k of['spend','results','purchases','revenue','impressions','clicks','reach','addToCart'])a[k]+=num(m[k]);return a},{spend:0,results:0,purchases:0,revenue:0,impressions:0,clicks:0,reach:0,addToCart:0})||{},[data.campaigns]);
 const ctr=total.impressions?total.clicks/total.impressions*100:0,cpm=total.impressions?total.spend/total.impressions*1000:0,cpr=total.results?total.spend/total.results:0,roas=total.spend?total.revenue/total.spend:0;
 return <div style={{display:'grid',gap:18}}>
  <div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'flex-end',flexWrap:'wrap'}}><div><h1 className="page-title">Media Buying Control Center</h1><p className="page-subtitle">Account-first live performance · every campaign stays separate under its ad account</p></div><div style={{fontSize:11,color:'var(--text-muted)'}}>Auto refresh every 30 seconds</div></div>
  <div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{['overview','campaigns','accounts'].map(x=><button key={x} onClick={()=>setTab(x)} className={tab===x?'btn btn-primary':'btn btn-secondary'}>{x==='overview'?'Overview':x==='campaigns'?'Campaigns':'Ad Accounts'}</button>)}</div>
  {msg&&<div className="card"><div className="card-body">{msg}</div></div>}
  {loading?<div className="card"><div className="card-body">Loading live media data…</div></div>:<>
   {tab==='overview'&&<>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(165px,1fr))',gap:12}}>
      <Kpi label="Amount Spent" value={money(total.spend)}/><Kpi label="Results" value={num(total.results).toLocaleString()}/><Kpi label="Cost / Result" value={money(cpr)}/><Kpi label="CTR" value={`${ctr.toFixed(2)}%`}/><Kpi label="CPM" value={money(cpm)}/><Kpi label="Purchases / مشتريات" value={num(total.purchases).toLocaleString()}/><Kpi label="Revenue" value={money(total.revenue)}/><Kpi label="ROAS" value={`${roas.toFixed(2)}×`}/>
    </div>
    <div style={{display:'grid',gap:16}}>{(data.accountGroups||[]).map((a:any)=>{const m=a.metrics||{};return <section key={a.id} style={{background:'var(--card-bg)',border:'1px solid var(--card-border)',borderRadius:18,overflow:'hidden'}}><div style={{padding:'16px 18px',borderBottom:'1px solid var(--card-border)',display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><div style={{fontSize:11,color:'var(--text-muted)',fontWeight:800}}>{a.platform} · {a.clientName}</div><h3 style={{fontSize:20,marginTop:3}}>{a.accountName||a.adAccountId}</h3><div style={{fontSize:11,color:'var(--text-muted)'}}>Account ID {a.adAccountId} · {a.campaignCount||0} campaign(s)</div></div><div style={{fontWeight:900,fontSize:22}}>{money(m.spend,a.currency||'EGP')}</div></div><div style={{padding:14,display:'grid',gap:12}}>{(a.campaigns||[]).map((c:any)=><CampaignCard key={c.id} c={c} onArchive={()=>act('archive_campaign',c.id)} onDelete={()=>act('delete_campaign',c.id)} onSync={()=>sync(c.id)} syncing={syncing===c.id}/>)}</div></section>})}{!data.accountGroups?.length&&<div className="card"><div className="card-body">No linked ad accounts yet.</div></div>}</div>
   </>}
   {tab==='campaigns'&&<div style={{display:'grid',gap:12}}>{(data.campaigns||[]).map((c:any)=><CampaignCard key={c.id} c={c} onArchive={()=>act('archive_campaign',c.id)} onDelete={()=>act('delete_campaign',c.id)} onSync={()=>sync(c.id)} syncing={syncing===c.id}/>)}{!data.campaigns?.length&&<div className="card"><div className="card-body">No linked campaigns.</div></div>}</div>}
   {tab==='accounts'&&<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:12}}>{(data.accountGroups||[]).map((a:any)=><div key={a.id} className="card"><div className="card-body"><div style={{fontSize:11,color:'var(--text-muted)'}}>{a.platform} · {a.clientName}</div><h3 style={{margin:'6px 0'}}>{a.accountName||a.adAccountId}</h3><div style={{fontSize:12,color:'var(--text-muted)'}}>Account ID {a.adAccountId}</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginTop:14}}><Kpi label="Spend" value={money(a.metrics?.spend,a.currency||'EGP')}/><Kpi label="Campaigns" value={String(a.campaignCount||0)}/></div></div></div>)}</div>}
  </>}
 </div>}
function CampaignCard({c,onArchive,onDelete,onSync,syncing}:{c:any;onArchive:()=>void;onDelete:()=>void;onSync:()=>void;syncing:boolean}){const m=c.metrics||{},cost=num(m.costPerResult)||(num(m.results)?num(m.spend)/num(m.results):0),ctr=num(m.ctr),freq=num(m.frequency),cpm=num(m.cpm);return <article style={{border:'1px solid var(--card-border)',borderRadius:16,padding:16,background:'var(--bg-primary)'}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'flex-start',flexWrap:'wrap'}}><div><div style={{fontSize:10,fontWeight:900,color:'var(--accent)',textTransform:'uppercase'}}>{c.platform} · {c.metricSource==='META_REPORTED'?'META REPORTED':'ERP DAILY'}</div><h3 style={{fontSize:18,margin:'4px 0'}}>{c.name}</h3><div style={{fontSize:11,color:'var(--text-muted)'}}>Campaign ID {c.externalId} · {c.clientName}</div></div><div style={{display:'flex',gap:6,flexWrap:'wrap'}}><button className="btn btn-secondary btn-sm" onClick={onSync} disabled={syncing}>{syncing?'Syncing…':'Sync now'}</button><button className="btn btn-secondary btn-sm" onClick={onArchive}>Archive</button><button className="btn btn-danger btn-sm" onClick={onDelete}>Delete</button></div></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(135px,1fr))',gap:8,marginTop:14}}><Kpi label="Amount Spent" value={money(m.spend,c.currency)}/><Kpi label={m.resultLabel||'Results'} value={num(m.results).toLocaleString()}/><Kpi label="Cost / Result" value={money(cost,c.currency)}/><Kpi label="CTR" value={`${ctr.toFixed(2)}%`}/><Kpi label="Frequency" value={freq.toFixed(2)}/><Kpi label="CPM" value={money(cpm,c.currency)}/><Kpi label="Purchases / مشتريات" value={num(m.purchases).toLocaleString()}/><Kpi label="Revenue" value={money(m.revenue,c.currency)}/><Kpi label="ROAS" value={`${num(m.roas).toFixed(2)}×`}/><Kpi label="Reach" value={num(m.reach).toLocaleString()}/><Kpi label="Impressions" value={num(m.impressions).toLocaleString()}/><Kpi label="Add to Cart" value={num(m.addToCart).toLocaleString()}/></div></article>}
