"use client";
import {useEffect,useMemo,useState} from "react";
const money=(v:any,c="EGP")=>new Intl.NumberFormat("en-EG",{style:"currency",currency:c||"EGP",maximumFractionDigits:2}).format(Number(v||0));
const num=(v:any)=>Number(v||0),iso=(d:Date)=>d.toISOString().slice(0,10);
function Kpi({label,value,sub}:{label:string;value:string;sub?:string}){return <div style={{background:"var(--card-bg)",border:"1px solid var(--card-border)",borderRadius:16,padding:"16px 18px",minHeight:96,boxShadow:"0 6px 18px rgba(15,23,42,.04)"}}><div style={{fontSize:11,fontWeight:800,color:"var(--text-muted)",letterSpacing:.4,textTransform:"uppercase"}}>{label}</div><div style={{fontSize:24,fontWeight:900,marginTop:8,color:"var(--text-primary)"}}>{value}</div>{sub&&<div style={{fontSize:10.5,color:"var(--text-muted)",marginTop:4}}>{sub}</div>}</div>}
function MiniMetrics({m,currency="EGP"}:{m:any;currency?:string}){const x=m||{},cpr=num(x.costPerResult)||(num(x.results)?num(x.spend)/num(x.results):0);return <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(105px,1fr))',gap:7,marginTop:9}}>{[["Spend",money(x.spend,currency)],["Results",num(x.results).toLocaleString()],["Cost / Result",money(cpr,currency)],["CTR",`${num(x.ctr).toFixed(2)}%`],["Purchases",num(x.purchases).toLocaleString()],["ROAS",`${num(x.roas).toFixed(2)}×`]].map(([l,v])=><div key={l} style={{padding:'8px 9px',border:'1px solid var(--card-border)',borderRadius:10,background:'var(--card-bg)'}}><div style={{fontSize:9,color:'var(--text-muted)',fontWeight:800,textTransform:'uppercase'}}>{l}</div><div style={{fontSize:12,fontWeight:850,marginTop:3}}>{v}</div></div>)}</div>}
function Hierarchy({sets,currency}:{sets:any[];currency:string}){const adCount=(sets||[]).reduce((s,x)=>s+(x.ads?.length||0),0);if(!sets?.length)return <div style={{marginTop:12,padding:'10px 12px',border:'1px dashed var(--card-border)',borderRadius:12,fontSize:11,color:'var(--text-muted)'}}>No Ad Set / Ad drilldown stored for this selected range yet. Click <b>Sync selected range</b> to load Meta hierarchy.</div>;return <details style={{marginTop:14,borderTop:'1px solid var(--card-border)',paddingTop:12}}><summary style={{cursor:'pointer',fontSize:12,fontWeight:850,color:'var(--text-secondary)'}}>Ad Set → Ad drilldown · {sets.length} ad set(s) · {adCount} ad(s)</summary><div style={{display:'grid',gap:9,marginTop:10}}>{sets.map((s:any)=><details key={s.id} style={{border:'1px solid var(--card-border)',borderRadius:12,padding:10,background:'var(--bg-subtle)'}}><summary style={{cursor:'pointer',display:'flex',justifyContent:'space-between',gap:10,alignItems:'center',listStyle:'none'}}><span><b style={{fontSize:12}}>{s.name}</b><span style={{display:'block',fontSize:9.5,color:'var(--text-muted)',marginTop:2}}>Ad Set ID {s.externalId} · {s.status||'UNKNOWN'} · {s.ads?.length||0} ad(s)</span></span><span className="badge badge-gray">Ad Set</span></summary><MiniMetrics m={s.metrics} currency={currency}/><div style={{display:'grid',gap:7,marginTop:10}}>{(s.ads||[]).map((a:any)=><div key={a.id} style={{border:'1px solid var(--card-border)',borderRadius:10,padding:9,background:'var(--card-bg)'}}><div style={{display:'flex',justifyContent:'space-between',gap:8,alignItems:'center'}}><div><b style={{fontSize:11.5}}>{a.name}</b><div style={{fontSize:9.5,color:'var(--text-muted)',marginTop:2}}>Ad ID {a.externalId} · {a.status||'UNKNOWN'}</div></div><span className="badge badge-blue">Ad</span></div><MiniMetrics m={a.metrics} currency={currency}/></div>)}{!s.ads?.length&&<div style={{fontSize:10.5,color:'var(--text-muted)'}}>No ads stored under this ad set for the current hierarchy.</div>}</div></details>)}</div></details>}
export function MediaControlV2(){
 const today=iso(new Date()),defaultFrom=iso(new Date(Date.now()-30*86400000));
 const[data,setData]=useState<any>({campaigns:[],archivedCampaigns:[],accountGroups:[],clients:[],range:{start:defaultFrom,end:today},access:{}}),[loading,setLoading]=useState(true),[msg,setMsg]=useState(""),[tab,setTab]=useState("overview"),[syncing,setSyncing]=useState<string|null>(null),[from,setFrom]=useState(defaultFrom),[to,setTo]=useState(today);
 async function load(start=from,end=to){setLoading(true);setMsg("");try{const q=new URLSearchParams({from:start,to:end}),r=await fetch(`/api/media-control-v2?${q}`,{cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Could not load media control data');setData(d)}catch(e:any){setMsg(e.message||'Could not load media control data')}finally{setLoading(false)}}
 useEffect(()=>{load(defaultFrom,today)},[]);
 useEffect(()=>{const t=setInterval(()=>load(from,to),30000);return()=>clearInterval(t)},[from,to]);
 function applyRange(e?:React.FormEvent){e?.preventDefault();if(!from||!to||from>to){setMsg('Choose a valid date range.');return}load(from,to)}
 function preset(days:number){const end=iso(new Date()),start=iso(new Date(Date.now()-(days-1)*86400000));setFrom(start);setTo(end);load(start,end)}
 function monthToDate(){const d=new Date(),start=iso(new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),1))),end=iso(d);setFrom(start);setTo(end);load(start,end)}
 async function act(op:string,id:string){if(op==='delete_campaign'&&!confirm('Permanently delete this archived campaign from VIVIT? Meta itself will not be changed.'))return;const r=await fetch('/api/media-control-v2',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({op,campaignId:id})}),d=await r.json().catch(()=>({}));setMsg(r.ok?(op==='archive_campaign'?'Campaign archived.':op==='restore_campaign'?'Campaign restored.':'Campaign deleted from VIVIT.'):d.error||'Action failed');if(r.ok)load()}
 async function sync(id:string){setSyncing(id);setMsg('');try{const r=await fetch('/api/media-control-v2',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({op:'sync_campaign',campaignId:id,from,to})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Campaign sync failed');const hr=await fetch(`/api/media-hierarchy/${id}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({from,to})}),h=await hr.json().catch(()=>({}));if(!hr.ok)throw new Error(`Campaign totals synced, but hierarchy failed: ${h.error||'unknown hierarchy error'}`);setMsg(`Campaign synced for ${from} → ${to} (${d.days||0} campaign days · ${h.adSets||0} ad sets · ${h.ads||0} ads · ${h.rows||0} hierarchy rows).`);await load()}catch(e:any){setMsg(e.message||'Sync failed')}finally{setSyncing(null)}}
 const total=useMemo(()=>data.campaigns?.reduce((a:any,c:any)=>{const m=c.metrics||{};for(const k of['spend','results','purchases','revenue','impressions','clicks','reach','addToCart'])a[k]+=num(m[k]);return a},{spend:0,results:0,purchases:0,revenue:0,impressions:0,clicks:0,reach:0,addToCart:0})||{},[data.campaigns]);
 const ctr=total.impressions?total.clicks/total.impressions*100:0,cpm=total.impressions?total.spend/total.impressions*1000:0,cpr=total.results?total.spend/total.results:0,roas=total.spend?total.revenue/total.spend:0;
 return <div style={{display:'grid',gap:18}}>
  <div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'flex-end',flexWrap:'wrap'}}><div><h1 className="page-title">Media Buying Control Center</h1><p className="page-subtitle">Account-first live performance · Campaign → Ad Set → Ad drilldown under the selected date range</p></div><div style={{fontSize:11,color:'var(--text-muted)'}}>Auto refresh every 30 seconds</div></div>
  <form onSubmit={applyRange} className="card"><div className="card-body" style={{display:'flex',gap:8,alignItems:'end',flexWrap:'wrap'}}><label className="form-label" style={{margin:0}}>FROM<input aria-label="Media report from date" type="date" value={from} max={to||today} onChange={e=>setFrom(e.target.value)} className="form-input"/></label><label className="form-label" style={{margin:0}}>TO<input aria-label="Media report to date" type="date" value={to} min={from} max={today} onChange={e=>setTo(e.target.value)} className="form-input"/></label><button className="btn btn-primary" disabled={loading}>Apply range</button><button type="button" className="btn btn-secondary" onClick={()=>preset(7)}>Last 7 days</button><button type="button" className="btn btn-secondary" onClick={()=>preset(30)}>Last 30 days</button><button type="button" className="btn btn-secondary" onClick={monthToDate}>MTD</button><span style={{fontSize:11,color:'var(--text-muted)',marginLeft:'auto'}}>Showing {data.range?.start||from} → {data.range?.end||to}</span></div></form>
  <div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{['overview','campaigns','accounts','archived'].map(x=><button key={x} onClick={()=>setTab(x)} className={tab===x?'btn btn-primary':'btn btn-secondary'}>{x==='overview'?'Overview':x==='campaigns'?'Campaigns':x==='accounts'?'Ad Accounts':`Archived (${data.archivedCampaigns?.length||0})`}</button>)}</div>
  {msg&&<div className="card"><div className="card-body" role="status">{msg}</div></div>}
  {loading?<div className="card"><div className="card-body">Loading live media data…</div></div>:<>
   {tab==='overview'&&<><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(165px,1fr))',gap:12}}><Kpi label="Amount Spent" value={money(total.spend)}/><Kpi label="Results" value={num(total.results).toLocaleString()}/><Kpi label="Cost / Result" value={money(cpr)}/><Kpi label="CTR" value={`${ctr.toFixed(2)}%`}/><Kpi label="CPM" value={money(cpm)}/><Kpi label="Purchases / مشتريات" value={num(total.purchases).toLocaleString()}/><Kpi label="Revenue" value={money(total.revenue)}/><Kpi label="ROAS" value={`${roas.toFixed(2)}×`}/></div><div style={{display:'grid',gap:16}}>{(data.accountGroups||[]).map((a:any)=>{const m=a.metrics||{};return <section key={a.id} style={{background:'var(--card-bg)',border:'1px solid var(--card-border)',borderRadius:18,overflow:'hidden'}}><div style={{padding:'16px 18px',borderBottom:'1px solid var(--card-border)',display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><div style={{fontSize:11,color:'var(--text-muted)',fontWeight:800}}>{a.platform} · {a.clientName}</div><h3 style={{fontSize:20,marginTop:3}}>{a.accountName||a.adAccountId}</h3><div style={{fontSize:11,color:'var(--text-muted)'}}>Account ID {a.adAccountId} · {a.campaignCount||0} campaign(s)</div></div><div style={{fontWeight:900,fontSize:22}}>{money(m.spend,a.currency||'EGP')}</div></div><div style={{padding:14,display:'grid',gap:12}}>{(a.campaigns||[]).map((c:any)=><CampaignCard key={c.id} c={c} onArchive={()=>act('archive_campaign',c.id)} onSync={()=>sync(c.id)} syncing={syncing===c.id}/>)}</div></section>})}{!data.accountGroups?.length&&<div className="card"><div className="card-body">No linked ad accounts yet.</div></div>}</div></>}
   {tab==='campaigns'&&<div style={{display:'grid',gap:12}}>{(data.campaigns||[]).map((c:any)=><CampaignCard key={c.id} c={c} onArchive={()=>act('archive_campaign',c.id)} onSync={()=>sync(c.id)} syncing={syncing===c.id}/>)}{!data.campaigns?.length&&<div className="card"><div className="card-body">No linked campaigns.</div></div>}</div>}
   {tab==='accounts'&&<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:12}}>{(data.accountGroups||[]).map((a:any)=><div key={a.id} className="card"><div className="card-body"><div style={{fontSize:11,color:'var(--text-muted)'}}>{a.platform} · {a.clientName}</div><h3 style={{margin:'6px 0'}}>{a.accountName||a.adAccountId}</h3><div style={{fontSize:12,color:'var(--text-muted)'}}>Account ID {a.adAccountId}</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginTop:14}}><Kpi label="Spend" value={money(a.metrics?.spend,a.currency||'EGP')}/><Kpi label="Campaigns" value={String(a.campaignCount||0)}/></div></div></div>)}</div>}
   {tab==='archived'&&<div style={{display:'grid',gap:12}}>{(data.archivedCampaigns||[]).map((c:any)=><article key={c.id} className="card"><div className="card-body" style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><div style={{fontSize:10,fontWeight:900,color:'var(--text-muted)'}}>{c.platform} · {c.clientName}</div><h3 style={{margin:'4px 0'}}>{c.name}</h3><div style={{fontSize:11,color:'var(--text-muted)'}}>Campaign ID {c.externalId}</div></div><div style={{display:'flex',gap:6}}><button className="btn btn-secondary btn-sm" onClick={()=>act('restore_campaign',c.id)}>Restore</button>{data.access?.canHardDelete&&<button className="btn btn-danger btn-sm" onClick={()=>act('delete_campaign',c.id)}>Delete permanently</button>}</div></div></article>)}{!data.archivedCampaigns?.length&&<div className="card"><div className="card-body">No archived campaigns.</div></div>}</div>}
  </>}
 </div>}
function CampaignCard({c,onArchive,onSync,syncing}:{c:any;onArchive:()=>void;onSync:()=>void;syncing:boolean}){const m=c.metrics||{},cost=num(m.costPerResult)||(num(m.results)?num(m.spend)/num(m.results):0),ctr=num(m.ctr),freq=num(m.frequency),cpm=num(m.cpm);return <article style={{border:'1px solid var(--card-border)',borderRadius:16,padding:16,background:'var(--bg-primary)'}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'flex-start',flexWrap:'wrap'}}><div><div style={{fontSize:10,fontWeight:900,color:'var(--accent)',textTransform:'uppercase'}}>{c.platform} · {c.metricSource==='META_REPORTED'?'META REPORTED':'ERP DAILY'}</div><h3 style={{fontSize:18,margin:'4px 0'}}>{c.name}</h3><div style={{fontSize:11,color:'var(--text-muted)'}}>Campaign ID {c.externalId} · {c.clientName}</div></div><div style={{display:'flex',gap:6,flexWrap:'wrap'}}><button className="btn btn-secondary btn-sm" onClick={onSync} disabled={syncing}>{syncing?'Syncing…':'Sync selected range'}</button><button className="btn btn-secondary btn-sm" onClick={onArchive}>Archive</button></div></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(135px,1fr))',gap:8,marginTop:14}}><Kpi label="Amount Spent" value={money(m.spend,c.currency)}/><Kpi label={m.resultLabel||'Results'} value={num(m.results).toLocaleString()}/><Kpi label="Cost / Result" value={money(cost,c.currency)}/><Kpi label="CTR" value={`${ctr.toFixed(2)}%`}/><Kpi label="Frequency" value={freq.toFixed(2)}/><Kpi label="CPM" value={money(cpm,c.currency)}/><Kpi label="Purchases / مشتريات" value={num(m.purchases).toLocaleString()}/><Kpi label="Revenue" value={money(m.revenue,c.currency)}/><Kpi label="ROAS" value={`${num(m.roas).toFixed(2)}×`}/><Kpi label="Reach" value={num(m.reach).toLocaleString()}/><Kpi label="Impressions" value={num(m.impressions).toLocaleString()}/><Kpi label="Add to Cart" value={num(m.addToCart).toLocaleString()}/></div><Hierarchy sets={c.adSets||[]} currency={c.currency||'EGP'}/></article>}
