"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {MediaIntelligenceWorkspaceV2} from "@/components/media/MediaIntelligenceWorkspaceV2";

type Campaign={id:string;name:string;clientName?:string;platform?:string;status?:string;currency?:string;metrics?:{spend?:number;results?:number;ctr?:number;roas?:number;costPerResult?:number;resultLabel?:string};externalId?:string};
type AccountGroup={id?:string;clientName?:string;accountName?:string;adAccountId?:string;currency?:string;campaigns?:Campaign[];metrics?:{spend?:number;results?:number;ctr?:number;roas?:number}};
const money=(v:unknown,c="EGP")=>new Intl.NumberFormat("en-EG",{style:"currency",currency:c||"EGP",maximumFractionDigits:0}).format(Number(v||0));
const cairoDate=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Africa/Cairo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());

export function MediaCampaignFirstView(){
 const today=cairoDate(),from=`${today.slice(0,7)}-01`;
 const[campaigns,setCampaigns]=useState<Campaign[]>([]),[accounts,setAccounts]=useState<AccountGroup[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[showFull,setShowFull]=useState(false),[busy,setBusy]=useState("");
 const load=useCallback(async()=>{setLoading(true);setMessage("");try{const r=await fetch(`/api/media-control-v2?from=${from}&to=${today}`,{cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Could not load campaigns");setCampaigns(Array.isArray(d.campaigns)?d.campaigns:[]);setAccounts(Array.isArray(d.accountGroups)?d.accountGroups:[])}catch(e){setMessage(e instanceof Error?e.message:"Could not load campaigns")}finally{setLoading(false)}},[from,today]);
 useEffect(()=>{const timer=window.setTimeout(()=>{void load()},0);return()=>window.clearTimeout(timer)},[load]);
 const fallbackAccounts=useMemo(()=>{if(accounts.length)return accounts;const map=new Map<string,AccountGroup>();for(const c of campaigns){const key=c.clientName||"Client";const a=map.get(key)||{id:key,clientName:key,accountName:key,campaigns:[],currency:c.currency||"EGP"};a.campaigns=[...(a.campaigns||[]),c];map.set(key,a)}return [...map.values()]},[accounts,campaigns]);
 async function lifecycle(c:Campaign,action:"archive"|"delete"){
  if(!confirm(action==="archive"?`Archive “${c.name}”?`:`Delete “${c.name}”? If it has reporting history it will remain archived.`))return;
  setBusy(`${c.id}:${action}`);setMessage("");
  try{const request=async(a:"archive"|"delete")=>{const r=await fetch("/api/campaign-lifecycle",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:c.id,action:a})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Could not ${a} campaign`)};if(action==="delete"){try{await request("archive")}catch(e){if(!/already archived/i.test(e instanceof Error?e.message:""))throw e}await request("delete")}else await request("archive");setMessage(action==="archive"?"Campaign archived.":"Campaign delete completed.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Campaign action failed")}finally{setBusy("")}
 }
 return <div className="mcf-shell"><style>{`
 .mcf-shell{display:grid;gap:16px;min-width:0;color:var(--text-primary)}.mcf-toolbar{display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap;padding:2px}.mcf-toolbar h2{margin:0;font-size:23px;letter-spacing:-.03em;color:var(--text-primary)}.mcf-toolbar p{margin:4px 0 0;color:var(--text-muted);font-size:12px;line-height:1.5}.mcf-actions{display:flex;gap:8px;flex-wrap:wrap}.mcf-accounts{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.mcf-account{background:linear-gradient(145deg,var(--card-bg),var(--bg-secondary));border:1px solid var(--card-border);border-radius:22px;padding:18px;box-shadow:var(--shadow-sm);min-width:0}.mcf-account-head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start;padding-bottom:14px;border-bottom:1px solid var(--card-border)}.mcf-account-head h3{margin:5px 0 3px;font-size:19px;color:var(--text-primary);overflow-wrap:anywhere;letter-spacing:-.02em}.mcf-account-head small{color:var(--text-muted)}.mcf-total{font-size:19px;font-weight:850;color:var(--text-primary);white-space:nowrap}.mcf-account-metrics{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px;margin:14px 0}.mcf-account-metrics div,.mcf-metric{background:var(--bg-tertiary);border:1px solid var(--card-border);border-radius:13px;padding:11px;min-width:0}.mcf-account-metrics span,.mcf-metric span{display:block;color:var(--text-muted);font-size:10.5px}.mcf-account-metrics b,.mcf-metric b{display:block;margin-top:5px;color:var(--text-primary);font-size:13.5px;overflow-wrap:anywhere}.mcf-campaign-list{display:grid;gap:10px}.mcf-card{background:var(--card-bg);border:1px solid var(--card-border);border-radius:16px;padding:14px;min-width:0;box-shadow:0 8px 24px rgba(15,23,42,.04);transition:transform .18s ease,border-color .18s ease,box-shadow .18s ease}.mcf-card:hover{transform:translateY(-1px);box-shadow:0 12px 30px rgba(15,23,42,.07)}.mcf-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.mcf-name{min-width:0}.mcf-name h4{margin:5px 0 3px;font-size:14.5px;line-height:1.25;color:var(--text-primary);overflow-wrap:anywhere}.mcf-name small{color:var(--text-muted);font-size:10.5px}.mcf-card-actions{display:flex;gap:7px;flex-wrap:wrap;justify-content:flex-end}.mcf-card-actions .btn{min-height:40px;min-width:78px}.mcf-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin-top:12px}.mcf-status{padding:11px 13px;border-radius:13px;background:var(--bg-tertiary);border:1px solid var(--card-border);color:var(--text-secondary);font-size:12px}.mcf-full{min-width:0;overflow:hidden}
 html.dark .mcf-account{background:linear-gradient(145deg,#101f33,#0b1728);border-color:rgba(139,170,210,.15);box-shadow:0 18px 48px rgba(0,0,0,.28)}html.dark .mcf-card{background:linear-gradient(145deg,#0e1b2d,#0a1625);border-color:rgba(139,170,210,.14);box-shadow:0 10px 28px rgba(0,0,0,.17)}html.dark .mcf-account-metrics div,html.dark .mcf-metric{background:#13243a;border-color:rgba(139,170,210,.13)}html.dark .mcf-toolbar h2,html.dark .mcf-account-head h3,html.dark .mcf-total,html.dark .mcf-name h4,html.dark .mcf-account-metrics b,html.dark .mcf-metric b{color:#edf4fb}html.dark .mcf-toolbar p,html.dark .mcf-account-head small,html.dark .mcf-name small,html.dark .mcf-account-metrics span,html.dark .mcf-metric span{color:#91a7c0}html.dark .mcf-status{background:#101e31;color:#b6c9dd;border-color:rgba(139,170,210,.14)}
 @media(max-width:900px){.mcf-accounts{grid-template-columns:1fr}.mcf-account{padding:15px;border-radius:18px}.mcf-account-head{flex-direction:column}.mcf-total{font-size:17px}.mcf-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.mcf-card-actions{width:100%;display:grid;grid-template-columns:1fr 1fr}.mcf-card-actions button{width:100%}}
 @media(max-width:560px){.mcf-shell{gap:11px}.mcf-toolbar{align-items:stretch}.mcf-actions{display:grid;grid-template-columns:1fr 1fr;width:100%}.mcf-actions button{width:100%}.mcf-account-metrics{grid-template-columns:repeat(3,minmax(0,1fr))}.mcf-account-metrics b{font-size:12px}.mcf-head{flex-direction:column}.mcf-name h4{font-size:14px}}
 `}</style>
 <div className="mcf-toolbar"><div><h2>Campaigns by account</h2><p>Account summary and campaigns appear immediately. Full intelligence loads only when requested.</p></div><div className="mcf-actions"><button type="button" className="btn btn-secondary" onClick={()=>void load()} disabled={loading}>{loading?"Loading…":"Refresh"}</button><button type="button" className="btn btn-primary" onClick={()=>setShowFull(v=>!v)}>{showFull?"Hide full intelligence":"Open full intelligence"}</button></div></div>
 {message&&<div className="mcf-status">{message}</div>}
 {loading&&!fallbackAccounts.length?<div className="mcf-status">Loading campaigns…</div>:<div className="mcf-accounts">{fallbackAccounts.map((a,idx)=>{const list=a.campaigns||[],spend=list.reduce((s,c)=>s+Number(c.metrics?.spend||0),0),results=list.reduce((s,c)=>s+Number(c.metrics?.results||0),0),currency=a.currency||list[0]?.currency||"EGP";return <section className="mcf-account" key={a.id||a.adAccountId||`${a.clientName}-${idx}`}><div className="mcf-account-head"><div><span className="eyebrow">AD ACCOUNT · {list.length} CAMPAIGNS</span><h3>{a.accountName||a.clientName||a.adAccountId||"Ad Account"}</h3><small>{a.clientName||"Client"}{a.adAccountId?` · ${a.adAccountId}`:""}</small></div><div className="mcf-total">{money(spend,currency)}</div></div><div className="mcf-account-metrics"><div><span>Campaigns</span><b>{list.length}</b></div><div><span>Spend MTD</span><b>{money(spend,currency)}</b></div><div><span>Results</span><b>{results.toLocaleString()}</b></div></div><div className="mcf-campaign-list">{list.map(c=>{const m=c.metrics||{},label=m.resultLabel||"Results";return <article className="mcf-card" key={c.id}><div className="mcf-head"><div className="mcf-name"><span className="eyebrow">{c.platform||"MEDIA"} · {c.status||"ACTIVE"}</span><h4>{c.name}</h4><small>{c.externalId||"Campaign"}</small></div><div className="mcf-card-actions"><button type="button" className="btn btn-secondary btn-sm" disabled={Boolean(busy)} onClick={()=>void lifecycle(c,"archive")}>Archive</button><button type="button" className="btn btn-danger btn-sm" disabled={Boolean(busy)} onClick={()=>void lifecycle(c,"delete")}>Delete</button></div></div><div className="mcf-metrics"><div className="mcf-metric"><span>Spend</span><b>{money(m.spend,c.currency||currency)}</b></div><div className="mcf-metric"><span>{label}</span><b>{Number(m.results||0).toLocaleString()}</b></div><div className="mcf-metric"><span>CTR</span><b>{Number(m.ctr||0).toFixed(2)}%</b></div><div className="mcf-metric"><span>ROAS</span><b>{Number(m.roas||0).toFixed(2)}×</b></div></div></article>})}</div></section>})}{!loading&&!fallbackAccounts.length&&<div className="mcf-status">No campaigns for the selected month.</div>}</div>}
 {showFull&&<div className="mcf-full"><MediaIntelligenceWorkspaceV2/></div>}
 </div>
}
