"use client";
import {useEffect,useMemo,useState} from "react";
import {MediaIntelligenceWorkspaceV2} from "@/components/media/MediaIntelligenceWorkspaceV2";

type Campaign={id:string;name:string;clientName?:string;platform?:string;status?:string;currency?:string;metrics?:{spend?:number;results?:number;ctr?:number;roas?:number;costPerResult?:number;resultLabel?:string};externalId?:string};
type AccountGroup={id?:string;clientName?:string;accountName?:string;adAccountId?:string;currency?:string;campaigns?:Campaign[];metrics?:{spend?:number;results?:number;ctr?:number;roas?:number}};
const money=(v:unknown,c="EGP")=>new Intl.NumberFormat("en-EG",{style:"currency",currency:c||"EGP",maximumFractionDigits:0}).format(Number(v||0));
const cairoDate=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Africa/Cairo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());

export function MediaCampaignFirstView(){
 const today=cairoDate(),from=`${today.slice(0,7)}-01`;
 const[campaigns,setCampaigns]=useState<Campaign[]>([]),[accounts,setAccounts]=useState<AccountGroup[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[showFull,setShowFull]=useState(false),[busy,setBusy]=useState("");
 async function load(){setLoading(true);setMessage("");try{const r=await fetch(`/api/media-control-v2?from=${from}&to=${today}`,{cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Could not load campaigns");setCampaigns(Array.isArray(d.campaigns)?d.campaigns:[]);setAccounts(Array.isArray(d.accountGroups)?d.accountGroups:[])}catch(e){setMessage(e instanceof Error?e.message:"Could not load campaigns")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const fallbackAccounts=useMemo(()=>{if(accounts.length)return accounts;const map=new Map<string,AccountGroup>();for(const c of campaigns){const key=c.clientName||"Client";const a=map.get(key)||{id:key,clientName:key,accountName:key,campaigns:[],currency:c.currency||"EGP"};a.campaigns=[...(a.campaigns||[]),c];map.set(key,a)}return [...map.values()]},[accounts,campaigns]);
 async function lifecycle(c:Campaign,action:"archive"|"delete"){
  if(!confirm(action==="archive"?`Archive “${c.name}”?`:`Delete “${c.name}”? If it has reporting history it will remain archived.`))return;
  setBusy(`${c.id}:${action}`);setMessage("");
  try{const request=async(a:"archive"|"delete")=>{const r=await fetch("/api/campaign-lifecycle",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:c.id,action:a})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Could not ${a} campaign`)};if(action==="delete"){try{await request("archive")}catch(e){if(!/already archived/i.test(e instanceof Error?e.message:""))throw e}await request("delete")}else await request("archive");setMessage(action==="archive"?"Campaign archived.":"Campaign delete completed.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Campaign action failed")}finally{setBusy("")}
 }
 return <div className="mcf-shell"><style>{`
 .mcf-shell{display:grid;gap:14px;min-width:0;color:#172033;--card-bg:#fff;--card-border:#e5e9f1;--bg-secondary:#f6f8fc;--text-primary:#172033;--text-muted:#6b7690;--text-secondary:#4f5d78}.mcf-toolbar{display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap}.mcf-toolbar h2{margin:0;font-size:21px;color:#172033}.mcf-toolbar p{margin:3px 0 0;color:#69758d;font-size:12px}.mcf-actions{display:flex;gap:8px;flex-wrap:wrap}.mcf-accounts{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.mcf-account{background:#fff;border:1px solid #e4e8f0;border-radius:20px;padding:16px;box-shadow:0 12px 36px rgba(29,43,72,.07);min-width:0}.mcf-account-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;padding-bottom:12px;border-bottom:1px solid #eef1f5}.mcf-account-head h3{margin:4px 0 2px;font-size:18px;color:#172033;overflow-wrap:anywhere}.mcf-account-head small{color:#778199}.mcf-total{font-size:18px;font-weight:850;color:#172033;white-space:nowrap}.mcf-account-metrics{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin:12px 0}.mcf-account-metrics div,.mcf-metric{background:#f6f8fc;border:1px solid #edf0f5;border-radius:12px;padding:10px;min-width:0}.mcf-account-metrics span,.mcf-metric span{display:block;color:#768198;font-size:10px}.mcf-account-metrics b,.mcf-metric b{display:block;margin-top:4px;color:#172033;font-size:13px;overflow-wrap:anywhere}.mcf-campaign-list{display:grid;gap:9px}.mcf-card{background:#fbfcfe;border:1px solid #e8ecf3;border-radius:14px;padding:12px;min-width:0}.mcf-head{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.mcf-name{min-width:0}.mcf-name h4{margin:3px 0;font-size:14px;line-height:1.25;color:#172033;overflow-wrap:anywhere}.mcf-name small{color:#798399;font-size:10px}.mcf-card-actions{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}.mcf-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px;margin-top:10px}.mcf-status{padding:10px 12px;border-radius:12px;background:#f6f8fc;color:#68748b;font-size:12px}.mcf-full{min-width:0;overflow:hidden}.vx-apps{right:126px!important;bottom:calc(88px + env(safe-area-inset-bottom))!important}.vivit-lang-switch{right:14px!important;bottom:calc(88px + env(safe-area-inset-bottom))!important}
 @media(max-width:900px){.mcf-accounts{grid-template-columns:1fr}.mcf-account{padding:14px;border-radius:17px}.mcf-account-head{flex-direction:column}.mcf-total{font-size:16px}.mcf-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.mcf-card-actions{width:100%;display:grid;grid-template-columns:1fr 1fr}.mcf-card-actions button{width:100%}}
 @media(max-width:560px){.mcf-shell{gap:10px}.mcf-toolbar{align-items:stretch}.mcf-actions{display:grid;grid-template-columns:1fr 1fr;width:100%}.mcf-actions button{width:100%}.mcf-account-metrics{grid-template-columns:repeat(3,minmax(0,1fr))}.mcf-account-metrics b{font-size:12px}.mcf-head{flex-direction:column}.mcf-name h4{font-size:14px}.vx-apps{right:128px!important}.vivit-lang-switch{right:12px!important}}
 `}</style>
 <div className="mcf-toolbar"><div><h2>Campaigns by account</h2><p>Account summary and campaigns appear immediately. Full intelligence loads only when requested.</p></div><div className="mcf-actions"><button className="btn btn-secondary" onClick={()=>void load()} disabled={loading}>{loading?"Loading…":"Refresh"}</button><button className="btn btn-primary" onClick={()=>setShowFull(v=>!v)}>{showFull?"Hide full intelligence":"Open full intelligence"}</button></div></div>
 {message&&<div className="mcf-status">{message}</div>}
 {loading&&!fallbackAccounts.length?<div className="mcf-status">Loading campaigns…</div>:<div className="mcf-accounts">{fallbackAccounts.map((a,idx)=>{const list=a.campaigns||[],spend=list.reduce((s,c)=>s+Number(c.metrics?.spend||0),0),results=list.reduce((s,c)=>s+Number(c.metrics?.results||0),0),currency=a.currency||list[0]?.currency||"EGP";return <section className="mcf-account" key={a.id||a.adAccountId||`${a.clientName}-${idx}`}><div className="mcf-account-head"><div><span className="eyebrow">AD ACCOUNT · {list.length} CAMPAIGNS</span><h3>{a.accountName||a.clientName||a.adAccountId||"Ad Account"}</h3><small>{a.clientName||"Client"}{a.adAccountId?` · ${a.adAccountId}`:""}</small></div><div className="mcf-total">{money(spend,currency)}</div></div><div className="mcf-account-metrics"><div><span>Campaigns</span><b>{list.length}</b></div><div><span>Spend MTD</span><b>{money(spend,currency)}</b></div><div><span>Results</span><b>{results.toLocaleString()}</b></div></div><div className="mcf-campaign-list">{list.map(c=>{const m=c.metrics||{},label=m.resultLabel||"Results";return <article className="mcf-card" key={c.id}><div className="mcf-head"><div className="mcf-name"><span className="eyebrow">{c.platform||"MEDIA"} · {c.status||"ACTIVE"}</span><h4>{c.name}</h4><small>{c.externalId||"Campaign"}</small></div><div className="mcf-card-actions"><button className="btn btn-secondary btn-sm" disabled={Boolean(busy)} onClick={()=>void lifecycle(c,"archive")}>Archive</button><button className="btn btn-danger btn-sm" disabled={Boolean(busy)} onClick={()=>void lifecycle(c,"delete")}>Delete</button></div></div><div className="mcf-metrics"><div className="mcf-metric"><span>Spend</span><b>{money(m.spend,c.currency||currency)}</b></div><div className="mcf-metric"><span>{label}</span><b>{Number(m.results||0).toLocaleString()}</b></div><div className="mcf-metric"><span>CTR</span><b>{Number(m.ctr||0).toFixed(2)}%</b></div><div className="mcf-metric"><span>ROAS</span><b>{Number(m.roas||0).toFixed(2)}×</b></div></div></article>})}</div></section>})}{!loading&&!fallbackAccounts.length&&<div className="mcf-status">No campaigns for the selected month.</div>}</div>}
 {showFull&&<div className="mcf-full"><MediaIntelligenceWorkspaceV2/></div>}
 </div>
}
