"use client";
import {useEffect,useState} from "react";

const CUTOFF="2026-07-25",iso=(d:Date)=>d.toISOString().slice(0,10);
async function read(r:Response){const t=await r.text();try{return t?JSON.parse(t):{}}catch{return {error:t||`Request failed (${r.status})`}}}
export function MetaAccountConnectPanel(){
 const [data,setData]=useState<any>({accountGroups:[]}),[busy,setBusy]=useState(""),[msg,setMsg]=useState("");
 async function load(){const to=iso(new Date()),r=await fetch(`/api/media-control-v2?from=${CUTOFF}&to=${to}`,{cache:"no-store"}),d=await read(r);if(r.ok)setData(d)}
 useEffect(()=>{load();const q=new URLSearchParams(location.search),oauth=q.get("oauth"),connectionId=q.get("connectionId");if(oauth==="success"&&connectionId){setMsg("Meta connected. Discovering campaigns with delivery since 25 Jul 2026…");syncAll(connectionId,true)}else if(oauth==="error")setMsg(q.get("message")||"Meta connection failed");history.replaceState({},"",location.pathname)},[]);
 useEffect(()=>{const accounts=(data.accountGroups||[]).filter((a:any)=>a.platform==="META"&&a.status!=="DISABLED"&&(a.status==="CONNECTED"||a.status==="ERROR"));if(!accounts.length)return;const key=`vivit-meta-live-refresh:${accounts.map((a:any)=>`${a.id}:${a.lastSyncAt||"never"}`).join("|")}`;if(sessionStorage.getItem(key))return;sessionStorage.setItem(key,"1");setMsg("Refreshing connected Meta accounts live…");(async()=>{for(const a of accounts)await syncAll(a.id,true)})()},[data.accountGroups]);
 function connect(a:any){const p=new URLSearchParams({clientId:a.clientId,adAccountId:String(a.adAccountId||"").replace(/^act_/i,""),accountName:a.accountName||"Meta Ad Account"});location.assign(`/api/ad-oauth/meta/start?${p}`)}
 async function syncAll(id:string,auto=false){setBusy(id);if(!auto)setMsg("");const r=await fetch("/api/media-discover",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({connectionId:id})}),d=await read(r);if(r.ok){const detail=Array.isArray(d.failures)&&d.failures.length?` · ${d.failures.slice(0,2).map((x:any)=>x.error).join(" | ")}`:"";setMsg(`Live Meta refresh complete · ${d.discovered||0} campaigns discovered · ${d.synced||0} updated${d.hiddenBeforeCutoff?` · ${d.hiddenBeforeCutoff} older/inactive hidden`:""}${d.failed?` · ${d.failed} failed${detail}`:""}.`)}else setMsg(d.error||"Meta refresh failed");setBusy("");await load()}
 const accounts=(data.accountGroups||[]).filter((a:any)=>a.platform==="META"&&a.status!=="DISABLED");
 return <div className="card" style={{padding:14,border:"1px solid rgba(59,130,246,.25)"}}>
  <div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"start",flexWrap:"wrap"}}><div><div style={{fontWeight:900,fontSize:16}}>Meta Accounts — Live Sync</div><div className="page-subtitle" style={{margin:0}}>Connected accounts refresh automatically when you open Media Control. Connect is only needed for first authorization or if Meta expires/revokes the token.</div></div><span className="badge badge-blue">{accounts.length} accounts</span></div>
  {msg&&<div style={{marginTop:12,padding:"10px 12px",borderRadius:10,background:"rgba(59,130,246,.08)",fontSize:12,fontWeight:700,overflowWrap:"anywhere"}}>{msg}</div>}
  <div style={{display:"grid",gap:9,marginTop:12}}>{accounts.map((a:any)=>{const authorized=a.status==="CONNECTED"||a.status==="ERROR";return <div key={a.id} style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,padding:12,border:"1px solid var(--card-border)",borderRadius:12,flexWrap:"wrap"}}><div><b>{a.accountName||a.adAccountId}</b><div className="page-subtitle" style={{margin:0}}>{a.clientName} · {a.adAccountId} · {a.campaignCount||0} active campaigns · {authorized?"Auto-sync enabled":"Authorization required"}</div>{a.syncError&&<div style={{fontSize:11,color:"var(--danger)",marginTop:3,overflowWrap:"anywhere"}}>{a.syncError}</div>}</div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button className={authorized?"btn btn-secondary btn-sm":"btn btn-primary btn-sm"} onClick={()=>connect(a)} disabled={!!busy}>{authorized?"Re-authorize only if needed":"Connect Meta once"}</button><button className="btn btn-primary btn-sm" onClick={()=>syncAll(a.id)} disabled={!authorized||busy===a.id}>{busy===a.id?"Refreshing…":"Refresh now ↻"}</button></div></div>})}{!accounts.length&&<div className="page-subtitle">No Meta ad accounts are registered yet.</div>}</div>
 </div>
}
