export const dynamic="force-dynamic";
import {auth} from "@/lib/auth";
import {redirect} from "next/navigation";
import {db,salesLeads,financeRecords,workspaces,sql} from "@/lib/db";
import {eq,notInArray,and} from "drizzle-orm";
import {Role} from "@/lib/types";

export default async function ForecastPage(){const session=await auth();if(!session?.user)redirect("/login");const workspaceId=String(session.user.workspaceId||"");if(!workspaceId)redirect("/login");if(![Role.SUPER_ADMIN,Role.ACCOUNTANT].includes(session.user.role))redirect("/dashboard");const now=new Date(),y=now.getFullYear(),m=now.getMonth(),activeLeads=sql`${salesLeads.id} in (select id from sales_leads where workspace_id=${workspaceId} and archived_at is null)`,[leads,historical,ws]=await Promise.all([db.select().from(salesLeads).where(and(eq(salesLeads.workspaceId,workspaceId),notInArray(salesLeads.stage,["WON","LOST"]),activeLeads)),db.select().from(financeRecords).where(and(eq(financeRecords.workspaceId,workspaceId),eq(financeRecords.year,y))).orderBy(financeRecords.month),db.select({currency:workspaces.currency}).from(workspaces).where(eq(workspaces.id,workspaceId)).then(r=>r[0])]);const currency=ws?.currency||"EGP",money=(n:number)=>{try{return new Intl.NumberFormat("en-EG",{style:"currency",currency,maximumFractionDigits:0}).format(Number(n||0))}catch{return `${Number(n||0).toLocaleString()} ${currency}`}},weights:Record<string,number>={NEW_LEAD:.05,CONTACTED:.15,QUALIFIED:.4,PROPOSAL_SENT:.6,NEGOTIATION:.8},weighted=leads.reduce((s,l)=>s+Number(l.estimatedValue||0)*(Number(l.probability||0)>0?Number(l.probability)/100:(weights[l.stage]||.1)),0),rawPipeline=leads.reduce((s,l)=>s+Number(l.estimatedValue||0),0),monthly=Array.from({length:m+1},(_,i)=>historical.filter(r=>r.month===i+1).reduce((s,r)=>s+Number(r.totalRevenue||0),0)),recent=monthly.filter(x=>x>0).slice(-3),base=recent.length?recent.reduce((a,b)=>a+b,0)/recent.length:0,names=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],forecast=Array.from({length:6},(_,i)=>{const idx=m+1+i,month=idx%12,year=y+Math.floor(idx/12),pipelineShare=weighted/6,predicted=Math.round(base*.82+pipelineShare*.18);return {month:names[month],year,predicted,base:Math.round(base),pipeline:Math.round(pipelineShare)}}),totalForecast=forecast.reduce((s,x)=>s+x.predicted,0),max=Math.max(...forecast.map(x=>x.predicted),1),hasEvidence=historical.length>0||leads.length>0;
 return <div style={{display:"flex",flexDirection:"column",gap:18}}><div><h1 className="page-title">Revenue Forecast</h1><p className="page-subtitle">Model estimate — 82% recent invoiced run-rate + 18% weighted active sales pipeline. This is planning guidance, not guaranteed revenue.</p></div>{!hasEvidence&&<div className="card"><div className="card-body" style={{textAlign:"center",color:"var(--text-muted)"}}>No finance or active pipeline history is available yet, so the model currently has no evidence to forecast from.</div></div>}<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:12}}>{[{l:"6-Month Model Estimate",v:money(totalForecast)},{l:"Active Pipeline Value",v:money(rawPipeline)},{l:"Weighted Pipeline",v:money(weighted)},{l:"Recent Monthly Base",v:money(base)}].map(x=><div className="card" key={x.l}><div className="card-body"><p style={{fontSize:11,color:"var(--text-muted)",fontWeight:800,textTransform:"uppercase"}}>{x.l}</p><b style={{fontSize:23,display:"block",marginTop:6}}>{x.v}</b></div></div>)}</div><section className="card"><div className="card-header"><p className="card-title">Next 6 Months — Estimated</p></div><div className="card-body"><div style={{height:240,display:"flex",alignItems:"end",gap:12}}>{forecast.map(x=><div key={x.month+x.year} style={{flex:1,display:"flex",flexDirection:"column",alignItems:"center",gap:6,height:"100%",justifyContent:"end"}}><span style={{fontSize:10.5,fontWeight:800}}>{money(x.predicted)}</span><div style={{width:"100%",height:`${Math.max(6,x.predicted/max*78)}%`,background:"linear-gradient(180deg,#7C3AED,#244D87)",borderRadius:"10px 10px 3px 3px"}}/><b style={{fontSize:11}}>{x.month}</b><span style={{fontSize:9.5,color:"var(--text-muted)"}}>{x.year}</span></div>)}</div></div></section><section className="card"><div className="card-header"><p className="card-title">Model Inputs</p></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Month</th><th>Recent Revenue Base</th><th>Pipeline Component</th><th>Estimated Revenue</th></tr></thead><tbody>{forecast.map(x=><tr key={x.month+x.year}><td><b>{x.month} {x.year}</b></td><td>{money(x.base)}</td><td>{money(x.pipeline)}</td><td><b>{money(x.predicted)}</b></td></tr>)}</tbody></table></div></section></div>}
