export const dynamic="force-dynamic";
import { auth } from "@/lib/auth";
import { redirect } from "next/navigation";
import { db,salesLeads,financeRecords } from "@/lib/db";
import { eq,notInArray } from "drizzle-orm";
import { Role } from "@/lib/types";
const money=(n:number)=>`EGP ${new Intl.NumberFormat("en-US",{maximumFractionDigits:0}).format(Number(n||0))}`;
export default async function ForecastPage(){const session=await auth();if(!session?.user)redirect("/login");if(![Role.SUPER_ADMIN,Role.ACCOUNTANT].includes((session.user as any).role))redirect("/dashboard");const now=new Date(),y=now.getFullYear(),m=now.getMonth(),[leads,historical]=await Promise.all([db.select().from(salesLeads).where(notInArray(salesLeads.stage,["WON","LOST"])),db.select().from(financeRecords).where(eq(financeRecords.year,y)).orderBy(financeRecords.month)]);const weights:Record<string,number>={NEW_LEAD:.05,CONTACTED:.15,QUALIFIED:.4,PROPOSAL_SENT:.6,NEGOTIATION:.8};const weighted=leads.reduce((s,l)=>s+Number(l.estimatedValue||0)*(Number(l.probability||0)>0?Number(l.probability)/100:(weights[l.stage]||.1)),0),rawPipeline=leads.reduce((s,l)=>s+Number(l.estimatedValue||0),0);const monthly=Array.from({length:m+1},(_,i)=>historical.filter(r=>r.month===i+1).reduce((s,r)=>s+Number(r.totalRevenue||0),0)),recent=monthly.filter(x=>x>0).slice(-3),base=recent.length?recent.reduce((a,b)=>a+b,0)/recent.length:0;const names=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],forecast=Array.from({length:6},(_,i)=>{const idx=m+1+i,month=idx%12,year=y+Math.floor(idx/12),pipelineShare=weighted/6,predicted=Math.round(base*.82+pipelineShare*.18);return {month:names[month],year,predicted,base:Math.round(base),pipeline:Math.round(pipelineShare)}}),totalForecast=forecast.reduce((s,x)=>s+x.predicted,0),max=Math.max(...forecast.map(x=>x.predicted),1);
 return <div style={{display:"flex",flexDirection:"column",gap:18}}><div><h1 className="page-title">Revenue Forecast</h1><p className="page-subtitle">Historical run-rate blended with weighted sales pipeline · currency shown as EGP</p></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:12}}>{[{l:"6-Month Forecast",v:money(totalForecast)},{l:"Pipeline Value",v:money(rawPipeline)},{l:"Weighted Pipeline",v:money(weighted)},{l:"Monthly Base",v:money(base)}].map(x=><div className="card" key={x.l}><div className="card-body"><p style={{fontSize:11,color:"var(--text-muted)",fontWeight:800,textTransform:"uppercase"}}>{x.l}</p><b style={{fontSize:23,display:"block",marginTop:6}}>{x.v}</b></div></div>)}</div><section className="card"><div className="card-header"><p className="card-title">Next 6 Months</p></div><div className="card-body"><div style={{height:240,display:"flex",alignItems:"end",gap:12}}>{forecast.map(x=><div key={x.month+x.year} style={{flex:1,display:"flex",flexDirection:"column",alignItems:"center",gap:6,height:"100%",justifyContent:"end"}}><span style={{fontSize:10.5,fontWeight:800,color:"var(--text-secondary)"}}>{money(x.predicted)}</span><div style={{width:"100%",height:`${Math.max(6,x.predicted/max*78)}%`,background:"linear-gradient(180deg,#7C3AED,#244D87)",borderRadius:"10px 10px 3px 3px",boxShadow:"0 8px 22px rgba(36,77,135,.18)"}}/><b style={{fontSize:11}}>{x.month}</b><span style={{fontSize:9.5,color:"var(--text-muted)"}}>{x.year}</span></div>)}</div></div></section><section className="card"><div className="card-header"><p className="card-title">Forecast Breakdown</p></div><div className="card-body-flush"><table className="data-table"><thead><tr><th>Month</th><th>Historical Base</th><th>Pipeline Component</th><th>Forecast</th></tr></thead><tbody>{forecast.map(x=><tr key={x.month+x.year}><td><b>{x.month} {x.year}</b></td><td>{money(x.base)}</td><td>{money(x.pipeline)}</td><td><b>{money(x.predicted)}</b></td></tr>)}</tbody></table></div></section></div>}
