export const dynamic="force-dynamic";
import {auth} from "@/lib/auth";
import {redirect} from "next/navigation";
import {db,sql} from "@/lib/db";
import Link from "next/link";
import Image from "next/image";
import {ClientLifecycleButtons} from "@/components/marketing/client-lifecycle-buttons";

type SessionUser={workspaceId?:string|null;role?:string|null;id?:string|null};
type ClientRow={id:string;company_name:string;industry?:string|null;health_score?:number|string|null;logo?:string|null;website?:string|null;account_manager_id?:string|null;media_buyer_id?:string|null};
type TaskRow={client_id:string;status:string;revision_count?:number|string|null;overdue:boolean};
type MediaRow={client_id:string;spend?:number|string|null;results?:number|string|null;atc?:number|string|null;purchases?:number|string|null};
type ClientWorld=ClientRow&{active:number;overdue:number;review:number;revisions:number;spend:number;results:number;atc:number;purchases:number;signals:number};
const n=(v:unknown)=>Number(v||0),money=(v:unknown)=>`${Math.round(n(v)).toLocaleString("en-EG")} EGP`;
export default async function ClientUniverse(){
 const s=await auth();if(!s?.user)redirect("/login");const user=s.user as SessionUser,workspaceId=String(user.workspaceId||"");if(!workspaceId)redirect("/login");const role=String(user.role||""),uid=String(user.id||"");if(!["SUPER_ADMIN","ACCOUNT_MANAGER","MEDIA_BUYER"].includes(role))redirect("/dashboard/today");
 const scope=role==="ACCOUNT_MANAGER"?sql`and c.account_manager_id=${uid}`:role==="MEDIA_BUYER"?sql`and c.media_buyer_id=${uid}`:sql``;
 const clients=Array.from(await db.execute(sql`select c.id,c.company_name,c.industry,c.health_score,c.logo,c.website,c.account_manager_id,c.media_buyer_id from clients c where c.workspace_id=${workspaceId} and c.is_active=true ${scope} order by c.company_name`)) as ClientRow[];const ids=clients.map(x=>String(x.id));let tasks:TaskRow[]=[],media:MediaRow[]=[];
 if(ids.length){tasks=Array.from(await db.execute(sql`select client_id,status,revision_count,(deadline < now()) overdue from creative_tasks where workspace_id=${workspaceId} and archived_at is null and client_id in (${sql.join(ids.map(id=>sql`${id}`),sql`,`)}) and status not in ('COMPLETED','REJECTED')`)) as TaskRow[];media=Array.from(await db.execute(sql`select a.client_id,coalesce(sum(p.spend),0) spend,coalesce(sum(p.results),0) results,coalesce(sum(p.add_to_cart),0) atc,coalesce(sum(p.purchases),0) purchases from ad_campaigns a left join ad_performance_daily p on p.campaign_id=a.id and p.date>=date_trunc('month',now()) and p.breakdown_type='TOTAL' and p.ad_set_id is null and p.ad_id is null where a.client_id in (${sql.join(ids.map(id=>sql`${id}`),sql`,`)}) group by a.client_id`)) as MediaRow[];}
 const worlds:ClientWorld[]=clients.map(c=>{const ct=tasks.filter(t=>t.client_id===c.id),cm=media.find(m=>m.client_id===c.id),overdue=ct.filter(t=>t.overdue).length,review=ct.filter(t=>["REVIEW","REVISION","APPROVED"].includes(t.status)).length,revisions=ct.filter(t=>n(t.revision_count)>=2).length,spend=n(cm?.spend),results=n(cm?.results),atc=n(cm?.atc),purchases=n(cm?.purchases),signals=overdue+(spend>0&&results===0?1:0)+revisions;return{...c,active:ct.length,overdue,review,revisions,spend,results,atc,purchases,signals}}).sort((a,b)=>b.signals-a.signals||a.company_name.localeCompare(b.company_name));
 const canManage=role==="SUPER_ADMIN"||role==="ACCOUNT_MANAGER",canDelete=role==="SUPER_ADMIN";
 return <div className="vx-world vx-client-universe"><style>{`
 .vx-client-universe{display:grid;gap:18px;min-width:0;color:#172033;--card-bg:#fff;--card-border:#e4e8f0;--bg-secondary:#f6f8fc;--text-primary:#172033;--text-muted:#6f7b92;--text-secondary:#52617b}.vx-client-universe .vx-world-hero,.vx-client-universe .card{background:#fff!important;color:#172033!important;border-color:#e4e8f0!important;box-shadow:0 12px 36px rgba(29,43,72,.07)!important}.vx-client-universe .vx-world-hero{border-radius:20px!important}.vx-client-universe .page-title,.vx-client-universe h3,.vx-client-universe b{color:#172033}.vx-client-universe .page-subtitle,.vx-client-universe small{color:#738098}.vcu-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.vcu-card{overflow:hidden;display:grid;min-height:300px;border-radius:20px}.vcu-visual{height:116px;position:relative;background:linear-gradient(135deg,#f8f9fc,#eef2f8);display:grid;place-items:center;border-bottom:1px solid #e8ecf2}.vcu-logo{width:76px;height:76px;border-radius:20px;display:grid;place-items:center;background:#fff;overflow:hidden;font-size:20px;font-weight:900;box-shadow:0 10px 28px rgba(15,23,42,.09);border:1px solid rgba(15,23,42,.06);position:relative}.vcu-body{padding:15px;display:grid;gap:12px}.vcu-meta{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px}.vcu-meta>div{background:#f6f8fc;border:1px solid #edf0f5;border-radius:11px;padding:9px}.vcu-meta small{display:block;font-size:10px}.vcu-meta b{display:block;margin-top:3px;font-size:13px}.vcu-actions{display:flex;gap:8px;align-items:center;justify-content:space-between;flex-wrap:wrap;border-top:1px solid #edf0f5;padding-top:11px}.vcu-actions>a{flex:1;min-width:130px;text-align:center}.vx-apps{right:126px!important;bottom:calc(88px + env(safe-area-inset-bottom))!important}.vivit-lang-switch{right:14px!important;bottom:calc(88px + env(safe-area-inset-bottom))!important}
 @media(max-width:900px){.vcu-grid{grid-template-columns:1fr}.vx-client-universe{padding-bottom:105px}.vx-client-universe .vx-world-hero{padding:14px!important}.vx-client-universe .page-title{font-size:26px!important;line-height:1.05!important}.vcu-card{border-radius:17px}.vcu-meta{grid-template-columns:repeat(2,minmax(0,1fr))}.vcu-actions{display:grid;grid-template-columns:1fr auto}.vcu-actions>a{width:100%}}
 @media(max-width:560px){.vx-client-universe{gap:12px}.vcu-body{padding:13px}.vcu-visual{height:100px}.vcu-logo{width:68px;height:68px}.vx-apps{right:128px!important}.vivit-lang-switch{right:12px!important}}
 `}</style>
 <header className="vx-world-hero"><div><span className="eyebrow">CLIENTS</span><h1 className="page-title">Your client workspaces.</h1><p className="page-subtitle">Open any account to see campaigns, creative, tasks and contacts. Lifecycle actions are available on the card.</p></div><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap",justifyContent:"flex-end"}}><Link href="/dashboard/clients/new" className="btn btn-primary" style={{textDecoration:"none",pointerEvents:"auto",position:"relative",zIndex:2}}>+ Add Account</Link><div className="vx-live-chip"><i/>{worlds.length} ACTIVE ACCOUNTS</div></div></header>
 <div className="vx-focus-strip"><span className="vx-focus-pill">{worlds.filter(x=>x.signals>0).length} need focus</span><span className="vx-focus-pill">{worlds.reduce((a,x)=>a+x.overdue,0)} overdue</span><span className="vx-focus-pill">{worlds.reduce((a,x)=>a+x.review,0)} in review</span><span className="vx-focus-pill">{money(worlds.reduce((a,x)=>a+x.spend,0))} media MTD</span></div>
 <section className="vcu-grid">{worlds.map(c=><article className="card vcu-card" key={c.id}><div className="vcu-visual"><div className="vcu-logo">{c.logo?<Image src={c.logo} alt={`${c.company_name} logo`} fill unoptimized sizes="76px" style={{objectFit:"contain",padding:8}}/>:c.company_name.slice(0,2).toUpperCase()}</div><span className={`badge ${c.signals>=3?"badge-red":c.signals?"badge-amber":"badge-green"}`} style={{position:"absolute",right:12,top:12}}>{c.signals?`${c.signals} signals`:"clear"}</span></div><div className="vcu-body"><div><h3 style={{margin:0,fontSize:18}}>{c.company_name}</h3><small>{c.industry||"Marketing account"}</small></div><div className="vcu-meta"><div><small>Active work</small><b>{c.active}</b></div><div><small>In review</small><b>{c.review}</b></div><div><small>Media MTD</small><b>{money(c.spend)}</b></div><div><small>Purchases</small><b>{c.purchases}</b></div></div><div className="vcu-actions"><Link href={`/dashboard/clients/${c.id}`} className="btn btn-secondary" style={{textDecoration:"none"}}>Open workspace →</Link>{canManage&&<ClientLifecycleButtons id={c.id} name={c.company_name} canDelete={canDelete}/>}</div></div></article>)}</section>
 {!worlds.length&&<div className="card" style={{padding:30,textAlign:"center"}}>No active client workspace is currently inside your scope.</div>}
 </div>
}
