export const dynamic="force-dynamic";
import {auth} from "@/lib/auth";
import {redirect} from "next/navigation";
import {db,sql} from "@/lib/db";
import Link from "next/link";
const W="default",n=(v:any)=>Number(v||0),money=(v:any)=>`${Math.round(n(v)).toLocaleString("en-EG")} EGP`;
export default async function ClientUniverse(){
 const s=await auth();if(!s?.user)redirect("/login");const role=String((s.user as any).role||""),uid=String((s.user as any).id||"");if(!["SUPER_ADMIN","ACCOUNT_MANAGER"].includes(role))redirect("/dashboard/today");
 const scope=role==="ACCOUNT_MANAGER"?sql`and c.account_manager_id=${uid}`:sql``;
 const clients:any[]=Array.from(await db.execute(sql`select c.id,c.company_name,c.industry,c.health_score,c.logo,c.account_manager_id,c.media_buyer_id from clients c where c.workspace_id=${W} and c.is_active=true ${scope} order by c.company_name`));
 const ids=clients.map(x=>String(x.id));let tasks:any[]=[],media:any[]=[],billing:any[]=[];
 if(ids.length){tasks=Array.from(await db.execute(sql`select client_id,status,deadline,revision_count from creative_tasks where workspace_id=${W} and archived_at is null and client_id in (${sql.join(ids.map(id=>sql`${id}`),sql`,`)}) and status not in ('COMPLETED','REJECTED')`));media=Array.from(await db.execute(sql`select client_id,coalesce(sum(p.spend),0) spend,coalesce(sum(p.results),0) results from ad_campaigns a left join ad_performance_daily p on p.campaign_id=a.id and p.date>=date_trunc('month',now()) and p.breakdown_type='TOTAL' and p.ad_set_id is null and p.ad_id is null where a.archived_at is null and a.client_id in (${sql.join(ids.map(id=>sql`${id}`),sql`,`)}) group by client_id`));billing=Array.from(await db.execute(sql`select client_id,outstanding from client_payment_profiles where client_id in (${sql.join(ids.map(id=>sql`${id}`),sql`,`)})`));}
 const now=Date.now(),worlds=clients.map(c=>{const ct=tasks.filter(t=>t.client_id===c.id),cm=media.find(m=>m.client_id===c.id),cb=billing.find(b=>b.client_id===c.id),overdue=ct.filter(t=>new Date(t.deadline).getTime()<now).length,review=ct.filter(t=>["REVIEW","REVISION","APPROVED"].includes(String(t.status))).length,revisions=ct.filter(t=>n(t.revision_count)>=2).length,spend=n(cm?.spend),results=n(cm?.results),outstanding=n(cb?.outstanding),signals=overdue+(spend>0&&results===0?1:0)+revisions+(outstanding>0?1:0);return{...c,active:ct.length,overdue,review,revisions,spend,results,outstanding,signals}}).sort((a,b)=>b.signals-a.signals||a.company_name.localeCompare(b.company_name));
 return <div className="vx-world vx-client-universe" style={{display:"grid",gap:18}}><header className="vx-world-hero"><div><span className="eyebrow">CLIENT UNIVERSE</span><h1 className="page-title">Every client is a living workspace.</h1><p className="page-subtitle">Delivery, campaign pressure, approvals and commercial exposure visible in one account-manager universe.</p></div><div className="vx-live-chip"><i/>{worlds.length} ACTIVE WORLDS</div></header><div className="vx-focus-strip"><span className="vx-focus-pill">{worlds.filter(x=>x.signals>0).length} need focus</span><span className="vx-focus-pill">{worlds.reduce((a,x)=>a+x.overdue,0)} overdue</span><span className="vx-focus-pill">{worlds.reduce((a,x)=>a+x.review,0)} in review</span><span className="vx-focus-pill">{money(worlds.reduce((a,x)=>a+x.outstanding,0))} outstanding</span></div><section className="vx-universe-grid">{worlds.map(c=><article className="card" key={c.id} style={{padding:18,display:"grid",gap:14}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center"}}><div style={{display:"flex",gap:10,alignItems:"center"}}><div style={{width:42,height:42,borderRadius:14,display:"grid",placeItems:"center",background:"var(--vx-accent-soft)",overflow:"hidden",fontWeight:900}}>{c.logo?<img src={c.logo} alt="" style={{width:"100%",height:"100%",objectFit:"cover"}}/>:c.company_name.slice(0,2).toUpperCase()}</div><div><h3 style={{margin:0}}>{c.company_name}</h3><small className="text-muted">{c.industry||"Marketing account"}</small></div></div><span className={`badge ${c.signals>=3?"badge-red":c.signals?"badge-amber":"badge-green"}`}>{c.signals?`${c.signals} signals`:"clear"}</span></div><div className="grid grid-2" style={{gap:8}}><div><small>Active work</small><b style={{display:"block",fontSize:20}}>{c.active}</b></div><div><small>Review</small><b style={{display:"block",fontSize:20}}>{c.review}</b></div><div><small>Media MTD</small><b style={{display:"block"}}>{money(c.spend)}</b></div><div><small>Outstanding</small><b style={{display:"block"}}>{money(c.outstanding)}</b></div></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><Link href="/dashboard/today" className="btn btn-secondary btn-sm">Open focus</Link><Link href="/dashboard/media/control-center" className="btn btn-secondary btn-sm">Media</Link></div></article>)}</section>{!worlds.length&&<div className="card" style={{padding:30,textAlign:"center"}}>No active client workspace is currently inside your scope.</div>}</div>
}
