export const dynamic="force-dynamic";
import {auth} from "@/lib/auth";
import {redirect} from "next/navigation";
import {db,sql} from "@/lib/db";
import Link from "next/link";
const W="default",n=(v:any)=>Number(v||0),money=(v:any)=>`${Math.round(n(v)).toLocaleString("en-EG")} EGP`;
export default async function ExecutivePage(){
 const s=await auth();if(!s?.user)redirect("/login");if(String((s.user as any).role)!=="SUPER_ADMIN")redirect("/dashboard");
 const clients:any[]=Array.from(await db.execute(sql`select id,company_name from clients where workspace_id=${W} and is_active=true order by company_name`));
 const ids=clients.map(x=>String(x.id));
 const tasks:any[]=Array.from(await db.execute(sql`select t.id,t.title,t.status,t.deadline,t.revision_count,c.company_name from creative_tasks t join clients c on c.id=t.client_id where t.workspace_id=${W} and c.workspace_id=${W} and c.is_active=true and t.archived_at is null and t.status not in ('COMPLETED','REJECTED') order by t.deadline asc limit 200`));
 let media:any[]=[],billing:any[]=[];
 if(ids.length){
  media=Array.from(await db.execute(sql`select c.company_name,a.id,a.name,a.reported_result_label,coalesce(sum(p.spend),0) spend,coalesce(sum(p.results),0) results,coalesce(sum(p.add_to_cart),0) atc,coalesce(sum(p.purchases),0) purchases,coalesce(sum(p.revenue),0) revenue from ad_campaigns a join clients c on c.id=a.client_id left join ad_performance_daily p on p.campaign_id=a.id and p.date>=date_trunc('month',now()) and p.breakdown_type='TOTAL' and p.ad_set_id is null and p.ad_id is null where a.archived_at is null and a.client_id in (${sql.join(ids.map(id=>sql`${id}`),sql`,`)}) group by c.company_name,a.id,a.name,a.reported_result_label order by spend desc`));
  billing=Array.from(await db.execute(sql`select c.company_name,p.outstanding,p.status from client_payment_profiles p join clients c on c.id=p.client_id where c.workspace_id=${W} order by p.outstanding desc`));
 }
 const overdue=tasks.filter(t=>new Date(t.deadline).getTime()<Date.now()),review=tasks.filter(t=>["REVIEW","REVISION","APPROVED"].includes(String(t.status))),spend=media.reduce((a,x)=>a+n(x.spend),0),revenue=media.reduce((a,x)=>a+n(x.revenue),0),outstanding=billing.reduce((a,x)=>a+n(x.outstanding),0),zero=media.filter(x=>n(x.spend)>0&&n(x.results)===0),highRev=tasks.filter(x=>n(x.revision_count)>=2);
 const riskByClient=clients.map(c=>{const name=c.company_name,od=overdue.filter(x=>x.company_name===name).length,z=zero.filter(x=>x.company_name===name).length,rv=highRev.filter(x=>x.company_name===name).length,b=n(billing.find(x=>x.company_name===name)?.outstanding),score=Math.min(100,od*18+z*22+rv*12+(b>0?20:0));return{name,score,od,z,rv,b}}).sort((a,b)=>b.score-a.score);
 const decisions=[...overdue.slice(0,4).map(x=>({title:"Recover overdue delivery",body:`${x.company_name} · ${x.title}`,href:`/dashboard/creative/${x.id}`,level:"critical"})),...zero.slice(0,4).map(x=>({title:"Diagnose campaign spend without result",body:`${x.company_name} · ${x.name} · ${money(x.spend)}`,href:"/dashboard/media/control-center",level:"warning"})),...(outstanding>0?[{title:"Prioritize collections",body:`${money(outstanding)} outstanding`,href:"/dashboard/clients/accounts-payment",level:"warning"}]:[])].slice(0,7);
 const health=Math.max(0,100-Math.min(100,overdue.length*5+zero.length*8+riskByClient.filter(x=>x.score>=60).length*7));
 return <div className="vx-world vx-war-room" style={{display:"grid",gap:18}}>
  <header className="vx-world-hero"><div><span className="eyebrow">EXECUTIVE WAR ROOM</span><h1 className="page-title">See the business. Make the next move.</h1><p className="page-subtitle">A live decision layer across clients, creative, media and collections — without dashboard noise.</p></div><div className="vx-live-chip"><i/>HEALTH {health}/100</div></header>
  <div className="vx-focus-strip"><span className="vx-focus-pill">{riskByClient.filter(x=>x.score>=40).length} clients need focus</span><span className="vx-focus-pill">{overdue.length} overdue</span><span className="vx-focus-pill">{zero.length} media anomalies</span><span className="vx-focus-pill">{review.length} review pressure</span></div>
  <div className="grid grid-4"><div className="card"><small>Active clients</small><h2>{clients.length}</h2><p>{riskByClient.filter(x=>x.score>=40).length} need attention</p></div><div className="card"><small>Media spend MTD</small><h2>{money(spend)}</h2><p>{zero.length} campaigns with zero result</p></div><div className="card"><small>Tracked revenue</small><h2>{money(revenue)}</h2><p>Across synced campaigns</p></div><div className="card"><small>Outstanding</small><h2>{money(outstanding)}</h2><p>Collection exposure</p></div></div>
  <div className="grid grid-2"><section className="card"><h2>Decision Engine</h2><p className="text-muted">What requires executive attention now, ordered by business risk.</p><div className="vx-decision-stack" style={{marginTop:14}}>{decisions.length?decisions.map((x,i)=><Link className="vx-decision" href={x.href} key={`${x.title}-${i}`} style={{textDecoration:"none",color:"inherit"}}><span className="vx-decision-index">{String(i+1).padStart(2,"0")}</span><span><b>{x.title}</b><small style={{display:"block",color:"var(--text-muted)",marginTop:2}}>{x.body}</small></span><span className={`badge ${x.level==="critical"?"badge-red":"badge-amber"}`}>{x.level}</span></Link>):<div className="empty good">No critical executive decision is waiting.</div>}</div></section>
   <section className="card"><h2>Client Sonar</h2><p className="text-muted">Pressure signals across delivery, media, revisions and cash.</p><div style={{display:"grid",gap:10,marginTop:14}}>{riskByClient.slice(0,10).map(x=><div key={x.name} style={{display:"grid",gridTemplateColumns:"1fr auto",gap:10,paddingBottom:10,borderBottom:"1px solid var(--card-border)"}}><div><b>{x.name}</b><small style={{display:"block",color:"var(--text-muted)"}}>{x.od} overdue · {x.z} media · {x.rv} revisions · {money(x.b)} due</small></div><span className={`badge ${x.score>=60?"badge-red":x.score>=30?"badge-amber":"badge-green"}`}>{x.score}/100</span></div>)}</div></section></div>
  <div className="grid grid-3"><Link href="/dashboard/today" className="card" style={{textDecoration:"none",color:"inherit"}}><span className="eyebrow">PULSE</span><h3 style={{marginTop:10}}>What changed & what matters →</h3><p className="text-muted">Role-aware operating focus.</p></Link><Link href="/dashboard/media/control-center" className="card" style={{textDecoration:"none",color:"inherit"}}><span className="eyebrow">COCKPIT</span><h3 style={{marginTop:10}}>Campaign intelligence →</h3><p className="text-muted">Spend, outcomes and anomalies.</p></Link><Link href="/dashboard/creative/quality" className="card" style={{textDecoration:"none",color:"inherit"}}><span className="eyebrow">CINEMA</span><h3 style={{marginTop:10}}>Creative pressure →</h3><p className="text-muted">Quality, reviews and revision risk.</p></Link></div>
 </div>
}
