"use client";
import {FormEvent,useState} from "react";

type Endpoint="operations"|"engines";
const inputStyle={width:"100%",padding:"11px 12px",borderRadius:12,border:"1px solid #25445d",background:"#0b1622",color:"#eaf6ff",outline:"none"} as const;
const buttonStyle={padding:"11px 14px",border:0,borderRadius:12,background:"#2ea8ff",color:"#04111c",fontWeight:900,cursor:"pointer"} as const;

function FormCard({title,endpoint,defaults,fields}:{title:string;endpoint:Endpoint;defaults:Record<string,unknown>;fields:{name:string;label:string;type?:string;required?:boolean}[]}){
 const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const fd=new FormData(event.currentTarget);const payload:{[k:string]:unknown}={...defaults};for(const field of fields){const value=fd.get(field.name);payload[field.name]=field.type==="number"?Number(value):value}try{const response=await fetch(`/api/vgroup/tech/${endpoint}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await response.json();setMessage(response.ok?"Saved successfully":data?.error?.message||"Action failed");if(response.ok)event.currentTarget.reset()}catch{setMessage("Network error")}finally{setBusy(false)}}
 return <form onSubmit={submit} style={{padding:20,borderRadius:20,border:"1px solid #1b3b53",background:"rgba(8,19,31,.88)",display:"grid",gap:10}}><h3 style={{margin:0,fontSize:18}}>{title}</h3>{fields.map(field=><label key={field.name} style={{display:"grid",gap:5,fontSize:11,color:"#8da8bd",fontWeight:800}}>{field.label}<input name={field.name} type={field.type||"text"} required={field.required} style={inputStyle}/></label>)}<button disabled={busy} style={{...buttonStyle,opacity:busy?0.65:1}}>{busy?"WORKING…":"RUN ACTION"}</button>{message&&<div style={{fontSize:12,color:message==="Saved successfully"?"#74e0a4":"#ff9696"}}>{message}</div>}</form>
}

export default function TechOpsConsole(){
 const cards=[
  {title:"Log Timesheet",endpoint:"operations" as Endpoint,defaults:{operation:"timesheet"},fields:[{name:"projectId",label:"Project ID",required:true},{name:"workDate",label:"Work date",type:"date",required:true},{name:"hours",label:"Hours",type:"number",required:true},{name:"hourlyCost",label:"Hourly cost",type:"number"},{name:"description",label:"Description"}]},
  {title:"Allocate Capacity",endpoint:"operations" as Endpoint,defaults:{operation:"capacity"},fields:[{name:"userId",label:"User ID",required:true},{name:"projectId",label:"Project ID",required:true},{name:"periodStart",label:"Start",type:"date",required:true},{name:"periodEnd",label:"End",type:"date",required:true},{name:"allocationPercent",label:"Allocation %",type:"number",required:true},{name:"capacityHours",label:"Capacity hours",type:"number"},{name:"allocatedHours",label:"Allocated hours",type:"number"}]},
  {title:"Open Issue / Bug",endpoint:"operations" as Endpoint,defaults:{operation:"issue"},fields:[{name:"projectId",label:"Project ID",required:true},{name:"title",label:"Issue title",required:true},{name:"severity",label:"Severity (low/medium/high/critical)",required:true},{name:"description",label:"Description"}]},
  {title:"Register Environment",endpoint:"engines" as Endpoint,defaults:{action:"environment_create"},fields:[{name:"projectId",label:"Project ID",required:true},{name:"name",label:"Environment name",required:true},{name:"environmentType",label:"Type (development/staging/production/qa)",required:true},{name:"url",label:"URL"},{name:"secretReference",label:"Secret reference only"}]},
  {title:"Support / Retainer Contract",endpoint:"operations" as Endpoint,defaults:{operation:"support_contract"},fields:[{name:"clientId",label:"Client ID",required:true},{name:"name",label:"Contract name",required:true},{name:"startDate",label:"Start date",type:"date",required:true},{name:"monthlyFee",label:"Monthly fee",type:"number"},{name:"includedHours",label:"Included hours",type:"number"},{name:"overageHourRate",label:"Overage rate",type:"number"}]},
  {title:"Create Quotation",endpoint:"operations" as Endpoint,defaults:{operation:"quotation"},fields:[{name:"clientId",label:"Client ID",required:true},{name:"title",label:"Quote title",required:true},{name:"serviceId",label:"Service catalog ID"},{name:"durationDays",label:"Duration days",type:"number"},{name:"validUntil",label:"Valid until",type:"date"}]},
  {title:"Convert Accepted Quote",endpoint:"engines" as Endpoint,defaults:{action:"quote_convert"},fields:[{name:"quoteId",label:"Quotation ID",required:true},{name:"projectManagerId",label:"Project manager ID"}]},
  {title:"Pause SaaS Subscription",endpoint:"engines" as Endpoint,defaults:{action:"subscription_pause"},fields:[{name:"subscriptionId",label:"Subscription ID",required:true},{name:"reason",label:"Reason",required:true},{name:"resumeAt",label:"Auto resume at",type:"datetime-local"}]},
  {title:"Resume SaaS Subscription",endpoint:"engines" as Endpoint,defaults:{action:"subscription_resume"},fields:[{name:"subscriptionId",label:"Subscription ID",required:true}]},
  {title:"SaaS Proration",endpoint:"engines" as Endpoint,defaults:{action:"subscription_proration"},fields:[{name:"subscriptionId",label:"Subscription ID",required:true},{name:"newPlanId",label:"New plan ID",required:true}]},
  {title:"Advance Collection",endpoint:"engines" as Endpoint,defaults:{action:"collection_advance"},fields:[{name:"caseId",label:"Collection case ID",required:true},{name:"status",label:"Optional target status"}]},
  {title:"Refresh Customer Health",endpoint:"engines" as Endpoint,defaults:{action:"health_refresh"},fields:[{name:"clientId",label:"Client ID",required:true},{name:"usageScore",label:"Usage score 0-100",type:"number"},{name:"billingScore",label:"Billing score 0-100",type:"number"},{name:"supportScore",label:"Support score 0-100",type:"number"},{name:"engagementScore",label:"Engagement score 0-100",type:"number"}]},
 ];
 return <section style={{marginTop:30}}><div style={{marginBottom:16}}><div style={{fontSize:11,fontWeight:900,letterSpacing:".14em",color:"#42adf5"}}>QUICK OPERATIONS</div><h2 style={{fontSize:28,margin:"6px 0"}}>Run controlled workflows</h2><p style={{margin:0,color:"#8da8bd"}}>Operational forms call server-authorized Tech APIs. Secret values are never stored here; only secret references are accepted.</p></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(250px,1fr))",gap:14}}>{cards.map(card=><FormCard key={card.title}{...card}/>)}</div></section>
}
