export const dynamic = "force-dynamic";
import { auth } from "@/lib/auth";
import { redirect } from "next/navigation";
import { db, clients, users } from "@/lib/db";
import { eq, and } from "drizzle-orm";
import { Role } from "@/lib/types";
import Link from "next/link";
import {ClientLifecycleButtons} from "@/components/marketing/client-lifecycle-buttons";

const money=(n:number)=>new Intl.NumberFormat("en-EG",{style:"currency",currency:"EGP",maximumFractionDigits:0}).format(Number(n||0));

export default async function ClientsPage({searchParams}:{searchParams?:Promise<Record<string,string|undefined>>}) {
 const session=await auth();if(!session?.user)redirect("/login");
 const role=session.user.role,userId=session.user.id,workspaceId=session.user.workspaceId||"";if(!role||!workspaceId)redirect("/login?reason=workspace_missing");
 if(![Role.SUPER_ADMIN,Role.ACCOUNT_MANAGER,Role.MEDIA_BUYER,Role.ACCOUNTANT].includes(role))redirect("/dashboard");
 const canAdd=[Role.SUPER_ADMIN,Role.ACCOUNT_MANAGER,Role.MEDIA_BUYER,Role.ACCOUNTANT].includes(role),canManage=[Role.SUPER_ADMIN,Role.ACCOUNT_MANAGER,Role.MEDIA_BUYER].includes(role),canDelete=role===Role.SUPER_ADMIN,params=(await searchParams)||{},q=String(params.q||"").trim().toLowerCase();
 const scope=and(eq(clients.workspaceId,workspaceId),eq(clients.isActive,true),role===Role.ACCOUNT_MANAGER?eq(clients.accountManagerId,userId):role===Role.MEDIA_BUYER?eq(clients.mediaBuyerId,userId):undefined);
 const [raw,ams]=await Promise.all([db.select({id:clients.id,companyName:clients.companyName,industry:clients.industry,healthScore:clients.healthScore,churnRisk:clients.churnRisk,monthlyRetainer:clients.monthlyRetainer,lifetimeValue:clients.lifetimeValue,accountManagerId:clients.accountManagerId,contractEnd:clients.contractEnd}).from(clients).where(scope).orderBy(clients.companyName),db.select({id:users.id,name:users.name}).from(users).where(and(eq(users.workspaceId,workspaceId),eq(users.role,"ACCOUNT_MANAGER"),eq(users.isActive,true)))]);
 const am=Object.fromEntries(ams.map(x=>[x.id,x.name])),rows=q?raw.filter(c=>[c.companyName,c.industry,am[c.accountManagerId||""]].some(v=>String(v||"").toLowerCase().includes(q))):raw,totalARR=raw.reduce((s,c)=>s+Number(c.monthlyRetainer||0)*12,0),atRisk=raw.filter(c=>c.churnRisk==="HIGH").length,avg=raw.length?Math.round(raw.reduce((s,c)=>s+Number(c.healthScore||0),0)/raw.length):0;
 return <div className="clp"><style>{`
 .clp{display:grid;gap:16px;min-width:0;max-width:1600px;margin:0 auto;width:100%;padding-bottom:90px}.cl-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;flex-wrap:wrap}.cl-actions{display:flex;gap:8px;flex-wrap:wrap}.cl-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.cl-kpi,.cl-card{background:var(--card-bg);border:1px solid var(--card-border);border-radius:16px;box-shadow:var(--shadow-sm)}.cl-kpi{padding:14px}.cl-kpi span{display:block;font-size:11px;color:var(--text-muted)}.cl-kpi b{display:block;margin-top:5px;font-size:20px;color:var(--text-primary)}.cl-toolbar{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.cl-search{display:flex;gap:8px;flex:1;min-width:240px;max-width:520px}.cl-table{overflow:auto;max-width:100%}.cl-table table{min-width:980px}.cl-mobile{display:none}.cl-card{padding:14px;display:grid;gap:10px;min-width:0}.cl-top{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.cl-name{min-width:0}.cl-name b{display:block;color:var(--text-primary);font-size:15px;overflow-wrap:anywhere}.cl-name small{color:var(--text-muted)}.cl-meta{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.cl-meta div{background:var(--bg-secondary);border-radius:10px;padding:9px;min-width:0}.cl-meta span{display:block;font-size:10px;color:var(--text-muted)}.cl-meta b{display:block;margin-top:3px;font-size:12px;color:var(--text-primary);overflow-wrap:anywhere}.cl-buttons{display:flex;gap:6px;flex-wrap:wrap;align-items:center}@media(max-width:900px){.cl-kpis{grid-template-columns:repeat(2,minmax(0,1fr))}.cl-table{display:none}.cl-mobile{display:grid;gap:10px}.cl-search{width:100%;max-width:none}.cl-head .page-title{font-size:1.6rem!important;line-height:1.1}.cl-actions{width:100%}.cl-actions a{flex:1;text-align:center;min-width:120px}}@media(max-width:560px){.clp{gap:12px}.cl-kpis{gap:8px}.cl-kpi{padding:12px}.cl-kpi b{font-size:17px}.cl-search{display:grid;grid-template-columns:1fr auto}.cl-meta{grid-template-columns:1fr 1fr}.cl-buttons{display:grid;grid-template-columns:1fr auto;width:100%}.cl-buttons>a{width:100%;text-align:center}}
 `}</style>
 <div className="cl-head"><div><h1 className="page-title">Clients</h1><p className="page-subtitle">{raw.length} active clients · portfolio health and revenue</p></div><div className="cl-actions">{canManage&&<Link href="/dashboard/archive" className="btn btn-secondary" style={{textDecoration:"none"}}>Archive</Link>}{canAdd&&<Link href="/dashboard/clients/new" className="btn btn-primary" style={{textDecoration:"none"}}>+ Add Client</Link>}</div></div>
 <div className="cl-kpis"><div className="cl-kpi"><span>Total Clients</span><b>{raw.length}</b></div><div className="cl-kpi"><span>Annual Revenue</span><b>{money(totalARR)}</b></div><div className="cl-kpi"><span>Avg Health</span><b>{avg}%</b></div><div className="cl-kpi"><span>At Risk</span><b>{atRisk}</b></div></div>
 <div className="cl-toolbar"><form className="cl-search" action="/dashboard/clients" method="GET"><input className="form-input" name="q" defaultValue={params.q||""} placeholder="Search client, industry or account manager"/><button className="btn btn-secondary" type="submit">Search</button></form>{q&&<Link href="/dashboard/clients" className="btn btn-ghost" style={{textDecoration:"none"}}>Clear</Link>}</div>
 <div className="card cl-table"><div className="card-body-flush"><table className="data-table"><thead><tr><th>Client</th><th>Industry</th><th>Account Manager</th><th>Health</th><th>Risk</th><th>Monthly</th><th>LTV</th><th>Actions</th></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td><b>{c.companyName}</b></td><td>{c.industry||"—"}</td><td>{am[c.accountManagerId||""]||"—"}</td><td>{Math.round(Number(c.healthScore||0))}%</td><td>{c.churnRisk||"—"}</td><td>{money(Number(c.monthlyRetainer||0))}</td><td>{money(Number(c.lifetimeValue||0))}</td><td><div className="cl-buttons"><Link href={`/dashboard/clients/${c.id}`} className="btn btn-secondary btn-sm" style={{textDecoration:"none"}}>Open</Link>{canManage&&<ClientLifecycleButtons id={c.id} name={c.companyName} canDelete={canDelete}/>}</div></td></tr>)}{!rows.length&&<tr><td colSpan={8}>No clients found.</td></tr>}</tbody></table></div></div>
 <div className="cl-mobile">{rows.map(c=><article className="cl-card" key={c.id}><div className="cl-top"><div className="cl-name"><b>{c.companyName}</b><small>{c.industry||"No industry"}</small></div><span className="badge badge-gray">{c.churnRisk||"—"}</span></div><div className="cl-meta"><div><span>Account Manager</span><b>{am[c.accountManagerId||""]||"—"}</b></div><div><span>Health</span><b>{Math.round(Number(c.healthScore||0))}%</b></div><div><span>Monthly</span><b>{money(Number(c.monthlyRetainer||0))}</b></div><div><span>LTV</span><b>{money(Number(c.lifetimeValue||0))}</b></div></div><div className="cl-buttons"><Link href={`/dashboard/clients/${c.id}`} className="btn btn-secondary" style={{textDecoration:"none"}}>Open Client</Link>{canManage&&<ClientLifecycleButtons id={c.id} name={c.companyName} canDelete={canDelete}/>}</div></article>)}{!rows.length&&<div className="cl-card">No clients found.</div>}</div>
 </div>
}
