"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import Link from "next/link";
type UserOption={id:string;name:string;email?:string};
type Competitor={name:string;facebook:string;instagram:string;tiktok:string};
const emptyCompetitor=():Competitor=>({name:"",facebook:"",instagram:"",tiktok:""});
export function NewClientForm({managers,buyers,portalUsers,isAccountManager,isAccountant}:{managers:UserOption[];buyers:UserOption[];portalUsers:UserOption[];isAccountManager:boolean;isAccountant:boolean}){
 const router=useRouter(),[saving,setSaving]=useState(false),[error,setError]=useState(""),[competitors,setCompetitors]=useState<Competitor[]>([emptyCompetitor()]);
 const setCompetitor=(index:number,key:keyof Competitor,value:string)=>setCompetitors(current=>current.map((item,i)=>i===index?{...item,[key]:value}:item));
 const addCompetitor=()=>setCompetitors(current=>current.length>=5?current:[...current,emptyCompetitor()]);
 const removeCompetitor=(index:number)=>setCompetitors(current=>current.length<=1?current:current.filter((_,i)=>i!==index));
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const fd=new FormData(e.currentTarget),body={...Object.fromEntries(fd.entries()),competitors};try{const r=await fetch("/api/clients",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error||"Client could not be created.");router.push(`/dashboard/clients/${d.clientId}`);router.refresh()}catch(e){setError(e instanceof Error?e.message:"Client could not be created.")}finally{setSaving(false)}}
 const industries=["F&B","Retail","Real Estate","Entertainment","Hospitality","Technology","Marketing","Jewelry & Fashion","Healthcare","Education","Automotive","Other"];
 return <form onSubmit={submit} className="client-form">
  <section className="card-vivit"><h2 className="form-section-title">Company information</h2><label className="form-label full">COMPANY NAME *<input name="companyName" required minLength={2} placeholder="Company or brand name" className="form-input" autoFocus/></label><div className="form-grid"><label className="form-label">INDUSTRY<select name="industry" className="form-select"><option value="">Select industry</option>{industries.map(x=><option key={x}>{x}</option>)}</select></label><label className="form-label">WEBSITE<input name="website" type="url" inputMode="url" placeholder="https://company.com" className="form-input"/></label></div></section>
  <section className="card-vivit"><h2 className="form-section-title">Vivito reporting</h2><p className="page-subtitle" style={{marginBottom:12}}>Choose how often Vivito prepares and sends the monitoring report to the internal team.</p><label className="form-label full">REPORT FREQUENCY *<select name="reportFrequency" required defaultValue="WEEKLY" className="form-select"><option value="DAILY">Daily</option><option value="EVERY_3_DAYS">Every 3 days</option><option value="WEEKLY">Weekly</option></select></label></section>
  <section className="card-vivit"><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"center",flexWrap:"wrap"}}><div><h2 className="form-section-title" style={{marginBottom:3}}>Competitors *</h2><p className="page-subtitle">Add at least 1 competitor and up to 5. Facebook, Instagram and TikTok profile links are required for every competitor.</p></div><button type="button" className="btn btn-secondary btn-sm" disabled={competitors.length>=5} onClick={addCompetitor}>+ Add competitor</button></div><div style={{display:"grid",gap:12,marginTop:14}}>{competitors.map((c,index)=><div key={index} style={{border:"1px solid var(--card-border)",borderRadius:14,padding:14,display:"grid",gap:10}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><b>Competitor {index+1}</b>{competitors.length>1&&<button type="button" className="btn btn-ghost btn-sm" onClick={()=>removeCompetitor(index)}>Remove</button>}</div><label className="form-label">NAME *<input required value={c.name} onChange={e=>setCompetitor(index,"name",e.target.value)} className="form-input" placeholder="Competitor brand"/></label><div className="form-grid three"><label className="form-label">FACEBOOK *<input required type="url" value={c.facebook} onChange={e=>setCompetitor(index,"facebook",e.target.value)} className="form-input" placeholder="https://facebook.com/..."/></label><label className="form-label">INSTAGRAM *<input required type="url" value={c.instagram} onChange={e=>setCompetitor(index,"instagram",e.target.value)} className="form-input" placeholder="https://instagram.com/..."/></label><label className="form-label">TIKTOK *<input required type="url" value={c.tiktok} onChange={e=>setCompetitor(index,"tiktok",e.target.value)} className="form-input" placeholder="https://tiktok.com/@..."/></label></div></div>)}</div></section>
  <section className="card-vivit"><h2 className="form-section-title">Contract & budgets</h2><div className="form-grid three"><label className="form-label">MONTHLY RETAINER<input name="monthlyRetainer" type="number" min="0" step="0.01" inputMode="decimal" className="form-input"/></label><label className="form-label">MEDIA BUDGET<input name="mediaBudget" type="number" min="0" step="0.01" inputMode="decimal" className="form-input"/></label><label className="form-label">CONTRACT VALUE<input name="contractValue" type="number" min="0" step="0.01" inputMode="decimal" className="form-input"/></label></div><div className="form-grid"><label className="form-label">START DATE<input name="contractStart" type="date" className="form-input"/></label><label className="form-label">END DATE<input name="contractEnd" type="date" className="form-input"/></label></div></section>
  {!isAccountant&&<><section className="card-vivit"><h2 className="form-section-title">Team assignment</h2><div className="form-grid">{!isAccountManager&&<label className="form-label">ACCOUNT MANAGER<select name="accountManagerId" className="form-select"><option value="">Unassigned</option>{managers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}<label className="form-label">MEDIA BUYER<select name="mediaBuyerId" className="form-select"><option value="">Unassigned</option>{buyers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div></section><section className="card-vivit"><h2 className="form-section-title">Client portal access</h2><p className="page-subtitle" style={{marginBottom:12}}>Link this company to the client login that should see its campaigns, calendar, creatives, files and invoices.</p><label className="form-label full">PORTAL USER<select name="portalUserId" className="form-select"><option value="">Set up later</option>{portalUsers.map(x=><option key={x.id} value={x.id}>{x.name} · {x.email}</option>)}</select></label></section></>}
  <section className="card-vivit"><h2 className="form-section-title">Primary contact</h2><div className="form-grid"><label className="form-label">NAME<input name="contactName" className="form-input" autoComplete="name"/></label><label className="form-label">JOB TITLE<input name="contactTitle" className="form-input"/></label><label className="form-label">EMAIL<input name="contactEmail" type="email" inputMode="email" className="form-input" autoComplete="email"/></label><label className="form-label">PHONE / WHATSAPP<input name="contactPhone" type="tel" inputMode="tel" className="form-input" autoComplete="tel"/></label></div></section>
  {!isAccountant&&<section className="card-vivit"><h2 className="form-section-title">Advertising links & internal notes</h2><div className="form-grid"><label className="form-label">META ADS<input name="metaAdsLink" type="url" inputMode="url" className="form-input"/></label><label className="form-label">GOOGLE ADS<input name="googleAdsLink" type="url" inputMode="url" className="form-input"/></label><label className="form-label">TIKTOK ADS<input name="tiktokAdsLink" type="url" inputMode="url" className="form-input"/></label><label className="form-label">SNAPCHAT ADS<input name="snapchatAdsLink" type="url" inputMode="url" className="form-input"/></label></div><label className="form-label full">INTERNAL NOTES<textarea name="internalNotes" rows={4} className="form-input" placeholder="Only your internal team can see this"/></label></section>}
  {error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions"><Link href="/dashboard/clients" className="btn btn-ghost">Cancel</Link><button className="btn btn-primary" disabled={saving}>{saving?"Creating client…":"Create client →"}</button></div>
 </form>
}
