"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import Link from "next/link";
type UserOption={id:string;name:string;email?:string};
export function NewClientForm({managers,buyers,portalUsers,isAccountManager,isMediaBuyer,isAccountant}:{managers:UserOption[];buyers:UserOption[];portalUsers:UserOption[];isAccountManager:boolean;isMediaBuyer:boolean;isAccountant:boolean}){
 const router=useRouter(),[saving,setSaving]=useState(false),[error,setError]=useState("");
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const fd=new FormData(e.currentTarget),body=Object.fromEntries(fd.entries());try{const r=await fetch("/api/clients",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error||"Client could not be created.");router.push(`/dashboard/clients/${d.clientId}`);router.refresh()}catch(e){setError(e instanceof Error?e.message:"Client could not be created.")}finally{setSaving(false)}}
 const industries=["F&B","Retail","Real Estate","Entertainment","Hospitality","Technology","Marketing","Jewelry & Fashion","Healthcare","Education","Automotive","Other"];
 return <form onSubmit={submit} className="client-form">
  <section className="card-vivit"><h2 className="form-section-title">Company information</h2><label className="form-label full">COMPANY NAME *<input name="companyName" required minLength={2} placeholder="Company or brand name" className="form-input" autoFocus/></label><div className="form-grid"><label className="form-label">INDUSTRY *<select name="industry" required className="form-select"><option value="">Select industry</option>{industries.map(x=><option key={x}>{x}</option>)}</select></label><label className="form-label">WEBSITE *<input name="website" required type="url" inputMode="url" placeholder="https://company.com" className="form-input"/></label></div></section>
  <section className="card-vivit"><h2 className="form-section-title">Contract</h2><div className="form-grid"><label className="form-label">START DATE *<input name="contractStart" required type="date" className="form-input"/></label><label className="form-label">END DATE *<input name="contractEnd" required type="date" className="form-input"/></label></div><div className="page-subtitle" style={{marginTop:12,padding:12,border:"1px solid var(--card-border)",borderRadius:12}}>Financial amounts are completed after account creation by Accountant or Super Admin from Accounts Payment.</div></section>
  {!isAccountant&&<><section className="card-vivit"><h2 className="form-section-title">Team assignment</h2><div className="form-grid">{!isAccountManager&&<label className="form-label">ACCOUNT MANAGER *<select name="accountManagerId" required className="form-select"><option value="">Select account manager</option>{managers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}{isAccountManager&&<div className="form-label">ACCOUNT MANAGER<div className="form-input" style={{display:"flex",alignItems:"center",opacity:.8}}>Assigned to you automatically</div></div>}{!isMediaBuyer&&<label className="form-label">MEDIA BUYER *<select name="mediaBuyerId" required className="form-select"><option value="">Select media buyer</option>{buyers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}{isMediaBuyer&&<div className="form-label">MEDIA BUYER<div className="form-input" style={{display:"flex",alignItems:"center",opacity:.8}}>Assigned to your account automatically</div></div>}</div></section><section className="card-vivit"><h2 className="form-section-title">Client portal access</h2><p className="page-subtitle" style={{marginBottom:12}}>A portal account must be linked before the client can be created.</p><label className="form-label full">PORTAL USER *<select name="portalUserId" required className="form-select"><option value="">Select client portal user</option>{portalUsers.map(x=><option key={x.id} value={x.id}>{x.name} · {x.email}</option>)}</select></label></section></>}
  <section className="card-vivit"><h2 className="form-section-title">Primary contact</h2><div className="form-grid"><label className="form-label">NAME *<input name="contactName" required className="form-input" autoComplete="name"/></label><label className="form-label">JOB TITLE<input name="contactTitle" className="form-input"/></label><label className="form-label">EMAIL *<input name="contactEmail" required type="email" inputMode="email" className="form-input" autoComplete="email"/></label><label className="form-label">PHONE / WHATSAPP *<input name="contactPhone" required type="tel" inputMode="tel" className="form-input" autoComplete="tel"/></label></div></section>
  {!isAccountant&&<section className="card-vivit"><h2 className="form-section-title">Advertising links & internal notes</h2><div className="form-grid"><label className="form-label">META ADS<input name="metaAdsLink" type="url" inputMode="url" className="form-input"/></label><label className="form-label">GOOGLE ADS<input name="googleAdsLink" type="url" inputMode="url" className="form-input"/></label><label className="form-label">TIKTOK ADS<input name="tiktokAdsLink" type="url" inputMode="url" className="form-input"/></label><label className="form-label">SNAPCHAT ADS<input name="snapchatAdsLink" type="url" inputMode="url" className="form-input"/></label></div><label className="form-label full">INTERNAL NOTES<textarea name="internalNotes" rows={4} className="form-input" placeholder="Only your internal team can see this"/></label></section>}
  {error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions"><Link href="/dashboard/clients" className="btn btn-ghost">Cancel</Link><button className="btn btn-primary" disabled={saving}>{saving?"Creating client…":"Create client →"}</button></div>
 </form>
}
