export const dynamic="force-dynamic";
import {NextRequest,NextResponse} from "next/server";
import {auth} from "@/lib/auth";
import {db,creativeTasks,clients,users,financeRecords,notifications,sql} from "@/lib/db";
import {eq,inArray,lte,and} from "drizzle-orm";

const TASK_STATUS_ALLOWLIST=["IN_PROGRESS","REVIEW","APPROVED","REVISION","REJECTED","COMPLETED"] as const;
const TRANSITIONS:Record<string,string[]>={IN_PROGRESS:["PENDING","REVISION"],REVIEW:["IN_PROGRESS"],APPROVED:["REVIEW"],REVISION:["REVIEW"],REJECTED:["REVIEW"],COMPLETED:["APPROVED"]};
const activeTaskScope=(workspaceId:string)=>sql`${creativeTasks.id} in (select t.id from creative_tasks t join clients c on c.id=t.client_id where t.workspace_id=${workspaceId} and t.archived_at is null and c.workspace_id=${workspaceId} and c.is_active=true)`;
async function managedClientIds(role:string,userId:string,workspaceId:string){if(role==="SUPER_ADMIN")return null;if(role!=="ACCOUNT_MANAGER")return[] as string[];return(await db.select({id:clients.id}).from(clients).where(and(eq(clients.workspaceId,workspaceId),eq(clients.accountManagerId,userId),eq(clients.isActive,true)))).map(c=>c.id)}
function taskScope(ids:string[],role:string,owned:string[]|null,userId:string,workspaceId:string,from?:string[]){const parts:any[]=[eq(creativeTasks.workspaceId,workspaceId),activeTaskScope(workspaceId)];if(ids.length)parts.push(inArray(creativeTasks.id,ids));if(role==="ACCOUNT_MANAGER")parts.push(owned?.length?inArray(creativeTasks.clientId,owned):eq(creativeTasks.clientId,"__none__"));if(role==="CREATOR")parts.push(eq(creativeTasks.assignedToId,userId));if(from?.length)parts.push(inArray(creativeTasks.status,from as any));return and(...parts)}

export async function POST(req:NextRequest){const session=await auth();if(!session?.user)return NextResponse.json({error:"Unauthorized"},{status:401});const role=String((session.user as any).role||""),userId=String((session.user as any).id||""),workspaceId=String((session.user as any).workspaceId||"");if(!workspaceId)return NextResponse.json({error:"Workspace unavailable"},{status:403});let payload:any;try{payload=await req.json()}catch{return NextResponse.json({error:"Invalid JSON body"},{status:400})}const action=String(payload?.action||""),rawIds:string[]=(Array.isArray(payload?.ids)?payload.ids:[]).map((v:any)=>String(v)).filter(Boolean),ids=[...new Set(rawIds)].slice(0,100),data=payload?.data&&typeof payload.data==="object"?payload.data:{},updated:string[]=[];
 switch(action){
  case"tasks.status":{if(!["SUPER_ADMIN","ACCOUNT_MANAGER"].includes(role))return NextResponse.json({error:"Forbidden"},{status:403});const target=String(data.status||"");if(!TASK_STATUS_ALLOWLIST.includes(target as any))return NextResponse.json({error:"Invalid task status"},{status:400});const from=TRANSITIONS[target];if(!ids.length||!from)return NextResponse.json({error:"Invalid task IDs or transition"},{status:400});const owned=role==="ACCOUNT_MANAGER"?await managedClientIds(role,userId,workspaceId):null,rows=await db.update(creativeTasks).set({status:target as any,completedAt:target==="COMPLETED"?new Date():undefined,updatedAt:new Date()}).where(taskScope(ids,role,owned,userId,workspaceId,from)).returning({id:creativeTasks.id});updated.push(...rows.map(r=>r.id));break}
  case"tasks.assign":{if(!["SUPER_ADMIN","ACCOUNT_MANAGER"].includes(role))return NextResponse.json({error:"Forbidden"},{status:403});const assignedToId=String(data.assignedToId||"");if(!ids.length||!assignedToId)return NextResponse.json({error:"Task IDs and creator are required"},{status:400});const [creator]=await db.select({id:users.id}).from(users).where(and(eq(users.id,assignedToId),eq(users.workspaceId,workspaceId),eq(users.role,"CREATOR"),eq(users.isActive,true))).limit(1);if(!creator)return NextResponse.json({error:"Selected creator is not active in this workspace"},{status:400});const owned=role==="ACCOUNT_MANAGER"?await managedClientIds(role,userId,workspaceId):null,rows=await db.update(creativeTasks).set({assignedToId,updatedAt:new Date()}).where(taskScope(ids,role,owned,userId,workspaceId)).returning({id:creativeTasks.id});updated.push(...rows.map(r=>r.id));break}
  case"clients.recalculate":case"clients.update_health":{if(role!=="SUPER_ADMIN")return NextResponse.json({error:"Forbidden"},{status:403});const base=process.env.NEXTAUTH_URL??new URL(req.url).origin,cookie=req.headers.get("cookie")||"",result=await fetch(`${base}/api/performance-score`,{method:"POST",headers:{"Content-Type":"application/json",cookie},body:"{}"});if(!result.ok)return NextResponse.json({error:"Health recalculation failed"},{status:502});const response=await result.json().catch(()=>({}));return NextResponse.json({success:true,action:"health_recalculated",processed:response.processed??null})}
  case"clients.export":{if(!["SUPER_ADMIN","ACCOUNTANT","ACCOUNT_MANAGER","MEDIA_BUYER"].includes(role))return NextResponse.json({error:"Forbidden"},{status:403});const condition=and(eq(clients.workspaceId,workspaceId),eq(clients.isActive,true),role==="ACCOUNT_MANAGER"?eq(clients.accountManagerId,userId):role==="MEDIA_BUYER"?eq(clients.mediaBuyerId,userId):sql`true`),rows=await db.select().from(clients).where(condition);return NextResponse.json({data:rows,count:rows.length},{headers:{"Cache-Control":"private, no-store"}})}
  case"tasks.export":{if(!["SUPER_ADMIN","ACCOUNT_MANAGER","CREATOR"].includes(role))return NextResponse.json({error:"Forbidden"},{status:403});const owned=role==="ACCOUNT_MANAGER"?await managedClientIds(role,userId,workspaceId):null,rows=await db.select().from(creativeTasks).where(taskScope(ids,role,owned,userId,workspaceId));return NextResponse.json({data:rows,count:rows.length},{headers:{"Cache-Control":"private, no-store"}})}
  case"tasks.notify":{if(!["SUPER_ADMIN","ACCOUNT_MANAGER"].includes(role))return NextResponse.json({error:"Forbidden"},{status:403});if(!ids.length)return NextResponse.json({success:true,notified:0});const owned=role==="ACCOUNT_MANAGER"?await managedClientIds(role,userId,workspaceId):null,tasks=await db.select({id:creativeTasks.id,title:creativeTasks.title,assignedToId:creativeTasks.assignedToId}).from(creativeTasks).where(taskScope(ids,role,owned,userId,workspaceId));let notified=0;for(const t of tasks){if(!t.assignedToId)continue;const [recipient]=await db.select({id:users.id}).from(users).where(and(eq(users.id,t.assignedToId),eq(users.workspaceId,workspaceId),eq(users.isActive,true))).limit(1);if(!recipient)continue;await db.insert(notifications).values({userId:t.assignedToId,type:"DEADLINE_UPCOMING",priority:"high",title:`📬 Reminder: ${t.title}`,message:"Your task needs attention — please check the latest status.",link:`/dashboard/creative/${t.id}`} as any);notified++}return NextResponse.json({success:true,notified})}
  case"invoices.mark_overdue":{if(!["SUPER_ADMIN","ACCOUNTANT"].includes(role))return NextResponse.json({error:"Forbidden"},{status:403});const rows=await db.update(financeRecords).set({invoiceStatus:"OVERDUE" as any,updatedAt:new Date()} as any).where(and(eq(financeRecords.workspaceId,workspaceId),lte(financeRecords.dueDate!,new Date()),eq(financeRecords.invoiceStatus,"SENT" as any))).returning({id:financeRecords.id});return NextResponse.json({success:true,action:"overdue_marked",updated:rows.length})}
  default:return NextResponse.json({error:"Unknown action"},{status:400})
 }
 return NextResponse.json({success:true,updated:updated.length,ids:updated})}