"use client";
import {useEffect,useState} from "react";

const platforms=["META","TIKTOK","GOOGLE","SNAPCHAT","LINKEDIN"];
const labels:any={META:"Meta — Facebook & Instagram",TIKTOK:"TikTok Ads",GOOGLE:"Google & YouTube Ads",SNAPCHAT:"Snapchat Ads",LINKEDIN:"LinkedIn Ads"};

export default function PlatformSync(){
 const[data,setData]=useState<any>({clients:[],campaigns:[],connections:[],integrations:{}}),[busy,setBusy]=useState(""),[message,setMessage]=useState(""),[selectedPlatform,setSelectedPlatform]=useState("META"),[loading,setLoading]=useState(true);
 async function load(){try{const r=await fetch("/api/media-control"),d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load integrations");setData(d)}catch(e:any){setMessage(e.message||"Unable to load integrations")}finally{setLoading(false)}}
 useEffect(()=>{const q=new URLSearchParams(window.location.search),status=q.get("oauth"),requested=(q.get("platform")||"").toUpperCase();if(platforms.includes(requested))setSelectedPlatform(requested);load();if(status==="success")setMessage(`${q.get("platform")} connected securely.`);if(status==="missing")setMessage(`${q.get("platform")} developer app keys are not configured in Vercel yet.`);if(status==="error")setMessage(q.get("message")||"Connection failed.");window.history.replaceState({},"",window.location.pathname)},[]);
 async function sync(campaignId:string){setBusy(campaignId);const r=await fetch("/api/media-control",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({op:"sync",campaignId})}),d=await r.json();setMessage(r.ok?`Synced ${d.days} days. ${d.alerts?.length||0} alerts created.`:d.error);if(r.ok)await load();setBusy("")}
 async function linkByIds(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,body:any=Object.fromEntries(new FormData(f).entries());setBusy("link");setMessage("");const r=await fetch("/api/media-link",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),d=await r.json();setMessage(r.ok?`${d.campaign?.name||"Campaign"} connected. ${d.days} days loaded from ${d.campaign?.platform}.`:d.error||"Campaign could not be connected.");if(r.ok){f.reset();await load()}setBusy("")}
 const quick=selectedPlatform==="META"||selectedPlatform==="TIKTOK";
 return <div style={{display:"grid",gap:18,maxWidth:1000}}>
  <div><h1 className="page-title">Ad Platform Connections</h1><p className="page-subtitle">Connect Meta or TikTok with the Ad Account ID + Campaign ID and load live campaign data into VIVIT ERP.</p></div>
  {message&&<div className={message.includes("connected")||message.includes("Synced")||message.includes("loaded")?"media-success":"media-error"}>{message}</div>}
  <div className="card"><div className="card-header"><div><p className="card-title">Quick campaign connection</p><p className="page-subtitle" style={{margin:0}}>No campaign URL needed. Enter the IDs exactly as shown in Ads Manager.</p></div><span className="badge badge-blue">Meta + TikTok</span></div><div className="card-body">
   <form className="media-form" onSubmit={linkByIds}>
    <label className="form-label">CLIENT<select required name="clientId" className="form-select"><option value="">Select client</option>{data.clients?.map((c:any)=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label>
    <label className="form-label">PLATFORM<select name="platform" value={selectedPlatform} onChange={e=>setSelectedPlatform(e.target.value)} className="form-select"><option value="META">Meta — Facebook & Instagram</option><option value="TIKTOK">TikTok Ads</option></select></label>
    <label className="form-label">AD ACCOUNT ID<input required name="adAccountId" inputMode="numeric" pattern="[0-9]+" className="form-input" placeholder={selectedPlatform==="META"?"Example: 123456789012345":"TikTok Advertiser ID"}/><small style={{color:"var(--text-muted)"}}>For Meta you can paste the number with or without the act_ prefix.</small></label>
    <label className="form-label">CAMPAIGN ID<input required name="campaignId" inputMode="numeric" pattern="[0-9]+" className="form-input" placeholder="Campaign ID"/><small style={{color:"var(--text-muted)"}}>VIVIT verifies that this campaign belongs to the account before saving it.</small></label>
    <label className="form-label">ACCOUNT NAME <span style={{fontWeight:400}}>(optional)</span><input name="accountName" className="form-input" placeholder="Client Main Ads Account"/></label>
    <button className="btn btn-primary" disabled={busy==="link"}>{busy==="link"?"Checking platform…":"Connect & Load Campaign →"}</button>
   </form><p style={{fontSize:11,color:"var(--text-muted)",marginTop:12}}>Requires a valid Meta/TikTok access token in Vercel, or a previously authorized OAuth account. No token is ever entered in this form.</p>
  </div></div>
  <div className="card"><div className="card-header"><p className="card-title">Secure OAuth connection</p><span className="badge badge-blue">Optional</span></div><div className="card-body">
   <form className="media-form" onSubmit={e=>{e.preventDefault();const values:any=Object.fromEntries(new FormData(e.currentTarget).entries()),params=new URLSearchParams({clientId:values.clientId,adAccountId:values.adAccountId||"",accountName:values.accountName||""});window.location.assign(`/api/ad-oauth/${String(values.platform).toLowerCase()}/start?${params}`)}}>
    <label className="form-label">CLIENT<select required name="clientId" className="form-select"><option value="">Select client</option>{data.clients?.map((c:any)=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label>
    <label className="form-label">PLATFORM<select name="platform" value={selectedPlatform} onChange={e=>setSelectedPlatform(e.target.value)} className="form-select">{platforms.map(p=><option key={p} value={p}>{labels[p]}</option>)}</select><small style={{color:data.integrations?.[selectedPlatform]?"var(--green)":"var(--amber)"}}>{loading?"Checking setup…":data.integrations?.[selectedPlatform]?"Developer app is ready — continue to authorization.":"Developer keys are not configured yet."}</small></label>
    <label className="form-label">AD ACCOUNT ID<input required={selectedPlatform!=="SNAPCHAT"} name="adAccountId" className="form-input" placeholder={selectedPlatform==="SNAPCHAT"?"Detected after authorization":"Ads Manager account ID"}/></label>
    <label className="form-label">ACCOUNT NAME<input name="accountName" className="form-input" placeholder="Client Main Account"/></label>
    <button className="btn btn-secondary" disabled={loading}>Authorize {labels[selectedPlatform]} →</button>
   </form><p style={{fontSize:11,color:"var(--text-muted)",marginTop:12}}>Use OAuth when you want each client account to have its own encrypted authorization token.</p>
  </div></div>
  <div className="card"><div className="card-header"><p className="card-title">Connected accounts</p><span className="badge badge-green">Encrypted / server-side</span></div><div className="card-body" style={{display:"grid",gap:9}}>{data.connections?.map((x:any)=><div className="media-decision" key={x.id}><div><strong>{labels[x.platform]||x.platform}</strong><small>{x.accountName||"Ad Account"} · {x.adAccountId}<br/>Last sync: {x.lastSyncAt?new Date(x.lastSyncAt).toLocaleString():"Not synced yet"}</small></div><span className={`badge ${x.status==="CONNECTED"?"badge-green":"badge-gray"}`}>{x.status}</span></div>)}{!data.connections?.length&&<p className="text-muted">No accounts connected yet.</p>}</div></div>
  <div className="card"><div className="card-header"><p className="card-title">Campaign sync</p><span className="badge badge-blue">Last 30 days</span></div><div className="card-body" style={{display:"grid",gap:9}}>{data.campaigns?.map((c:any)=><div className="media-decision" key={c.id}><div><strong>{c.name}</strong><small>{c.platform} · Campaign ID {c.externalId}<br/>Last sync: {c.lastSyncAt?new Date(c.lastSyncAt).toLocaleString():"Never"}</small></div><span className="badge badge-gray">{c.status}</span><button className="btn btn-primary btn-sm" disabled={busy===c.id} onClick={()=>sync(c.id)}>{busy===c.id?"Syncing…":"Sync now ↻"}</button></div>)}{!data.campaigns?.length&&<div className="empty-state"><p className="empty-state-icon">🔗</p><p className="empty-state-desc">Connect a Meta or TikTok campaign above.</p></div>}</div></div>
 </div>
}
