import Link from "next/link";
import {notFound} from "next/navigation";
import {WorkspacePage} from "@/components/vgroup/workspace-page";
import {PostActionButton} from "@/components/vgroup/post-action-button";
import {requireBusinessUnitAccess} from "@/lib/vgroup/access";
import {getVGroupSql} from "@/lib/vgroup/db";
import HospitalityCalendar from "./HospitalityCalendar";

type Ops={housekeeping_open:number;complaints_open:number;inbox_open:number;maintenance_due:number;rfqs_open:number;reconciliation_open:number;lost_found_open:number;pricing_rules:number};
type PropertyRow={id:string;name:string};type ReservationRow={id:string;property_id:string;guest_name:string;check_in:string;check_out:string;status:string};
type WorkOrderRow={id:string;title:string;priority:string;status:string;estimated_cost:number|null;property_name:string};type PurchaseOrderRow={id:string;po_number:string;status:string;currency:string;total:number;property_name:string|null;vendor_name:string|null};
export const dynamic="force-dynamic";const uuid=/^[0-9a-f-]{36}$/i;
export default async function Page({searchParams}:{searchParams:Promise<{propertyId?:string}>}){
 await requireBusinessUnitAccess("hospitality");
 const {propertyId:rawPropertyId}=await searchParams;
 if(rawPropertyId&&!uuid.test(rawPropertyId))notFound();
 const propertyId=rawPropertyId||"";
 const sql=getVGroupSql();
 const [bu]=await sql<{id:string}[]>`select id::text from vgroup.business_units where code='hospitality' and status='active' limit 1`;const buId=bu?.id;
 let activeProperty:PropertyRow|undefined;
 if(propertyId){
  [activeProperty]=await sql<PropertyRow[]>`select id::text,name from hospitality.properties where id=${propertyId}::uuid and archived_at is null limit 1`;
  if(!activeProperty)notFound();
 }
 const effectivePropertyId=activeProperty?.id||"";
 const workOrders=effectivePropertyId?await sql<WorkOrderRow[]>`select w.id::text,w.title,w.priority,w.status,w.estimated_cost,p.name property_name from hospitality.work_orders w join hospitality.properties p on p.id=w.property_id where w.archived_at is null and w.property_id=${effectivePropertyId}::uuid order by w.created_at desc limit 40`:await sql<WorkOrderRow[]>`select w.id::text,w.title,w.priority,w.status,w.estimated_cost,p.name property_name from hospitality.work_orders w join hospitality.properties p on p.id=w.property_id where w.archived_at is null order by w.created_at desc limit 40`;
 const purchaseOrders=effectivePropertyId?await sql<PurchaseOrderRow[]>`select po.id::text,po.po_number,po.status,po.currency,po.total,p.name property_name,v.name vendor_name from hospitality.purchase_orders po left join hospitality.properties p on p.id=po.property_id left join hospitality.vendors v on v.id=po.vendor_id where po.property_id=${effectivePropertyId}::uuid order by po.created_at desc limit 40`:await sql<PurchaseOrderRow[]>`select po.id::text,po.po_number,po.status,po.currency,po.total,p.name property_name,v.name vendor_name from hospitality.purchase_orders po left join hospitality.properties p on p.id=po.property_id left join hospitality.vendors v on v.id=po.vendor_id order by po.created_at desc limit 40`;
 const zero:Ops={housekeeping_open:0,complaints_open:0,inbox_open:0,maintenance_due:0,rfqs_open:0,reconciliation_open:0,lost_found_open:0,pricing_rules:0};
 const ops:Ops=!effectivePropertyId&&buId?(await sql<Ops[]>`select (select count(*)::int from hospitality.housekeeping_tasks where business_unit_id=${buId}::uuid and status not in ('passed','cancelled')) housekeeping_open,(select count(*)::int from hospitality.guest_complaints where business_unit_id=${buId}::uuid and status not in ('resolved','closed')) complaints_open,(select count(*)::int from hospitality.guest_conversations where business_unit_id=${buId}::uuid and status<>'closed') inbox_open,(select count(*)::int from hospitality.preventive_maintenance_plans where business_unit_id=${buId}::uuid and active and next_due_on<=current_date+30) maintenance_due,(select count(*)::int from hospitality.procurement_rfqs where business_unit_id=${buId}::uuid and status in ('open','evaluation')) rfqs_open,(select count(*)::int from hospitality.channel_reconciliations where business_unit_id=${buId}::uuid and status in ('pending','variance')) reconciliation_open,(select count(*)::int from hospitality.lost_found_items where business_unit_id=${buId}::uuid and status not in ('returned','disposed')) lost_found_open,(select count(*)::int from hospitality.pricing_rules where business_unit_id=${buId}::uuid and active) pricing_rules`)[0]:zero;
 const properties:PropertyRow[]=effectivePropertyId&&activeProperty?[activeProperty]:buId?Array.from(await sql<PropertyRow[]>`select id::text,name from hospitality.properties where business_unit_id=${buId}::uuid and archived_at is null and status='active' order by name limit 30`):[];
 const reservations:ReservationRow[]=effectivePropertyId?Array.from(await sql<ReservationRow[]>`select r.id::text,r.property_id::text,r.guest_name,r.check_in::text,r.check_out::text,r.status from hospitality.reservations r where r.property_id=${effectivePropertyId}::uuid and r.status in ('pending','confirmed','checked_in') and r.check_out>=current_date order by r.check_in limit 120`):buId?Array.from(await sql<ReservationRow[]>`select r.id::text,r.property_id::text,r.guest_name,r.check_in::text,r.check_out::text,r.status from hospitality.reservations r where r.business_unit_id=${buId}::uuid and r.status in ('pending','confirmed','checked_in') and r.check_out>=current_date order by r.check_in limit 120`):[];
 const cards=effectivePropertyId?[["Property reservations",`${reservations.length} active/upcoming`,`Calendar is restricted to ${activeProperty?.name}.`],["Work orders",`${Array.from(workOrders).length} recent`,`Maintenance list is restricted to this property.`],["Purchase orders",`${Array.from(purchaseOrders).length} recent`,`Procurement records shown here are property-bound only.`]]:[["Housekeeping",`${ops.housekeeping_open} open`,`Turnover, stayover, deep cleaning, inspection and turnaround SLA.`],["Guest CRM & Inbox",`${ops.complaints_open} complaints · ${ops.inbox_open} threads`,`Guest history, preferences, VIP/repeat tracking and provider-neutral conversations.`],["Revenue Management",`${ops.pricing_rules} active pricing rules`,`Seasonal, weekend, occupancy, minimum-stay and manual pricing controls.`],["Preventive Maintenance",`${ops.maintenance_due} due ≤30d`,`Recurring plans, asset lifecycle, warranty tracking and vendor routing.`],["Procurement",`${ops.rfqs_open} RFQs`,`RFQ → vendor quotations → approval → PO → receiving → 3-way invoice match.`],["Channel Reconciliation",`${ops.reconciliation_open} pending/variance`,`Reservation gross, channel fees and actual payout reconciliation.`],["Lost & Found",`${ops.lost_found_open} open`,`Custody, claimant and return/disposal evidence.`],["Owner Commercials","Commission + fee + revenue share","Contract renewal rules, owner economics and profitability controls."]];
 return <><WorkspacePage tone="hospitality" eyebrow="HOSPITALITY OPERATING SYSTEM" title={effectivePropertyId?`${activeProperty?.name} Operations`:"Operations Cockpit"} description={effectivePropertyId?"Property context is enforced: calendar, work orders and purchase orders are restricted to this apartment/property.":"Daily property operations, revenue management, guest experience, procurement, maintenance and channel finance in one control plane."} sections={cards.map(([title,body,description])=>({title,body:`${body} — ${description}`}))}/><section style={{maxWidth:1180,margin:"-40px auto 60px",padding:"0 20px",color:"#f7f1e3",display:"grid",gap:24}}>{effectivePropertyId&&<Link href={`/group/hospitality/properties/${effectivePropertyId}`} style={{color:"#d6ad5b",fontWeight:900,textDecoration:"none"}}>← Back to {activeProperty?.name}</Link>}<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:12}}>{cards.map(([name,value,desc])=><article key={name} style={{padding:18,border:"1px solid #4a3a1c",borderRadius:18,background:"rgba(212,175,55,.035)"}}><h2 style={{fontSize:17,margin:"0 0 7px"}}>{name}</h2><strong style={{color:"#d9c98f"}}>{value}</strong><p style={{fontSize:12,color:"#b7aa8b",lineHeight:1.55}}>{desc}</p></article>)}</div><HospitalityCalendar properties={properties} reservations={reservations}/><div><h2>Work orders</h2><div style={{display:"grid",gap:9}}>{Array.from(workOrders).map(r=><article key={r.id} style={{padding:14,border:"1px solid #4a3a1c",borderRadius:14,display:"flex",justifyContent:"space-between",gap:14,alignItems:"center",flexWrap:"wrap"}}><div><b>{r.title}</b><div style={{fontSize:12,color:"#b7aa8b"}}>{r.property_name} · {r.priority} · {r.status} · Est. {Number(r.estimated_cost||0).toFixed(2)}</div></div>{r.status==="pending_approval"?<PostActionButton endpoint={`/api/vgroup/hospitality/work-orders/${r.id}/approve`} label="Approve"/>:null}</article>)}</div></div><div><h2>Purchase orders</h2><div style={{display:"grid",gap:9}}>{Array.from(purchaseOrders).map(r=><article key={r.id} style={{padding:14,border:"1px solid #4a3a1c",borderRadius:14,display:"flex",justifyContent:"space-between",gap:14,alignItems:"center",flexWrap:"wrap"}}><div><b>{r.po_number}</b><div style={{fontSize:12,color:"#b7aa8b"}}>{r.property_name||"Group"} · {r.vendor_name||"Unassigned vendor"} · {r.currency} {Number(r.total||0).toFixed(2)} · {r.status}</div></div>{r.status==="draft"||r.status==="pending_approval"?<PostActionButton endpoint={`/api/vgroup/hospitality/purchase-orders/${r.id}/approve`} label="Approve PO"/>:null}</article>)}</div></div></section></>
}
