"use client";
import {FormEvent,useState} from "react";
import {useRouter} from "next/navigation";

type Props={block:{id:string;summary:string;starts_on:string;ends_on:string;finance_status:string;currency:string;gross_amount:number|null;airbnb_fee:number|null;cleaning_fee:number|null;taxes:number|null;net_payout:number|null}};
const input:React.CSSProperties={width:"100%",boxSizing:"border-box",background:"#0c0b09",color:"#f7f1e3",border:"1px solid #5a4927",borderRadius:10,padding:"9px 10px"};
const btn:React.CSSProperties={border:0,borderRadius:10,padding:"9px 12px",fontWeight:900,cursor:"pointer",background:"#D6AD5B",color:"#0C1B2A"};
export function AirbnbFinanceCard({block}:Props){
  const router=useRouter();const[busy,setBusy]=useState(false);const[error,setError]=useState("");
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);const payload={blockId:block.id,guestName:f.get("guestName"),guests:Number(f.get("guests")||1),currency:f.get("currency"),grossAmount:Number(f.get("grossAmount")),airbnbFee:Number(f.get("airbnbFee")||0),cleaningFee:Number(f.get("cleaningFee")||0),taxes:Number(f.get("taxes")||0),netPayout:Number(f.get("netPayout")),companyCommission:Number(f.get("companyCommission")||0)};const r=await fetch("/api/vgroup/hospitality/airbnb-finance",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const b=await r.json();if(!r.ok){setError(typeof b.error==="string"?b.error:"Save failed");setBusy(false);return}router.refresh();setBusy(false)}
  async function markNotBooking(){setBusy(true);setError("");const r=await fetch("/api/vgroup/hospitality/airbnb-finance",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({blockId:block.id,notABooking:true})});if(!r.ok){const b=await r.json();setError(typeof b.error==="string"?b.error:"Update failed");setBusy(false);return}router.refresh();setBusy(false)}
  return <div style={{padding:14,borderRadius:16,border:"1px solid rgba(214,173,91,.18)"}}><div style={{display:"flex",justifyContent:"space-between",gap:10,flexWrap:"wrap"}}><div><strong>{block.summary}</strong><div style={{fontSize:12,color:"#C7B894",marginTop:4}}>{block.starts_on} → {block.ends_on}</div></div><span style={{fontSize:11,fontWeight:900,color:block.finance_status==="complete"?"#BDE7A8":"#F7E3AA"}}>{block.finance_status==="complete"?"FINANCIAL COMPLETE":block.finance_status==="not_a_booking"?"NOT A BOOKING":"FINANCIAL DATA PENDING"}</span></div>{block.finance_status==="complete"?<div style={{marginTop:10,fontSize:13,color:"#C7B894"}}>{block.currency} {Number(block.gross_amount||0).toLocaleString()} gross · Airbnb fee {Number(block.airbnb_fee||0).toLocaleString()} · Cleaning {Number(block.cleaning_fee||0).toLocaleString()} · Taxes {Number(block.taxes||0).toLocaleString()} · <b style={{color:"#F7E3AA"}}>Net payout {Number(block.net_payout||0).toLocaleString()}</b></div>:block.finance_status==="pending"?<form onSubmit={submit} style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(120px,1fr))",gap:8,marginTop:12}}><input name="guestName" placeholder="Guest name" style={input}/><input name="guests" type="number" min="1" defaultValue="1" placeholder="Guests" style={input}/><input name="currency" defaultValue="EGP" maxLength={3} style={input}/><input name="grossAmount" type="number" min="0" step="0.01" required placeholder="Gross" style={input}/><input name="airbnbFee" type="number" min="0" step="0.01" defaultValue="0" placeholder="Airbnb fee" style={input}/><input name="cleaningFee" type="number" min="0" step="0.01" defaultValue="0" placeholder="Cleaning" style={input}/><input name="taxes" type="number" min="0" step="0.01" defaultValue="0" placeholder="Taxes" style={input}/><input name="companyCommission" type="number" min="0" step="0.01" defaultValue="0" placeholder="Vivit commission" style={input}/><input name="netPayout" type="number" min="0" step="0.01" required placeholder="Net payout" style={input}/><button disabled={busy} style={btn}>{busy?"Saving…":"Complete finance"}</button><button disabled={busy} type="button" onClick={markNotBooking} style={{...btn,background:"transparent",color:"#C7B894",border:"1px solid #5a4927"}}>Not a booking</button></form>:null}{error&&<div style={{marginTop:8,color:"#FFB8B8",fontSize:12}}>{error}</div>}</div>
}
