"use client";
import {useState} from "react";

async function post(url:string,body:Record<string,unknown>={}){const res=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||`Request failed (${res.status})`);return data}
export function CrActionPanel({id,status}:{id:string;status:string}){
 const [busy,setBusy]=useState(false);const [msg,setMsg]=useState("");const [price,setPrice]=useState("");const [days,setDays]=useState("0");
 async function run(action:"price"|"approve"|"reject"){setBusy(true);setMsg("");try{if(action==="price")await post(`/api/vgroup/tech/change-requests/${id}/price`,{price:Number(price),extraDays:Number(days)});else if(action==="approve")await post(`/api/vgroup/tech/change-requests/${id}/approve`,{});else await post(`/api/vgroup/tech/change-requests/${id}/reject`,{note:"Rejected from commercial workspace"});setMsg("Updated");window.location.reload()}catch(e){setMsg(e instanceof Error?e.message:"Action failed")}finally{setBusy(false)}}
 return <div style={{display:"grid",gap:8,minWidth:270}}><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><input aria-label="Proposed price" value={price} onChange={e=>setPrice(e.target.value)} placeholder="Price" type="number" min="0" style={{width:90,padding:8,borderRadius:9,border:"1px solid #23445f",background:"#08111b",color:"#fff"}}/><input aria-label="Extra days" value={days} onChange={e=>setDays(e.target.value)} type="number" min="0" style={{width:72,padding:8,borderRadius:9,border:"1px solid #23445f",background:"#08111b",color:"#fff"}}/><button disabled={busy} onClick={()=>run("price")} style={{padding:"8px 10px",borderRadius:9,border:0,fontWeight:800}}>Price</button>{status==="priced"?<button disabled={busy} onClick={()=>run("approve")} style={{padding:"8px 10px",borderRadius:9,border:0,fontWeight:800}}>Approve</button>:null}<button disabled={busy} onClick={()=>run("reject")} style={{padding:"8px 10px",borderRadius:9,border:"1px solid #5b2830",background:"transparent",color:"#fca5a5",fontWeight:800}}>Reject</button></div>{msg?<small>{msg}</small>:null}</div>
}
