"use client";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";

type Statement={id:string;owner_name:string;period_start:string;period_end:string;currency:string;gross_revenue:number;net_payable:number;status:string};
type ReservationFinance={id:string;source:string;guest_name:string;check_in:string;check_out:string;currency:string;gross_amount:number;platform_fee:number;company_commission:number;net_owner_amount:number;status:string};
type FinanceData={statements:Statement[];payouts:unknown[];refunds:unknown[];deposits:unknown[];reservations?:ReservationFinance[];propertyScoped?:boolean;property?:{id:string;name:string}};
type Ref={id:string;name:string};
type Expense={id:string;property_id:string;property_name:string;vendor_name:string|null;category_name:string|null;invoice_number:string|null;invoice_type:string;currency:string;subtotal:number;tax:number;total:number;issued_at:string;status:string;notes:string|null;receipt_count:number};
type ExpenseData={expenses:Expense[];properties:Ref[];categories:Ref[];vendors:Ref[]};

const GOLD="#c6a04a",GOLD_DARK="#8a6a22",INK="#171717",MUTED="#6b6252",BORDER="#e3d4ae",PAPER="#ffffff",SOFT="#fbf8f0";
const card:React.CSSProperties={padding:18,border:`1px solid ${BORDER}`,borderRadius:18,background:PAPER,color:INK,boxShadow:"0 12px 34px rgba(116,88,30,.08)",minWidth:0,maxWidth:"100%",boxSizing:"border-box"};
const input:React.CSSProperties={width:"100%",minWidth:0,maxWidth:"100%",boxSizing:"border-box",background:PAPER,color:INK,border:"1px solid #d8d0bd",borderRadius:12,padding:"12px 13px",fontSize:16,outlineColor:GOLD};
const label:React.CSSProperties={display:"grid",gap:6,minWidth:0,fontSize:12,fontWeight:800,color:GOLD_DARK};
const button:React.CSSProperties={border:0,borderRadius:12,padding:"12px 16px",fontWeight:900,cursor:"pointer",background:GOLD,color:INK,minHeight:44};
function errorText(value:unknown){if(typeof value==="string")return value;if(value&&typeof value==="object"&&"message" in value)return String((value as {message?:unknown}).message??"Request failed");return "Request failed"}

export function HospitalityFinancePanel({propertyId}:{propertyId?:string}){
 const router=useRouter();const[finance,setFinance]=useState<FinanceData|null>(null),[expenseData,setExpenseData]=useState<ExpenseData|null>(null),[error,setError]=useState(""),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 const[reportProperty,setReportProperty]=useState(propertyId||"");const today=new Date().toISOString().slice(0,10),monthStart=`${today.slice(0,8)}01`;const[reportFrom,setReportFrom]=useState(monthStart),[reportTo,setReportTo]=useState(today);const query=propertyId?`?propertyId=${encodeURIComponent(propertyId)}`:"";
 const loadFinance=useCallback(()=>fetch(`/api/vgroup/hospitality/finance${query}`,{cache:"no-store"}).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(errorText(body.error));return body as FinanceData}).then(setFinance),[query]);
 const loadExpenses=useCallback(()=>fetch(`/api/vgroup/hospitality/expenses${query}`,{cache:"no-store"}).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(errorText(body.error));return body as ExpenseData}).then(data=>{setExpenseData(data);setReportProperty(current=>propertyId||current||data.properties[0]?.id||"")}),[propertyId,query]);
 const load=useCallback(()=>Promise.all([loadFinance(),loadExpenses()]).catch((e:unknown)=>setError(e instanceof Error?e.message:"load_failed")),[loadFinance,loadExpenses]);useEffect(()=>{void load()},[load]);
 const propertyTotals=useMemo(()=>{const map=new Map<string,{name:string,total:number;currency:string}>();for(const item of expenseData?.expenses??[]){const current=map.get(item.property_id)??{name:item.property_name,total:0,currency:item.currency};current.total+=Number(item.total);map.set(item.property_id,current)}return Array.from(map.entries())},[expenseData]);
 async function submitExpense(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setMessage("");setError("");const form=new FormData(event.currentTarget);if(propertyId)form.set("propertyId",propertyId);try{const response=await fetch("/api/vgroup/hospitality/expenses",{method:"POST",body:form});const body=await response.json();if(!response.ok)throw new Error(errorText(body.error));event.currentTarget.reset();setMessage("Expense saved and locked to its property.");await loadExpenses()}catch(e){setError(e instanceof Error?e.message:"expense_save_failed")}finally{setSaving(false)}}
 function exportReport(format:"xls"|"pdf"){if(!reportProperty){setError("Select a property before exporting");return}const qs=new URLSearchParams({propertyId:reportProperty,from:reportFrom,to:reportTo,format});router.push(`/api/vgroup/hospitality/expenses/report?${qs.toString()}`)}
 if(!finance||!expenseData)return <p style={{color:INK,padding:16}}>{error||"Loading finance…"}</p>;
 const selectedProperty=propertyId?expenseData.properties.find(x=>x.id===propertyId):undefined;
 const metricItems=[["Expenses",expenseData.expenses.length],["Properties with spend",propertyTotals.length],["Reservations",finance.reservations?.length||0],["Statements",finance.statements.length],["Payouts",finance.payouts.length],["Refunds",finance.refunds.length],["Deposits",finance.deposits.length]] as const;
 return <div className="hospitality-finance" style={{display:"grid",gap:22,minWidth:0,maxWidth:"100%",overflowX:"hidden",color:INK}}><style>{`.hospitality-finance *{box-sizing:border-box}.hf-metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(135px,1fr));gap:10px}.hf-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:18px}.hf-report{display:grid;grid-template-columns:minmax(0,2fr) minmax(140px,1fr) minmax(140px,1fr) auto auto;gap:10px;margin-top:16px;align-items:end}.hf-row{display:grid;grid-template-columns:minmax(0,2fr) repeat(3,minmax(0,1fr));gap:10px;align-items:center}.hf-span2{grid-column:span 2}@media(max-width:720px){.hospitality-finance{gap:16px!important}.hf-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.hf-form,.hf-report,.hf-row{grid-template-columns:minmax(0,1fr)}.hf-span2{grid-column:1}.hf-report button{width:100%}.hf-row>span{display:flex;justify-content:space-between;gap:12px;align-items:baseline;min-width:0}.hf-row>span:first-child{display:block}.hospitality-finance h2{font-size:1.25rem}}@media(max-width:390px){.hf-metrics{grid-template-columns:minmax(0,1fr)}}`}</style>
 {propertyId&&<div style={{...card,borderColor:GOLD,background:SOFT}}><b style={{color:GOLD_DARK,letterSpacing:".08em"}}>PROPERTY CONTEXT ACTIVE</b><div style={{fontSize:13,marginTop:6,color:MUTED,lineHeight:1.55,overflowWrap:"anywhere"}}>{selectedProperty?.name||finance.property?.name||propertyId} · Portfolio-level owner statements and payouts are intentionally hidden in this view.</div></div>}
 {error&&<div style={{...card,borderColor:"#e8b4b4",background:"#fff7f7",color:"#a11"}}>{error}</div>}{message&&<div style={{...card,borderColor:"#b7d7ae",background:"#f8fff6",color:"#25631e"}}>{message}</div>}
 <div className="hf-metrics">{metricItems.map(([l,v])=><div key={l} style={{...card,padding:16}}><b style={{fontSize:25,color:INK}}>{v}</b><div style={{marginTop:4,color:MUTED,fontSize:13,fontWeight:700}}>{l}</div></div>)}</div>
 <section style={card}><div><div style={{fontSize:12,letterSpacing:".14em",color:GOLD_DARK,fontWeight:900}}>PROPERTY-BOUND EXPENSE</div><h2 style={{margin:"6px 0",color:INK}}>Add hospitality expense</h2></div><form onSubmit={submitExpense} className="hf-form">
  <label style={label}>Property / Apartment *<select name="propertyId" required style={input} defaultValue={propertyId||""} disabled={Boolean(propertyId)}><option value="" disabled>Select property</option>{expenseData.properties.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
  <label style={label}>Category<select name="categoryId" style={input} defaultValue=""><option value="">Uncategorized</option>{expenseData.categories.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label style={label}>Vendor<select name="vendorId" style={input} defaultValue=""><option value="">No vendor</option>{expenseData.vendors.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label style={label}>Invoice #<input name="invoiceNumber" style={input}/></label><label style={label}>Expense type<select name="invoiceType" style={input} defaultValue="vendor_bill"><option value="vendor_bill">Vendor bill</option><option value="owner_charge">Owner charge</option><option value="platform_fee">Platform fee</option><option value="company_fee">Company fee</option><option value="other">Other</option></select></label><label style={label}>Currency<input name="currency" defaultValue="EGP" maxLength={3} style={input}/></label><label style={label}>Subtotal *<input name="subtotal" type="number" min="0" step="0.01" required style={input}/></label><label style={label}>Tax<input name="tax" type="number" min="0" step="0.01" defaultValue="0" style={input}/></label><label style={label}>Issue date *<input name="issuedAt" type="date" required defaultValue={today} style={input}/></label><label style={label}>Due date<input name="dueAt" type="date" style={input}/></label><label className="hf-span2" style={label}>Invoice / receipt image or PDF<input name="receipt" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" style={input}/></label><label className="hf-span2" style={label}>Notes<textarea name="notes" rows={3} style={input}/></label><div className="hf-span2"><button disabled={saving} style={{...button,opacity:saving?0.65:1,width:"100%"}}>{saving?"Saving…":"Save expense"}</button></div>
 </form></section>
 <section style={card}><div><div style={{fontSize:12,letterSpacing:".14em",color:GOLD_DARK,fontWeight:900}}>VIVIT HOSPITALITY REPORTING</div><h2 style={{margin:"6px 0",color:INK}}>Property expense statement</h2></div><div className="hf-report"><label style={label}>Property<select value={reportProperty} onChange={e=>setReportProperty(e.target.value)} style={input} disabled={Boolean(propertyId)}>{expenseData.properties.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label style={label}>From<input type="date" value={reportFrom} onChange={e=>setReportFrom(e.target.value)} style={input}/></label><label style={label}>To<input type="date" value={reportTo} onChange={e=>setReportTo(e.target.value)} style={input}/></label><button type="button" style={button} onClick={()=>exportReport("xls")}>Excel</button><button type="button" style={{...button,background:INK,color:"#fff"}} onClick={()=>exportReport("pdf")}>PDF</button></div></section>
 {propertyId&&<section><h2 style={{color:INK}}>Property reservation finance</h2><div style={{display:"grid",gap:8}}>{(finance.reservations??[]).map(r=><div key={r.id} className="hf-row" style={card}><span><b>{r.guest_name}</b><br/><small style={{color:MUTED}}>{r.check_in} → {r.check_out} · {r.source} · {r.status}</small></span><span>Gross <b>{r.currency} {Number(r.gross_amount).toLocaleString()}</b></span><span>Fees <b>{r.currency} {(Number(r.platform_fee)+Number(r.company_commission)).toLocaleString()}</b></span><span>Owner net <b>{r.currency} {Number(r.net_owner_amount).toLocaleString()}</b></span></div>)}{!(finance.reservations??[]).length&&<span style={{color:MUTED}}>No financial reservations for this property yet.</span>}</div></section>}
 <section><h2 style={{color:INK}}>Recent property expenses</h2><div style={{display:"grid",gap:8}}>{expenseData.expenses.map(e=><div key={e.id} className="hf-row" style={card}><span><b>{e.property_name}</b><br/><small style={{color:MUTED}}>{e.issued_at} · {e.category_name||e.invoice_type}{e.vendor_name?` · ${e.vendor_name}`:""}</small></span><span>Invoice <b>{e.invoice_number||"—"}</b></span><span>Total <b>{e.currency} {Number(e.total).toLocaleString()}</b></span><span>Receipt <b>{e.receipt_count>0?"Attached":"No receipt"}</b></span></div>)}</div></section>
 {!propertyId&&<section><h2 style={{color:INK}}>Owner statements</h2><div style={{display:"grid",gap:8}}>{finance.statements.map(s=><div key={s.id} className="hf-row" style={card}><span><b>{s.owner_name}</b><br/><small style={{color:MUTED}}>{s.period_start} → {s.period_end}</small></span><span>Gross <b>{s.currency} {Number(s.gross_revenue).toLocaleString()}</b></span><span>Net <b>{s.currency} {Number(s.net_payable).toLocaleString()}</b></span><span>Status <b>{s.status}</b></span></div>)}</div></section>}
 </div>
}
