"use client";
import {FormEvent,useState} from "react";

type Field={name:string;label:string;type?:"text"|"number"|"date"|"email";required?:boolean;placeholder?:string};
export function JsonMutationForm({endpoint,title,submitLabel="Save",fields,tone="group"}:{endpoint:string;title:string;submitLabel?:string;fields:Field[];tone?:"hospitality"|"tech"|"group"}){
 const [busy,setBusy]=useState(false);const [message,setMessage]=useState<string>("");
 const accent=tone==="hospitality"?"#d6ad5b":tone==="tech"?"#42adf5":"#a78bfa";
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const form=new FormData(e.currentTarget);const payload:Record<string,unknown>={};for(const f of fields){const raw=String(form.get(f.name)??"");payload[f.name]=f.type==="number"?Number(raw):raw}try{const res=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(body.error||`Request failed (${res.status})`);setMessage("Saved successfully");e.currentTarget.reset();window.location.reload()}catch(err){setMessage(err instanceof Error?err.message:"Request failed")}finally{setBusy(false)}}
 return <form onSubmit={submit} style={{padding:20,border:"1px solid #2a3340",borderRadius:20,background:"rgba(255,255,255,.03)",display:"grid",gap:12}}><h3 style={{margin:0,fontSize:18}}>{title}</h3><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10}}>{fields.map(f=><label key={f.name} style={{display:"grid",gap:6,fontSize:12,fontWeight:800}}>{f.label}<input name={f.name} type={f.type||"text"} required={f.required} placeholder={f.placeholder} style={{padding:"11px 12px",borderRadius:12,border:"1px solid #374151",background:"#0b1119",color:"#fff"}}/></label>)}</div><button disabled={busy} style={{justifySelf:"start",padding:"11px 16px",borderRadius:999,border:0,background:accent,color:"#071018",fontWeight:900,cursor:"pointer",opacity:busy?.6:1}}>{busy?"Saving…":submitLabel}</button>{message?<div role="status" style={{fontSize:12,color:message==="Saved successfully"?"#86efac":"#fca5a5"}}>{message}</div>:null}</form>
}
