"use client";
import {FormEvent,useEffect,useState} from "react";

type Client={id:string;company_name:string;contact_name?:string|null;email?:string|null};
function errorMessage(body:unknown,fallback:string){if(body&&typeof body==="object"){const error=(body as Record<string,unknown>).error;if(typeof error==="string")return error;if(error&&typeof error==="object"&&typeof (error as Record<string,unknown>).message==="string")return String((error as Record<string,unknown>).message)}return fallback}
const fieldStyle:React.CSSProperties={width:"100%",boxSizing:"border-box",minWidth:0,padding:"12px 13px",borderRadius:12,border:"1px solid #cfd6df",background:"#fff",color:"#111827",fontSize:16};
const labelStyle:React.CSSProperties={display:"grid",gap:6,minWidth:0,fontSize:12,fontWeight:800,color:"#1f2937"};
export function TechProjectCreatePanel(){
 const[clients,setClients]=useState<Client[]>([]),[clientId,setClientId]=useState(""),[busy,setBusy]=useState(false),[clientBusy,setClientBusy]=useState(false),[message,setMessage]=useState(""),[clientMessage,setClientMessage]=useState("");
 async function loadClients(){const res=await fetch("/api/vgroup/tech/clients",{cache:"no-store"});const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(errorMessage(body,"Could not load Tech clients."));const next=Array.isArray(body.clients)?body.clients as Client[]:[];setClients(next);setClientId(current=>current||next[0]?.id||"")}
 useEffect(()=>{let active=true;fetch("/api/vgroup/tech/clients",{cache:"no-store"}).then(async res=>{const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(errorMessage(body,"Could not load Tech clients."));return Array.isArray(body.clients)?body.clients as Client[]:[]}).then(next=>{if(!active)return;setClients(next);setClientId(current=>current||next[0]?.id||"")}).catch(e=>{if(active)setMessage(e instanceof Error?e.message:"Could not load Tech clients.")});return()=>{active=false}},[]);
 async function createClient(event:FormEvent<HTMLFormElement>){event.preventDefault();setClientBusy(true);setClientMessage("");const form=new FormData(event.currentTarget);const payload={companyName:String(form.get("companyName")||""),contactName:String(form.get("contactName")||""),email:String(form.get("email")||""),phone:String(form.get("phone")||"")};try{const res=await fetch("/api/vgroup/tech/clients",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(errorMessage(body,"Could not create client."));const created=body.client as Client;await loadClients();setClientId(created.id);setClientMessage(`Client ${created.company_name} created and selected.`);event.currentTarget.reset()}catch(e){setClientMessage(e instanceof Error?e.message:"Could not create client.")}finally{setClientBusy(false)}}
 async function createProject(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!clientId){setMessage("Create or select a client first.");return}setBusy(true);setMessage("");const form=new FormData(event.currentTarget);const payload={clientId,name:String(form.get("name")||""),projectType:String(form.get("projectType")||"custom"),basePrice:Number(form.get("basePrice")||0),plannedStart:String(form.get("plannedStart")||""),plannedEnd:String(form.get("plannedEnd")||"")};try{const res=await fetch("/api/vgroup/tech/projects",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(errorMessage(body,"Could not create project."));setMessage("Project created successfully.");event.currentTarget.reset();window.location.reload()}catch(e){setMessage(e instanceof Error?e.message:"Could not create project.")}finally{setBusy(false)}}
 return <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(330px,100%),1fr))",gap:16,minWidth:0}}>
  <form onSubmit={createClient} style={{padding:20,border:"1px solid #d7dde7",borderRadius:20,background:"#fff",display:"grid",gap:12,color:"#111827",minWidth:0}}><div><div style={{fontSize:11,fontWeight:900,letterSpacing:".12em",color:"#2877b5"}}>TECH CLIENT</div><h3 style={{margin:"4px 0 0"}}>Add client</h3></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(170px,100%),1fr))",gap:10}}><label style={labelStyle}>Company name *<input name="companyName" required style={fieldStyle}/></label><label style={labelStyle}>Contact name<input name="contactName" style={fieldStyle}/></label><label style={labelStyle}>Email<input name="email" type="email" style={fieldStyle}/></label><label style={labelStyle}>Phone<input name="phone" style={fieldStyle}/></label></div><button disabled={clientBusy} style={{justifySelf:"start",border:0,borderRadius:999,padding:"11px 16px",background:"#5aade9",color:"#08131f",fontWeight:900}}>{clientBusy?"Creating…":"Add client"}</button>{clientMessage&&<div role="status" style={{fontSize:13,fontWeight:700,color:clientMessage.includes("created")?"#166534":"#b42318",overflowWrap:"anywhere"}}>{clientMessage}</div>}</form>
  <form onSubmit={createProject} style={{padding:20,border:"1px solid #d7dde7",borderRadius:20,background:"#fff",display:"grid",gap:12,color:"#111827",minWidth:0}}><div><div style={{fontSize:11,fontWeight:900,letterSpacing:".12em",color:"#2877b5"}}>TECH PROJECT</div><h3 style={{margin:"4px 0 0"}}>Create project</h3></div><label style={labelStyle}>Client *<select value={clientId} onChange={e=>setClientId(e.target.value)} required style={fieldStyle}><option value="">Select client</option>{clients.map(client=><option key={client.id} value={client.id}>{client.company_name}{client.email?` · ${client.email}`:""}</option>)}</select></label><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(170px,100%),1fr))",gap:10}}><label style={labelStyle}>Project name *<input name="name" required style={fieldStyle}/></label><label style={labelStyle}>Project type<select name="projectType" defaultValue="custom" style={fieldStyle}><option value="custom">Custom</option><option value="website">Website</option><option value="mobile_app">Mobile app</option><option value="system">System</option><option value="saas_implementation">SaaS implementation</option><option value="other">Other</option></select></label><label style={labelStyle}>Base price *<input name="basePrice" type="number" min="0" step="0.01" required style={fieldStyle}/></label><label style={labelStyle}>Planned start<input name="plannedStart" type="date" style={fieldStyle}/></label><label style={labelStyle}>Planned end<input name="plannedEnd" type="date" style={fieldStyle}/></label></div><button disabled={busy} style={{justifySelf:"start",border:0,borderRadius:999,padding:"11px 16px",background:"#5aade9",color:"#08131f",fontWeight:900}}>{busy?"Creating…":"Create project"}</button>{message&&<div role="status" style={{fontSize:13,fontWeight:700,color:message.includes("successfully")?"#166534":"#b42318",overflowWrap:"anywhere"}}>{message}</div>}</form>
 </div>
}