"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";

type Capability={key:string;workspace:string;label:string;risk:string;approvalRequired:boolean;enabled:boolean;integrationRequired?:boolean};
type Task={id:string;actor_user_id:string;workspace_code:string;capability_key:string;status:string;risk_level:string;idempotency_key?:string;error_code?:string|null;approved_at?:string|null;started_at?:string|null;completed_at?:string|null;created_at:string};
type Event={id:string;task_id:string;actor_user_id:string|null;event_type:string;metadata_redacted:unknown;created_at:string};
type Data={canApprove:boolean;capabilities:Capability[];tasks:Task[];events:Event[]};

export function VivitoControlPanel({initialWorkspace}:{initialWorkspace?:string}){
 const[data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[message,setMessage]=useState(""),[busyTask,setBusyTask]=useState("");
 const[capability,setCapability]=useState(""),[payload,setPayload]=useState("{}"),[idempotency,setIdempotency]=useState(""),[expanded,setExpanded]=useState<string>("");
 const load=()=>fetch("/api/vgroup/vivito/tasks",{cache:"no-store"}).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body?.error?.message||"Failed to load Vivito");setData(body)}).catch(e=>setError(e instanceof Error?e.message:"Failed to load Vivito capabilities"));
 useEffect(()=>{void load()},[]);
 const caps=(data?.capabilities??[]).filter(c=>!initialWorkspace||c.workspace===initialWorkspace);
 const eventMap=useMemo(()=>{const map=new Map<string,Event[]>();for(const event of data?.events??[]){const list=map.get(event.task_id)??[];list.push(event);map.set(event.task_id,list)}return map},[data]);
 async function submit(dryRun:boolean){setError("");setMessage("");let parsed:unknown;try{parsed=JSON.parse(payload)}catch{setError("Payload must be valid JSON");return}if(!capability){setError("Choose a capability");return}const key=idempotency||`vivito-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;const r=await fetch("/api/vgroup/vivito/tasks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({capabilityKey:capability,idempotencyKey:key,payload:parsed,dryRun})});const body=await r.json();if(!r.ok){setError(body?.error?.message||"Vivito request failed");return}setMessage(dryRun?"Preflight passed. Nothing was changed.":body.approvalRequired?"Task queued and is waiting for approval.":"Task executed.");setIdempotency(key);await load()}
 async function decide(taskId:string,decision:"approve"|"reject"){setError("");setMessage("");const reason=decision==="reject"?window.prompt("Rejection reason (optional)")??"":"";setBusyTask(taskId);try{const r=await fetch(`/api/vgroup/vivito/tasks/${taskId}/decision`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({decision,reason})});const body=await r.json();if(!r.ok){setError(body?.error?.message||"Vivito decision failed");return}setMessage(decision==="approve"?"Task approved and execution completed/started according to policy.":"Task rejected.");await load()}finally{setBusyTask("")}}
 function onSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();void submit(false)}
 return <div style={{display:"grid",gap:18}}>
  <section style={{padding:20,border:"1px solid #2d3748",borderRadius:20,background:"rgba(255,255,255,.035)"}}><h2 style={{marginTop:0}}>Execution console</h2><p style={{color:"#9aa8ba",lineHeight:1.6}}>Vivito can only use registered capabilities. Sensitive actions stop for approval; Marketing execution stays locked until the controlled integration.</p><form style={{display:"grid",gap:10}} onSubmit={onSubmit}><select required value={capability} onChange={e=>setCapability(e.target.value)} style={{padding:12,borderRadius:12}}><option value="">Choose capability</option>{caps.map(c=><option key={c.key} value={c.key} disabled={!c.enabled}>{c.label} · {c.workspace} · {c.risk}{c.integrationRequired?" · integration required":""}</option>)}</select><textarea rows={8} value={payload} onChange={e=>setPayload(e.target.value)} spellCheck={false} style={{padding:12,borderRadius:12,fontFamily:"monospace"}}/><input value={idempotency} onChange={e=>setIdempotency(e.target.value)} placeholder="Idempotency key (auto-generated if empty)" style={{padding:12,borderRadius:12}}/><div style={{display:"flex",gap:9,flexWrap:"wrap"}}><button type="button" onClick={()=>void submit(true)} style={{padding:"11px 15px",borderRadius:12}}>Dry run</button><button type="submit" style={{padding:"11px 15px",borderRadius:12,fontWeight:900}}>Execute / Queue</button></div></form>{error&&<p style={{color:"#fca5a5"}}>{error}</p>}{message&&<p style={{color:"#86efac"}}>{message}</p>}</section>
  <section><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><h2>Recent Vivito tasks</h2><button type="button" onClick={()=>void load()} style={{padding:"8px 12px",borderRadius:10}}>Refresh</button></div><div style={{display:"grid",gap:8}}>{(data?.tasks??[]).map(t=>{const events=eventMap.get(t.id)??[];const open=expanded===t.id;return <article key={t.id} style={{padding:14,border:"1px solid #273244",borderRadius:14,display:"grid",gap:10}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><span><b>{t.capability_key}</b><br/><small>{t.workspace_code} · {t.risk_level} · {new Date(t.created_at).toLocaleString()}</small></span><strong>{t.status}</strong></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button type="button" onClick={()=>setExpanded(open?"":t.id)} style={{padding:"7px 10px",borderRadius:9}}>{open?"Hide history":"View history"}</button>{data?.canApprove&&t.status==="waiting_approval"&&<><button disabled={busyTask===t.id} type="button" onClick={()=>void decide(t.id,"approve")} style={{padding:"7px 10px",borderRadius:9,fontWeight:900}}>Approve</button><button disabled={busyTask===t.id} type="button" onClick={()=>void decide(t.id,"reject")} style={{padding:"7px 10px",borderRadius:9}}>Reject</button></>}</div>{open&&<div style={{borderTop:"1px solid #273244",paddingTop:10,display:"grid",gap:6}}>{events.length===0?<small style={{color:"#9aa8ba"}}>No events recorded.</small>:events.map(e=><div key={e.id} style={{fontSize:12,color:"#b9c5d5"}}><b>{e.event_type}</b> · {new Date(e.created_at).toLocaleString()}</div>)}{t.error_code&&<small style={{color:"#fca5a5"}}>Error: {t.error_code}</small>}</div>}</article>})}</div></section>
 </div>
}
