export const dynamic="force-dynamic";
import { auth } from "@/lib/auth";
import { redirect } from "next/navigation";
import { db,clients,creativeTasks,salesLeads,mediaMetrics,financeRecords,users } from "@/lib/db";
import { eq,and,gte,count,sum,notInArray } from "drizzle-orm";
import { Role } from "@/lib/types";
const money=(n:number)=>`EGP ${new Intl.NumberFormat("en-US",{maximumFractionDigits:0}).format(Number(n||0))}`;
export default async function KPIPage(){const session=await auth();if(!session?.user)redirect("/login");if((session.user as any).role!==Role.SUPER_ADMIN)redirect("/dashboard");const now=new Date(),monthStart=new Date(now.getFullYear(),now.getMonth(),1),y=now.getFullYear();const [clientsN,media,finance,creativeN,creativeDone,leadsN,won,lost,team]=await Promise.all([
 db.select({n:count()}).from(clients).where(eq(clients.isActive,true)),db.select({spend:sum(mediaMetrics.adSpend),revenue:sum(mediaMetrics.revenue),leads:sum(mediaMetrics.leads)}).from(mediaMetrics).where(gte(mediaMetrics.date,monthStart)),db.select({total:sum(financeRecords.totalRevenue),paid:sum(financeRecords.paid),outstanding:sum(financeRecords.outstanding)}).from(financeRecords).where(eq(financeRecords.year,y)),db.select({n:count()}).from(creativeTasks).where(gte(creativeTasks.createdAt,monthStart)),db.select({n:count()}).from(creativeTasks).where(and(gte(creativeTasks.createdAt,monthStart),notInArray(creativeTasks.status,["PENDING","IN_PROGRESS","REVIEW","REVISION","REJECTED"]))),db.select({n:count()}).from(salesLeads).where(notInArray(salesLeads.stage,["WON","LOST"])),db.select({n:count()}).from(salesLeads).where(eq(salesLeads.stage,"WON")),db.select({n:count()}).from(salesLeads).where(eq(salesLeads.stage,"LOST")),db.select({n:count()}).from(users).where(eq(users.isActive,true))]);
 const m=media[0]||{},f=finance[0]||{},spend=Number(m.spend||0),rev=Number(m.revenue||0),leads=Number(m.leads||0),total=Number(f.total||0),paid=Number(f.paid||0),out=Number(f.outstanding||0),creativeTotal=Number(creativeN[0]?.n||0),creativeCompleted=Number(creativeDone[0]?.n||0),wonN=Number(won[0]?.n||0),lostN=Number(lost[0]?.n||0),collection=total?paid/total*100:0,completion=creativeTotal?creativeCompleted/creativeTotal*100:0,win=(wonN+lostN)?wonN/(wonN+lostN)*100:0,roas=spend?rev/spend:0,cpl=leads?spend/leads:0,health=Math.round((Math.min(collection,100)+Math.min(completion,100)+Math.min(win,100))/3);
 const metrics=[{l:"Agency Health",v:`${health}%`,s:"Collection + creative + sales"},{l:"Collection Rate",v:`${collection.toFixed(0)}%`,s:`${money(out)} outstanding`},{l:"Creative Completion",v:`${completion.toFixed(0)}%`,s:`${creativeCompleted}/${creativeTotal} this month`},{l:"Sales Win Rate",v:`${win.toFixed(0)}%`,s:`${wonN} won · ${lostN} lost`},{l:"ROAS",v:`${roas.toFixed(2)}x`,s:`Spend ${money(spend)}`},{l:"CPL",v:leads?money(cpl):"—",s:`${leads} leads`},{l:"Active Clients",v:String(clientsN[0]?.n||0),s:"Live accounts"},{l:"Active Team",v:String(team[0]?.n||0),s:"All active users"}];
 return <div style={{display:"flex",flexDirection:"column",gap:18}}><div><h1 className="page-title">KPIs & BI</h1><p className="page-subtitle">A compact live scorecard for agency health and operating performance</p></div><section className="card" style={{background:"linear-gradient(135deg,rgba(124,58,237,.10),rgba(197,42,49,.08))",borderTop:"3px solid #7C3AED"}}><div className="card-body" style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"center",flexWrap:"wrap"}}><div><p style={{fontSize:11,color:"var(--text-muted)",fontWeight:800,textTransform:"uppercase"}}>Overall Agency Health</p><b style={{fontSize:48,color:health>=75?"var(--green)":health>=50?"var(--amber)":"var(--red)"}}>{health}%</b></div><div style={{display:"flex",gap:18,flexWrap:"wrap"}}><Mini l="Collection" v={collection}/><Mini l="Creative" v={completion}/><Mini l="Sales" v={win}/></div></div></section><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:12}}>{metrics.map(x=><div className="card" key={x.l}><div className="card-body"><p style={{fontSize:11,fontWeight:800,textTransform:"uppercase",color:"var(--text-muted)"}}>{x.l}</p><b style={{display:"block",fontSize:24,marginTop:5}}>{x.v}</b><p style={{fontSize:11.5,color:"var(--text-muted)",marginTop:4}}>{x.s}</p></div></div>)}</div></div>}
function Mini({l,v}:{l:string;v:number}){return <div style={{minWidth:100,textAlign:"center",padding:10,borderRadius:12,background:"var(--card-bg)",border:"1px solid var(--card-border)"}}><b style={{fontSize:22}}>{v.toFixed(0)}%</b><p style={{fontSize:10.5,color:"var(--text-muted)"}}>{l}</p></div>}
