export const dynamic="force-dynamic";export const maxDuration=120;
import {NextRequest,NextResponse} from "next/server";import {db,sql} from "@/lib/db";const WS="default";
function authorized(req:NextRequest){const secret=process.env.CRON_SECRET;if(!secret)return process.env.NODE_ENV!=="production";return req.headers.get("authorization")===`Bearer ${secret}`}
async function notify(userId:string,type:string,title:string,message:string,link:string,priority="normal"){const recent=await db.execute(sql`select id from notifications where user_id=${userId} and type=${type} and title=${title} and created_at>now()-interval '18 hours' limit 1`);if(Array.from(recent as any).length)return false;await db.execute(sql`insert into notifications(id,user_id,type,title,message,link,is_read,priority,created_at) values(${crypto.randomUUID()},${userId},${type},${title},${message},${link},false,${priority},now())`);return true}
export async function GET(req:NextRequest){if(!authorized(req))return NextResponse.json({error:"Unauthorized"},{status:401});let created=0;const admins=Array.from(await db.execute(sql`select id from users where workspace_id=${WS} and role='SUPER_ADMIN' and is_active=true`) as any) as any[],accountants=Array.from(await db.execute(sql`select id from users where workspace_id=${WS} and role='ACCOUNTANT' and is_active=true`) as any) as any[];
 const overdue=Array.from(await db.execute(sql`select t.id,t.title,t.deadline,t.assigned_to_id,c.company_name,c.account_manager_id,c.media_buyer_id from creative_tasks t join clients c on c.id=t.client_id where t.workspace_id=${WS} and t.archived_at is null and c.is_active=true and t.status not in ('COMPLETED','APPROVED','REJECTED') and t.deadline<now() order by t.deadline asc limit 40`) as any) as any[];for(const t of overdue){for(const uid of new Set([t.assigned_to_id,t.account_manager_id,t.media_buyer_id,...admins.map(a=>a.id)].filter(Boolean)))if(await notify(String(uid),"AI_TASK_RISK",`Overdue · ${t.company_name}`,`${t.title} passed its deadline. Resolve the blocker or re-plan delivery.`,`/dashboard/creative/${t.id}`,"high"))created++}
 const media=Array.from(await db.execute(sql`select ac.id,ac.name,c.company_name,c.account_manager_id,c.media_buyer_id,coalesce((ac.reported_metrics->>'spend')::numeric,0) spend,coalesce((ac.reported_metrics->>'results')::numeric,0) results,ac.reported_result_label from ad_campaigns ac join clients c on c.id=ac.client_id where ac.workspace_id=${WS} and c.is_active=true and ac.archived_at is null and ac.status='ACTIVE' and coalesce((ac.reported_metrics->>'spend')::numeric,0)>=500 and coalesce((ac.reported_metrics->>'results')::numeric,0)=0 limit 30`) as any) as any[];for(const m of media){for(const uid of new Set([m.account_manager_id,m.media_buyer_id,...admins.map(a=>a.id)].filter(Boolean)))if(await notify(String(uid),"AI_MEDIA_RISK",`Media attention · ${m.company_name}`,`${m.name} spent ${Number(m.spend).toFixed(0)} EGP with 0 ${m.reported_result_label||"primary results"}. Review tracking, creative and delivery before scaling.`,`/dashboard/media/control-center`,"high"))created++}
 const due=Array.from(await db.execute(sql`select c.company_name,c.account_manager_id,p.amount_remaining outstanding,p.payment_status,p.payment_day from client_payment_profiles p join clients c on c.id=p.client_id where c.workspace_id=${WS} and c.is_active=true and coalesce(p.amount_remaining,0)>0 order by p.amount_remaining desc limit 30`) as any) as any[];for(const p of due){for(const uid of new Set([p.account_manager_id,...admins.map(a=>a.id),...accountants.map(a=>a.id)].filter(Boolean)))if(await notify(String(uid),"AI_COLLECTION",`Collection · ${p.company_name}`,`${Number(p.outstanding).toLocaleString("en-EG")} EGP outstanding · payment day ${p.payment_day||"not set"}. Prepare the next collection follow-up.`,`/dashboard/clients/accounts-payment`,Number(p.outstanding)>=25000?"high":"normal"))created++}
 return NextResponse.json({ok:true,created,scanned:{overdue:overdue.length,media:media.length,collections:due.length},at:new Date().toISOString()})}
