export const dynamic="force-dynamic";
import {auth} from "@/lib/auth";
import {redirect} from "next/navigation";
import {db,clients,financeRecords,workspaces} from "@/lib/db";
import {eq,sum,count,and} from "drizzle-orm";
import {Role} from "@/lib/types";
import Link from "next/link";

export default async function LTVPage(){const session=await auth();if(!session?.user)redirect("/login");const workspaceId=String(session.user.workspaceId||"");if(!workspaceId)redirect("/login");if(![Role.SUPER_ADMIN,Role.ACCOUNTANT].includes(session.user.role))redirect("/dashboard");const [allClients,revenueByClient,ws]=await Promise.all([db.select().from(clients).where(and(eq(clients.workspaceId,workspaceId),eq(clients.isActive,true))).orderBy(clients.companyName),db.select({clientId:financeRecords.clientId,totalPaid:sum(financeRecords.paid),months:count()}).from(financeRecords).where(eq(financeRecords.workspaceId,workspaceId)).groupBy(financeRecords.clientId),db.select({currency:workspaces.currency}).from(workspaces).where(eq(workspaces.id,workspaceId)).then(r=>r[0])]),currency=ws?.currency||"EGP",money=(n:number)=>{try{return new Intl.NumberFormat("en-EG",{style:"currency",currency,maximumFractionDigits:0}).format(Number(n||0))}catch{return `${Number(n||0).toLocaleString()} ${currency}`}},revenueMap=new Map(revenueByClient.map(r=>[r.clientId,r])),data=allClients.map(c=>{const agg=revenueMap.get(c.id),ltv=Number(agg?.totalPaid||0),months=Number(agg?.months||0),avgMonthly=months>0?ltv/months:Number(c.monthlyRetainer||0),contractMonthsLeft=c.contractEnd?Math.max(0,Math.ceil((new Date(c.contractEnd).getTime()-Date.now())/(30*86400000))):0,riskFactor=c.churnRisk==="HIGH"?.4:c.churnRisk==="MEDIUM"?.7:.9,predictedLTV=ltv+(avgMonthly*contractMonthsLeft*riskFactor);return {client:c,ltv,months,avgMonthly,contractMonthsLeft,predictedLTV}}).sort((a,b)=>b.ltv-a.ltv),total=data.reduce((s,d)=>s+d.ltv,0),avg=data.length?total/data.length:0,top=data.slice(0,Math.max(0,Math.ceil(data.length*.2))),topRevenue=top.reduce((s,d)=>s+d.ltv,0),share=total?Math.round(topRevenue/total*100):0,max=Math.max(...data.map(d=>d.ltv),1);
return <div style={{display:"flex",flexDirection:"column",gap:18}}><div><h1 className="page-title">Client Lifetime Value</h1><p className="page-subtitle">LTV to date is actual collected revenue. Future LTV is a planning estimate using remaining contracted months, average collected monthly value and churn-risk factor.</p></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12}}>{[{l:"Collected LTV",v:money(total)},{l:"Average LTV",v:money(avg)},{l:"Top 20% Share",v:data.length?`${share}%`:"—"},{l:"Active Clients",v:String(allClients.length)}].map(k=><div className="card" key={k.l}><div className="card-body"><p style={{fontSize:11,color:"var(--text-muted)",fontWeight:800}}>{k.l}</p><b style={{fontSize:24,display:"block",marginTop:5}}>{k.v}</b></div></div>)}</div>{!data.length?<div className="card"><div className="card-body" style={{textAlign:"center",color:"var(--text-muted)"}}>No active clients are available for LTV analysis.</div></div>:<section className="card"><div className="card-header"><p className="card-title">Client LTV Ranking</p><span className="badge badge-gray">{data.length} clients</span></div><div className="card-body-flush">{data.map((d,i)=><div key={d.client.id} style={{padding:14,borderBottom:"1px solid var(--card-border)",display:"grid",gridTemplateColumns:"minmax(180px,1.4fr) repeat(3,minmax(100px,.7fr))",gap:12,alignItems:"center"}}><div><Link href={`/dashboard/clients/${d.client.id}`} style={{fontWeight:800,textDecoration:"none",color:"inherit"}}>#{i+1} {d.client.companyName}</Link><div style={{height:5,borderRadius:6,background:"var(--bg-tertiary)",marginTop:7}}><div style={{height:5,borderRadius:6,width:`${Math.round(d.ltv/max*100)}%`,background:"var(--vivit-blue)"}}/></div></div><div><b>{money(d.ltv)}</b><small style={{display:"block",color:"var(--text-muted)"}}>actual collected</small></div><div><b>{money(d.predictedLTV)}</b><small style={{display:"block",color:"var(--text-muted)"}}>estimated total</small></div><div><b>{d.contractMonthsLeft} mo</b><small style={{display:"block",color:"var(--text-muted)"}}>contract remaining</small></div></div>)}</div></section>}</div>}
